### ISSUE TITLE
Automatically resolve DNS names of Kubernetes services at host

### ISSUE THREAD

**Issue by wideawakening** [ubuntu/microk8s#1005]
Hi! First would like to thank you for the awesome job you're doing. Working with microk8s is being a nice learning path for starters.

Don't know the technical implications, but is there any way to have the k8s service dns' resolved at host machine, similar to how kubefwd performs? Guess it would imply "su" permissions, but would be very helpful for local development when IPs may be shifting.

My current workaround is:
```
$ microk8s.config > ~/.kube/config 
$ sudo kubefwd svc -n {namespace} -x microk8s
```

**Comment by balchua** [comment]
I usually just use `kubectl -n mynamespace port-forward svc/theservice 9411:9411`
And then i access it like localhost:9411.
Is this what you're looking for?

Sorry i dont know kubefwd. 😁

**Comment by wideawakening** [comment]
``port-forward`` may be helpful for just one/two services, but when dealing with multiple, it becomes non agile. I'm looking to provide several services for development environment, as transparent as possible, and [kubefwd](https://github.com/txn2/kubefwd) has been my tool of choice before.

Besides, using "localhost" as service name, gives no identity to the service itself (its more the port who provides it). Dealing with kubernetes DNS names makes more sense.

**Comment by balchua** [comment]
Yes you're right. I will check out kubefwd thanks.  I believe kubefwd also uses the KUBECONFIG thats why you need to export the config using microk8s.config.
By default microk8s doesnt export it.  So you're all good.

**Comment by balchua** [comment]
Oh another thing that i use without mucking with my `/etc/host`..  install an ingress controller and use the service `http://xip.io` or `https://nip.io/`. Check that out too.

**Comment by strigona-worksight** [comment]
I've had limited success with pointing my PC's DNS at the DNS server inside microk8s. I'm not doing that at the moment... currently I'm just messing with my `/etc/hosts` file which works, but is a bit of a pain as well.
