### ISSUE TITLE
issue with etcd and microk8s timeouts

### ISSUE THREAD

**Issue by srinikrev** [ubuntu/microk8s#1008]
Hi all,
Snap changes output:

snap changes microk8s
ID   Status  Spawn               Ready               Summary
32   Error   today at 18:21 IST  today at 18:36 IST  Auto-refresh snaps "core", "microk8s", "code"
33   Done    today at 19:38 IST  today at 19:38 IST  Running service command

Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20200304_184552.tar.gz](https://github.com/ubuntu/microk8s/files/4287786/inspection-report-20200304_184552.tar.gz)

**Comment by balchua** [comment]
I can see that the cluster was upgraded and then downgraded. Due to this log in the etcd
`cluster cannot be downgraded...`
Microk8s upgraded etcd (i think in stable channel).
Did you know if this setup of yours was previously in the stable or edge channel and then you refreshed it to 1.17/stable?
