### ISSUE TITLE
Failed to enable helm

### ISSUE THREAD

**Issue by ghost** [ubuntu/microk8s#1009]
When running `microk8s.enable helm` on edge channel I get the following output:
```
Enabling Helm
Fetching helm version v2.16.0.
/snap/microk8s/1245/actions/enable.helm.sh: line 17: cd: /var/snap/microk8s/1245/tmp/helm: Permission denied
Failed to enable helm
```

**Comment by balchua** [comment]
Hi did you add your user to the `microk8s` group prior to enabling helm? Like described in the docs?
`sudo usermod -a -G microk8s $USER`.

When you add your user, you may have to relogin.

**Comment by nnewc** [comment]
Good thought, but yes I have already done that.

**Comment by nnewc** [comment]
I am behind a corporate HTTPS proxy. Is it possible to use my ca bundle in /etc/ssl/certs/ca-certificates.crt?

**Comment by ktsakalozos** [comment]
@nnewc I suspect the umask of the sudo user is something like 027 and this is why when the tmp directory is created does not get the permission of 'r-x' on the others. I suspect that you first created the `tmp` directory as sudoer via a `microk8s.enable` command, then you added your self in the `microk8s` group and tried to enable helm.

The obvious workaround is to enable helm with helm or change the permissions of the path.

A proper fix would be to review the addons and make sure when directories are created and files are moved to set the owner to "root:microk8s". No ETA for this yet.

**Comment by anushkrishnav** [comment]
I am intrested

**Comment by nwneisen** [comment]
Hello,

I wanted to take a look at this but I was not able to reproduce the original error. These are the steps I followed:

Install microk8s from the edge channel:
`sudo snap install microk8s --classic --channel=edge`

Enabled the helm addon:
`microk8s.enable helm`

I get output that helm was successfully enabled:
```
Enabling Helm
Fetching helm version v2.16.7.
...
Helm is enabled
```

Was this issue fixed at some point and this issue can be closed?

Thanks!

**Comment by ktsakalozos** [comment]
I suspect this is a matter of when the user is added to the microk8s group. Maybe if you first enable helm with `sudo mcirok8s enable helm` and then add your user in the microk8s group the files used by helm will be owned by root.

**Comment by nwneisen** [comment]
I removed my user from the `microk8s` group and then logged out and back in. I walked through the same steps as I mentioned above except I used `sudo` to enable helm. I'm getting the following directories:

```
drwxrwx--- 3 root microk8s 4096 Sep 27 19:09 args
drwxr-xr-x 2 root root     4096 Sep 27 19:16 bin
drwxrwx--- 2 root microk8s 4096 Sep 27 19:17 certs
drwxrwx--- 2 root microk8s 4096 Sep 27 19:03 credentials
drwxrwx--- 3 root microk8s 4096 Sep 27 19:03 juju
drwxrwx--- 2 root microk8s 4096 Sep 27 19:03 juju-home
drwxr-xr-x 3 root root     4096 Sep 27 19:03 opt
drwxr-xr-x 2 root root     4096 Sep 27 19:16 tmp
drwxr-xr-x 7 root root     4096 Sep 27 19:04 var
```

Once adding my user to the microk8s group, I'm not having any issues enabling and disabling helm. I tried a few variations of the above as well but always got a `tmp` dir with `r-x` premissions.

Could there be another process that first created the `tmp` directory with these permissions such as another package being installed? When the helm package was installed it then ran into the results of that?

**Comment by zmraul** [comment]
Hi, I've managed to reproduce this problem. It does seem to be caused by what @ktsakalozos said. I believe it affects all enable scripts that use the _tmp_ foder.

I'm working on a VM, and I've added to `/etc/sudoers`:
```
Defaults    umask = 0027
Defaults    umask_override
```
Then, I've installed microk8s with `sudo snap install microk8s --classic`. Enabling any addon that creates the tmp folder will lead to this problem:
```bash
$ sudo microk8s enable istio
...
Istio is starting

To configure mutual TLS authentication consult the Istio documentation.
$ sudo usermod -a -G microk8s $USER
---- log out & log in ----
$ microk8s enable helm
Enabling Helm
Fetching helm version v2.16.7.
/snap/microk8s/2948/scripts/wrappers/common/../../../actions/enable.helm.sh: line 17: cd: /var/snap/microk8s/2948/tmp/helm: Permission denied
```

I'll try to create a PR with changes to the affected addons, wich are `cilium`, `helm`, `helm3`, `istio` and `prometheus`.
