### ISSUE TITLE
Certificate Distribution during Cluster Formation

### ISSUE THREAD

**Issue by asergeant01** [ubuntu/microk8s#1011]
**Outline Procedure**
1 Qcow VM image that has micro-k8s installed. There are two nics, one external, one internal.

Image is cloned to produce 3 nodes, k8s-master, k8s-worker-1 and k8s-worker-2
Netplan is used to configure the external interface to dhcp, whilst the internal interface is static (192.168.130.1-3)

/var/snap/microk8s/common/run/flannel/subnet.env is changed so each node's flannel starts on a different subnet.

micro-k8s is then stop and started for the changes to take effect.

**Outcomes**

get nodes - shows all nodes in Ready state.
get pods - shows pods being deployed across all nodes

metallb - accessing load balancer ip for a deployed nginx pod, web page displays.

**Errors**
Trying to port forward - error: error upgrading connection: unable to upgrade connection: Unauthorized
Trying to get logs - error: You must be logged in to the server

The log error happens even for metallb speakers running on worker nodes:
metallb-system   speaker-542sx                             1/1     Running     1          20d   10.55.168.94    k8s-master     <none>           <none>
metallb-system   speaker-9zpzx                             1/1     Running     1          25h   10.55.168.175   k8s-worker-2   <none>           <none>
metallb-system   speaker-vhqxr                             1/1     Running     1          25h   10.55.168.67    k8s-worker-1   <none>           <none>

However master node displays logs correctly.

**Comment by ktsakalozos** [comment]
@asergeant01 how do you form the cluster? Are you doing a `microk8s.add-node`?

**Comment by asergeant01** [comment]
@ktsakalozos Yes.... add-node
