### ISSUE TITLE
How to disable kube-proxy after installing Cilium

### ISSUE THREAD

**Issue by Richard87** [ubuntu/microk8s#1012]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

Hi! I have installed Cilium, and expect it to replace kube-proxy, but both are still running, and flooding iptabels with rules...

I disabled daemon-proxy and stopped it, but it started again after a reboot. Also it didn't clean up any leftover iptables-rules.

Kan we reuse flanneld config to stop daemon-proxy?
```
set_service_not_expected_to_start flanneld
run_with_sudo systemctl stop snap.${SNAP_NAME}.daemon-flanneld
```

```
microk8s.inspect 
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
 FAIL:  Service snap.microk8s.daemon-flanneld is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-flanneld
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1214/inspection-report-20200305_143915.tar.gz

```

**Comment by ktsakalozos** [comment]
At this point there is no way to disable kube-proxy permanently. We did not look into this setup because replacing kube-proxy with cilium requires a kernel newer than a certain version [1]. It is however a great suggestion especialy since we plan to start using cilium as the default cni.  

[1] https://docs.cilium.io/en/v1.7/gettingstarted/kubeproxy-free/

**Comment by matjazp** [comment]
@ktsakalozos any news on how to disable kube-proxy? IS there any way to use Cilium's kube-proxy-free configuration in Microk8s?

**Comment by alphabet5** [comment]
I can't seem to find any other references to disabling kube-proxy. Is this something that won't be added?
