### ISSUE TITLE
Istio: kiali doesn't know grafana and jaeger's URL

### ISSUE THREAD

**Issue by luispabon** [ubuntu/microk8s#1015]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20200305_213043.tar.gz](https://github.com/ubuntu/microk8s/files/4295239/inspection-report-20200305_213043.tar.gz)

Upon enabling istio on microk8s, looks like Kiali's config does not contain the URLs to grafana and jaeger (both services are present and working):

![image](https://user-images.githubusercontent.com/6388823/76027645-e98ec580-5f28-11ea-898a-3ec9299cb275.png)

![image](https://user-images.githubusercontent.com/6388823/76027617-db40a980-5f28-11ea-82a5-99f79dec7bea.png)

**Comment by ktsakalozos** [comment]
Thank you for reporting this @luispabon.

The current istio addon (found https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.istio.sh) deploys the default istio demo setup of v1.3.4. @knkski is working on an updated charmed version of istio. Having kiali configured out of the box is a good suggestion.
