### ISSUE TITLE
metallb pods in CrashLoopBackoff after enable

### ISSUE THREAD

**Issue by davecahill** [ubuntu/microk8s#1017]
I enabled metallb with:
```microk8s.enable metallb```

This appeared successful, however the metallb pods got stuck in CrashLoopBackOff:
```
$ kubectl get pods --namespace=metallb-system
NAME                          READY   STATUS             RESTARTS   AGE
controller-65895b47d4-92zld   0/1     CrashLoopBackOff   1          12s
speaker-cjptj                 0/1     CrashLoopBackOff   1          12s
```

Logs show the same error for both pods:
```
$ kubectl logs controller-65895b47d4-92zld --namespace=metallb-system
standard_init_linux.go:207: exec user process caused "operation not permitted"

$ kubectl logs speaker-cjptj --namespace=metallb-system
standard_init_linux.go:207: exec user process caused "operation not permitted"
```

This issue seemed possibly related: https://github.com/metallb/metallb/issues/21

[inspection-report-20200308_210918.tar.gz](https://github.com/ubuntu/microk8s/files/4303182/inspection-report-20200308_210918.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @davecahill 

I see some kernel problems in your dmesg. This could be potentially related to the issue you are having.

The problem seems similar to https://github.com/ubuntu/microk8s/issues/533. Could you make sure you have your system updated (`apt-get update/upgrade`)? You may also have more luck with other than the generic kernel.

Another suggestion is to remove `allowPrivilegeEscalation: false` from:
```
microk8s.kubectl edit -n metallb-system  deployment/controller
```
as mentioned in https://github.com/ubuntu/microk8s/issues/533#issuecomment-509285866

**Comment by davecahill** [comment]
Thanks @ktsakalozos !

I made the below change, rebuilt the snap, installed it, and disabled / enabled metallb - success! 🎉 
```
--- a/microk8s-resources/actions/metallb.yaml
+++ b/microk8s-resources/actions/metallb.yaml
@@ -13,7 +13,6 @@ metadata:
   name: speaker
   namespace: metallb-system
 spec:
-  allowPrivilegeEscalation: false
   allowedCapabilities:
   - NET_ADMIN
   - NET_RAW
@@ -223,7 +222,6 @@ spec:
             cpu: 100m
             memory: 100Mi
         securityContext:
-          allowPrivilegeEscalation: false
           capabilities:
             add:
             - NET_ADMIN
@@ -279,7 +277,6 @@ spec:
             cpu: 100m
             memory: 100Mi
         securityContext:
-          allowPrivilegeEscalation: false
           capabilities:
             drop:
             - all
```

Is it worth submitting that as a pull request, or do you think the need for this change is specific to my system?

**Comment by ktsakalozos** [comment]
Thank you for spending time to fix this. Yes I think it is worth submitting a PR for this. However since this error is not present everywhere, I would suggest you patch it similar to this: https://github.com/ubuntu/microk8s/pull/551/files

**Comment by davecahill** [comment]
Fixed in https://github.com/ubuntu/microk8s/pull/1028.
