### ISSUE TITLE
Some commands not working with a user in the microk8s group

### ISSUE THREAD

**Issue by mystfox** [ubuntu/microk8s#1023]
Running on a fresh Ubuntu LTS image through multipass, host OS is Windows 10 Pro, using Hyper-V. `microk8s.status`, `microk8s.kubectl` just hang when run as `ubuntu`, even though it's a member of `microk8s`. However, `microk8s.inspect`, `microk8s.stop`, `microk8s.start` at the least work as `ubuntu`. Attached the inspection report, ran as `ubuntu`, from before figuring out that stop and start worked too - but obviously after figuring out that inspect worked:
[inspection-report-20200311_105526.tar.gz](https://github.com/ubuntu/microk8s/files/4319607/inspection-report-20200311_105526.tar.gz)

```
ubuntu@microk8s-vm:~$ microk8s.status
^C
ubuntu@microk8s-vm:~$ id
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),20(dialout),24(cdrom),25(floppy),27(sudo),29(audio),30(dip),44(video),46(plugdev),108(lxd),114(netdev),999(microk8s)
```

**Comment by balchua** [comment]
Can you clean you `~/.kube` and then try again?

**Comment by mystfox** [comment]
> 
> 
> Can you clean you `~/.kube` and then try again?

Ahh, thank you! It was owned by `root`, for whatever reason, and after removing, everything seems to be working fine.

**Comment by ktsakalozos** [comment]
This has cause problems to a lot of our users. I think we should improve our messaging and ask users to set the right permissions to the `.kube` files when adding the user to the microk8s group.
