### ISSUE TITLE
kubeflow ingress/ambassador not found - impossible to open dashboard 

### ISSUE THREAD

**Issue by ricpet** [ubuntu/microk8s#1030]
After installing microk8s and enabling kubeflow, I cannot access its dashboard. There is some issue with the ambassador. If I run:

`microk8s.kubectl edit -n kubeflow ingress/ambassador` I get:
`Error from server (NotFound): ingresses.extensions "ambassador" not found`

The report tarball is available here: https://www.dropbox.com/s/lc62p3zrl7s9w63/inspection-report-20200313_134750.tar.gz?dl=0

**Comment by knkski** [comment]
@ricpet: Can you try rerunning the command with `ingress/ambassador-ingress` instead of `ingress/ambassador`? The name was recently switched to fix another issue.

**Comment by ricpet** [comment]
Great! Thanks @knkski, it works fine now!
