### ISSUE TITLE
Microk8s handling private registries and overriding built-in manifests

### ISSUE THREAD

**Issue by CalvinHartwell** [ubuntu/microk8s#1035]
Hi all, 

Recently we had the requirement to run Microk8s in an airgapped environment and ran into two main issues:

1. We need an easy way to set and configure the registry for containerd, I.E an option like microk8s.registry = <xyz> would be useful for changing the registry globally for microk8s. 

2. We need an easy way to override the registry in each of the manifests used as part of the microk8s.enable, so that we can override this for local, offline use as they currently pull from lots of different registries. In this case we assume a local mirror is available which already has container images already stored for each of the pre-built manifests provided by the microk8s.enable functionality. 

Hopefully that makes sense, feel free to ask any questions. 

Cheers,

- Calvin

**Comment by joedborg** [comment]
Hey @CalvinHartwell,
Option 1 can currently be done via https://microk8s.io/docs/registry-private.  I agree that a CLI option to set would be nicer, but just FYI if you're blocked on it.

Will investigate point 2.  As far as I'm aware, adding a registry as part of point 1 should also impinge upon the addons.  I'll test to confirm.

**Comment by joedborg** [comment]
@CalvinHartwell I've tested this, using the built in registry.  I've enabled the registry addon, pushed the coredns image to it, pulled away the network and then enabled the dns addon; this works fine which leads me to believe a private registry would too.  I'll double check this though.

**Comment by joedborg** [comment]
@CalvinHartwell Just tried this with a private registry in an LXD container (as if it were a corporate one) and it works fine with the steps above.  Please let me know if there's any more to this.
