### ISSUE TITLE
Strict Confinement of microk8s

### ISSUE THREAD

**Issue by mewais** [ubuntu/microk8s#1037]
This is a suggestion/feature request rather than a bug. Apologies if this is not the intended place to talk about it.

Is there anyway to get microk8s with strict confinement? I'm trying to use it on Ubuntu Core 18. Obviously this can't happen with classic confinement.

EDIT:
I keep coming across articles by people in Canonical (like [this one](https://thenewstack.io/how-microk8s-helps-deployment-to-the-internet-of-things/)) saying that microk8s is supposed to receive strict confinement, is there any timeline for this?

**Comment by ktsakalozos** [comment]
Hi @mewais we are actively working on this now. As you understand strict confinement may block some user operations and we are being careful not to hurt the UX.

You can build a strictly confined snap from this branch https://github.com/ubuntu/microk8s/tree/feature/jdb/strict (although at the time of this writing the certificate of https://www.netfilter.org seems to have expired and the build is failing. You can use a mirror in the snapcraft.yaml eg http://www.es.netfilter.org )

**Comment by mewais** [comment]
Thanks a lot, I will definitely give a try to that branch.

**Comment by joedborg** [comment]
FYI the the build steps have also been updated https://github.com/ubuntu/microk8s/blob/feature/jdb/strict/docs/build.md

**Comment by mewais** [comment]
All the netfilter mirrors seem to have the same issue, I still managed to build using download links from ubuntu or fedora. Thank you for your help guys.
