### ISSUE TITLE
microk8s.status breaking change

### ISSUE THREAD

**Issue by TheRealChssAddct** [ubuntu/microk8s#1041]
@balchua @ktsakalozos 
Today's latest/edge channel revision 1278 has a breaking change to existing code for others.

Specifically, this PR https://github.com/ubuntu/microk8s/pull/876 "Make `microk8s.status` addons more readable" is catered to humans and not scripts.

I had in a shell script  this line:
`while ! microk8s.status | grep "storage: enabled" ;do echo "not ready";sleep 2;done` which the PR breaks.

OK. no problem. I can accomodate with this change:
`while ! microk8s.status --addon storage | grep "enabled" ;do echo "not ready";sleep 2;done`
(though unless I now want complex branching logic, I have to not release my change to others in my company who are on latest/stable channel until this PR makes it to latest/stable).

However, I ran into another problem, and that is I'm not the only one checking for the old format of "$addon: enabled".  My script ultimately ends up calling `chectl server:start -p microk8s ...`.  

Eclipse Che's chectl, not my project, checks for storage: enabled and ingress: enabled in the same manner, and now fails in those checks.  I've submitted a bug report to them here: [https://github.com/eclipse/che/issues/16408](https://github.com/eclipse/che/issues/16408)

Might I respectfully request that you maintain the former, simply grep-able presentation, as if it were an api or interface, i.e., a 'contract' that others have built code around (because it is so).  Otherwise, this is a breaking change that forces others to change their code.
  
Two suggestions for making the pretty format available are `-o pretty` or `--pretty` switches.

Thanks.

**Comment by ktsakalozos** [comment]
Hi @TheRealChssAddct 

Thank you for reporting this and for following the edge channel, we really appreciate early feedback.

You are right we should not be changing our interfaces and that includes the CLI.

In https://github.com/ubuntu/microk8s/pull/1042 we have taken corrective action to make sure we maintain the CLI and output we have until now.

`microk8s.status` and `microk8s.status --yaml` have the same output as used to. We introduced a new argument `--format` to which you can pass `pretty` and get the add-ons with their descriptions, or `yaml` to get the new yaml format with the addons and their descriptions in a list.

Apologies for the inconvenience we may have caused.

**Comment by TheRealChssAddct** [comment]
Thanks so much for your very quick turnaround and responsiveness! For readability, I like the new better. For continuity with existing code, I appreciate you keeping the old.

**Comment by TheRealChssAddct** [comment]
> @TheRealChssAddct we postponed the status output update for many months. We will be moving on with the change on the v1.19 release. You can give it a try by installing MicroK8s from the `latest/edge` channel (`sudo snap install microk8s --classic --channel=latest/edge`). The old status format is still available with `microk8s status --format short`.

oh. woops. I didn't see this till today.  I appreciate the heads up. 

I don't agree with the decision to go with the breaking change, but I can accept it.  It's simply a matter of it will break some who use earlier versions of chectl, forcing them to explicitly deal with it somehow, i.e., force a specific earlier version of microk8s, or update to a later version of chectl after it is fixed to work with the breaking change.
