### ISSUE TITLE
microk8s storage creates 777 directories

### ISSUE THREAD

**Issue by darkalia** [ubuntu/microk8s#1045]
Hello,

First, thanks for this tool, it's very handy.

Upon debugging an issue with the storage class and out of curiosity, I checked how it was working a bit behind the scene.
I was a bit surprised to see some directories where created with 777 permissions: https://pastebin.ubuntu.com/p/fMf9frXcgk/

I was wondering what was the rational behind such permissions ?
I couldn't find where the binary used inside docker.io/cdkbot/hostpath-provisioner-amd64:1.0.0 was built so I don't have more context right now but will look more into it later.

[inspection-report-20200320_174320.tar.gz](https://github.com/ubuntu/microk8s/files/4360822/inspection-report-20200320_174320.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @darkalia 

Thank you for looking into this issue. The hostpath provisioner can be found in 
https://github.com/juju-solutions/hostpath-provisioner. Any suggestions and fixes in hardening it are welcomed.

Thank you

**Comment by dmaj** [comment]
I looked at the " hostpath provisioner" code. From my point of view the concept is problematic. The memory and its contents are bound to the instance. If there is a "rescheduling" of a Pod on another node, it will not find the expected memory. 
A bigger problem is also in the code: https://github.com/juju-solutions/hostpath-provisioner/blob/master/hostpath-provisioner.go. Line 88 in this code (if err := os.MkdirAll(path, 0777); err != nil) only works if the "pvc" is created on the machine running the "hostpath provisioner". This line is a local operation. But the mask "777" is necessary if I want to access the pvc as "non-root". This only works correctly if the pvc happens to be on the same machine as the "hostpath provisioner".

This can also be seen if you want to install the "mongodb operator" from " percona" (https://www.percona.com/doc/kubernetes-operator-for-psmongodb/index.html)
I use version 1.17

**Comment by balchua** [comment]
@dmaj you're right, `microk8s.enable storage` is using `hostPath` hence it difficult to use it on a multi node setup.

For multi node microk8s, there's a discussion about using Rook in microk8s here https://github.com/ubuntu/microk8s/issues/885
