### ISSUE TITLE
Multi-node - adding a node fails with no error 

### ISSUE THREAD

**Issue by zerocode** [ubuntu/microk8s#1047]
Attempting to add a node to an existing single node microk8s instance fails (without returning an error message). It seems to kill the dashboard, which fails with the error:

`E0323 21:44:50.086272    2253 portforward.go:233] lost connection to pod` 

Any ideas how to debug this? 

tarballs for both the master (t480s-kubuntu) and node being added (n54) attached.
[inspection-report-20200323_214733.tar.gz](https://github.com/ubuntu/microk8s/files/4369717/inspection-report-20200323_214733.tar.gz)
[inspection-report-20200323_214738.tar.gz](https://github.com/ubuntu/microk8s/files/4369769/inspection-report-20200323_214738.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @zerocode 

On the logs you attached i see a lot of errors regarding the certificates. For example in the flanneld logs:
```
Mar 22 20:14:56 N54 microk8s.daemon-flanneld[22065]: Error:  client: etcd cluster is unavailable or misconfigured; error #0: x509: certificate has expired or is not yet valid
Mar 22 20:14:56 N54 microk8s.daemon-flanneld[22065]: error #0: x509: certificate has expired or is not yet valid
```
Are the machine dates correct, or where they correct when MicroK8s got installed?

Certificates are under `/var/snap/microk8s/current/certs`

**Comment by zerocode** [comment]
Machine dates and certs look ok..

`$ date`
Tue Mar 24 13:54:21 +08 2020

`$ find . -name '*.crt' -exec echo {} \; -exec openssl x509 -subject -dates -issuer -noout -in {} \;`
./kubelet.crt
subject=CN = n54@1584875971
notBefore=Mar 22 10:19:30 2020 GMT
notAfter=Mar 22 10:19:30 2021 GMT
issuer=CN = n54-ca@1584875970
./server.remote.crt
subject=C = US, ST = Isles of Blessed, L = Arkadia, O = acme, OU = dev, CN = 127.0.0.1
notBefore=Mar 23 21:44:50 2020 GMT
notAfter=Jan  6 21:44:50 2294 GMT
issuer=CN = 10.152.183.1
./ca.remote.crt
subject=CN = 10.152.183.1
notBefore=Mar 21 14:19:39 2020 GMT
notAfter=Aug  7 14:19:39 2047 GMT
issuer=CN = 10.152.183.1
./ca.crt
subject=CN = 10.152.183.1
notBefore=Mar 22 11:19:15 2020 GMT
notAfter=Aug  8 11:19:15 2047 GMT
issuer=CN = 10.152.183.1
./front-proxy-client.crt
subject=CN = front-proxy-client
notBefore=Mar 22 11:19:28 2020 GMT
notAfter=Jan  5 11:19:28 2294 GMT
issuer=CN = front-proxy-ca
./front-proxy-ca.crt
subject=CN = front-proxy-ca
notBefore=Mar 22 11:19:15 2020 GMT
notAfter=Aug  8 11:19:15 2047 GMT
issuer=CN = front-proxy-ca
./server.crt
subject=C = US, ST = Isles of Blessed, L = Arkadia, O = acme, OU = dev, CN = 127.0.0.1
notBefore=Mar 22 11:19:28 2020 GMT
notAfter=Jan  5 11:19:28 2294 GMT
issuer=CN = 10.152.183.1

What else should I check?

**Comment by balchua** [comment]
I think your master and the node are not of the same timezone.

For example on the node `N54` apiserver logs, i can see this.
`Active: inactive (dead) since Mon 2020-03-23 21:43:33 +08; 4min 0s ago`

While your master `t480s-kubuntu` apiserver systemctl logs have this.
`Active: active (running) since Mon 2020-03-23 21:44:50 UTC; 2min 41s ago`

One is in `UTC` the other is in `+8`

**Comment by zerocode** [comment]
After a clean reinstall on both machines, fixing the clock issues (one machine is a dual boot Win10/Linux box) and wiping out ~./kube, I now have a working multi-node cluster.
Thanks guys :)
