### ISSUE TITLE
Kubeflow could not be enabled

### ISSUE THREAD

**Issue by SrdjanStevanetic** [ubuntu/microk8s#1050]
Hi all,

After discussion with @knkski I am creating a new error for enabling kubeflow. Namely, I am getting an error for enabling kubeflow on Ubuntu 18.04. The error is:
ERROR cannot deploy bundle: cannot add charm "cs:~kubeflow-charmers/ambassador-54": cannot retrieve charm "cs:~kubeflow-charmers/ambassador-54": cannot get archive: Get https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/ambassador-54/archive?channel=stable: dial tcp: lookup api.jujucharms.com on 10.152.183.10:53: server misbehaving

Command '('microk8s-juju.wrapper', 'deploy', 'cs:kubeflow', '--channel', 'stable', '--overlay', '/tmp/tmpp902pdg2')' returned non-zero exit status 1
Failed to enable kubeflow

I have also executed the following command: KUBEFLOW_DEBUG=true microk8s.enable kubeflow and the output is in the attached file.

Thanks a lot for your time!

[kubeflow-enable-output.txt](https://github.com/ubuntu/microk8s/files/4374079/kubeflow-enable-output.txt)

**Comment by knkski** [comment]
@SrdjanStevanetic: Can you also run `microk8s.inspect` and attach the file that it generates? It looks like the deploy is failing due to an issue with volumes not getting created with microk8s.

**Comment by SrdjanStevanetic** [comment]
@knkski  Hi, the generated file cuda-repo-ubuntu1804-10-2-local-10.2.89-440.33.01_1.0-1_amd64.deb is 1.8GB big if you mean that one, so it is too big to be sent here.

**Comment by knkski** [comment]
@SrdjanStevanetic: no, there should be a .tar.gz file that's considerably smaller

**Comment by SrdjanStevanetic** [comment]
@knkski Yes I see. Here it is.
[inspection-report-20200324_163102.tar.gz](https://github.com/ubuntu/microk8s/files/4379220/inspection-report-20200324_163102.tar.gz)

**Comment by ktsakalozos** [comment]
@SrdjanStevanetic there seems to be something blocking the pod to service communication. For example CoreDNS reports:
```
E0324 15:55:10.345596       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: connect: connection refused
```

10.152.183.1 is the Kubernetes API server available for the hosted services.

Often this problem has to do with a firewall adding IPtable rules. Could you check the first couple of points in https://microk8s.io/docs/troubleshooting ?

**Comment by SrdjanStevanetic** [comment]
@ktsakalozos Hi, sorry for the late reply. Could you please indicate exactly which options I should check?

**Comment by ktsakalozos** [comment]
@SrdjanStevanetic in the logs of failing containers you will see that the pod cannot reach the apiserver. The pods are in the 10.1.0.0/16 network and the cluster IPs are in 10.152.183.0/24.
```
Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: connect: connection refused
```
 If you do a a `sudo iptables -L` you will see the iptable rules shaping the network traffic. I suspect the traffic is blocked because in the FORWARD chain there are two REJECT rules before the accept rules for the 10.1.0.0/16 network:
```
Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
ACCEPT     all  --  anywhere             anywhere             /* generated for LXD network lxdbr0 */
ACCEPT     all  --  anywhere             anywhere             /* generated for LXD network lxdbr0 */
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             192.168.122.0/24     ctstate RELATED,ESTABLISHED
ACCEPT     all  --  192.168.122.0/24     anywhere            
ACCEPT     all  --  anywhere             anywhere            
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
ACCEPT     all  --  10.1.0.0/16          anywhere             /* generated for MicroK8s pods */
ACCEPT     all  --  anywhere             10.1.0.0/16          /* generated for MicroK8s pods */
ACCEPT     all  --  10.1.0.0/16          anywhere            
ACCEPT     all  --  anywhere             10.1.0.0/16         
```
You may want to investigate if these two REJECT rules are really the cause of the problem and why are these rules there.

**Comment by nuka137** [comment]
@knkski @ktsakalozos 

I'm faced with this issue.
I think we need to add `juju-no-proxy` option to [here](https://github.com/ubuntu/microk8s/blob/a4046bed7eed8ed889a2937dbd23034f6e3809b8/microk8s-resources/actions/enable.kubeflow.sh#L353) as well as [here](https://github.com/ubuntu/microk8s/blob/a4046bed7eed8ed889a2937dbd23034f6e3809b8/microk8s-resources/actions/enable.kubeflow.sh#L342) and [here](https://github.com/ubuntu/microk8s/blob/a4046bed7eed8ed889a2937dbd23034f6e3809b8/microk8s-resources/actions/enable.kubeflow.sh#L344).
What do you think?

**Comment by knkski** [comment]
@wallyworld: Do we need to add the `juju-no-proxy` option in those places? :point_up:
