### ISSUE TITLE
How to access domain dns resource

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ubuntu/microk8s#1064]
Hi,

I am new to Kubernetes and have deployed Ansible AWX. However, I am unable dns resolve both in our domain and internet from inside the namespace.

The microk8s host has no problem dns resolving. 

[inspection-report-20200326_125559.tar.gz](https://github.com/ubuntu/microk8s/files/4387246/inspection-report-20200326_125559.tar.gz)

Any help is appreciated. Thanks

**Comment by ktsakalozos** [comment]
Hi @nicolaibaralmueller 

I suspect you would want to set your own forward dns server. By default we use 8.8.8.8. Have a look at https://microk8s.io/docs/addon-dns

**Comment by nicolaibaralmueller** [comment]
> Hi @nicolaibaralmueller
> 
> I suspect you would want to set your own forward dns server. By default we use 8.8.8.8. Have a look at https://microk8s.io/docs/addon-dns

Thanks. But shouldn't 8.8.8.8 resolve internet adresses?
