### ISSUE TITLE
Failed to enable kubeflow

### ISSUE THREAD

**Issue by jfantell** [ubuntu/microk8s#1065]
Steps to reproduce:
KUBEFLOW_CHANNEL=edge microk8s.start
microk8s.status --wait-ready
microk8s.enable gpu
microk8s.enable kubeflow

(I also tried using the stable channel, but with no success)

Report Tarball:
[inspection-report-20200326_141903.tar.gz](https://github.com/ubuntu/microk8s/files/4389090/inspection-report-20200326_141903.tar.gz)

Terminal Output:
john@john-X570-AORUS-PRO-WIFI:~$ microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling rbac...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Deploying Kubeflow...
Kubeflow could not be enabled:
Creating Juju controller "uk8s" on microk8s/localhost
Creating k8s resources for controller "controller-uk8s"
ERROR failed to bootstrap model: creating controller stack for controller: creating statefulset for controller: timed out waiting for controller pod: unschedulable: pvc storage-controller-0 pending due to ExternalProvisioning - waiting for a volume to be created, either by external provisioner "microk8s.io/hostpath" or manually created by system administrator

Command '('microk8s-juju.wrapper', 'bootstrap', 'microk8s', 'uk8s')' returned non-zero exit status 1
Failed to enable kubeflow

**Comment by ktsakalozos** [comment]
Hi @jfantell 

I see your hostname has capital letters. Could you update the hostname to lowercase? Similar issue: https://github.com/ubuntu/microk8s/issues/1066#issuecomment-604833190
