### ISSUE TITLE
Invalid charm URL in application "oidc-gatekeeper" & "dex-auth"

### ISSUE THREAD

**Issue by srmeier** [ubuntu/microk8s#1068]
[inspection-report-20200327_130231.tar.gz](https://github.com/ubuntu/microk8s/files/4393619/inspection-report-20200327_130231.tar.gz)

Attempting to enable Kubeflow under recent 1.18 release to take advantage of new features:
```
sudo snap install microk8s --classic --channel=1.18/stable
sudo usermod -a -G microk8s $USER
su - $USER
microk8s status --wait-ready
microk8s enable dns storage
microk8s.enable kubeflow
```

Receiving the following error when attempting to enable Kubeflow:
```
Enabling dns...
Enabling storage...
Enabling rbac...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Deploying Kubeflow...
Kubeflow could not be enabled:
Located bundle "cs:bundle/kubeflow-170"
ERROR cannot deploy bundle: the provided bundle has the following errors:
empty charm path
invalid charm URL in application "oidc-gatekeeper": cannot parse URL "": name "" not valid
empty charm path
invalid charm URL in application "dex-auth": cannot parse URL "": name "" not valid

Command '('microk8s-juju.wrapper', 'deploy', 'cs:kubeflow', '--channel', 'stable', '--overlay', '/tmp/tmpy8g83g_k')' returned non-zero exit status 1
Failed to enable kubeflow
```

I see a similar error message briefly mentioned in this thread https://github.com/ubuntu/microk8s/issues/753#issuecomment-554878693 but for "ambassador-auth" under a different build.

**Comment by knkski** [comment]
Sorry about this, there was a delay in stabilizing the kubeflow deployment for microk8s. Can you try again?

**Comment by knkski** [comment]
Closing since this should now work, feel free to reopen if you are still encountering this issue.
