### ISSUE TITLE
Containers resolve DNS via inaccessible host systemd-resolve instead of coredns

### ISSUE THREAD

**Issue by ships** [ubuntu/microk8s#1070]
Hi friends, thanks for this lovely utility!

I am running microk8s on a physical host and am running into problems with DNS. pods that do not require DNS are running just fine.

I have enabled DNS via `microk8s` cli and see CoreDNS is running happily:
```
 kc get pod -o wide --all-namespaces
NAMESPACE     NAME                                    READY   STATUS             RESTARTS   AGE    IP           NODE           NOMINATED NODE   READINESS GATES
default       concourse-teem-postgresql-0             1/1     Running            0          53m    10.1.72.72   carthage       <none>           <none>
default       concourse-teem-web-594dd6697d-7t6ll     0/1     CrashLoopBackOff   9          25m    10.1.72.73   carthage       <none>           <none>
kube-system   coredns-588fd544bf-7b54g                1/1     Running            2          19h    10.1.72.62   carthage       <none>           <none>
kube-system   hostpath-provisioner-75fdc8fccd-t8rh5   1/1     Running            2          19h    10.1.72.53   carthage       <none>           <none>
```

As you can see, this `web` pod which is trying to lookup the `postgres` pod is failing. In its logs I see that:
```
dial tcp: lookup concourse-teem-postgresql on 127.0.0.53:53: read udp 127.0.0.1:43082-\u003e127.0.0.53:53: read: connection refused
```

Although I am surprised to see that the systemd-resolve (127.0.0.53) on my host is refusing connection (and in fact, in other containers I am instead seeing connection timeout), it is further surprising because I don't expect that resolver to be able to resolve the kubernetes service names anyway. The IP for the core-dns does resolve them:

```
# dig @10.1.72.62 concourse-teem-postgresql.default.svc.cluster.local

; <<>> DiG 9.11.3-1ubuntu1.11-Ubuntu <<>> @10.1.72.62 concourse-teem-postgresql.default.svc.cluster.local
; (1 server found)
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25537
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 90424a268925d8be (echoed)
;; QUESTION SECTION:
;concourse-teem-postgresql.default.svc.cluster.local. IN	A

;; ANSWER SECTION:
concourse-teem-postgresql.default.svc.cluster.local. 5 IN A 10.152.183.158

;; Query time: 0 msec
;; SERVER: 10.1.72.62#53(10.1.72.62)
;; WHEN: Fri Mar 27 19:58:27 UTC 2020
;; MSG SIZE  rcvd: 159
```

So I look in my container's /etc/resolv.conf:

```
# cat /etc/resolv.conf
search attlocal.net
nameserver 127.0.0.53
```

Shouldn't I expect to see coredns as the preferred resolver? If not, why not? What is the expected flow for inheriting DNS resolution internal to the cluster?

Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20200327_193038.tar.gz](https://github.com/ubuntu/microk8s/files/4395682/inspection-report-20200327_193038.tar.gz)

I appreciate your feedback. Thank you for sharing microk8s!

**Comment by ktsakalozos** [comment]
Hi @ships 

I see in the arguments of kubelet (`/var/snap/microk8s/current/args/kubelet`) you are missing: `--cluster-dns=10.152.183.10`. This IP is the IP of the dns service and gets injected into the pods.

As you can see in [1] both `--cluster-domain=cluster.local` and  `--cluster-dns=10.152.183.10` are set one after the other, but only the first one is set in your deployment. Do you have any idea what happened? Did the `microk8s.enable dns` finished without errors?

The obvious fix is to add the missing argument and `microk8s stop; microk8s start`.


https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.dns.sh#L23

**Comment by ships** [comment]
I don't recall an error during enabling DNS, but I went ahead with trying to disable then re-enable. I've done some bad ops with a node that was previously join and never did `leave` so I have a bit of a weird output:

```
# microk8s enable dns
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns created
clusterrolebinding.rbac.authorization.k8s.io/coredns created
Restarting kubelet
Adding argument --cluster-domain to nodes.
Applying to node 192.168.1.74.
Node 192.168.1.74 not present
Adding argument --cluster-dns to nodes.
Applying to node 192.168.1.74.
Node 192.168.1.74 not present
Restarting nodes.
Applying to node 192.168.1.74.
Node 192.168.1.74 not present
DNS is enabled
```

Incidentally, where does this enable script get that node info from? It still shows up after `kubectl node delete ...`?

However, after this process, the DNS is back up. I would guess it must have encountered an error during the enable process which I missed, and which stopped it from writing the cluster-dns flag.
