### ISSUE TITLE
Unble pull image from private registry on another node

### ISSUE THREAD

**Issue by huranjiu** [ubuntu/microk8s#1075]
Env:
  os: Ubuntu18.04
  microk8s version: 1.18/stable

  I have two node(node1,node2) and enable registry on node1. they are in one cluster and node1 is matser.
  According to the guid [https://microk8s.io/docs/registry-private](url), I have updated files /var/snap/microk8s/current/args/containerd-template.toml  and /etc/docker/daemon.json on both nodes.
`        [plugins.cri.registry.mirrors."192.168.1.106:32000"]
`
`
                  endpoint = ["http://192.168.1.106:32000"]
  `

When I created a deployment and assigned it to node2, failed to pull image with the message:

> no available registry endpoint: failed to do request: Head "https:/
/192.168.1.106:32000/v2/docker-demo/manifests/0.0.1-SNAPSHOT": http: server gave HTTP response to HTTPS client

But when I assigned this deployment to node1, it worked.  

See [https://github.com/ubuntu/microk8s/issues/756](url)

**Comment by balchua** [comment]
You may need to restart the containerd on both machines.

**Comment by huranjiu** [comment]
I did and I even reboot the both machine,but it still didn't work.

  Thx .
                    :)

**Comment by balchua** [comment]
Can you go to your node2 and run `microk8s.inspect` and if possible upload the generated tarball here?

**Comment by huranjiu** [comment]
[inspection-report-20200330_103106.tar.gz](https://github.com/ubuntu/microk8s/files/4402559/inspection-report-20200330_103106.tar.gz)
