### ISSUE TITLE
How to chage microk8s  from enp0s3 to enp0s8

### ISSUE THREAD

**Issue by huranjiu** [ubuntu/microk8s#1078]
I used VBox (Ubuntu18.04) to create two nodes, and each node was configured with enp0s3 and enp0s8. Enp0s8 represents the IP of the LAN.

   The master node network is bound to the enp0s3 card, so the pod in the slave node and the pod point in the master node cannot communicate. Now I want to rebind the master node network to enp0s3. If you can use `--apiserver-advertise-address` to bind IP when installing k8s with kubeadm, what should I do in microk8s?

   I saw configuration items in the `/var/snap/microk8s/1294/args/etcd`  file: `--advertise-client-urls = https: // $ {DEFAULT_INTERFACE_IP_ADDR}: 12379`. Where can I view or modify the value of           `${DEFAULT_INTERFACE_IP_ADDR}` ?

**Comment by ktsakalozos** [comment]
Hi @huranjiu 

You can set all the apiserver arguments [1] in `/var/snap/microk8s/current/args/kube-apiserver` and then you have to restart MicroK8s with `microk8s.stop; microk8s.start`. I believe you should set 
the `--advertise-address` and/or `--bind-address`.


[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by huranjiu** [comment]
Thanks,
