### ISSUE TITLE
microk8s command isn't installed on Windows

### ISSUE THREAD

**Issue by pjxiao** [ubuntu/microk8s#1079]
The official installation guide [1] let us open cmd and run `microk8s`  command though, `microk8s` command isn't available. cmd returned the following error message. Is the installation guide correct?

```cmd
> microk8s
'microk8s' is not recognized as an internal or external command,
operable program or batch file.
```

I looked for `microk8s` executable in my computer (`C:\Program Files`, `C:\Program Files (x86)`, `%USERPROFILE%\AppData`), but I couldn't find that executable.

[1]: https://microk8s.io/#get-started

**Comment by ktsakalozos** [comment]
Hi @pjxiao 

Thank you for reporting that. We have a bug in our docs, the link of the "Download MicroK8s for Windows" button should point to [1]. Could you try that installer?

Apologies for the inconvenience. We are working to fix this.

[1] https://github.com/ubuntu/microk8s/releases/download/installer-v1.0.0/microk8s-installer.exe

**Comment by pjxiao** [comment]
Hi @ktsakalozos 

I succeeded in installing microk8s by using `microk8s-installer.exe` and confirmed that a MicroK8s launched. Thank you. 

Now, my problem has been resolved but that link in the document is still broken. Shouldn't I close this issue until the document is fixed?

**Comment by ktsakalozos** [comment]
Pleased to hear this worked for you. We track the issue in [1] and there is already a PR under review.

We can close this issue.

[1] https://github.com/canonical-web-and-design/microk8s.io/issues/241

**Comment by mabrahamdevops** [comment]
Again Microsoft Windows has a tutorial with a product that doesn't work with Microsoft Windows.  Linux here we come again!!!!!
