### ISSUE TITLE
Behind Proxy Can't install Kubeflow

### ISSUE THREAD

**Issue by rickyking** [ubuntu/microk8s#1081]
Hi,

I followed the instruction on Kubeflow page to install Kubeflow with Microk8s in ubuntu machine. The machine is behind a enterprise proxy. I used cntlm to create a local proxy that requires no authentification. (127.0.0.1:3128). 

The snap is set properly to use the proxy, and also followed https://microk8s.io/docs/install-proxy to set up the proxy.

Also I read from the previous bugs and try to set up `export KUBEFLOW_NO_PROXY=localhost,127.0.0.1,10.18.1.120 ,10.1.79.0/24,10.152.183.0/24`

I am not quite sure I correctly isolate the right IP to no proxy. But I am still getting following error.

```
Enabling dns...
Enabling storage...
Enabling rbac...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Deploying Kubeflow...
Kubeflow could not be enabled:
Creating Juju controller "uk8s" on microk8s/localhost
Creating k8s resources for controller "controller-uk8s"
Starting controller pod
Bootstrap agent now started
Contacting Juju controller at 10.152.183.18 to verify accessibility...
ERROR unable to contact api server after 1 attempts: read tcp 127.0.0.1:42054->127.0.0.1:3128: i/o timeout

Command '('microk8s-juju.wrapper', 'bootstrap', 'microk8s', 'uk8s')' returned non-zero exit status 1
Failed to enable kubeflow
```

Here is the inspect:

```
nspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball

Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1293/inspection-report-20200331_225320.tar.gz
```
[inspection-report-20200331_225320.tar.gz](https://github.com/ubuntu/microk8s/files/4412525/inspection-report-20200331_225320.tar.gz)

Thanks for the help

**Comment by knkski** [comment]
@wallyworld: Do you know what the no proxy option should be set to?

**Comment by knkski** [comment]
@rickyking: Can you say a little bit more about your proxy setup? It sounds like you're running cntlm locally, which proxies off to an enterprise proxy sitting somewhere on the local network. Are you then using network manager to route HTTP traffic to cntlm?

**Comment by rickyking** [comment]
@knkski : Thanks for your reply. Yes I have setup a local cantle which take care of the credential to enterprise proxy. There is no network manager to route HTTP traffic. But environment variable, such as `http_proxy` and `https_proxy` in bash. For `snap`, I set this: 

```
$ sudo snap set system proxy.http="http://<proxy_addr>:<proxy_port>"
$ sudo snap set system proxy.https="http://<proxy_addr>:<proxy_port>"
```

Also the enterprise SSL CA certificate is properly configured at system-level (ubuntu).

If you need any other information, don't hesitate.

**Comment by wallyworld** [comment]
As far as I am aware, Juju needs to have the juju-no-proxy model config set, and also when using the CLI, NO_PROXY needs to be set. So any KUBEFLOW_NO_PROXY value would need to be propagated through to those Juju settings. I think that should be sufficient.

**Comment by rickyking** [comment]
> As far as I am aware, Juju needs to have the juju-no-proxy model config set, and also when using the CLI, NO_PROXY needs to be set. So any KUBEFLOW_NO_PROXY value would need to be propagated through to those Juju settings. I think that should be sufficient. 

I have set up the KUBEFLOW_NO_PROXY as specified above. The error shows the 127.0.0.1 is trying to connect proxy. I am confused...
