### ISSUE TITLE
Backport Multi-Node support to 1.15/stable

### ISSUE THREAD

**Issue by sishbi** [ubuntu/microk8s#1082]
I have been using microk8s v1.17/stable for the past few weeks and have enjoyed using the multi-node support to utilise 2 laptops for my k8s cluster.
I have now found out that our company has to support v1.15 of k8s for production installations (such as PKS/EKS) so have had to downgrade microk8s back to 1.15/stable to make sure that we don't accidentally introduce configuration that is not compatible with that version.

However, this downgrade has meant that I no longer have the ability to use multi-node, as I see that it was introduced into microk8s v1.16
I am sure that it does not depend on the specific Kubernetes version so I am asking whether it would be possible to 'back-port' the multi-node support back to the 1.15/stable channel.

I have attached my inspection-report (as requested in the template)
[inspection-report-20200401_192455.tar.gz](https://github.com/ubuntu/microk8s/files/4416985/inspection-report-20200401_192455.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @sishbi, unfortunately there is not enough incentive to back port clustering to v1.15.

**Comment by sishbi** [comment]
We are now using v1.17 so this is no longer required.
