### ISSUE TITLE
Kubeflow dashboard - error to connect backend API

### ISSUE THREAD

**Issue by ereil** [ubuntu/microk8s#1084]
Hi,

on a fresh Ubuntu 18.04.4 installation with latest microk8s (rbac fix from 02. April seems to be working) I get a lot of "error to connect backend API" in the kubeflow dashboard gui. The complete error message is on the bottom of the web browser.

![Screenshot from 2020-04-02 15-25-56](https://user-images.githubusercontent.com/62931301/78257447-21723400-74fa-11ea-9c20-2b3fd731c9ab.png)

I had chance to start successfull one jupyter notebook but then the error message is appearing and its not possible to start a second notebook. 

This is only a single node microk8s cluster.
But i have tried 3 times a microk8s cluster of two nodes. Always the same errors in dashboard.

Any tips how to check whats going wrong?

[inspection-report-20200402_154731.tar.gz](https://github.com/ubuntu/microk8s/files/4421496/inspection-report-20200402_154731.tar.gz)

**Comment by ereil** [comment]
Also after restarting it's not possible to start a new notebook server. Always CrashLoopBackOff. The same settings which working with the first time notebook server, not working again. Also when all notebook servers are deleted.

![Screenshot from 2020-04-02 17-28-31](https://user-images.githubusercontent.com/62931301/78267572-66e92e00-7507-11ea-8f07-28590c40d8e9.png)

`sudo microk8s kubectl describe notebooks test8 -n admin
`
Results:
[notebook_server.txt](https://github.com/ubuntu/microk8s/files/4421987/notebook_server.txt)

**Comment by ereil** [comment]
Update: 
all shell commands like creating TFJob, creating MPI Jobs, creating pods with docker images seems to be working properly. I can't find anything not working in shell.

Only creating jupyter notebooks via kubeflow dashboard or visit dashboard generally did not working properly.

Is there a way to create jupyter notebooks via shell? Is there a yaml example how to do that? So i could test if this is also working via shell.

Could it be a rbac or authentication problem?
We finally want to use the kubeflow dashboard with Multi-User support. So rbac should be necessary?

Thanks

**Comment by knkski** [comment]
@ereil: Can you attach the logs from the failing jupyter notebook pod? Also, when you encounter the dashboard error, if you open up Firefox's dev tools and go to the network tab, what exactly is the response for the failing request? Though I would guess that that's just failing due to the pods being in CrashLoopBackoff

**Comment by ereil** [comment]
Here is the result of 

caduser@cad660745:~$ kubectl describe notebooks -n admin test77
Name:         test77
Namespace:    admin
Labels:       app=test77
Annotations:  <none>
API Version:  kubeflow.org/v1beta1
Kind:         Notebook
Metadata:
  Creation Timestamp:  2020-04-15T15:01:30Z
  Generation:          1
  Managed Fields:
    API Version:  kubeflow.org/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
    Manager:         manager
    Operation:       Update
    Time:            2020-04-15T15:07:29Z
  Resource Version:  379728
  Self Link:         /apis/kubeflow.org/v1beta1/namespaces/admin/notebooks/test77
  UID:               74995fdb-ba29-48cd-9e0b-e6f12086f94e
Spec:
  Template:
    Spec:
      Containers:
        Env:
        Image:  gcr.io/kubeflow-images-public/tensorflow-2.0.0a0-notebook-gpu:v0.7.0
        Name:   test77
        Resources:
          Limits:
            nvidia.com/gpu:  2
          Requests:
            Cpu:     0.5
            Memory:  1.0Gi
        Volume Mounts:
          Mount Path:              /home/jovyan
          Name:                    workspace-test77
          Mount Path:              /dev/shm
          Name:                    dshm
      Service Account Name:        default-editor
      Ttl Seconds After Finished:  300
      Volumes:
        Name:  workspace-test77
        Persistent Volume Claim:
          Claim Name:  workspace-test77
        Empty Dir:
          Medium:  Memory
        Name:      dshm
Status:
  Conditions:
    Last Probe Time:  2020-04-15T15:07:28Z
    Message:          Error
    Reason:           Error
    Type:             Terminated
    Last Probe Time:  2020-04-15T15:04:55Z
    Message:          back-off 2m40s restarting failed container=test77 pod=test77-0_admin(a7099c34-1c06-424e-bb6e-7af6ccee1946)
    Reason:           CrashLoopBackOff
    Type:             Waiting
    Last Probe Time:  2020-04-15T15:04:45Z
    Message:          Error
    Reason:           Error
    Type:             Terminated
    Last Probe Time:  2020-04-15T15:04:43Z
    Type:             Running
    Last Probe Time:  2020-04-15T15:03:25Z
    Message:          back-off 1m20s restarting failed container=test77 pod=test77-0_admin(a7099c34-1c06-424e-bb6e-7af6ccee1946)
    Reason:           CrashLoopBackOff
    Type:             Waiting
    Last Probe Time:  2020-04-15T15:03:10Z
    Message:          Error
    Reason:           Error
    Type:             Terminated
    Last Probe Time:  2020-04-15T15:02:31Z
    Message:          back-off 40s restarting failed container=test77 pod=test77-0_admin(a7099c34-1c06-424e-bb6e-7af6ccee1946)
    Reason:           CrashLoopBackOff
    Type:             Waiting
    Last Probe Time:  2020-04-15T15:02:17Z
    Message:          Error
    Reason:           Error
    Type:             Terminated
    Last Probe Time:  2020-04-15T15:02:16Z
    Type:             Running
    Last Probe Time:  2020-04-15T15:02:02Z
    Message:          back-off 20s restarting failed container=test77 pod=test77-0_admin(a7099c34-1c06-424e-bb6e-7af6ccee1946)
    Reason:           CrashLoopBackOff
    Type:             Waiting
    Last Probe Time:  2020-04-15T15:01:50Z
    Message:          Error
    Reason:           Error
    Type:             Terminated
    Last Probe Time:  2020-04-15T15:01:36Z
    Message:          back-off 10s restarting failed container=test77 pod=test77-0_admin(a7099c34-1c06-424e-bb6e-7af6ccee1946)
    Reason:           CrashLoopBackOff
    Type:             Waiting
    Last Probe Time:  2020-04-15T15:01:35Z
    Message:          Error
    Reason:           Error
    Type:             Terminated
    Last Probe Time:  2020-04-15T15:01:34Z
    Type:             Running
    Last Probe Time:  2020-04-15T15:01:33Z
    Message:          Error
    Reason:           Error
    Type:             Terminated
    Last Probe Time:  2020-04-15T15:01:32Z
    Type:             Running
    Last Probe Time:  2020-04-15T15:01:31Z
    Reason:           ContainerCreating
    Type:             Waiting
  Container State:
    Terminated:
      Container ID:  containerd://ce51474cbc429096b479b368ff9099182c1049fe795a6966cbf2e1ddd045b0b2
      Exit Code:     1
      Finished At:   2020-04-15T15:07:28Z
      Reason:        Error
      Started At:    2020-04-15T15:07:27Z
  Ready Replicas:    0
Events:              <none>


And here are the logs of the jupyter notebook:

kubectl logs test77-0 -n admin
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1676, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1349, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'

**Comment by ereil** [comment]
And here are entries of activity in kubeflow dashboard

![Screenshot from 2020-04-15 17-16-15](https://user-images.githubusercontent.com/62931301/79354566-d9610180-7f3c-11ea-8c82-63e45d4d41e1.png)

**Comment by knkski** [comment]
@ereil: The error you're getting looks similar to this:

https://github.com/jupyter/docker-stacks/issues/526

Do you have enough disk space, and are permission set up correctly on the disk?
