### ISSUE TITLE
[installer] multipass VM name should be `microk8s-vm`

### ISSUE THREAD

**Issue by ceefour** [ubuntu/microk8s#1085]
As documented in https://microk8s.io/#get-started,
Getting Started suggests a VM name as `microk8s-vm`, instead of the currently used `MicroK8sVM` by installer.

While it's a subtle detail, it's good to avoid subtle issues regarding documentation etc. especially for Windows and MacOS users.

**Comment by ktsakalozos** [comment]
Thank you for spotting that @ceefour . You are right, we should be consistent.

**Comment by kwmonroe** [comment]
In addition to the VM name, i think it would also be good to synchronize the default constraints with the docs.  Currently, [microk8s multipass docs](https://github.com/canonical-web-and-design/microk8s.io/blob/master/docs/install-alternatives.md#multipass) say this:

```bash
multipass launch --name microk8s-vm --mem 4G --disk 40G
```

But if users run one of the installers, they'll get these constraints by default:

https://github.com/ubuntu/microk8s/blob/master/installer/common/definitions.py#L23-L25

**Comment by ktsakalozos** [comment]
The VM naming is fixed  https://github.com/ubuntu/microk8s/pull/1125

The default VM disk size is set to 50 GB in https://github.com/ubuntu/microk8s/pull/1112
