### ISSUE TITLE
[Question] does kubeflow installation support aarch64?

### ISSUE THREAD

**Issue by sakaia** [ubuntu/microk8s#1086]
From seeing the following code, kubeflow is only supports amd64. is there any plan to support aarch64? has juju limitation on aarch64?

[microk8s-juju.wrapper](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-juju.wrapper)

**Comment by ktsakalozos** [comment]
Juju is available for ARM64. ARM64 kubeflow support is not so clear. I see people have already made it work [1], but there is still work to be done from upstream. I am not aware of any plans of Kubeflow on ARM64 MicroK8s. 

[1] https://github.com/kubeflow/kubeflow/issues/2337

**Comment by sakaia** [comment]
I close this issue. Since this is kubeflow limitation not microk8s.
