### ISSUE TITLE
[Question] kubeflow's cli kfctl and python package "kubeflow" installation instruction is available?

### ISSUE THREAD

**Issue by sakaia** [ubuntu/microk8s#1087]
I try to install kubeflow on microk8s and it seems successfully.
   (I build it on AWS EC2 environment)
but I cannot find kfctl command line is not found. also "import kubeflow" is not work for python3

From following instruction, it needs to work above commands.
[https://ubuntu.com/kubeflow/install](https://ubuntu.com/kubeflow/install)

which refers following pages as sample.
- [Kubeflow Samples](https://www.kubeflow.org/docs/examples/kubeflow-samples/)
- [Pipelines](https://www.kubeflow.org/docs/pipelines/)

**Comment by knkski** [comment]
`microk8s.enable kubeflow` uses Juju to deploy Kubeflow, as opposed to kfctl. You shouldn't need to use kfctl, but it would be great if you could list any specific use cases that you've found you need it for.

Where are you getting the import error for the `kubeflow` package? If it's within a Jupyter Notebook, you can run `%pip install kubeflow` to install the package.

**Comment by sakaia** [comment]
Thank you I understand kfctl and juju takes same position.

**Comment by sakaia** [comment]
Python package kubeflow installed successfully. 
And can import kubeflow but cannot import kubeflow.tfjob
is there any operation?

[https://github.com/kubeflow/examples/blob/master/mnist/mnist_vanilla_k8s.ipynb](https://github.com/kubeflow/examples/blob/master/mnist/mnist_vanilla_k8s.ipynb)

**Comment by knkski** [comment]
@sakaia: You'll need to also install the `kubeflow-tfjob` Python package

**Comment by sakaia** [comment]
Thank you, In my environment (AWS EC2), katib and tfjob works fine on microk8s1.15 + kubeflow 1.0.2.
So I close it.

pipeline and pytorchjob is not working yet as "Message: ContainerCreating"

**Comment by paravatha** [comment]
@sakaia 
When you get time, can you please provide instructions about how to setup kubeflow + microk8s on AWS EC2?
