### ISSUE TITLE
Win/Mac installers to add microk8s context in existing kubeconfig

### ISSUE THREAD

**Issue by alxchalkias** [ubuntu/microk8s#1095]
As a microk8s user on Windows/Mac, I want to be able to use a standard kubectl for all my K8s instances that run on my machine. 

A solution to that would be to have the installers detect any pre-existing kubeconfig files in the system and automatically append the microk8s context to them. Essentially, the installers need to automate this procedure: https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

One issue to be taken into account would be how to keep the version of kubectl outside the MicroK8sVM in sync with the K8s inside the VM.

**Comment by joedborg** [comment]
Thanks @alxchalkias, we can certainly investigate this.  We did look at synchronizing the installer and VM, but this posed some pretty complex challenges between Windows and MacOS.
