### ISSUE TITLE
Make number of files ulimit configurable

### ISSUE THREAD

**Issue by donbowman** [ubuntu/microk8s#1096]
In [#413](https://github.com/ubuntu/microk8s/pull/413) we set ulimit -n 64K.
but this is lowering it on my system, rendering many tools unusable.
Since this is delivered in a snap I don't believe I can override it.

E.g. running `titan`
```
["the maximum number of open file descriptors is too small, got 65536, expect greater or equal to 82920"]
```

How can i set the ulimit, or, at least, not lower it? 

```
cat /proc/sys/fs/file-max
8388608
```

**Comment by ktsakalozos** [comment]
Hi @donbowman, you can edit `/var/snap/microk8s/current/args/containerd-env` and restart microk8s with `microk8s.stop; microk8s.start`. What kind of machine specs/setup is expecting that many file descriptions?

**Comment by PhotoTeeborChoka** [comment]
@ktsakalozos For example the `npm install` inside a Jenkins K8s agent during build process requires a gigantic amount of open files.

**Comment by sibelius** [comment]
after edit just restart ?
