### ISSUE TITLE
microK8S's dns does not work

### ISSUE THREAD

**Issue by hostettler** [ubuntu/microk8s#1098]
Hello,

I've just a fresh install of microK8S following [the official doc](https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#1-overview) do not get the dns pods to start.
Following the troubleshooting section [there](https://microk8s.io/docs/troubleshooting) I double checked my fw rules.
but a 

> microk8s.kubectl logs coredns-588fd544bf-dt8jz -n kube-system

```
0407 16:07:10.623229       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: i/o timeout
E0407 16:07:10.623229       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: i/o timeout
E0407 16:07:10.623229       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: i/o timeout
```

My ufw status looks like:
```
xxxxxx@master-node:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
443/tcp                    ALLOW       Anywhere
Anywhere on cni0           ALLOW       Anywhere

Anywhere                   ALLOW OUT   Anywhere on cni0
```
So the dns pod does not have access to the cluster ip
```
xxxxx@pinfo3:~$ microk8s kubectl -n kube-system get services
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
kube-dns   ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   2m32s
````
I tried the same with a busy box and it has also not access to the cluster-ip but it has access to the other pods.

Thanks a lot in advance

[inspection-report-20200407_213505.tar.gz](https://github.com/ubuntu/microk8s/files/4446664/inspection-report-20200407_213505.tar.gz)

**Comment by hostettler** [comment]
Following #1034, I checked my proxy logs and I have the same issue:
```
7224   32034 server.go:621] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
```
But the problem is that when microK8S runs I have
```
xxxx@master-node:~$  sudo lsof -i :10256
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
kube-prox 32157 root    9u  IPv4 690097      0t0  TCP localhost:10256 (LISTEN)
```
But when I stop microk8s I do not have any more port running
```
xxxx@master-node:~$ sudo microk8s stop
Stopped.
xxxx@master-node:~$  sudo lsof -i :10256
xxxx@master-node:~$
```

**Comment by ktsakalozos** [comment]
Hi @hostettler there is something not right with the network setup in this system. The 10.152.183.X network is where kubernetes gets its cluster ips from. It seems that traffic is dropped to this network. It is not only DNS that is affected by this. This needs a bit of research on your side. One thing I would check first is the default input policy that is set to DROP. Could you try to change that to ACCEPT or at least ACCEPT the traffic to/from the 10.152.183.X network?

**Comment by hostettler** [comment]
Thanks a lot for looking into it. So I did
```
sudo ufw allow to 10.152.183.0/24
sudo ufw allow from 10.152.183.0/24
````
But it does not solve the problem

**Comment by hostettler** [comment]
So I temperately set the default policy to accept and it does solve the problem but obviously I do not want to have to set that policy to accept.

**Comment by ktsakalozos** [comment]
The second network you want to allow traffic to/from is 10.1.14.1. This network if where pods are.

**Comment by hostettler** [comment]
So adding 
```
 sudo iptables -A INPUT-p tcp -s 10.1.14.0/24 -j ACCEPT
 sudo iptables -A OUTPUT -p tcp -d 10.1.14.0/24 -j ACCEPT
```

Does not solve the problem

**Comment by hostettler** [comment]
I made some progress. So the problem is apparently that the traffic from cni0 get dropped despite the fact that microk8s seems to put the right rules in place.

I did the following
```
sudo iptables -P INPUT ACCEPT
sudo iptables -L LOGGING
sudo iptables -A LOGGING -m limit --limit 10/min -j LOG --log-prefix "IPTables-Dropped: " --log-level 6
sudo iptables -A LOGGING -j DROP
```

to capture the dropped packets and simulate the drop policy as it sweep the rest of the traffic and I can reproduce the problem. Now if I add accept to all cni0 traffic before logging/dropping

```
sudo iptables -P INPUT ACCEPT
sudo iptables -D  LOGGING -m limit --limit 10/min -j LOG --log-prefix "IPTables-Dropped: " --log-level 6
sudo iptables -D  LOGGING -j DROP
sudo iptables -A LOGGING -i cni0
sudo iptables -A LOGGING -m limit --limit 10/min -j LOG --log-prefix "IPTables-Dropped: " --log-level 6
sudo iptables -A LOGGING -j DROP
```

Then it works.
