### ISSUE TITLE
enable kubeflow gets stuck with "Waiting for service pods to become ready"

### ISSUE THREAD

**Issue by pourquoi42** [ubuntu/microk8s#1101]
After fresh install of microk8s, I was trying to enable kubeflow. It gets stuck with "Waiting for service pods to become ready". Also until I got "Operator pods ready." it took >2000s, which I assume is not normal.  Looking at what pods are scheduled, I see many many in "evicted" state. Can kf not be started because before all dependencies are up, already started ones are evicted again due to resource limits? What can I do about it. I have 16GB of RAM, 8 CPUs und the host/node.
[inspection-report-20200408_155528.tar.gz](https://github.com/ubuntu/microk8s/files/4450874/inspection-report-20200408_155528.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @pourquoi42, if you do a `microk8s.kubectl describe no` you will see that your node is under disk pressure. In your `df -h` you will see ` /dev/sda1        35G   31G  1,5G  96% /`.

**Comment by pourquoi42** [comment]
Was able to install kubeflow after adding diskspace.

**Comment by jkim711** [comment]
Hi
I am stuck at the same problem as well. 
Ubuntu version is 18.04.

**Comment by ktsakalozos** [comment]
@jkim711, please attach the tarball produced by `microk8s.inspect`.

**Comment by jkim711** [comment]
Amazing, I left them running on both my PC linux and Azure Linux. Event the PC version finished in the installation, but the Linux on Azure is still hanging, printing "Waited 25290s for operator pods to come up, 5 remaining.". 
But the IP address that the kubeflow installation printed out is unreachable.

Congratulations, Kubeflow is now available.
The dashboard is available at http://10.64.140.43.xip.io/

    Username: admin
    Password: xxxxxxxxxxxxxxxxxxxxxxxxx
To see these values again, run:

    microk8s juju config dex-auth static-username
    microk8s juju config dex-auth static-password

To tear down Kubeflow and associated infrastructure, run:

   microk8s disable kubeflow

**Comment by knkski** [comment]
@jkim711: does following this comment help you connect?

https://github.com/ubuntu/microk8s/issues/1140#issuecomment-660044973

**Comment by blizda** [comment]
I get same error with ubuntu 18.04 and microk8s version 1.19.0
[inspection-report-20200930_063253.tar.gz](https://github.com/ubuntu/microk8s/files/5305949/inspection-report-20200930_063253.tar.gz)
