### ISSUE TITLE
How to use Helm 3

### ISSUE THREAD

**Issue by magick93** [ubuntu/microk8s#1105]
# Description

I'm unable to use Helm3. 

When I try the following:
1. `microk8s enable helm3`
1. `helm list`

I get `Error: Kubernetes cluster unreachable`.

I then try:
1. `microk8s.config view > /home/anton/.kube/config` as suggested in https://github.com/ubuntu/microk8s/issues/833
1. `helm list`

And get the same

#### Doesnt Work
`kubectl cluster-info`

```
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
Unable to connect to the server: x509: certificate signed by unknown authority
```

#### Works
`kubectl cluster-info --insecure-skip-tls-verify=true`

```
Kubernetes master is running at https://127.0.0.1:16443
Heapster is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/heapster/proxy
CoreDNS is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Grafana is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
InfluxDB is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-influxdb:http/proxy

So I assume the issue is something to do with certificates, however, from my understanding Helm3 doesnt use Tiller. 


To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

From run `microk8s inspect`:

[inspection-report-20200410_123916.tar.gz](https://github.com/ubuntu/microk8s/files/4459265/inspection-report-20200410_123916.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

**Comment by magick93** [comment]
This helped - https://worklifenotes.com/2020/01/22/how-to-make-microk8s-work-with-helm/

**Comment by ktsakalozos** [comment]
I believe you could have used the addon comming with MicroK8s (`microk8s enable helm3`) and then use `microk8s helm3`.

**Comment by giddyhut** [comment]
I don't understand why this helm/helm3 addon is needed. Helm can be obtained separately via snap, so why is this an addon in microk8s? Any advantages?

**Comment by neoaggelos** [comment]
Hi @giddyhut 

The helm3 addon is there for mainly two reasons: first is simplicity, microk8s comes with it out of the box so no extra binaries are needed to get started. the second is that some addons (e.g. GPU) are using it to deploy the necessary manifests. that would be a lot more complex if helm was not built-in.

By the way, there is nothing that stops you from using any helm binary (or version) you might prefer with a microk8s cluster, as long as you point it to the cluster kubeconfig.

Hope this gives some more context around it.
