### ISSUE TITLE
MetalLB *can* work in MacOS

### ISSUE THREAD

**Issue by cscheib** [ubuntu/microk8s#1107]
Contrary to canonical/multipass#1298, #908 - 

I have MetalLB working on MacOS with multipass/microk8s just fine, and my config looks similar-ish to the config generated by the microk8s add-on (I just installed metallb manually). 

Caveats:
* metallb doesn't respond to regular ICMP ping, from MacOS or from within the Linux VM
* arping doesn't seem to work, even from inside the Multipass Linux VM.  This kinda indicates that MacOS isn't really the problem on that one.

**I can curl the endpoint behind my LB service that's running on microk8s in multipass**
```
chris@mandalore   ~  curl http://192.168.64.51
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Kashti</title>

  <link rel="apple-touch-icon" sizes="128x128" href="assets/images/icons/default/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/images/icons/default/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/images/icons/default/favicon-16x16.png">

  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.56bbad704999d16e724b.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.a66f828dca56eeb90e02.js"></script><script type="text/javascript" src="polyfills.086a5b637f757f4c448b.js"></script><script type="text/javascript" src="scripts.f8a41137d5ecf8dd31f5.js"></script><script type="text/javascript" src="main.b2e8a34247df00f0cab7.js"></script></body>
</html>
```

**Here's the load balancer resource:**
```
 chris@mandalore   ~  kubectl get svc brigade-server-kashti -n brigade-system
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)        AGE
brigade-server-kashti   LoadBalancer   10.152.183.165   192.168.64.51   80:31538/TCP   25m
```

**MetalLB config:**
```
 chris@mandalore   ~  kubectl get configmap -n metallb-system config -o yaml --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.64.50-192.168.64.100
kind: ConfigMap
metadata:
  annotations:
    fluxcd.io/sync-checksum: 64a621d53c13252b2b280090f14f999639501b7a
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"address-pools:\n- name: default\n  protocol: layer2\n  addresses:\n  - 192.168.64.50-192.168.64.100\n"},"kind":"ConfigMap","metadata":{"annotations":{"fluxcd.io/sync-checksum":"64a621d53c13252b2b280090f14f999639501b7a"},"labels":{"fluxcd.io/sync-gc-mark":"sha256.NIaJeDs6KJDSCWGRnkxjLiQ59w_zuuD52O_bGy9jD84"},"name":"config","namespace":"metallb-system"}}
  creationTimestamp: null
  labels:
    fluxcd.io/sync-gc-mark: sha256.NIaJeDs6KJDSCWGRnkxjLiQ59w_zuuD52O_bGy9jD84
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config: {}
      f:metadata:
        f:annotations:
          .: {}
          f:fluxcd.io/sync-checksum: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:fluxcd.io/sync-gc-mark: {}
    manager: kubectl
    operation: Update
    time: "2020-04-11T02:35:45Z"
  name: config
  selfLink: /api/v1/namespaces/metallb-system/configmaps/config
```
If I have some time tomorrow, I'll provide more examples, and possibly make an attempt to see if this works with the microk8s plugin, as I would expect it to 

CC/ @candlerb for information/discussion

**Comment by cscheib** [comment]
Actually, I just got arping working from the host, but only when I specify the interface: 
```
 chris@mandalore   ~  sudo /usr/local/Cellar/arping/2.21_1/sbin/arping -i bridge100 192.168.64.50
ARPING 192.168.64.50
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.50): index=0 time=7.856 msec
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.50): index=1 time=824.000 usec
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.50): index=2 time=1.899 msec
^C
--- 192.168.64.50 statistics ---
3 packets transmitted, 3 packets received,   0% unanswered (0 extra)
rtt min/avg/max/std-dev = 0.824/3.526/7.856/3.093 ms
 chris@mandalore   ~  sudo /usr/local/Cellar/arping/2.21_1/sbin/arping -i bridge100 192.168.64.51
ARPING 192.168.64.51
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.51): index=0 time=2.856 msec
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.51): index=1 time=601.000 usec
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.51): index=2 time=414.000 usec
^C
--- 192.168.64.51 statistics ---
3 packets transmitted, 3 packets received,   0% unanswered (0 extra)
rtt min/avg/max/std-dev = 0.414/1.290/2.856/1.110 ms
```

**Comment by cscheib** [comment]
non working arping, but arp is in the table on laptop
``` 
chris@mandalore   ~  sudo /usr/local/Cellar/arping/2.21_1/sbin/arping 192.168.64.51
arping: libnet_init(LIBNET_LINK, <null>): libnet_ifaddrlist(): SIOCGIFADDR: dev=en5: Operation not permitted
 chris@mandalore   ~  arp -a | grep 196.168.54
 chris@mandalore   ~  arp -a | grep 192.168.54
 chris@mandalore   ~  arp -a | grep 192.168.64
? (192.168.64.1) at fa:ff:c2:d0:67:64 on bridge100 ifscope permanent [bridge]
? (192.168.64.4) at ca:3b:cc:e:10:69 on bridge100 ifscope [bridge]
? (192.168.64.50) at ca:3b:cc:e:10:69 on bridge100 ifscope [bridge]
? (192.168.64.51) at ca:3b:cc:e:10:69 on bridge100 ifscope [bridge]
? (192.168.64.255) at ff:ff:ff:ff:ff:ff on bridge100 ifscope [bridge]
```

**Comment by candlerb** [comment]
Remember this is a problem with multipass specifically.

FWIW, I have now switched from multipass to Virtualbox for another networking reason (multipass VM was unable to access remote site via Cisco Anyconnect VPN client).  I haven't tried metallb since the switch, but I've never had issues with ARP with Virtualbox.

**Comment by cscheib** [comment]
@candlerb yes, this is macos > multipass > microk8s > metallb

The only differentiator may be that I installed metallb manually, rather than using the addon.

**Comment by cscheib** [comment]
Versions:
multipass v1.1.0
microk8s 1.18/stable channel
metallb v0.8.2 (I should probably update to 0.9.3)
macos 10.15.4

**Comment by cscheib** [comment]
I have confirmed I can replicate this metallb working with the microk8s addon version of metallb, as well:

```
 chris@mandalore   ~/src/cscheib-fluxcd/workloads     master   kubectl get configmap -n metallb-system -o yaml config --export
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.64.50-192.168.64.100
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config":"address-pools:\n- name: default\n  protocol: layer2\n  addresses:\n  - 192.168.64.50-192.168.64.100\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config","namespace":"metallb-system"}}
  creationTimestamp: null
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:config: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl
    operation: Update
    time: "2020-04-11T17:10:39Z"
  name: config
  selfLink: /api/v1/namespaces/metallb-system/configmaps/config
```
```
 chris@mandalore   ~/src/cscheib-fluxcd/workloads     master   curl -i http://192.168.64.52
HTTP/1.1 307 Temporary Redirect
Content-Type: text/html; charset=utf-8
Location: https://192.168.64.52/
Date: Sat, 11 Apr 2020 17:11:46 GMT
Content-Length: 58

<a href="https://192.168.64.52/">Temporary Redirect</a>.

 chris@mandalore   ~/src/cscheib-fluxcd/workloads     master   curl -i http://192.168.64.51
HTTP/1.1 200 OK
Server: nginx/1.16.0
Date: Sat, 11 Apr 2020 17:11:48 GMT
Content-Type: text/html
Content-Length: 980
Last-Modified: Wed, 14 Aug 2019 20:50:55 GMT
Connection: keep-alive
ETag: "5d54742f-3d4"
Accept-Ranges: bytes

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Kashti</title>

  <link rel="apple-touch-icon" sizes="128x128" href="assets/images/icons/default/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="assets/images/icons/default/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/images/icons/default/favicon-16x16.png">

  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.56bbad704999d16e724b.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.a66f828dca56eeb90e02.js"></script><script type="text/javascript" src="polyfills.086a5b637f757f4c448b.js"></script><script type="text/javascript" src="scripts.f8a41137d5ecf8dd31f5.js"></script><script type="text/javascript" src="main.b2e8a34247df00f0cab7.js"></script></body>
```

**Comment by cscheib** [comment]
I'll rebuild this single-node cluster from scratch in a little while and verify that I can replicate all of this again.

**Comment by candlerb** [comment]
Then I guess it might be because I'm on macOS 10.14.6 (due to not having time to replace all 32-bit apps)

**Comment by cscheib** [comment]
@candlerb out of curiosity, did you have any loadbalancer services created during your testing?

metallb is only responding to IP addresses that have an active LB service assigned to them:

ARP from an IP within the MetalLB range, backed by a service:
``` 
chris@mandalore   ~/src/cscheib-fluxcd/workloads     master   sudo /usr/local/Cellar/arping/2.21_1/sbin/arping -i bridge100 192.168.64.51
ARPING 192.168.64.51
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.51): index=0 time=6.749 msec
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.51): index=1 time=2.095 msec
^C
--- 192.168.64.51 statistics ---
2 packets transmitted, 2 packets received,   0% unanswered (0 extra)
rtt min/avg/max/std-dev = 2.095/4.422/6.749/2.327 ms
```


ARP failure from an IP within the MetalLB range, not backed by a service:
```
 chris@mandalore   ~/src/cscheib-fluxcd/workloads     master   sudo /usr/local/Cellar/arping/2.21_1/sbin/arping -i bridge100 192.168.64.55
ARPING 192.168.64.55
Timeout
Timeout
Timeout
Timeout
^C
--- 192.168.64.55 statistics ---
5 packets transmitted, 0 packets received, 100% unanswered (0 extra)
```

**Comment by candlerb** [comment]
> @candlerb out of curiosity, did you have any loadbalancer services created during your testing?

Yes, as you'll see at https://github.com/ubuntu/microk8s/issues/908 (see `kubectl describe service www4`).  You can see both the LB address and the pod address it was forwarding to.

Also, the multipass ARP issue I was able to reproduce without microk8s, just by adding IP aliases to VMs: see https://github.com/canonical/multipass/issues/1298

**Comment by cscheib** [comment]
@candlerb the one thing I didn't see you try in your ip alias experiment is specifying the interface with arping.  I was not able to get arping to work properly without specifying the interface (bridge100) from the MacOS side.

This is the procedure I've used to replicate my environment multiple times:

```shell
multipass launch --name primary --mem 4G --disk 40G
multipass exec primary -- sudo snap install microk8s --classic --channel=1.18/stable
multipass exec primary -- sudo usermod -a -G microk8s ubuntu
multipass exec primary -- sudo chown -f -R ubuntu ~/.kube
multipass exec primary -- sudo iptables -P FORWARD ACCEPT
multipass exec primary -- /snap/bin/microk8s.enable dns metallb:192.168.64.50-192.168.64.100
```
From there, remaining steps to test/replicate would be:
* create any deployment
* expose deployment as a service of type LoadBalancer
* query the service to see which IP it received (almost certainly 192.168.64.50)
* `arping -i bridge100 <ip.ad.dr.ess>`
* `multipass exec primary -- sudo ip addr add 192.168.64.111/24 dev enp0s2`
* with bridge100: `arping -i bridge100 192.168.64.111`
* without bridge100: `arping 192.168.64.111`


my arping results with adding an ip via the ip addr method:
```
 chris@mandalore   ~/src/argocd-demo     master   sudo /usr/local/Cellar/arping/2.21_1/sbin/arping -i bridge100 192.168.64.111
ARPING 192.168.64.111
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.111): index=0 time=163.000 usec
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.111): index=1 time=508.000 usec
60 bytes from ca:3b:cc:0e:10:69 (192.168.64.111): index=2 time=173.000 usec
^C
--- 192.168.64.111 statistics ---
3 packets transmitted, 3 packets received,   0% unanswered (0 extra)
rtt min/avg/max/std-dev = 0.163/0.281/0.508/0.160 ms

 chris@mandalore   ~/src/argocd-demo     master   sudo /usr/local/Cellar/arping/2.21_1/sbin/arping 192.168.64.111
arping: libnet_init(LIBNET_LINK, <null>): libnet_ifaddrlist(): SIOCGIFADDR: dev=en5: Operation not permitted
```

**Comment by candlerb** [comment]
> the one thing I didn't see you try in your ip alias experiment is specifying the interface with arping

I *think* I tried this, I can't remember for sure.  However, what I definitely did record is that arping the VM primary address from macOS works fine; only arping for the alias fails (and surely it shouldn't be necessary to bind in the second case if the first works).

I then documented a more fundamental problem at https://github.com/canonical/multipass/issues/1298 which means this is irrelevant anyway:

* I build two VMs under multipass
* I add an alias to one of the VMs
* I arping the alias from the other VM

That doesn't work, and it should.  Both VMs have only a single interface, so there's definitely no need to bind arping to an interface.  And as I said before, this problem is nothing to do with microk8s, since I haven't even installed microk8s in those two VMs.

If the above works for you, then most likely something has changed in macOS between 10.14 and 10.15.

**Comment by evantorrie** [comment]
I can confirm that MetalLB works fine for me with microk8s, multipass and MacOS 10.15. Apple must have changed HyperKit networking in Catalina 10.15 vs. Mojave 10.14, but this does work for me.

**Comment by andsens** [comment]
Could the ARP problem have something to do with the fact that metallb uses DNAT?
http://linux-ip.net/html/nat-dnat.html
> In a devilishly subtle difference, netfilter DNAT does not cause the kernel to answer ARP requests for the NAT IP, where iproute2 NAT automatically begins answering ARP requests for the NAT IP.

**Comment by candlerb** [comment]
I don't think so.  As mentioned above, HyperKit networking is broken in macOS 10.14 anyway.  Two HyperKit VMs on the same network can't ARP for each other's IP aliases.  This problem reproduces without even bringing metallb into the equation.

I think this issue can be closed, as it's nothing that microk8s or metallb can fix.

**Comment by candlerb** [comment]
Or before closing you might want to update the note which was added in https://github.com/canonical-web-and-design/microk8s.io/pull/205/files to say that this only applies to some versions of macOS.
