### ISSUE TITLE
1.17.3 to 1.17.4 x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by twfs** [ubuntu/microk8s#1114]
microk8s stopped working for me on a dev server when auto-snap-upgraded to 1.17.4 - I get x509 errors when the pause container is pulled from storage.googleapis.com but not sure why this occurs only after the upgrade and reverting the snap upgrade makes it work again. However, I need to install fresh to another server and can't because I can't install 1.17.3, installing 1.17.4 fresh on that new server causes the same issue as on the dev server. I am behind a zscaler SSL proxy filtering firewall. Separate docker and curl also have tls/x509 issues with pulling from storage.googleapis.com but still 1.17.3 microk8s does not have a problem, why is this - and pretty please can I have 1.17.3 on my new server!!?

Further info here: https://discuss.kubernetes.io/t/microk8s-1-17-3-to-1-17-4-x509-certificate-signed-by-unknown-authority/10467

I don't have 1.17.4 installed so can't attach the inspect?

Thanks

Tim

**Comment by ktsakalozos** [comment]
Hi @twfs, is there a way for me to reproduce the issue (eg what workload are you testing)? Thank you for reporting this.

**Comment by twfs** [comment]
This was just trying to run a basic container, e.g.:

kubectl run -i --tty --image rocker/r-ver test --restart=Never --rm /bin/sh

The output is:

Name:         test
Namespace:    default
Priority:     0
Node:         <SNIP>
Start Time:   Sat, 11 Apr 2020 03:18:21 +0100
Labels:       run=test
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  test:
    Container ID:  
    Image:         rocker/r-ver
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-p7k6f (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-p7k6f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-p7k6f
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                From                             Message
  ----     ------                  ----               ----                             -------
  Normal   Scheduled               <unknown>          default-scheduler                Successfully assigned default/test to <SNIP>
  Warning  FailedCreatePodSandBox  18s (x2 over 29s)  kubelet, <SNIP>  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to copy: httpReaderSeeker: failed open: failed to do request: Get "https://storage.googleapis.com/eu.artifacts.google-containers.appspot.com/containers/images/sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e": x509: certificate signed by unknown authority
  Warning  FailedCreatePodSandBox  6s (x4 over 72s)   kubelet, uk2as028.medimmune.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.1": failed to pull image "k8s.gcr.io/pause:3.1": failed to pull and unpack image "k8s.gcr.io/pause:3.1": failed to copy: httpReaderSeeker: failed open: failed to do request: Get "https://storage.googleapis.com/eu.artifacts.google-containers.appspot.com/containers/images/sha256:67ddbfb20a22d7c0ea0df568069e7ffc42378467402d04f28ecfa244e78c5eb8": x509: certificate signed by unknown authority

(using 1.17.4, but runs fine with 1.17.3). 

Does that help? Does 1.17.4 make use of storage.googleapis.com wheras 1.17.3 doesn't? 

Thanks

Tim
