### ISSUE TITLE
[Question] - How to manage multi user isolation?

### ISSUE THREAD

**Issue by ereil** [ubuntu/microk8s#1116]
I'm not sure how to manage multi user isolation with microk8s.

An practical way could be to create an own namespace for each user or group and map the linux user account to only use this namespace. Is this the correct way?
I think microk8s is by default AllwaysAllow, ABAC, right?
When using own namespaces for each user/group it's possible to define quota ressource restrictions (Only 2 gpus per user).

- create namespace for each user/group
- define permissions for namespaces (json, ABAC)?
- map linux user to automatically use the own namespace

Can someone help me to get the multi user isolation running?
Or are there other ways?

Thanks

**Comment by ereil** [comment]
Update:

The users should access the master node via ssh and should only have access to their own namespace. We want to use kubeflow/arena so the users need ssh access to the server

I have done following tasks:
- create user student1
- create namespace student1ns
- usermod -a -G microk8s student1     # add student1 to microk8s group
- sudo microk8s.kubectl config view --raw > $HOME/.kube/config  #generate config file for 
- edit basic_auth.csv and add password, user, etc for student1
- edit .kube/config of student1 and edit user, password and namespace

The user can now connect via ssh to the master node and microk8s kubectl get nodes is working.

But i think the user student1 has now full access to the complete cluster.
Is it possible to restrict the user rights (with basic auth) to only own namespace?

And also 'arena top nodes' is not working -> Unauthorized

I've made some steps forward but i don't know if this is the right way.
I've invest a lot of time of researching. But i can't find information on how to grant users access with microk8s, arena, etc.

Any help?
Thanks

**Comment by ereil** [comment]
It seems that microk8s is not using the local $HOME/.kube/config file:

Here is the config file of student1:
![Screenshot from 2020-04-15 16-51-41](https://user-images.githubusercontent.com/62931301/79352224-d87aa080-7f39-11ea-9717-9cf0f32a9fc2.png)

and here is the result of 'microk8s kubectl config view' under student1 user account:
![Screenshot from 2020-04-15 16-50-50](https://user-images.githubusercontent.com/62931301/79352342-006a0400-7f3a-11ea-9ce5-74759fea3ddf.png)

the system is not using credentials of student1, its using the credentials of admin.

Is $HOME/.kube/config not the right config file which microk8s is using?

**Comment by ktsakalozos** [comment]
Hi @ereil, `microk8s.kubeclt` is a wrapper around `kubectl` and it uses the kubeconfig file under `/var/snap/microk8s/current/credentials/client.config`. If you add users into the `microk8s` group (`usermod -a -G microk8s student1`) you are granting them admin access so you better not do that.

Instead, you can create the users by adding them to the `basic_auth.csv` file as you already did. Then you can enable Role Based Access Control (RBAC) [1] with `microk8s.enable rbac` and restrict user permissions using RBAC rules [2]. Actually you do not need to give users ssh access to the machine as the api server is available on all interfaces on port 16443. You just need to give your users their kubeconfig file and tell them to `snap install kubectl`.

For resource quota you can have a look at [3]. This doc describes how to set quota on namespaces. 

I am not sure if @knkski knows of kubeflow specific ways to restrict user permissions and appoint resources.

[1] https://kubernetes.io/docs/reference/access-authn-authz/rbac/
[2] google suggestion for restricting users in a namespace https://jeremievallee.com/2018/05/28/kubernetes-rbac-namespace-user.html
[3] https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/

**Comment by ereil** [comment]
Hi @ktsakalozos, thanks for your detailed explanation, perfect!
..i'm very familiar with ML, tensorflow and docker, but i'm new to k8s.

For my understanding: When i connect to kubernetes cluster via kubectl on a local workstation, i can use all kubectl commands (if user have permisson to) but microk8s commands are only on host node possible (and needs sudo, microk8s group)?

Than i have to try what's with kubeflow/arena, if arena commands (which are very useful for DL scientists, also very easy reporting of used and free gpus in cluster `arena top node`) are possible trough remote kubectl or needs further setup.

**Comment by ktsakalozos** [comment]
> For my understanding: When i connect to kubernetes cluster via kubectl on a local workstation, i can use all kubectl commands (if user have permisson to) but microk8s commands are only on host node possible (and needs sudo, microk8s group)?

Yes, this is correct.


> Than i have to try what's with kubeflow/arena, if arena commands (which are very useful for DL scientists, also very easy reporting of used and free gpus in cluster `arena top node`) are possible trough remote kubectl or needs further setup.

I did not get this. Based on the installation instructions at [1] you should not need any thing more than the kubeconfig file.

[1] https://github.com/kubeflow/arena/blob/master/docs/installation/INSTALL_FROM_BINARY.md

**Comment by knkski** [comment]
@ereil: Kubeflow has multi-user isolation if you'd like to just work within that ecosystem, instead of managing kubernetes users:

https://www.kubeflow.org/docs/components/multi-tenancy/overview/

**Comment by ereil** [comment]
@ktsakalozos  Perfect, its all running, thanks!
For people who wants to know here are the steps to do:

- create namespace for user
- create Role for full access to user namespace
- add user in basic_auth.csv
- bind role to user:
`kubectl create rolebinding rolebindingname --role full-access-usernamespace --user user1`
- it could be necessary to grant additional roles to user (view cluster nodes ect)
- generate Kubeconfig file for kubectl remote access from user workstation:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxxxxxxxxx
    server: https://xxx.xxx.xxx.xxx:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    namespace: usernamespace
    user: username
  name: user-context
current-context: user-context
kind: Config
preferences: {}
users:
- name: user1
  user:
    username: user1
    password: xxxxxxx (from basic_auth.csv)
```
- copy file 'config' to $home/.kube on workstation
- now you can use kubectl to connect the remote cluster, and it's automatically using the user namespace

@knkski Yes i know the multi-user feature from kubeflow. But kubeflow is in actual microk8s 1.18 not running smooth. It has some gui problems as reported in #1084 
Also there are one cool feature missing: to show in an easy way how many gpus are used/available due to (nearly all) tensorflow trainings are using gpus:

![Screenshot from 2020-04-21 21-42-51](https://user-images.githubusercontent.com/62931301/79906974-1f283900-8419-11ea-92b6-39167cb9b396.png)

Thanks
