### ISSUE TITLE
Running Microk8s in Docker Container has issues

### ISSUE THREAD

**Issue by CalvinHartwell** [ubuntu/microk8s#1117]
Hi all, 

I've been testing running microk8s as part of a CI/CD pipeline with Gitlab. Gitlab uses Docker-in-Docker (DID) to dynamically generate containers on the fly when new code is committed either to run tests or arbitrary code used as part of some build automation. It can also be used to generate new releases of container and push them to private registry for example. 

My idea was to use this functionality to perform a dynamic install of microk8s to run some k8s integration tests which can then be dynamically killed. It seems that the confinement of snaps causes some issues within the docker container but it requires some more troubleshooting. 

I found this thread on the subject: [https://forum.snapcraft.io/t/running-snaps-inside-docker-containers/869](https://forum.snapcraft.io/t/running-snaps-inside-docker-containers/869)

Has anyone else tested this? 

Cheers

**Comment by ktsakalozos** [comment]
This is a duplicate of https://github.com/ubuntu/microk8s/issues/233

**Comment by trulede** [comment]
I suggest taking a look a Kaniko from GoogleContainerTools. With that you can build Docker Containers without needing Docker. Its a pure Kubernetes solution.

When I run a CI/CD "pipeline", I deploy to a K8s namespace, run some tests, and then blow away the namespace to cleanup the mess. All of that can be scripted via the K8s API's, with Python or Go (and other languages I guess).

**Comment by balchua** [comment]
May not be related to Docker, but as an alternative Gitlab CI happens to support lxd runner. 
https://docs.gitlab.com/runner/executors/custom_examples/lxd.html

You can run microk8s in lxc/lxd. I imagine you can use lxd to build your images, spin up microk8s, deploy and run your tests and finally throw away the lxd container.
