### ISSUE TITLE
Raspberry Pi 4B // Pods stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by iamroddo** [ubuntu/microk8s#1118]
I have a 2-node Raspberry Pi 4B cluster running Ubuntu installed with "sudo snap install microk8s --channel=1.18 --classic".

I have enabled cgroups. 
ubuntu@rod-k8s-0:~$ cat /boot/firmware/nobtcmd.txt
cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 net.ifnames=0 dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc

Pods, no matter what the namespace used, get stuck in CrashLoopBackOff.

The logs for the stuck pods always have a single message.
standard_init_linux.go:207: exec user process caused "exec format error"

I have tried ubuntu 18.04 & 19.10, with the nodes as singletons and in a cluster, always the same behaviour.

What am I doing wrong?
[inspection-report-20200415_034511.tar.gz](https://github.com/ubuntu/microk8s/files/4479086/inspection-report-20200415_034511.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @iamroddo. I believe the image you are using is not for arm64 (`gcr.io/kuar-demo/kuard-amd64:blue`).

**Comment by ktsakalozos** [comment]
Please reopen this issue if the problem persists.
