### ISSUE TITLE
microk8s fails pulling images from github packages

### ISSUE THREAD

**Issue by bountin** [ubuntu/microk8s#1120]
I fell down the same issue as described in https://github.com/containerd/containerd/issues/3879 but with github packages.

It is understandable that the upgrade to 1.3 is postponed as described in #702 but upgrading to the last 1.2 version (1.2.12) should be possible, right? According to the linked report, >=1.2.9 should help.

**Comment by svweber** [comment]
Did you get it working? I’m experiencing also issues with a private registry.

**Comment by bountin** [comment]
> Did you get it working? I’m experiencing also issues with a private registry.

Yes and no. I didn't want to build my own microk8s package, so I (temporarily) switched to a paid plan of Docker hub.

**Comment by balajiv113** [comment]
The same issue appears for registry.access.redhat.com registry also.

**Comment by AntonioL** [comment]
Also for Amazon ECS.
