### ISSUE TITLE
Nothing to do for knative - Raspberry Pi

### ISSUE THREAD

**Issue by jasonmccallister** [ubuntu/microk8s#1132]
I am running microk8s on a local Raspberry Pi 4 cluster. I have multiple nodes, but it appears that a lot of the add-ons are missing from `microk8s.enable` such as knative.

I am going on a limb, but I am assuming that knative is not an option for Raspberry Pis? I am following this guide here: https://ubuntu.com/blog/getting-started-with-knative-1

Inspection report:
[inspection-report-20200421_220745.tar.gz](https://github.com/ubuntu/microk8s/files/4512839/inspection-report-20200421_220745.tar.gz)

**Comment by jasonmccallister** [comment]
Just verified by looking in `/snap/microk8s/current/addon-lists.yaml` and can confirm that most of the tools I'm looking for are not available on `arm64`. Is there a way to denote this in the add-ons documentation?

**Comment by jasonmccallister** [comment]
I'm good to close this out, but I think the error message could be a little more informative.

**Comment by ktsakalozos** [comment]
@jasonmccallister what tools would you be interested in having on MicroK8s on arm?

You could open a feature request (or a pull request) so we can try to find time to work on them. Just make sure the software you are asking for is available on ARM64.

You are right, we should update the docs to make clear what addons are not available on ARM.

**Comment by jasonmccallister** [comment]
Thanks @ktsakalozos, I think the issue is that most of what I was looking for is not available on ARM64 (e.g. Istio and Linkerd). 

I think again the output is what threw me off. Something along the lines of `Linkerd is not available on ARM64` would be more clear and not cause me to make sure I did not screw something up. Happy to make a PR if/when I get some time.
