### ISSUE TITLE
Arm64, cannot deploy in default namespace

### ISSUE THREAD

**Issue by Xevious202** [ubuntu/microk8s#1138]
Hello all,
Microk8s cluster is up and online, cannot deploy any samples found online, even a simple "run" such as: `$ sudo microk8s.kubectl run http --image=katacoda/docker-http-server:latest`

I believe this issue is related to Arm64/x86 architecture more than RPI, as I had the same issue in EC2 AWS Arm64, but not in AWS x86.

Hardware/software information:
(4) Raspberry Pi 4: 4Gb
Ubuntu: 19.10 (GNU/Linux 5.3.0-1022-raspi2 aarch64)
Microk8s Kubernetes: Client & Server Version 1.18.0

They all come back with the same issue;
![image](https://user-images.githubusercontent.com/26842830/80128505-c44f2880-8563-11ea-90ea-d478e8dc7e44.png)

I removed and reinstalled the microk8s snap in order to try and isolate the issue. 

Previously the cluster had grafana/kubernetes dashboard running with the same error, crashloop img below;
![image](https://user-images.githubusercontent.com/26842830/80128621-efd21300-8563-11ea-8e14-a8d2535f1f1f.png)

[inspection-report-20200423_164549.tar.gz](https://github.com/ubuntu/microk8s/files/4524034/inspection-report-20200423_164549.tar.gz)

Cannot identify the issue, kube-system namespace with baked-in services appears to work fine, but default namespace does not.

I've documented the original install here; https://github.com/Xevious202/RPI-Kubernetes

**Comment by balchua** [comment]
@Xevious202 the image you mentioned above `katacoda/docker-http-server:latest` doesn't have the arm64 architecture. It is based on linux amd64.
Based on dockerhub the os/arch is listed as `linux/amd64`

**Comment by Xevious202** [comment]
> @Xevious202 the image you mentioned above `katacoda/docker-http-server:latest` doesn't have the arm64 architecture. It is based on linux amd64.
> Based on dockerhub the os/arch is listed as `linux/amd64`
> Usually arm images have a different tag.
> Thanks.

I’m sure you’re right. I’m still very much an amateur. Thanks so much, I’ll verify this fix in about an hour by finding an arm deployment!
