### ISSUE TITLE
Microk8s network implementation is faulted. SNAT issue.

### ISSUE THREAD

**Issue by peix2** [ubuntu/microk8s#1139]
Default installation of Microk8s fails test from "Kubernetes tutorial" described here:
https://kubernetes.io/docs/tutorials/services/source-ip/

Full output of test below:

```
px2@sm3:~$ kubectl config set-context --current --namespace=test
Context "microk8s" modified.
px2@sm3:~$ kubectl create deployment source-ip-app --image=k8s.gcr.io/echoserver:1.4

deployment.apps/source-ip-app created
px2@sm3:~$ 
px2@sm3:~$ kubectl expose deployment source-ip-app --name=clusterip --port=80 --target-port=8080
service/clusterip exposed
px2@sm3:~$ kubectl run busybox -it --image=busybox --restart=Never --rm^C
px2@sm3:~$ kubectl get svc
NAME        TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
clusterip   ClusterIP   10.152.183.84   <none>        80/TCP    17s
px2@sm3:~$ kubectl run busybox -it --image=busybox --restart=Never --rm
If you don't see a command prompt, try pressing enter.
/ # ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if7: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue 
    link/ether 06:e8:ba:a1:40:d9 brd ff:ff:ff:ff:ff:ff
    inet 10.1.95.3/24 scope global eth0
       valid_lft forever preferred_lft forever
/ # wget -qO - 10.152.183.84
CLIENT VALUES:
client_address=10.1.95.1
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.152.183.84:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
connection=close
host=10.152.183.84
user-agent=Wget
BODY:
-no body in request-/ # 
```

IP address expected to be presented is busybox pod IP address - 10.1.95.3
IP address presented as source reach out service - 10.1.95.1

This means that packets are being SNATed. 
A side effect of this bug is inability of using revDNS inside cluster.

Inspection report attached.
[inspection-report-20200424_164356.tar.gz](https://github.com/ubuntu/microk8s/files/4526706/inspection-report-20200424_164356.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @peix2 thank you for reporting this.

Could you do the following two changes:
1. In `/var/snap/microk8s/current/args/flanneld` add this argument `--ip-masq=true`
1. In `/var/snap/microk8s/current/args/kube-proxy` update the argument `--cluster-cidr=10.1.0.0/16`
1. Restart flanneld and kube-proxy `sudo systemctl restart snap.microk8s.daemon-proxy` and `sudo systemctl restart snap.microk8s.daemon-flanneld`
1. Delete the test namespace `microk8s kubectl delete ns test`

Then rerun the test above.

I would like to look more into the effects of `--ip-masq=true` before fixing this in the default arguments we run with https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/flanneld .

**Comment by peix2** [comment]
Hi @ktsakalozos ,

Done as requested:
`root@sm3:~# kubectl create deployment source-ip-app --image=k8s.gcr.io/echoserver:1.4
deployment.apps/source-ip-app created
root@sm3:~# kubectl expose deployment source-ip-app --name=clusterip --port=80 --target-port=8080
service/clusterip exposed
root@sm3:~# kubectl get svc clusterip
NAME        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
clusterip   ClusterIP   10.152.183.120   <none>        80/TCP    6s
root@sm3:~# kubectl run busybox -it --image=busybox --restart=Never --rm
If you don't see a command prompt, try pressing enter.
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if9: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue 
    link/ether 5a:9a:16:85:0c:90 brd ff:ff:ff:ff:ff:ff
    inet 10.1.95.5/24 scope global eth0
       valid_lft forever preferred_lft forever
/ # wget -qO - 10.152.183.120
^C
/ # wget -qO - 10.152.183.120
wget: can't connect to remote host (10.152.183.120): Connection timed out
/ # 
/ # pod "busybox" deleted
pod default/busybox terminated (Error)
root@sm3:~# kubectl get pod
NAME                             READY   STATUS    RESTARTS   AGE
source-ip-app-5b85689676-mdgqf   1/1     Running   0          9m25s
`

It looks like this breaks networking. "Server" pod is running, service is assigned but client cannot reach it. 
Below files with changes:
`root@sm3:/var/snap/microk8s/current/args# cat flanneld 
--iface=""
--etcd-endpoints=https://127.0.0.1:12379
--etcd-cafile=${SNAP_DATA}/certs/ca.crt
--etcd-certfile=${SNAP_DATA}/certs/server.crt
--etcd-keyfile=${SNAP_DATA}/certs/server.key
--subnet-file=${SNAP_COMMON}/run/flannel/subnet.env
--ip-masq=true
root@sm3:/var/snap/microk8s/current/args# cat kube-proxy 
--kubeconfig=${SNAP_DATA}/credentials/proxy.config
--cluster-cidr=10.1.0.0/16
--healthz-bind-address=127.0.0.1
root@sm3:/var/snap/microk8s/current/args# 
`

**Comment by ktsakalozos** [comment]
@peix2 I put up a PR with the above fix https://github.com/ubuntu/microk8s/pull/1145. 

In github action check https://github.com/ubuntu/microk8s/pull/1145/checks?check_run_id=619747799 you can find the microk8s snap as a build artifact. It would be great if you downloaded and extracted the .zip file in order to install the build snap with `sudo snap install ./microk8s.snap --classic --dangerous` and see if the issue persists. Thank you.

**Comment by peix2** [comment]
Hi @ktsakalozos ,

Thanks for taking care of it. 
Result is same as before when you asked me to modify files, restart and re-try.
Have a look:
```
px2@px2-ThinkPad-W540 ~ $ sudo snap install /tmp/microk8s.snap --classic --dangerous
microk8s v1.18.2 installed
px2@px2-ThinkPad-W540 ~ $ microk8s.status
microk8s is not running. Use microk8s inspect for a deeper inspection.
px2@px2-ThinkPad-W540 ~ $ microk8s.start
Started.
Enabling pod scheduling
node/px2-thinkpad-w540 already uncordoned
px2@px2-ThinkPad-W540 ~ $ microk8s.config > .kube/config 
px2@px2-ThinkPad-W540 ~ $ kubectl get pod -A
No resources found
px2@px2-ThinkPad-W540 ~ $ kubectl create ns test
namespace/test created
px2@px2-ThinkPad-W540 ~ $ kubectl config set-context --current --namespace=test
Context "microk8s" modified.
px2@px2-ThinkPad-W540 ~ $ kubectl create deployment source-ip-app --image=k8s.gcr.io/echoserver:1.4
deployment.apps/source-ip-app created
px2@px2-ThinkPad-W540 ~ $ kubectl get nodes
NAME                STATUS   ROLES    AGE     VERSION
px2-thinkpad-w540   Ready    <none>   4m59s   v1.18.2-41+571940263f7692
px2@px2-ThinkPad-W540 ~ $ kubectl expose deployment source-ip-app --name=clusterip --port=80 --target-port=8080
service/clusterip exposed
px2@px2-ThinkPad-W540 ~ $ kubectl get svc clusterip
NAME        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
clusterip   ClusterIP   10.152.183.212   <none>        80/TCP    5s
px2@px2-ThinkPad-W540 ~ $ kubectl run busybox -it --image=busybox --restart=Never --rm
If you don't see a command prompt, try pressing enter.
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if109: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue 
    link/ether 76:f2:12:c0:48:b8 brd ff:ff:ff:ff:ff:ff
    inet 10.1.9.3/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::74f2:12ff:fec0:48b8/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever
/ # wget -qO - 10.152.183.212
wget: can't connect to remote host (10.152.183.212): Connection timed out
/ # 

```

So it looks like this setting breaks up networking.

**Comment by ktsakalozos** [comment]
Would you be able to attach a `microk8s.inspect` tarball?

**Comment by peix2** [comment]
[inspection-report-20200428_192812.tar.gz](https://github.com/ubuntu/microk8s/files/4544004/inspection-report-20200428_192812.tar.gz)

**Comment by peix2** [comment]
@ktsakalozos, wondering if you plan to work more on that in the nearest future or this one is out of priority at the moment?

**Comment by ktsakalozos** [comment]
@peix2 the issue you report is confirmed. The fix I thought I had (see the PR) works for me, it passed the review but you report it is not working on your setup so I did not go ahead with the merge. I am not sure how to proceed. Have you tried any configuration that worked?

**Comment by ktsakalozos** [comment]
@peix2 could you try to load br_netfilter with `modprobe br_netfilter` after installing the snap in the proposed PR?

**Comment by peix2** [comment]
@ktsakalozos I have repeated test with br_netfilter loaded - indeed, it hasn't been loaded before - good spot.

```
px2@px2-ThinkPad-W540 ~ $ kubectl get pod
No resources found in test namespace.
px2@px2-ThinkPad-W540 ~ $ kubectl create ns test
namespace/test created
px2@px2-ThinkPad-W540 ~ $ kubectl get svc
No resources found in test namespace.
px2@px2-ThinkPad-W540 ~ $ kubectl create deployment source-ip-app --image=k8s.gcr.io/echoserver:1.4
deployment.apps/source-ip-app created
px2@px2-ThinkPad-W540 ~ $ kubectl get po
NAME                             READY   STATUS    RESTARTS   AGE
source-ip-app-5b85689676-gxv2j   1/1     Running   0          6s
px2@px2-ThinkPad-W540 ~ $ kubectl expose deployment source-ip-app --name=clusterip --port=80 --target-port=8080
service/clusterip exposed
px2@px2-ThinkPad-W540 ~ $ kubectl get svc
NAME        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
clusterip   ClusterIP   10.152.183.252   <none>        80/TCP    6s
px2@px2-ThinkPad-W540 ~ $ kubectl run busybox -it --image=busybox --restart=Never --rm
If you don't see a command prompt, try pressing enter.
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if144: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue 
    link/ether a2:fe:e4:60:c1:cd brd ff:ff:ff:ff:ff:ff
    inet 10.1.9.38/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a0fe:e4ff:fe60:c1cd/64 scope link tentative dadfailed 
       valid_lft forever preferred_lft forever
/ # wget -qO - 10.152.183.252
CLIENT VALUES:
client_address=10.1.9.38
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.152.183.252:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
connection=close
host=10.152.183.252
user-agent=Wget
BODY:
-no body in request-/ # 

```

That means it works!

Why I was looking into that is because I ran multinode cluster based on microk8s and this was breaking my app behaviour when certain pods been located on different nodes. In the meantime I just went with vanilla k8s and that works, so not much more environment to test it on multinode, however question is still valid - will it work in multinode setup as well?

**Comment by ktsakalozos** [comment]
@peix2 good to hear we solved this mystery. I updated the attached PR to try an load the br_netfilter module. This setup seems to work fine in multinode setups. Thank you for helping in fixing this.

**Comment by peix2** [comment]
Due diligence I will test it later on multinode setup and close this ticket in case of successful test.

**Comment by peix2** [comment]
Tested on 2 node deployment where server and client pods are on different nodes and all works as it should. Problem solved. Again, thanks @ktsakalozos for taking care of it.
