### ISSUE TITLE
Unable to enable istio on microk8s.

### ISSUE THREAD

**Issue by oliwave** [ubuntu/microk8s#1142]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
[inspection-report-20200425_062225.tar.gz](https://github.com/ubuntu/microk8s/files/4532474/inspection-report-20200425_062225.tar.gz)

After executed this command : `microk8s.enable istio`

It always showed : 
> Nothing to do for istio

Thanks in advance.

**Comment by balchua** [comment]
Istio is not supported on arm64 arch.

**Comment by TUT-jiayou** [comment]
HI, all 
     I want to know if Istio is supported on arm64 arch.

**Comment by stevekerrison** [comment]
@TUT-jiayou There are `arm64` builds of `istio` now, but to try it you'd have to use `istioctl` rather than the Istio support within the `microk8s` tool: https://istio.io/latest/docs/setup/install/istioctl/#customizing-external-charts-and-profiles
