### ISSUE TITLE
New node does not show up after `microk8s join`

### ISSUE THREAD

**Issue by zhanxw** [ubuntu/microk8s#1146]
Both machines are behind the firewall, can ping each other, use microk8s v1.8/stable from snap.

I can run `microk8s add-node` and `microk8s join xxx:25000/token`. No error messages were printed. But `microk8s.kubectl get no` only shows the master node and not the slave node.

The master/slave nodes logs are attached.
[slave.inspection-report-20200426_075951.tar.gz](https://github.com/ubuntu/microk8s/files/4535347/slave.inspection-report-20200426_075951.tar.gz)
[master.inspection-report-20200426_080001.tar.gz](https://github.com/ubuntu/microk8s/files/4535348/master.inspection-report-20200426_080001.tar.gz)

**Comment by balchua** [comment]
Thanks for reporting.  Few things i noticed.
1. Requests seems to be routing to your proxy.  Perhaps your have configured the env var `https_proxy` or `http_proxy`  without adding `no_proxy` to exclude the machines.
2.  Is the firewall configured to allow ports as defined here? https://microk8s.io/docs/ports

**Comment by zhanxw** [comment]
Just found that our proxy blocks all ip-based access.

Can I join with name, e.g. `microk8s join domain:25000/token` instead of `microk8s join ip:25000/token`?

**Comment by balchua** [comment]
Hmmm.  It's worth a try, but IIRC the worker node is registered to the master node with its IP.

**Comment by zhanxw** [comment]
Thanks @balchua . I tried and failed, as the proxy blocks all IP-based accesses.
