### ISSUE TITLE
Failed to create pod sandbox: no IP addresses available in range set

### ISSUE THREAD

**Issue by duclm2609** [ubuntu/microk8s#1147]
After a fresh installation of microk8s, I try to enable the dashboard UI but it stuck at state ContainerCreate. Below is event log:

Warning  FailedCreatePodSandBox  2m52s (x35156 over 5d7h)  kubelet, 10.1.121.33  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9a1b3fd9596e428093232c054a1ac7fac47a57c87f5c46dd80dde72e5bbea132": failed to allocate for range 0: no IP addresses available in range set: 10.1.56.1-10.1.56.254

I've noticed that many other pods also has failed to start of the same reason. I've attach the inspect tar. Hope this help.
[inspection-report-20200426_231811.tar.gz](https://github.com/ubuntu/microk8s/files/4535916/inspection-report-20200426_231811.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @duclm2609, in the VM you have MicroK8s running on do you have a 10.1.X.Y network attached? The 10.1.0.0/16 is the network where pods get IPs from.
