### ISSUE TITLE
Update asciicinema on getting started page

### ISSUE THREAD

**Issue by chrisroat** [ubuntu/microk8s#1148]
The example shown installs 1.12, whereas the command snippets right above the example install 1.18.  The example falls apart at the nginx section (less than half-way through) on 1.18 because `--replicas`` has been deprecated and no deployment is made.  A bit jarring for someone who is just getting started!

I also found the example sluggish as I ran it, as a `microk8s.kubectl get all` produced 6 `Throttling request too X.XXXXs...` logging statements and took about 20 seconds to run.  I'm not sure if that is a problem with the example, or with my beginner's setup, though.

**Comment by balchua** [comment]
Thanks @chrisroat for pointing the stale screencast.  Yes this should be updated to reflect the current version.

Wrt to the slow response when doing `microk8s kubectl`, my guess is that it is due to your `$HOME/.kube` contents owned by root.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @chrisroat the asciinema will soon be updated to https://asciinema.org/a/18zR8APlrKmgQQmlnTZHNeHkW

**Comment by chrisroat** [comment]
New example works great.  Thanks for putting that together.  Also, I switched group on the ~/.kube directory and things are much more responsive.
