### ISSUE TITLE
Kubelet Authentication (Port 10250)

### ISSUE THREAD

**Issue by egeloen** [ubuntu/microk8s#1151]
Hello,

I' trying to configure metricbeat to fetch metric for my microk8s cluster. All is working so far except the authentication part on the kublet port 10250 using https.

When looking the [doc](https://microk8s.io/docs/ports), I noticed the API needs an x509 client certificate to authenticate. I have looked into `/var/snap/microk8s/current/certs` and found some certificates (especially kubelet.crt & kubelet.key) but when using them I still get a 401 status code.

Can you point me how can I auth into the kubelet port 10250 ?

**Comment by balchua** [comment]
@egeloen you may want to use the bearer token for the kubelet along with the certs you already have to establish https. 
 The token can be found in `/var/snap/microk8s/current/credentials/known_tokens.csv` and look for the one assigned to the kubelet.

**Comment by mcadam** [comment]
@egeloen did that fix it for you? I am running in the same issue. thanks

**Comment by egeloen** [comment]
@mcadam No, for now, I have disabled TLS by using `insecure-skip-tls-verify: true` in my kubeconfig :(I'm able to authenticate on it but without TLS), it's not a solution on a long run, I will need to investigate how to make it working. If you find a solution, it would be very appreciated :)
