### ISSUE TITLE
/snap/microk8s/136/microk8s-config.wrapper: line 38: netstat: command not found

### ISSUE THREAD

**Issue by setharnold** [ubuntu/microk8s#1176]
Hello, the microk8s.config script appears to rely on the older `netstat(8)` and `ifconfig(8)` executables rather than using `ip route` and `ip addr`. `netstat(8)` and `ifconfig(8)` were removed from Ubuntu 20.04 (and perhaps earlier):

```
$ microk8s.config 
/snap/microk8s/136/microk8s-config.wrapper: line 38: netstat: command not found
/snap/microk8s/136/microk8s-config.wrapper: line 39: ifconfig: command not found
apiVersion: v1
clusters:
- cluster:
    server: http://:8080
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    username: admin
```

(Skipping the inspect, it doesn't feel relevant.)

Thanks

**Comment by ktsakalozos** [comment]
Hi @setharnold are you on ppc? This architecture is not actively maintained. Would it be possible to switch to amd64 or arm64? The issue you are reporting is addressed on those archs.

**Comment by setharnold** [comment]
On Tue, May 05, 2020 at 10:40:43PM -0700, Konstantinos Tsakalozos wrote:
> Hi @setharnold are you on ppc? This architecture is not actively
> maintained. Would it be possible to switch to amd64 or arm64? The issue
> you are reporting is addressed on those archs.

Ah, I'm glad to hear it's been addressed. My power9 is the biggest
machine I have that's not already allocated to something, so I thought
it'd be an ideal place to learn microk8s. Fast IO, lots of threads, it
seemed like a perfect fit.

Thanks
