### ISSUE TITLE
Microk8s Insecure Registry not working

### ISSUE THREAD

**Issue by cetiberiojr** [ubuntu/microk8s#1179]
Hi Guys,

I’m configuring my microk8s and I’m having a stranger issue and don’t know anymore how to check it… I know the configurations are ok… at least, it should.

I have a registry I can access only as HTTP (insecure), if I point to my browser, I can see the HTTPS is not accessible but HTTP is (/v2/_catalog)

So, I configured the /var/snap/microk8s/current/args/containerd-template.toml with the following:

```
[plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."localhost:32000"]
          endpoint = ["http://localhost:32000"]
        [plugins.cri.registry.mirrors."myregistry.domain.com:5000"]
          endpoint = ["http://myregistry.domain.com:5000"]
```
restarted microk8s:

```
microk8s stop
microk8s start
```
tried to pull the image:

```
microk8s ctr --debug images pull myregistry.domain.com:5000/image:latest

DEBU[0000] fetching                                      image="myregistry.domain.com:5000/image:latest"
DEBU[0000] resolving                                    
DEBU[0000] do request                                    request.headers=map[Accept:[application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, *]] request.method=HEAD url="https://myregistry.domain.com:5000/v2/image/manifests/latest"
ctr: failed to resolve reference "myregistry.domain.com:5000/image:latest": failed to do request: Head "https://myregistry.domain.com:5000/v2/image/manifests/latest": http: server gave HTTP response to HTTPS client
```
He is still trying to access the HTTPS…

Can someone help me here?

Seems like microk8s is not picking up the updated file…

Ps.: I don’t have docker installed or anything, I’m using only the microk8s

Those are the addons installed:

```
microk8s is running
addons:
dashboard: enabled
dns: enabled
helm: enabled
registry: enabled
storage: enabled
cilium: disabled
fluentd: disabled
gpu: disabled
helm3: disabled
ingress: disabled
istio: disabled
jaeger: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
prometheus: disabled
rbac: disabled
```

**Comment by balchua** [comment]
Can you try removing the `localhost:32000` registry in the `containerd.conf.template`? I've experienced this before.  The containerd v1.2.5 seems to be buggy when it comes to insecure registry.

**Comment by cetiberiojr** [comment]
Hi @balchua, tested removing the `localhost:32000` restarted and I'm still having the same issue :(

**Comment by double73** [comment]
You should add '--plain-http' option like this
`microk8s ctr --debug images pull --plain-http myregistry.domain.com:5000/image:latest`

**Comment by cetiberiojr** [comment]
The `--plain-http` worked,
BUT
the configuration on `containerd.conf.template` doesn't work anymore? if I want to install a pod, he will know that he should use the http?

**Comment by ktsakalozos** [comment]
Containerd should know this is an insecure http registry. Have a look at https://microk8s.io/docs/registry-private

**Comment by njleon007** [comment]
@ktsakalozos 
I use microk8s to be a CI/CD cluster, run all jobs in k8s with unsecurity registry.
 I find --plain-http is always worked.
microk8s ctr images pull --plain-http myregistry.domain.com/image:latest

**Comment by double73** [comment]
Please make sure /var/snap/microk8s/current/args/containerd.toml has your registry settings
It will be updated when after microk8s stop/start

**Comment by double73** [comment]
If the pod is running in a worker node, not a master, it should also be microk8s stop/started there.

**Comment by ktsakalozos** [comment]
Restarting services on nodes is also possible with systemctl, for example: `systemctl restart snap.microk8s.daemon-containerd`

**Comment by njleon007** [comment]
> If the pod is running in a worker node, not a master, it should also edit containerd-template.toml and microk8s stop/started there.
> 
> But it said "This MicroK8s deployment is acting as a node in a cluster. Please use the microk8s stop on the master."
> 
> So, you have to reboot the system

@double73 , need restart all system? including master and nodes?
I think restart containerd and microk8s should be OK.

**Comment by double73** [comment]
Each worker node has to restart the containerd using @ktsakalozos' suggested command.

**Comment by njleon007** [comment]
@double73 thanks for your help, k8s pod can pull image from my registry.

**Comment by balchua** [comment]
@cetiberiojr are you still getting this issue?

**Comment by njleon007** [comment]
@double73 @balchua 
Sorry to ask for help again.
Occasionally, I find some image can not pull from my insecure registry. I find the kubelet log：

> journal.log:Jun 01 17:05:21 ubuntu21 microk8s.daemon-kubelet[99968]: E0601 17:05:21.666824   99968 pod_workers.go:191] Error syncing pod 8121befc-aa7e-4064-9ca9-0d369fa6a46b ("runner-sdmjyg-s-project-73-concurrent-2vjwlh_gitlab-ci-cpu(8121befc-aa7e-4064-9ca9-0d369fa6a46b)"), skipping: failed to "StartContainer" for "build" with ErrImagePull: "rpc error: code = Unknown desc = failed to resolve image \"dockerhub.company.com/xx-ci:latest\": no available registry endpoint: failed to do request: Head \"https://dockerhub.company.com/v2/xx-ci/manifests/latest\": dial tcp 192.168.2.111:443: connect: connection refused"

still the https endpoint error, but I don't know what cause this unstable issue.
What I got from google
1. microk8s is not capable of IPV6,  I comment all ipv6 related from /etc/hosts
I guess it related to iptables/dns, but I don't know how to troubleshoot.

Thanks for help

**Comment by balchua** [comment]
@cetiberiojr mind uploading the `containerd.conf.template` here?

**Comment by njleon007** [comment]
@balchua attachment is the containerd-template.txt，I modify sandbox_image url and  add plugins.cri.registry section of my local insecure registry.

thanks for your reply.

[containerd-template.txt](https://github.com/ubuntu/microk8s/files/4714395/containerd-template.txt)

**Comment by balchua** [comment]
@njleon007 @cetiberiojr another request.
Can you also upload the `containerd.toml`? Thanks

**Comment by njleon007** [comment]
@balchua sure, thanks

[containerd.txt](https://github.com/ubuntu/microk8s/files/4717983/containerd.txt)

**Comment by njleon007** [comment]
@balchua @double73 
I find this issue is gone when I change master to unschedule pods.
I guess it's an io issue from etcd server.
