### ISSUE TITLE
setup_grafana defunct process

### ISSUE THREAD

**Issue by scottbisker** [ubuntu/microk8s#1181]
I have clean install of microk8s installed on an Ubuntu 20.04 vm.

I've run the following:
microk8s.enable cilium
microk8s.enable dns dashboard

After some time this results in setup_grafana going into a zombie state.

root        4691  0.0  0.0      0     0 ?        Z    19:47   0:00 [setup_grafana] <defunct>

I've tried without cilium as well and have the same issue.

[inspection-report-20200506_195412.tar.gz](https://github.com/ubuntu/microk8s/files/4589178/inspection-report-20200506_195412.tar.gz)

**Comment by balchua** [comment]
Doesn't necessarily answer your question, but i think we should retire the use of heapster, influx and grafana in this addon.

**Comment by ktsakalozos** [comment]
> we should retire the use of heapster, influx and grafana in this addon

+1 to that. @tvansteenburgh @joedborg wdyt?

@scottbisker you can get a prometheus based monitoring dashboard with the prometheus addon `microk8s enable prometheus`.

**Comment by balchua** [comment]
I've made a pr to update the dashboard as well as remove some of the resources that it used to include such as heapster, influx and grafana.
Its a bare bones dashboard, it also enables metrics-server to get the node metrics.

https://github.com/ubuntu/microk8s/pull/1201

**Comment by balchua** [comment]
@scottbisker the defunct grafana process you see is coming from the old dashboard addon, where old influx , heapster and old grafana is included.
We have since remove those in favor of barebones dashboard and metrics server.
It is available in the `edge` channel.
Is it ok to close this?
Thanks.

**Comment by scottbisker** [comment]
Yes.  It can be closed.

**Comment by balchua** [comment]
Thanks.
