### ISSUE TITLE
microk8s.enable kubeflow stuck at 2 remaining operator pods to come up

### ISSUE THREAD

**Issue by yashjakhotiya** [ubuntu/microk8s#1189]
When enabling kubeflow on an Azure VM with 16GB RAM and 4 CPUs, the waiting for operator pods to come up seems to take a long time. Right now the service has waited 3705s for operator pods to come up and 2 are still remaining. 

Moreover, the 'remaining operator pods' started with 23, decreased gradually and then increased to 26 before decreasing again. Is this behaviour common?
[inspection-report-20200511_105639.tar.gz](https://github.com/ubuntu/microk8s/files/4609156/inspection-report-20200511_105639.tar.gz)

**Comment by yashjakhotiya** [comment]
Update: I tried disabling and enabling it. The disabling got stuck so I killed that process and tried enabling. Now, `microk8s status` says, kubeflow is disabled but `microk8s enable kubeflow` says kubeflow has already been enabled. Stuck at this. Attaching my tmux screenshot here.
![2020-05-11-222958_1366x768_scrot](https://user-images.githubusercontent.com/26331636/81589671-3b474680-93d7-11ea-97ee-30d088866fcb.png)

**Comment by yashjakhotiya** [comment]
Another update - `ERROR cannot deploy bundle: cannot deploy application "metadata-ui": storage class "microk8s-hostpath": etcdserver: request timed out `

**Comment by natalytvinova** [comment]
Same issue. The problem is the misleading status in kubeflow.enable command. 
Kubeflow.enable shows that 2 pods remaining, when in fact, `microk8s.kubectl get to --all-namespaces ` shows that all pods are running. But if I do `microk8s.juju status` I can see that cert-manager-controller  and cert-manager-webhook charms are still in maintenance. They get active eventually and the problem resolves itself.

**Comment by knkski** [comment]
@yashjakhotiya: Can you update microk8s to the latest stable version (if snap hasn't automatically updated it)? cert-manager has been moved to a separate bundle, which should eliminate this issue.

**Comment by shivangicloud04** [comment]
@knkski I have  updated  the microk8s version tp 1.19. I am facing the same issue. Any other workaround?

**Comment by knkski** [comment]
@shivangicloud04: Is this still an issue for you with microk8s `latest/stable`?
