### ISSUE TITLE
microk8s.ctr does not support "images tag"

### ISSUE THREAD

**Issue by jetpackdanger** [ubuntu/microk8s#1191]
Occasionally I find myself wanting to manipulate image tags locally in the microk8s containerd. Unfortunately the version of ctr shipped (v1.2.5) is too old. Please consider upgrading it.

For reference, this subcommand was added in https://github.com/containerd/containerd/pull/3388

I've been working around this by bind-mounting a newer binary on top of the snap, but obviously that's pretty gross. :)

**Comment by balchua** [comment]
There is a PR to upgrade to 1.3.1 here.
Still pending review, this pr also upgraded the configuration to version 2.

https://github.com/ubuntu/microk8s/pull/838
