### ISSUE TITLE
Remove kube-apiserver insecure port (8080)

### ISSUE THREAD

**Issue by DazWilkin** [ubuntu/microk8s#1192]
This question has been asked before (#198) but I'm unclear on the resolution.

Like MicroK8s a lot... running v.1.16.8:

I'd like to avoid having kube-apiserver on 8080.

I reviewed /var/snap/microk8s/current/args/kube-apiserver but there's no obvious place here where its being configured to run on 8080. In fact, the only port referenced is the expected 16443:

However:

```
sudo ss --tcp --listening --processes | grep http-alt
```

Gets me `users:(("kube-apiserver",pid=130609,fd=5))` and `ps aux | grep kube-apiserver`:

```
/snap/microk8s/1302/kube-apiserver \
--cert-dir=/var/snap/microk8s/1302/certs \
--service-cluster-ip-range=10.152.183.0/24 \
--authorization-mode=AlwaysAllow \
--basic-auth-file=/var/snap/microk8s/1302/credentials/basic_auth.csv \
--service-account-key-file=/var/snap/microk8s/1302/certs/serviceaccount.key \
--client-ca-file=/var/snap/microk8s/1302/certs/ca.crt \
--tls-cert-file=/var/snap/microk8s/1302/certs/server.crt \
--tls-private-key-file=/var/snap/microk8s/1302/certs/server.key \
--kubelet-client-certificate=/var/snap/microk8s/1302/certs/server.crt \
--kubelet-client-key=/var/snap/microk8s/1302/certs/server.key \
--secure-port=16443 \
--token-auth-file=/var/snap/microk8s/1302/credentials/known_tokens.csv \
--token-auth-file=/var/snap/microk8s/1302/credentials/known_tokens.csv \
--etcd-servers=https://127.0.0.1:12379 \
--etcd-cafile=/var/snap/microk8s/1302/certs/ca.crt \
--etcd-certfile=/var/snap/microk8s/1302/certs/server.crt \
--etcd-keyfile=/var/snap/microk8s/1302/certs/server.key \
--requestheader-client-ca-file=/var/snap/microk8s/1302/certs/front-proxy-ca.crt \
--requestheader-allowed-names=front-proxy-client \
--requestheader-extra-headers-prefix=X-Remote-Extra- \
--requestheader-group-headers=X-Remote-Group \
--requestheader-username-headers=X-Remote-User \
--proxy-client-cert-file=/var/snap/microk8s/1302/certs/front-proxy-client.crt \
--proxy-client-key-file=/var/snap/microk8s/1302/certs/front-proxy-client.key
```
But still no obvious place where `8080` is being configured.

The guidance in the other comment was that, configuration is preserved and to clean-install. I'd prefer not to reinstall but, is this documented? Presumably more than just removing the snap?

I'd prefer to just understand where the port is configured so that I may remove it.

Thanks!

[inspection-report-20200512_132313.tar.gz](https://github.com/ubuntu/microk8s/files/4618295/inspection-report-20200512_132313.tar.gz)

**Comment by balchua** [comment]
Hi,

Can you go to `/var/snap/microk8s/current/args/kube-apiserver`
And add this `--insecure-port=0` like shown below?  

```
--etcd-keyfile=${SNAP_DATA}/certs/server.key
--insecure-port=0
```
Afaik setting `insecure-port=0` effectively turns off the insecure port.

After that you can restart microk8s.

```shell
$ microk8s.stop
$ microk8s.start
```
Let me know if this works.

**Comment by DazWilkin** [comment]
Outstanding! Thank you.

**Comment by balchua** [comment]
@DazWilkin can we close this issue?
Thanks!
