### ISSUE TITLE
microk8s stopped working after latest ubuntu update

### ISSUE THREAD

**Issue by rpdeadly** [ubuntu/microk8s#1193]
Hello.
           I am unable to produce a tarball using inspect or query using kubectl. The error message i get is "Unable to connect to the server: net/http: TLS handshake timeout". I'm running Ubuntu 18.04.4 LTS

Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Unable to connect to the server: net/http: TLS handshake timeout

We appreciate your feedback. Thank you for using microk8s.

**Comment by ktsakalozos** [comment]
Does this persist if you reinstall with `snap remove microk8s` and `snap install microk8s --classic`? Have you installed a specific channel?

**Comment by rpdeadly** [comment]
I'm running  v1.18.2 latest/stable version of microk8s. I did a reinstall and things are working again. Thanks @ktsakalozos
