### ISSUE TITLE
Multus does not create a second interface in POD

### ISSUE THREAD

**Issue by ednaganon** [ubuntu/microk8s#1194]
I would like to have a second flannel interface  in a pod using Multus. I have few questions
1. First try - since Flannel exists as the default network, i create only multus-daemonset.yml and flannel networkAattachmentDefinition network (but not flannel daemonset). Creating a test pod with the annotation - only eth0 created:

$ **kubectl -n=kube-system get po -o wide**
[sudo] password for eganon:
NAME                                              READY   STATUS    RESTARTS   AGE    IP            NODE          NOMINATED NODE   READINESS GATES
coredns-588fd544bf-sqmh5                          1/1     Running   2          17h    10.1.8.15     gr-05         <none>           <none>
dashboard-metrics-scraper-db65b9c6f-zb6sb         1/1     Running   2          17h    10.1.8.16     gr-05         <none>           <none>
heapster-v1.5.2-58fdbb6f4d-6jrm5                  4/4     Running   11         17h    10.1.8.14     gr-05         <none>           <none>
kube-multus-ds-amd64-9qvz9                        1/1     Running   0          172m   192.168.1.6   192.168.1.6   <none>           <none>
kube-multus-ds-amd64-dv8sl                        1/1     Running   1          172m   192.168.1.5   gr-05         <none>           <none>
kube-multus-ds-amd64-lpk7b                        1/1     Running   0          172m   192.168.1.8   192.168.1.8   <none>           <none>
kubernetes-dashboard-67765b55f5-p22jj             1/1     Running   2          17h    10.1.8.17     gr-05         <none>           <none>
monitoring-influxdb-grafana-v4-6dc675bf8c-hb95v   2/2     Running   4          17h    10.1.8.13     gr-05         <none>           <none>

**$ kubectl -n=kube-system get net-attach-def**
NAME      AGE
flannel   10h

**$ kubectl -n=kube-system describe net-attach-def**
Name:         flannel
Namespace:    kube-system
Labels:       <none>
Annotations:  API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2020-05-12T21:56:27Z
  Generation:          1
  Managed Fields:
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:config:
    Manager:         kubectl
    Operation:       Update
    Time:            2020-05-12T21:56:27Z
  Resource Version:  31308
  Self Link:         /apis/k8s.cni.cncf.io/v1/namespaces/kube-system/network-attachment-definitions/flannel
  UID:               cd965b92-922b-4381-827e-64ee976f00b1
Spec:
  Config:  {
    "cniVersion": "0.3.1",
    "plugins": [
      {
        "type": "flannel",
        "delegate": {
          "hairpinMode": true,
          "isDefaultGateway": true
        }
      },
      {
        "type": "portmap",
        "capabilities": {"portMappings": true},
        "snat": true
      }
    ]
}

Events:  <none>

**$ more workdir/plumb/multus-daemonset.yml**
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  version: v1
  scope: Namespaced
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    shortNames:
    - net-attach-def
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            config:
                 type: string
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: multus
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: multus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus
subjects:
- kind: ServiceAccount
  name: multus
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus
  namespace: kube-system
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "capabilities": {
        "portMappings": true
      },
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "default-cni-network",
          "plugins": [
            {
              "type": "flannel",
              "name": "flannel.1",
                "delegate": {
                  "isDefaultGateway": true,
                  "hairpinMode": true
                }
              },
              {
                "type": "portmap",
                "capabilities": {
                  "portMappings": true
                }
              }
          ]
        }
      ],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: multus
spec:
  selector:
    matchLabels:
      app: multus
  template:
    metadata:
      labels:
        tier: node
        app: multus
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      containers:
      - name: kube-multus
        image: nfvpe/multus:latest
        command: ["/entrypoint.sh"]
        args:
        - "--multus-conf-file=/tmp/multus-conf/70-multus.conf"
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
        - name: multus-cfg
          mountPath: /tmp/multus-conf
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
            - key: cni-conf.json
              path: 70-multus.conf

**$ sudo more /etc/cni/net.d/00-multus.conf**
{
  "name": "multus-cni-network",
  "type": "multus",
  "LogFile": "/var/log/multus.log",
"LogLevel": "debug",
  "capabilities": {
    "portMappings": true
  },
  "delegates": [
    {
      "cniVersion": "0.3.1",
      "name": "default-cni-network",
      "plugins": [
        {
          "type": "flannel",
          "name": "flannel.1",
            "delegate": {
              "isDefaultGateway": true,
              "hairpinMode": true
            }
          },
          {
            "type": "portmap",
            "capabilities": {
              "portMappings": true
            }
          }
      ]
    }
  ],
  "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
}
~**$ more workdir/pod-test.yml**
apiVersion: v1
kind: Pod
metadata:
  name: pod-test
  annotations:
    k8s.v1.cni.cncf.io/networks: flannel, flannel
spec:
  containers:
  - name: pod-test
    image: docker.io/centos/tools:latest
    command: ['sleep', '3600']

2. If I activate flannel-daemonset in addition to the built-in flannel, I get two flanneld processes, each one with different args, and I see in some of the nodes a clash in the pod-cidr between the two processes.

What is the right way to add a second flannel interface? should I have a flannel daemonset in addition to the built in flannel? if  yes - how to do it? if not what is wrong with the configuration I shared?

Thanks, Edna Ganon

**Comment by balchua** [comment]
Closing this issue.  Fixed by the multus addon available currently on edge channel.
