### ISSUE TITLE
Routing outbound traffic from pods on node with iptables not working

### ISSUE THREAD

**Issue by fieldju** [ubuntu/microk8s#1205]
I am trying to get something like kube2iam up and running with microk8s.

Basically the goal is to hijack traffic for all pods on a node that are making calls to http://169.254.169.254/latest/meta-data/iam/security-credentials and route them to a special endpoint in a container to turn annotations into AWS IAM credentials.

The service runs the following command at boot time.

```bash
iptables -t nat -A PREROUTING -p tcp -d ${metadataAddress} --dport 80 -j DNAT --to-destination ${hostIp}:${appPort} -i ${hostInterface}
```

example
```bash
iptables -t nat -A PREROUTING -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination 192.168.64.12:8181 -i docker0
```

This works on Minikube but doesn't work on Microk8s

MiniKube works
```bash
iptables -t nat -v -L PREROUTING -n --line-number
Chain PREROUTING (policy ACCEPT 15 packets, 1691 bytes)
num   pkts bytes target     prot opt in     out     source               destination      
3        0     0 DNAT       tcp  --  docker0 *       0.0.0.0/0            169.254.169.254      tcp dpt:80 192.168.64.12:8181
```

microk8s
```bash
iptables -t nat -v -L PREROUTING -n --line-number
Chain PREROUTING (policy ACCEPT 15 packets, 1691 bytes)
num   pkts bytes target     prot opt in     out     source               destination      
3        0     0 DNAT       tcp  --  docker0 *       0.0.0.0/0            169.254.169.254      tcp dpt:80 to:192.168.0.2:8181
```

Does something about mircrok8s and snaps make this impossible or is there a special configuration?

**Comment by ktsakalozos** [comment]
I am not sure exactly what may be wrong but here are some thoughts. Comparing the minikube and microk8s cases, what is the 192.168.0.2:8181 and why is this different than the 192.168.64.12:8181? The pods are on 10.1.0.0/16 and microk8s does not use docker0 I suspect the  192.168.64.12 is where the translation service is?

Could you please use the edge channel of microk8s? We recently addressed a routing issue described in https://github.com/ubuntu/microk8s/issues/1139

**Comment by fieldju** [comment]
> What is the 192.168.0.2:8181 and why is this different than the 192.168.64.12:8181?

Running `k get pod kube2iam-96d4d86db-b6gl6 -o yaml` on minikube

```yaml
...
status:
  ...
  hostIP: 192.168.64.12
  podIP: 192.168.64.12
  podIPs:
  - ip: 192.168.64.12
```

So its the IP of the virtual image where as on microk8s its the ip of the physical server (`192.168.0.2`) that I am running ubuntu 20.04 on.

The `8181` comes from the daemon set manifest

```yaml
...
          ports:
            - containerPort: 8181
              hostPort: 8181
              name: http
...
```

> The pods are on 10.1.0.0/16 and microk8s does not use docker0 I suspect the 192.168.64.12 is where the translation service is?

I can override this with a flag:

```golang
fs.StringVar(&s.HostInterface, "host-interface", "docker0", "Host interface for proxying AWS metadata")
```

Which is used here

```golang
	return ipt.AppendUnique(
		"nat", "PREROUTING", "-p", "tcp", "-d", metadataAddress, "--dport", "80",
		"-j", "DNAT", "--to-destination", hostIP+":"+appPort, "-i", hostInterface,
	)
```

> Could you please use the edge channel of microk8s? We recently addressed a routing issue described in #1139

I gave latest/edge a go and it didn't work, but I wonder if its because I am using `docker0` and I need to try a different value there.

**Comment by fieldju** [comment]
Digging into this more, I found this:

https://askubuntu.com/a/579540
![image](https://user-images.githubusercontent.com/711726/82364751-8c9d9a00-99c4-11ea-9491-074ba0081d44.png)

I think this might be my issue here, let me do a little spike and adjust the command and report back.

**Comment by fieldju** [comment]
Okay, running

```bash
iptables -t nat -A OUTPUT -p tcp -d 169.254.169.254 --dport 80 -j DNAT --to-destination 192.168.0.3:8181
```

Does have the effect I want, where as with `Minikube` you can use PREROUTING
