### ISSUE TITLE
apparmor rules prevent `exec`s onto pods

### ISSUE THREAD

**Issue by BigRedS** [ubuntu/microk8s#1214]
```
$ kubectl -n dev exec avigreenbury-support-7f86bfc5bf-7nl5t /bin/bash
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "f7bd8a289d551bb96fdd0dedd6251eb3669c058044889eb097b99343aea21ce8": OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "apparmor failed to apply profile: write /proc/self/attr/exec: operation not permitted": unknown
```

The fix is to add `/proc/self` to the exceptions in the regex `/etc/apparmor.d/cri-containerd.apparmor.d`

```
# grep Avi /etc/apparmor.d/cri-containerd.apparmor.d -A2
  # Avi 2020-05-21
  #deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
  deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9s][^0-9e][^0-9l][^0-9f]*}/** w,
```

This appears to be undone when microk8s is updated but I'm not sure how to tell what Snap's doing to files.

I haven't added an inspect tarball because I don't think this is that related (it feels like a snap packaging issue) and mine has some stuff in it that I can't share; I can replicate this on its own and add a tarball if need be.

**Comment by ktsakalozos** [comment]
Could you help me reproduce this? What channel are you using? Do you have containerd installed in the host? What distribution are you on? What is the workload you are running?

MicroK8s ships its own containerd so it is strange why you have to update the apparmor profile of containerd on the host.

**Comment by BigRedS** [comment]
Sorry, yeah, missed out _all_ the details there. This is just from a `snap install microk8s --classic` on Ubuntu 18.04:

```
$ snap list microk8s
Name      Version  Rev   Tracking       Publisher   Notes
microk8s  v1.18.2  1378  latest/stable  canonical✓  classic
```
I'd fixed this before (in this way), and had set that file to immutable. Later, a microk8s.start failed because it couldn't modify that file; I can probably replicate that and grab some relevant logs if that's the interesting bit, and you let me know which logs are relevant.

**Comment by balchua** [comment]
This could be related to [this](https://github.com/ubuntu/microk8s/issues/784)

Can you check if your prod has the security profile?
```yaml
securityContext:
         allowPrivilegeEscalation: false
```
A workaround mentioned is to reload the apparmor profile 
` sudo apparmor_parser -R /var/lib/snapd/apparmor/profiles/snap.microk8s.daemon-containerd`

**Comment by BigRedS** [comment]
Ah, yes, we are running with `allowPrivilegeEscalation: false`.

Curiously, the `apparmor_parser -r` doesn't help, but -R followed by -a (as initially suggested in #784) _does_ work: 

    sudo apparmor_parser -R /var/lib/snapd/apparmor/profiles/snap.microk8s.daemon-containerd
    sudo apparmor_parser -a /var/lib/snapd/apparmor/profiles/snap.microk8s.daemon-containerd

so I've got a reliable workaround here, thanks!
