### ISSUE TITLE
Replace flannel with calico

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1221]
Hi,

I've seen some scripts in the source for setting up calico and dqlite and this pr to change back to flannel https://github.com/ubuntu/microk8s/pull/1209. I have an installation via `sudo snap install microk8s --classic --channel=1.18/stable` Is there some way to do an installation or modify an installation to use calico that is part of the snap. I need network policies and from what I've read flannel doesn't support this and I would also rather not use cillium as it has quite high resource usage from what I understand.

**Comment by ktsakalozos** [comment]
Hi @sstubbs 

Calico is introduced for the HA work, have a look at [1]. You can get get to a calico based setup by installing MicroK8s from the `ha-preview` channel and then `microk8s enable ha-cluster`.

Could you provide some more info on the use case you have? You mention you have resource constraints, could you provide more details? The HA work also replaces etcd with dqlite. Is this a problem? Any network policy capable CNI would work? I haven't done any benchmarking, but cilium does not feel much heavier than calico. 

[1] https://github.com/ubuntu/microk8s/issues/1127#issuecomment-629651489

**Comment by sstubbs** [comment]
Ok thanks a lot. I will try it. Currently running kubenernetes on AWS but we still have some applications in vms on local servers which have some extra capacity. Our new work flow is quite reliant on kubernetes so I'm trying to see what I can do with these until everyhting is moved completely to kubernetes.

I will also try cillium. I read this https://itnext.io/benchmark-results-of-kubernetes-network-plugins-cni-over-10gbit-s-network-updated-april-2019-4a9886efe9c4 which is what made me think it has high resource usage but there won't be a lot of traffic to these anyway.
