### ISSUE TITLE
Upgrade Istio to 1.6 (major update)

### ISSUE THREAD

**Issue by tringuyen-yw** [ubuntu/microk8s#1222]
Istio has announced a major update [Announcing Istio 1.6](https://istio.io/news/releases/1.6.x/announcing-1.6/) on 2020-05-21
Would appreciate if you can update microk8s accordingly.

**Comment by balchua** [comment]
Using the `istioctl` to install makes it a lot easier.  Allow different profiles to set during addon enabling will be great.

**Comment by tegk** [comment]
Feel free to have a look at my [PR](https://github.com/ubuntu/microk8s/pull/1233) to use v1.6.0

**Comment by balchua** [comment]
Continuing the discussion here @tegk 

I do have some thoughts about using istioctl to install istio, just like what istio documentation says. The same thing with disabling the addon.
Instead of applying the demo profile we can have users set profiles while enabling the addon.
For example:
`microk8s enable istio:profile=default;addonComponents.grafana.enabled=true`

Where these `profile=default;addonComponents.grafana.enabled=true` are then parsed to become

`istioctl install --set profile=default --set addonComponents.grafana.enabled=true`
For reference on parsing arguments when enabling addons, check linkerd or metallb addons.

**Comment by tegk** [comment]
> Continuing the discussion here @tegk
> 
> I do have some thoughts about using istioctl to install istio, just like what istio documentation says. The same thing with disabling the addon.
> Instead of applying the demo profile we can have users set profiles while enabling the addon.
> For example:
> `microk8s enable istio:profile=default;addonComponents.grafana.enabled=true`
> 
> Where these `profile=default;addonComponents.grafana.enabled=true` are then parsed to become
> 
> `istioctl install --set profile=default --set addonComponents.grafana.enabled=true`
> For reference on parsing arguments when enabling addons, check linkerd or metallb addons.

Sorry, I have created a separate issue for this because the discussion could diverge too much from the intention of this issue.

https://github.com/ubuntu/microk8s/issues/1235

**Comment by tringuyen-yw** [comment]
> Feel free to have a look at my [PR](https://github.com/ubuntu/microk8s/pull/1233) to use v1.6.0

Can you show the step how to use this PR?

**Comment by tegk** [comment]
You can build the snap by your self as described here: https://github.com/ubuntu/microk8s/blob/master/docs/build.md

If you are simply interested in trying Istio 1.6, I would just install it by my self with istioctl.

**Comment by tringuyen-yw** [comment]
I am more interested in updating Istio 1.6. So `istioctl` seems more interesting. Regardless of the method I would use (whether build the snap or `istioctl`). Would there be any risk of corrupting the "normal" update of microk8s once a stable updated version is released?

**Comment by tegk** [comment]
> Regardless of the method I would use (whether build the snap or `istioctl`). Would there be any risk of corrupting the "normal" update of microk8s once a stable updated version is released?

There is no difference if you use istioctl yourself compared to installing binary via Microk8s as you are only assisted with the installation. Microk8s only simplifies the installation of maybe 10 steps to one. There is no update mechanism provided in Microk8s but you can probably use[ istioctl upgrade ](https://istio.io/docs/reference/commands/istioctl/#istioctl-upgrade) for that.

**Comment by tringuyen-yw** [comment]
>  you can probably use `istioctl upgrade` for that
Unfortunately the `upgrade` commande is not available in the `microk8s.istioctl` that comes with microk8s 1.18.2 which has istio 1.34. Let's see if I can install the istio 1.6 binaries following https://istio.io/docs/setup/upgrade/

**Comment by tegk** [comment]
`You can copy the latest istioctl to /var/snap/microk8s/current/bin` an then run `istioctl upgrade` in case you are running the edge snap with istio 1.5.x

**Comment by tringuyen-yw** [comment]
Upgrading istio 1.6 outside of microk8s is a total disaster! There was probably some config or path that microk8s set which `istioctl` is not aware. The upgrade had partially failed now I end up with itsio having incompleted upgrade. Sometime, even bot old and new version exists.
```
 $ microk8s.istioctl version
client version: 1.6.0
citadel version: 1.3.4
galley version: 1.3.4
pilot version: 1.3.4
policy version: 1.3.4
sidecar-injector version: 1.3.4
telemetry version: 1.3.4
pilot version: 1.6.0
data plane version: 1.6.0 (2 proxies), 1.3.4 (3 proxies)
```
Is there a way to clean that up?

**Comment by sstubbs** [comment]
I'm a bit hesitant to use this addon until this issue is resolved. I've installed istio 1.6.4 with `istioctl install --set profile=default` for the time being.

It works however I'm getting this error from the HPA. I don't currently need HPA but just thought I would post the issue if anyone else has run into it before.

```
unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
``` 

I get the same issue with the metrics-server addon enabled and disabled. I've installed the following:
```
sudo snap install microk8s --classic --channel=latest/edge/ha-preview
microk8s enable ha-cluster dns rbac prometheus
```

**Comment by tringuyen-yw** [comment]
@sstubbs This issue had been superceded by #1233 Can you report your observation in that issue instead?
