### ISSUE TITLE
Istio addon: Improvement of the installation options 

### ISSUE THREAD

**Issue by tegk** [ubuntu/microk8s#1235]
This issue aims to discuss how to improve the installation process of Istio for the user in terms of options that would normally be considered in a installation with istioctl.

Furthermore, Istio follows a strategy of built-in profiles to help the user to easily find the desired installation result based on the application scenario. From my point of view it would be desirable to offer these options to the user of the add on in microk8s as well.

https://istio.io/docs/setup/additional-setup/config-profiles/

The following profiles are provided by Istio:

- default
- demo
- minimal
- remote
- empty
- preview

At the moment microk8s is using the demo profile which I think should remain the standard in the future but it becomes clear that an option should make sense.

(this issue is an response to @balchua as I feel this should live in an separate issue)

**Comment by balchua** [comment]
Agree, offering this type of options to users allow one to have minimal istio installation especially on a constrained environment.

One thing that we need to take care of when disabling, is that, the profiles set or custom values set during enabling must also be passed on.  

Or we can assume the demo profile while disabling, you will just see components not existing error.

**Comment by tegk** [comment]
> One thing that we need to take care of when disabling, is that, the profiles set or custom values set during enabling must also be passed on.
For installation with istioctl the profile can be specified: `istioctl install --set profile=demo`.

In case failure messages are not desired during uninstalling the `https://istio.io/docs/setup/install/istioctl/#generate-a-manifest-before-installation`can be parsed to obtain the information.

**Comment by balchua** [comment]
Good point!  We can keep the generated yaml in `$SNAP_DATA/tmp/istio-install-generated.yaml`.  
On disable, we can perhaps just call `$KUBECTL delete -f $SNAP_DATA/tmp/istio-install-generated.yaml`.

**Comment by tegk** [comment]
> On disable, we can perhaps just call `$KUBECTL delete -f $SNAP_DATA/tmp/istio-install-generated.yaml`.

yes, you're right it's even easier, you don't need to read out anything but just delete the generated manifest.

**Comment by balchua** [comment]
How about the old istio already installed?
We also need to remove them.
Perhaps the new istio will be extracted onto a different path than the old istio.
To give us chance to remove both the old and new when disabling the addon.

**Comment by tegk** [comment]
Do you mean with "old istio" the previous profile installed or a new version?

**Comment by balchua** [comment]
The current istio addon that microk8s incorporate today.  I think its 1.5 or something like that.

**Comment by tegk** [comment]
Currently the Istio version is hard coded so there would be no old version present.

**Comment by balchua** [comment]
There will be. Snaps are automatically updated. Say today im using microk8s v 1.18.2, then it was upgraded to 1.19.0.
But when i was using 1.18.2, i enabled istio which is based on 1.5.

Then when i disable istio on a 1.19.0 the scripts are all based on the new `istioctl`.

Which leaves me with dangling istio 1.5.

I don't if i manage to explain the situation clearly.

**Comment by tegk** [comment]
@balchua you still interested to work on this? I would have some time in the next days :-)

**Comment by balchua** [comment]
@tegk if you have sometime to work on this, we will be more than happy to get help. 
Thanks!
