### ISSUE TITLE
microk8s.reset still running after +2 hours

### ISSUE THREAD

**Issue by tringuyen-yw** [ubuntu/microk8s#1237]
Using microk8s 1.18.2 stable. After a flawed attempt to upgrade istio outside of microk8s I ended up with a partial updated of istio. I decided to reinstall microk8s from scratch by
```
$ microk8s reset
$ sudo snap remove microk8s
```
`microk8s reset` still running since more than 2 hours. The activity monitor shows `microk8s-reset.wrapper` at 0% CPU but the LED of the hard drive is still blinking nonstop since `microk8s reset` was started.

Attached is the inspection report created by `microk8s inspect` on a new terminal, while `microk8s reset` is still running since +2 hours.

[inspection-report-20200527_005622.tar.gz](https://github.com/ubuntu/microk8s/files/4686532/inspection-report-20200527_005622.tar.gz)

**Comment by ktsakalozos** [comment]
I can see the cluster is not healthy. The apiserver is complaining. This is most probably why `microk8s reset` kept retrying to cleanup any running workloads. I could offer more insight on what went wrong if you give me a way to reproduce the setup you have.

**Comment by balchua** [comment]
Im actually surprised that you're not facing issues.  The hostname has capital letters.
Either change it to all small or add `--hostname-override` in kubelet.

**Comment by tringuyen-yw** [comment]
@balchua can you elaborate a bit more on "add --hostname-override in kubelet"?

**Comment by tringuyen-yw** [comment]
>  I could offer more insight on what went wrong if you give me a way to reproduce the setup you have

@ktsakalozos this would be quite time consuming, not sure if it would be worthwhile of your time for now. If there was nothing obvious in the inspection report. Maybe you can close that issue?

I am testing an application which uses an open source stateful serverless technology which is called [Cloudstate](https://cloudstate.io/docs/user/features/index.html). This needs a Custom Resource Definition called [cloudstate operator](https://github.com/cloudstateio/cloudstate/tree/master/operator). The tech is in alpha stage at the moment. The deployment and testing the service is not very smooth for now. It would be more time efficient if I break down the support request in smaller chunks.
