### ISSUE TITLE
Kubelet repeatedly fails when starting microk8s

### ISSUE THREAD

**Issue by Nike-Prallow** [ubuntu/microk8s#1242]
When starting microk8s on a Ubuntu 18 LTS v-server the node don't get ready. 
Kubelet repeatedly tries to start but it fails each time.

Output from `kubectl describe node`
```
Normal   Starting                 4s                     kubelet, hostname     Starting kubelet.
Warning  InvalidDiskCapacity      4s (x2 over 4s)        kubelet, hostname     invalid capacity 0 on image filesystem
Warning  ImageGCFailed            4s                     kubelet, hostname     invalid capacity 0 on image filesystem
```
Maybe this issue belongs to kubelet. But let me know your thoughts.
Trank you for help. 
[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/4689867/inspection-report.tar.gz)

**Comment by balchua** [comment]
I see errors in the kubelet logs like this `Failed to start ContainerManager open /proc/sys/kernel/panic: permission denied`.

Also something like this too.
`failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory`

This is very strange. Do you happen to be running on strato?

**Comment by Nike-Prallow** [comment]
Trank you fit your command. 
Yes i‘ve test microk8s on strato. Are they trying to block k8s?

**Comment by Nike-Prallow** [comment]
Okay im closing this. I think it is an issue at stratos. Thank you for help!
See #893.
