### ISSUE TITLE
microk8s status --wait-ready just hangs

### ISSUE THREAD

**Issue by lucacerone** [ubuntu/microk8s#1246]
I am new to kubernetes, and I am trying to install microk8s on Ubuntu 20.04 for learning purposes.

I followed the instruction on microk8s' website and I installed microk8s using:

`sudo snap install microk8s --classic --channel=1.18/stable` 

Next I run:

`sudo microk8s status --wait-ready`

but after 30 minutes it was still hanging, so I just stopped the process.

FYI this is the output:

```bash
luca@laptop:~$ microk8s status --wait-ready
^CTraceback (most recent call last):
  File "/snap/microk8s/1379/scripts/wrappers/status.py", line 145, in <module>
    isReady = wait_for_ready(wait_ready, timeout)
  File "/snap/microk8s/1379/scripts/wrappers/common/utils.py", line 75, in wait_for_ready
    isReady = is_cluster_ready()
  File "/snap/microk8s/1379/scripts/wrappers/common/utils.py", line 50, in is_cluster_ready
    service_output = kubectl_get("all")
  File "/snap/microk8s/1379/scripts/wrappers/common/utils.py", line 98, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/1379/scripts/wrappers/common/utils.py", line 31, in run
    env=env
  File "/snap/microk8s/1379/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/snap/microk8s/1379/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/snap/microk8s/1379/usr/lib/python3.5/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/snap/microk8s/1379/usr/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

Then I run `microk8s inspect` and there seems to be some problem (`Service snap.microk8s.daemon-etcd is not running`):

```bash
luca@laptop:~$ microk8s inspect
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
 FAIL:  Service snap.microk8s.daemon-etcd is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-etcd
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
```
The output of `sudo journalctl -u snap.microk8s.daemon-etc` is:

```
-- Logs begin at Sun 2020-04-26 20:47:30 CEST, end at Thu 2020-05-28 09:57:07 CEST. --
-- No entries --
```

I am attaching the full tarball file generated.
[inspection-report-20200528_095451.tar.gz](https://github.com/ubuntu/microk8s/files/4694111/inspection-report-20200528_095451.tar.gz)

Before completion, mickrok8s inspect also adviced me to do some changes

```
 WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT 
The change can be made persistent with: sudo apt-get install iptables-persistent
WARNING:  Docker is installed. 
File "/etc/docker/daemon.json" does not exist. 
You should create it and add the following lines: 
{
    "insecure-registries" : ["localhost:32000"] 
}
and then restart docker with: sudo systemctl restart docker
```

I applied both changes, but still microk8s gets stuck when I run `microk8s status --wait-ready`.

**Comment by ktsakalozos** [comment]
Hi @lucacerone, if you look at the etcd logs with `sudo journalctl -u snap.microk8s.daemon-etcd` (you missed a 'd' in the end) you will see the error:
```
listen tcp 127.0.0.1:2380: bind: address already in use
```

You can either free the 2380 port, or you could add something like `--listen-peer-urls https://0.0.0.0:12380` in `/var/snap/microk8s/current/args/etcd` to tell etcd to use a different port. Note this second approach is not tested but should work based on [1].

[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/clustering.md

**Comment by lucacerone** [comment]
Thanks @ktsakalozos! I have no idea what might be using that port.

I'll try to follow your advice!

**Comment by foxler2010** [comment]
> Thanks @ktsakalozos! I have no idea what might be using that port.
> 
> I'll try to follow your advice!

To find the process using that port, you can run `lsof -i :2380`. It will list programs using that port. You can then debug from there and figure out how to stop the process and free the port.

**Comment by wajdi-datalvo** [comment]
I had the same issue and it was because the server where microk8s was installed don't have enough disk & ram (At least 20G of disk space and 4G of memory are recommended as mentioned in the docs: https://microk8s.io/docs

**Comment by imaliasgharkhan** [comment]
any permanent fix to this issue , I am facing same. with Cento7

 sudo journalctl -u snap.microk8s.daemon-etcd
-- Logs begin at Thu 2023-04-06 16:43:37 CEST, end at Thu 2023-04-06 17:10:18 CEST. --
Apr 06 16:51:14 test.homelab.com systemd[1]: Started Service for snap application microk8s.daemon-etcd.

**Comment by tolonbai** [comment]
> Hi @lucacerone, if you look at the etcd logs with `sudo journalctl -u snap.microk8s.daemon-etcd` (you missed a 'd' in the end) you will see the error:
> 
> ```
> listen tcp 127.0.0.1:2380: bind: address already in use
> ```
> 
> You can either free the 2380 port, or you could add something like `--listen-peer-urls https://0.0.0.0:12380` in `/var/snap/microk8s/current/args/etcd` to tell etcd to use a different port and restart MicroK8s with `micork8s.stop; micork8s.start`. Note this second approach is not tested but should work based on [1].
> 
> [1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/clustering.md

@ktsakalozos Hi ! Thanks for possible solution recommedation. However, that did not help.

**Comment by ktsakalozos** [comment]
@tolonbai, the `microk8s status --wait-ready` command waits for two things:

  1. the API server to be responsive
  2. at least one worker node to be present and Ready.

Would you mind opening a new issue attaching your `microk8s inpsect` tarball so we can see what is the status of your deployment? Thank you.
