### ISSUE TITLE
Ubuntu 20.04 not working

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1251]
I'm currently running Ubuntu 20.04 and having a hard time getting microk8s to show the nodes. After running microk8s inspect, I get the following error:
(base) vinhdiesal@vinhdiesal-Blade-Stealth:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
 **_FAIL:  Service snap.microk8s.daemon-containerd is not running_**
For more details look at: sudo journalctl -u snap.microk8s.daemon-containerd
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball

I looked at the containerD files and they're in the /var/snap/microk8s/current/args directory, so does this mean it doesn't work with Ubuntu 20.04?

**Comment by vinhdiesal** [comment]
Nevermind, it turns out that I had some kubernetes left lying around, after I performed a snap remove it resolved the issues.

**Comment by balchua** [comment]
@vinhdiesal microk8s works on ubuntu 20.04 in your case?
Thanks for confirming.
