### ISSUE TITLE
Dashboard not showing. 

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1252]
Hi, 

I'm running microk8s version v.1.18 stable on Ubuntu 20.04.
I enabled the dashboard on microk8s and I performed the following: microk8s.kubectl proxy --accept-hosts=.* --address=0.0.0.0 & 
which servers on 8001. 
I went to the following URL: 
http://192.168.1.191:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
and I see the following errors: 
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
However, when I tried the same procedure on the IMAC OSX Mojave with multi pass it works. 
Can you help me get this resolved on the Ubuntu machine? 

Thanks,

**Comment by vinhdiesal** [comment]
**some further data points from microk8s:** 
microk8s kubectl get pods --all-namespaces
NAMESPACE            NAME                                              READY   STATUS    RESTARTS   AGE
container-registry   registry-7cf58dcdcc-rgphq                         0/1     Unknown   0          17h
ingress              nginx-ingress-microk8s-controller-t5jj9           0/1     Unknown   0          17h
istio-system         grafana-78758665bb-7cdqq                          0/1     Pending   0          9m6s
istio-system         istio-citadel-799bf7ddb9-ztlvz                    0/1     Pending   0          9m3s
istio-system         istio-egressgateway-76d7cf9c58-769vs              0/1     Pending   0          9m7s
istio-system         istio-galley-54cb4b4bcd-88qg8                     0/1     Pending   0          9m7s
istio-system         istio-grafana-post-install-1.3.4-rz24l            0/1     Pending   0          9m7s
istio-system         istio-ingressgateway-785cd6c5cc-6n9vd             0/1     Pending   0          9m6s
istio-system         istio-pilot-5fdd79bcb5-9g9x7                      0/2     Pending   0          9m6s
istio-system         istio-policy-7dc9dbf6bc-vvcwq                     0/2     Pending   0          9m6s
istio-system         istio-security-post-install-1.3.4-7bn2b           0/1     Pending   0          9m7s
istio-system         istio-sidecar-injector-66bc6cf76b-nnlss           0/1     Pending   0          9m3s
istio-system         istio-telemetry-66786bfd8f-tkjgg                  0/2     Pending   0          9m6s
istio-system         istio-tracing-6cb4f885d4-ljmwb                    0/1     Pending   0          9m3s
istio-system         kiali-68d8fc4d54-f9vdn                            0/1     Pending   0          9m6s
istio-system         prometheus-5c8fb8f746-xzx26                       0/1     Pending   0          9m4s
kube-system          coredns-588fd544bf-brkts                          0/1     Unknown   0          17h
kube-system          dashboard-metrics-scraper-db65b9c6f-czmsl         0/1     Unknown   0          17h
kube-system          heapster-v1.5.2-58fdbb6f4d-jfmqh                  0/4     Unknown   0          17h
kube-system          hostpath-provisioner-75fdc8fccd-cz9jt             0/1     Unknown   0          17h
kube-system          kubernetes-dashboard-67765b55f5-dsscl             0/1     Error     0          17h
kube-system          monitoring-influxdb-grafana-v4-6dc675bf8c-fhhqv   0/2     Unknown   0          17h
kube-system          nvidia-device-plugin-daemonset-mwrhz              0/1     Unknown   0          17h
metallb-system       controller-5f98465b6b-klnqx                       0/1     Unknown   0          17h
metallb-system       speaker-nwhq4                                     0/1     Unknown   0          17h

**When I looked at the dash board log:**
`microk8s kubectl logs kubernetes-dashboard-67765b55f5-dsscl --namespace=kube-system
2020/05/29 21:42:40 Starting overwatch
2020/05/29 21:42:40 Using namespace: kube-system
2020/05/29 21:42:40 Using in-cluster config to connect to apiserver
2020/05/29 21:42:40 Using secret token for csrf signing
2020/05/29 21:42:40 Initializing csrf token from kubernetes-dashboard-csrf secret
2020/05/29 21:42:40 Empty token. Generating and storing in a secret kubernetes-dashboard-csrf
2020/05/29 21:42:40 Successful initial request to the apiserver, version: v1.18.3
2020/05/29 21:42:40 Generating JWE encryption key
2020/05/29 21:42:40 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2020/05/29 21:42:40 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 21:42:40 Initializing JWE encryption key from synchronized object
2020/05/29 21:42:40 Creating in-cluster Sidecar client
2020/05/29 21:42:40 Auto-generating certificates
2020/05/29 21:42:40 Successfully created certificates
2020/05/29 21:42:40 Serving securely on HTTPS port: 8443
2020/05/29 21:42:40 Successful request to sidecar
2020/05/29 22:25:12 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
2020/05/29 22:25:42 Successful request to sidecar
2020/05/29 22:27:42 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
2020/05/29 22:28:12 Successful request to sidecar
2020/05/29 22:30:12 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
2020/05/29 22:30:42 Successful request to sidecar
2020/05/29 22:32:14 http: TLS handshake error from 127.0.0.1:55682: remote error: tls: unknown certificate
2020/05/29 22:32:14 http: TLS handshake error from 127.0.0.1:55684: remote error: tls: unknown certificate
2020/05/29 22:32:14 http: TLS handshake error from 127.0.0.1:55692: remote error: tls: unknown certificate
2020/05/29 22:32:14 http: TLS handshake error from 127.0.0.1:55694: remote error: tls: unknown certificate
2020/05/29 22:32:19 http: TLS handshake error from 127.0.0.1:55716: remote error: tls: unknown certificate
2020/05/29 22:32:19 http: TLS handshake error from 127.0.0.1:55718: remote error: tls: unknown certificate
2020/05/29 22:32:28 http: TLS handshake error from 127.0.0.1:55758: remote error: tls: unknown certificate
2020/05/29 22:32:28 http: TLS handshake error from 127.0.0.1:55756: remote error: tls: unknown certificate
2020/05/29 22:32:30 http: TLS handshake error from 127.0.0.1:55772: remote error: tls: unknown certificate
2020/05/29 22:32:30 http: TLS handshake error from 127.0.0.1:55774: remote error: tls: unknown certificate
2020/05/29 22:32:42 Metric client health check failed: the server is currently unable to handle the request (get services dashboard-metrics-scraper). Retrying in 30 seconds.
2020/05/29 22:33:12 Successful request to sidecar
2020/05/29 22:34:19 http: TLS handshake error from 127.0.0.1:56716: remote error: tls: unknown certificate
2020/05/29 22:34:19 http: TLS handshake error from 127.0.0.1:56718: remote error: tls: unknown certificate
2020/05/29 22:34:22 http: TLS handshake error from 127.0.0.1:56736: remote error: tls: unknown certificate
2020/05/29 22:34:22 http: TLS handshake error from 127.0.0.1:56742: remote error: tls: unknown certificate
2020/05/29 22:34:22 http: TLS handshake error from 127.0.0.1:56744: remote error: tls: unknown certificate
2020/05/29 22:34:30 http: TLS handshake error from 127.0.0.1:56780: remote error: tls: unknown certificate
2020/05/29 22:34:30 http: TLS handshake error from 127.0.0.1:56778: remote error: tls: unknown certificate
2020/05/29 22:34:45 http: TLS handshake error from 127.0.0.1:56830: remote error: tls: unknown certificate
2020/05/29 22:34:45 http: TLS handshake error from 127.0.0.1:56832: remote error: tls: unknown certificate
2020/05/29 23:07:40 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: unexpected object: &Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Data:map[string][]byte{},Type:,StringData:map[string]string{},}
2020/05/29 23:07:42 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:42 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:42 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:43 Metric client health check failed: Get https://10.152.183.1:443/api/v1/namespaces/kube-system/services/dashboard-metrics-scraper/proxy/healthz: dial tcp 10.152.183.1:443: connect: connection refused. Retrying in 30 seconds.
2020/05/29 23:07:44 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:44 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:44 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:46 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:46 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:46 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:48 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:48 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:48 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:50 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:50 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:50 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:52 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:52 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:52 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:54 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:54 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:54 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:56 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:56 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:56 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:07:58 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:07:58 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:07:58 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:08:00 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:08:00 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:08:00 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:08:02 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:08:02 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:08:02 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:08:04 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:08:04 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:08:04 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:08:06 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:08:06 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:08:06 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:08:08 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:08:08 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:08:08 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
2020/05/29 23:08:10 Restarting synchronizer: kubernetes-dashboard-key-holder-kube-system.
2020/05/29 23:08:10 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2020/05/29 23:08:10 Synchronizer kubernetes-dashboard-key-holder-kube-system exited with error: kubernetes-dashboard-key-holder-kube-system watch ended with timeout
E0529 23:08:12.173974       1 runtime.go:76] Observed a panic: synchronizer kubernetes-dashboard-key-holder-kube-system restart limit execeeded. Restarting pod.
goroutine 12 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x151f480, 0xc0002a6460)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:48 +0x82
panic(0x151f480, 0xc0002a6460)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents.func1()
	/home/travis/build/kubernetes/dashboard/src/app/backend/sync/overwatch.go:92 +0x236
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00022f7b0)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00022f7b0, 0x0, 0x0, 0x877901, 0xc000510000)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88
k8s.io/apimachinery/pkg/util/wait.Forever(0xc00022f7b0, 0x0)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:79 +0x50
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents
	/home/travis/build/kubernetes/dashboard/src/app/backend/sync/overwatch.go:88 +0x78
panic: synchronizer kubernetes-dashboard-key-holder-kube-system restart limit execeeded. Restarting pod. [recovered]
	panic: synchronizer kubernetes-dashboard-key-holder-kube-system restart limit execeeded. Restarting pod.

goroutine 12 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:55 +0x105
panic(0x151f480, 0xc0002a6460)
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents.func1()
	/home/travis/build/kubernetes/dashboard/src/app/backend/sync/overwatch.go:92 +0x236
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00022f7b0)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00022f7b0, 0x0, 0x0, 0x877901, 0xc000510000)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88
k8s.io/apimachinery/pkg/util/wait.Forever(0xc00022f7b0, 0x0)
	/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:79 +0x50
created by github.com/kubernetes/dashboard/src/app/backend/sync.(*overwatch).monitorRestartEvents
	/home/travis/build/kubernetes/dashboard/src/app/backend/sync/overwatch.go:88 +0x78

Please help me get my pods running and get access to the dashboard. 

Thanks,

**Comment by vinhdiesal** [comment]
In my Ubuntu 20.04 environment I used a multipass of ubuntu 18.04 and it appears to have worked. so I believe there is no compatibility with Ubuntu 20.04.

**Comment by balchua** [comment]
In the docs, there's a section regarding networking. 
https://microk8s.io/docs/troubleshooting#common-issues. If you haven't tried, maybe those can help.

**Comment by ktsakalozos** [comment]
@vinhdiesal could you please attach the tarball created by `microk8s.inspect`? We need to see if all the services are running and they are not why.

**Comment by vinhdiesal** [comment]
I attached the tarball report. All the services seems to be running but I can't get to the dashboard.
[inspection-report-20200601_164808.tar.gz](https://github.com/ubuntu/microk8s/files/4713962/inspection-report-20200601_164808.tar.gz)

**Comment by balchua** [comment]
@vinhdiesal i can see that your host name has capital letters.  You can do 2 things.

1.  You can change your hostname to all small letters
2. Add in the kubelet args `--hostname-override` located in `/var/snap/microk8s/current/args/kubelet`

Restart microk8s afterwards. Lets see if it works.

**Comment by vinhdiesal** [comment]
i tried that and I get the following error:
```{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}```

**Comment by balchua** [comment]
@vinhdiesal i checked the tarball, no pods are running.  Even coredns.  First i will suggest to bring up components needed by the dashboard.  I believe dns is required by dashboard.
Can help check if all pods are running when u change your hostname to all small letters?

**Comment by vinhdiesal** [comment]
Can you help show how the hostname is in capital letters and how to change it?  In the terminal I see everything lower case. 
I did performed the `--hostname-override` and I also changed my hostname to lowercase by going to the Ubuntu settings and put my account name in lowercase.
After I performed a `microk8s stop; microk8s start`, I typed in the following commands: `microk8s.kubectl proxy --accept-hosts=.* --address=0.0.0.0 &` and tried access the dashboard via `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`
However I get 

```  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503}
```
The only way for me to get the pods up and running is performing a `microk8s start`

Now when I performed the `microk8s inspect`, I get the following errors: 

```FAIL:  Service snap.microk8s.daemon-kubelet is not running```

I attached the latest tarball: 
[inspection-report-20200602_043902.tar.gz](https://github.com/ubuntu/microk8s/files/4716865/inspection-report-20200602_043902.tar.gz)

**Comment by balchua** [comment]
Hi, 
The journal logs shows like this.
```
May 29 08:48:45 vinhdiesal-Blade-Stealth systemd[1]: Started Service for snap application microk8s.daemon-flanneld.
```

But with the latest tarball the hostname has been changed to `hadoopmaster` great.
When you added the kubelet args `hostname-override` you didn't pass a value.  But since the names are all small now, you can remove the `hostname-override` args in the kubelet.
After that restart microk8s. `microk8s stop` then `microk8s start`

**Comment by vinhdiesal** [comment]
Hi, 
I have removed the `hostname-override` from `/var/snap/microk8s/current/args/kubelet` and then performed a `microk8s stop` even rebooted my computer and performed a `microk8s start` 
I performed a `microk8s inspect ` and everything looks healthy:
```
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
```
I performed a `microk8s.kubectl proxy --accept-hosts=.* --address=0.0.0.0 &` command for port 8001 and tried to access the dashboard via `http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`.
However I have gotten the same failure: 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```
I tried to type in the `microk8s kubectl get all/services` command and only see the following values and not all the pods running: 
```
NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   xx.xx.xxx.xxx  <none>        443/TCP   3d20h
```

I attached the latest tarball:

[inspection-report-20200602_064107.tar.gz](https://github.com/ubuntu/microk8s/files/4717532/inspection-report-20200602_064107.tar.gz)

**Comment by balchua** [comment]
@vinhdiesal is it ok to reinstall microk8s?
By doing `sudo snap remove microk8s` then `sudo snap install microk8s --classic --channel=<the channel you want to use>`
I think changing the hostname completely led to adverse effect.

**Comment by vinhdiesal** [comment]
Thank you @balchua, I performed a `sudo snap remove microk8s --purge` then `sudo snap install microk8s --classic` and the dashboard is now working. I am on Ubuntu 20.04.

**Comment by balchua** [comment]
Great.  Can we close the issue?

**Comment by vinhdiesal** [comment]
Yes. Thanks again.
