### ISSUE TITLE
Help building an API using microk8s

### ISSUE THREAD

**Issue by Sshuichi** [ubuntu/microk8s#1254]
Hello everyone, and thank you for the amazing work. 
I'm trying to build the rudderstack-server using helm: 
https://github.com/rudderlabs/rudderstack-helm

What I want to achieve: 
Run the API and expose it to a port, so I can use Nginx as a reverse proxy on a domain. 

What I tried: 
```
git clone git@github.com:rudderlabs/rudderstack-helm.git
cd rudderstack-helm/
microk8s enable dns dashboard registry
microk8s kubectl config view --raw > $HOME/.kube/config
helm install myproject ./ --set rudderWorkspaceToken="MYCODE"
```
When running kubectl get --namespace default svc -w myproject-rudderstack I get:
```
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
myproject-rudderstack   LoadBalancer   10.152.183.212   <pending>     80:31455/TCP   23m
```
or `kubectl get services` 
I get:

```
NAME                                        TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes                                  ClusterIP      10.152.183.1     <none>        443/TCP        26m
myproject-rudderstack                       LoadBalancer   10.152.183.212   <pending>     80:31455/TCP   24m
myproject-rudderstack-postgresql            ClusterIP      10.152.183.102   <none>        5432/TCP       24m
myproject-rudderstack-postgresql-headless   ClusterIP      None             <none>        5432/TCP       24m
myproject-rudderstack-transformer           ClusterIP      10.152.183.22    <none>        9090/TCP       24m
```
I'm very new to Kubernetes, and I want to have an external IP that I can proxy through Nginx to serve the API URL on a specific domain but I'm stuck here.
Can you please help?

I'm trying to run this on a single machine.

**Comment by balchua** [comment]
There is a metallb addon which can help provide a kubernetes service external ip.

**Comment by Sshuichi** [comment]
Do you have any example how to use it?

**Comment by balchua** [comment]
First you identify the external ips you want your pods to have.  For example in my internal network, my ip ranges from `192.168.0.0/24` which means it has up to 255 devices.  And i want to allocate `192.168.1.200-192.168.1.210`
Then enable metallb like this.

`microk8s enable metallb:192.168.1.200-192.168.1.210`

After you enable metallb, for every new `Service` of type `LoadBalancer` metallb will allocate an ip from the range you specified above.

**Comment by balchua** [comment]
For more info on metallb check their site.
https://metallb.universe.tf/
I believe the metallb addon is using layer 2 mode.
