### ISSUE TITLE
MicroK8s behind ssl-inspection proxy

### ISSUE THREAD

**Issue by jeremypng** [ubuntu/microk8s#1256]
I have followed the proxy instructions and gotten connectivity through the proxy but Helm3 is not installing because the SSL inspection CA is not a trusted cert. Is there a way I can add it to the data directory and have the microk8s' update-ca-certificates script pick it up?

**Comment by ktsakalozos** [comment]
Hi @jeremypng I do not have a good answer for you right now. I can only point you to the helm3 addon https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.helm3.sh How would the curl command change?

**Comment by jeremypng** [comment]
I do not believe the CURL command would need to change. The helm3 add-on is only generating the error because it is the first thing I have tried to download. The ssl-inspection cert needs to go into /var/lib/snapd/snap/microk8s/current/usr/share/ca-certificates and then /var/lib/snapd/snap/microk8s/current/usr/sbin/update-ca-certificates needs to be run. Then enabling the helm3 add-on or any other microk8s download should work. However, those files are part of the squashfs filesystem so they cannot be easily modified without rebuilding the snap.

If modifying the CURL command was the only option, a way to pass in --cacert or --capath should fix it.

[root@host current]# microk8s enable helm3
Enabling Helm 3
Fetching helm version v3.0.2.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 99 11.5M   99 11.5M    0     0  9562k      0  0:00:01  0:00:01 --:--:-- 9557k
curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.
Failed to enable helm3


Thanks!
