### ISSUE TITLE
ingress addon does not work on mixed-arch cluster

### ISSUE THREAD

**Issue by ssmall** [ubuntu/microk8s#1257]
I have a 4-node microk8s cluster. 2 of the nodes (including the master) are `linux/amd64` and the remainder are `linux/arm64`. I am running microk8s from the `1.18/stable` channel.

After running `microk8s enable ingress`, I see the following:

```
$ kubectl get po -n ingress
NAME                                          READY   STATUS    RESTARTS   AGE
pod/nginx-ingress-microk8s-controller-925lz   1/1     Running   0          16m
pod/nginx-ingress-microk8s-controller-nfpk2   0/1     Error     1          6s
pod/nginx-ingress-microk8s-controller-nh4x9   0/1     Pending   0          1s
pod/nginx-ingress-microk8s-controller-sjkpf   0/1     Error     0          3s
```

The two pods with `Error` status are running on the `arm64` nodes. Their logs say

```
standard_init_linux.go:207: exec user process caused "exec format error"
```

## Workaround

I am able to workaround the issue by updating `daemonset.apps/nginx-ingress-microk8s-controller` to use the manifest `quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0`, which has both `amd64` and `arm64` images.

**Comment by ktsakalozos** [comment]
Thank you for reporting this issue and offering a workaround. We should revise the manifests we ship to use this kind of multi-arch images.   

For anyone interested in seeing fixing the ingress addon the enable script is at [1] and the manifest is at [2] 

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.ingress.sh
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ingress.yaml

**Comment by balchua** [comment]
This is a bit more complex in my opinion.

We need to have as many `DaemonSet` manifest as the number of supported arch. One for `amd64` and another for `arm64` and using `nodeSelector` or `nodeAffinity` we pin it to the right arch.

**Comment by balchua** [comment]
PR to use multi-arch images. Also upgraded ingress to `v0.33.0`

**Comment by ktsakalozos** [comment]
Thank you for your work @balchua and @ssmall for reporting the issue. The patch is merged and the fix will be available in the latest/edge channel within a day.
