### ISSUE TITLE
Unable to access k8s server using kubectl commands form macOS

### ISSUE THREAD

**Issue by munjalpatel** [ubuntu/microk8s#1262]
Hello,

I am installing `MicroK8s` using the following procedure as detailed on:
https://microk8s.io/docs/install-alternatives#heading--macos

```sh
brew install ubuntu/microk8s/microk8s

microk8s install
microk8s status --wait-ready

microk8s enable dns registry

microk8s kubectl config view --flatten > ~/.kube/microk8s-config && \
KUBECONFIG=~/.kube/microk8s-config:~/.kube/config kubectl config view --flatten > ~/.kube/temp-config && \
mv ~/.kube/temp-config ~/.kube/config && \
kubectl config use-context microk8s
```

However, when I run any command from my macOS with `kubectl` I keep getting the following error:
```
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

![image](https://user-images.githubusercontent.com/2717686/83504620-8fdf5e00-a479-11ea-977c-688757440845.png)

Here is my `~/.kube/config`
![image](https://user-images.githubusercontent.com/2717686/83504565-7f2ee800-a479-11ea-9baf-a9b6891bd66d.png)

Attached is my `microk8s inspect` output:
[inspection-report-20200602_023458.tar.gz](https://github.com/ubuntu/microk8s/files/4716279/inspection-report-20200602_023458.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @munjalpatel 

could you get the kubeconfig with `microk8s config`?

MicroK8s on mac and windows creates a linux VM. In your kubeconfig you should point to the IP of that VM and not your localhost (127.0.0.1).

**Comment by munjalpatel** [comment]
That was it! Thanks @ktsakalozos
