### ISSUE TITLE
Microk8s Namespaces In Terminating Status On Reset

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1264]
Hi,

Whenever I run microk8s reset it gets stuck at deleting namespaces. If I check the cluster I can see that all custom namespaces added are stuck terminating. If I cancel the reset process and then stop and start the cluster they then do terminate properly and are removed but ideally this wouldn't need to be done.

**Comment by balchua** [comment]
I see this happen when there are crds or apiservices still left behind.

**Comment by DanHartman** [comment]
I am also able to reproduce this.  I am not creating any CRDs.  
* `uname -a`
  * `19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64`
* `microk8s uninstall`
* `microk8s install`
* `microk8s config > ~/.kube/config`
```shell
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: foo
EOF
```
`microk8s reset`
which prints:
```shell
Disabling all addons.
...
Removing CRDs
No resources found
Removing PriorityClasses
Removing StorageClasses
namespace "foo" deleted

```

And then it does not complete.  I am able to "force" it by removing the finalizer manually by editing the json produced with [these steps](https://github.com/kubernetes/kubernetes/issues/60807#issuecomment-668375214) and then updating the cluster with that json

Per [the command found here](https://github.com/kubernetes/kubectl/issues/151#issuecomment-402003022) I can view what is in this namespace still
`kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get -n foo`
```shell
NAME                  TYPE                                  DATA   AGE
default-token-7lcxj   kubernetes.io/service-account-token   3      5m55s
NAME      SECRETS   AGE
default   1         5m55s
```
Those are `secrets` and `serviceaccounts` respectively

I'd love if someone could point out a mistake on my end, or verify this symptom as well.
Thanks

**Comment by DanHartman** [comment]
I'm not sure if this is relevant but if I `kubectl delete ns ${FOO}` before issuing `microk8s reset` everything proceeds as expected
