### ISSUE TITLE
Centos 7.4: microk8s.join throws openssl error

### ISSUE THREAD

**Issue by pelojoy** [ubuntu/microk8s#1270]
Running microk8s.join on Centos 7.4 version, getting the following error:

`microk8s.join 192.168.1.33:25000/oAnOGKxcsBCfkRybcDudVCdWkGamOsOf
openssl: relocation error: /snap/core/current/lib/x86_64-linux-gnu/libresolv.so.2: symbol __h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
Traceback (most recent call last):
  File "/snap/microk8s/1253/scripts/cluster/join.py", line 387, in <module>
    update_flannel(info["etcd"], master_ip, master_port, token)
  File "/snap/microk8s/1253/scripts/cluster/join.py", line 132, in update_flannel
    get_etcd_client_cert(master_ip, master_port, token)
  File "/snap/microk8s/1253/scripts/cluster/join.py", line 107, in get_etcd_client_cert
    subprocess.check_call(cmd_cert.split())
  File "/snap/microk8s/1253/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['openssl', 'req', '-new', '-key', '/var/snap/microk8s/1253/certs/server.key', '-out', '/var/snap/microk8s/1253/certs/server.remote.csr', '-config', '/var/snap/microk8s/1253/certs/csr.conf']' returned non-zero exit status 127`

**Comment by pelojoy** [comment]
Thanks to @Balchu’s hint, I tried to modify `join.py` to use /snap/core/current/usr/bin/openssl. And it seems to work. I need to mount the scripts to a different location to be able to modify it:

`mount --bind -o nodev,ro  /home/cluster  /var/lib/snapd/snap/microk8s/1253/scripts/cluster`

It comes back with a warning. But it does seem to work.
```
[root@zeek8s02 cluster]# microk8s.join 192.168.1.33:25000/ejRzaJDWUIovjoezgDaCUZszowzsotG 
WARNING: can't open config file: /usr/lib/ssl/openssl.cnf
```

**Comment by ktsakalozos** [comment]
@pelojoy thank you for reporting the issue an taking the extra step to provide a fix.

Could you please try to set in the `check_call` the following environment variables and keep using the openssl found in the MicroK8s snap:
```
SNAP="/snap/microk8s/current"
PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
ARCH="$($SNAP/bin/uname -m)"
LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu"
OPENSSL_CONF="$SNAP/etc/ssl/openssl.cnf"
```

Using the snap in the core is an option however there is the chance the snap will break in the future as the updates of the openssl in the core snap is out of our reach.

**Comment by pelojoy** [comment]
@ktsakalozos  Add the following to join.py: 

```
myenv = { "SNAP":"/snap/microk8s/current",
              "PATH":"$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH",
              "ARCH":"$($SNAP/bin/uname -m)",
              "LD_LIBRARY_PATH":"$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu",
              "OPENSSL_CONF":"$SNAP/etc/ssl/openssl.cnf"}
    subprocess.check_call(cmd_cert.split(), env=myenv )
```
but getting this error: 
```
Traceback (most recent call last):
  File "/snap/microk8s/1443/scripts/cluster/join.py", line 393, in <module>
    update_flannel(info["etcd"], master_ip, master_port, token)
  File "/snap/microk8s/1443/scripts/cluster/join.py", line 138, in update_flannel
    get_etcd_client_cert(master_ip, master_port, token)
  File "/snap/microk8s/1443/scripts/cluster/join.py", line 113, in get_etcd_client_cert
    subprocess.check_call(cmd_cert.split(), env=myenv )
  File "/snap/microk8s/1443/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/snap/microk8s/1443/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/snap/microk8s/1443/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/snap/microk8s/1443/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'openssl'

```

**Comment by pelojoy** [comment]
The following code change in `join.py` seems to work:

```
 cmd_cert = "/snap/microk8s/current/usr/bin/openssl  ...
 myenv = { "OPENSSL_CONF":"/snap/microk8s/current/etc/ssl/openssl.cnf"}
 subprocess.check_call(cmd_cert.split(), env=myenv)

```

**Comment by ktsakalozos** [comment]
> The following code change in `join.py` seems to work

Awesome. Thank you for reporting this and offering the fix. Would you be interested in submitting a PR? It is absolutely fair you get the credit for this work.

**Comment by pelojoy** [comment]
@ktsakalozos Thanks for the credit. But can you submit the PR instead? I don't have the environment setup to do it. Thanks.
