### ISSUE TITLE
Gadgets on different Grafana dashboards report "no data" though there should be some data to show

### ISSUE THREAD

**Issue by nikolayvinogradov** [ubuntu/microk8s#1273]
See the attached screenshot. I have enabled dns, dashboard, prometheus and HA features and I have simple workload running.

![Screenshot_20200605_154922](https://user-images.githubusercontent.com/32940265/83878037-2d6db280-a744-11ea-923f-3f43baa479cc.png)

**Comment by ktsakalozos** [comment]
The work on updating the metrics server was pushed to the ha-preview branch and seems to address this issue. Please have a look.
