### ISSUE TITLE
microk8s won't start unknown reason

### ISSUE THREAD

**Issue by Logibox** [ubuntu/microk8s#1275]
I'm installing microk8s 1.16 into a ubuntu 18.04 cloud image via ['packer'](https://www.packer.io/).

I essentially want to create a pre-baked kubernetes master node, with a few deployments and services baked in.

During the build, when `microk8s status` is run I get:
```
 microk8s is not running. Use microk8s.inspect for a deeper inspection
````
Output from `snap services` is 
```
Service                             Startup  Current  Notes          
microk8s.daemon-apiserver           enabled  active   -                         
microk8s.daemon-apiserver-kicker    enabled  active   -                           
microk8s.daemon-cluster-agent       enabled  active   -                                       
microk8s.daemon-containerd          enabled  active   -                     
microk8s.daemon-controller-manager  enabled  active   -                                                         
microk8s.daemon-etcd                enabled  active   -
microk8s.daemon-flanneld            enabled  active   -                                                                                                                                   
microk8s.daemon-kubelet             enabled  active   -                                        
microk8s.daemon-proxy               enabled  active   -                                                                                                                                  
microk8s.daemon-scheduler           enabled  active   -
```
Unsure how to debug this any further - any help would be greatly appreciated!

`kubectl` cannot talk to the api server, it just times out.

[inspection-report-20200605_192035.tar.gz](https://github.com/ubuntu/microk8s/files/4738235/inspection-report-20200605_192035.tar.gz)

**Comment by balchua** [comment]
I think it is running out of memory.
I see this in the inspect tarball
```shell
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1a71e12, 0x16)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0x7ffc2ec062b8 sp=0x7ffc2ec06288 pc=0x42f212
runtime.sysMap(0xc000000000, 0x4000000, 0x2d14d98)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc5 fp=0x7ffc2ec062f8 sp=0x7ffc2ec062b8 pc=0x418255
runtime.(*mheap).sysAlloc(0x2cfc500, 0x2000, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:701 +0x1cd fp=0x7ffc2ec063a0 sp=0x7ffc2ec062f8 pc=0x40b4ed
runtime.(*mheap).grow(0x2cfc500, 0x.......
```
Looking at `free`, the system seems to running with little memory.

```shell
              total        used        free      shared  buff/cache   available
Mem:            481         409           5           0          65          58
Swap:             0           0           0
```
Is there a way to increase the memory?

**Comment by Logibox** [comment]
Ah an easy fix then - by default the qemu builder for packer only assigns 512MiB for the build machine https://www.packer.io/docs/builders/qemu/#memory. Bumping it up to 2GiB resolves the issue.

Thanks so much for looking it this!

**Comment by Logibox** [comment]
Ah an easy fix then - by default the qemu builder for packer only assigns 512MiB for the build machine https://www.packer.io/docs/builders/qemu/#memory. Bumping it up to 2GiB resolves the issue.

Thanks so much for looking it this!

**Comment by balchua** [comment]
That's great to hear!  Im closing this now.
Thanks
