### ISSUE TITLE
Best Way To Change Istio CPU Limits

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1277]
Hi,

I've just installed the beta of microk8s on ubuntu 20.04 with the following:
```
sudo snap install microk8s --classic --channel=1.19/beta
```
and installed the following addons.
```
microk8s enable cilium rbac dns storage metallb istio metrics-server prometheus fluentd
```

I haven't even had to do any fixes for any of the issues I was experiencing on 1.18/stable.

I'm extremely impressed as everything seems to just work out the box. Really really happy. One thing though is the cpu limits for the `istio-system` namespace are quite high at `14.80`.

What would be the best way for me to alter these? I can manually edit their manifests but just want to check if there is a better way.

**Comment by balchua** [comment]
Not as of the moment.  Right now, editing the manifest is the way to go.
There's an open issue to further improve the way we enable istio.
https://github.com/ubuntu/microk8s/issues/1235

**Comment by sstubbs** [comment]
ok thanks easy enough to change just was courious.
