### ISSUE TITLE
Unable to start, API server certs are missing

### ISSUE THREAD

**Issue by farzanuddin** [ubuntu/microk8s#128]
Hola there, first time microk8s user here :)

I just did an install (`--beta`) and the api server doesn't seem to be running. `journalctl -xe` says:

```
15558 localkube.go:137] open /var/lib/localkube/certs/apiserver.crt: no such file or directory
```

Install details:

```
microk8s    v1.11.3                 185   beta      canonical✓    classic
```

If I try to curl the api server it doesn't seem to be running. I also noticed some other random errors on other units (`journalctl -xe -u snap.microk8s.*`), for example:

```
18341 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry [unix://etcd.socket:2379]
```

Any help? :)

**Comment by ktsakalozos** [comment]
Hola @farzanuddin , welcome to microk8s!

Can you please run a `microk8s.inspect` and share here the tarball with the inspection report?

This should give me a better view of the deployment. This `/var/lib/localkube/certs/apiserver.crt` error seems to be from a non-microk8s kubernetes distribution. Could this be the case?
