### ISSUE TITLE
HTTPS Connection Pool error

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1281]
I currently have two machines joined in a `microk8s kubernetes cluster`. One machine is a `IMAC` with IP: `192.168.1.108` and the other one is a Razer running `Ubuntu 20.04` with IP address `192.168.1.192`. 
On the `IMAC` I've installed `microk8s` through `Multipass` where the `multipass list` command shows a VM IP address of `192.168.64.6`. Both the `Razer` and `IMAC` have `microk8s version 18.3` from the `--classic channel`. 
Both machines have the firewall disabled. I created a `microk8s` cluster by the join command where the master is on the `Razer Ubuntu` machine. 
My problems is when the two nodes are connected in the cluster and I performed a `microk8s helm` installation or install an `add-on` like `microk8s.enable cilium`, I get the following error: 
```
Traceback (most recent call last):
  File "/snap/microk8s/1422/scripts/cluster/distributed_op.py", line 159, in <module>
    update_argument(service, args[2], args[3])
  File "/snap/microk8s/1422/scripts/cluster/distributed_op.py", line 84, in update_argument
    do_op(remote_op)
  File "/snap/microk8s/1422/scripts/cluster/distributed_op.py", line 38, in do_op
    verify=False)
  File "/snap/microk8s/1422/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/snap/microk8s/1422/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/snap/microk8s/1422/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/microk8s/1422/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/snap/microk8s/1422/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.1.108', port=25000): Max retries exceeded with url: /cluster/api/v1.0/configure (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9d9a0871d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Failed to enable cilium
```
Again the firewall is off on my `IMAC` and the nodes can connect fine, but somehow I get this connection error.

**Comment by ktsakalozos** [comment]
> One machine is a `IMAC` with IP: `192.168.1.108`

However, when you install MicroK8s with Multipass a new VM is created inside your `IMAC`. That VM does not have the IP: `192.168.1.108` and therefore the two MicroK8s instances cannot "see" each other.

You have to create a VM (possibly without Multipass [1]) with bridged network and then run MicroK8s inside it.

[1] https://github.com/canonical/multipass/issues/118

**Comment by vinhdiesal** [comment]
I created a VM using Virtual Box with Ubuntu 20.04 with microk8s running inside, however I'm having the same problem with reaching `192.168.1.108 port 25000`. When I performed an `ifconfig` the `IP Address` is different than the `MAC host` and I attached the VMWARE ethernet to the `bridge network adapter`. When I performed a `microk8s.enable` cilium as an example I'm getting the same errors.

**Comment by vinhdiesal** [comment]
Nevermind, I had to close the `Multipass` instance and restarted the cluster using the `microk8s add-node` and `join` method and deployment started to work. 

Thanks for your help.
