### ISSUE TITLE
Why image name in metrics is empty?

### ISSUE THREAD

**Issue by heckad** [ubuntu/microk8s#1283]
```
container_memory_working_set_bytes{container="",id="/kubepods/burstable/pod06a3c539-82c6-4861-946f-2ad225023c59",image="",name="",namespace="default",pod="order-storage-postgres-postgresql-0"} 2.8192768e+07 1591712929139
```
Why container, image, name are empty?

[inspection-report-20200609_164432.tar.gz](https://github.com/ubuntu/microk8s/files/4752826/inspection-report-20200609_164432.tar.gz)

**Comment by ktsakalozos** [comment]
Where do you see this? What is the effect of it? Is there something failing?
