### ISSUE TITLE
Flanner D 

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1285]
I'm getting closer to my goal with this local cluster, but it appears every time something works something else breaks. 
My current configuration is that I have three machines running `Ubuntu 20.04` with `microk8s` installed on all three machines. 
I successfully created the `microk8s kubernetes cluster`, however my master node now has the following error: 
```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
 FAIL:  Service snap.microk8s.daemon-flanneld is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-flanneld
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
```
I can't access the `kubeflow/kubernetes` dashboard and some services like `Helm` isn't working correctly. 
Can you review the attached `tarbell` to help resolve the issue?

Thanks, 
[inspection-report-20200609_104253.tar.gz](https://github.com/ubuntu/microk8s/files/4753896/inspection-report-20200609_104253.tar.gz)

**Comment by vinhdiesal** [comment]
[inspection-report-20200609_104253.tar.gz](https://github.com/ubuntu/microk8s/files/4753894/inspection-report-20200609_104253.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @vinhdiesal,

I see you have cilium enabled. The cilium cni stops flannel so the reported error is expected. If you are testing kubeflow could you please go with flannel just because this is the setup we are testing and we are confident with.

Thank you

**Comment by vinhdiesal** [comment]
Thank you very much for your help.
