### ISSUE TITLE
Lightweight version of kubeflow addon

### ISSUE THREAD

**Issue by knkski** [ubuntu/microk8s#1286]
Many people would like to try out Kubeflow on their laptop. The full deployment of Kubeflow is quite heavyweight, taking up about 16G of memory. We should find some way of letting people deploy either a predefined "lightweight" version of Kubeflow with just the most popular services, or have an easy way of picking and choosing which services to deploy.

This would be good to get community feedback on, so if anyone has opinions on what this should look like, feel free to comment. As a first pass, I propose that we add a second addon to microk8s called `kubeflow-lite` that contains these services:

- admission-webhook
- ambassador
- argo-controller
- jupyter-controller
- jupyter-web
- kubeflow-dashboard
- pipelines-api
- pipelines-db
- pipelines-persistence
- pipelines-scheduledworkflow
- pipelines-ui
- pipelines-viewer
- pipelines-visualization

This will be 13 services instead of 35 services, which will help alleviate the strain of deploying Kubeflow on a laptop. Something to note in this proposal is that login is not included, which may pose a security risk.

**Comment by ktsakalozos** [comment]
@knkski this is great news. Instead of a separate addon have you considered putting it into the existing kubeflow addon? With a flag you could decide if the addon would give you the full or the lite version:
```
microk8s enable kubeflow:bundle=lite
# or 
microk8s enable kubeflow:bundle=full
```
By default (no arguments) the lite version will be installed.
