### ISSUE TITLE
External IP not exposed.

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1294]
Hi, 
I had this working at one time, now it doesn't work anymore. 
What I'm trying to do is create a `dask cluster` on `microk8s kubernetes`. 
According to the `Helm` website: `https://hub.helm.sh/charts/dask/dask`, to deploy the cluster I must type in the following: 
```
helm repo add dask https://helm.dask.org/
helm repo update
helm install --name my-release dask/dask
```
However, I performed a `microk8s kubectl get svc` I don't see an `external IP signed`:
```
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
kubernetes          ClusterIP   10.152.183.1     <none>        443/TCP           40h
my-dask-jupyter     ClusterIP   10.152.183.219   <none>        80/TCP            12m
my-dask-scheduler   ClusterIP   10.152.183.89    <none>        8786/TCP,80/TCP   12m
```
When I performed a the following I get a `null` value: 
```echo tcp://$DASK_SCHEDULER:$DASK_SCHEDULER_PORT               -- Dask Client connection
  echo http://$DASK_SCHEDULER_UI_IP:$DASK_SCHEDULER_UI_PORT     -- Dask dashboard
  echo http://$JUPYTER_NOTEBOOK_IP:$JUPYTER_NOTEBOOK_PORT       -- Jupyter notebook
```
Please help, I think there may be some setup I need to perform with microk8s?
Thanks,

**Comment by balchua** [comment]
@vinhdiesal `ExternalIP` is only applicable if you have a load balancer in place.  Most cloud providers have their cloud controller create an external ip for you.
In microk8s, we have Metallb addon, which can provide an external IP.
`microk8s enable metallb:<specify ip range>`

**Comment by vinhdiesal** [comment]
Thanks @balchua I re-installed the `helm` with the `load balancer` override and it now works.
