### ISSUE TITLE
Failed to provision volume with StorageClass "gp2": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead

### ISSUE THREAD

**Issue by ratnadeeprdg** [ubuntu/microk8s#1298]
When I am trying to create mongo stack using stateful set containing pvc volumeclaim templates, I am getting the below error . I am using microk8s in my AWS EC2 instance with installation done through snap.

_** Failed to provision volume with StorageClass "gp2": Failed to get AWS Cloud Provider. GetCloudProvider returned <nil> instead **_

I have already created a default storage class gp2 explicitly in my cluster and again tried to create the stack, but receiving the same error.

My mongo yaml
================

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dev-omnius-vnext
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: dev-omnius-vnext
spec:
  selector:
    matchLabels:
      role: mongo
  serviceName: mongo
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
    spec:
      serviceAccountName: mongo
      containers:
        - args:
            #  - --smallfiles
            - --auth
          name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "huR55tfr"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "gp2"
        resources:
          requests:
            storage: 5Gi

Storage-class yaml file
=================

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

Appreciate your quick help on this.

**Comment by balchua** [comment]
I think there's a lot more to do than just adding the `StorageClass`.
Though never tried it, but i think the way to go is to use this https://github.com/kubernetes/cloud-provider-aws

**Comment by ratnadeeprdg** [comment]
I followed the link https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore and then ran the command below , before provisioning the mongo.yaml mentioned earlier, but still same result.

root@ip-10-7-23-91:/dev/shm/infra# aws ec2 create-volume --availability-zone=ap-south-1a --size=40 --volume-type=gp2
{
    "AvailabilityZone": "ap-south-1a",
    "CreateTime": "2020-06-12T09:01:16+00:00",
    "Encrypted": false,
    "Size": 40,
    "SnapshotId": "",
    "State": "creating",
    "VolumeId": "vol-0023152ef5758c014",
    "Iops": 120,
    "Tags": [],
    "VolumeType": "gp2"
}

So, it will be beneficial for me if somebody can provide list of specific steps that needs to be followed in order to troubleshoot the issue rather than just providing the links to go through it.

**Comment by ratnadeeprdg** [comment]
@balchua  I followed the link [](https://github.com/kubernetes/cloud-provider-aws) provided by you but all I understood is that I need to pass flag --cloud-provider kubelet, kube-apiserver, and kube-controller-manager. Any way to do so in microk8s?

**Comment by balchua** [comment]
To change the `kubelet`, `kube-apiserver` and controller.
Go to the directory `/var/snap/microk8s/current/args`, if you see the file `kubelet` you can add the argument `--cloud-provider`.
Im not familiar with aws stuffs so i can't be too much of a help.
