### ISSUE TITLE
Microk8s enable is very slow

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1306]
What I did was reinstalled `Ubuntu 18.04` so I can install `CUDA 11.0 RC Toolkit` and then I performed an upgrade to `Ubuntu 20.04`. Now it takes forever like 10-30 minutes for the `microk8s.enable` to respond. I reinstalled `microk8s` with purge and the problem still exists. 
Is there something that can make it go faster?

**Comment by balchua** [comment]
@vinhdiesal what particular addon you are enabling?
Are also experiencing the same slow response when using `microk8s status` command?
Thanks

**Comment by vinhdiesal** [comment]
I ended up reinstalling `Ubuntu` and things are back to normal.

**Comment by l-4-l** [comment]
I have the same problem. But I cannot "just reinstall" my Ubuntu 20.04 LTS server. I suppose it is something with DNS response

$ microk8s.enable dashboard dns
(... waiting ....)
