### ISSUE TITLE
Feature Request - Backup And Restore

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1307]
I have found this issue https://github.com/ubuntu/microk8s/issues/223 which went stale. I was wondering what the best way of backing up and restoring a cluster is.

Is it just a case of backing up etcd and the certs like it would be with kubeadm?

**Comment by balchua** [comment]
There is another issue https://github.com/ubuntu/microk8s/issues/820 which can potentially address more than just backup and restore based on the user's need is to utilize snap hooks.

**Comment by sstubbs** [comment]
ok thanks I'll see how I can use this.

**Comment by balchua** [comment]
Do you think adding velero addon will be useful? https://velero.io/docs/v1.4/

**Comment by sstubbs** [comment]
This would be great.
