### ISSUE TITLE
Distributed Machine Learning 

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1308]
My goal is to perform distributed machine learning using `microk8s`. I want a Jupyter Notebook to be performed between my machines.
Before I joined the nodes together on the network, I performed a `kubeflow` and `helm/dask` installation only on the master node. Even though there are multiple machines on the Kubernetes cluster, when I execute kubeflow or jupyter notebook, it only works off the one machine. 
How do I make it so that it utilizes the different nodes on the `kubernetes` cluster?

**Comment by ktsakalozos** [comment]
Could you describe the exact steps you are following to get to your setup? K8s and kubeflow should take advantage the entire cluster, not just one node.

@knkski this might interest you.

**Comment by vinhdiesal** [comment]
I have three machines: 

**PART ONE**
- Razer with Ubuntu 20.04 

1. `sudo snap install microk8s --classic`
2. `microk8s.enable dns dashboard ingress fluentd register istio`
3. `microk8s.enable kubeflow`

**PART TWO**
- iMAC with OSX Catalina

1. `brew install /ubuntu/microk8s`
2. `microk8s install`
3. `microk8s join ...........`

When I check the `kubernetes dashboard` it shows the `kubeflow` pods all running on the `Razer node`. So if `kubeflow` pods are all running on the `Razer` node, when I execute a notebook server, will it utilize the entire cluster?

Thanks,

**Comment by ktsakalozos** [comment]
If you want to see pods spread across the cluster you may want to first form the cluster (via `microk8s.add-node` and `microk8s join`) and then enable the addons.
