### ISSUE TITLE
launch failed: instance "microk8s-vm" already exists

### ISSUE THREAD

**Issue by joedborg** [ubuntu/microk8s#1313]
Originates from @bmbferreira on https://github.com/ubuntu/microk8s/issues/1287#issuecomment-642731101

```
> microk8s install
launch failed: The following errors occurred:
Instance stopped while starting
launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


launch failed: instance "microk8s-vm" already exists


An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again
```

**Comment by joedborg** [comment]
Hi @bmbferreira,
Can you please try running `microk8s uninstall` before `microk8s install` and let me know if you still see an issue?

Many thanks, 
Joe

**Comment by bmbferreira** [comment]
Hi @joedborg ,
Thanks for prioritising this. I think the problem is related with hyperkit since it worked when I switched to virtualbox, by running this `multipass set local.driver=virtualbox`.

Hyperkit version: `0.20200224`
OS: `macOS Catalina 10.15.5`
Docker: `19.03.8, build afacb8b`

**Comment by joedborg** [comment]
No problem @bmbferreira.  Are you happy to stay on Virtualbox, or would you like to try and fix with Hyperkit?

Out of interest, did you also have Minikube installed too?

**Comment by bmbferreira** [comment]
> No problem @bmbferreira. Are you happy to stay on Virtualbox, or would you like to try and fix with Hyperkit?
I'm ok with virtualbox
> 
> Out of interest, did you also have Minikube installed too?
Yes, and I noticed that I was also having problems with hyperkit. When I changed to virtualbox or docker it worked, so I guess this is not a problem with microk8s. Thank you!

**Comment by joedborg** [comment]
No problem @bmbferreira, thanks again for bringing this to our attention.  We'll close this issue but try to investigate a way we can document or script a fix for MacOS after minikube.

**Comment by slmingol** [comment]
I ran into a similar issue while I had a VPN connection running, after stopping it I was able to `microk8s uninstall` and `microk8s install` and things worked.

```
$ multipass list
Name                    State             IPv4             Image
microk8s-vm             Unknown           --               Ubuntu 18.04 LTS
```

Droppped VPN

```
$ microk8s uninstall
Thank you for using MicroK8s!

$ microk8s install
VM disk size requested exceeds free space on host.
Launched: microk8s-vm
Mount snap "core" (9289)                                                                                                                                                                      |2020-06-23T23:44:38-04:00 INFO Waiting for restart...
microk8s (latest/stable) v1.18.4 from Canonical✓ installed
MicroK8s is up and running. See the available commands with `microk8s --help`.

$ multipass exec microk8s-vm -- lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

$ microk8s status --wait-ready
microk8s is running
addons:
cilium: disabled
dashboard: disabled
dns: disabled
fluentd: disabled
gpu: disabled
helm: disabled
helm3: disabled
host-access: disabled
ingress: disabled
istio: disabled
jaeger: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
prometheus: disabled
rbac: disabled
registry: disabled
storage: disabled
```

**Comment by nc-ruth** [comment]
@slmingol same issue here, dropping the VPN connection did solve the issue.

**Comment by NathanDotTo** [comment]
```
microk8s install                     
launch failed: The following errors occurred:                                   
microk8s-vm: timed out waiting for response
launch failed: instance "microk8s-vm" already exists                            
... 
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

**Comment by NathanDotTo** [comment]
I have the same issue it seems. Om a MBP M1 macOS 12.6. I originally used Homebrew. During the Homebew phase I was asked to change my security settings, see attached image. After following those instructions I uninstalled with Homebrew, reinstalled with Homebrew, then tried `microk8s install`, `microk8s uninstall`, and `microk8s install` again.

No luck.

![Untitled 4](https://user-images.githubusercontent.com/13392790/194096034-5ae1e0fd-7b28-4a03-bdb8-ca933178f333.png)
