### ISSUE TITLE
Self Signed Registry - X509: certificate signed by unknown authority Error 

### ISSUE THREAD

**Issue by kstedman9** [ubuntu/microk8s#1321]
So I just started started using microk8s today, but I have been developing in DCOS and Kubernetes for years now.  We have a development docker registry on our network that is self signed running on https with no proxy.  I cannot figure out how to properly configure microK8s to talk to this registry.   (I have another kubernetes cluster that is working just fine not microk8s)

The machine is an Ubuntu linux server with microk8s installed through snap.  I installed docker through snap also.  On the same machine docker is talking to the registry just fine and can pull an image from the registry.   In docker I do not need the insecure_skip_verify since I have the crt file. But I tried adding it to the containerd config just to see if it would work.

Attached is the microk8s inspect that you asked for.  Below is my containerd-template.toml section for the registry.  Hopefully someone can tell me what I am doing wrong.  I have been reading every article on the internet that I could find to fix this issue but nothing seems to be working.  I have tried both DNS name and IP address for the registry.  

    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."localhost:32000"]
          endpoint = ["http://localhost:32000"]
        [plugins.cri.registry.mirrors."bootstrap.day.dbresearch.net:5000"]
          endpoint = ["https://bootstrap.day.dbresearch.net:5000"]

      [plugins.cri.registry.configs."bootstrap.day.dbresearch.net:5000".tls]
        insecure_skip_verify = true
        ca_file = "/var/snap/microk8s/current/certs/bootstrap-registry.crt"

[inspection-report-20200617_193458.tar.gz](https://github.com/ubuntu/microk8s/files/4794789/inspection-report-20200617_193458.tar.gz)

**Comment by balchua** [comment]
The `insecure_skip_verify` was added from containerd 1.3.
The upgrade to containerd 1.3.4 was recently merged.
@ktsakalozos which channel should have the latest containerd, maybe @kstedman9  can give that a try.

**Comment by kstedman9** [comment]
@balchua Thank you for the heads up.  I see where you did the merge but SNAP does not show a channel with that yet.  So it sounds like for the short term to get what I need to work is to just create a simple http -> https proxy around my registry unless that channel is going to show up today.

**Comment by balchua** [comment]
Usually it gets to the `latest/stable` within a day.  If not, you can try the channel `edge`.
But edge channel is not for prod use at all.

**Comment by kstedman9** [comment]
@balchua  I just just updated to the latest/edge version which was updated with yesterday's date and everything seems to be working now.  Thank you.  

This is only for development and test, so at this point I do not care if we are on edge.

**Comment by balchua** [comment]
@kstedman9 great to hear that. I will be closing this issue. If there are other issues feel free to file a new one.
Thanks!
