### ISSUE TITLE
Dask Helm Chart - Ingress Route error

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1324]
I'm having issues installing `dask-gateway` helm chart. 
I followed the revised version of the helm installation procedure: 
`microk8s helm repo add daskgateway https://dask.org/dask-gateway-helm-repo/`
`microk8s helm repo update`
```
microk8s helm upgrade --install \
>     --namespace $NAMESPACE \
>     --version $VERSION \
>     --values path/to/your/config.yaml \
>     $RELEASE \
>     daskgateway/dask-gateway
```
I have the following error: 
```
Error: validation failed: [unable to recognize "": no matches for kind "IngressRoute" in version "traefik.containo.us/v1alpha1", unable to recognize "": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"]
```
Please help with this issue. 
Thanks,

**Comment by vinhdiesal** [comment]
This is solved by creating the crd objects per the provided traefik.yaml file. 

Thanks,

**Comment by hussainsultan-mss** [comment]
@vinhdiesal I am having the same issue. How did you end up providing the traefik.yaml file to helm?
