### ISSUE TITLE
restarting a single node by master node

### ISSUE THREAD

**Issue by andredrumond1995** [ubuntu/microk8s#1325]
[inspection-report-20200618_122206.tar.gz](https://github.com/ubuntu/microk8s/files/4799842/inspection-report-20200618_122206.tar.gz)

is it possible to restart a worker node by the master node?

sometimes it is needed when some changes need to be applied
what i've done is 'sudo microk8s stop' and then i ran 'start' param, but it was in worker node

**Comment by ktsakalozos** [comment]
This is a nice feature request. We do not have this functionality yet. You have to login into the node to restart it.

**Comment by andredrumond1995** [comment]
thank you!
