### ISSUE TITLE
`microk8s dashboard-proxy` produces `https://N/A:10443`

### ISSUE THREAD

**Issue by javajon** [ubuntu/microk8s#1327]
Generated tarball to this issue. [inspection-report-20200618_225707.tar.gz](https://github.com/ubuntu/microk8s/files/4802268/inspection-report-20200618_225707.tar.gz)

- Installed the latest microk8s fresh on Windows 10 using microk8s-installer.exe
- Ran `microk8s enable dashboard dns registry`
- List of pods appears healthy and running: `microk8s kubectl get pods -A`

However, attempting access to dashboard provides an unexpected URL and is not accessible at https://127.0.0.1:10433.

```
$ microk8s dashboard-proxy
Checking if Dashboard is running.
Waiting for Dashboard to come up.
Dashboard will be available at **https://N/A:10443**
Use the following token to login:
e...[omitted for brevity]..w
Forwarding from 0.0.0.0:10443 -> 8443
```
What is causing the "N/A" to appear?
https://N/A:10443

**Comment by javajon** [comment]
Uninstalled both microk8s and multipass. Upgraded VirtualBox to version 6.1.8. Rebooted. Reinstalled microk8s and still getting the same error.  Multipass reports instance running:
```
$ multipass list
Name                    State             IPv4             Image
microk8s-vm             Running           N/A              Ubuntu 18.04 LTS
```
However, not seeing VM in VirtualBox, if it's supposed to be listed there.

**Comment by joedborg** [comment]
Hi @javajon, 

Apologies for this, I’m not sure why Multipass isn’t assigning an IP address to your container.  I’ll do some investigation and update you shortly.

**Comment by Telemarking** [comment]
I do have the same problem.

**Comment by tommeke** [comment]
I have the same issue on Windows 10 Home edition.
So it's using Oracle VirtualBox and not Hyper-V.

**Comment by javajon** [comment]
@tommeke I just tried this again last week and experienced the same problem. On the machine I tried, I have **Windows 10 Home edition edition** as well and perhaps therein lies the nugget of truth. A deviation of Windows often forgotten. However, Minikube there works fine.

**Comment by mircotamburini** [comment]
Same problem with win 10 pro and virtualbox... no problem with minikube

**Comment by jgengo** [comment]
Same problem with OSX Catalina
