### ISSUE TITLE
HA-cluster: calico-node pods are exceedingly verbose

### ISSUE THREAD

**Issue by nikkoura** [ubuntu/microk8s#1334]
When enabling ha-cluster, calico replaces flannel. 
The default logging settings used for calico-node pods generates a massive amount of log - about 10 entries/second.

This can be adjusted by modifying the `FELIX_LOGSEVERITYSCREEN` env variable for calico-node pods, in the relevant Daemonset.

**Comment by balchua** [comment]
Since the pr is merged, closing this one.
