### ISSUE TITLE
Add A Second Storage Class

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1337]
I have two different mounted volumes. I would like two different storage classes Is there any way to configure the hostpath provisioner to add a second storage class so I can specify in PVC which to use?

**Comment by sstubbs** [comment]
I have found https://github.com/rancher/local-path-provisioner which seems to exactly what I need. I just install a helm release per path.

**Comment by ktsakalozos** [comment]
It would be great to introduce an addon to provide HA storage in an cluster.

**Comment by sstubbs** [comment]
I've been testing this and its working well so far if it was added as an addon I would happily use it but it's easy enough to setup using their helm chart for the time being. When I get some time to understand the source of microk8s a bit better I will try and do a pr for this.

**Comment by balchua** [comment]
@ktsakalozos the closest i got to a distributed volume is using rook/ceph.  But to set it up is not easy on a laptop.
Do you think an nfs provisioner can help and pinned to the control plane?

**Comment by sstubbs** [comment]
I've been using rook/ceph. The main issue I have with it is that it takes complete control over the block devices. So If I reinstall microk8s it's a pain to set up the osds again. 

I'm using this rancher local-path-provisioner for local volumes and then minio using one of these local volumes as it can be run in standalone or clustered mode .

If anyone has a better idea for clustered storage that survives reinstalls of microk8s I would be really happy.

**Comment by sstubbs** [comment]
I've been trying https://openebs.io/ which works well and is versatile in terms of providing local pvs as well as there own clustered solutions. it's easy to add different storageclasses for different host paths.

**Comment by balchua** [comment]
Is it easy to get it up and running without the complexity of rook ceph? 😁

**Comment by sstubbs** [comment]
Yes very easy took a few minutes to go through the docs. Adding and removing extra storage classes is also painless so far which is nice. WIll be testing it today with deleting and recreating clusters and restoring microk8s dqlite for disaster recovery and see how it behaves.

**Comment by eosantigen** [comment]
Hi and Many Thanks for microk8s! I would like to ask here (as I think it's a related question) whether an NFS storage class provisioner is supported, and what would the implications be if the storage backend under the hostpath pvc's directory _(/var/snap/microk8s/common/default-storage)_ is on an external NFS server - meaning, if I manually get to attach it as it is without the storage class (simply through /etc/fstab). _Thank you._

**Comment by sstubbs** [comment]
> Hi and Many Thanks for microk8s! I would like to ask here (as I think it's a related question) whether an NFS storage class provisioner is supported, and what would the implications be if the storage backend under the hostpath pvc's directory _(/var/snap/microk8s/common/default-storage)_ is on an external NFS server - meaning, if I manually get to attach it as it is without the storage class (simply through /etc/fstab). _Thank you._

I'm no storage expert but from experience kubernetes is quite particular about access modes of storage classes. I would be hesitant to add a provisioner designed for local to something network attached. I would suggest using an NFS provsioner like https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client. If your app can use s3 api why not install minio on th remote side and access it that way. I try to use minio where I can.

**Comment by sstubbs** [comment]
One more benefit of openebs I've found is that the pvc chart in the microk8s chart shows the correct capacity and usage. I wasn't getting any data in it when I was the using the microk8s storage addon. I have a two local pv storage classes and quite a few pvcs and they all showing correctly which is nice.

**Comment by balchua** [comment]
@sstubbs this is great. 😊 Is this something you keen to contribute?  A storage that can work for single node and multi node is perfect.

**Comment by sstubbs** [comment]
I would happily contribute this.  I've looked at this. https://github.com/ubuntu/microk8s/blob/master/docs/build.md 
My dev machine is a mac though. How do I go about this? Do I need to run a vm?

**Comment by sstubbs** [comment]
It would be great if there was a way of doing this in docker.

**Comment by sstubbs** [comment]
currently I'm using openebs for direct pvs on nvme drives and then minio using direct csi drive for object storage on 4 ssds using their direct csi driver. It seems to be a lot better performance wise than ceph and a lot simpler to setup.

They merged a PR I did which makes it compatible with microk8s https://github.com/minio/direct-csi/issues/11

Storage seems to be the biggest nightmare that I've run into with kubernetes in general so I think microk8s would benefit greatly from having openebs for local and distributed block storage as a plugin. 

Then minio as a plugin for object storage using direct-csi (only caveat with this is it needs minium of 4 drives)

**Comment by sstubbs** [comment]
Perhaps minio is out of scope of microk8s but openebs would definitely be great.

**Comment by madalinignisca** [comment]
MicroK8s fresh installation, HA enabled by default, while storage addon is still old fashion localpath.
I vote for openebs, as I experimented it on MicroK8s and did not encounter any issue so far. I've been using it as the HA related chapters in a book I write for managing WordPress on MicroK8s and I intend to keep users away from the current storage addon, with intention to help them avoid a lot of trouble in the future.

Openebs could be default configured for current storage addon alternative using it's localpath mode, as I do understand a lot of people are not using HA mode yet, but allow the rest of us to extend to our needs easy in HA mode.

**Comment by ktsakalozos** [comment]
We need a good storage story for clusters.

@madalinignisca let us know when your book comes out. We may be able to promote it.

**Comment by sstubbs** [comment]
It looks like minio also has changed from recommending their own csi plugin to Openebs in their operator. I've been using Openebs for a while now with microk8s on a standard node and a 3 node cluster and it works well. They have also now created different charts for the different storage modes https://github.com/openebs/openebs/releases/tag/v2.5.0

Perhaps adding the localpv to microk8s would be a good idea. This does a better job than the current storage plug-in in my opinion. https://openebs.github.io/dynamic-localpv-provisioner

**Comment by madalinignisca** [comment]
> We need a good storage story for clusters.
> 
> @madalinignisca let us know when your book comes out. We may be able to promote it.

I'm in early stage with the [book](https://leanpub.com/wp-microk8s/), covering at this moment https. Storage will be in a few weeks in progress from my plan, and I intend to fill in adding OpenEbs as something that users should consider a standard, as without it, there is no easy way for real high availability and horizontal scaling for people. I wanna help people to be able to setup on a 3 nodes cluster, triple replication of data on all nodes, so they can be even sure that if one node is in trouble, everything still runs smooth :). I think that is more reliable than using the public cloud's volumes attached, as that is not allowing horizontal scaling on multiple nodes.

I was even thinking, what if current Storage would use OpenEbs and allowing people only to define pools of storage to get HA easy without too much hustle?

**Comment by balchua** [comment]
Finally got the time yo whip up a PR with OpenEBS.  https://github.com/ubuntu/microk8s/pull/2080

Feel free to do a review.  Hopefully we can be ready before the 1.21 release.

**Comment by balchua** [comment]
Closing the PR, since OpenEBS addon is now available from MicroK8s v1.21

**Comment by madalinignisca** [comment]
Ah, I forgot to add an extra question. Will the NFS support for OpenEBS be used once it's maturing from experimental stage?
https://github.com/openebs/dynamic-nfs-provisioner

Possible, alternative, NFS server provisioner might worki on top of OpenEBS Jiva as well.

**Comment by balchua** [comment]
@madalinignisca i haven't tried that at all.
