### ISSUE TITLE
Unbind microk8s installation from Multipass

### ISSUE THREAD

**Issue by ranst91** [ubuntu/microk8s#1338]
When Installing microk8s using an installer, it requires that Multipass will be installed, and insists on installing it. If Multipass is already installed and the user clicks cancel on the Multipass installation, the microk8s one gets stuck.

I suggest unbinding the two in some way, Since Multipass has now version 1.3 and microk8s installer installs 1.2.

**Comment by joedborg** [comment]
Hi @ranst91,
Please try installer from https://github.com/ubuntu/microk8s/suites/780478462/artifacts/8232134, if you are installing on Windows.

We are waiting for this to be signed internally.

Thanks,
Joe

**Comment by joedborg** [comment]
MicroK8s Windows installer 2.0.0 released with Multipass 1.3.
