### ISSUE TITLE
How to backup dqlite in ha mode

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1339]
Hi,

I'm running the ha-mode to test it out. Works great so far. When using the standard mode I backup etcd like:

```
/snap/microk8s/current/etcdctl \
--endpoints=127.0.0.1:12379 \
--cacert=/var/snap/microk8s/current/certs/ca.crt \
--cert=/var/snap/microk8s/current/certs/server.crt \
--key=/var/snap/microk8s/current/certs/server.key snapshot save backup.db
```

Is there an equivalent command to backup dqlite?

**Comment by ktsakalozos** [comment]
Hi @sstubbs 

We are packaging a `migrator` tool with the snap that will take care of data migration and backups from/to etcd and dqlite. There is a PR up [1] that adds the backup-dqlite functionality. It should soon be added to the snap. 

[1] https://github.com/ktsakalozos/go-migrator/pull/1/files#diff-7ddfb3e035b42cd70649cc33393fe32cR31

**Comment by sstubbs** [comment]
That really is great news. This project is amazing.

**Comment by sstubbs** [comment]
Hi,
I just wanted to check when will this be available in the ha-preview snap?
