### ISSUE TITLE
Homebrew install Microk8s MacOSx

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1340]
I'm not sure if I am imagining things, but for a couple days straight after installing `microk8s` through `homebrew` on `MAC OSX`, i was able to get the same VM ip address as the host computer which made it possible to be on a cluster and install pods from the master as if I using the Ubuntu version of `microk8s`. Now, after I reinstalled homecrew, I no longer have this capability. Is there a way to get this capability back?

**Comment by ktsakalozos** [comment]
I think what you are describing is bridged mode networking. You can have a look at the multipass docs [1] to see how this can be configured. 

[1] https://multipass.run/docs/using-virtualbox-in-multipass-macos

**Comment by vinhdiesal** [comment]
When I set `sudo multipass set local.driver=virtualbox` on the Mac OSx, microk8s was able to deploy the pods to the nodes. 

Thanks!
