### ISSUE TITLE
InvalidDiskCapacity in a fresh install of microk8s on Ubuntu 20.04 on Raspberry Pi 4 8GB 

### ISSUE THREAD

**Issue by nuinattapon** [ubuntu/microk8s#1347]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
I install microk8s fresh in my new Raspberry PI 4 8GB model today on top of UBUNTU 20.04LTS.

And I found that my K8s node is always not ready because of "invalid capacity 0 on image filesystem". 
I believe that this is a bug. Pls advise.

`NAME     STATUS     ROLES    AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION     CONTAINER-RUNTIME
ubuntu   NotReady   <none>   13m   v1.18.3   192.168.1.110   <none>        Ubuntu 20.04 LTS   5.4.0-1012-raspi   containerd://1.2.5
df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           782M  4.4M  777M   1% /run
/dev/mmcblk0p2   29G  8.2G   20G  30% /
tmpfs           3.9G   29M  3.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0       86M   86M     0 100% /snap/core/9290
/dev/loop1       49M   49M     0 100% /snap/core18/1708
/dev/loop3       24M   24M     0 100% /snap/snapd/7267
/dev/loop4       62M   62M     0 100% /snap/lxd/14808
/dev/loop7       49M   49M     0 100% /snap/core18/1753
/dev/loop6       26M   26M     0 100% /snap/snapd/8147
/dev/loop5       64M   64M     0 100% /snap/lxd/15685
/dev/mmcblk0p1  253M  107M  146M  43% /boot/firmware
tmpfs           782M   20K  782M   1% /run/user/1000
/dev/loop2      165M  165M     0 100% /snap/microk8s/1423`

[k_describe_node.txt](https://github.com/ubuntu/microk8s/files/4820171/k_describe_node.txt)
[inspection-report-20200623_214123.tar.gz](https://github.com/ubuntu/microk8s/files/4820177/inspection-report-20200623_214123.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @nuinattapon, I suspect cgroups are not enabled. Can you please take a look at [1]? 

[1] https://microk8s.io/docs/install-alternatives#heading--arm

**Comment by nuinattapon** [comment]
I tried install another UBUNTU 20.04 from scratch again today. And I have tried following the instruction to enable cgroups as advised above. But the issue is still there. Here is a new inspect file
[inspection-report-20200624_190633.tar.gz](https://github.com/ubuntu/microk8s/files/4825238/inspection-report-20200624_190633.tar.gz)


`ubuntu@ubuntu:~$ microk8s kubectl describe nodes
Name:               ubuntu
Roles:              <none>
Labels:             beta.kubernetes.io/arch=arm64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=arm64
                    kubernetes.io/hostname=ubuntu
                    kubernetes.io/os=linux
                    microk8s.io/cluster=true
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 24 Jun 2020 18:41:49 +0700
Taints:             node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  ubuntu
  AcquireTime:     <unset>
  RenewTime:       Wed, 24 Jun 2020 19:02:23 +0700
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 24 Jun 2020 19:02:23 +0700   Wed, 24 Jun 2020 18:41:49 +0700   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 24 Jun 2020 19:02:23 +0700   Wed, 24 Jun 2020 18:41:49 +0700   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 24 Jun 2020 19:02:23 +0700   Wed, 24 Jun 2020 18:41:49 +0700   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Wed, 24 Jun 2020 19:02:23 +0700   Wed, 24 Jun 2020 18:41:49 +0700   KubeletNotReady              [container runtime status check may not have completed yet, missing node capacity for resources: ephemeral-storage]
Addresses:
  InternalIP:  192.168.1.4
  Hostname:    ubuntu
Capacity:
  cpu:     4
  memory:  7998780Ki
  pods:    110
Allocatable:
  cpu:     4
  memory:  7896380Ki
  pods:    110
System Info:
  Machine ID:                 faee705dd30c4a1ea47e9293b9c08635
  System UUID:                faee705dd30c4a1ea47e9293b9c08635
  Boot ID:                    1cfa0b44-73db-4cc2-b34b-6899301b3b81
  Kernel Version:             5.4.0-1012-raspi
  OS Image:                   Ubuntu 20.04 LTS
  Operating System:           linux
  Architecture:               arm64
  Container Runtime Version:  containerd://1.2.5
  Kubelet Version:            v1.18.3
  Kube-Proxy Version:         v1.18.3
Non-terminated Pods:          (0 in total)
  Namespace                   Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----    ------------  ----------  ---------------  -------------  ---
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
Events:
  Type     Reason                   Age    From                Message
  ----     ------                   ----   ----                -------  
  ...
  ...
  Normal   Starting                 17s    kubelet, ubuntu     Starting kubelet.
  Warning  InvalidDiskCapacity      10s    kubelet, ubuntu     invalid capacity 0 on image filesystem
  Normal   Starting                 10s    kubelet, ubuntu     Starting kubelet.
  Normal   NodeHasSufficientMemory  10s    kubelet, ubuntu     Node ubuntu status is now: NodeHasSufficientMemory
  Normal   Starting                 3s     kubelet, ubuntu     Starting kubelet.
  Warning  InvalidDiskCapacity      2s     kubelet, ubuntu     invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  2s     kubelet, ubuntu     Node ubuntu status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    2s     kubelet, ubuntu     Node ubuntu status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     2s     kubelet, ubuntu     Node ubuntu status is now: NodeHasSufficientPID`

**Comment by nuinattapon** [comment]
OK, thanks for the instruction. This issue happen because of cgroups is not enabled. The instruction at https://microk8s.io/docs/install-alternatives#heading--arm won't work on Ubuntu 20.04LTS. MicroK8s master node is up now. 

Instead I found the solution in https://askubuntu.com/questions/1189480/raspberry-pi-4-ubuntu-19-10-cannot-enable-cgroup-memory-at-boostrap . And what I need is changing /boot/firmware/cmdline.txt

`root@ubuntu:/boot/firmware# cat cmdline.txt

net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc`
