### ISSUE TITLE
Unable to pull from private insecure docker registry

### ISSUE THREAD

**Issue by zenbones** [ubuntu/microk8s#1349]
We have a private insecure registry, and this works fine...

docker pull docker.forio.com/k8s/epicenter/desktop/epicenter-facade:2.9.0

...but this does not...

microk8s.ctr image pull docker.forio.com/k8s/epicenter/desktop/epicenter-facade:2.9.0
docker.forio.com/k8s/epicenter/desktop/epicenter-facade:2.9.0: resolving      |--------------------------------------| 
elapsed: 0.6 s                                                 total:   0.0 B (0.0 B/s)                                         
ctr: no signatures

I have added...

    [plugins.cri.registry.mirrors."docker.forio.com"]
      endpoint = ["http://docker.forio.com:4243"]

...to no avail. And have tried with and without the port, but got the same 'no signatures'.

What does it mean?

**Comment by ktsakalozos** [comment]
@joedborg @CalvinHartwell have you seen anything similar in your experimentation with the registries?

**Comment by joedborg** [comment]
I believe this to be an issue with the remote server as I get the same issue inside a Ubuntu VM with a fresh install of Containerd

```
$ sudo ctr image pull docker.forio.com/k8s/epicenter/desktop/epicenter-facade:2.9.0
docker.forio.com/k8s/epicenter/desktop/epicenter-facade:2.9.0: resolving      |--------------------------------------| 
elapsed: 0.1 s                                                 total:   0.0 B (0.0 B/s)                                         
ctr: no signatures
```

And from docker.io is working:

```
$ sudo ctr image pull docker.io/library/hello-world:latest
docker.io/library/hello-world:latest:                                             resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:d58e752213a51785838f9eed2b7a498ffa1cb3aa7f946dda11af39286c3db9a9:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:0e03bdcc26d7a9a57ef3b6f1bf1a210cff6239bff7c8cac72435984032851689:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:bf756fb1ae65adf866bd8c456593cd24beb6a0a061dedf42b26a993176745f6b:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 0.4 s                                                                    total:  2.6 Ki (6.4 KiB/s)                                       
unpacking linux/amd64 sha256:d58e752213a51785838f9eed2b7a498ffa1cb3aa7f946dda11af39286c3db9a9...
done
```

**Comment by joedborg** [comment]
Yes, it would appear their manifest is failing this check https://github.com/containerd/containerd/blob/574bde08ba1a698d96fd4a294443ea90fd7bd213/remotes/docker/schema1/converter.go#L547

Which is either a bug in containerd or in the image you are trying to pull.

**Comment by zenbones** [comment]
Not sure how it could be a bug in the image, in that it's a valid docker image, built by packer, which works when pulled by docker? If docker can pull the docker image, I'd have to ask why the failing check is appropriate? Is there a way to switch microk8s to use docker as opposed to containerd?

**Comment by joedborg** [comment]
@zenbones You could try pulling it into Docker and then pushing it into a MicroK8s registry to see if that fixes it (https://microk8s.io/docs/registry-built-in).  I'm not sure why this image, in particular, isn't working with containerd, but is with Docker.  I'd definitely raise a bug there too so they are aware.

In reference to Docker with MicroK8s; it is technically possible.  You can change the kubelet to point to a local Dockerd but this isn't something we can help with.

**Comment by zenbones** [comment]
Sounds fair. Thanks for the advice. I'll try setting up the local registry and let you know how it goes. I'll file this against containerd to see what they have to say.

**Comment by joedborg** [comment]
Thanks @zenbones.  I'll close this issue.  Feel free to link that containerd issue here, in case it's useful to others with the same issue.  I'll close this issue but please do comment here if you come across any issues with the registry.

**Comment by heimerdingerUltra** [comment]
Hello I have the same issue @joedborg, did you arrived to fix it ?
