### ISSUE TITLE
heapster can not connect to the influxdb

### ISSUE THREAD

**Issue by auqf** [ubuntu/microk8s#1350]
can not see the cpu usage and mem usage.
![image](https://user-images.githubusercontent.com/8895540/85496237-90998900-b60e-11ea-873e-066d0c524cce.png)
![image](https://user-images.githubusercontent.com/8895540/85496353-b9218300-b60e-11ea-8cfd-8431f9f0fbe0.png)

**Comment by ktsakalozos** [comment]
Hi @auqf, how did you install MicroK8s? Did you select a channel? What addons do you have enables? Did you try the Prometheus and the metrics server addons?
