### ISSUE TITLE
microk8s (Windows) command not found after fresh installation

### ISSUE THREAD

**Issue by mmattersdorfer** [ubuntu/microk8s#1351]
Please run `microk8s inspect` and attach the generated tarball to this issue. --> Sorry cannot run microk8s inspect

After fresh / first installation of microk8s on Windows 10 Pro (Version 1903) with the 2.0 installer, i cannot run microk8s commands. All commands are returning:

sudo: microk8s.status: command not found
An error occurred when trying to execute 'sudo microk8s.status --wait-ready' with 'multipass': returned exit code 1.

or

sudo: microk8s.inspect: command not found
An error occurred when trying to execute 'sudo microk8s.inspect' with 'multipass': returned exit code 1.

**Comment by joedborg** [comment]
Hey @mmattersdorfer,

Can you try `microk8s status`, i.e. a space and not a period?

Thanks,
Joe

**Comment by mmattersdorfer** [comment]
Hi @joedborg,

I tried it with a space.... In the error message there is always a period instead.

Greetings,
Marcus

**Comment by joedborg** [comment]
Thanks @mmattersdorfer 

Did you check the "Add MicroK8s to PATH" when installing?  And have you tried opening a new `cmd` window to try?

Thanks,
Joe

**Comment by mmattersdorfer** [comment]
Hello @joedborg,

yes I checked the option to add microk8s to the path. And I used a new CMD. I even tried a reboot. No success.

Thanks for your help.

**Comment by joedborg** [comment]
No problem @mmattersdorfer, we'll get to the bottom of this.

Can you open a `cmd` window and show me the output of `echo %PATH%`, please?

**Comment by mmattersdorfer** [comment]
Hi @joedborg,

here is the result of echo %PATH%:

C:\Program Files\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin;C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;c:\ProgramData\chocolatey\bin\;C:\Python38\Scripts\;C:\Python38\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\tools\groovy-3.0.3\bin;c:\Tools\apache-maven-3.6.2\\bin;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Webex\Plugins;C:\Users\usimmatter\.jpm\windows\bin;C:\Program Files (x86)\Yarn\bin\;C:\tools\groovy-3.0.3\bin;C:\Program Files (x86)\Sennheiser\SoftphoneSDK\;C:\tools\groovy-3.0.3\bin;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\usimmatter\.windows-build-tools\python27\;C:\Users\usimmatter\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Oracle\VirtualBox;C:\tools\dart-sdk\bin;C:\Users\usimmatter\AppData\Roaming\Pub\Cache\bin;C:\tools\flutter;C:\Users\usimmatter\AppData\Local\Pandoc\;C:\Users\usimmatter\AppData\Local\Yarn\bin;C:\Program Files\kdiff3;C:\Users\usimmatter\AppData\Roaming\npm;C:\Program Files\Multipass\bin;C:\Program Files\MicroK8s

**Comment by wjpbiblio** [comment]
I can confirm this also happens for me, this is sadly a blocking issue for the windows installer.

microk8s status
sudo: microk8s.status: command not found
An error occurred when trying to execute 'sudo microk8s.status' with 'multipass': returned exit code 1.

**Comment by dmirandab** [comment]
Hi!

Is there any update on this? I installed yesterday on Windows 10 pro version 2004 and I'm getting the same error. Path seems to be correct.

Thanks,
Daniel.

**Comment by joedborg** [comment]
Hi @mmattersdorfer, apologies for the late reply, GitHub notifications really suck...

It looks like PATH is set correctly (`C:\Program Files\MicroK8s`).

Could you please open a `cmd` and run `multipass exec microk8s-vm -- sudo snap list` and check that `microk8s` is listed?

Thanks,
Joe

**Comment by joedborg** [comment]
@wjpbiblio @dmirandab ^ if you could try that too, it'd be a great help.  thanks!

**Comment by mmattersdorfer** [comment]
Hi Joe,

here is the result:
`No snaps are installed yet. Try 'snap install hello-world'.`

Greetings
Marcus

**Comment by mmattersdorfer** [comment]
Trying to install microk8s snap manually ends in this:
`
multipass exec microk8s-vm -- sudo snap install microk8s --classic --channel=1.18/stable

error: cannot install "microk8s": persistent network error: Post
       https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup api.snapcraft.io: Temporary
       failure in name resolution
`

**Comment by joedborg** [comment]
Hey @mmattersdorfer,

Ah, thanks.  We do check for networking issue during install, so not sure why that was missed.  

Assuming

```
multipass exec microk8s-vm -- sudo ping -c 1 1.1.1.1
multipass exec microk8s-vm -- sudo ping -c 1 snapcraft.io

```

both fail, can you try looking over https://multipass.run/docs/troubleshooting-networking-on-windows to see if that fixes your issue.  If not, you could also switch to using Virtualbox instead of Hyper-V.  I know this can be inconvenient, but if it's an option it'll likely remedy the issues.

Thanks,
Joe

**Comment by dmirandab** [comment]
Hey all,

I ended up following this blog post which lead to a successful installation of microk8s over WSL2: https://wsl.dev/wsl2-microk8s/

Cheers!

**Comment by mmattersdorfer** [comment]
Hi @joedborg ,

the firewall of my company vpn blocked the calls. I deactivted it and then the pings and installation worked. Also the microk8s commands are now working.

Thanks,
Marcus

**Comment by joedborg** [comment]
Perfect, thanks for the update @mmattersdorfer

**Comment by tuananh** [comment]
I still have this issue on windows. the network test is fine (ping to 1.1.1.1 and netcraft works)

```An error occurred when trying to execute 'sudo microk8s.status --wait-ready' with 'multipass': returned exit code 1.```

**Comment by TibebeJS** [comment]
> I still have this issue on windows. the network test is fine (ping to 1.1.1.1 and netcraft works)
> 
> `An error occurred when trying to execute 'sudo microk8s.status --wait-ready' with 'multipass': returned exit code 1.`

Just run:
```
multipass exec microk8s-vm -- sudo snap install microk8s --classic
```

and it all should start working fine.

**Comment by danifgxcom** [comment]
Hi everyone,

In addition to the excellent answer that fixed my issue on Windows: 
`multipass exec microk8s-vm -- sudo snap install microk8s --classic`

I had to create the personal config file by creating the MicroK8s folder and then:
`microk8s config > config`

It seems that something is not well explained in the installation guide...

Thanks.

**Comment by danifgxcom** [comment]
Hi Joe,

I used the default values provided by the installer: 2VCPUs, 4GB of RAM and
50GB of disk.

The first time I ran into a disk space issue, but after that I did free
enough space and reinstalled, so the VM was OK.
I tried several times, with both Multipass versions... and I also created
the "primary" VM to check other things.
But it never worked.

As soon as I executed the sudo snap from Windows as explained before and
dumped the config file into the personal folder that I manually created,
everything worked fine.

I have seen that other people faced the same issue and that's why I found
such solution. So it is not that I resolved it, but I wanted to share it
with the MicroK8s Team so that you may update the installation guide if
required (or assess on what the issue is to avoid those manual steps).
On an Ubuntu host it does work perfectly! :)

Hope it helps.

Thank you.

Best regards,
   Dani.

**Comment by danifgxcom** [comment]
Hi again,

I have checked out the new installer...
But it is the project to generate the installers for the different OS.
It requires NSIS and the plugin to generate the Windows .msi file, but NSIS installer is not properly signed (downloaded from the  official website). I have read that it triggers false positives on some antivirus and on Windows Defender, but I cannot compromise my computer with this now.
So I will wait until the version 2.2.0 of your setup installer is released.

Cheers,
   Dani.
