### ISSUE TITLE
microk8s is not proper works on Raspberry Pi 4 B (ubnunu 20.04)

### ISSUE THREAD

**Issue by nVitaliy** [ubuntu/microk8s#1352]
1)
 - Raspberry Pi 4 B (4GB RAM)
 - microCd ADATA 32GB
 - LAN
 
2)
- From Windows 10 run Raspberry Pi Imager v1.3
- choose operating system: Ubuntu 20.04 LTS (Raspberry Pi3/4) 64-bit server OS
- choose appropriate SD card
- write

3) 
after success installation:
go to SD Card and update cmdline.txt -> 
`net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1`

4) 
run Raspberry (only power and LAN is plugin)

5) 
determine IP and connect via SSH
`sudo apt update`
`sudo apt upgrade -y`
`sudo reboot`

6) 
`sudo snap install microk8s --classic --channel=1.18/stable`
`sudo usermod -a -G microk8s $USER`
`sudo chown -f -R $USER ~/.kube`
`su - $USER`
`microk8s enable dns`
`microk8s kubectl create deployment microbot --image=dontrebootme/microbot:v1`

Expected result: Pod has running status
Actual result: Pod has CrashLoopBackOff status

[inspection-report-20200624_130825.tar.gz](https://github.com/ubuntu/microk8s/files/4825839/inspection-report-20200624_130825.tar.gz)

Thank you

**Comment by joedborg** [comment]
Hi @nVitaliy,

Thanks for raising the bug.

Could you please paste the output of `microk8s kubectl describe pod/microbot-6d97548556-t5bz4`?

Thanks,
Joe

**Comment by nVitaliy** [comment]
[microbot.txt](https://github.com/ubuntu/microk8s/files/4825925/microbot.txt)

Thanks

**Comment by joedborg** [comment]
Thanks @nVitaliy, will attempt to reproduce.

**Comment by joedborg** [comment]
Can reproduce this on an AWS a1 instance (ARM aarch64).  I imagine this is an issue with Microbot on ARM issue, will continue to dig.

**Comment by nVitaliy** [comment]
the same issue for `microk8s kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4` from https://kubernetes.io/pl/docs/tutorials/hello-minikube/

**Comment by joedborg** [comment]
Okay @nVitaliy, this is because the K8s docs are not providing you with multiarch images (which is a shock to me).

If you run `microk8s kubectl edit deployment.apps/microbot` and change image to `cdkbot/microbot-arm64:latest\, it'll work fine.

Same issue applies to the echoserver (https://github.com/kubernetes-retired/contrib/issues/2991).

**Comment by nVitaliy** [comment]
works
Thank you!

**Comment by nVitaliy** [comment]
I think need to update https://ubuntu.com/blog/deploying-kubernetes-locally-microk8s

Thanks

**Comment by joedborg** [comment]
Ah thank you @nVitaliy, I will raise that with the author to fix.

**Comment by mhawkshaw** [comment]
Hi @joedborg, can I check if this was fixed? I'm using Ubuntu 23.10 (aarch64) with MicroK8s v1.28.4 revision 6227 following the tutorial here: https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s and I experience the same problem. Changing the image to use cdkbot/microbot-arm64:latest works fine.
