### ISSUE TITLE
Snapcraft failure when building the snap from source

### ISSUE THREAD

**Issue by siddharths2710** [ubuntu/microk8s#1362]
My OS is Ubuntu 18.04, and while following the procedure for [building the snap from source](https://github.com/ubuntu/microk8s/blob/master/docs/build.md), I was halted by this error from snapcraft:

```
$ snapcraft --use-lxd

+ . build-scripts/set-env-binaries-location.sh
+ set -eu
Downloading binaries
+ . build-scripts/fetch-other-binaries.sh
+ set -eu
+ mkdir -p build/kube_bins/v1.18.5
+ cd build/kube_bins/v1.18.5
+ curl -LO https://github.com/etcd-io/etcd/releases/download/v3.4.3/etcd-v3.4.3-linux-amd64.tar.gz
100 16.4M  100 16.4M    0     0   472k      0  0:00:35  0:00:35 --:--:--  737k
+ gzip -d etcd-v3.4.3-linux-amd64.tar.gz
gzip: etcd-v3.4.3-linux-amd64.tar already exists;	not overwritten
Failed to run 'override-build': Exit code was 2.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
```

Attached the entire log for the full picture. Please advise if I must use the `--debug` switch as well. 

[microk8s-error.log](https://github.com/ubuntu/microk8s/files/4839949/microk8s-error.log)

**Comment by siddharths2710** [comment]
I also want to mention that I had previously built from snapcraft successfully and I uninstalled the package using `snap remove`. Could this be propogating the issue by any chance?

**Comment by balchua** [comment]
I get this too occasionally.  I tend to do `snapcraft clean microk8s`.  After that i can do `snapcraft --use-lxd`.  
Not so long ago i made a pr to clean the kubernetes build which is throwing me some error when rebuilding.

**Comment by siddharths2710** [comment]
That works! Thank you for the reply. Hope the pr goes through :)
