### ISSUE TITLE
MicroK8s using large amount disk

### ISSUE THREAD

**Issue by EnziinSystem** [ubuntu/microk8s#1363]
In 1 day only, microk8s using increment from 22GB to 35GB in ` /var/snap/microk8s/common` 

```
$ cd /var/snap/microk8s/common
$ sudo du -hsx * | sort -rh | head -10
35G	var
3.8M	run
8.0K	default-storage
```
My application is simple.
I don't know why, please help me.
Thanks.

**Comment by ktsakalozos** [comment]
Hi @EnziinSystem. The docker images are stored under that directory. You can read more on how and when the unused images are garbage collected in [1]. To configure kubelet to match the behavior you desire you will need to edit `/var/snap/microk8s/current/args/kubelet` and restart MicroK8s with `microk8s stop; microk8s start`.

[1] https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
