### ISSUE TITLE
use hostname for kubelet for worker nodes in multinode setup

### ISSUE THREAD

**Issue by sean-abbott** [ubuntu/microk8s#1364]
I've given all my worker nodes hostnames, but when I run `kubectl get nodes`, the kubelet config shows the IP. The server shows the hostname.

```
$ kubectl get nodes
NAME             STATUS   ROLES    AGE   VERSION
10.10.1.2  Ready    <none>   12d   v1.18.4-1+629a74c268c116
10.10.1.3    Ready    <none>   17m   v1.18.4-1+6f17be3f1fd54a
10.10.1.4   Ready    <none>   12d   v1.18.4-1+629a74c268c116
10.10.1.5    Ready    <none>   11d   v1.18.4-1+629a74c268c116
piserver       Ready    <none>   12d   v1.18.4-1+629a74c268c116
```
if possible, it'd be nicer if it showed the hostname. Or was configurable via the `add node` or `join` commands.

**Comment by ktsakalozos** [comment]
Are all hostnames resolvable on all nodes?

**Comment by sean-abbott** [comment]
Ah, fair enough, I thought it was a sugary "name", not "resolvable name".
