### ISSUE TITLE
Unable to login into KubeFlow after the addon is enabled

### ISSUE THREAD

**Issue by tomalbrecht** [ubuntu/microk8s#1366]
When I install microk8s on a workstation an enabling kubernetes, I am not able to open the kubeflow dashboard remotely. I found several other issues and solutions for this, but none of them worked (attached/linked). Does anyone have a working configuration, so I am able to remotely use Kubeflow on this workstation?

https://github.com/ubuntu/microk8s/issues/817
https://stackoverflow.com/questions/60973804/microk8s-broken-k8s-dashboard-and-kubeflow-dashboard

Network Setup:
- lenovo-lan: beefy machine with enough RAM and GPU to run kubernetes and kubeflow. Installing microk8s and kubeflow via ssh 
- mac: should be able to connect to lenovo-lan via chrome http://lenovo-lan:80
- DNS is able to resolve lenovo-lan to 192.168.178.53

Workstation (lenovo-lan) Setup:
- ubuntu 18.04
- microk8s v1.18.4
- remote login via ssh lenovo-lan does work
- local dashboard does work (10.64.140.43.xip.io)

Workstation microk8s setup Routine:
```bash
ssh tal@lenovo-lan
# now on remote host
sudo -i
snap install microk8s --classic
microk8s.status --wait-ready
microk8s.enable dns dashboard storage gpu
KUBEFLOW_HOSTNAME=lenovo-lan microk8s.enable kubeflow
# Enabling dns...
# Enabling storage...
# Enabling dashboard...
# Enabling ingress...
# Enabling metallb:10.64.140.43-10.64.140.49...
# Waiting for DNS and storage plugins to finish setting up
# Deploying Kubeflow...
```

* kubeflow is now deployed
* all pods and services are up and running
* opening http://10.64.140.43.xip.io (locally on lenovo-lan) does work

Local curls on http://lenovo-lan not working **(Error 403)**
```bash
ssh tal@lenovo-lan
curl -vk https://lenovo-lan
> 403 forbidden
curl -v http://lenovo-lan
> 403 forbidden
curl -v http://10.64.140.43.xip.io:80
> 403 forbidden
```

When I try to open the ambassador from my 2nd machine (imac->lenovo-lan) via chrome:
* http://10.64.140.43.xip.io/  --> won't come back
* http://lenovo-lan:80/ --> 403 forbidden
* https://lenovo-lan/ --> 403 forbidden
```shell
# pinging from mac -> lenovo-lan
ping lenovo-lan
> 64 bytes from 192.168.178.53: icmp_seq=1 ttl=64 time=0.386 ms

# pinging from lenovo-lan -> lenovo-lan
ping lenovo-lan
> 64 bytes from lenovo.fritz.box (192.168.178.53): icmp_seq=2 ttl=64 time=0.052 ms

```

Any help?

[inspection-report-20200702_162838.tar.gz](https://github.com/ubuntu/microk8s/files/4864938/inspection-report-20200702_162838.tar.gz)

**Comment by tomalbrecht** [comment]
When following this solution: 

```bash
sudo microk8s juju config dex-auth public-url=http://lenovo.local
sudo microk8s juju config oidc-gatekeeper public-url=http://lenovo.local
sudo microk8s juju config ambassador juju-external-hostname=http://lenovo.local
```

and restarting microk8s
```bash
microk8s.stop
microk8s.start
```

"connection refused" errors accessing http://lenovo.local (Ports :80 and :31362)

**Comment by tomalbrecht** [comment]
Checked Workstation hostname: `lenovo` and reinstalled kubeflow (disable/enable).

```bash
sudo snap remove microk8s
sudo snap install microk8s --classic
microk8s.status --wait-ready
# Enable common services:
microk8s.enable dns dashboard storage gpu


KUBEFLOW_HOSTNAME=lenovo microk8s.enable kubeflow

[...]

Operator pods ready.
Waiting for service pods to become ready.

Congratulations, Kubeflow is now available.
The dashboard is available at http://lenovo/

    Username: admin
```

Same result. Accessing http://lenovo/ results in 403 not authorized.

**Comment by tomalbrecht** [comment]
Accessing the k8 dashboard does work, though:

` microk8s dashboard-proxy`

accessing via https://lenovo:10443

**Comment by tomalbrecht** [comment]
`kubectl describe -n kube-system pod/coredns-588fd544bf-xs5tp` looks ok to me?

```shell
Events:
  Type    Reason          Age   From               Message
  ----    ------          ----  ----               -------
  Normal  Scheduled       45m   default-scheduler  Successfully assigned kube-system/coredns-588fd544bf-xs5tp to lenovo
  Normal  Pulling         45m   kubelet, lenovo    Pulling image "coredns/coredns:1.6.6"
  Normal  SandboxChanged  44m   kubelet, lenovo    Pod sandbox changed, it will be killed and re-created.
  Normal  Pulling         44m   kubelet, lenovo    Pulling image "coredns/coredns:1.6.6"
  Normal  Pulled          44m   kubelet, lenovo    Successfully pulled image "coredns/coredns:1.6.6"
  Normal  Created         44m   kubelet, lenovo    Created container coredns
  Normal  Started         44m   kubelet, lenovo    Started container coredns
```

**Comment by tomalbrecht** [comment]
Testing juju setup:

```shell
sudo microk8s juju config dex-auth public-url=http://192.168.178.53.xip.io
sudo microk8s juju config oidc-gatekeeper public-url=http://192.168.178.53.xip.io
sudo microk8s juju config ambassador juju-external-hostname=192.168.178.53.xip.io
```

Did not work. `http://192.168.178.53.xip.io` not reachable locally nor remotely. 

Rolled back:
```shell
sudo microk8s juju config dex-auth public-url=http://10.64.140.43.xip.io
sudo microk8s juju config oidc-gatekeeper public-url=http://10.64.140.43.xip.io
sudo microk8s juju config ambassador juju-external-hostname=10.64.140.43.xip.io
```

**Comment by tomalbrecht** [comment]
Testing solution from [Nvidia](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9515-up-and-running-with-kubeflow-anywhere.pdf) on microk8s setup:

```shell
sudo microk8s.juju config ambassador juju-external-hostname=192.168.178.53.xip.io
sudo microk8s.juju expose ambassador
```

**Comment by tomalbrecht** [comment]
Installation as described [at bundle-kubeflow](https://github.com/juju-solutions/bundle-kubeflow), results in the same error 404. Manually deploying kubeflow (as described at kubeflow.org) and patching the LoadBalancer manually, does work, though.



Anyone any idea how to connect remotely when using microk8s.enable?

**Comment by knkski** [comment]
@tomalbrecht: The easiest way is to use SSH port forwarding, as detailed in this comment:

https://github.com/ubuntu/microk8s/issues/1243#issuecomment-635429958

Specifically, you'll want to run `ssh -D9999 tal@lenovo-lan`, and then configure Firefox to use a SOCKS5 proxy at port 9999, as show here:

https://github.com/ubuntu/microk8s/issues/1243#issuecomment-647137827

Then, you can go to http://10.64.140.43.xip.io/ in Firefox and log in as normal.

If you'd like, you can also set the `KUBEFLOW_HOSTNAME` environment variable to have Kubeflow available over a regular network connection, though this is slightly more involved. Here are the steps:

 - Run `KUBEFLOW_HOSTNAME=lenovo-lan microk8s.enable kubeflow`
 - Run `microk8s.kubectl edit configmap -n kube-system coredns` and edit the line that says `forward . 8.8.8.8 8.8.4.4` to read `forward . X.X.X.X`, where X.X.X.X is a local DNS resolver that is aware of `lenovo-lan`. For example, I use `192.168.1.1`, as that's the URL of my local router.

**Comment by tomalbrecht** [comment]
@knkski: Thank a lot you for your help. I did miss the point, that I have to setup a DNS resolver. I set it to my router and configured cordns correctly. Now I am able to open the kubeflow dashboard on my remote computer.

**Comment by tomalbrecht** [comment]
Asked the kubeflow team, to update their configuration.
