### ISSUE TITLE
NVIDIA GPU

### ISSUE THREAD

**Issue by vinhdiesal** [ubuntu/microk8s#1370]
I'm trying to create a `dask-cuda-worker` and asked different communities which concluded I should ask the microk8s community regarding enabling the GPU. 

I have tried two methods of enabling GPUS, but the helm charts are having issues detecting the GPUs.

First method: 

After I join all the nodes, On the master, I perform a `microk8s enable gpus`.

Alternative Methods: 
I performed the instructions of installing the nvidia-k8 plugs through helm. 
This requires the `Docker` with `NVIDIA container tool kit`. 
I install the NVIDIA helm chart as follows: 
```
microk8s helm3 repo add nvdp https://nvidia.github.io/k8s-device-plugin
microk8s helm3 repo update
microk8s helm3 install \
    --version=0.6.0 \
    --generate-name \
    nvdp/nvidia-device-plugin
```
The helm chart I'm trying to install with GPUs is at the following: [RAPIDS AI HELM CHART](https://github.com/rapidsai/helm-chart)
Can you install in microk8s environment and see if you can get it to work?

**Comment by joedborg** [comment]
Hi @vinhdiesal,

I've installed MicroK8s 1.18/stable on a GPU host.  `microk8s enable gpu` gives me the device plugin, as expected:

```
$ sudo microk8s kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-588fd544bf-hxs2g               1/1     Running   0          113s
kube-system   pod/nvidia-device-plugin-daemonset-9hbm8   1/1     Running   0          108s

NAMESPACE     NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP                  2m6s
kube-system   service/kube-dns     ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   113s

NAMESPACE     NAME                                            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/nvidia-device-plugin-daemonset   1         1         1       1            1           <none>          108s

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   1/1     1            1           113s

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-588fd544bf   1         1         1       113s

```

What issue are you seeing from there?

**Comment by vinhdiesal** [comment]
Hi @joedborg , 

I don't have issues enabling GPU on the nodes, but when I install the helm chart, it doesn't recognize any nvidia nodes so the pods doesn't start. 
I've asked the dask team, but they referred me to ask here because they think it's an issue with microk8s. 
Here is the Helm chart, [RAPIDS AI HELM CHART](https://github.com/rapidsai/helm-chart), can you install it can see if you can get the dask cuda workers to run?

**Comment by joedborg** [comment]
Hi @vinhdiesal,

I've quickly tried using the AI helm chart, with both MicroK8s enable GPU and Nvidia helm chart; neither bring the RAPIDS AI pods up.  If I have time later today,  I'll try on a baremetal K8s cluster, but this seems to be an issue with their chart.

Thanks,
Joe

**Comment by vinhdiesal** [comment]
Hi @joedborg, thanks for looking into this and please let me know what you find out. I really hope the helm chart works with microk8s.

**Comment by joedborg** [comment]
Yep @vinhdiesal, this chart doesn't work on bare metal K8s either, so you'll have to go back to the chart author I'm afraid.

```
NAMESPACE                         NAME                                                          READY   STATUS         RESTARTS   AGE
ingress-nginx-kubernetes-worker   pod/default-http-backend-kubernetes-worker-7f969db96f-4lc95   1/1     Running        0          4h30m
ingress-nginx-kubernetes-worker   pod/nginx-ingress-controller-kubernetes-worker-k4v88          1/1     Running        0          4h30m
kube-system                       pod/coredns-6b59b8bd9f-zx7wp                                  1/1     Running        0          4h30m
kube-system                       pod/kube-state-metrics-69f474f8cb-4m7qs                       1/1     Running        0          4h30m
kube-system                       pod/metrics-server-v0.3.6-74c87686d-q99qq                     2/2     Running        0          4h30m
kube-system                       pod/nvidia-device-plugin-daemonset-4hwcp                      1/1     Running        0          4h29m
kube-system                       pod/tiller-deploy-fc55974f-67qz6                              1/1     Running        0          3m51s
kubernetes-dashboard              pod/dashboard-metrics-scraper-78d587b6b-sw994                 1/1     Running        0          4h30m
kubernetes-dashboard              pod/kubernetes-dashboard-7b76878768-dh9kt                     1/1     Running        0          4h30m
mynamespace                       pod/rapidsai-jupyter-76fc4b96bb-dg7tm                         0/1     Pending        0          60s
mynamespace                       pod/rapidsai-scheduler-7675655dc6-9qxtq                       0/1     ErrImagePull   0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-6jmlt                          0/1     Evicted        0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-fjks2                          0/1     Pending        0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-lngll                          0/1     Pending        0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-x4ggc                          0/1     Pending        0          20s
```

**Comment by vinhdiesal** [comment]
can you run kubectl describe pod on the following? 
The RAPIDS AI team are asking for the data.

mynamespace                       pod/rapidsai-scheduler-7675655dc6-9qxtq                       0/1     ErrImagePull   0          60s
mynamespace                       pod/rapidsai-worker-77c9d9d8cb-6jmlt                          0/1     Evicted        0          60s
