### ISSUE TITLE
etcd can not start on fresh installation on archlinux

### ISSUE THREAD

**Issue by bench** [ubuntu/microk8s#1385]
On my archlinux installation, etcd snap service cannot start because of

```
1.0.0.1:53: connect: network is unreachable
```

Please run `microk8s inspect` and attach the generated tarball to this issue.

❯ microk8s inspect

Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
 FAIL:  Service snap.microk8s.daemon-etcd is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-etcd
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1496/inspection-report-20200706_151709.tar.gz

**Comment by bench** [comment]
[inspection-report-20200706_151709.tar.gz](https://github.com/ubuntu/microk8s/files/4879415/inspection-report-20200706_151709.tar.gz)

here is the tarball

**Comment by bench** [comment]
seems that 1.0.0.1 is cloudfare secondary DNS resolver. Is there something specific to configure so that snap services can access the this resolver ?

**Comment by johnlane** [comment]
Hey, I just opened a similar issue. Just wondring whether 1.0.0.1 is what you have configured in `/etc/resolv.conf` ? I'm having exactly the same symptom except with `127.0.0.1:53` which matches what I have in mine. I still don't know how to fix it though!

**Comment by bench** [comment]
hey @johnlane, happy to read that I am not alone in that case. Indeed this maches my `/etc/resolv.conf`. But I still have no ideas atm.

**Comment by bench** [comment]
OK, I found a solution thanks to https://github.com/ubuntu/microk8s/issues/1394 and @johnlane.
I had no `locahost` into my `/etc/hosts`.
Works now :+1:
