### ISSUE TITLE
Cert-Manager (v0.15.1) Certificate generate error

### ISSUE THREAD

**Issue by babvin** [ubuntu/microk8s#1390]
kubectl apply -f cert.yaml 
namespace/cert-manager-test unchanged
Error from server (InternalError): error when creating "cert.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s": x509: certificate is valid for k8s-pi-master, not cert-manager-webhook.cert-manager.svc
Error from server (InternalError): error when creating "cert.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s": x509: certificate is valid for k8s-pi-master, not cert-manager-webhook.cert-manager.svc

vinay@pramukha:~$ cat cert.yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  commonName: example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
vinay@pramukha:~$ 

ubuntu@k8s-pi-master:/storage$ cat <<EOF | kubectl apply -f -
> apiVersion: cert-manager.io/v1alpha2
> kind: ClusterIssuer
> metadata:
>   name: letsencrypt-staging
> spec:
>   acme:
>     email: vinay.umesh@gmail.com
>     server: https://acme-staging-v02.api.letsencrypt.org/directory
>     privateKeySecretRef:
>       name: letsencrypt-staging
>     solvers:
>     - http01:
>         ingress:
>           class: nginx
> EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.kube-system.svc:443/mutate?timeout=30s": x509: certificate is valid for k8s-pi-master, not cert-manager-webhook.kube-system.svc
[inspection-report-20200707_162032.tar.gz](https://github.com/ubuntu/microk8s/files/4886048/inspection-report-20200707_162032.tar.gz)

**Comment by balchua** [comment]
Its strange i dont see the cert managers pod running.

**Comment by babvin** [comment]
ubuntu@k8s-pi-master:~$ kubectl get pods -A
NAMESPACE            NAME                                        READY   STATUS             RESTARTS   AGE
container-registry   registry-5d5b754549-m8zl6                   1/1     Running            2          33h
default              echo1-bfb568c8b-7fchh                       0/1     CrashLoopBackOff   287        24h
default              echo1-bfb568c8b-phc29                       0/1     CrashLoopBackOff   287        24h
default              echo2-5f44d9d965-hznqh                      0/1     ImagePullBackOff   0          24h
default              nginx-deployment-6b474476c4-5sm7t           1/1     Running            1          23h
default              nginx-deployment-6b474476c4-btzdq           1/1     Running            1          23h
ingress              nginx-ingress-microk8s-controller-247ws     1/1     Running            6          33h
ingress              nginx-ingress-microk8s-controller-8gzgf     1/1     Running            1          26h
ingress              nginx-ingress-microk8s-controller-qwtxr     1/1     Running            1          28h
kube-system          cert-manager-7747db9d88-7gjvf               1/1     Running            1          11m
kube-system          cert-manager-cainjector-87c85c6ff-pm8xf     1/1     Running            3          11m
kube-system          cert-manager-webhook-55fcfdfd7c-9gnc6       1/1     Running            1          11m
kube-system          coredns-588fd544bf-9nmds                    1/1     Running            2          33h
kube-system          dashboard-metrics-scraper-59f5574d4-wcrll   1/1     Running            1          24h
kube-system          hostpath-provisioner-9b7695c6b-x5p27        1/1     Running            2          33h
kube-system          kubernetes-dashboard-6d97855997-tmqmf       1/1     Running            1          24h
kube-system          metrics-server-79749d858b-bhzl6             1/1     Running            2          33h
kube-verify          kube-verify-5f976b5474-4vz5s                1/1     Running            2          33h
kube-verify          kube-verify-5f976b5474-7fg52                1/1     Running            2          33h
kube-verify          kube-verify-5f976b5474-tjl5v                1/1     Running            2          33h
kube-verify1         kube-verify-5f976b5474-6t7pv                1/1     Running            1          28h
kube-verify1         kube-verify-5f976b5474-7blz8                1/1     Running            1          28h
kube-verify1         kube-verify-5f976b5474-mprc4                1/1     Running            1          28h
metallb-system       controller-5f98465b6b-gd82s                 1/1     Running            2          33h
metallb-system       speaker-6gs2w                               1/1     Running            1          28h
metallb-system       speaker-cml76                               1/1     Running            1          26h
metallb-system       speaker-ncs2p                               1/1     Running            2          33h
monitoring           alertmanager-main-0                         2/2     Running            4          33h
monitoring           arm-exporter-522xf                          2/2     Running            2          26h
monitoring           arm-exporter-mcw44                          2/2     Running            4          33h
monitoring           arm-exporter-ptshf                          2/2     Running            2          28h
monitoring           grafana-676bcb5687-d6hl2                    1/1     Running            1          31h
monitoring           kube-state-metrics-96bf99844-6tlrq          3/3     Running            6          33h
monitoring           node-exporter-9gkhm                         2/2     Running            4          33h
monitoring           node-exporter-cjjgs                         2/2     Running            2          28h
monitoring           node-exporter-hbg8s                         2/2     Running            2          26h
monitoring           prometheus-adapter-f78c4f4ff-zvcr7          1/1     Running            2          33h
monitoring           prometheus-k8s-0                            3/3     Running            4          31h
monitoring           prometheus-operator-6b8868d698-pt9rw        2/2     Running            4          33h
monitoring           smtp-server-5c7c8d77f8-q592k                1/1     Running            2          33h
nextcloud            nextcloud-857cd47bdf-xrnm4                  1/1     Running            1          24h
ubuntu@k8s-pi-master:~$ cat <<EOF | kubectl apply -f -
> apiVersion: cert-manager.io/v1alpha2
> kind: ClusterIssuer
> metadata:
>   name: letsencrypt-staging
> spec:
>   acme:
>     email: vinay.umesh@gmail.com
>     server: https://acme-staging-v02.api.letsencrypt.org/directory
>     privateKeySecretRef:
>       name: letsencrypt-staging
>     solvers:
>     - http01:
>         ingress:
>           class: nginx
> EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.kube-system.svc:443/mutate?timeout=30s": x509: certificate is valid for k8s-pi-master, not cert-manager-webhook.kube-system.svc
ubuntu@k8s-pi-master:~$ cat <<EOF | kubectl apply -f -
> apiVersion: cert-manager.io/v1alpha2
> kind: ClusterIssuer
> metadata:
>   name: letsencrypt-prod
> spec:
>   acme:
>     email: vinay.umesh@gmail.com
>     server: https://acme-v02.api.letsencrypt.org/directory
>     privateKeySecretRef:
>       name: letsencrypt-prod
>     solvers:
>     - http01:
>         ingress:
>           class: nginx
> EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.kube-system.svc:443/mutate?timeout=30s": x509: certificate is valid for k8s-pi-master, not cert-manager-webhook.kube-system.svc
ubuntu@k8s-pi-master:~$
[inspection-report-20200708_154023.tar.gz](https://github.com/ubuntu/microk8s/files/4891725/inspection-report-20200708_154023.tar.gz)

**Comment by babvin** [comment]
Please find the latest inspect report tarball @balchua - Thank you for the respnse and kindly look into this

**Comment by balchua** [comment]
Im totally unfamiliar with cert-manager, but google led me to this. https://github.com/jetstack/cert-manager/issues/2752#issuecomment-605883456
It seems to suggest using `cert-manager` namespace , instead of another can lead to better result.

**Comment by babvin** [comment]
vinay@pramukha:~$ kubectl get namespace
NAME                 STATUS   AGE
cert-manager         Active   9h
cert-manager-test    Active   2d1h
container-registry   Active   2d10h
default              Active   2d10h
ingress              Active   2d10h
kube-node-lease      Active   2d10h
kube-public          Active   2d10h
kube-system          Active   2d10h
kube-verify          Active   2d10h
kube-verify1         Active   2d5h
metallb-system       Active   2d10h
monitoring           Active   2d10h
nextcloud            Active   2d1h
vinay@pramukha:~$

vinay@pramukha:~$ kubectl get pods -A
NAMESPACE            NAME                                        READY   STATUS             RESTARTS   AGE
cert-manager         cert-manager-66bbb47c56-lh229               1/1     Running            0          9h
cert-manager         cert-manager-cainjector-5579468649-8jwvg    1/1     Running            0          9h
cert-manager         cert-manager-webhook-746cf468-xzb24         1/1     Running            0          9h
container-registry   registry-5d5b754549-m8zl6                   1/1     Running            2          2d10h
default              echo1-bfb568c8b-7fchh                       0/1     CrashLoopBackOff   575        2d
default              echo1-bfb568c8b-phc29                       0/1     CrashLoopBackOff   575        2d
default              echo2-5f44d9d965-hznqh                      0/1     ImagePullBackOff   0          2d
default              microbot-65bc8bdd7c-sgrd6                   1/1     Running            0          8h
default              microbot-65bc8bdd7c-zzdqt                   1/1     Running            0          8h
default              nginx-deployment-6b474476c4-5sm7t           1/1     Running            1          2d
default              nginx-deployment-6b474476c4-btzdq           1/1     Running            1          2d
ingress              nginx-ingress-microk8s-controller-247ws     1/1     Running            6          2d10h
ingress              nginx-ingress-microk8s-controller-8gzgf     1/1     Running            1          2d3h
ingress              nginx-ingress-microk8s-controller-qwtxr     1/1     Running            1          2d5h
kube-system          coredns-588fd544bf-9nmds                    1/1     Running            2          2d10h
kube-system          dashboard-metrics-scraper-59f5574d4-wcrll   1/1     Running            1          2d1h
kube-system          hostpath-provisioner-9b7695c6b-x5p27        1/1     Running            2          2d10h
kube-system          kubernetes-dashboard-6d97855997-tmqmf       1/1     Running            1          2d1h
kube-system          metrics-server-79749d858b-bhzl6             1/1     Running            2          2d10h
kube-verify          kube-verify-5f976b5474-4vz5s                1/1     Running            2          2d10h
kube-verify          kube-verify-5f976b5474-7fg52                1/1     Running            2          2d10h
kube-verify          kube-verify-5f976b5474-tjl5v                1/1     Running            2          2d10h
kube-verify1         kube-verify-5f976b5474-6t7pv                1/1     Running            1          2d5h
kube-verify1         kube-verify-5f976b5474-7blz8                1/1     Running            1          2d5h
kube-verify1         kube-verify-5f976b5474-mprc4                1/1     Running            1          2d5h
metallb-system       controller-5f98465b6b-gd82s                 1/1     Running            2          2d10h
metallb-system       speaker-6gs2w                               1/1     Running            1          2d5h
metallb-system       speaker-cml76                               1/1     Running            1          2d3h
metallb-system       speaker-ncs2p                               1/1     Running            2          2d10h
monitoring           alertmanager-main-0                         2/2     Running            4          2d10h
monitoring           arm-exporter-522xf                          2/2     Running            2          2d3h
monitoring           arm-exporter-mcw44                          2/2     Running            4          2d10h
monitoring           arm-exporter-ptshf                          2/2     Running            2          2d5h
monitoring           grafana-676bcb5687-d6hl2                    1/1     Running            1          2d7h
monitoring           kube-state-metrics-96bf99844-6tlrq          3/3     Running            6          2d10h
monitoring           node-exporter-9gkhm                         2/2     Running            4          2d10h
monitoring           node-exporter-cjjgs                         2/2     Running            2          2d5h
monitoring           node-exporter-hbg8s                         2/2     Running            2          2d3h
monitoring           prometheus-adapter-f78c4f4ff-zvcr7          1/1     Running            2          2d10h
monitoring           prometheus-k8s-0                            3/3     Running            4          2d7h
monitoring           prometheus-operator-6b8868d698-pt9rw        2/2     Running            4          2d10h
monitoring           smtp-server-5c7c8d77f8-q592k                1/1     Running            2          2d10h
nextcloud            nextcloud-857cd47bdf-xrnm4                  0/1     Running            2          2d1h

vinay@pramukha:~$ cat <<EOF | kubectl apply -f -
> apiVersion: cert-manager.io/v1alpha2
> kind: ClusterIssuer
> metadata:
>   name: letsencrypt-staging
> spec:
>   acme:
>     email: vinay.umesh@gmail.com
>     server: https://acme-staging-v02.api.letsencrypt.org/directory
>     privateKeySecretRef:
>       name: letsencrypt-staging
>     solvers:
>     - http01:
>         ingress:
>           class: nginx
> EOF
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s": x509: certificate is valid for k8s-pi-master, not cert-manager-webhook.cert-manager.svc
vinay@pramukha:~$

Issue still persists even after with dedicated namespace "cert-manager"

**Comment by balchua** [comment]
What does it look like when you do this?
`kubectl get certificate -o wide --namespace cert-manager`.
If you don't mind, can you use markdown code formatting? It is difficult to read them when its not in markdown code format.
Thanks.

**Comment by babvin** [comment]
`ubuntu@k8s-pi-master:~$ kubectl get namespace
NAME                 STATUS   AGE
cert-manager         Active   18h
cert-manager-test    Active   2d10h
container-registry   Active   2d19h
default              Active   2d20h
ingress              Active   2d19h
kube-node-lease      Active   2d20h
kube-public          Active   2d20h
kube-system          Active   2d20h
kube-verify          Active   2d19h
kube-verify1         Active   2d15h
metallb-system       Active   2d19h
monitoring           Active   2d19h
nextcloud            Active   2d11h

> ubuntu@k8s-pi-master:~$ kubectl get certificate -o wide --namespace cert-manager

> No resources found in cert-manager namespace.


> ubuntu@k8s-pi-master:~$ kubectl get certificate -o wide --namespace kube-system

> No resources found in kube-system namespace.

> ubuntu@k8s-pi-master:~$ kubectl get certificate -o wide -A

> No resources found

ubuntu@k8s-pi-master:~$

`
There are no certificates in cert-manager and all other namespaces.

**Comment by balchua** [comment]
That could be the reason why the apiserver couldn't talk to the cert manager webhook.
I think its best to check with the cert-manager project team.
