### ISSUE TITLE
unable to start microk8s etcd fails with lookup localhost on 127.0.0.1:53: no such host

### ISSUE THREAD

**Issue by johnlane** [ubuntu/microk8s#1394]
I am unable to start microk8s. I can see that `etcd` fails with an error about 
```
listen tcp: lookup localhost on 127.0.0.1:53: no such host
```
I use arch linux with zfs and I have made the [suggested changes](https://microk8s.io/docs/install-alternatives), although `containerd-template.toml` was slightly different for me, I had to replace `snapshotter = "${SNAPSHOTTER}"` with `snapshotter = "zfs"`. It feels like this isn't related however thought worth mentioning.

Please run `microk8s inspect` and attach the generated tarball to this issue. [done](https://github.com/ubuntu/microk8s/files/4895602/inspection-report-20200709_093357.tar.gz)

**Comment by balchua** [comment]
Can you check if `localhost` exist in `/etc/hosts` file?

**Comment by johnlane** [comment]
@balchua thank you that was the problem. After putting that in, everything just worked :)
Don't know why it wasn't there - usually is.
