### ISSUE TITLE
Enable gpu metrics in Prometheus with gpu plugin

### ISSUE THREAD

**Issue by grebennikov** [ubuntu/microk8s#1395]
With gpu plugin activated it'd be great to expose gpu metrics in grafana via prometheus as well.
This requires to run a daemonset of gpu exporter with this spec:

> apiVersion: apps/v1
> kind: DaemonSet
> metadata:
>   name: pod-gpu-metrics-exporter
>   namespace: monitoring
> spec:
>   selector:
>     matchLabels:
>       app: pod-gpu-metrics-exporter
>   template:
>     metadata:
>       labels:
>         app: pod-gpu-metrics-exporter
>       name: pod-gpu-metrics-exporter
>     spec:
>       nodeSelector:
>         hardware-type: NVIDIAGPU
>       containers:
>       - image: nvidia/pod-gpu-metrics-exporter:v1.0.0-alpha
>         name: pod-nvidia-gpu-metrics-exporter
>         ports:
>         - name: metrics
>           containerPort: 9400
>           hostPort: 9400
>         securityContext:
>           runAsNonRoot: false
>           runAsUser: 0
>         volumeMounts:
>         - name: pod-gpu-resources
>           readOnly: true
>           mountPath: /var/lib/kubelet/pod-resources
>         - name: device-metrics
>           readOnly: true
>           mountPath: /run/prometheus
>       - image: nvidia/dcgm-exporter:1.4.6
>         name: nvidia-dcgm-exporter
>         securityContext:
>           runAsNonRoot: false
>           runAsUser: 0
>         volumeMounts:
>         - name: device-metrics
>           mountPath: /run/prometheus
>       volumes:
>       - name: pod-gpu-resources
>         hostPath:
>           path: /var/snap/microk8s/common/var/lib/kubelet/pod-resources
>       - name: device-metrics
>         emptyDir:
>           medium: Memory
> 

And also to update Prometheus' configmap with the following pattern:

>   prometheus.yml: |-
>     global:
>       scrape_interval:     15s 
>       evaluation_interval: 15s
>     scrape_configs:
>     - job_name: pod-gpu
>       metrics_path: /gpu/metrics
>       scheme: http
>       static_configs:
>       - targets:
>         - <gpu node address>:9400

**Comment by ktsakalozos** [comment]
We could introduce a flag in [1] eg, `microk8s enable gpu:report-metrics=true` with which the user could state his intentions.

If that flag is enabled we would enable the prometheus addon and apply the suggested config map.

Would that work @grebennikov ?

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.gpu.sh
