### ISSUE TITLE
Microk8s snap doesn't consume environment variables properly

### ISSUE THREAD

**Issue by grebennikov** [ubuntu/microk8s#1399]
Trying to store snap's data in non-default location using env variables.

(from inside the snap)
[root@bm1-microk8s-ha ~]# env|grep home
SNAP_COMMON=/home
SNAP_DATA=/home
However containerd is running using default /var/snap location:

247907 ?        Ssl    3:15 /snap/microk8s/1533/bin/containerd --config /var/snap/microk8s/1533/args/containerd.toml --root /var/snap/microk8s/common/var/lib/containerd --state /var/snap/microk8s/common/run/containerd --address /var/snap/microk8s/common/run/containerd.sock

[root@bm1-microk8s-ha ~]# cat /var/snap/microk8s/current/args/containerd
--config ${SNAP_DATA}/args/containerd.toml
--root ${SNAP_COMMON}/var/lib/containerd
--state ${SNAP_COMMON}/run/containerd
--address ${SNAP_COMMON}/run/containerd.sock

**Comment by balchua** [comment]
I don't think changing the environment variable like that affects snap.
If the intention is to have `/var/snap` use a different file system, simply mount `/var/snap` to `/home`

If i recall it looks something like this.
`mount --bind /var/snap /home/var/snap`

And to survive restart, need to add to `/etc/fstab`
