### ISSUE TITLE
Microk8s doesn't populate all IP addresses into the template

### ISSUE THREAD

**Issue by grebennikov** [ubuntu/microk8s#1400]
the certificate is supposed to be created using all current IP adresses of the machine.
On the laptop:

agrebennikov@andreygX1:~$ ip a|grep -B2 192
2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 54:e1:ad:67:8b:73 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.172/24 brd 192.168.1.255 scope global dynamic noprefixroute enp0s31f6

3: wlp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ac:ed:5c:db:39:81 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.3/24 brd 192.168.1.255 scope global dynamic noprefixroute wlp4s0

Though in the template:
agrebennikov@andreygX1:~$ cat /var/snap/microk8s/current/certs/csr.conf.template|grep -A8 ' alt_names'
[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
IP.1 = 127.0.0.1
IP.2 = 10.152.183.1
#MOREIPS

**Comment by balchua** [comment]
@grebennikov can you check the generated `csr.conf` instead of the `csr.conf.template`?.

`var/snap/microk8s/current/certs/csr.conf | grep -A8 ' alt_names'`

**Comment by ktsakalozos** [comment]
@grebennikov, please follow @balchua's suggestion. MicroK8s replaces the `#MOREIPS` part of `csr.conf.template` with any IPs it finds and then produces the `csr.conf ` file. The `csr.conf` is the file that will be used in issuing certificates.

**Comment by grebennikov** [comment]
@balchua yes, the csr.conf does contain app IPs of the node.
Does it mean that currently used cert should be fine then? Is there a way to retrieve current cert itself? Or it is recommended to just probe it via openssl client?

**Comment by balchua** [comment]
> Does it mean that currently used cert should be fine then?
Yes it should be included in the certificate.

>  Is there a way to retrieve current cert itself?

All certs will be in `/var/snap/microk8s/current/credentials`
