### ISSUE TITLE
microk8s.inspect should generate a zip, not tar.gz

### ISSUE THREAD

**Issue by davigar15** [ubuntu/microk8s#1409]
Github doesn't support tar.gz files, so it would be nice to generate a .zip with `microk8s.inspect`. That way we don't have to extract it and compress it with again :P

EDIT: uploading a tar.gz in the issue description.
[inspection-report-20200716_114554.tar.gz](https://github.com/ubuntu/microk8s/files/4930434/inspection-report-20200716_114554.tar.gz)

**Comment by ktsakalozos** [comment]
Test of attaching a tar.gz in a reply.
[inspection-report-20200716_114554.tar.gz](https://github.com/ubuntu/microk8s/files/4930401/inspection-report-20200716_114554.tar.gz)

**Comment by ktsakalozos** [comment]
I cannot confirm this bug @davigar15 can you describe in more detail what is failing?

**Comment by davigar15** [comment]
Create a new bug, and drag and drop the .tar.gz into the bug description. In my case, it is getting stuck and it says that the format is not supported.

**Comment by ktsakalozos** [comment]
What browser are you using?

![upload](https://user-images.githubusercontent.com/11489452/88047862-f53afb80-cb5a-11ea-8b2d-7ab6b2994b2b.png)
