### ISSUE TITLE
Support user supplied CA cert and key

### ISSUE THREAD

**Issue by balbirthomas** [ubuntu/microk8s#1410]
Use Case
-------------
During installation of microk8s a CA cert and key is autogenerated. However at present the `microk8s-refersh-certs.wrapper` script does not support using a CA cert and key supplied by the user. This is a useful feature to have. 

Interface
------------
It is proposed that new command line options (`-r` and `--refresh`) be added to the `microk8s-refresh-certs.wrapper` script. This argument will have a mandatory argument that provides the path to a directory, where two files `ca.cert` and `ca.key` are present. if these files are present they will replace the existing CA cert and key

**Comment by balbirthomas** [comment]
Created a [pull request](https://github.com/ubuntu/microk8s/pull/1423) for this issue. A restart of the host system (for instance virtualbox machine) is required after updating CA certificates. I would be grateful for any feedback.

**Comment by balchua** [comment]
PR #1486 merged which fixes this one.
