### ISSUE TITLE
Disable SSL Medium Strength Cipher Suites Support

### ISSUE THREAD

**Issue by vadimeisenbergibm** [ubuntu/microk8s#1419]
To handle https://github.com/kubernetes/kubernetes/issues/41038.

The Kubernetes solution is to use `--tls-cipher-suites` described in https://github.com/kubernetes/kubernetes/pull/48859.

Is it possible to configure microk8s to use that option, or maybe you can just remove the medium strength cipher suites by default?

**Comment by balchua** [comment]
You can configure kube-apiserver's arguments.
Go to `/var/snap/microk8s/args/kube-apiserver`.
While the kubelet's file is in `/var/snap/microk8s/args/kubelet`.  After modifying, you can restart microk8s.

**Comment by vadimeisenbergibm** [comment]
Thanks a lot, @balchua ! Let me try.

**Comment by vadimeisenbergibm** [comment]
Great, I have added the `--tls-cipher-suites` parameter to the following files on Ubuntu:

- `/var/snap/microk8s/current/args/kube-apiserver`
- `/var/snap/microk8s/current/args/kube-scheduler`
- `/var/snap/microk8s/current/args/kube-controller-manager`
- `/var/snap/microk8s/current/args/kubelet`

and it seems to work. Closing the issue. Thanks, @balchua !

**Comment by ryanwong00** [comment]
Sorry for bringing this backup.  I recently used Nexsus scanner to scan my Microk8s 1.27 and stumbled onto the same SWEET32 findings.  By using the above methods, most ports are fixed except 19001 and 25000.  For 25000, I have appended '--min-tls-version "tls13"' to /var/snap/microk8s/current/args/cluster-agent and it seems fixed the vulnerability since TLS 1.3 removed 3DES encryption.  Is there any way to fix 19001 (i.e. dqlite)?

BTW, the vulnerability for 19001 did not happen in Microk8s 1.23.  That can be tested by using command ' nmap --script ssl-enum-ciphers -p 19001 _hostname_'

**Comment by hirushanlk** [comment]
@balchua I have tried using Microk8s 1.30, and the options above appear to fix ports 16443, 10250 with adding `--tls-cipher-suites` to the kube-apiserver and adding `--min-tls-version=tls13` to the cluster-agent fix the port 25000. 

But any update on fixing this on port 19001?

**Comment by naphtali-davies** [comment]
Hi, I have the same for port 12379  which is etcd.
Etcd doesn't recognize the --min-tls-version flag or --tls-cipher-suites

**Comment by HanochLzd** [comment]
> @balchua I have tried using Microk8s 1.30, and the options above appear to fix ports 16443, 10250 with adding `--tls-cipher-suites` to the kube-apiserver and adding `--min-tls-version=tls13` to the cluster-agent fix the port 25000.
> 
> But any update on fixing this on port 19001?

At present, MicroK8s 1.32 has been released, which uses K8s-dqlite v1.3.0 and can support the "--min-tls-version=tls13" configuration. If you don't want to upgrade the entire microk8s, you can replace the K8s-dqlite and execute it. My environment is microk8s1.27, which can be executed normally with K8s-dqlite v1.3.0, and the "--min-tls-version=tls13" parameter can be recognized.

Update ExecStart to use the new K8s-dqlite executable (before replacing, it's best to back up storage-dir)
