### ISSUE TITLE
Error While Disabling Prometheus

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1430]
When disabling prometheus addon I get this error
```
Traceback (most recent call last):
  File "/snap/microk8s/1564/scripts/wrappers/status.py", line 242, in <module>
    print_pretty(isReady, enabled, disabled)
  File "/snap/microk8s/1564/scripts/wrappers/status.py", line 51, in print_pretty
    info = get_dqlite_info()
  File "/snap/microk8s/1564/scripts/wrappers/common/utils.py", line 71, in get_dqlite_info
    with open("{}/info.yaml".format(cluster_dir), mode='r') as f:
```
Everything seems to disable fine and I can reenable it without problems but just thought I would add this in case it causes problems down the line.

**Comment by sstubbs** [comment]
I get the same error when I disable DNS. Is https://github.com/ubuntu/microk8s/pull/1429 related to this? Is it better to run sudo microk8s for everything or will this PR fix it?

**Comment by ktsakalozos** [comment]
You see this error on the `latest/edge/ha-preview` channel when your user is on the `microk8s` group, right? Yes, this error should be fixed in with https://github.com/ubuntu/microk8s/pull/1429

**Comment by sstubbs** [comment]
yes on the `latest/edge/ha-preview` channel. ok great thanks.

**Comment by balchua** [comment]
Pr merged
