### ISSUE TITLE
[Question] How to set default sysctl net.ipv6.conf.all.disable_ipv6 for cluster

### ISSUE THREAD

**Issue by vassilvk** [ubuntu/microk8s#1433]
We need to have IPv6 disabled by default for all pods that will run on our `microk8s` clusters (`sysctl net.ipv6.conf.all.disable_ipv6=1`).

This has been the default value for that kernel parameter on all K8s clusters we have used so far (i.e. RKE, Kubernetes on Docker).
Now we are considering using `microk8s` for our development workflows, but the default value for `net.ipv6.conf.all.disable_ipv6` in containers created by `microk8s` is `0` which leads to failures in a number of our containers because IPv6 being enabled causes localhost to resolve to `::1` instead of `127.0.0.1`.

I am looking for a sensible way to set `net.ipv6.conf.all.disable_ipv6=1` for all pods deployed to `microk8s` by default.

I was able to configure `microk8s`'s kubelet to add the sysctl to the safe param list (through `--allowed-unsafe-sysctls=net.ipv6.*`).
I was also able to set `net.ipv6.conf.all.disable_ipv6` to `1` in a pod manifest by using the pod's `securityContext:sysctls`.

That's all great, but I'd like to avoid having to set this on every pod definition as our Helm charts need to be able to deploy on different Kubernetes environments, including ones where `net.ipv6.conf.all.disable_ipv6` is set to `1` by default, but also where we don't have access to the kubelet settings to allow unsafe `sysctls`.

**Comment by ktsakalozos** [comment]
@vassilvk I do not have an good answer. What is the `net.ipv6.conf.all.disable_ipv6` on the host machine?

**Comment by vassilvk** [comment]
It’s 1.
