### ISSUE TITLE
Microk8s 1.15 unbound variable error

### ISSUE THREAD

**Issue by jaaanko** [ubuntu/microk8s#1436]
Hi, I am getting the following error when running `microk8s.kubectl config view --raw > $HOME/.kube/config` on microk8s 1.15. 

`/snap/microk8s/1301/microk8s-kubectl.wrapper: line 16: args[@]: unbound variable`

I cannot upgrade my microk8s version due to compatibility issues with another application.

**Comment by ktsakalozos** [comment]
Hi @jaaanko 

Can you help me reproduce this.  Could you share the output of `cat /snap/microk8s/1301/microk8s-kubectl.wrapper` and the tarball of the `microk8s.inspect` command? Does this `args[@]: unbound variable` error appear in other `microk8s.kubectl` commands?

**Comment by jaaanko** [comment]
Hi @ktsakalozos, yes the error appears in other `microk8s.kubectl` commands.

Here is the tarball:
[inspection-report-20200727_085407.tar.gz](https://github.com/ubuntu/microk8s/files/4981030/inspection-report-20200727_085407.tar.gz)

And here is the output of `cat /snap/microk8s/1301/microk8s-kubectl.wrapper`:
```
#!/bin/bash

set -eu

export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
source $SNAP/actions/common/utils.sh

exit_if_stopped

if echo "$*" | grep -v -q -- '--kubeconfig'; then
  exit_if_no_permissions
fi


declare -a args="($(cat $SNAP_DATA/args/kubectl))"
"${SNAP}/kubectl" "${args[@]}" "$@"
```

**Comment by balchua** [comment]
Could it be that the `bash` in your system is old?

**Comment by jaaanko** [comment]
Reinstalling seems to have fixed this issue.
