### ISSUE TITLE
Need docs linked from inspect to fix nf_conntrack sizing by lxc guest for daemon-proxy

### ISSUE THREAD

**Issue by kriswuollett** [ubuntu/microk8s#1438]
Seems same issue as in the closed #119, daemon-proxy in microk8s is attempting to update my system's `/sys/module/nf_conntrack/parameters/hashsize`. Based on some research it sounds like it needs to update it since my Ubuntu 20.04 machine has a lot of CPU cores. There should be a mechanism like in microk8s.inspect to detect this type of error that causes `daemon-proxy` to fail to start, and link to some documentation on how to fix (per OS as needed).

I think there was another issue that a command line flag used to be supported that would cause `daemon-proxy` to skip trying to update these settings, but is now ignored? Is there anyway I can configure microk8s instead of updating my system settings?

[inspection-report-20200728_004132.tar.gz](https://github.com/ubuntu/microk8s/files/4985511/inspection-report-20200728_004132.tar.gz)

My current workaround is:

```shell
sudo /sbin/sysctl -w net.nf_conntrack_max=1572864
sudo /sbin/sysctl -w net.netfilter.nf_conntrack_max=1572864
echo 393216 | sudo tee -a /sys/module/nf_conntrack/parameters/hashsize
```

I assume after reboot updates to these files will cause the fix to be persisted:

```
# /etc/modules
nf_conntrack

# /etc/sysctl.conf
net.netfilter.nf_conntrack_max=1572864
net.nf_conntrack_max=1572864

# /etc/modprobe.d/ip_conntrack_hashsize.conf
options ip_conntrack hashsize=393216
```

**Comment by ktsakalozos** [comment]
Thank you for reporting this @kriswuollett and offering a workaround.

Indeed updating the inspection script to detect this case would be the a first step. 

Have you tried adding `--conntrack-max-per-core=0` in `/var/snap/microk8s/current/args/kube-proxy`?

Another approach would be to see why the lxc profile in `https://github.com/ubuntu/microk8s/blob/master/tests/lxc/microk8s.profile` did not allow access to `/sys/module/nf_conntrack/parameters/hashsize`.

**Comment by kriswuollett** [comment]
I reduced `hashsize` on the host and I can confirm `--conntrack-max-per-core=0` in the config file works. Thanks for pointing that out to me.

Otherwise, regarding the profile config itself, is there any special meaning to devices named with a [prefix `aadisable`](https://github.com/ubuntu/microk8s/blob/1e18f12fa3314eaa1f72bab5b6e300a11a6943ee/tests/lxc/microk8s-zfs.profile#L14)? I couldn't find anything about that in the [instance configuration docs](https://lxd.readthedocs.io/en/latest/instances/#devices-configuration), but the naming seems a bit suspicious to me.

I've also tried making `/sys/module/nf_conntrack/parameters/hashsize` temporarily world writable and starting a new container, but doing `echo "393216" > hashsize` inside the container still yields `bash: echo: write error: Operation not supported`. Same with omitting the profile entry for the hashsize file itself in case "aadisable*" means something. So with the other `lxc` settings in the microk8s config like `security.privileged: true` `lxc.mount.auto=proc:rw sys:rw cgroup:rw` and glancing at [lxc security](https://linuxcontainers.org/lxc/security/) I'd guess that something like apparmor is preventing access, but I won't have a chance to learn more until the weekend.

**Comment by sstubbs** [comment]
I also had this issue in lxd. `--conntrack-max-per-core=0` does fix it but I'm wondering what other problems adding this will cause.

**Comment by dogbertai** [comment]
https://github.com/ubuntu/microk8s/blob/master/tests/lxc/microk8s-zfs.profile
https://github.com/ubuntu/microk8s/blob/master/tests/lxc/microk8s.profile
```
    path: /sys/module/nf_conntrack/parameters/hashsize
    source: /sys/module/nf_conntrack/parameters/hashsize
```
I think this is redundant, since `lxc.mount.auto=proc:rw sys:rw cgroup:rw` is already set, and it doesn't meet the explanation in https://microk8s.io/docs/lxd

> devices: disable /sys/module/nf_conntrack/parameters/hashsize and /sys/module/apparmor/parameters/enabled: Hide two files owned by the host from the LXD containers. Containers cannot disable AppArmor or set the size of the connection tracking table[7].

Is it supposed to be ? `source: /dev/null`

Maybe these guys copied the same error https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/

I think `--conntrack-max-per-core=0` in `/var/snap/microk8s/current/args/kube-proxy` should be added to https://microk8s.io/docs/lxd

**Comment by dev852com** [comment]
Set this on the host if you are running microk8s in lxd
