### ISSUE TITLE
Fluentd can't connect to elasticsearch: memory leak and crash on a fresh install

### ISSUE THREAD

**Issue by arnoldfranz** [ubuntu/microk8s#1451]
Hi,
I did a fresh install of microk8s on a Virtualbox VM Ubuntu 10.04 fully updated today. (6 GBi RAM, 2 cores)
I install microk8s following the documentation: https://microk8s.io/docs
I enable the addons in this order :  
sudo microk8s enable storage
sudo microk8s enable rbac
sudo microk8s enable dns
sudo microk8s enable fluentd
sudo microk8s enable metrics-server
sudo microk8s enable dashboard
sudo microk8s enable ingress

All seems working well but in fact fluentd pod has a problem:

2020-07-30 10:08:11 +0000 [warn]: [elasticsearch] got unrecoverable error in primary and no secondary error_class=Fluent::Plugin::ElasticsearchOutput::ConnectionFailure error="Can not reach Elasticsearch cluster ({:host=>\"elasticsearch-logging\", :port=>9200, :scheme=>\"http\"})!"
2020-07-30 10:08:11 +0000 [warn]: [elasticsearch] bad chunk is moved to /tmp/fluentd-buffers/backup/worker0/elasticsearch/5aba5d941e1815620131cf3aa61740fe.log

I leads to a memory leak that eventually crashes the server.
I attach the inspection report.
I haven't even deployed a pod or any other kubernetes object! Just right out of the box the issue is there.

Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20200730_101021.tar.gz](https://github.com/ubuntu/microk8s/files/5000586/inspection-report-20200730_101021.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

**Comment by arnoldfranz** [comment]
Ubuntu 18.04 and not 10.04 :-)

**Comment by balchua** [comment]
The fluentd addon image is rather old.  I guess its time to update it.  I will try to make a PR updating fluentd addon.
The addon is mostly taken from here https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

**Comment by arnoldfranz** [comment]
Thank you, 
I have rebuilt again a new installation with 6 Gi of RAM and the error messages disappeared.
I think my problem was due to the size of the machine.
However, the logger is flooded by by metrics-server witch emits a message every 50 ms !! I open an issue on this topic.
So I close the issue.
