### ISSUE TITLE
Metrics-server floods the logger with messages ERROR: logging before flag.Parse: E0730 17:44:28.043770 

### ISSUE THREAD

**Issue by arnoldfranz** [ubuntu/microk8s#1455]
Hi,
My Box is a Microk8s Ubuntu 18.04 last update, 6Gi RAM 200 Gi SSD VM Virtualbox
Installation was done today, following the doc https://microk8s.io/docs. The cluster works fine. Nothing installed or done after basic installation. It is just fresh out of the box.  Addons have been installed: storage, rbac, dns, fluentd, metrics-server, dashboard, ingress.
The issue:
Every 50 ms the metrics server sends a log message : "ERROR: logging before flag.Parse: E0730 17:44:28.043770 "
I attach a screen shot of Kibana/fluentd with some details. I add also the inspection report.
![floodingByMetricsServer](https://user-images.githubusercontent.com/45284097/88961917-fa5c2100-d2a5-11ea-90d7-412565f255d0.PNG)
Any clue is welcome.
AF

[inspection-report-20200730_184445.tar.gz](https://github.com/ubuntu/microk8s/files/5003248/inspection-report-20200730_184445.tar.gz)

**Comment by balchua** [comment]
Thanks for reporting this.  I looked at the inspection report.  I can see that it is still running heapster and old metrics server. Which we recently upgraded and heapster is decommissioned.  Perhaps its not in the 1.18 channel.
The error seems to be related to rbac for the addon-resizer.  What if we turn off RBAC?  Just testing it out.

**Comment by arnoldfranz** [comment]
Thank you for your help. 
I did while microk8s was started:
microk8s disable rbac
At this point, still log flooding by metrics-server
After I did:
microk8s stop
microk8s start
The problem is still there.
Conclusion: disabling rbac didn't fix the issue.

**Comment by balchua** [comment]
I tried reproducing this issue today.  I get some logs from metrics server but it is not continuously spewing this out.
Tried with bare bones microk8s, addons enabled: prometheus, linkerd, rbac, fluentd and metrics-server.
