### ISSUE TITLE
Enable GPU addon when master is "CPU" and a node has Nvidia drivers installed?

### ISSUE THREAD

**Issue by maximveksler** [ubuntu/microk8s#1466]
Hi,

I have a 2 nodes cluster, the master being a CPU only node running control plane. A second node in the cluster has cuda installed and has 2 GPU's.

```
root@ops-maser:~# microk8s kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION
172.19.0.2   Ready    <none>   21m   v1.18.6
ops-maser    Ready    <none>   29m   v1.18.6
```

```
root@ops-maser:~# microk8s enable gpu 
Enabling NVIDIA GPU
Aborting: NVIDIA kernel module not loaded.
Please ensure you have CUDA capable hardware and the NVIDIA drivers installed.
Failed to enable gpu
```

Is this mode supported where clsuter nodes have GPU however plugins are used to enable them?

Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20200802_205010.tar.gz](https://github.com/ubuntu/microk8s/files/5012912/inspection-report-20200802_205010.tar.gz)

**Comment by balchua** [comment]
Thanks for reporting this issue.  In the current cluster setup commands related to `microk8s` are limited to the main node as you have already pointed out.
But in the ha-cluster preview version any node can issue `microk8s` commands.

**Comment by codebeard1** [comment]
I'm having a similar issue with enabling GPU on Microk8s with WSL2. I have a single node Microk8s cluster and have followed all of the steps for the [NVIDIA driver](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#installing-wsl2) for which I'm able to use my machines GPU with Docker and Tensorflow without any issues. However, when I run microk8s.enable gpu I still get the following message. Any thoughts?

Enabling NVIDIA GPU
Aborting: NVIDIA kernel module not loaded.
Please ensure you have CUDA capable hardware and the NVIDIA drivers installed.
Failed to enable gpu

**Comment by codebeard1** [comment]
For setting up microk8s I used the instructions [here](https://wsl.dev/wsl2-microk8s/) to get to this point. Also, I'm wondering if I have to go through this [exercise](https://github.com/NVIDIA/kubevirt-gpu-device-plugin) first in order for the GPU to be recognized by microk8s?

**Comment by ziongh** [comment]
I have the same issue as @codebeard1, any news?
