### ISSUE TITLE
microk8s v1.18 seems to prevent installing kubeflow from manifests

### ISSUE THREAD

**Issue by tomalbrecht** [ubuntu/microk8s#1472]
It seems, that microk8s prevents installing kubeflow from manifests. 
- Why is it not possible to install kubeflow via manifests?
- What do I have to change, so I am able to deploy the kubeflow manifests?

What am I trying to do?
- Installing microk8s v1.18.6
   - `microk8s.enable dns dashboard storage gpu`
   - Patching Istio configuration for trustworthy JWTs
- Deploying kubeflow manually (not microk8s.enable kubeflow)
   - Deployed kubeflow as described here: https://www.kubeflow.org/docs/started/k8s/kfctl-istio-dex/
- Running the tutorial from here: https://github.com/kubeflow/pipelines/blob/master/samples/core/lightweight_component/lightweight_component.ipynb

The tutorial won't succeed on microk8s. But it seems to work on other distributions of k8s. See kubeflow issue regarding the same problem: https://github.com/kubeflow/pipelines/issues/4302

[inspection-report-20200805_070845.tar.gz](https://github.com/ubuntu/microk8s/files/5026255/inspection-report-20200805_070845.tar.gz)

**Comment by balchua** [comment]
Coredns doesn't look healthy
```shell
==== START logs for container coredns of pod kube-system/coredns-588fd544bf-g8jwz ====
.:53
[INFO] plugin/reload: Running configuration MD5 = be0f52d3c13480652e0c73672f2fa263
CoreDNS-1.6.6
linux/amd64, go1.13.5, 6a7a75e
[INFO] 10.1.68.1:52816 - 51332 "A IN www.googleapis.com.fritz.box. udp 46 false 512" NOERROR - 0 6.001795719s
[ERROR] plugin/errors: 2 www.googleapis.com.fritz.box. A: read udp 10.1.68.15:50545->8.8.4.4:53: i/o timeout
[INFO] 10.1.68.1:49470 - 63446 "AAAA IN metadata-grpc-service.fritz.box. udp 49 false 512" NOERROR - 0 6.001563713s
[ERROR] plugin/errors: 2 metadata-grpc-service.fritz.box. AAAA: read udp 10.1.68.15:42129->8.8.4.4:53: i/o timeout
==== END logs for container coredns of pod
```
Does this server have access to the internet?

**Comment by tomalbrecht** [comment]
Yes. I did a fresh install (without VPN, maybe I ran microk8s.inspect while on VPN).
[inspection-report-20200806_103648.tar.gz](https://github.com/ubuntu/microk8s/files/5033631/inspection-report-20200806_103648.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @tomalbrecht,

Thank you for using MicroK8s. I see the pods on the cluster up an running. Could you provide more details on how exactly the tutorial is failing? For example which point is failing, with what error. As soon as the error comes up can you create a `microk8s.inspect` tarball so we grab the state the cluster is in?

**Comment by tomalbrecht** [comment]
@ktsakalozos here it is.

tal@ki-server1:~/workspace/ki-stack$ kubectl get pods -A | grep calc
kubeflow               calculation-pipeline-hwvjr-1240467882                          0/2     Completed   0          6d4h
kubeflow               calculation-pipeline-zpvvt-3399156013                          0/2     Completed   0          6d4h

[inspection-report-20200810_124008.tar.gz](https://github.com/ubuntu/microk8s/files/5050814/inspection-report-20200810_124008.tar.gz)

![image](https://user-images.githubusercontent.com/17781570/89783771-cb507580-db17-11ea-9428-289cb8da947d.png)

![image](https://user-images.githubusercontent.com/17781570/89783831-e0c59f80-db17-11ea-92b2-88a5d2cb0aae.png)

[logs_calculation-pipeline-hwvjr-1240467882.txt](https://github.com/ubuntu/microk8s/files/5050847/logs_calculation-pipeline-hwvjr-1240467882.txt)


On minikube this tutorial will run kubeflow. Not sure where to look at.

**Comment by knkski** [comment]
@tomalbrecht: I suspect you need to switch to the PNS executor:

https://argoproj.github.io/argo/workflow-executors/#process-namespace-sharing-pns

The default executor for Argo (which Kubeflow Pipelines builds on) is a docker executor, which isn't used by MicroK8s.

**Comment by tomalbrecht** [comment]
@knkski: Patching pns into argo executor does solve the problem. The kubeflow pipeline succeeds now. Thanks for your help.

![image](https://user-images.githubusercontent.com/17781570/90010628-72601900-dca0-11ea-87b0-b5e27176e725.png)

![image](https://user-images.githubusercontent.com/17781570/90010693-93286e80-dca0-11ea-9efd-295fb7f865ce.png)
