### ISSUE TITLE
Port forward issue

### ISSUE THREAD

**Issue by axelekwall** [ubuntu/microk8s#1473]
Hello! I just got up and running with microk8s and I'm trying to make the dashboard available. When running the `kubectl` port-forward command it changes the port from `443` to `8443` for some reason resulting in errors when trying to access the service. Does anyone know hot to fix this issue?

```
axel@homepi:~$ kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443 --address 0.0.0.0
Forwarding from 0.0.0.0:10443 -> 8443
```

**Comment by axelekwall** [comment]
I think this might be related, I get the same error as described here: https://discuss.kubernetes.io/t/dashboard-service-connection-refused/11786

**Comment by axelekwall** [comment]
I figured it out, UFW issue. It works with the firewall disabled. Closing the issue.

**Comment by SpongeManiac** [comment]
I have this issue too, can you specify what firewall you are disabling?
