### ISSUE TITLE
First installs stuck in Pending

### ISSUE THREAD

**Issue by BitRacer** [ubuntu/microk8s#1474]
I'm new to microk8s so this may be an obvious miss on my part.  

I am using microk8s to better understand service mesh, istio/envoy etc.  I have tried installing coredns, dashboard and they seem stalled.

Also when I run  'microk8s install envoy' as noted here:
https://istio.io/latest/docs/setup/platform-setup/microk8s/

It does not seem to do work...

root@master:~# microk8s.enable envoy
Nothing to do for envoy

Same with istio
https://istio.io/latest/docs/setup/platform-setup/microk8s/
root@master:~# microk8s.enable istio
Nothing to do for istio

Every 2.0s: microk8s.kubectl get all --all-namespaces                                                                                                                                               master: Wed Aug  5 13:48:16 2020

NAMESPACE     NAME                                            READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-588fd544bf-sjc5r                    0/1     Pending   0          9h
kube-system   pod/dashboard-metrics-scraper-59f5574d4-fd8qd   0/1     Pending   0          9h
kube-system   pod/kubernetes-dashboard-6d97855997-f96ft       0/1     Pending   0          9h
kube-system   pod/metrics-server-79749d858b-bfxxl             0/1     Pending   0          9h

NAMESPACE     NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes                  ClusterIP   10.152.183.1     <none>        443/TCP                  12h
kube-system   service/dashboard-metrics-scraper   ClusterIP   10.152.183.175   <none>        8000/TCP                 9h
kube-system   service/kube-dns                    ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   9h
kube-system   service/kubernetes-dashboard        ClusterIP   10.152.183.190   <none>        443/TCP                  9h
kube-system   service/metrics-server              ClusterIP   10.152.183.111   <none>        443/TCP                  9h

NAMESPACE     NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                     0/1     1            0           9h
kube-system   deployment.apps/dashboard-metrics-scraper   0/1     1            0           9h
kube-system   deployment.apps/kubernetes-dashboard        0/1     1            0           9h
kube-system   deployment.apps/metrics-server              0/1     1            0           9h

NAMESPACE     NAME                                                  DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-588fd544bf                    1         1         0       9h
kube-system   replicaset.apps/dashboard-metrics-scraper-59f5574d4   1         1         0       9h
kube-system   replicaset.apps/kubernetes-dashboard-6d97855997       1         1         0       9h
kube-system   replicaset.apps/metrics-server-79749d858b             1         1         0       9h

[inspection-report-20200805_134929.tar.gz](https://github.com/ubuntu/microk8s/files/5028822/inspection-report-20200805_134929.tar.gz)

**Comment by balchua** [comment]
@BitRacer thanks for using MicroK8s.
First, i think you need to setup the cgroups on your system for raspberry PIs.
Here's link.
https://discuss.kubernetes.io/t/alternative-installs-macos-windows-10-multipass/11257
Or here 
https://microk8s.io/docs/install-alternatives#heading--arm

Second, There is no istio available for `arm64` architecture.
And envoy isn't included as microk8s addon, that is why issuing `microk8s enable envoy` yields nothing.

**Comment by BitRacer** [comment]
@balchua the istio guys pointed me here.  just thought I would share it https://www.envoyproxy.io/docs/envoy/latest/install/building#arm64-binaries

it does look like there are two docker containers available, would this work?

**Comment by balchua** [comment]
Im not that familiar with envoy.  I think you can manually install envoy into your cluster.  It should be able to get the arm64 image. But for the istio addon in microk8s, dont think we have an arm64 version.

**Comment by BitRacer** [comment]
ok, thanks for the feedback.  certainly makes the learning curve a little steeper, but Ill figure it out.  thanks
