### ISSUE TITLE
Future channel for ha-preview

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1481]
Hi,

I'll be setting up a production cluster in a few days for some smaller workloads. I've been testing the ha-preview channel for a while and its working well. Once it's out of preview will there be a stable ha channel that I can change the installation to use? Or will I have to reinstall microk8s?

**Comment by ktsakalozos** [comment]
Hi @sstubbs, 

The HA work will go into the master branch within the next two weeks so it will get released with the v1.19 kubernetes.

If you deploy now from the latest/stable there will be instructions on how to enable HA when released.

Thank you for trying out the HA preview. Your feedback is very valuable.

**Comment by sstubbs** [comment]
ok that is great news. Thanks.
