### ISSUE TITLE
Microk8s stop + start results in dead pods

### ISSUE THREAD

**Issue by ninja-** [ubuntu/microk8s#1483]
Running microk8s stop and then start results in dead pods in etcd and then attempt to view pod logs for example will result in:

```
kubectl logs xx
Error from server (NotFound): the server could not find the requested resource ( pods/log xx)
```

I would expect pods to survive microk8s restart, or at least be wiped during restart...
Pods are not going to run after restart if I don't manually delete them

EDIT: looks like it recovers by itself after a few minutes...but I would still be interested to know if I can make pods survive microk8s restart in some way? Most kubernetes implementations offer that, especially these using docker.

**Comment by balchua** [comment]
microk8s stop will stop kubelet, containerd, apiserver etc.. which mean the pod is terminated.
