### ISSUE TITLE
Unable to deploy in microk8s using local file. Mac OS

### ISSUE THREAD

**Issue by andreas-ahman** [ubuntu/microk8s#1489]
After installation of microk8s i enabled the dns plugin.

```
microk8s kubectl get pods --all-namespaces
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-588fd544bf-v46bn   1/1     Running   0          16m
```

Which works fine. But when deploying any workload using a local deployment specification I get the following error.

```
microk8s kubectl apply -f busybox.yaml
error: the path "busybox.yaml" does not exist
An error occurred when trying to execute 'sudo microk8s.kubectl apply -f busybox.yaml' with 'multipass': returned exit code 1.
```

Any ideas?

**Comment by ktsakalozos** [comment]
MicroK8s still runs on a VM on MacOS. You will need to transfer the yaml manifest file in the VM with `multipass transfer` or `multipass mount`, see [1]

[1] https://multipass.run/docs/working-with-instances

**Comment by andreas-ahman** [comment]
Yes I became aware of that and forgot to close the issue. I was under the impression that the transfer of the manifests was handled by the microk8s cli tool.
But eventually found some documentation.
