### ISSUE TITLE
Microk8s Master only

### ISSUE THREAD

**Issue by gnilesh4** [ubuntu/microk8s#1492]
Hi Microk8s Team,

We are trying to setup a multinode cluster with microk8s.
To add slave nodes to the microk8s cluster, we are running the add-node command and generating the join command.

When we do deployment ( Angular UI ) in Master Node the pods are created as expected.

The issue is the pods are created in Master & we are able to access the site from Master + child node, 
How do we restrict this and the site should be accessed from child node only.

Please advice.

**Comment by balchua** [comment]
Hi @gnilesh4 you do not want the pod to be scheduled on the master node?
Normally it is done using taints and tolerations.  MicroK8s by default do not set these taints.
There's a good documentation at the kubernetes docs. https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

**Comment by gnilesh4** [comment]
@balchua , i will try the solution today & update you
Thanks for the support.
