### ISSUE TITLE
Metallb libssl_conf.so missing(?)

### ISSUE THREAD

**Issue by natdan** [ubuntu/microk8s#1497]
On arm64 (aarch64) snap versions:
  latest/candidate: v1.18.8  2020-08-14 (1615) 187MB classic
  latest/edge:      v1.18.8  2020-08-19 (1625) 186MB classic

BTW latest/stable (v1.18.6) is fine...

```
$ microk8s enable metallb
Enabling MetalLB
Enter each IP address range delimited by comma (e.g. '10.64.140.43-10.64.140.49,192.168.0.105-192.168.0.111'): 192.168.5.10-192.168.5.99
Error configuring OpenSSL
548145813264:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
548145813264:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:233:
548145813264:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:271:module=ssl_conf, path=ssl_conf
548145813264:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:212:module=ssl_conf
Applying Metallb manifest
namespace/metallb-system created
error: error validating "STDIN": error validating data: unknown object type "nil" in Secret.data.secretkey; if you choose to ignore these errors, turn validation off with --validate=false
Failed to enable metallb
```

**Comment by ktsakalozos** [comment]
Thank you for following the candidate channel and for reporting this issue @natdan. What distribution is this on?

@balchua I think we missed the OPENSSL_CONF variable [1].

[1] https://github.com/ubuntu/microk8s/pull/985/files

**Comment by natdan** [comment]
LOL - I was, kind of, avoiding to say immediately! O: )

It is on Raspberry Pi  64bit PiOS (formerly known as Raspbian)...

I'm looking forward giving it a go as soon as your PR goes through.
Thanks for the quick fix, too! :)

**Comment by natdan** [comment]
Now I am confused. @ktsakalozos your PR is adding 
```
export OPENSSL_CONF="/snap/microk8s/current/etc/ssl/openssl.cnf"
```
but that line is already in the master! :( (and there are other changes)...

**Comment by natdan** [comment]
BTW - I've just given it a go and script with your changes worked well (no error reported). I am yet to test metallb as I've completely undone my cluster and I'll need to build it up again before I can see if metallb works or not. But 🤞  😃
