### ISSUE TITLE
No default storageclass present

### ISSUE THREAD

**Issue by srinathganesh1** [ubuntu/microk8s#1503]
`microk8s kubectl get storageclass` is returning empty for me. 

Is there any way to auto create a default storageclass? like minikube comes with a built in storageclass

-------

`microk8s inspect`
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

WARNING:  Docker is installed. 
Add the following lines to /etc/docker/daemon.json: 
{
    "insecure-registries" : ["localhost:32000"] 
}
and then restart docker with: sudo systemctl restart docker
Building the report tarball
  Report tarball is at /var/snap/microk8s/1551/inspection-report-20200820_132538.tar.gz

**Comment by ktsakalozos** [comment]
For local development you could try: `microk8s enable storage`

**Comment by srinathganesh1** [comment]
> For local development you could try: `microk8s enable storage`
Thanks, it works now
generally its default in all Vendors like AKS, GKE. Wonder why its manual here.
