### ISSUE TITLE
Raspberry PI4 - invalid capacity 0 on image filesystem

### ISSUE THREAD

**Issue by kensykora** [ubuntu/microk8s#1510]
[inspection-report-20200823_022916.tar.gz](https://github.com/ubuntu/microk8s/files/5113426/inspection-report-20200823_022916.tar.gz)

I'm following this guide on how to setup microk8s on a raspberry pi 4. <https://ubuntu.com/tutorials/how-to-kubernetes-cluster-on-raspberry-pi#4-installing-microk8s> I've managed to get it up and running and can connect with kubectl, but when I try to install dns and dashboard those services don't come online. The containers are stuck in `Pending` state and the node status is tainted with Not Ready and giving this error:

```
Warning  InvalidDiskCapacity      7s     kubelet, ubuntu     invalid capacity 0 on image filesystem
```

Looking at similar threads on the issue seem to indicate zfs needs some special configuration, but that's not the case here for me, as it's running on an ext4 mounted microSD card.

I did try similar recommendations for the ZFS issue to set my `snapshotter = "native"` in ` /var/snap/microk8s/current/args/containerd-template.toml` but that had no effect, same error.

I'm not sure where to look next, being new to k8s. Any suggestions would be helpful. Thank you!

**Comment by ktsakalozos** [comment]
Hi @kensykora 

Thank you for reporting this.

I just updated the docs [1] to point out the kernel command line parameters are distribution specific. We also have a pending PR [2] against `microk8s inspect` that could detect missing cgroups and will point to the docs.

[1] https://discuss.kubernetes.io/t/alternative-installs-macos-windows-10-multipass/11257
[2] https://github.com/ubuntu/microk8s/pull/1501

**Comment by kensykora** [comment]
Wonderful, thank you @ktsakalozos!
