### ISSUE TITLE
How to use a custom conf file for Ingress

### ISSUE THREAD

**Issue by AnishAnil** [ubuntu/microk8s#1513]
Hello microk8s

In nginx we can use a custom "conf" file to redirect the error pages to the ones hiding the internal information about the used reverse proxy server. 

For EX: if the Application server is down and if a user accesses  the Ingress URl it shows the version of nginx installed on the system and is a security breach. What is ideally done to harden the NGINX is to provide custom html error pages for 40x and 50x errors by modifying the conf file.

Can something similar be done for Ingress aswell??

Thank you,
Anish

**Comment by ktsakalozos** [comment]
Hi @AnishAnil 

Would something like [1] work for you?

[1] https://kubernetes.github.io/ingress-nginx/user-guide/custom-errors/

**Comment by AnishAnil** [comment]
No Not exactly,

Please find my conf file:

***************
# generated 2020-08-19, Mozilla Guideline v5.6, nginx 1.16.1, OpenSSL 1.1.1c, intermediate configuration, no OCSP
# https://ssl-config.mozilla.org/#server=nginx&version=1.16.1&config=intermediate&openssl=1.1.1c&ocsp=false&guideline=5.6
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
	
	server_name mickok8s-staging.com;     server_tokens off; 
	
    ssl_certificate /etc/pki/tls/certs/star.crt;
    ssl_certificate_key /etc/pki/tls/private/star.key;
	
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam
    #ssl_dhparam /path/to/dhparam;
	
	root /usr/share/nginx/html; 

    location / {
	 proxy_set_header X-Forwarded-For $remote_addr;
	 proxy_set_header   Host $http_host;
	 proxy_pass         http://localhost:8080;
    }

    error_page 404 /custom_40x.html;
    location = /custom_40x.html {
	root /usr/share/nginx/html;
	internal;
    }

    error_page 500 502 503 504 /custom_50x.html;
    location = /custom_50x.html {
	root /usr/share/nginx/html;
	internal;
    }
	location = /Gerrit.png {     
	root /usr/share/nginx/html/custom_50ximages;    
	}
}

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;
}
***************

I'm trying to add the above nginx .conf file to the ingress. 
By default it exists in /etc/nginx/conf/custom.conf

**Comment by balchua** [comment]
I think how to provide custom error pages is by creating a default backend.  See example here https://github.com/kubernetes/ingress-nginx/tree/master/images/custom-error-pages
