### ISSUE TITLE
Joining nodes fails with openssl config error

### ISSUE THREAD

**Issue by djjudas21** [ubuntu/microk8s#1514]
I'm trying to set up a sandbox microk8s cluster but I'm failing at the `microk8s join` stage. My environment is CentOS 8 Virtualbox VMs, with bridged networking.

On the master:
```
[jonathan@kube01 inspection-report]$ microk8s add-node
From the node you wish to join to this cluster, run the following:
microk8s join 192.168.0.41:25000/900dec3a5ee653a4e838d5f41e189eae

If the node you are adding is not reachable through the default interface you can use one of the following:
 microk8s join 192.168.0.41:25000/900dec3a5ee653a4e838d5f41e189eae
 microk8s join 10.1.19.0:25000/900dec3a5ee653a4e838d5f41e189eae
```

On the worker:
```
[jonathan@kube02 ~]$ microk8s join 192.168.0.41:25000/900dec3a5ee653a4e838d5f41e189eae
WARNING: can't open config file: /usr/lib/ssl/openssl.cnf
```

The worker complains about `/usr/lib/ssl/openssl.cnf` but produces no errors. It never joins the cluster, but you have to run `microk8s leave` if you want to try again.

Output of `microk8s inspect` on both nodes:
[master-inspection-report-20200825_165737.tar.gz](https://github.com/ubuntu/microk8s/files/5124923/master-inspection-report-20200825_165737.tar.gz)
[worker-inspection-report-20200825_165937.tar.gz](https://github.com/ubuntu/microk8s/files/5124925/worker-inspection-report-20200825_165937.tar.gz)

I've tried grepping the logs for references to `openssl` but didn't find anything. I don't know enough about the rest of 

I noticed #978 and wondered if it was related, but the fix produced after that issue should be in the versions I've tried (v1.18.8 from `latest/edge/ha-preview` and v1.18.6 from `latest/stable`)

As this is just a sandbox for me, I'm happy to try stuff if it helps you find a solution. Thanks!

**Comment by djjudas21** [comment]
For what it's worth, I tried setting up the same config on Ubuntu 20.04 and it did not throw the `openssl.cnf` error

**Comment by ktsakalozos** [comment]
Thank you for reporting this @djjudas21 and for your time in investigating.

Could you try installing the latest/edge revision: `sudo snap install microk8s --classic --channel=latest/edge`

**Comment by djjudas21** [comment]
Thanks @ktsakalozos. I have switched to `latest/edge` as you recommended:

```
[jonathan@kube02 ~]$ sudo snap refresh microk8s --classic --channel=latest/edge
microk8s (edge) v1.18.8 from Canonical✓ refreshed
```

There's no change in the behaviour when joining:

```
[jonathan@kube02 1630]$ microk8s join 192.168.0.41:25000/4a4e79d2e012b6b86c85c0ab9decf1b1
WARNING: can't open config file: /usr/lib/ssl/openssl.cnf
```

So here are the latest inspection reports:

[master-inspection-report-20200826_093512.tar.gz](https://github.com/ubuntu/microk8s/files/5128589/master-inspection-report-20200826_093512.tar.gz)
[worker-inspection-report-20200826_093521.tar.gz](https://github.com/ubuntu/microk8s/files/5128590/worker-inspection-report-20200826_093521.tar.gz)

**Comment by ktsakalozos** [comment]
@djjudas21 I am not able to reproduce the issue you report however I see who this may happen and I would like to do a bling fix to put some guards in place. Anything else you can tell me that would help me reproduce the issue would be great. What centos image did you use?

Could you please do a clean reinstall of MicroK8s from latest/edge?
```
snap remove microk8s
snap install microk8s --classic --channel=latest/edge
```
After doing so could you also please try a:
```
microk8s refresh-certs
```

**Comment by djjudas21** [comment]
@ktsakalozos Sorry for taking ages to respond. Last week this was still a problem for me on `latest/edge` but since `1.19` was released with HA support, clustering seems to work fine so I guess this has been fixed.
