### ISSUE TITLE
docker-proxy seg fault on CentOS 7.5.1804

### ISSUE THREAD

**Issue by double16** [ubuntu/microk8s#152]
docker-proxy seg faults causing containers needing the service to fail.

The easiest way to reproduce is to use `ldd docker-proxy`:

```shell
$ ldd /var/lib/snapd/snap/microk8s/237/usr/bin/docker-proxy
/usr/bin/ldd: line 116:  3529 Segmentation fault      LD_TRACE_LOADED_OBJECTS=1 LD_WARN= LD_BIND_NOW= LD_LIBRARY_VERSION=$verify_out LD_VERBOSE= "$@"
```

Other binaries in `usr/bin` do not seg fault on `ldd`.
[inspection-report-20181026_152226.tar.gz](https://github.com/ubuntu/microk8s/files/2520794/inspection-report-20181026_152226.tar.gz)

**Comment by double16** [comment]
I forgot to mention I have a Vagrant box exhibiting the issue: https://app.vagrantup.com/double16/boxes/linux-dev-workstation/versions/201810.1 . Warning: it's 6.29G.

**Comment by thomas-riccardi** [comment]
Same on ubuntu 18.04: 
```
kernel: docker-proxy[29666]: segfault at 400318 ip 00007f082ebc7949 sp 00007fff7c0e02a0 error 7 in ld-2.23.so[7f082ebc4000+26000]
```
This seems to be the same issue as #173
