### ISSUE TITLE
Cannot pull image from secured private registry

### ISSUE THREAD

**Issue by dajester2013** [ubuntu/microk8s#1526]
I added the registry to /var/snap/microk8s/current/args/containerd-template.toml as follows

```
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.my.domain"]
        endpoint = ["https://docker.my.domain"]
```

But it couldn't resolve.  So I changed the endpoint to use the IP.

```
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.my.domain"]
        endpoint = ["https://#.#.#.#"]
```

There was an error with the cert where the IP address was not listed in the SANs - so I re-issued the cert with the IP address in the SANs.  Went back to not resolving.  Keep in mind, I can successfully pull the image specified using `docker pull`.

```
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.my.domain"]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.my.domain".tls]
          insecure_skip_verify = true
```

I even tried specifying the CA certificate as the path on the host, no change.

What am I missing?

**Comment by balchua** [comment]
Hi what version of microk8s you are using?

**Comment by dajester2013** [comment]
Sorry, was in a hurry.

Running on Fedora 32, installed with snap, version 1.18.6.

This is the rendered toml:
https://gist.github.com/dajester2013/65343e838dae397e89620b356487e256

I can't remember the exact error from home, but it's something to the effect of  `failed to resolve docker.my.domain/my/app:latest`.

Its being served from a nexus 3 registry server.

**Comment by balchua** [comment]
I see that you customized the `containerd.toml` to use version 2.
I suppose that the registry is using a self signed cert.  You probably need to configure certs like described here. 
https://github.com/containerd/cri/blob/release/1.3/docs/registry.md

I also noticed that the path to `cni` is hardcoded to the snap version ex. `"/var/snap/microk8s/1551/opt/cni/bin"`, it tends to change when the snap is refreshed.  Better use `"/var/snap/microk8s/current/opt/cni/bin"` in this case.

**Comment by dajester2013** [comment]
Well, the only thing I personally modified was adding the last 4 lines.

Where would you recommend I place the CA cert in order for it to be picked
up properly?

**Comment by balchua** [comment]
Strange, the `containerd.toml.template` is based on version 1.  The template is then rendered to become `containerd.toml`, when you start the containerd.
Where we normally store the certs for kubernetes is `/var/snap/microk8s/current/certs` the advantage of putting it together with MicroK8s `$SNAP_DATA` files is that it gets backed up automatically when the snap is refreshed.

The usual way to change the containerd configuration is by editing the `containerd.toml.template` located in `/var/snap/microk8s/current/args`.

**Comment by dajester2013** [comment]
Sorry for the delay - was away last week.

So I placed the cert file in  the `current/certs` directory as noted above, and added the following lines to the template toml:
```
    [plugins."io.containerd.grpc.v1.cri".registry.configs]
      [plugins."io.containerd.grpc.v1.cri".registry.configs."docker.my.domain".tls]
        ca_file = "${SNAP_DATA}/certs/mycert.crt"
```
Then restarted microk8s using `microk8s stop; microk8s start`.

I tried to pull the image again, but it failed fast:
```
> microk8s ctr i pull docker.my.domain/my/app:latest
ctr: failed to resolve reference "docker.my.domain/my/app:latest": docker.my.domain/my/app:latest: not found
```

Now, something else I thought of - I have to use a custom DNS server (already configured on my host) to resolve the IP for the docker registry.  Is there anything special I have to do to get containerd to resolve using that DNS server? I've already followed https://microk8s.io/docs/addon-dns to point it to the right DNS server.

**Comment by balchua** [comment]
I assume that your docker and microk8s is on the same server. Which means the host (your machine) is able to resolve the dns.
I don't recall doing anything special as long as the host can resolve the name.  You can try the `dig` command from the host to see if its resolvable.

**Comment by dajester2013** [comment]
> I assume that your docker and microk8s is on the same server. 

That is correct

**Comment by dajester2013** [comment]
Found the debug flag.

```
> microk8s ctr --debug i pull docker.my.domain/my/app:latest
DEBU[0000] fetching                                      image="docker.my.domain/my/app:latest"
DEBU[0000] resolving                                     host=docker.my.domain
DEBU[0000] do request                                    host=docker.my.domain request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/v1.3.4 request.method=HEAD url="https://docker.my.domain/v2/my/app/manifests/latest"
DEBU[0000] fetch response received                       host=docker.my.domain response.header.cache-control="post-check=0, pre-check=0" response.header.content-length=1844 response.header.content-security-policy="sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation" response.header.content-type=text/html response.header.date="Tue, 08 Sep 2020 13:29:37 GMT" response.header.expires=0 response.header.pragma=no-cache response.header.server="Nexus/3.13.0-01 (OSS)" response.header.x-content-type-options=nosniff response.status="404 Not Found" url="https://docker.my.domain/v2/my/app/manifests/latest"
ctr: failed to resolve reference "docker.my.domain/my/app:latest": docker.my.domain/my/app:latest: not found
```

This is odd - everything resolves except the Nexus server is returning a 404 for the manifest URL, but when I copy/paste that URL into the browser, I get the expected manifest.

**Comment by balchua** [comment]
Did u try it with a newer version of nexus?

**Comment by dajester2013** [comment]
> Did u try it with a newer version of nexus?

Not yet - I'm researching it now, apparently it's an issue with the registry server not responding to HEAD requests, which I can verify outside of microk8s.  I'll keep you updated, but for now this issue can be closed.

**Comment by balchua** [comment]
Thanks @dajester2013

**Comment by dajester2013** [comment]
Updating to Nexus 3.27 corrected the issue, I was able to pull the image successfully.  Thank you!
