### ISSUE TITLE
update on Ubuntu 20.04.1 LTS  - snap install microk8s --channel=1.19 --classic

### ISSUE THREAD

**Issue by goblinrieur** [ubuntu/microk8s#1536]
whould install microk8s I check it is not already present : 

```
# microk8s instpect

La commande « microk8s » n'a pas été trouvée, mais peut être installée avec :

snap install microk8s

```

check version :+1: I should run `snap install microk8s --channel=1.19 --classic`

result is here : 
```
# snap install microk8s --channel=1.19 --classic
erreur : system does not fully support snapd: cannot mount squashfs image using "squashfs": mount:                                                                                           
          /tmp/sanity-mountpoint-174145105: type de syst�me de fichiers ��squashfs�� inconnu.
# locate squashfs | grep bin
/usr/bin/mksquashfs
/usr/bin/unsquashfs
#
```
so I have squashfs it is somewhere in install script the ubuntu 20.04.1LTS case using mksquashfs not set ?

**Comment by ktsakalozos** [comment]
Hi @goblinrieur 

Is this on a VM on any cloud?

This is a snapd issue, here is a related issue on the snapcraft forum https://forum.snapcraft.io/t/system-does-not-fully-support-snapd/14767/7

**Comment by goblinrieur** [comment]
It is a baremetal OVH server

**Comment by ktsakalozos** [comment]
Does this look relative: https://github.com/ubuntu/microk8s/issues/362 ?

What is your kernel version (`uname -a`)?

**Comment by goblinrieur** [comment]
here my uname : 
`Linux squadlabo 4.9.87-xxxx-std-ipv6-64 #1 SMP Tue Mar 13 18:41:47 CET 2018 x86_64 x86_64 x86_64 GNU/Linux`

it somehow looks like [#362](https://github.com/ubuntu/microk8s/issues/362) I did similarly diagnostic tests in facts without results

**Comment by goblinrieur** [comment]
I tried update but still no fix included.

**Comment by ktsakalozos** [comment]
This is not the kernel Ubuntu 20.04 LTS ships with [1]. Canonical puts a lot of effort in patching and testing the kernels used in Ubuntu. Taking the kernel out of the distribution may cause such bugs and hurt its users. You should talk to OVH to see what are your options in getting the original kernel and maybe asking if there are other changes to the distribution you should be aware of. I am not even sure if this can be called "Ubuntu 20.04.1LTS" anymore. 

[1] https://ubuntu.com/blog/ubuntu-kernel-5-4-whats-new-with-ubuntu-20-04-lts

**Comment by goblinrieur** [comment]
OK thanks I going to both : 
- Ask OVH about that (_I think you're right they should have given a personalized kernel to allow virsh and other stuff_)
- Use a virtual machine for microk8s while waiting for the next available server I will manage.

So I will close this incident here.
