### ISSUE TITLE
How is it possible to change/enhance the default configuration files for the standard Nginx ingress?

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [ubuntu/microk8s#1539]
This is not a true issue but a question that aims to overcome a problem.

I am configuring my microservices/docker application (developed locally using docker and Envoy as reverse proxy) in MicroK8s. The applications are written in .net core 2.1 and do use IdentityServer4 as an OAuth2 provider (it is a docker service among the other services).

The services configured in my local environment (with Envoy as reverse proxy) are working fine; configured in MicroK8s they works, but the authentication give a problem when the auth service invoke (through a POST call) the original web application:

POST requests are not supported / 502 Bad Gateway / openresty/1.15.8.1

Searching on the internet i didn't find really anything specifically related to this (too much) generic error; the closer one was this post:

https://medium.com/@mshanak/solve-nginx-error-signin-oidc-502-bad-gateway-dotnet-core-and-identity-serve-bc27920b42d5

The author (Mahdi Shanak) suggest to modify the config files of nginx to increase the size of the proxy buffers. The files touched are "/etc/nginx/nginx.conf" and "/etc/nginx/conf.d/default.conf".

But here is the problem: if i want to try this solution i have to modify the files.... but i used the default ingress implementation (enabling the "ingress" module) and i don't see any easy way to change the default configuration files for nginx nor any documentation on how to do so.

Use the default modules of microk8s is very handy since i have a full environment running in few minutes, but i also need to go a little further in the configuration... Can you give me some advice on how i can proceed?

Thanks in advance.

**Comment by balchua** [comment]
Many of the nginx configuration can be added to the `Ingress` resource as annotations.

I don't think there is a need to actually change the nginx ingress controller.

Here's the link to all nginx ingress annotations.
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/

Not particularly sure the actual mapping between the annotation and nginx conf though.

**Comment by balchua** [comment]
This might also help you configure nginx ingress.

https://github.com/dotnet/aspnetcore/issues/19293

**Comment by LeonSebastianCoimbra** [comment]
Hi @balchua and thanks for the response.

After further search and tests, i found the following page:

https://www.b2-4ac.com/nginx-ingress-controller-errors/

(it is a confirm of the previous thread mentioned in my original comment, and the proof that some additional configuration is needed)


After that i added some annotation to the ingress, in particular the following:

    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-body-size: 8m

They can overcome some of the common problems specified in the previous link and in particular some of my problems (in fact now i have different problems.... but not the same as before!!).

I think that i will continue searching for the correct configurations.


Still, i think that having to add multiple times the same annotations to different ingress definitions (and in a micro-service environment i can have a lot of different ingress) is still a lot of effort... being able to configure a standard behavior for the whole cluster seems to me something reasonably.


Thanks for your tips, especially for the advice about how to change the ConfigMap... i was still searching around the net the recommended way to do it in microk8s.

**Comment by balchua** [comment]
Different workloads will always require different configurations. 

I think the way to configure nginx ingress controller is to edit the ConfigMap.  Give it a try and let us know how it goes. 👍

**Comment by LeonSebastianCoimbra** [comment]
I will, thanks again!!

**Comment by LeonSebastianCoimbra** [comment]
I can confirm that both approaches work:

- By specifying the values as annotation of the ingress:
`
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
`
- By creating a patch to the default nginx configmap:
`
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-microk8s-conf
  namespace: ingress
data:
  proxy-buffering: "on"
  proxy-buffer-size: 16k
  proxy-body-size: 8m
  large-client-header-buffers: "4 16k"
  use-forwarded-headers: "true"

The patch is applied with the command:

kubectl -n ingress patch configmap nginx-load-balancer-microk8s-conf --patch "$(cat nginx-config-map-patch.yaml)"
`

If there are no obvious drawbacks (performance issues for instance) I will use the second way, as it makes the yaml file cleaner and easier to maintain.


Thanks again for the help.
