### ISSUE TITLE
Smooth upgrade addons

### ISSUE THREAD

**Issue by An0nymous0** [ubuntu/microk8s#1542]
Such as istio

This coupling is depressing

**Comment by ktsakalozos** [comment]
Hi @An0nymous0 can you please elaborate on this request?

In general if you follow a specific track by installing MicroK8s for a specific channel, eg `sudo snap install microk8s --classic --channel=1.19` the addons do not get upgraded.

**Comment by An0nymous0** [comment]
Recently I am trying to build a microk8s cluster with Raspberry Pi, but the maintenance method of the components makes me puzzled.

1. sudo snap install microk8s --classic --channel=1.18/stable

2. microk8s enable dns istio

3. microk8s.istioctl version

4. sudo snap refresh microk8s --classic --channel=1.19/beta

5. microk8s.istioctl version

istio related components have not been upgraded


If it is k8s, I will upgrade istio version or k8s version separately, and there is no strong coupling. What should I do if I change to microk8s? After installation, istio can never upgrade smoothly?

Similar problems: https://discuss.kubernetes.io/t/upgrade-istio-from-1-34-to-1-54-on-microk8s/11027/5
