### ISSUE TITLE
How is it possible to access Grafana in the same way i can access the Kubernetes Dashboard?

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [ubuntu/microk8s#1543]
Sorry to bother you all with this question, but i didn't find an answer suitable to my case in internet.

To access grafana the documentation (https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#4-accessing-the-kubernetes-and-grafana-dashboards) says to do a "kubectl cluster-info" and then use the corresponding link.

But the link is related to 127.0.0.1... so what if i configured microk8s inside an EC2 instance on the AWS cloud and i can only reach it through the internet (because i don't want to configure also a vnc-like service?).

One possibility is to do the same way i did for the kubernetes dashboard: use port-forward (on a protected port that only i can access) like this:

**kubectl port-forward -n=kube-system service/monitoring-grafana 9001:80 --address 0.0.0.0 &disown**

Unfortunately this lead only to a standard html page with the following content:

  {{alert.title}}
      Docs
      Support Plans
      Community
      Grafana vv4.4.3 (commit: unknown-dev)

What am i doing wrong?

**Comment by ktsakalozos** [comment]
Hi @LeonSebastianCoimbra this seems like the issue discussed in https://github.com/grafana/grafana/issues/12933

**Comment by LeonSebastianCoimbra** [comment]
Hi @ktsakalozos , yes, it seems the same problem, except that the user @adamdecaf  builded everything from scratch, while i am using the modules coming with microk8s... so i was expecting that all worked automagically...

Here is the output from microk8s:

  microk8s status
  microk8s is running
  addons:
    dashboard: enabled
    dns: enabled
    ingress: enabled
    rbac: enabled
    storage: enabled
    cilium: disabled
    fluentd: disabled
    gpu: disabled
    helm: disabled
    helm3: disabled
    istio: disabled
    jaeger: disabled
    knative: disabled
    kubeflow: disabled
    linkerd: disabled
    metallb: disabled
    metrics-server: disabled
    prometheus: disabled
    registry: disabled

    kubectl get all -n kube-system
    NAME                                                  READY   STATUS    RESTARTS   AGE
    pod/coredns-588fd544bf-jg57d                          1/1     Running   2          3d18h
    pod/dashboard-metrics-scraper-db65b9c6f-v6df5         1/1     Running   2          3d18h
    pod/heapster-v1.5.2-58fdbb6f4d-6w9kt                  4/4     Running   8          3d18h
    pod/hostpath-provisioner-75fdc8fccd-j5x78             1/1     Running   2          3d18h
    pod/kubernetes-dashboard-67765b55f5-45hxl             1/1     Running   2          3d18h
    pod/monitoring-influxdb-grafana-v4-6dc675bf8c-sj7nh   2/2     Running   4          3d18h
    
    NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
    service/dashboard-metrics-scraper   ClusterIP   10.152.183.139   <none>        8000/TCP                 3d18h
    service/heapster                    ClusterIP   10.152.183.94    <none>        80/TCP                   3d18h
    service/kube-dns                    ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   3d18h
    service/kubernetes-dashboard        ClusterIP   10.152.183.18    <none>        443/TCP                  3d18h
    service/monitoring-grafana          ClusterIP   10.152.183.170   <none>        80/TCP                   3d18h
    service/monitoring-influxdb         ClusterIP   10.152.183.238   <none>        8083/TCP,8086/TCP        3d18h
    
    NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
    deployment.apps/coredns                          1/1     1            1           3d18h
    deployment.apps/dashboard-metrics-scraper        1/1     1            1           3d18h
    deployment.apps/heapster-v1.5.2                  1/1     1            1           3d18h
    deployment.apps/hostpath-provisioner             1/1     1            1           3d18h
    deployment.apps/kubernetes-dashboard             1/1     1            1           3d18h
    deployment.apps/monitoring-influxdb-grafana-v4   1/1     1            1           3d18h
    
    NAME                                                        DESIRED   CURRENT   READY   AGE
    replicaset.apps/coredns-588fd544bf                          1         1         1       3d18h
    replicaset.apps/dashboard-metrics-scraper-db65b9c6f         1         1         1       3d18h
    replicaset.apps/heapster-v1.5.2-58fdbb6f4d                  1         1         1       3d18h
    replicaset.apps/hostpath-provisioner-75fdc8fccd             1         1         1       3d18h
    replicaset.apps/kubernetes-dashboard-67765b55f5             1         1         1       3d18h
    replicaset.apps/monitoring-influxdb-grafana-v4-6dc675bf8c   1         1         1       3d18h

**Comment by balchua** [comment]
@LeonSebastianCoimbra i believe grafana port is 3000 not 80

**Comment by LeonSebastianCoimbra** [comment]
@balchua As configured by default in microk8s the service monitoring-grafana expose the port 80 (mapped by the service to the port 3000 on the pod as you say).

The problem is not that i can not reach (through the port-forward directive) the service (and doing so the grafana server), it is that the resulting page refers to the internal urls....

The html returned has, in fact, the following types of links:

    <link href='/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy/public/css/fonts.min.css' rel='stylesheet' type='text/css'>

As you can see, they refers to absolute urls on the form "/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy/...", which are the same reported in the documentation (https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#4-accessing-the-kubernetes-and-grafana-dashboards) and retrieved through a "kubectl cluster-info" call. 

This work locally, but it will not works outside the local machine using a "port-forward" directive.

**Comment by balchua** [comment]
I see. Normally i use an ingress if i need to access it beyond my localhost.

**Comment by LeonSebastianCoimbra** [comment]
I also have an ingress, but i want to reserve it for official pages. 
For other "hidden" services i prefer to use a different approach (like port-forward)... it is simple enough to be disabled or enabled on demand and using unusual ports and firewalls rules i can make so i am the only one to access it.

**Comment by balchua** [comment]
Oh you're trying to access the grafana that came along with the kubernetes dashboard.
That is deprecated.  It came with heapster (obsolete) and influxdb.  Grafana version is also rather old.
In 1.19, kubernetes dashboard only comes with the dashboard and the scraper.
I suggest to use the grafana that comes with `prometheus` addon. The service port is `3000` not `80`
And if you want to be able to use `kubectl top` command, enable the metrics-server.

**Comment by LeonSebastianCoimbra** [comment]
Ah... thanks, i wasn't aware of the deprecation and since i found a grafana already activated i though that it was ok to use it.

I will activate the prometheous addon then, thanks for the tip.

**Comment by balchua** [comment]
@ktsakalozos how to update this documentation? https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#4-accessing-the-kubernetes-and-grafana-dashboards

We removed the grafana that came with the dashboard.

**Comment by ktsakalozos** [comment]
Thank you for spotting that @balchua @LeonSebastianCoimbra . I just updated the respective tutorial to not mention Grafana.
