### ISSUE TITLE
error: unable to forward port because pod is not running. Current status=Pending

### ISSUE THREAD

**Issue by geewynn** [ubuntu/microk8s#1547]
Hello, I started an ubuntu 18.04 virtual machine on google cloud platform with required vCPU, memory and disk storage, Once the machine was up, I ssh into it and installed microk8s.
Then I deployed kubeflow using the link below

https://v1-0-branch.kubeflow.org/docs/started/k8s/kfctl-istio-dex/#expose-kubeflow

Now I am trying to access kubeflow with this instruction
`kubectl port-forward svc/istio-ingressgateway -n istio-system 8080:80
`
But it returns this error
`error: unable to forward port because pod is not running. Current status=Pending`

Tarball from `microk8s inspect`
[inspection-report-20200908_182514.tar.gz](https://github.com/ubuntu/microk8s/files/5190362/inspection-report-20200908_182514.tar.gz)

microk8s v1.18
kfctl - https://github.com/kubeflow/kfctl/releases/download/v1.0.2/kfctl_v1.0.2-0-ga476281_linux.tar.gz
manifest - https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_istio_dex.v1.0.2.yaml

**Comment by knkski** [comment]
It looks like the pod is still booting up:

    istio-system      pod/istio-ingressgateway-c79f9f6f-qj7z6                            0/1     ContainerCreating   0          9m50s

Given that there's no restarts on that pod, I would assume that it's taking a long time to boot up, as opposed to running into any errors. Are you able to wait for the pod(s) to finish booting up with `microk8s kubectl wait -n istio-system --for=condition=ready pod --all` before attempting the port forward?

If the pod never finishes starting up, can you run `microk8s kubectl describe -n istio-system` on the ingress-gateway `Pod` and `Deployment` resources and post the output here?

**Comment by geewynn** [comment]
Running this code
`microk8s kubectl wait -n istio-system --for=condition=ready pod --all
`
the output.
```
pod/authservice-0 condition met
pod/istio-citadel-7f66ddfcfb-fr5xq condition met
pod/istio-galley-7976dd55cd-7md2k condition met
pod/istio-nodeagent-dnmfp condition met
pod/istio-sidecar-injector-56b6997f7d-kprdj condition met
pod/prometheus-65fdcbc857-smr9p condition met
timed out waiting for the condition on pods/cluster-local-gateway-84bb595449-8sstc
timed out waiting for the condition on pods/istio-ingressgateway-c79f9f6f-qj7z6
timed out waiting for the condition on pods/istio-pilot-7bd96d69d9-wdpt8
timed out waiting for the condition on pods/istio-policy-66b5d9887c-j6pkf
timed out waiting for the condition on pods/istio-security-post-install-release-1.3-latest-daily-tt6b9
timed out waiting for the condition on pods/istio-telemetry-856f7bcff4-4262c
```
It timed out on the pods taking time to run.

**Comment by ktsakalozos** [comment]
Hi @geewynn, does this https://github.com/kubeflow/manifests/issues/959 look related?

**Comment by DavidSpek** [comment]
@ktsakalozos 
I was facing a somewhat related issue to the one you linked when trying to deploy kubeflow on Charmed Kubernetes https://github.com/juju-solutions/bundle-kubeflow/issues/240#issuecomment-692758081.

**Comment by shahzaibekram** [comment]
I have the same problem with my microk8s pods and I have done all solution but still pods not running

NAMESPACE     NAME                                         READY   STATUS              RESTARTS   AGE
kube-system   metrics-server-8bbfb4bdb-q9ldh               0/1     ContainerCreating   0          29m
kube-system   kubernetes-dashboard-7ffd448895-qm44w        0/1     ContainerCreating   0          28m
kube-system   dashboard-metrics-scraper-6c4568dc68-qrcjv   0/1     ContainerCreating   0          28m
kube-system   coredns-86f78bb79c-v7tgt                     0/1     ContainerCreating   0          31m
kube-system   calico-kube-controllers-847c8c99d-g59cp      0/1     ContainerCreating   0          32m
kube-system   calico-node-xph9f                            0/1     CrashLoopBackOff    10         32m

**Comment by DavidSpek** [comment]
@shahzaibekram Did you use `microk8s enable kubeflow` by any chance? Because for issues related to that you should be over at https://github.com/juju-solutions/bundle-kubeflow/issues

**Comment by shahzaibekram** [comment]
My pod log what can I do to solve this problem

<pre>Name:           kubernetes-dashboard-7ffd448895-qm44w
Namespace:      kube-system
Priority:       0
Node:           shah/192.168.0.104
Start Time:     Thu, 28 Jan 2021 17:54:37 +0500
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=7ffd448895
Annotations:    &lt;none&gt;
Status:         Pending
IP:             
IPs:            &lt;none&gt;
Controlled By:  ReplicaSet/kubernetes-dashboard-7ffd448895
Containers:
  kubernetes-dashboard:
    Container ID:  
    Image:         kubernetesui/dashboard:v2.0.0
    Image ID:      
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --auto-generate-certificates
      --namespace=kube-system
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    &lt;none&gt;
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-m4mk2 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:       EmptyDir (a temporary directory that shares a pod&apos;s lifetime)
    Medium:     
    SizeLimit:  &lt;unset&gt;
  kubernetes-dashboard-token-m4mk2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-m4mk2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  &lt;none&gt;
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               30m                  default-scheduler  Successfully assigned kube-system/kubernetes-dashboard-7ffd448895-qm44w to shah
  Warning  FailedCreatePodSandBox  30m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;66da87b9899130a5eddd9f751a394ac529148fd0de3b8f5d01cdcc30688ffdd9&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  30m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;9cd3282f69c89187a5c1cde109459aab287a0982cb35c42ec85273a82d971cc3&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  30m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;bae06850c830fcb711fcdf312be2ba220ca8e5e384bce747d2173343ecc0bb32&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  30m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;b93f01f89a3aaea5d30ea25ee82debfccc1bd3ad7f0857fd7399bcc5c074935f&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  29m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;ac9f00ee49b38b6471ca48b8e3e6f27c5725faaacebaef508ed50e601f2db2d8&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  29m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;6bdcaa77db2c43bc59cd2c1e818e681ecf1543c48fdff5784e88c092f647483e&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  29m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;6190c3c539440ec1200204fb2f5c69e8ca2a4e52fe8456ab3ddc2b6bc693c77f&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  29m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;2c5b173879831db79ccf573506a28c57acd47514012a7e743240fee1c8b1a12f&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  29m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;7c8ec308c522f2688445509ad8b157b67953a224e40d5ee3dfe71ced8349acdd&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
  Warning  FailedCreatePodSandBox  49s (x126 over 28m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox &quot;31868e97def1e40694d30f8f481cbfe99abf2c0b0fa5032ab5369e33ccf81b4c&quot;: error getting ClusterInformation: resource does not exist: ClusterInformation(default) with error: clusterinformations.crd.projectcalico.org &quot;default&quot; not found
</pre>

**Comment by shahzaibekram** [comment]
> @shahzaibekram Did you use `microk8s enable kubeflow` by any chance? Because for issues related to that you should be over at https://github.com/juju-solutions/bundle-kubeflow/issues

Yes I used but didn't work

**Comment by knkski** [comment]
@shahzaibekram: can you open a new issue and ping @ktsakalozos on it? The `kube-system   calico-node-xph9f                            0/1     CrashLoopBackOff    10         32m` line makes it look like a networking issue.

**Comment by ORUNSOLU** [comment]
(Ubuntu 22.04.3 LTS) I also ran into this issue, and in my case, it seemed Jenkins was running locally on the same port. I had to stop Jenkins to work around it. Another workaround was using a different port number.
