### ISSUE TITLE
kube-dns, hostpath-provisioner, and dashboard crashing after upgrade to 1.19

### ISSUE THREAD

**Issue by eric-pfi** [ubuntu/microk8s#1548]
At some point this morning, all workloads on the microk8s cluster became inaccessible. While trying to diagnose, noticed that three services kept running briefly and going into crashLoopBackoff (the three services mentioned in the title). Example output of kubectl:

````
NAME                                              READY   STATUS             RESTARTS   AGE
dashboard-metrics-scraper-566cddb686-pdl6c        1/1     Running            162        296d
heapster-v1.5.2-5c58f64f8b-245k4                  4/4     Running            1599       296d
hostpath-provisioner-6d744c4f7c-2j52g             0/1     CrashLoopBackOff   198        458d
kube-dns-6bfbdd666c-xp2xf                         2/3     Running            742        439d
kubernetes-dashboard-cc76d5565-9728m              0/1     Error              111        24d
monitoring-influxdb-grafana-v4-6d599df6bf-6mtnn   2/2     Running            132        296d
tiller-deploy-5dc46c877-7hmhp                     1/1     Running            238        434d
traefik-ingress-f8b7f948-fk7js                    1/1     Running            66         296d
````

and

````
ericw@wsv-dev:~$ kubectl get pods --namespace=kube-system
NAME                                              READY   STATUS    RESTARTS   AGE
dashboard-metrics-scraper-566cddb686-pdl6c        1/1     Running   162        296d
heapster-v1.5.2-5c58f64f8b-245k4                  4/4     Running   1599       296d
hostpath-provisioner-6d744c4f7c-2j52g             1/1     Running   199        458d
kube-dns-6bfbdd666c-xp2xf                         2/3     Error     742        439d
kubernetes-dashboard-cc76d5565-9728m              1/1     Running   112        24d
monitoring-influxdb-grafana-v4-6d599df6bf-6mtnn   2/2     Running   132        296d
tiller-deploy-5dc46c877-7hmhp                     1/1     Running   238        434d
traefik-ingress-f8b7f948-fk7js                    1/1     Running   66         296d
````

I needed the cluster running to work on a bug in our application, so after running microk8s stop and start, as well as a restart of the virtual machine, I downgraded to 18.6:

````
ericw@wsv-dev:~$ sudo snap revert --classic microk8s
microk8s reverted to v1.18.6
````

Everything is back up now.

Attaching two inspection reports. The earlier one is when I was having the problem, the later one is while it is running successfully with 1.18.6.
[inspection-report-20200908_190517.tar.gz](https://github.com/ubuntu/microk8s/files/5190668/inspection-report-20200908_190517.tar.gz)
[inspection-report-20200908_194151.tar.gz](https://github.com/ubuntu/microk8s/files/5190670/inspection-report-20200908_194151.tar.gz)

**Comment by ollie-nye** [comment]
Having the same issue here, no pods could access 10.152.183.1:443 (api server).
Kubedns logs printed `1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...` repeatedly, before crashing with `1 dns.go:167] Timeout waiting for initialization`

**Comment by balchua** [comment]
@eric-pfi i can see that you have a long lasting cluster.  It is recommended to follow a specific channel for example `1.18/stable`.
Check this out https://microk8s.io/docs/setting-snap-channel
Moving from one version of kube to another can result to broken cluster.  If it is a long lasting cluster, it is best to stick to a specific channel.

Back to the issue.

The cluster is still configured to use `kubenet` based on the `kubelet` args.

In the network logs of the upgraded cluster, the iptables were not created properly.  Atleast it doesn't seem to contain the same one as the working cluster.
@ktsakalozos thoughts?

**Comment by ktsakalozos** [comment]
@eric-pfi as @balchua mentioned deploying MicroK8s from the latest/stable channel is not recommended for long lasting deployments because there will be breaking changes either from upstream Kubernetes or from MicroK8s. The revert you did is only temporary. You would better do a refresh on `1.18/stable` with `sudo snap refresh microk8s --channel=1.18/stable`. I would also recommend you do a fresh installation, as there are a lot of improvements you do not take advantage of eg, new CNI, HA and clustering capable setup, security fixes.

I could not exactly pinpoint the reason why this deployment broke. One reason could be the removal of the basic-auth authorization that forced us to rewrite the kubeconfig files used by all services.

@ollie-nye please attach the `microk8s inspect` tarball. It is hard to say if the issue you see is the same reported by @eric-pfi .
