### ISSUE TITLE
Feature request: microk8s.status

### ISSUE THREAD

**Issue by AdamIsrael** [ubuntu/microk8s#155]
It would be nice if there were an easier way to query k8s to find out what plugins are enabled. Something like `microk8s.enabled --list` could expose the list in a way that's consistent with the current command, I think.

You can poke around `kubectl get all -n kube-system` but it's not a 1:1 map between what we enable explicitly and what's on by default.

For my use-case, I want to know what addons are enabled so that I can make an operational decision. In other words, if `dns` is already enabled, I don't want to enable it a second time because it goes through the process (applying manifest/creating services/etc and restarting kubelet.

**Comment by ktsakalozos** [comment]
If I may add, a machine friendly response output would also help in integration with external systems and automating tasks (eg `microk8s.status --format yaml`).

A rest server to expose all management ops paired with a good looking UI would appeal to both integrators and users new to Kubernetes.
