### ISSUE TITLE
sudo access "jovyan" password required to install GDAL 

### ISSUE THREAD

**Issue by ajinkya933** [ubuntu/microk8s#1558]
I want to install gdal on Kubeflow but when I do:

```
!pip install --user gdal==2.4.4
```

I get error:

```
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config': 'gdal-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
**Question:**

How install GDAL ?, I need sudo access to terminal to install gdal, for example:
```
sudo apt-get install libgdal-dev
```

I always get asked to enter a password, Whats this password. How do I install gdal this way ?
```
$ sudo apt-get install libgdal-dev
[sudo] password for jovyan:
```

**Comment by balchua** [comment]
@ajinkya933 you will need to ask your administrator to add the user `joyval` to the `sudoers`.

**Comment by ajinkya933** [comment]
@balchua I installed microk8s on ubuntu myself. This makes me administrator.  How do I add user joyval to the sudoers ?

**Comment by balchua** [comment]
Check this out. https://www.google.com/amp/s/phpraxis.wordpress.com/2016/09/27/enable-sudo-without-password-in-ubuntudebian/amp/

**Comment by ajinkya933** [comment]
No, even to do this (https://www.google.com/amp/s/phpraxis.wordpress.com/2016/09/27/enable-sudo-without-password-in-ubuntudebian/amp/) I need access to "sudo"

**Comment by balchua** [comment]
I am sorry but I don't know how you setup your machine. If you have root access then become root and you can easily add your user to sudoers.
If your user is not able to use sudo by supplying your user `jovyan`, there is nothing much i can do.
