### ISSUE TITLE
Debian 9 installation issue

### ISSUE THREAD

**Issue by fibergames** [ubuntu/microk8s#156]
Hello everyone? 
I looked through the issues and even closed ones.
Installation is failing on debian and I get seems to find the issue here:

```
:~# snap install microk8s --classic
error: cannot perform the following tasks:
- Run configure hook of "microk8s" snap if present (run hook "configure":
-----
+ '[' '!' -d /var/snap/microk8s/238/certs ']'
+ grep -e '\-\-client-ca-file=${SNAP}/certs/ca.crt' /var/snap/microk8s/238/args/kube-apiserver
grep: /var/snap/microk8s/238/args/kube-apiserver: No such file or directory
+ grep requestheader-client-ca-file /var/snap/microk8s/238/args/kube-apiserver
grep: /var/snap/microk8s/238/args/kube-apiserver: No such file or directory
+ echo 'Patching requestheader-client-ca-file argument'
Patching requestheader-client-ca-file argument
+ echo ''
/snap/microk8s/238/meta/hooks/configure: line 29: /var/snap/microk8s/238/args/kube-apiserver: No such file or directory
-----)
```

Any ideeas on this matter? 
Installed without issues under any Ubuntu.

Thanks.

**Comment by ktsakalozos** [comment]
Hi @fibergames,

Thank you for reporting this issue. I confirmed the problem and forwarded it to the right team of the software stack https://forum.snapcraft.io/t/snapd-not-apt-installing-properly-on-debian-9/8240/2 .

In short, snapd in debian 9 is outdated. It is in our plans to update the debian package. There is an easy workaround for getting microk8s, snap install core and then microk8s
```
sudo snap install core
sudo snap install microk8s --classic
```
The reason why the above works is that the installation of core will force snapd to re-execute a newer version of itself.

Is this an acceptable solution for your case?

Thank you for using microk8s.

**Comment by fibergames** [comment]
Thanks, worked like a charm:
```
:~# snap install core
core 16-2.35.5 from 'canonical' installed
:~# snap install microk8s --classic
microk8s v1.12.0 from Canonical✓ installed
:~#
```
Have a great day!
