### ISSUE TITLE
microk8s ingress stops to create resources

### ISSUE THREAD

**Issue by jenisov** [ubuntu/microk8s#1564]
cannot create nor update any existing Ingress resource, getting error:
`
Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/extensions/v1beta1/ingresses?timeout=30s": service "ingress-nginx-controller-admission" not found`

nginx pod and previously created resources however work well...

[inspection-report-20200914_191406.tar.gz](https://github.com/ubuntu/microk8s/files/5220487/inspection-report-20200914_191406.tar.gz)

**Comment by jenisov** [comment]
found a workaround:

` kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission -n ingress`

**Comment by balchua** [comment]
@jenisov i noticed that you have a long lasting install.  If thats the case, we recommend that you follow a certain track.  For example `1.19/stable` or `1.18/stable`.

More often than not, new versions tends to have some breaking changes either from upstream kubernetes or from MicroK8s.

More information [here](https://microk8s.io/docs/setting-snap-channel)

**Comment by jenisov** [comment]
Yes, I understand the risk and want to track latest updates for the stable branch. 

My concern was no information how to fix this, even disable/enable ingress add-on doesn't clean webhooks properly.

**Comment by balchua** [comment]
I am checking the ingress addon that came with microk8s, i dont see where we add the validating webhook.  I think this is an optional feature.

**Comment by jenisov** [comment]
I guess the webhook was the part of old nginx-ingress installation, there are some complains not related to microk8s: https://stackoverflow.com/questions/61616203/nginx-ingress-controller-failed-calling-webhook/61681896#61681896

**Comment by balchua** [comment]
Thanks @jenisov .  Will close the issue now.  At anytime, feel free to open an issue when having trouble with MicroK8s.
Thanks again for using MicroK8s.
