### ISSUE TITLE
Microk8s ha stop working after remove and add nodes several times

### ISSUE THREAD

**Issue by enderson-pan** [ubuntu/microk8s#1565]
microk8s inspect file:
[inspection-report-20200915_105837.tar.gz](https://github.com/ubuntu/microk8s/files/5222233/inspection-report-20200915_105837.tar.gz)

I have 5 machines, then I try to add nodes, remove nodes, and add the same nodes again to test the ha.
After several times, microk8s cluster failed. 

```
 microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```
Then the inspect file is attached.

**Comment by ktsakalozos** [comment]
Hi @enderson-pan, I am interested in a process to reproduce the issue you saw. How are you removing the nodes? Are you removing more than one simultaneously? Do you allow any time between consecutive removals/additions? Is this a graceful removal ie call `mirok8s.leave` on the departing node and then `microk8s.remove-node` on any of the cluster's nodes? Or is it a crash emulation ie poweroff one of the nodes and then `microk8s.remove-node --force` on any of the clustr's nodes?

Overall there is a certain amount of time (some seconds) needed for leadership election in case a node departs. There is also the requirement to have quorum (more than 3 nodes) to maintain HA. Finally one requirement not to be forgotten is that a node has to be removed from the cluster gracefully (`microk8s leave` and `microk8s remove-node`) or not gracefully (`microk8s remove-node --force`) before it can be re-added.

cc @freeekanayaka in case he has a better understanding what the `microk8s.daemon-apiserver[24923]: Error: context deadline exceeded` is.

**Comment by freeekanayaka** [comment]
The `context deadline exceeded` error is a timeout. But with that line only is not possible to know where it happens.

Note that in order to test HA, generally you don't need to remove and add nodes. HA is supposed to be tolerance against failure of nodes that are **currently part of the cluster**, for example the cluster survives a node being shutting down for maintenance. To test HA you should do something like, reboot a node (or restart microk8s on it) and check that the cluster is still available during that downtime (e.g. you can run `kubectl` from nodes that are still online).

**Comment by enderson-pan** [comment]
@ktsakalozos Hi, I just do as the offical doc, to add and remove node on worker nodes run `microk8s leav`, and then run `microk8s remove-node` on the api-server node.

**Comment by bbarclay** [comment]
sudo microk8s.remove-node --force makes it startup atgain without having to snap remove it. Not sure what is causing this though.

**Comment by bbarclay** [comment]
One thing is to try and run join with and without sudo. There is also another command. sudo usermod -a -G microk8s $USER
 1913  sudo chown -f -R $USER ~/.kube. using those. Logging out and logging back into your terminal. Plus the last one. Resetting your certs. sudo microk8s refresh-certs.  A combination of these random things seem to get it to boot for me, eventually.
