### ISSUE TITLE
dashboard can't access

### ISSUE THREAD

**Issue by jet10000** [ubuntu/microk8s#1569]
ubuntu desktop 20.04

I follow this docs https://microk8s.io/docs/addon-dashboard

but I can't access dashboard.

```
microk8s dashboard-proxy
```

**Comment by FixedCroissant** [comment]
Having the same issue here running Ubuntu 20.04 installed yesterday; from [this guide](https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#1-overview).... the kubernetes-dashboard pod continually gets evicted and never actually fully runs. I certainly may be missing a step.

**Comment by jet10000** [comment]
It's worked for me.

I forgot disconnect VPN.

**Comment by ktsakalozos** [comment]
@FixedCroissant if the pod gets evicted there must be some resource shortage? What does `microk8s kubectl describe no` show?
