### ISSUE TITLE
Add configuration options (size, location) to microk8s.enable registry.

### ISSUE THREAD

**Issue by carmine** [ubuntu/microk8s#157]
At present, the registry is constrained to 20Gb and to a specific path in the local environment. It'd be great if both were configurable. The use case:

- Using the registry in anger, you'll exceed 20GB quickly, particularly for ML images
- If microk8s/registry is running in a VM that is ephemeral (may be destroyed), it'd be great to pass in a mounted location so that the registry contents will survive from vm to vm.

**Comment by tvansteenburgh** [comment]
@ktsakalozos What are your thoughts on this?

**Comment by ktsakalozos** [comment]
There have been some private conversations with @carmine on this topic.

We have two asks here. First how to add parameters in our addons. Second how to reuse storage volumes.

I do not have a good and clean answer for the second ask. I am not sure if we should handle this with the host-provisioner or follow the upstream solutions.

Here are my thoughts on adding parameters to addons. Imagine that you have a properties ini file that would look like this:

```
[registry]
size=20GB
claim=bar

[storage]
dir=${snap_data}/default-storage
```
Could we change the default registry properties with something like:
```
microk8s.configure registry --size=30GB
microk8s.enable registry
```

or 

```
microk8s.create myregistryconf --from registry
microk8s.configure myregistryconf --size=30GB
```

That would add a
```
[myregistryconf]
size=30GB
claim=bar
```

and then do 

```
microk8s.enable registry --with myregistryconf
```

This apprach would be generic for all addons we have.

**Comment by carmine** [comment]
I think the ability to provide a conf would be great, but also the ability to specify key settings in the enable. Downside to this suggestion is that the "key settings" list could grow. 

If this is more of a storage issue .. then I would start with storage. Something like:

microk8s.enable storage --name class_name --size [X] --location /some/path --default true

From there, I could then do something similar with registry, specifying the storage class and pvc size.
