### ISSUE TITLE
Kubelet seems to be down after multiple snap disable / enable sessions

### ISSUE THREAD

**Issue by geoand** [ubuntu/microk8s#158]
Furthermore, the registry seems to not work properly - when I push to it I get something like: 

```
Put http://localhost:32000/v1/repositories/my-busybox/: EOF
```

The associated report can be found attached.
[inspection-report-20181101_135304.tar.gz](https://github.com/ubuntu/microk8s/files/2538405/inspection-report-20181101_135304.tar.gz)

**Comment by ikarlashov** [comment]
Getting the simillar error message. Registry stops working sporadically.
