### ISSUE TITLE
Microk8s snap fails to install on upgraded Ubuntu 20.10 machine 

### ISSUE THREAD

**Issue by barryprice** [ubuntu/microk8s#1586]
Hi,

Install of the snap fails on a 20.10 (prerelease) amd64 machine, recently upgraded from 20.04:

https://paste.ubuntu.com/p/CwjrxxqJyj/

Since the snap fails to install, there's unfortunately no way to run `microk8s inspect`.

This is a ZFS system, in case that makes a difference.

Here's a full dump of what journalctl sees during the install - note that while I usually run UFW, it's disabled for the course of this attempted install, to rule out firewall issues[1]:

https://paste.ubuntu.com/p/yzSQP9V2nR/

[1] That said, the 20.04 -> 20.10 upgrade does switch the system from legacy iptables to nftables, and I notice the install process does insert (legacy) FORWARD rules...

**Comment by balchua** [comment]
@barryprice perhaps using iptables legacy will work?

Im not sure if kube-proxy works with nftables.

If this might help to use legacy iptables. 
 https://v1-15.docs.kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#ensure-iptables-tooling-does-not-use-the-nftables-backend

**Comment by barryprice** [comment]
Ah thanks, that's likely it then. 

However, nftables is the default as of Ubuntu 20.10 - if extra manual steps are now needed to install microk8s then they should be documented on the microk8s website (perhaps the installer could even detect nftables and warn the user?).

I can reproduce this in a regular 20.10 VM, so it's not a quirk of my system, and will affect everyone running the latest Ubuntu once 20.10 is released next month:

$ multipass launch daily:20.10 microk8stest
$ multipass shell microk8stest

(And then within the VM)

$ sudo snap install microk8s --classic
# the install fails

**Comment by balchua** [comment]
@barryprice did it work for you when you switch to legacy iptables?
Agree that it should be documented somewhere.

**Comment by barryprice** [comment]
Hi,

Actually no - nftables compatibility may have been compounding the issue, but even with legacy iptables chosen and UFW disabled, I still see the same error.

I can confirm that kube-apiserver does *briefly* start and listen on port 16443, but only for a few seconds before shutting down again:

`LISTEN 0      4096                                   *:16443            *:*    users:(("kube-apiserver",pid=1906284,fd=32))`

I don't see anything in the logs to suggest exactly why that service is shutting down, but that seems to be the root cause of the subsequent failures.

**Comment by balchua** [comment]
Do you have the apiserver logs that you cam share?  And btw i just saw that you are running on zfs.  There's a section in the docs regarding zfs setup.  https://microk8s.io/docs/install-alternatives

**Comment by barryprice** [comment]
It worked fine on 20.04 with the same filesystem, this is an upgrade issue. I managed to uninstall the broken snap post-upgrade, I just can't seem to reinstall it again.

And since I can't install it, the /var/snap/microk8s dir doesn't exist :/

I already posted the install logs in the initial post, but there's not much there from apiserver. Is there a more detailed apiserver log I can share somewhere?

**Comment by ktsakalozos** [comment]
Hi @barryprice, multipass is rather conservative in the amount of memory and cpu it gives to the machines. Can you try to provision a machine with these specs:
```
multipass launch daily:20.10 -n micro2010 -m 4G -c 2
```

**Comment by barryprice** [comment]
Thanks, that's a great catch - on closer inspection, the failed install within my original multipass VM was actually timing out, not failing to connect as it does on my real machine.

In a new VM with the specs you suggest, it installs fine - even with nftables selected:

https://pastebin.canonical.com/p/X63xHzz9vX/

So this doesn't appear to be an nftables issue after all. I think the next useful step should probably be to set up another 20.10 VM with a ZFS root, and see whether it installs correctly there - and then repeat in 20.04 VMs upgraded to 20.10.

I'll update this issue once I've done that, but if there's any simple way to get debug logs out of kube-apiserver in order to see why it's failing during the install, that might be faster!

**Comment by barryprice** [comment]
> So this doesn't appear to be an nftables issue after all. I think the next useful step should probably be to set up another 20.10 VM with a ZFS root, and see whether it installs correctly there - and then repeat in 20.04 VMs upgraded to 20.10.

I've set up a 20.10 VM by manually installing from the daily 20.10 Desktop image and selecting the ZFS root option during install, then upgrading all packages, and then running `snap install microk8s --classic`. But that seems to work fine with no errors.

So this must be something to do with my having upgraded from 20.04, I'll continue trying to work on steps to reproduce in a VM.

**Comment by desrod** [comment]
I can confirm that this (admittedly quick-n-dirty) change I made to the timeout and building the snap locally, solves the issue: 

`$ git config --get remote.origin.url; git diff
http://github.com/ubuntu/microk8s

diff --git a/snap/hooks/configure b/snap/hooks/configure
index 183e490..40067cf 100755
--- a/snap/hooks/configure
+++ b/snap/hooks/configure
@@ -442,7 +442,7 @@ then
   start_timer="$(date +%s)"
   # Wait up to two minutes for the apiserver to come up.
   # TODO: this polling is not good enough. We should find a new way to ensure the apiserver is up.
-  timeout="120"
+  timeout="300"
   KUBECTL="$SNAP/kubectl --kubeconfig=${SNAP_DATA}/credentials/client.config"
   while ! ($KUBECTL get all --all-namespaces | grep -z "service/kubernetes") &> /dev/null
   do
`

`
sudo snap install snapcraft --classic
sudo snap install lxd
sudo apt-get remove lxd* -y
sudo apt-get remove lxc* -y
sudo lxd init
sudo usermod -a -G lxd ${USER}
git clone http://github.com/ubuntu/microk8s
cd ./microk8s/
snapcraft --use-lxd
sudo snap install microk8s_*_amd64.snap --classic --dangerous
`

This does work: 

`ubuntu@rpi-node-01:/tmp/microk8s$ sudo snap install microk8s_v1.19.3_arm64.snap --classic --dangerous
microk8s v1.19.3 installed
`

`$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    ha-cluster           # Configure high availability on the current node
  disabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
`

`$ snap list
Name       Version    Rev    Tracking       Publisher   Notes
core       16-2.47.1  10188  latest/stable  canonical✓  core
core18     20200724   1888   latest/stable  canonical✓  base
lxd        4.7        17938  latest/stable  canonical✓  -
microk8s   v1.19.3    x1     -              -           classic
snapcraft  4.3        5476   latest/stable  canonical✓  classic`

**Comment by hbjydev** [comment]
Can confirm this is completely broken on 20.10. I'll try @desrod's fix, see if it solves it on the stable 20.10.

**Comment by balchua** [comment]
Hi there's actually a PR where the cni is applied later. To prevent this from happening.
Unfortunately, the snap is not yet available on arm arch.

Check this comment https://github.com/ubuntu/microk8s/issues/1623#issuecomment-707030282

**Comment by barryprice** [comment]
> Hi there's actually a PR where the cni is applied later. To prevent this from happening.
> Unfortunately, the snap is not yet available on arm arch.
> 
> Check this comment [#1623 (comment)](https://github.com/ubuntu/microk8s/issues/1623#issuecomment-707030282)

Thanks, I can confirm this solves the issue for me, at least (on amd64):

```
$ sudo snap install microk8s --classic --channel=latest/edge/slow-start
microk8s (edge/slow-start) v1.19.2 from Canonical✓ installed
$ 
```

**Comment by desrod** [comment]
It appears that `latest/edge/slow-start` channel does not exist and the `latest/edge` channel (2020-10-26 (1771)) fails in precisely the same way as the OP's error and my own reproducer.

**Comment by balchua** [comment]
@ktsakalozos i saw that the PR to load the cni later has been merged to the master, will the `latest/edge` have an arm version?

@desrod i am checking with the canonical team whether the arm version is ready.
