### ISSUE TITLE
Migrate Travis CI from `.org` to `.com` 

### ISSUE THREAD

**Issue by odidev** [ubuntu/microk8s#1588]
Hi,
I was trying to build this project for arm64 in travis, but it is failing for arm64. As this project uses lxd containers for testing and arm64 is already built over the unprivileged lxd containers and to implement nested container concept we must have privileged lxd containers. Due to these reasons the tests are failing for arm64. This issue can be solved if we use arm64-graviton2.

As per https://blog.travis-ci.com/2020-09-11-arm-on-aws the arm64-graviton support is added for travis-ci.com. I have tested the package over arm64-graviton and it is successfully executed with the following changes :

https://github.com/odidev/microk8s/pull/1/commits/386a8a50b3b051ae61c78f78ab8c60a6de623359

TravisLink : https://travis-ci.com/github/odidev/microk8s/builds/185934145

It will be very helpful for arm64 users, if we migrate this project from travis-ci.org to travis-ci.com.

Please let me know if any help is required.

**Comment by ktsakalozos** [comment]
Thank you for this suggestion @odidev.

We will have to eventually move to travis-ci.com as the .org is going to be disabled at the end of the year.

For now the testing on arm64 happens through our internal CI.

**Comment by balchua** [comment]
@ktsakalozos it will also be nice to have `arm` based travis.  This will allow contributors to see the arm builds when they commit.  As an example the prometheus addon recently added arm support.
