### ISSUE TITLE
docker0 bridge MAC address

### ISSUE THREAD

**Issue by somabc** [ubuntu/microk8s#159]
Is it possible to edit the MAC address of the docker0 bridge? 

My host network requires all MAC addresses to be registered in order to obtain a valid IP address from DHCP and with a random MAC I have no external connectivity.

[inspection-report-20181102_105350.tar.gz](https://github.com/ubuntu/microk8s/files/2542138/inspection-report-20181102_105350.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @somabc,

As you might know microk8s has its own dockerd. Configuring dockerd is done through two files, `/var/snap/microk8s/current/dockerd` and `/var/snap/microk8s/current/docker-daemon.json`. The first file includes the dockerd command line arguments and the second is the `daemon.json`. Configuring docker0 bridge is documented here: https://docs.docker.com/v17.09/engine/userguide/networking/default_network/custom-docker0/ , however I do not see an option to set the mac address. Therefore I wonder if it is possible to change the mac address of the bridge as if it were any other interface, for example https://backreference.org/2010/07/28/linux-bridge-mac-addresses-and-dynamic-ports/ 

Thank you for using microk8s.
