### ISSUE TITLE
Linkerd addon - check didn't pass

### ISSUE THREAD

**Issue by fanshibear** [ubuntu/microk8s#1595]
I enabled linkerd addon and then executed the check. There was one error and one failed item.
```
> microk8s linkerd check
ERRO[0000] could not set namespace from kubectl context: ensure a valid KUBECONFIG path has been set 
...
kubernetes-version
------------------
√ is running the minimum Kubernetes API version
× is running the minimum kubectl version
    exec: "kubectl": executable file not found in $PATH
    see https://linkerd.io/checks/#kubectl-version for hints
...
```

[inspection-report-20200924_004425.tar.gz](https://github.com/ubuntu/microk8s/files/5272826/inspection-report-20200924_004425.tar.gz)

Is there anything else should I do?

Thanks.

**Comment by ktsakalozos** [comment]
Hi @fanshibear, for now the linkerd addon is not working on the v1.19 MicroK8s. We are waiting for a linkerd release with this fix https://github.com/linkerd/linkerd2/issues/4918 . This release should come in the next couple of weeks.

On the error you are seeing here you may want to point KUBECONFIG to `/var/snap/microk8s/current/credentials/client.config` and the kubectl is in `/snap/microk8s/current/`.

**Comment by balchua** [comment]
@fanshibear this particular error means you need `kubectl` in your path.  
If you do `sudo snap install kubectl --classic` and try again?

You may also want to do `microk8s config > $HOME/.kube/config`

But as @ktsakalozos mentioned linkerd on kubernetes 1.19 isnt fully functional, there are areas that works but its wonky at best.  We are waiting for the next linkerd release. Then we will update MicroK8s.

**Comment by fanshibear** [comment]
Thanks to @ktsakalozos and @balchua !

Finally I executed `sudo ln -s /snap/microk8s/current/kubectl /usr/bin/kubectl` and `microk8s config > $HOME/.kube/config` and the check passed.
