### ISSUE TITLE
Inspect performance

### ISSUE THREAD

**Issue by AdamIsrael** [ubuntu/microk8s#160]
I've noticed that the performance of `microk8s.inspect` degrades over time. It appeared that most of the time was spent inspecting `snap.microk8s.daemon-apiserver`.

Stepping through `check_service`, I found most of the time was spent dumping the journalctl logs. In my case, it generated an 785M log with 3.3+ million lines.

Is it really necessary to capture the full log? If not, what would a sane limit be?

**Comment by ktsakalozos** [comment]
Fixed via https://github.com/ubuntu/microk8s/pull/161

Indeed the apiserver was configured with aggressive logging. Log verbosity is recenty tuned to the default values.

Your PR addresses the issue in a better way as it puts an upper limit to the log lines we will grab in inspect. Thank you.
