### ISSUE TITLE
Microk8s HA Cluster seems unstable

### ISSUE THREAD

**Issue by VaticanUK** [ubuntu/microk8s#1602]
I'm trying to run a 4 x Pi4 cluster.

Was previously running on 1.18, but I was using latest/stable and things started going wonky this week - issues with pods talking to those on different nodes. When I started looking into things, I noticed it had upgraded to 1.19 at some point. The two _may_ be related, but may not.

In the process of trying to work out what was going on, things got a whole lot worse:
`microk8s status` said that microk8s wasn't running.
`microk8s inspect` said everything was fine.
`microk8s kubectl` said it couldn't connect.

I didn't have a whole lot on my cluster at this point, and everything important is on PVs, so decided to rebuild my cluster, redeploy etc, so I snap removed microk8s from each node, re-installed, checked HA was enabled (because it seems to be a good idea!), re-added the nodes and things were still screwy, but in a different way.

I use lens to manage my cluster and I noticed that lens kept getting disconnected about every 5-10 minutes. I tried deploying something and the deployment was created but no pods were every spun up... I tried looking at logs etc but couldn't find anything obvious so decided to start properly from scratch and reinstalled ubuntu 20.04 on the 4 sd cards.

I've now reinstalled microk8s on each node, checked HA is enabled, added a few other features and added all the nodes... and it still doesn't seem happy.

I'm regularly getting this (though not as often as before I reinstalled from scratch!):
![image](https://user-images.githubusercontent.com/1851814/94368647-2ac10f80-00dd-11eb-8b5c-53d1d2badb52.png)

plus one of my nodes, which initially showed as ready, has turned "unhappy" (the warnings are because the node has change to "unready"):
![image](https://user-images.githubusercontent.com/1851814/94369027-45948380-00df-11eb-8604-9eb076b36a6c.png)

I decided to get take a screenshot of just using kubectl and whilst writing this, the same has happened to node 3:
![image](https://user-images.githubusercontent.com/1851814/94369075-7eccf380-00df-11eb-9cfc-239c377cf1d4.png)

inspection report from node 1:
[inspection-report-20200927_143617.tar.gz](https://github.com/ubuntu/microk8s/files/5288567/inspection-report-20200927_143617.tar.gz)

inspect report from node 2:
[inspection-report-20200927_143534.tar.gz](https://github.com/ubuntu/microk8s/files/5288568/inspection-report-20200927_143534.tar.gz)

**Comment by balchua** [comment]
@VaticanUK thanks for reporting the issue.  It seems like the apiserver on the failing node is crashing with segmentation fault.  Its similar to the one reported earlier.  
https://github.com/ubuntu/microk8s/issues/1598

**Comment by NashidForbes** [comment]
Getting similar errors is this error truly resolved? Or is it just closed for convenience?
