### ISSUE TITLE
[v1.19.2] `helm install` brings 127.0.0.1:16443 not reachable

### ISSUE THREAD

**Issue by cedricpoon** [ubuntu/microk8s#1605]
## How it happens

Hello all. After I deploy microk8s using snap channel 1.19/stable(1.19/stable: v1.19.2 2020-09-26 (1710) 214MB classic), I experience helm chart install failure with the following error message

```json
{"chart_repo": {"chart": {"name": "metallb", "ref": "bitnami/metallb", "version": "0.1.21"}, "config": {"configInline": {"address-pools": [{"addresses": ["172.16.0.0/16"], "avoid-buggy-ips": true, "name": "internal", "protocol": "layer2"}, {"addresses": ["10.101.2.50-10.101.2.100"], "avoid-buggy-ips": true, "name": "external", "protocol": "layer2"}]}}, "repository": {"name": "bitnami", "url": "https://charts.bitnami.com/bitnami"}}, "ansible_loop_var": "chart_repo", "changed": false, "command": "/snap/bin/helm --namespace=default --version=0.1.21 upgrade -i --reset-values -f=/tmp/tmpf7crurpc.yml metallb bitnami/metallb", "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"metallb\" does not exist. Installing it now.\n\nstderr: Error: Kubernetes cluster unreachable: Get \"https://127.0.0.1:16443/version?timeout=32s\": dial tcp 127.0.0.1:16443: connect: connection refused\n", "stderr": "Error: Kubernetes cluster unreachable: Get \"https://127.0.0.1:16443/version?timeout=32s\": dial tcp 127.0.0.1:16443: connect: connection refused\n", "stderr_lines": ["Error: Kubernetes cluster unreachable: Get \"https://127.0.0.1:16443/version?timeout=32s\": dial tcp 127.0.0.1:16443: connect: connection refused"], "stdout": "Release \"metallb\" does not exist. Installing it now.\n", "stdout_lines": ["Release \"metallb\" does not exist. Installing it now."]}
```

The highlight of the above error log will be `"Error: Kubernetes cluster unreachable: Get \"https://127.0.0.1:16443/version?timeout=32s\": dial tcp 127.0.0.1:16443: connect: connection refused"`, which indicated the cluster is not reachable in one of the node of the HA microk8s cluster. However, the cluster is running fine using `kubectl get nodes` on any node inside the HA microk8s cluster.

I had tried doing `curl https://127.0.0.1:16443` on one of the nodes and the cluster returned 404 error arbitrarily mixed with normal unauthorized result (2 out of 10 times returned 404 on my trial).

My `helm install` is performed using Ansible module `community.kubernetes.helm`.

**This issue is not happening on channel latest/stable (latest/stable: v1.19.0 2020-09-08 (1668) 214MB classic)**

Many thanks.

## Versions
| Name | Version |
|-|-|
| Helm | v3.3.4 |
| Ansible | 2.9.12 |
| Microk8s | v1.19.2 |

## Report Tarball
[inspection-report-20200928_112106.tar.gz](https://github.com/ubuntu/microk8s/files/5291860/inspection-report-20200928_112106.tar.gz)

**Comment by cedricpoon** [comment]
This problem also appears on snap channel 1.19/edge: v1.19.2 2020-09-28 (1728) 214MB classic

**Comment by ktsakalozos** [comment]
Thank you for reporting this @cedricpoon.

@freeekanayaka this looks related to the latest patches we added:
```
Sep 27 08:00:35 node-0.v8s.lab microk8s.daemon-apiserver[13731]: I0927 08:00:35.904945   13731 clientconn.go:948] ClientConn switching balancer to "pick_first"
Sep 27 08:00:58 node-0.v8s.lab microk8s.daemon-apiserver[13731]: kube-apiserver: src/db.c:40: db__open_follower: Assertion `db->follower == NULL' failed.
Sep 27 08:00:58 node-0.v8s.lab systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=killed, status=6/ABRT
Sep 27 08:00:58 node-0.v8s.lab systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'signal'.
```

**Comment by alwynpan** [comment]
This problem also appears when enable other add-ons such as storage, prometheus, and fluentd. Those add-ons can be enabled eventually after a few retries. 

This error also pops out randomly: `rpc error: code = Unknown desc = call query-sql (budget 0s): receive: header: EOF`

When I watch a deployment by running `watch microk8s.kubectl get pod -n some-namespace` I can see those two errors appear randomly.

**Comment by ballab1** [comment]
I have the same error with a 3 node HA cluster, running the same version. The only addons I have enabled are: coredns, dashboard, calico. The microk8s.daemon-apiserver restarts every 7 secs. If needed, I can post the microk8s inspect files. I have them from when the system was initially configured 3 days ago, and today after noticing the issue.

**Comment by bdols** [comment]
Also seeing this apiserver error, I have this version running on a two node cluster:
microk8s  v1.19.2   1710   1.19/stable    canonical✓  classic

Oct 18 15:59:05 glrunner02 microk8s.daemon-apiserver[3809796]: kube-apiserver: src/db.c:40: db__open_follower: Assertion `db->follower == NULL' failed.
Oct 18 15:59:06 glrunner02 systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=killed, status=6/ABRT
Oct 18 15:59:06 glrunner02 systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'signal'.
...
Oct 18 15:59:08 glrunner02 systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=killed, status=11/SEGV
Oct 18 15:59:08 glrunner02 systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'signal'.

apiserver never gets back in service.
The second node became unresponsive to a microk8s.status request.
I believe I had ha-cluster, storage, rbac, dns, helm, helm3, registry, and ingress active.
So far, the only fix I have is to remove and install the microk8s snap again.

[inspection-report-20201019_172538.tar.gz](https://github.com/ubuntu/microk8s/files/5403923/inspection-report-20201019_172538.tar.gz)

**Comment by cedricpoon** [comment]
Although I got no clues or evidences there was a solid fix for this issue, `1.19/candidate `(or any release with the same id in snap) seems working fine with me at least now. Those who look for quick and dirty fix can have a look on channel `1.19/candidate` or even `1.19/edge`.

@ktsakalozos May I ask is there any official update for it?

**Comment by ktsakalozos** [comment]
Indeed in there are a few fixes in the database layer waiting to be released in 1.19/candidate. However, before releasing to stable we need to first fix a memory leak identified in https://github.com/ubuntu/microk8s/issues/1598 .

**Comment by nlnjnj** [comment]
I have the same error on snap channel 1.20

**Comment by cedricpoon** [comment]
As I am not actively monitoring my old issue on snap channel 1.19.0, and time flies, I am closing this issue card.

@nlnjnj If you encounter similar issues on newer snap channels, you can start another issue :)
