### ISSUE TITLE
[coredns] default to host configuration not google public

### ISSUE THREAD

**Issue by chris-sanders** [ubuntu/microk8s#1606]
Deploying microk8s on an environment that does not allow access to public domain servers I discovered that the DNS add on is deploying coredns configured with google dns servers hard coded as the default forwarders. It would seem a better option would be to use the hosts DNS configuration rather than a public server that may or may not be allowed on the system.

Referencing https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns this default is what I as a user had expected from coredns. While I can edit the configmap to make changes myself, for a better first time user experience consider using a configuration like this by default.

**Comment by balchua** [comment]
Maybe an option to override this when enabling the addon.

Ex.
`microk8s enable dns:use-host`

Otherwise it defaults to google dns.

Wdyt?

**Comment by chris-sanders** [comment]
In the situation I was in where a corporate policy prevents going directly to public DNS even an option gives the same first user experience. Someone not familiar with K8s enables DNS and things just don't work quite right. I'm hard pressed to think of a situation where using Google is more likely to "just work" than using the host's settings. 

Once someone becomes opinionated the ConfigMap can be configured however you like, so I was just thinking of the first user experience which I don't think an extra option helps with unless our introduction guides recommend it but at that point why not make it the default.

**Comment by balchua** [comment]
@chris-sanders good point when using in a restricted corporate environment.  @ktsakalozos do you think we default to host based `resolv.conf` then google dns as an option?

**Comment by ktsakalozos** [comment]
This is a fair point. We could try to default to the host's resolve.conf on the next 1.20 release.

**Comment by RiyaJohn** [comment]
Hi folks, I would like to pick this issue. I raised a PR for it where coredns uses resolv.conf if hitting google dns servers fails. Do take a look at it.

**Comment by chris-sanders** [comment]
While better, that the previous default, if the resolve.conf isn't used until/unless the hard coded google server doesn't respond you only get some use caes.

If for example, there is a local DNS server(s) that resolve domains but Google isn't blocked. You'll still get unexpected behavior by sending people to Google DNS servers. I guess trying resolve.conf and falling back go Google wouldn't hurt but the local config really should be the first resolver.

**Comment by chris-sanders** [comment]
Just ran across this today, and it might explain why /etc/resolv.conf wasn't used originally.

https://github.com/coredns/coredns/blob/master/plugin/loop/README.md

The use of /etc/resolv.conf will cause a loop with systemd-resolved and CoreDNS will fail to start. You can work around that as shown in the link, but that seems like a fairly common use case for developers. Knowing that, I can see why a public DNS was chosen, while on a server /etc/resolve.conf is a good default it doesn't mesh well with a workstation that's likely using systemd-resolved.

I don't currently see a good default w/o user input. Either way you stand a chance of having DNS not work. I still like the option, I just don't feel strongly about a default anymore. Pick your poison.

**Comment by ktsakalozos** [comment]
@chris-sanders I do not remember the exact details but I think the reason we went for a public forward dns was because in some distributions the `/etc/resolv.conf` was/is a link and that was causing problems. But do not quote me on that, it has been a long time to remember.
