### ISSUE TITLE
Offline install fails on RHEL

### ISSUE THREAD

**Issue by just1victory** [ubuntu/microk8s#1614]
https://microk8s.io/docs/install-alternatives#heading--offline

Current results:
sudo snap ack microk8s_1379.assert
sudo install microk8s_1379.snap
error: This revision of snap "microk8s_1379.snap" was published using classic confinement and thus may perform arbitrary system changes outside of the security sandbox that snaps are usually confined tom which may put your system at risk
If you understand and want to proceed repeat the command including --classic

sudo install microk8s.snap --classic
error: cannot perform the following tasks:
-Ensure prerequisites for "microk8s" are available (cannot install snap base "core": Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup api.snapcraft.io on xx.xx.xx.xx:53: read tcp: xx.xx.xx.xx:35831->xx.xx.xx.xx:53: i/o timeout)

**Comment by balchua** [comment]
Oh you also need to download the `core` first.
`snap download core`.  This will download the `core` snap and the `core` assert.

You will have to do something like this.
`sudo snap ack core_1379.assert` then install the snap core.

After that try to install microk8s snap like above.

**Comment by just1victory** [comment]
Thanks for responding!  I will try that

**Comment by balchua** [comment]
The documentation regarding this subject has also been updated.

https://microk8s.io/docs/install-alternatives#heading--offline
Closing the issue.
