### ISSUE TITLE
error: You must be logged in to the server (Unauthorized) from another server

### ISSUE THREAD

**Issue by gurdeepsira** [ubuntu/microk8s#1626]
Hi
I have Microk8s installed.

I have installed kubectl on my local machine and got the kubectl binary installed on another server. config is this:

apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://10.0.0.78:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: REDACTED

However, in kubeclt I get this: 
error: You must be logged in to the server (Unauthorized)

**Comment by balchua** [comment]
Thanks for reporting this.
We can find out more by setting verbosity in kubectl.
Ex. `kubectl -v 9 get nodes`

This can help us determine where the kubectl is trying to connect to.
