### ISSUE TITLE
Add microk8s to list of support kubernetes in jenkins-x

### ISSUE THREAD

**Issue by carmine** [ubuntu/microk8s#164]
Jenkins-x is the opinionated way to do jenkins, natively on kubernetes. It has several integrations with other kubernetes providers and/or clouds, including minikube and minishift:

https://github.com/jenkins-x/cloud-environments

It'd be great to add microk8s to that list.

**Comment by bohushvitali** [comment]
It would be perfect to enable Jenkins X as an add-on in MicroK8s
