### ISSUE TITLE
gitlab can't install prometheus into my microk8s cluster

### ISSUE THREAD

**Issue by sixcorners** [ubuntu/microk8s#1642]
[inspection-report-20201012_103644.tar.gz](https://github.com/ubuntu/microk8s/files/5364600/inspection-report-20201012_103644.tar.gz)
[inspection-report-20201012_103648.tar.gz](https://github.com/ubuntu/microk8s/files/5364601/inspection-report-20201012_103648.tar.gz)
[inspection-report-20201012_103644.tar.gz](https://github.com/ubuntu/microk8s/files/5364604/inspection-report-20201012_103644.tar.gz)
I'm trying to have gitlab install prometheus onto my cluster but it doesn't seem to be working. I've seen errors about the volume but I'm not sure where Lens is pulling that from. When I have Lens exec in I can see that there is no /data directory in the container where the volume is supposed to be mounted. I'm not really sure what other debugging steps I should use to try to find out what happened.
This is a part of a log from the prometheus container:
```
component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"
```

**Comment by balchua** [comment]
Oh the storage addon is a hostpath provisioner and is meant for single node.

I've tried rook + ceph. But i didnt proceed to use it though.  Perhaps the simplest is an nfs provisioner.

**Comment by sixcorners** [comment]
https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.storage.sh
Based on the warning here I was under the impression that it would work on a single node but just wouldn't be copied over to new nodes.. kind of like how docker swarm's local volume works. Could the warning be updated to say that it will no-op when asked to mount a volume in a cluster?

**Comment by balchua** [comment]
The thing with hostpath is that the pod running the *hostpath provisioner* and the pod needing the volume must be in the same node.  Even if it is running in a cluster.

Pinning your application and hostpath provisioner using `nodeselector` or `taints and tolerations` is also possible even if MicroK8s isnt running multi nodes.  Imho, saying it is a no-op is probably not true at all.  Though one have to be more careful about using it.

**Comment by sixcorners** [comment]
Would it make sense to run the hostpath provisioner on every node then?

**Comment by balchua** [comment]
The data will not be available on other nodes.  Btw, i recently tried longhorn.  Its really easy to setup.  When using it in Microk8s, you need atleast dns to be available.
You may want to give that a try.
