### ISSUE TITLE
How to get addon tar(s) for an offline install (RHEL)

### ISSUE THREAD

**Issue by just1victory** [ubuntu/microk8s#1645]
What is the procedure to get supported addon tar(s) to an offline (air gapped) install of microk8s?    

Microk8s has the image import command, but there isn't any instructions where and how to exactly obtain the tar(s) required for each supported addon.   This is really needed for an offline install.  

microk8s ctr image import myimage.tar

Thanks

**Comment by balchua** [comment]
Hi @just1victory different addons have different ways of getting the images.  We usually jist take it from an upstream.  For example prometheus is using kube-prometheus manifests as provided from their repo/release.

Which addon are you interested?

**Comment by just1victory** [comment]
I was looking for what I need (and where to get it) to support enabling these 5 addons offline:

microk8s enable dashboard dns registry istio ingress

**Comment by balchua** [comment]
The list of addons are located here https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions

You can check the scripts `enable.<addon name>.sh`. You will see which yamls are used.

The `ingress`, `registry`, `dns`, `dashboard` follows the same patterns, except for istio.

For istio we download the `istioctl` and the manifest files from github.
You will be better off following the istio installation from istio site, since you will be doing all those manually for offline.

**Comment by just1victory** [comment]
Thanks.  I'm still trying to get the istio stuff installed.   The install guide is here https://istio.io/latest/docs/setup/getting-started/ but it mentions a config profile.   Have you tried this?  Isn't there a side-door to install istio with microk8s if I downloaded the istio-<ver>.tar.gz?

**Comment by balchua** [comment]
The config profile is an argument to istioctl command.  Where you can choose what components you need.  Thats a good thing as you kight not want to have the full suite running. It takes up a lot of resources.

**Comment by just1victory** [comment]
Thank you for responding.   I ended up copying the enable.isto.sh file locally and modifying it to use a local istio.tar.gz file instead of github.  Then I did a "mount --bind" so microk8s would use it.    

Side question:  Where does microk8s store it's image repository?  docker has a "data-root" override property to state where the repository is.... I cannot find a similar option for microk8s.

**Comment by balchua** [comment]
MicroK8s uses containerd.  The root is by default setup to be in `${SNAP_COMMON}/var/lib/containerd`, where `SNAP_COMMON` is in `/var/snap/microk8s/current/common`.

You can find the arguments passed to containerd from here https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/containerd

**Comment by just1victory** [comment]
Thanks balchua!
