### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by e11137** [ubuntu/microk8s#165]
Hi,
I'm actually trying to install mikrok8s on debian 9 and the install process failed.
Could you help me please?

# snap install microk8s --classic --channel=1.12/stable
error: cannot perform the following tasks:
- Run configure hook of "microk8s" snap if present (run hook "configure": 
-----
+ '[' '!' -d /var/snap/microk8s/237/certs ']'
+ grep -e '\-\-client-ca-file=${SNAP}/certs/ca.crt' /var/snap/microk8s/237/args/kube-apiserver
grep: /var/snap/microk8s/237/args/kube-apiserver: Aucun fichier ou dossier de ce type
+ grep requestheader-client-ca-file /var/snap/microk8s/237/args/kube-apiserver
grep: /var/snap/microk8s/237/args/kube-apiserver: Aucun fichier ou dossier de ce type
+ echo 'Patching requestheader-client-ca-file argument'
Patching requestheader-client-ca-file argument
+ echo ''
/snap/microk8s/237/meta/hooks/configure: ligne 29: /var/snap/microk8s/237/args/kube-apiserver: Aucun fichier ou dossier de ce type
-----)

**Comment by ktsakalozos** [comment]
Hi @e11137 ,

The issue you are having is very similar (if not the same) as the one reported https://github.com/ubuntu/microk8s/issues/156 .

While we are waiting for a new snapd to be released on Debian, the workaround you have to follow is to snap install ` core` right before you deploy microk8s:

```
sudo snap install core
sudo snap install microk8s --classic
```

Have a look at  https://forum.snapcraft.io/t/snapd-not-apt-installing-properly-on-debian-9/8240/2 on why this works.

Thank you for using microk8s.

**Comment by e11137** [comment]
thanks @ktsakalozos 
works fine

**Comment by gandra** [comment]
For me this didn't work.

`uname -a` output:
`Linux gandra-hp-ubuntu 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
