### ISSUE TITLE
microk8s.daemon-containerd service crashing

### ISSUE THREAD

**Issue by neutrongenious** [ubuntu/microk8s#1652]
I have had a stable microk8s cluster running on a single home server, today containerd service started failing. 
I have tried reset and even removing and installing fresh via snap. though still facing same issue.

` level=info msg="StartContainer for \"196a2fb57c59ca9a82b5137419125976048e46ab90e0ecaaf8e7f8bc5f4f232b\""
Oct 15 19:46:38 antaresinc-cluster microk8s.daemon-containerd[614832]: time="2020-10-15T19:46:38.379695723Z" level=info msg="starting signal loop" namespace=k8s.io path=/var/snap/microk8s/common/run/containerd/io.containerd.runtime.v2.task/k8s.io/196a2fb57c59ca9a82b5137419125976048e46ab90e0ecaaf8e7f8bc5f4f232b pid=616403
Oct 15 19:46:38 antaresinc-cluster microk8s.daemon-containerd[614832]: time="2020-10-15T19:46:38.445113989Z" level=info msg="StartContainer for \"196a2fb57c59ca9a82b5137419125976048e46ab90e0ecaaf8e7f8bc5f4f232b\" returns successfully"
Oct 15 19:46:38 antaresinc-cluster microk8s.daemon-containerd[614832]: time="2020-10-15T19:46:38.481460777Z" level=info msg="Stop CRI service"
Oct 15 19:46:38 antaresinc-cluster systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...`

[inspection-report-20201015_194843.tar.gz](https://github.com/ubuntu/microk8s/files/5387409/inspection-report-20201015_194843.tar.gz)

**Comment by balchua** [comment]
Hi when you reinstalled it did you purge it?
Like this `snap remove microk8s --purge`?

**Comment by neutrongenious** [comment]
after multiple attempts and a restart finally, Fresh installation is working as expected. another thing i have noticed is DNS service is using Google DNS directly. Anybody knows why this has been done?

**Comment by balchua** [comment]
Currently there is a PR to be able to use different dns.  https://github.com/ubuntu/microk8s/pull/1625

**Comment by neutrongenious** [comment]
I have resolved my issue by reinstalling though it concerns me Microk8s markets itself as production ready, but my cluster (running for months) have crashed without any change.

**Comment by balchua** [comment]
Choosing the right channel is key to having a long term stable version.  Say using 1.18/stable or 1.19/stable.  
The MicroK8s team will only update the channel for any changes related to that kubernetes version i.e. 1.18 or 1.19.

I wouldn't recommend `latest/stable` for production though.

**Comment by neutrongenious** [comment]
that could be the case, i was using latest/stable channel.
