### ISSUE TITLE
microk8s doesn't start properly without internet access

### ISSUE THREAD

**Issue by bangbangjim** [ubuntu/microk8s#1653]
I have set up a microk8s cluster on a bunch of Centos7 VMs. These VM's internet access was disabled and rebooted.
When I run `microk8s.kubectl get nodes` it will now return:
`The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?`

It seems like I am not the only one who's encountering this [problem](https://askubuntu.com/questions/1270030/microk8s-doesnt-start-without-internet-access).

Is this an expected behaviour. If not, is there anyway to solve this issue?

`microk8s inspect` didn't detect any error
```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1702/inspection-report-20201016_072951.tar.gz

```

**Comment by ktsakalozos** [comment]
Hi @bangbangjim offline deployments are supported as described in [1]. Could you attach the tarball created by `microk8s inspect` so we see why the apiserver refuses to start. Is it possible there is no default network interface?

[1] https://microk8s.io/docs/install-alternatives#heading--offline

**Comment by bangbangjim** [comment]
[inspection-report-20201016_072951.tar.gz](https://github.com/ubuntu/microk8s/files/5398907/inspection-report-20201016_072951.tar.gz)
@ktsakalozos here's the tarbell. Thanks for your advice I will taking a look at the network interface 👍

**Comment by ktsakalozos** [comment]
The apiserver reports (in `journalctl -u snap.microk8s.daemon-apiserver`):
```
Oct 16 00:41:30 master-node microk8s.daemon-apiserver[25802]: Error: Unable to find suitable network address.error='no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.
```

**Comment by bangbangjim** [comment]
@ktsakalozos I tried adding a loopback interface [reference](https://askubuntu.com/questions/993139/how-to-create-a-virtual-network-interface-in-ubuntu) which didn't solve the problem. I have a few questions:

1. I installed the microk8s using snap when I still had internet connection? Should that work or do I need to install the following the offline install guide in https://microk8s.io/docs/install-alternatives#heading--offline

2. Do you know how to solve `Unable to find suitable network address.error='no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.`?

**Comment by ktsakalozos** [comment]
@bangbangjim to solve the issue you are seeing you can either set a default network route, see for example [1], or you can set the bind-address or advertise-address arguments of the api server [2]. To add an argument to the api server you will need to append it to the `/var/snap/microk8s/current/args/kube-apiserver` file and then restart microk8s with `microk8s.stop ; microk8s.start`.

Your approach to offline installation should work but make sure you go through the official doc [3] so you understand what the next steps would be (registries/proxies etc).


[1] https://www.cyberciti.biz/faq/linux-setup-default-gateway-with-route-command/
[2] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
[3] https://microk8s.io/docs/install-alternatives#heading--offline

**Comment by bangbangjim** [comment]
@ktsakalozos Thanks for your help. It's working now and I will list out what I did for the benefit of others.

Assuming 192.168.210.32 is your master node IP address.
1.  Run `sudo ip route add default via 192.168.210.32` for **ALL** VM nodes (Worker nodes too otherwise pulling image from local docker registry wouldn't work).
2. Disable and enable dns in microk8s
3. Run `sudo snap restart microk8s`
4. Remove worker-nodes from cluster and add them back. You should now see `Join node with: microk8s 192.168.210.32:25000/JSKjpIGPOcVsJWKrKeoNOGbKdvvYiCiF`, notice the IP is now your master node IP (it was the router IP if you have internet connection I think?).
5. For me, I encountered ImagePullBackErr in the VMs that hasn't assign a hostname to 192.168.210.32. The pull error was fixed once I assigned 192.168.210.32 with the **same** hostname as the master node VM's. i.e. I append the line `192.168.210.32 master-node` to `/etc/hosts`

@ktsakalozos thanks again for your help :)

**Comment by rome-legacy** [comment]
Holla fratellis,
I have the same problem but a different requirement, maybe there is also a solution for this...
I have microk8s installed on my notebook and would like to start it without any wifi connection. That means something like airplane mode. The goal is to use my time while flying or at places where there is no wifi signal at all.
Basically i just have the lo interface, and that's it...
Any ideas?

**Comment by yurkoff-mv** [comment]
After a local installation of microk8s, my inspection is successful, but the status is not...
`microk8s inspect`
```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2760/inspection-report-20240425_212115.tar.gz
```

`microk8s status`
`microk8s is not running. Use microk8s inspect for a deeper inspection.`
[inspection-report-20240425_212115.tar.gz](https://github.com/canonical/microk8s/files/15119118/inspection-report-20240425_212115.tar.gz)
