### ISSUE TITLE
QUESTION: Is it possible to change the server dns public name once microk8s installed? Ingress certificate issue.

### ISSUE THREAD

**Issue by arnoldfranz** [ubuntu/microk8s#1656]
Hi,
I have installed a one node microk8s v1.18 stable classic on Linux Ubuntu 18.04.
During the installation, the dns public name was 'name1'
I enabled the ingress. It worked correctly for a few weeks.
I change the machine dns public name with a new A record, 'name2'
The issue:
Ingress controller tries to validate certificates with name1. So it fails.
I can't manage making the controller forgetting name1 and adopting name2
Is there a solution?
Thanks a lot
AF

**Comment by balchua** [comment]
Hi thanks for using MicroK8s.
For ingress to work with ssl, i assume you generated a certificate and configured it with nginx ingress.  You may need to recreate the certs again to use "name2" instead of "name1".

Unless i misunderstood your question.

**Comment by arnoldfranz** [comment]
Thanks @balchua for your answer. Yes, a new certificate has been issued, and the problem is that the ingress controller rejects it because it checks the cn and alternate names against the former dns machine name. I have spent a lot of time trying to find where the former machine name is still in code/parameters/cache, I had no success. The public DNS resolves correctly with the new name matching the cn and alternate name, but k8s ingress is stuck on the former name.
Any idea is welcome.

**Comment by balchua** [comment]
Is is similar to this issue? https://github.com/kubernetes/ingress-nginx/issues/5411
