### ISSUE TITLE
Possible performance issues of dqlite over VPN, MTU etc?

### ISSUE THREAD

**Issue by bodleytunes** [ubuntu/microk8s#1657]
Hi,

I'm just trying out a 3 node LXD ZFS based cluster of nodes that are connected by a zerotier VPN.  The VPN throughput is tested to max out around 350mbit/s so its relatively quick.

I've noticed I'm getting intermittent timeouts running kubectl commands and what looks to be pretty shoddy performance where the nodes are not particularly lacking in resources (8 core servers, 32gb ram and the 3rd node is 2vcpu, 2GB ram VM).

I'm wondering if I need to tweak MTU settings in some of the services.  Possibly the calico VXLAN settings.

I've set both LXD bridges to 1350 which drops the 2 containers on servers MTU down to 1350 and also tested manually enforcing 1350 on the vpn interface of the 3rd node.

I can see 3 to 4mbit/s of what I assume is DB replication data giong between the nodes sometimes spiking to 16mbit and then ticking over around 1 to 3 mbit/s which I assume is normal.

Here are some of the examples of the timeouts I'm quite regularly receiving especially when I'm pasting in multiple commands so the system is busy.

```
root@kube1:~/.kube# kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"


Error from server: rpc error: code = Unknown desc = call exec-sql (budget 32.847057672s): receive: header: EOF

----
    
    root@kube1:~/.kube# kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.crds.yaml
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created

error when creating "https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.crds.yaml": Post "https://127.0.0.1:16443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?fieldManager=kubectl-client-side-apply": unexpected EOF
error when retrieving current configuration of:

Name: "issuers.cert-manager.io", Namespace: ""
from server for: "https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.crds.yaml": Get "https://127.0.0.1:16443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/issuers.cert-manager.io": dial tcp 127.0.0.1:16443: connect: connection refused


root@kube1:~/.kube# helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v0.16.1
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: config


Error: Kubernetes cluster unreachable: Get "https://10.100.0.216:16443/version?timeout=32s": dial tcp 10.100.0.216:16443: connect: connection refused

root@kube1:~/.kube# kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
Error from server (InternalError): Internal error occurred: resource quota evaluation timed out

root@kube1:~/.kube# kubectl get pods --all-namespaces
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?

---

```
**Server Node HTOP**
![image](https://user-images.githubusercontent.com/619239/96372329-4066a980-115e-11eb-8e9a-f566439a39a3.png)

**VM node HTOP**
![image](https://user-images.githubusercontent.com/619239/96372383-72780b80-115e-11eb-800a-1ceae5a1f394.png)

Any ideas on whether this will work better with some network or service tweaks?

Many thanks,

Jon.

[inspection-report-20201018_152630.tar.gz](https://github.com/ubuntu/microk8s/files/5397728/inspection-report-20201018_152630.tar.gz)

**Comment by bodleytunes** [comment]
OK seems the problem was running ZFS storage for LXD.

use dir storage works fine.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @bodleytunes

**Comment by bodleytunes** [comment]
Also just for the record I did use the recommended LXD profile for ZFS as per this link wget https://raw.githubusercontent.com/ubuntu/microk8s/master/tests/lxc/microk8s-zfs.profile -O microk8s.profile
