### ISSUE TITLE
Docker version update?

### ISSUE THREAD

**Issue by dmarkey** [ubuntu/microk8s#166]
Any way to have a newer version of docker that allows the --chown flag in the Dockerfile?? 

Great work by the way. Very nice!

**Comment by ktsakalozos** [comment]
Hi @dmarkey 

The `--chown` flag is part of the docker client or dockerd? Here is what you can try. You can deploy a docker package of your preference and **make sure the dockerd of that package is not running**. Then point the docker client that came with that package to the dockerd of microk8s. Have a loo at https://github.com/ubuntu/microk8s/blob/master/docs/dockerd.md and use the `-H` flag on the client as you can see here https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-docker.wrapper#L8.

There is no easy way to replace the dockerd shipping with microk8s at the moment. What we plan to do is to lift the constraint of not having another dockerd running next to microk8s.

Hope this helps. Thank you for using microk8s.

**Comment by ktsakalozos** [comment]
Good to hear this works for you. Using system components goes against the idea of having everything in a single snap package. As you understand, it is hard to account for every possible setup and certify the compatibility across all possible dockerd+microk8s combinations. So, again, I am happy that it works but it is hard to officially support such deployment.

**Comment by ktsakalozos** [comment]
@trusch the dockerd we use is here https://github.com/ubuntu/microk8s/blob/master/snapcraft.yaml#L87. We get the dockerd that comes with xenial's docker.io package. Since you are willing to rebuild the snap here are some options you have:

- Update the snap to base: core18 and try to rebuild
- Cherry pick the docker daemon package and its dependencies from an external repository as we do in the case of the nvidia stack https://github.com/ubuntu/microk8s/blob/master/snapcraft.yaml#L216
- Use our branch that uses containerd https://github.com/ubuntu/microk8s/tree/feature/containerd . This is the path we intend to follow as it should allow users to have installed on their system any dockerd they wish (but that remains to be proven).

**Comment by deas** [comment]
@ktsakalozos I am on cosmic and tried following your suggestion to bump base to core18. Build ended up

```
Downloading core18
Successfully downloaded core18 at /tmp/tmpgxi3_zbp/core18.snap
Setting up '/root/.cache/snapcraft/projects/core18/snap_hashes/amd64/09b7cdd51de34f0db0d8d725e9b6cf0193d2d4aaec7333e5cd359d10b1215c41322d0616b83ce437c65b16ee7c3cb5a7' in '/snap/core18/current'
Parallel unsquashfs: Using 8 processors
7114 inodes (7613 blocks) to write

[=============================================================\] 7613/7613 100%

created 5266 files
created 1008 directories
created 1735 symlinks
created 7 devices
created 0 fifos
Pulling libnftnl
Segmentation fault (core dumped)
Downloading 'core18.snap' 100%
Failed to run 'override-pull': Exit code was 139.
```
Does not seem related to microk8s. Still, I'd appreciate a hint if anyone has one. ;)

PS: I am new to snap, so I might be getting things wrong

**Comment by gortiz** [comment]
Not being able to use multistage build is a big problem in my environment. There is no easier solution than to build my own snap for microk8s?

**Comment by ktsakalozos** [comment]
Hi @gortiz ,

As you can see on this comment https://github.com/ubuntu/microk8s/issues/214#issuecomment-442292449 it is a matter of days to get an updated dockerd in the official repositories. After that we will be able to ship an updated MicroK8s version, given our QA is passing.

For the record, the docker currently available in MicroK8s is 17.03.2-ce (`microk8s.docker version`) released on 2017-05-29 (https://docs.docker.com/engine/release-notes/). 17.03.0-ce came out on 2017-03-01.

Thanks

**Comment by gortiz** [comment]
Great news! I'm eager to use it. Microk8s looks promising. It is really easy to install and more performant than minikube, but this kind of configurations problems may be really blocking.

About the docker version... totally my bad. I thought it read 15.03! Even that, Docker adds functionality very fast. It is a must to be able to update its version.

**Comment by iackov** [comment]
For my "Linux Mint 19 Tara"  I just:
1. unscuash /var/lib/snapd/snaps/microk8s_340.snap
2. Replace (and fix-rename) all docker-related binary /usr/bin/docker* to newer versions from docker-ce_5*.deb and containerd.io._.deb (from https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/ in my case)
3. mksquashfs dir back to microk8s_340.snap 
4. replace microk8s_340.snap and restart: microk8s.stop && microk8s.start

It's dry solution, but it works.
```
root@phenix:~# microk8s.docker -v
Docker version 18.09.0, build 4d60db4
```
(PS: https://unix.stackexchange.com/questions/80305/mounting-a-squashfs-filesystem-in-read-write)
(PS2: rename\fix names:
```
docker-ce-cli.deb
/usr/bin/docker -> /usr/bin/docker

docker-ce.deb
/usr/bin/docker-init      -> /usr/bin/docker-init
/usr/bin/docker-proxy  -> /usr/bin/docker-proxy
/usr/bin/dockerd-ce     -> /usr/bin/dockerd

containerd.io.deb
/usr/bin/containerd           -> /usr/bin/docker-containerd
/usr/bin/containerd-shim  -> /usr/bin/docker-containerd-shim
/usr/bin/ctr                       -> /usr/bin/docker-containerd-ctr
/usr/sbin/runc                  -> /usr/bin/docker-runc
```
)
