### ISSUE TITLE
kubelet logs and kube-apiserver logs are empty

### ISSUE THREAD

**Issue by arnoldfranz** [ubuntu/microk8s#1660]
Hi, 
We run a microk8s 1.19/stable classic.
We had a major incident tonight, all pods restarted @ 22:12 UTC.
I am trying to find the root cause of the problem.
I expect to find logs of kubelet and api-server through journald. However, logs are empty.

```
sysadmin@myserver:/var/snap/microk8s/common/var$ sudo journalctl -u kube-apiserver
-- Logs begin at Sat 2020-10-10 15:06:06 UTC, end at Tue 2020-10-20 11:49:56 UTC. --
-- No entries --
```
```
sysadmin@myserver:/var/snap/microk8s/common/var$ sudo journalctl -u kubelet
-- Logs begin at Sat 2020-10-10 15:06:06 UTC, end at Tue 2020-10-20 11:56:17 UTC. --
-- No entries --
```
How can I get logs ? Any clue is welcome
Thanks
AF

**Comment by ktsakalozos** [comment]
Hi @arnoldfranz 

`microk8s inspect` will print the names of all services in MicroK8s and will gather logs in a tarball. The two services you are looking for are `snap.microk8s.daemon-apiserver` and `snap.microk8s.daemon-kubelet`.

**Comment by arnoldfranz** [comment]
Thank you @ktsakalozos, I have done some progress thanks to your answer.
I see that in the apiserver log:

```
Oct 19 21:50:42 myserver systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver.
Oct 19 21:50:59 myseerver systemd[1]: Started Service for snap application microk8s.daemon-apiserver.
```
Can a snap update stop and start the microk8s server?
Can I explain the incident by a snap update which killed the running services?
Thanks 
AF

**Comment by ktsakalozos** [comment]
Yes, kubernetes services may restart due to an update. You can specify when an update will reach you as described in section "Changing the refresh schedule" of [1].

[1] https://microk8s.io/docs/setting-snap-channel

**Comment by arnoldfranz** [comment]
Thank you  @ktsakalozos , it makes sense, I see the restart in the logs. I had prototyped badly persisted pods, indeeed, restart killed the application context  :-O  So now, I have to make sure my applications are resilient to updates that happen fairly often.
Best regards

**Comment by ktsakalozos** [comment]
Thanks
