### ISSUE TITLE
Tekton CLI (tkn) with MicroK8s on MacOS : how ?

### ISSUE THREAD

**Issue by didier-durand** [ubuntu/microk8s#1662]
Hi there,

We use Tekton and [its CLI](https://github.com/tektoncd/cli) for some CI/CD: it works fine for us on GKE, EKS.

We'd like also to use it now on dev laptops with MicroK8s
But, 'microk8s --help' (see below) tends to demonstrate that microk8s wraps standard K8s CLI : kubectl, istioctl, etc.

Does it mean that I have no chance to get standard tkn cli working on MacOs? 

Unsuccessful trials until now in using 'microk8s kubectl config view --raw > "kube-config"' and using the generated kube-config-file as input to the --kubeconfig of tkn cli.

Thanks in advance for your feedback.

Didier

**Comment by ktsakalozos** [comment]
Hi @didier-durand 

The API server is listening on port 16443 on all interfaces so on a Mac you will need to change the endpoint IP you get with `microk8s kubectl config view --raw` to the IP of the VM running MicroK8s. Alternatively you can use `microk8s config` to get the kubeconfig file.

**Comment by didier-durand** [comment]
@ktsakalozos : Konstantinos, config view to obtain the kubeconfig file seems promising. I'll try it and report back here. Didier
