### ISSUE TITLE
ModuleNotFoundError: installation on macOS not successful

### ISSUE THREAD

**Issue by pr498bp** [ubuntu/microk8s#1667]
Error while installing microk8s on macOS Catalina 10.15.7 using Homebrew v2.5.6.
python v3.8.6 and multipass v1.4.0 are successfully installed.

brew install ubuntu/microk8s/microk8s     
==> Installing microk8s from ubuntu/microk8s
==> Downloading https://files.pythonhosted.org/packages/85/3e/6c3abf78b2207f3565ebadd0b99d1945f4ff18abdc6879617a4f6d939e41/virtualenv-20.0.33.tar.gz
[...]
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/microk8s--homebrew-virtualenv-20201021-39905-au5cev/target/vendor --install-scri
Last 15 lines from /Users/stephan/Library/Logs/Homebrew/microk8s/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/microk8s--homebrew-virtualenv-20201021-39905-au5cev/target/vendor
--install-scripts=/private/tmp/microk8s--homebrew-virtualenv-20201021-39905-au5cev/target/vendor/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/ubuntu/homebrew-microk8s/issues

**Comment by joedborg** [comment]
Hi @pr498bp, thanks for raising the issue.

Is it possible for you to run

```
brew postinstall python3
pip3 install setuptools
```

and then try to install microk8s again please?

**Comment by pr498bp** [comment]
Yes, works fine! Thanks!
