### ISSUE TITLE
Microk8s failed to enable kubeflow on GCP Ubuntu 20.04 VM

### ISSUE THREAD

**Issue by brightlee6** [ubuntu/microk8s#1669]
I launched a VM instance in GCP using ubuntu 20.04 with 8vCPU, 32G memory, 150G disk space.

I followed this web link to install kubeflow using microk8s: https://www.kubeflow.org/docs/started/workstation/getting-started-multipass/

The process failed with following msgs:
![image](https://user-images.githubusercontent.com/6210065/96791691-bf055600-13ad-11eb-9e8d-3364c4561c64.png)

Inspected tarball file is attached here:
[inspection-report-20201021_202733.tar.gz](https://github.com/ubuntu/microk8s/files/5418909/inspection-report-20201021_202733.tar.gz)

Also provide details on how to access kubeflow on GCP instance if succeed. 
Thanks

**Comment by ktsakalozos** [comment]
@brightlee6 could you please try the `1.19/candidate` branch?
```
sudo snap install microk8s --classic --channel=1.19/candidate
```
@knkski might have a better understanding what might be wrong.

**Comment by tommichiels** [comment]
I have the same problem.This is due to this line in 
    if bundle_type == 'full':
        run(
            'microk8s-kubectl.wrapper',
            'delete',
            'mutatingwebhookconfigurations/katib-mutating-webhook-config',
            'validatingwebhookconfigurations/katib-validating-webhook-config',
        )

in enable.kubeflow.sh   

It seems this command returns errors because resource that need to be deleted are not available.

**Comment by tommichiels** [comment]
I remove the lines above created a temp snap with snapcraft and everything worked fine.
