### ISSUE TITLE
Unable to restart kube-proxy.

### ISSUE THREAD

**Issue by Jezza** [ubuntu/microk8s#1673]
We've been experiencing some issues with DNS in microk8s.
It first happened a month or so ago.

The network just hangs.
Trying to create any pods leads to it hanging like so:
![image](https://user-images.githubusercontent.com/4224088/96874845-de1bea80-1476-11eb-85c3-590f0e8fb1c0.png)

I solved it by restarting the server.

It happened again a couple of weeks later, and after I did a little bit of digging, I solved it by restarting the DNS module bundled with microk8s.

Today, totally randomly, it happened again.

I took the time to truly dive into it, and I got as deep as I could, before I realised I have no idea what I'm doing or what I'm looking for.

I was following this as a general guide: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/#is-the-kube-proxy-working

One of the last steps it says is: "Restart kube-proxy and see if it's ok."

The problem with that is:

```bash
root@kubernet1:/etc/microk8s# systemctl restart snap.microk8s.daemon-proxy
Failed to add /run/systemd/ask-password to directory watch: No space left on device
```

What's even weirder is we've already bumped up the inotify limit.
```bash
root@kubernet1:/etc/microk8s# cat /proc/sys/fs/inotify/max_user_watches
65536
```

And right now, we're using about ~400:
```
root@kubernet1:/etc/microk8s# lsof -K | grep inotify | wc -l
415
```

I am seeing a bunch of errors about lsof not being able to print out information on UID 999.
From a quick google, it looks like something related to docker, but docker has never been installed on this machine, so it's probably something related to containerd or something that's common to both docker and microk8s.

Any help would be greatly appreciated!

Here's the report:
[inspection-report-20201022_140435.tar.gz](https://github.com/ubuntu/microk8s/files/5422960/inspection-report-20201022_140435.tar.gz)

**Comment by Jezza** [comment]
There's no event associated with the containers/pods.
They're just sitting there, waiting for nothing.

![image](https://user-images.githubusercontent.com/4224088/96877051-71eeb600-1479-11eb-9cd5-4b8710e3c56e.png)


If I try to look at ingress-nginx logs, I do get an error saying it failed to "wait for the condition", but that's probably a symptom.

**Comment by Jezza** [comment]
I had a look at the couple of processes that UID 999 created.

```bash
 1439 ?        3-13:33:10 mysqld
29210 ?        00:00:04 postgres
31116 ?        00:00:01 postgres
31117 ?        00:00:39 postgres
31118 ?        00:00:39 postgres
31119 ?        00:00:20 postgres
31120 ?        00:00:27 postgres
31121 ?        00:00:02 postgres
```

![cmd_2020-10-22_15-23-10](https://user-images.githubusercontent.com/4224088/96878267-ec6c0580-147a-11eb-991c-e39a22f5de2e.png)

It looks like mysql created a lot of filedescriptors, but I'd assume it'll need them.
On top of that, that's still well below the limit.

I took a look at the postgres instances, and each is packing about 10.
So that's 70 + 700 calls.
Again, still well below the hard limit.

**Comment by Jezza** [comment]
I ended up bumping `/proc/sys/fs/inotify/max_user_watches` up to 1048576.

And with that I restarted the kube-proxy, but nothing seems to have changed.

**Comment by Jezza** [comment]
After mucking around even more, I think the issue lies in the built-in registry.

All of those containers were waiting on the registry, trying to get the same image.
I don't know if there is some lock or something, but if I didn't know any better, it would look like a deadlock.

**Comment by Jezza** [comment]
Bump

Any reason this is happening?

**Comment by ktsakalozos** [comment]
Hi @Jezza 

On the Kube proxy logs (`journalct -u snap.microk8s.daemon-proxy`) I see this error:
```
Oct 22 12:21:58 kubernet1 microk8s.daemon-proxy[18943]: W1022 12:21:58.667024   18943 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4
Oct 22 12:35:10 kubernet1 microk8s.daemon-proxy[18943]: E1022 12:35:10.142169   18943 proxier.go:833] Failed to ensure that filter chain KUBE-EXTERNAL-SERVICES exists: error creating chain "KUBE-EXTERNAL-SERVICES": exit status 4: Another app is currently holding the xtables lock; still 4s 100000us time ahead to have a chance to grab the lock...
```

Is there anything you can think of that may interfere with the network? Could remove dockerd and containerd you have installed probably via apt so we can eliminate one unknown factor?

**Comment by Jezza** [comment]
Hey, thanks for getting back.

There's no running dockerd instance.

containerd is running, but it's the one that belongs to microk8s.
`/snap/microk8s/1702/bin/containerd`

I can't think of anything else that would be changing the network.  
The only thing running on this machine is microk8s.

**Comment by Jezza** [comment]
I also get weird errors when trying to restart the dns module.

![image](https://user-images.githubusercontent.com/4224088/97679147-2c437600-1a95-11eb-96db-2d90f3eb7aa6.png)

**Comment by Jezza** [comment]
This happens quite a lot now.
Every couple of days, we restart a couple of the services, but it happens almost like clockwork.

We make extensive use of cronjobs, if that's a red flag for anyone.

The more I dive into the issue, the more it looks like the server itself just can't handle what we're using it for, because I see stuff like:
![image](https://user-images.githubusercontent.com/4224088/97973752-dccbb580-1dc6-11eb-8a68-8503d6b588ae.png)

That's a _lot_ of time to do requests.
I can't tell if there's a GC issue, or if the process itself just isn't getting any CPU time.

We have a single mysql DB on here, and while it does get hit fairly often, IMO nowhere near enough to cause issues like this.
It probably has something to do with our long running cron jobs.
I'm going to start limiting their resources, and see how that works.

**Comment by Jezza** [comment]
A quick update for those finding themselves in this thread:

The main issue that I could determine was CPU starvation.
Too many things were trying to run, and weren't being limited, so everything was fighting for some time.
Including some core services.

And what ended up happening was a lot of the connections between the pieces seemed to start dropping and timing out.

So the solution was to just reduce how many things were using the node in question.
Ideally, the different services that make use of the internal services would be able to self-heal, but we haven't had this issue for a long time, so identifying which specific applications/services would need to be address would be a tad bit difficult.

My advice: Just reduce the amount of things nomming the CPU time.
