### ISSUE TITLE
microk8s version : how to obtain it?

### ISSUE THREAD

**Issue by didier-durand** [ubuntu/microk8s#1679]
Hi,

When I run 'snap list' on Ubuntu, I get something like

Name        Version    Rev    Tracking       Publisher              Notes
microk8s    v1.19.2    1769   1.19/stable    canonical*             classic

snap list is not usable on MacOs. How do I get equivalent info?

If nothing currently available, maybe a 'microk8s version' command could be added? 

Didier

**Comment by ktsakalozos** [comment]
On MacOS and Win MicroK8s runs on a VM and is paired with a thin client that would forward all `microk8s` commands in that VM. For non-`microk8s` commands you will have to use `multipass exec` [1]. Something like the following should get you the version:
```
multipass exec microk8s-vm -- snap list
```


[1] https://multipass.run/docs/exec-command

**Comment by didier-durand** [comment]
On my Mac:
Name      Version    Rev    Tracking       Publisher   Notes
core      16-2.47.1  10185  latest/stable  canonical✓  core
microk8s  v1.19.0    1668   latest/stable  canonical✓  classic

So, it works fine! Thanks.
Didier
