### ISSUE TITLE
1.19 High cpu usage when idle (twice than 1.18)

### ISSUE THREAD

**Issue by qbx2** [ubuntu/microk8s#1684]
Helo, I am trying to set up microk8s cluster on Vultr. I tried very different settings and found that Microk8s 1.19 consumes much more cpu usage and memory than 1.18. Microk8s 1.19 when idle consistently consumes about 25% cpu usage and 860M mem usage. However, Microk8s 1.18 consumes only 10~15% cpu usage and 590M mem usage on average. Is this normal?

I attached `microk8s inspect` result tarballs (on 1.18 machine, and on 1.19 machine)
[inspection-report-1-1.19.tar.gz](https://github.com/ubuntu/microk8s/files/5432623/inspection-report-1-1.19.tar.gz)
[inspection-report-2-1.18.tar.gz](https://github.com/ubuntu/microk8s/files/5432622/inspection-report-2-1.18.tar.gz)

**Comment by JonathanWilbur** [comment]
I observed this as well. I completely uninstalled 1.19 and installed 1.18 and my issue went away. Sorry I could not give an inspection report: my master was so hosed `microk8s inspect` would hang indefinitely.

One discrepancy between my 1.19 install is that I did it using Ansible's `snap` module, and I enabled these features on **every device** (not just the master) before adding them to the cluster:

- `dns`
- `dashboard`
- `registry`
- `helm3`

The problem seemed to start when I joined nodes to the cluster. There did not seem to be an issue when the master was by itself. The problem also seemed to get considerably worse each time I added a node. I got to four worker nodes in the cluster before another one could not be added (the API request to join the cluster would time out).

The cluster is composed of six Raspberry Pi 4 modules, four of which have 8 GB memory. Two have 2 GB of memory. The master is one of the 2 GB nodes. Looking at the master, the memory usage seemed fine; it seemed to be only a CPU issue. `cgroups` was enabled on all nodes.

@qbx2 Did your issue have any similarities with mine?

**Comment by nemethk** [comment]
Short comparison of 1.18 and 1.19 versions...

Both VMs are running on the same host in the same time. The details of VMs:
- RAM: 2Gi
- vCPU: 1
- OS: [Ubuntu 20.04.1 LTS (mini.iso)](http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/mini.iso)

The compared microk8s versions:
- v1.18.9
- v1.19.3-34+a56971609ff35a

The exactly same manifests (svc, pod, pvc, pv) are created on both VMs. Nginx is serving a static html file.
![118-vs-119-service](https://user-images.githubusercontent.com/29813936/100809540-9eadca00-3436-11eb-8068-f89465429cea.png)

Based on `htop` the memory and cpu usage of version 1.19 is significantly higher.
![118-vs-119-htop](https://user-images.githubusercontent.com/29813936/100809577-b1280380-3436-11eb-9294-5d48cce41853.png)

Data visualisation with Netdata

Overview:
![118-vs-119-netdata-overview](https://user-images.githubusercontent.com/29813936/100809599-c13fe300-3436-11eb-8965-0c4feefb415c.png)

Memory:
![118-119-netdata-memory](https://user-images.githubusercontent.com/29813936/100809613-ca30b480-3436-11eb-8d2e-f35febb84787.png)

CPU:
![118-vs-119-netdata-cpu](https://user-images.githubusercontent.com/29813936/100809628-d157c280-3436-11eb-9213-a2f44998ba7b.png)

**Comment by alfonzso** [comment]
> Short comparison of 1.18 and 1.19 versions...
> 
> Both VMs are running on the same host in the same time. The details of VMs:
> 
> * RAM: 2Gi
> * vCPU: 1
> * OS: [Ubuntu 20.04.1 LTS (mini.iso)](http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/mini.iso)
> 
> The compared microk8s versions:
> 
> * v1.18.9
> * v1.19.3-34+a56971609ff35a
> 
> The exactly same manifests (svc, pod, pvc, pv) are created on both VMs. Nginx is serving a static html file.
> ![118-vs-119-service](https://user-images.githubusercontent.com/29813936/100809540-9eadca00-3436-11eb-8068-f89465429cea.png)
> 
> Based on `htop` the memory and cpu usage of version 1.19 is significantly higher.
> ![118-vs-119-htop](https://user-images.githubusercontent.com/29813936/100809577-b1280380-3436-11eb-9294-5d48cce41853.png)
> 
> Data visualisation with Netdata
> 
> Overview:
> ![118-vs-119-netdata-overview](https://user-images.githubusercontent.com/29813936/100809599-c13fe300-3436-11eb-8965-0c4feefb415c.png)
> 
> Memory:
> ![118-119-netdata-memory](https://user-images.githubusercontent.com/29813936/100809613-ca30b480-3436-11eb-8d2e-f35febb84787.png)
> 
> CPU:
> ![118-vs-119-netdata-cpu](https://user-images.githubusercontent.com/29813936/100809628-d157c280-3436-11eb-9213-a2f44998ba7b.png)

yepp, I have similar issue/problem as @nemethk and others ...

**Comment by Xachman** [comment]
Seems to be the same with 1.20 as well.

**Comment by Mlocik97** [comment]
I have same problem, it took ~30% (in peak, even 40-60%) of my CPU I5 8300H, and my laptop was noisy, when I turned mikrok8s off, I had only ~2% CPU usage, and my CPU get cooler by 10°C.

(official installation (sudo snap install microk8s --classic) on Ubuntu 20.04)

**Comment by thwhk** [comment]
Is it related to ha-cluster enabled by default?
#1671 seems having the same problem

**Comment by Xachman** [comment]
@thwhk I think so I disabled it and I did see better performance.

**Comment by nemethk** [comment]
@thwhk Thanks!
I can confirm. It seems better now.

```
nemethk@microk8s-1-19:~$ microk8s.disable ha-cluster
Reverting to a non-HA setup
Generating new cluster certificates.
Waiting for node to start.  
Enabling flanneld and etcd
HA disabled
```
![image](https://user-images.githubusercontent.com/29813936/106908210-65782b80-66ff-11eb-9978-5c406a354249.png)
