### ISSUE TITLE
How many nodes are available

### ISSUE THREAD

**Issue by saedabdu** [ubuntu/microk8s#169]
Hello,
Wondering how many nodes are available with microk8s, and if possible to control the number of the nodes/masters ?

**Comment by ktsakalozos** [comment]
Hi @saedabdu ,

In microk8s there is only one node and that is your host. If you want more than one nodes running on a single host you can take a look at the Canonical Distribution of Kubernetes (CDK) with the localhost provider [1]. 

Things you should know if you want to use CDK:
- conjure-up is an easy to use installer
- localhost provider uses LXC containers to create more nodes
- `conjure-up kubernetes-core` will give you the minimal deployment (one node, one master) that you can scale afterwards.
- CDK is a production grade offering with a rich configuration options

Why do you want more than one nodes on microk8s? Should we consider this ticket as a feature request?

[1] https://conjure-up.io/
[2] https://www.ubuntu.com/kubernetes/install

**Comment by saedabdu** [comment]
Thanks @ktsakalozos

I use AKS for my production environment, and was looking for a solution to run the workload locally on my 
laptop. I will explore CDK with the localhost provider as you suggest. No need to issue a feature request.
Closing this ..
Best.
