### ISSUE TITLE
Node crashes after a few hours.

### ISSUE THREAD

**Issue by doodlemania2** [ubuntu/microk8s#1693]
See attached. Last thing I had done was install grafana, then came back and it was dead. Reboot did not fix. Other nodes in the cluster appear fine. K8S dashboard said it had failed about six hours prior.
[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/5454589/inspection-report.tar.gz)

**Comment by ktsakalozos** [comment]
@doodlemania2 I think you are affected by https://github.com/ubuntu/microk8s/issues/1598

Could you re-install the node from the 1.19/candidate channel?
```
sudo snap install microk8s --classic --channel=1.19/candidate
```

**Comment by doodlemania2** [comment]
Fantastic! Thank you so much - will do so and report back on #1598
