### ISSUE TITLE
Parallel instances of microk8s snap supported ?

### ISSUE THREAD

**Issue by didier-durand** [ubuntu/microk8s#1694]
Hello,

Based on https://forum.snapcraft.io/t/parallel-installs/7679, are multiple parallel instances of microk8s on a single Ubuntu instance supported ?

Thanks

Didier

**Comment by ktsakalozos** [comment]
No, parallel installs are not supported. There are certain resources that are shared at this point (eg network).

**Comment by didier-durand** [comment]
Thanks for the quick response. I'll have to use several Ubuntu instances then. Didier
