### ISSUE TITLE
missing AppArmor profiles for microk8s on LXD

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1697]
Hi,

When I restart the container containing microk8s I sometimes get this error. I found this https://blog.sleeplessbeastie.eu/2020/07/20/how-to-deal-with-missing-apparmor-profiles-for-microk8s-on-lxd/ which seems to fix it. Perhaps if one of these ways is the best it could be included in the docs? I'm pretty sure most people wouldn't want a microk8s instance that can't start.

**Comment by ktsakalozos** [comment]
Hi @sstubbs 

Thank you for reporting this. The same issue was reported some time ago in [1, 2]. We have revised the documentation page regarding the installation on LXD with the least intrusive solution [3]

[1] https://forum.snapcraft.io/t/cannot-change-profile-for-the-next-exec-call-no-such-file-or-directory/12255
[2] https://forum.snapcraft.io/t/snapd-apparmor-profiles-not-being-applied-in-lxd-containers-with-lxc-apparmor-profile-unconfined-when-host-is-rebooted/5818/8
[3] https://discuss.kubernetes.io/t/microk8s-in-lxd/11520

**Comment by sstubbs** [comment]
Hi @ktsakalozos,

ok I'm using that solution then. Generally I'm very impresses with running microk8s in LXD. Another benefit is that I can run apps that aren't quite production ready in kubernetes in their standalone modes in lxd containers.

Not sure how I never heard about LXD until recently. I've been using docker and then kubernetes for quite a few years. LXD is the last piece of the puzzle that is needed.

Thanks for all the great work on microk8s and LXD.

**Comment by balchua** [comment]
@sstubbs glad that this worked for you!!  Im closing the issue for now.  Feel free to open one when needed.
