### ISSUE TITLE
Cannot enable Prometheus on Microk8s 1.19/stable

### ISSUE THREAD

**Issue by tarteens** [ubuntu/microk8s#1699]
Hi, 

I'm trying to upgrade microk8s from 1.16 to 1.19. Everything seems to working , except that I cannot enable the prometheus addon.
I'm curring a CentOs 7.7

* MicroK8s is properly installed  and is working expecting 

$ snap list
Name      Version    Rev    Tracking       Publisher   Notes
microk8s  v1.19.2    1769   1.19/stable    canonical✓  classic`

$ microk8s.status 
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    helm3                # Helm 3 - Kubernetes package manager
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
  disabled:
    ambassador           # Ambassador API Gateway and Ingress
    cilium               # SDN, fast with full network policy
    dashboard            # The Kubernetes dashboard
    fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring
    gpu                  # Automatic enablement of Nvidia CUDA
    helm                 # Helm 2 - the package manager for Kubernetes
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    istio                # Core Istio service mesh services
    jaeger               # Kubernetes Jaeger operator with its simple config
    knative              # The Knative framework on Kubernetes.
    kubeflow             # Kubeflow for easy ML deployments
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    multus               # Multus CNI enables attaching multiple network interfaces to pods
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation

* When I' try to enable prometheus :

$ microk8s.enable prometheus
Addon dns is already enabled.
/snap/microk8s/1769/bin/sed: can't read /var/snap/microk8s/1769/kube-prometheus/manifests/alertmanager-alertmanager.yaml: No such file or directory
Failed to enable prometheus

* Indeed , the directory is empty , the ls command gives nothing
ls /var/snap/microk8s/1769/kube-prometheus/

thanks for your help

**Comment by balchua** [comment]
@tarteens does the directory (`/var/snap/microk8s/1769/kube-prometheus/`) exist? If yes can you delete that directory?
The addon will download the binary from the kube-prometheus github releases.

**Comment by tarteens** [comment]
@balchua  The directory exists indeed. I've deleted it , and re execute the microk8s.enable prometheus. 

the installation was properly done. thanks for your help.
