### ISSUE TITLE
Enable mountPropagation

### ISSUE THREAD

**Issue by wayneconnolly** [ubuntu/microk8s#1702]
Hi - I can't find out how to enable mountPropagation=shared for microk8s. 

Ubuntu: 20.04
Microk8s: 1.18
Thanks,
w

**Comment by ktsakalozos** [comment]
Hi @wayneconnolly 

Do you follow a guide/tutorial/manual I can look at? What steps do you take and what error do you get?

**Comment by madalinignisca** [comment]
Hi. I'm trying Longhorn, and also stopped on understanding how to enable mount propagation, which is mandatory for it.
https://longhorn.io/docs/1.1.0/deploy/install/#installation-requirements
Longhorn seems a really viable solution for MicroK8s clusters.

**Comment by madalinignisca** [comment]
I'm back!

MicroK8s 1.20.1

```
curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/scripts/environment_check.sh | bash
daemonset.apps/longhorn-environment-check created
waiting for pods to become ready (0/1)
waiting for pods to become ready (0/1)
all pods ready (1/1)

  MountPropagation is enabled!

cleaning up...
daemonset.apps "longhorn-environment-check" deleted
clean up complete
```

Looks like it comes with MountPropagation enabled by default, at least in 1.20.1.
