### ISSUE TITLE
Dashboard does not show in browser

### ISSUE THREAD

**Issue by fethomm** [ubuntu/microk8s#1705]
I am new to all of Kubernetes, but quite versed in Linux in general. So today for testing purposes I installed ubuntu 20.10 server 64-bit on 2 raspberry pis and installed microk8s on both. All goes well, I can join the leaf to the master.

 What does not work is bringing up the dashboard. The command 'microk8s dashboard-proxy' tells me, the dashboard will be available at https://127.0.0.1:10443 and gives me a token. The browser says: '127.0.0.1 has denied the connection'. I did some reading, but can't get it solved. Help is much appreciated.

[inspection-report-20201101_143714.tar.gz](https://github.com/ubuntu/microk8s/files/5471136/inspection-report-20201101_143714.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @fethomm 

The `microk8s dashboard-proxy` command is run on one of the nodes and the browser is also running on the same node? I want to make sure that the localhost 127.0.0.1 is the same for both the `microk8s dashboard-proxy` and the browser.

**Comment by fethomm** [comment]
The microk8s dashboard-proxy command is run on one of the nodes, but since it's headless, the browser runs on a workstation in the same network.

**Comment by ktsakalozos** [comment]
The microk8s dashboard-proxy should be exposing the dashboard on all interfaces [1]. You should be able to reach the dashboard if you used the IP of the node where the `microk8s dashboard-proxy` was called.

[1] https://github.com/ubuntu/microk8s/blob/master/scripts/wrappers/dashboard-proxy.py#L64

**Comment by fethomm** [comment]
Thanks, that works. At least in Firefox after agreeing to an exception, which Chrome for security reasons does not grant.
