### ISSUE TITLE
v1.19/Raspberry PI 4/Ubuntu server 20.10  missing addons

### ISSUE THREAD

**Issue by wtao-redfast** [ubuntu/microk8s#1706]
I installed v1.19 stable to my pi4 device running ubuntu sever 20.10. (system info below)

<img width="835" alt="Screen Shot 2020-11-01 at 11 35 42 AM" src="https://user-images.githubusercontent.com/53849964/97812477-68620c80-1c36-11eb-9835-6978469470f3.png">

But when i tried to enable fluentd and Prometheus addons, they are not included. 
<img width="619" alt="Screen Shot 2020-11-01 at 11 42 31 AM" src="https://user-images.githubusercontent.com/53849964/97812626-5896f800-1c37-11eb-8621-0fcaece5d843.png">

can anyone help how to bring these addons back? 

`microk8s inspect` log attached.
[inspection-report-20201101_193436.tar.gz](https://github.com/ubuntu/microk8s/files/5471619/inspection-report-20201101_193436.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @wtao-redfast 

The scripts to enable and disable prometheus are [1] and [2]. To get them released to architectures other than amd64 we will need to make sure these scripts deliver the right yaml manifests for the architectures we want to target (arm64 in this case). Afterwards enabling the addon is done in [3] and [4]. Would you or anyone else be willing to try prometheus on arm64 and submit a PR?

Thank you.

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.prometheus.sh
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/disable.prometheus.sh 
[3] https://github.com/ubuntu/microk8s/blob/master/snap/snapcraft.yaml#L475
[4] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/addon-lists.yaml#L86

**Comment by wtao-nexus5** [comment]
sure. let me try work on it

**Comment by wtao-nexus5** [comment]
Tried to replace many of the images with its respective arm64 build with a matching/similar version number, (change diffs in the attached file)
[arm64-Prometheus-diff.txt](https://github.com/ubuntu/microk8s/files/5484818/arm64-Prometheus.txt)

I can get most objects running in green, 
<img width="912" alt="Screen Shot 2020-11-03 at 4 27 20 PM" src="https://user-images.githubusercontent.com/43157832/98055120-9c356180-1df1-11eb-95c3-a761a8240068.png">

Prometheus operator's CRDs are also in green,
<img width="802" alt="Screen Shot 2020-11-03 at 4 28 40 PM" src="https://user-images.githubusercontent.com/43157832/98055163-aeaf9b00-1df1-11eb-8dad-752b9d1b001e.png">

But, somehow the Prometheus-k8s CRD object doesn't spawn a Statefulset (prometheus-k8s) and a Pod(prometheus-k8s-0); means the Prometheuse app itself is not running. 

if someone has interests to work on the issue, i am more than happy to join you.

**Comment by ktsakalozos** [comment]
Maybe you should ping the people over at kube-prometheus [1]. They may be interested in your work and offer more resources and directions.

[1] https://github.com/prometheus-operator/kube-prometheus

**Comment by wtao-nexus5** [comment]
I got it work now for v1.19.

1. The change is based on kube-prometheus 0.6.0 release (because your script enable.prometheus.sh uses 0.6.0). changed files, 
[arm64-change.log](https://github.com/ubuntu/microk8s/files/5512793/arm64-change.log)

2. all pods, service, etc, are running
<img width="877" alt="Screen Shot 2020-11-09 at 11 19 36 AM" src="https://user-images.githubusercontent.com/43157832/98586707-eef19c00-227d-11eb-974f-4cfbed7bf6b4.png">

3. Prometheus dashboard is running,
<img width="1189" alt="Screen Shot 2020-11-09 at 11 19 57 AM" src="https://user-images.githubusercontent.com/43157832/98586740-003aa880-227e-11eb-946d-e239611f8991.png">

**Question**, your v1.19 enable.prometheus.sh downloads the manifests yaml files on the fly; v1.18 bundles the yamls. would you like to restore the bundled way in a pull request so that there will be two yaml set, one is for arm64 and the other for amd64?

**Comment by wtao-nexus5** [comment]
Also, jaeger and fluentd addons are also hidden for v1.19. would you like to restore the add-ons? i'd like to work on it

**Comment by wtao-nexus5** [comment]
Jaeger is working now if using a mutli-arch all-in-one (querycapjaegertracing/all-in-one:latest) image and you need to build the jaeger-operator yourself.

[jaeger.log](https://github.com/ubuntu/microk8s/files/5532831/jaeger.log)

**Comment by morlay** [comment]
use `querycapistio/all-in-one:1.20.0` instead. see more https://github.com/querycap/istio

`jaegertracing/jaeger-operator:master` is already multi arch image. https://hub.docker.com/r/jaegertracing/jaeger-operator/tags

**Comment by wtao-nexus5** [comment]
@ktsakalozos i have ported jaeger, efk and prometheus addons to work with v1.9.  you can find the details at https://github.com/wtao-nexus5/public/tree/master/K8s/Addons. 

the porting works for each addons are different. can you do a review? are you open for a discussion how to bring the addons back officially to microk8s for arm64 arch?
