### ISSUE TITLE
Error when running microk8s enable dns dashboard storage

### ISSUE THREAD

**Issue by jtfogarty** [ubuntu/microk8s#1709]
clusterrolebinding.rbac.authorization.k8s.io/microk8s-admin created
Adding argument --authentication-token-webhook to nodes.
Configuring node 172.27.96.66
Configuring node 172.27.96.68
Configuring node 172.27.96.67
Metrics-Server is enabled
Applying manifest
E1102 20:12:34.604717    2300 request.go:1001] Unexpected error when reading response body: unexpected EOF
error: unexpected error when reading response body. Please retry. Original error: unexpected EOF
Failed to enable dashboard
[inspection-report-20201102_205016.tar.gz](https://github.com/ubuntu/microk8s/files/5477951/inspection-report-20201102_205016.tar.gz)

**Comment by RFMVasconcelos** [comment]
Thank you for raising this @jtfogarty.

@ktsakalozos any ideas of what might be wrong?

**Comment by ktsakalozos** [comment]
Hi @jtfogarty 

The API server failed to serve one of the requests needed to complete the enabling chain. We have addressed a number of such cases and we will be releasing the fixes soon. In the meantime you could refresh to the `1.19/candidate` channel.
```
sudo snap refresh microk8s --channel=1.19/candidate
```
```

**Comment by jtfogarty** [comment]
Thanks
