### ISSUE TITLE
Docs need updating for calico firewall/ufw requirements

### ISSUE THREAD

**Issue by barryprice** [ubuntu/microk8s#1712]
Hi,

I'm on the latest/edge/slow-start channel (on Ubuntu 20.10 for x86_64) as the default channel won't install for me (see #1586), so I have calico instead of flannel (or whatever came before):
```
$ snap info microk8s | grep -E '^tr|^in'
tracking:     latest/edge/slow-start
installed:          v1.19.2                    (1758) 214MB classic
$
```
With a local UFW firewall enabled, the calico-kube-controllers pod goes into CrashLoopBackOff, as it's unable to connect to the kubernetes service:
```
2020-11-05 03:34:10.543 [INFO][1] main.go 88: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", CompactionPeriod:"10m", EnabledControllers:"node", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", HealthEnabled:true, SyncNodeLabels:true, DatastoreType:"kubernetes"}
W1105 03:34:10.546467       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020-11-05 03:34:10.547 [INFO][1] main.go 109: Ensuring Calico datastore is initialized
2020-11-05 03:34:20.548 [ERROR][1] client.go 255: Error getting cluster information config ClusterInformation="default" error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2020-11-05 03:34:20.548 [FATAL][1] main.go 114: Failed to initialize Calico datastore error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
```

```
$ kubectl get all
NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.152.183.1   <none>        443/TCP   23h
$ 
```

With UFW disabled, it starts up perfectly, and I can use the cluster just fine.

[The current docs](https://microk8s.io/docs/troubleshooting#heading--common-issues) have a solution to this kind of issue (expand "My dns and dashboard pods are CrashLooping..."):

`sudo ufw allow in on cni0 && sudo ufw allow out on cni0`

However, I don't have a cni0 interface, nor a cbr0.

I do have the following, some of which will be unrelated - but haven't yet managed to figure out exactly what traffic I need to allow from where to where:

```
$ ip a s | awk '/^[1-9]/ {print $2}' | sort
cali06c9fa74f73@if3:
cali105bb1aee37@if3:
cali4af84c3c4ff@if3:
cali4b91890a870@if3:
cali633c34636fc@if3:
cali82bb067e648@if3:
cali8bc6fd8a8ad@if3:
calicd414050d96@if3:
calid5e06928aba@if3:
docker0:
enp0s31f6:
lo:
lxcbr0:
lxdbr0:
mpqemubr0:
mpqemubr0-dummy:
tun0:
veth811aa80a@if10:
virbr0:
virbr0-nic:
vxlan.calico:
wlp3s0:
$ 
```

I don't see the `10.152.183.1` address on any of the above interfaces, the closest seems to be `mpqemubr0` on an adjacent subnet: 
```
$ ip a s | grep -B 2 10.15
8: mpqemubr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:b0:05:02 brd ff:ff:ff:ff:ff:ff
    inet 10.153.54.1/24 brd 10.153.54.255 scope global mpqemubr0
$ 
```

I did try the following, but it appears to have no effect:

```
sudo ufw allow in on mpqemubr0
sudo ufw allow out on mpqemubr0
```

**Comment by petermetz** [comment]
@barryprice My guess is that you want to allow the `vxlan.calico` interface instead. Not sure why this has changed from cni0 that the inspect script looks for. Maybe microk8s changed the calico config you get by default when you pull up a cluster and that made it define a different interface?

Looking here [1], they have different install options and one of them is the VXLAN so that's definitely point to the direction that the default Calico config of microk8s was changed somewhere along the line and the inspect script was not updated to match it.

[1]: https://docs.projectcalico.org/networking/configuring

**Comment by barryprice** [comment]
Thanks, I tried this:
```
sudo ufw allow in on vxlan.calico
sudo ufw allow out on vxlan.calico
```

Which gives me the following UFW status:

```
Status: active

To                         Action      From
--                         ------      ----
Anywhere on lxcbr0         ALLOW       Anywhere                  
Anywhere on lxdbr0         ALLOW       Anywhere                  
Anywhere on virbr0-nic     ALLOW       Anywhere                  
Anywhere on virbr0         ALLOW       Anywhere                  
Anywhere on mpqemubr0      ALLOW       Anywhere                  
Anywhere on mpqemubr0-dummy ALLOW       Anywhere                  
Anywhere on vxlan.calico   ALLOW       Anywhere                  
Anywhere (v6) on lxcbr0    ALLOW       Anywhere (v6)             
Anywhere (v6) on lxdbr0    ALLOW       Anywhere (v6)             
Anywhere (v6) on virbr0-nic ALLOW       Anywhere (v6)             
Anywhere (v6) on virbr0    ALLOW       Anywhere (v6)             
Anywhere (v6) on mpqemubr0 ALLOW       Anywhere (v6)             
Anywhere (v6) on mpqemubr0-dummy ALLOW       Anywhere (v6)             
Anywhere (v6) on vxlan.calico ALLOW       Anywhere (v6)             

Anywhere                   ALLOW OUT   Anywhere on lxcbr0        
Anywhere                   ALLOW OUT   Anywhere on lxdbr0        
Anywhere                   ALLOW OUT   Anywhere on virbr0        
Anywhere                   ALLOW OUT   Anywhere on virbr0-nic    
Anywhere                   ALLOW OUT   Anywhere on mpqemubr0     
Anywhere                   ALLOW OUT   Anywhere on mpqemubr0-dummy
Anywhere                   ALLOW OUT   Anywhere on vxlan.calico  
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on lxcbr0   
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on lxdbr0   
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on virbr0   
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on virbr0-nic
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on mpqemubr0
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on mpqemubr0-dummy
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on vxlan.calico

I still see the same failures on the kube-controller pod though:
```
2021-01-02 09:33:56.361 [INFO][1] main.go 88: Loaded configuration from environment config=&config.Config{LogLevel:"info", ReconcilerPeriod:"5m", CompactionPeriod:"10m", EnabledControllers:"node", WorkloadEndpointWorkers:1, ProfileWorkers:1, PolicyWorkers:1, NodeWorkers:1, Kubeconfig:"", HealthEnabled:true, SyncNodeLabels:true, DatastoreType:"kubernetes"}
W0102 09:33:56.364224       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2021-01-02 09:33:56.365 [INFO][1] main.go 109: Ensuring Calico datastore is initialized
2021-01-02 09:34:06.365 [ERROR][1] client.go 255: Error getting cluster information config ClusterInformation="default" error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2021-01-02 09:34:06.366 [FATAL][1] main.go 114: Failed to initialize Calico datastore error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
```

**Comment by barryprice** [comment]
Ah, on closer inspection there's a second calico interface here with a uuid name, presumably dedicated to the kube-system namespace:

```
20: calic34b1eb380d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-957ccf8c-b8e6-8716-6d2f-d7364bfde992
    inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
       valid_lft forever preferred_lft forever
```

And indeed, adding `ufw allow` rules for both "in" and "out" on that interface solves the problem.

**Comment by petermetz** [comment]
> Ah, on closer inspection there's a second calico interface here with a presumably randomised name, perhaps dedicated to the kube-system namespace?
> 
> ```
> 20: calic34b1eb380d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
>     link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-957ccf8c-b8e6-8716-6d2f-d7364bfde992
>     inet6 fe80::ecee:eeff:feee:eeee/64 scope link 
>        valid_lft forever preferred_lft forever
> ```
> 
> And indeed, adding `ufw allow` rules for both "in" and "out" on that interface solves the problem.

@barryprice Oh, that makes sense in hindsight. I could send a second PR where these randomized interfaces are also covered, but need to think carefully about how to reliably find/identify them given the randomized name. Best I can come up with right now is a regex to match it as close as possible, but that still leaves the possibility open for issues when someone just happens to have an interface defined that for whatever reason is also matching the regex.
