### ISSUE TITLE
Microk8s not starting behind corporate proxy

### ISSUE THREAD

**Issue by Phylu** [ubuntu/microk8s#1718]
I installed microk8s on a Ubuntu 20.04 server via snap as of the official documentation. After the installation, the kubernetes cluster does not boot up properly, as the calico pods cannot be retrieved. 

```
Nov 06 14:31:07 SRV100116 microk8s.daemon-containerd[1073]: time="2020-11-06T14:31:07.363358638+01:00" level=error msg="Failed to load cni configuration" error="cni config load failed: no network config found in /var/snap/microk8s/1769/args/cni-network: cni plugin not initialized: failed to load cni config"
Nov 06 14:31:12 SRV100116 microk8s.daemon-containerd[1073]: time="2020-11-06T14:31:12.364102216+01:00" level=error msg="Failed to load cni configuration" error="cni config load failed: no network config found in /var/snap/microk8s/1769/args/cni-network: cni plugin not initialized: failed to load cni config"
Nov 06 14:31:14 SRV100116 microk8s.daemon-containerd[1073]: time="2020-11-06T14:31:14.248621204+01:00" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:calico-node-q4ghx,Uid:1ba56ccd-5d72-4db5-ad12-5dcf0463a2af,Namespace:kube-system,Attempt:0,}"
Nov 06 14:31:15 SRV100116 microk8s.daemon-containerd[1073]: time="2020-11-06T14:31:15.120050803+01:00" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:calico-node-q4ghx,Uid:1ba56ccd-5d72-4db5-ad12-5dcf0463a2af,Namespace:kube-system,Attempt:0,} failed, error" error="failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to copy: httpReaderSeeker: failed open: unexpected status code https://k8s.gcr.io/v2/pause/blobs/sha256:da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e: 503 Service Unavailable"
```

I have the suspicion that the corporate proxy server in the network is somehow blocking the download of the images. The proxy is doing deep package inspection and re-encrypting any SSL traffic. The root certificate of the proxy is correctly installed in /etc/ssl/certs/ca-certificates.crt

I am not sure, if I need to do some extra configuration, or if there is a bug that prevents microk8s from spawning. Any help is highly appreciated.

[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/5502342/inspection-report.tar.gz)

**Comment by mavencode01** [comment]
@Phylu  Have you tried the instruction installing behind proxy ?

https://microk8s.io/docs/install-proxy

**Comment by Phylu** [comment]
The network setup is totally transparent for the host. So I do not have the option to configure any proxy settings there.

**Comment by yalosev** [comment]
@mavencode01 Hello.
I tried to install microk8s behind proxy following that manual but no luck.
Installation stucks with:
```
Dec 28 09:55:45 no-int microk8s.daemon-apiserver-kicker[99441]: Setting up the CNI
Dec 28 09:55:45 no-int microk8s.daemon-apiserver-kicker[103473]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dec 28 09:55:45 no-int microk8s.daemon-apiserver-kicker[103473]:                                  Dload  Upload   Total   Spent    Left  Speed
Dec 28 09:55:45 no-int microk8s.daemon-apiserver-kicker[103473]: [158B blob data]
Dec 28 09:55:45 no-int microk8s.daemon-apiserver-kicker[103473]: curl: (56) Received HTTP code 403 from proxy after CONNECT

Dec 28 09:55:46 no-int microk8s.daemon-containerd[99458]: time="2020-12-28T09:55:46.733895323Z" level=error msg="Failed to load cni configuration" error="cni config load failed: no network config found in /var/snap/microk8s/1864/args/cni-network: cni plugin not initialized: failed to load cni config"
Dec 28 09:55:46 no-int microk8s.daemon-kubelet[99489]: E1228 09:55:46.734690   99489 kubelet.go:2160] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

Meanwhile in the proxy logs I can find record like this:
```
CONNECT   Dec 28 09:56:18 [4694]: Connect (file descriptor 7): myhost [10.130.0.19]
CONNECT   Dec 28 09:56:18 [4694]: Request (file descriptor 7): CONNECT 127.0.0.1:16443 HTTP/1.1
INFO      Dec 28 09:56:18 [4694]: Refused CONNECT method on port 16443
```

Sure no-proxy is set, like
`NO_PROXY="localhost,127.0.0.0/8,10.0.0.0/8,10.130.0.0/16,192.168.0.0/16"`
but it makes no difference. Seems like curl script is ignoring NO_PROXY settings.

Do you have any advice in this case?
Thank you

**Comment by Phylu** [comment]
Just to let you know. I ended up getting the `k8s.gcr.io` host excluded from the SSL/TLS inspection functionalily in the web proxy. So it is working for me now, but the original issue still exists.

**Comment by yalosev** [comment]
I also have fixed my case. `kubelet-env` also need to be patched with NO_PROXY variables

**Comment by mavencode01** [comment]
@yalosev where is the file `kubelet-env` ?

**Comment by yalosev** [comment]
@mavencode01 I'm sorry, not `kubelet-env` but `kubectl-env`. It's also placed in SNAP_DATA - `${SNAP_DATA}/args/kubectl-env`
