### ISSUE TITLE
Proxy not working inside container except manually setting http_proxy inside container

### ISSUE THREAD

**Issue by mavencode01** [ubuntu/microk8s#1719]
I'm cannot enable kubeflow because the pod cannot reach the internet (api.jujucharms.com). 

If I exec into a container, then set the **http_proxy** inside the container, I could reach the internet otherwise, it fails. 

For example, running the Ubuntu connectivity check image

```
 microk8s.kubectl run --rm -it --restart=Never --image=ubuntu connectivity-check -- bash

$apt update    # Fails

# set proxy variable
$export http_proxy='https://....'

$apt update    # works now
```

Also, I followed the instruction running behind [proxy](https://microk8s.io/docs/install-proxy) setting the **HTTPS_PROXY** variable inside /var/snap/microk8s/current/args/containerd-env but no luck.

Any idea what's wrong with my microk8s setup?

**Comment by orenamir2** [comment]
same for me.
this works for me 
microk8s.kubectl run --rm -it --restart=Never --image=ubuntu connectivity-check -- bash -c "export http_proxy=http://<IP ADDRESS>:3128 && export https_proxy=http://<IP ADDRESS>:3128 && apt update && apt install -y curl && curl https://api.jujucharms.com/charmstore/v5/~kubeflow-charmers/ambassador-88/icon.svg"

**Comment by mavencode01** [comment]
This is preventing user from enabling `kubeflow`
