### ISSUE TITLE
Systemd kills containerd after failed restart in v1.19 - destroys cluster

### ISSUE THREAD

**Issue by erdos4d** [ubuntu/microk8s#1722]
I'm having a very frustrating issue with systemd killing my containerd service after it refuses to restart, resulting in complete loss of my cluster. It happens very reliably within 8 hours of the cluster being up, I've done it 3 times now in the past day, so I should be able to reproduce it for anyone who wants. I have had it happen on AWS EC2 instances running both Ubuntu 20.04 and 18.04 and using v1.19 stable and edge channels. I am using t3a.large (2 CPU, 8GB RAM) instances with only a few containers and my system usage hovers around 10% CPU and 40% RAM, so I don't think it is a resource issue. In the system logs I see that systemd will try to restart microk8s and containerd will not restart, which results in systemd killing it:
```
systemd[1]: Reloading.
systemd[1]: Mounting Mount unit for microk8s, revision 1668...
systemd[1]: Mounted Mount unit for microk8s, revision 1668.
systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
systemd[1]: snap.microk8s.daemon-containerd.service: State 'stop-final-sigterm' timed out. Killing.
```
After that is a long list of processes being killed. I lose the entire cluster with this and only calico comes back. None of my deployments, config maps, etc survive. Not even the dns pods return. I don't know why this is happening as I see nothing in any of the logs to indicate why systemd wants to restart things, or why containerd won't go along. This happens after some hours of the cluster running great with no problems at all. 

I am trying to set up a stable single-node production deployment, so if anyone could give advice on a good host/version/channel combo that works I would appreciate it. This issue is preventing that, so I appreciate any help and ideas anyone has. Thanks.

**Comment by ktsakalozos** [comment]
Hi @erdos4d,

Could you attach the `microk8s.inspect` tarball so we look at the logs and try to find any clue on what may be happening? It would also be great is we had some insight on the workload you run so we can try to reproduce the issue.

Thanks.

**Comment by erdos4d** [comment]
Hi @ktsakalozos, thanks for taking the time to answer. I reproduced it with v1.19/stable for you. Attached are two tarballs, one before the incident and one after. It ran stable as a rock for about 6 hours before this happened. Then the same syslog output as I mentioned above, and systemd killed the entire cluster, with only calico coming back up afterwards. My workloads are 3 postgres containers, 2 django website containers, an email server container, and a mail client container. I can reproduce this very reliably, so let me know if you want anything more. 

[inspection-report-20201109_151529.tar.gz](https://github.com/ubuntu/microk8s/files/5513670/inspection-report-20201109_151529.tar.gz)
[inspection-report-20201109_221834.tar.gz](https://github.com/ubuntu/microk8s/files/5513672/inspection-report-20201109_221834.tar.gz)
