### ISSUE TITLE
Error from server (NotFound): mutatingwebhookconfigurations.admissionregistration.k8s.io "katib-mutating-webhook-config" not found

### ISSUE THREAD

**Issue by shrinidhisuresha** [ubuntu/microk8s#1723]
Hi Team,

Im facing issues when i enable kubeflow like below attaching inspect logs as well.
@microk8s:~$ microk8s enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for DNS and storage plugins to finish setting up
Deploying Kubeflow...
Kubeflow deployed.
Waiting for operator pods to become ready.
Waited 0s for operator pods to come up, 30 remaining.
Waited 15s for operator pods to come up, 30 remaining.
Waited 30s for operator pods to come up, 29 remaining.
Waited 45s for operator pods to come up, 29 remaining.
Waited 60s for operator pods to come up, 28 remaining.
Waited 75s for operator pods to come up, 28 remaining.
Waited 90s for operator pods to come up, 28 remaining.
Waited 105s for operator pods to come up, 26 remaining.
Waited 120s for operator pods to come up, 24 remaining.
Waited 135s for operator pods to come up, 21 remaining.
Waited 150s for operator pods to come up, 20 remaining.
Waited 165s for operator pods to come up, 20 remaining.
Waited 180s for operator pods to come up, 20 remaining.
Waited 195s for operator pods to come up, 20 remaining.
Waited 210s for operator pods to come up, 20 remaining.
Waited 225s for operator pods to come up, 19 remaining.
Waited 240s for operator pods to come up, 18 remaining.
Waited 255s for operator pods to come up, 16 remaining.
Waited 270s for operator pods to come up, 13 remaining.
Waited 285s for operator pods to come up, 7 remaining.
Waited 300s for operator pods to come up, 4 remaining.
Waited 315s for operator pods to come up, 4 remaining.
Waited 330s for operator pods to come up, 4 remaining.
Waited 345s for operator pods to come up, 3 remaining.
Waited 360s for operator pods to come up, 2 remaining.
Operator pods ready.
Waiting for service pods to become ready.
Kubeflow could not be enabled:
Error from server (NotFound): mutatingwebhookconfigurations.admissionregistration.k8s.io "katib-mutating-webhook-config" not found
Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "katib-validating-webhook-config" not found

Command '('microk8s-kubectl.wrapper', 'delete', 'mutatingwebhookconfigurations/katib-mutating-webhook-config', 'validatingwebhookconfigurations/katib-validating-webhook-config')' returned non-zero exit status 1
Failed to enable kubeflow

Thanks
[inspection-report-20201109_062622.tar.gz](https://github.com/ubuntu/microk8s/files/5508504/inspection-report-20201109_062622.tar.gz)

Shrinidhi

**Comment by ralfstx** [comment]
According to this [comment on #1698](https://github.com/ubuntu/microk8s/issues/1698#issuecomment-731260701), a fix for this issue is included in microk8s `1.20/stable`.

    sudo snap install microk8s --classic --channel=1.20/edge
