### ISSUE TITLE
docker-proxy

### ISSUE THREAD

**Issue by AdamIsrael** [ubuntu/microk8s#173]
Ubuntu 18.04.1
microk8s: v1.12.2 (266)

I was trying to `docker-compose up -d` a [Wordpress service](https://docs.docker.com/compose/wordpress/) with a port forward, using the microk8s docker and the exported DOCKER_HOST, but it failed:

```
driver failed programming external connectivity on endpoint hs-subscriptions_wordpress_1
(2b0dae5c331d1cf6a67c6b839631bdcd430c1cb756309f8a6d18c2cf5e98f46b): Error starting userland proxy:
```

This led me to discovering that `/snap/microk8s/current/usr/bin/docker-proxy` throws a `segmentation fault (core dumped)`. dmesg shows:

```
docker-proxy[6615]: segfault at 400318 ip 00007f3d759db949 sp 00007ffc0c293a90 error 7 in ld-2.23.so[7f3d759d8000+26000]
```

This might be related to issue #152, but I'm not familiar enough with how docker-proxy should work in this context.

**Comment by ktsakalozos** [comment]
Hi @AdamIsrael ,

We plan to decouple microk8s from the docker you might want to use. Right now it is not recommended to have docker deployed next to microk8s. We intend to lift this constraint. That means that you will be able to install docker with whatever method & version you desire and also that you will not be able to  use the docker cli coming with microk8s.

We appreciate your feedback and thank you for using microk8s.

**Comment by isutton** [comment]
I'm running 1.12/stable (267) on a recently installed Ubuntu 18.04.1 (not server) and am getting the very same behavior. Tried the same at a recently installed box (same OS version) and got the same results.

For my use, I just need to run Docker and microk8s on the same development box, and am fine with microk8s one.

Are you aware of any temporary workaround to be able to publish ports on microk8s Docker?

**Comment by ktsakalozos** [comment]
@isutton the only workaround I have until now is to not use the port proxy and use the hosts network to expose you service:
```
microk8s.docker run --network host <your_image>
```

**Comment by ktsakalozos** [comment]
@isutton there is also the option to use kubernetes to test your containers instead of docker run:

For example, after building and tagging you container with `dontrebootme/microbot:v1` you can:
```
microk8s.kubectl run microbot --image=dontrebootme/microbot:v1
microk8s.kubectl expose deployment microbot --type=NodePort --port=80 --name=microbot-service
```
and use the ClusterIP+port or the randomly selected nodeport to see your app.

**Comment by flixr** [comment]
> We plan to decouple microk8s from the docker you might want to use. Right now it is not recommended to have docker deployed next to microk8s. We intend to lift this constraint. That means that you will be able to install docker with whatever method & version you desire and also that you will not be able to use the docker cli coming with microk8s.

@ktsakalozos That would be great!
The problems with another dockerd next to microk8s makes it unfortunately unusable to me for now...
Is there an issue for this so that I could get more info, track progress and possibly help with debugging?

**Comment by calohmn** [comment]
We experienced the same issue with 1.13.2/edge (383) on Ubuntu 18.04, getting `Failed to allocate and map port: Error starting userland proxy: , retry: 1` errors when using the microk8s docker.

As a workaround, we found that the "userland proxy" can either be deactivated or a path to a separate `docker-proxy` binary can be set.

That would be editing
`/var/snap/microk8s/current/args/docker-daemon.json`
and using either
````
{
  "insecure-registries" : ["localhost:32000"],
  "userland-proxy-path": "/path/to/separately/downloaded/docker-proxy"
}
````
or
````
{
  "insecure-registries" : ["localhost:32000"],
  "userland-proxy": false
}
````
(Note there might still be an issue with disabling the userland-proxy (see https://github.com/moby/moby/issues/14856).)

**Comment by xgenvn** [comment]
@calohmn for the option 1, can you help us with the link to download docker-proxy? I search around but it seems the docker-proxy is actually `docker-proxy-current` that locates under `/usr/libexec/docker`? Since option 2 is not safe, I want to try the option 1.

**Comment by calohmn** [comment]
@xgenvn I've used the `docker-proxy` contained in
https://download.docker.com/linux/static/stable/x86_64/docker-18.06.1-ce.tgz
(Ie. I've not installed the docker package but instead have just extracted this one file from the above archive.)

**Comment by Soullivaneuh** [comment]
Based on @calohmn solution, this is what I added on my zsh autoload:

```bash
DOCKERD_SNAP_ARGS=/var/snap/microk8s/current/args/dockerd
DOCKERD_ARGS="--userland-proxy=false"

grep --quiet --line-regexp --fixed-strings -- ${DOCKERD_ARGS} ${DOCKERD_SNAP_ARGS} \
  || echo ${DOCKERD_ARGS} | sudo tee --append ${DOCKERD_SNAP_ARGS}
```

Works great.
