### ISSUE TITLE
The connection to the server 127.0.0.1:16443 was refused

### ISSUE THREAD

**Issue by wayneconnolly** [ubuntu/microk8s#1730]
Hi - I have the following setup. 3 nodes.  

All 3 nodes have a:
1. Ubuntu 20.04 (sudo apt update/upgrade all confirm latest)
2. microk8s 1.19  `sudo snap refresh microk8s --classic --channel=1.19`
3. `microk8s enable dns dashboard helm storage`
4. `microk8s enable metallb: 3 x IPs`
5. Other services running: Traefik, Kubeless, Longhorn
6. No CPU, memory or disk pressure

Recently the master failed, the other 2 nodes are running fine and still serving content although some services are hindered. By default HA is enabled on 1.19 channel. I also did a snap refresh of 1.19. That didnt fix anything. 
```
kubectl get no
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

also
```
microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```

Inspection report attached. Actions taken: 

1. microk8s.stop/start; 
2. reboot. 
3. Confirmed swap is off..
4. sudo snap refresh microk8s --classic --channel=1.19

[inspection-report-20201112_114440.tar.gz](https://github.com/ubuntu/microk8s/files/5534712/inspection-report-20201112_114440.tar.gz)

**Comment by wayneconnolly** [comment]
```
microk8s remove-node k1 --force
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
Node k1 does not exist in Kubernetes.
```

I tried the above from all 3 nodes and received the same result.

**Comment by wayneconnolly** [comment]
Don't worry, I'm moving away from microk8s. It's not ready for use.

**Comment by barisvelioglu** [comment]
Unfortunately I have the same problem. Is there anyone knows how to solve the issue ?
