### ISSUE TITLE
Connection to server refused

### ISSUE THREAD

**Issue by JacobBN** [ubuntu/microk8s#1733]
I'm running Ubuntu on a Raspberry Pi 3 B+ as per this tutorial: https://ubuntu.com/tutorials/how-to-kubernetes-cluster-on-raspberry-pi#1-overview

This is what's happening when I run `sudo microk8s.enable dns`:
```
Enabling DNS
Applying manifest
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
Failed to enable dns
```
The api server does look like it's running, it says `active (running)`.

A solution to the same message is provided in this issue: #61 

It says to remove the current microk8s version and install it from the edge channel with `sudo snap install microk8s --edge --classic`.

I'm getting this error having installed it with that command still. Any help is appreciated?

microk8s inspect results:
[inspection-report-20201114_000239.tar.gz](https://github.com/ubuntu/microk8s/files/5539862/inspection-report-20201114_000239.tar.gz)

**Comment by balchua** [comment]
@JacobBN you may want to get the cluster ready first before enabling any addons.

Try `microk8s kubectl get no` see what gives.  Based on the logs you provided, the api server seems to be still starting.  
Another thing, as far as i can tell, 1GB RAM is pretty small though.

**Comment by JacobBN** [comment]
The tutorial implies that a raspberry 3 is sufficient, so I figured it is even though there's only 1GB of ram.

I triggered the `microk8s kubectl get no` command, it's taking ages to execute though I'll put what it says here when it does.

**Comment by balchua** [comment]
IIRC the recommendation is around 4G RAM.
