### ISSUE TITLE
capital letters in hostname is not supported

### ISSUE THREAD

**Issue by hesperup** [ubuntu/microk8s#1736]
This machine's hostname contains capital letters and/or underscores.
  This is not a valid name for a Kubernetes node, causing node registration to fail.

[inspection-report-20201115_045252.tar.gz](https://github.com/ubuntu/microk8s/files/5541456/inspection-report-20201115_045252.tar.gz)

**Comment by balchua** [comment]
@hesperup thanks.  Yes you're right.  Kubernetes normalizes the hostname to all small letters.  You try one of the suggested way from the docs.
https://microk8s.io/docs/troubleshooting#heading--common-issues in the section "Node is not Ready when RBAC is enabled.".  See if it resolves your issue.
