### ISSUE TITLE
Pods scheduled on non-host node in the cluster don't have internet access

### ISSUE THREAD

**Issue by tamimjabban** [ubuntu/microk8s#1737]
Please find the inspection-report here: [inspection-report-20201116_072520.tar.gz](https://github.com/ubuntu/microk8s/files/5544117/inspection-report-20201116_072520.tar.gz).

`sudo iptables -P FORWARD ACCEPT` does not solve my problem.

**Comment by ktsakalozos** [comment]
Hi @tamimjabban 

If I understand the issue correctly you have two nodes and the pods in one of them cannot reach the internet. Is the problematic node `segubtjabban001`? I assume you already checked for firewalls.

**Comment by tamimjabban** [comment]
@ktsakalozos The problem is with pods scheduled on the second machine (not segubtjabban001 as it is the main/host machine, and pods schedule there are able to connect to the internet as well as other pods, so there's not a problem here).
