### ISSUE TITLE
Install of MicroK8s : ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by didier-durand** [ubuntu/microk8s#1738]
Hi there,

'brew install microk8s' was working fine on my MacOs until recently. Now, it does not go through and ends the message in title.

Full log below.

Didier

brew install microk8s
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Installing microk8s from ubuntu/microk8s
==> Downloading https://files.pythonhosted.org/packages/06/8c/eb8a0ae49eba5be054ca32b3a1dca432baee1d83c4f125d276c6a5fd2d20/virtualenv-20.1.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/b4e86049c816dde47c7a914a6db0f94a5688cb385de88d3bb08edd041e561aa6--virtualenv-20.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c316d7b95f46c669dd9c15aaeecbb48c7d0aeb88c40/appdirs-1.4.4.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/d46628d315f103ea527907020cf5f6c94365bbb549783f75a794526482afb672--appdirs-1.4.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/83/1eba07997b8ba58d92b3e51445d5bf36f9fba9cb8166bcae99b9c3464841/distlib-0.3.1.zip
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/b25916e85753e80fccf86f2f1ba088b86d1a82c93cd36bdb72613c81cb830c55--distlib-0.3.1.zip
==> Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/6132211d03cc3113b135a5b72510e3b6ea1df5bf527eb89d71c3f45085c252a7--filelock-3.0.12.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b8/e2/a3a86a67c3fc8249ed305fc7b7d290ebe5e4d46ad45573884761ef4dea7b/certifi-2020.4.5.1.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/bffbbd7ee41c28944ae86910ee924f450d919d2915c7825db25095d2381ed7a8--certifi-2020.4.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/de28644dd0ba2aaf30228e9b28ba90366e333e7a34e1b1f97cf85d0edd0cb278--chardet-3.0.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/27/6f/be940c8b1f1d69daceeb0032fee6c34d7bd70e3e649ccac0951500b4720e/click-7.1.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/729f15182b3d73a61df6c5b70fb07736c3a57abd09b7fde46af074f5787e42dd--click-7.1.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/65/c4/80f97e9c9628f3cac9b98bfca0402ede54e0563b56482e3e6e45c43c4935/idna-2.7.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/aba6aff23ff0ee31279add4664bd5f407a590ad2a0ac29747f5e569a51e8cedf--idna-2.7.tar.gz
==> Downloading https://files.pythonhosted.org/packages/58/0d/c816f5ea5adaf1293a1d81d32e4cdfdaf8496973aa5049786d7fdb14e7e7/jsonschema-2.5.1.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/968a9462d392b9f0f5fbeaf0bd717c942279f76e63daf6f0fa733a7a78ced88a--jsonschema-2.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/71/fc/7c8e01f41a6e671d7b11be470eeb3d15339c75ce5559935f3f55890eec6b/progressbar33-2.4.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/4f671409b54c153caf3929a5a9210e036096c54fdbd567619affcd6156fbc00d--progressbar33-2.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/97/10/92d25b93e9c266c94b76a5548f020f3f1dd0eb40649cb1993532c0af8f4c/requests-2.20.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/b41510c418b03cfb53cff6ccb749c551377cb242100e0f7a6ed9a1419e5605c5--requests-2.20.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f3/94/67d781fb32afbee0fffa0ad9e16ad0491f1a9c303e14790ae4e18f11be19/requests-unixsocket-0.1.5.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/079163d4a38fd48851f914d3018dc464b95e7ef341f9cc40998303f4bf7f0bfa--requests-unixsocket-0.1.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f0/07/26b519e6ebb03c2a74989f7571e6ae6b82e9d7d81b8de6fcdbfc643c7b58/simplejson-3.8.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/c394b64dcdc4fbf8ad5b5bd86402b48123ae4275fdc917d0b0c3a2934bc0cc7f--simplejson-3.8.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b9/19/5cbd78eac8b1783671c40e34bb0fa83133a06d340a38b55c645076d40094/toml-0.10.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/8dd2734c2fe98588801dd538809a3da7987291bd858dfbad935cfabd46090cbb--toml-0.10.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fd/fa/b21f4f03176463a6cccdb612a5ff71b927e5224e83483012747c12fc5d62/urllib3-1.24.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/17afd9f91be6a5b62202c12b7e2fdba3860182bd630f4912fd306850ff49619c--urllib3-1.24.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/553d732b4cf117039b60aab1f75ac3e6f6869a9fa3127b4107984fa5b084a00b--wheel-0.34.2.tar.gz
==> Downloading https://github.com/ubuntu/microk8s/archive/installer-v2.0.1.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/10969f61ddb5fe415263d903413885ed4d952f7c98dc5a39d9815972e168bc0f--microk8s-installer-v2.0.1.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/microk8s--homebrew-virtualenv-20201116-58743-1k9k33e/target/vendor --install-scripts=/pri
Last 15 lines from /Users/ddurand/Library/Logs/Homebrew/microk8s/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/microk8s--homebrew-virtualenv-20201116-58743-1k9k33e/target/vendor
--install-scripts=/private/tmp/microk8s--homebrew-virtualenv-20201116-58743-1k9k33e/target/vendor/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/ubuntu/homebrew-microk8s/issues

**Comment by didier-durand** [comment]
Additional info : 'setuptools' is already installed on my machine

pip install setuptools
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (41.4.0)**

**Comment by joedborg** [comment]
Thanks for the report @didier-durand.  What happens if you try 

```
python3 -m pip install setuptools
```

As a note, MicroK8s relies on Python3, this might be the underlying issue (if only Py2 is installed).

**Comment by didier-durand** [comment]
@joedborg : there you go. There is one bizarre thing: after I upgrade to last pip, python3 pip install doesn't see it, it seems. It still proposes me to upgrade 20.2.4. See final chun,.
Didier 

python3 -m pip install setuptools
Requirement already satisfied: setuptools in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (41.2.0)
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

ddurand@macbook049 microk8s-akri % pip install --upgrade pip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading https://files.pythonhosted.org/packages/cb/28/91f26bd088ce8e22169032100d4260614fc3da435025ff389ef1d396a433/pip-20.2.4-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 736kB/s 
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
Successfully installed pip-20.2.4

ddurand@macbook049 microk8s-akri % python3 -m pip install setuptools
Requirement already satisfied: setuptools in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (41.2.0)
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by joedborg** [comment]
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages 

Makes me think something's awry, as this path isn't part of homebrew.  Is Python3 installed via homebrew?

```brew install python3```

If so, could you please try

```brew reinstall python3```

in order to setup symlinks etc.

**Comment by didier-durand** [comment]
Yes, python3 was installed via homebrew: see below. But you were right: `brew reinstall python3 ` did it. Execution log added for others having same issue.

Thanks a lot! I close ticket

Didier

brew install python3
$Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 73 formulae.
==> Updated Casks
appcode             dashlane            maccy               opera-developer     quaternion          qv2ray              sublime-merge       synology-chat

Warning: python@3.9 3.9.0_1 is already installed, it's just not linked
You can use `brew link python@3.9` to link this version.


ddurand@macbook049 microk8s-akri % brew reinstall python3
Warning: Building python@3.9 from source:
  The bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

==> Downloading https://files.pythonhosted.org/packages/a7/e0/30642b9c2df516506d40b563b0cbd080c49c6b3f11a70b4c7a670f13a78b/setuptools-50.3.2.zip
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/6c4cd84935cccfee61e433509bdda7951ea6b77ae5db203b1e708eea72d93603--setuptools-50.3.2.zip
==> Downloading https://files.pythonhosted.org/packages/0b/f5/be8e741434a4bf4ce5dbc235aa28ed0666178ea8986ddc10d035023744e6/pip-20.2.4.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/8420c2f6f4c2831dfbd1b0e1caa05c0c044729c31b52f8884a785a56038ad0e7--pip-20.2.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/83/72/611c121b6bd15479cb62f1a425b2e3372e121b324228df28e64cc28b01c2/wheel-0.35.1.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/1aa1a9563d6af09f2712c180679dfd512aac6c710fc3fb573175e88eaa7c6de3--wheel-0.35.1.tar.gz
==> Downloading https://www.python.org/ftp/python/3.9.0/Python-3.9.0.tar.xz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/d37370983bfa2dfe731256050c2097e61210550756783e4623a6eb9a8812b210--Python-3.9.0.tar.xz
==> Reinstalling python@3.9 
==> ./configure --prefix=/usr/local/Cellar/python@3.9/3.9.0_1 --enable-ipv6 --datarootdir=/usr/local/Cellar/python@3.9/3.9.0_1/share --datadir=/usr/local/Cella
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python@3.9/3.9.0_1
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python@3.9/3.9.0_1/share/python@3.9
==> /usr/local/Cellar/python@3.9/3.9.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.9/3.9.0_1
==> /usr/local/Cellar/python@3.9/3.9.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.9/3.9.0_1
==> /usr/local/Cellar/python@3.9/3.9.0_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python@3.9/3.9.0_1
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.9/3.9.0_1: 9,224 files, 136.2MB, built in 2 minutes 44 seconds
Removing: /usr/local/Cellar/python@3.9/3.9.0... (9,236 files, 136.5MB)
ddurand@macbook049 microk8s-akri % brew install microk8s
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 7 formulae.

==> Installing microk8s from ubuntu/microk8s
==> Downloading https://files.pythonhosted.org/packages/06/8c/eb8a0ae49eba5be054ca32b3a1dca432baee1d83c4f125d276c6a5fd2d20/virtualenv-20.1.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/b4e86049c816dde47c7a914a6db0f94a5688cb385de88d3bb08edd041e561aa6--virtualenv-20.1.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/d7/d8/05696357e0311f5b5c316d7b95f46c669dd9c15aaeecbb48c7d0aeb88c40/appdirs-1.4.4.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/d46628d315f103ea527907020cf5f6c94365bbb549783f75a794526482afb672--appdirs-1.4.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/2f/83/1eba07997b8ba58d92b3e51445d5bf36f9fba9cb8166bcae99b9c3464841/distlib-0.3.1.zip
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/b25916e85753e80fccf86f2f1ba088b86d1a82c93cd36bdb72613c81cb830c55--distlib-0.3.1.zip
==> Downloading https://files.pythonhosted.org/packages/14/ec/6ee2168387ce0154632f856d5cc5592328e9cf93127c5c9aeca92c8c16cb/filelock-3.0.12.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/6132211d03cc3113b135a5b72510e3b6ea1df5bf527eb89d71c3f45085c252a7--filelock-3.0.12.tar.gz
==> Downloading https://files.pythonhosted.org/packages/6b/34/415834bfdafca3c5f451532e8a8d9ba89a21c9743a0c59fbd0205c7f9426/six-1.15.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/e99698a932bde9f5fb8ca552923ae339984f284e1c7764df95c12175f573c0d7--six-1.15.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b8/e2/a3a86a67c3fc8249ed305fc7b7d290ebe5e4d46ad45573884761ef4dea7b/certifi-2020.4.5.1.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/bffbbd7ee41c28944ae86910ee924f450d919d2915c7825db25095d2381ed7a8--certifi-2020.4.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fc/bb/a5768c230f9ddb03acc9ef3f0d4a3cf93462473795d18e9535498c8f929d/chardet-3.0.4.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/de28644dd0ba2aaf30228e9b28ba90366e333e7a34e1b1f97cf85d0edd0cb278--chardet-3.0.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/27/6f/be940c8b1f1d69daceeb0032fee6c34d7bd70e3e649ccac0951500b4720e/click-7.1.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/729f15182b3d73a61df6c5b70fb07736c3a57abd09b7fde46af074f5787e42dd--click-7.1.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/65/c4/80f97e9c9628f3cac9b98bfca0402ede54e0563b56482e3e6e45c43c4935/idna-2.7.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/aba6aff23ff0ee31279add4664bd5f407a590ad2a0ac29747f5e569a51e8cedf--idna-2.7.tar.gz
==> Downloading https://files.pythonhosted.org/packages/58/0d/c816f5ea5adaf1293a1d81d32e4cdfdaf8496973aa5049786d7fdb14e7e7/jsonschema-2.5.1.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/968a9462d392b9f0f5fbeaf0bd717c942279f76e63daf6f0fa733a7a78ced88a--jsonschema-2.5.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/71/fc/7c8e01f41a6e671d7b11be470eeb3d15339c75ce5559935f3f55890eec6b/progressbar33-2.4.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/4f671409b54c153caf3929a5a9210e036096c54fdbd567619affcd6156fbc00d--progressbar33-2.4.tar.gz
==> Downloading https://files.pythonhosted.org/packages/97/10/92d25b93e9c266c94b76a5548f020f3f1dd0eb40649cb1993532c0af8f4c/requests-2.20.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/b41510c418b03cfb53cff6ccb749c551377cb242100e0f7a6ed9a1419e5605c5--requests-2.20.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f3/94/67d781fb32afbee0fffa0ad9e16ad0491f1a9c303e14790ae4e18f11be19/requests-unixsocket-0.1.5.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/079163d4a38fd48851f914d3018dc464b95e7ef341f9cc40998303f4bf7f0bfa--requests-unixsocket-0.1.5.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f0/07/26b519e6ebb03c2a74989f7571e6ae6b82e9d7d81b8de6fcdbfc643c7b58/simplejson-3.8.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/c394b64dcdc4fbf8ad5b5bd86402b48123ae4275fdc917d0b0c3a2934bc0cc7f--simplejson-3.8.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b9/19/5cbd78eac8b1783671c40e34bb0fa83133a06d340a38b55c645076d40094/toml-0.10.0.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/8dd2734c2fe98588801dd538809a3da7987291bd858dfbad935cfabd46090cbb--toml-0.10.0.tar.gz
==> Downloading https://files.pythonhosted.org/packages/fd/fa/b21f4f03176463a6cccdb612a5ff71b927e5224e83483012747c12fc5d62/urllib3-1.24.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/17afd9f91be6a5b62202c12b7e2fdba3860182bd630f4912fd306850ff49619c--urllib3-1.24.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/75/28/521c6dc7fef23a68368efefdcd682f5b3d1d58c2b90b06dc1d0b805b51ae/wheel-0.34.2.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/553d732b4cf117039b60aab1f75ac3e6f6869a9fa3127b4107984fa5b084a00b--wheel-0.34.2.tar.gz
==> Downloading https://github.com/ubuntu/microk8s/archive/installer-v2.0.1.tar.gz
Already downloaded: /Users/ddurand/Library/Caches/Homebrew/downloads/10969f61ddb5fe415263d903413885ed4d952f7c98dc5a39d9815972e168bc0f--microk8s-installer-v2.0.1.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/microk8s--homebrew-virtualenv-20201116-96218-oty2uy/target/vendor --install-scr
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/microk8s--homebrew-virtualenv-20201116-96218-oty2uy/target/vendor --install-scr
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/microk8s--homebrew-virtualenv-20201116-96218-oty2uy/target/vendor --install-scr
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/microk8s--homebrew-virtualenv-20201116-96218-oty2uy/target/vendor --install-scr
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/microk8s--homebrew-virtualenv-20201116-96218-oty2uy/target --install-scripts=/p
==> python3 -s /private/tmp/microk8s--homebrew-virtualenv-20201116-96218-oty2uy/target/bin/virtualenv -p python3 /usr/local/Cellar/microk8s/2.0.1/libexec
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--certifi-20201116-96218-ld
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--chardet-20201116-96218-bp
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--click-20201116-96218-12f5
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--idna-20201116-96218-1iagk
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--jsonschema-20201116-96218
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--progressbar33-20201116-96
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--requests-20201116-96218-j
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--requests-unixsocket-20201
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--simplejson-20201116-96218
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--toml-20201116-96218-cd64d
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--urllib3-20201116-96218-ig
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s--wheel-20201116-96218-1hoe
==> /usr/local/Cellar/microk8s/2.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/microk8s-20201116-96218-pio2gb/micr
🍺  /usr/local/Cellar/microk8s/2.0.1: 1,460 files, 13.9MB, built in 33 seconds
Removing: /Users/ddurand/Library/Caches/Homebrew/microk8s--homebrew-virtualenv--20.0.33.tar.gz... (7.9MB)
ddurand@macbook049 microk8s-akri % microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # CoreDNS
    fluentd              # Elasticsearch-Fluentd-Kibana logging and monitoring
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    storage              # Storage class; allocates storage from host directory
  disabled:
    ambassador           # Ambassador API Gateway and Ingress
    cilium               # SDN, fast with full network policy
    dashboard            # The Kubernetes dashboard
    gpu                  # Automatic enablement of Nvidia CUDA
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    istio                # Core Istio service mesh services
    jaeger               # Kubernetes Jaeger operator with its simple config
    knative              # The Knative framework on Kubernetes.
    kubeflow             # Kubeflow for easy ML deployments
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    multus               # Multus CNI enables attaching multiple network interfaces to pods
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
