### ISSUE TITLE
microk8s.enable dns not working in snap version 278, 266 if executed too soon.

### ISSUE THREAD

**Issue by carmine** [ubuntu/microk8s#174]
When running --edge or --stable I get the following error when trying to enable dns. For --edge, I get this error

configmap/kube-dns created
error: unable to recognize "/root/snap/microk8s/278/tmp/temp.dns.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

For --stable (or --beta, they are same at the moment), I get the same message, except 266 instead of 278 in the directory path.

**Comment by carmine** [comment]
The issue occurs when the command is executed too soon after the snap has been installed (ie within 10-20 seconds). This can be common when scripted. Suggest adding something to .enable that determines if it is okay to run this command.

**Comment by ktsakalozos** [comment]
This came up also in the install instructions here: https://github.com/geoand/sb-fmp-microk8s . We need a command to check in microk8s is ready. For example

```
# Return 0 if microk8s is ready 1 otherwise
microk8s.ready
# Wait forever for microk8s to get ready
microk8s.ready --wait
# Wait with timeout of X seconds for microk8s to get ready
microk8s.ready --wait --timeout X
```
