### ISSUE TITLE
"microk8s help" command not working on MacOS

### ISSUE THREAD

**Issue by Credentive-Sec** [ubuntu/microk8s#1741]
Attempting to run "microk8s help" from the command line on the MacOS version. I receive the following error:

```
> microk8s help              
sudo: microk8s.help: command not found
An error occurred when trying to execute 'sudo microk8s.help' with 'multipass': returned exit code 1.
```

After executing "multipass shell microk8s-vm", I have identified the issue. There is no "microk8s.help" command in the vm. Executing "microk8s help" at the command line of the vm returns the expected result.

Either the microk8s.help command should be added or the command "microk8s help" should be passed as is to the vm.

**Comment by joedborg** [comment]
Hi @Credentive-Sec, thanks for raising the issue. 

I believe microk8s hasn't installed inside the VM correctly.  Could you shell back into the VM and run the following command:

```
sudo snap install microk8s --classic
```

And let me know what happens?

Thanks,
Joe

**Comment by Credentive-Sec** [comment]
ubuntu@microk8s-vm:~$ sudo snap install microk8s --classic
snap "microk8s" is already installed, see 'snap help refresh'

**Comment by Credentive-Sec** [comment]
I want to be careful to follow your instructions to the letter rather than making assumptions - but should I uninstall and reinstall the snap?

**Comment by joedborg** [comment]
@Credentive-Sec ah, I've just realised it's because we don't actually have a dedicated help section, which is why this isn't working.  Instead, you should run
```
microk8s --help
```
I agree this should be handled better though, so I'll have a think about how that could be.

**Comment by Credentive-Sec** [comment]
microk8s --help works for now. Thanks for your help!
