### ISSUE TITLE
microk8s should nat dns through its host

### ISSUE THREAD

**Issue by camille-rodriguez** [ubuntu/microk8s#1743]
I installed microk8s on a VM in a proxied environment. I'm trying to bootstrap that machine with juju on the same host. 
I already set up the provy in /var/snap/microk8s/current/args/containerd-env (no_proxy, http_proxy, https_proxy).
I also set up the same in my juju command :

juju bootstrap microk8s microk8s --model-default juju-no-proxy="10.1.0.0/16,10.152.183.0/24" --model-default juju-http-proxy="http://squid.internal:3128" --model-default juju-https-proxy="http://squid.internal:3128"

But when doing so, errors logs show up in the controller pods because it cannot resolve the proxy "squid.internal". 
$ microk8s.kubectl logs controller-0 -n controller-microk8s api-server
Installing Dashboard...
curl: (5) Could not resolve proxy: squid.internal
curl: (5) Could not resolve proxy: squid.internal
curl: (5) Could not resolve proxy: squid.internal

However, if I do a nslookup on the host, it resolves it easily:
$ nslookup squid.internal
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   squid.internal
Address: 91.189.89.11

In my perspective, microk8s should pickup the dns setup from its host. The current behavior makes it difficult to work in proxied environment.

**Comment by balchua** [comment]
@camille-rodriguez i think you maybe able to change the coredns `ConfigMap` change `forward 8.8.8.8 8.8.4.4` to `forward . /etc/resolv.conf`.
You may need to delete the pod though.

Care to try that?

**Comment by ktsakalozos** [comment]
There is a PR [1] and a respective issue [2] on this subject.

[1] https://github.com/ubuntu/microk8s/pull/1625
[2] https://github.com/ubuntu/microk8s/issues/1606
