### ISSUE TITLE
microk8s is clustered but kubectl does not detect additional nodes

### ISSUE THREAD

**Issue by camille-rodriguez** [ubuntu/microk8s#1746]
I created a 3 nodes cluster for microk8s in aws. The process was the following:
- install juju on node 1
- install microk8s on all 3 nodes
- enable storage and dns on all 3 nodes
- juju bootstrap microk8s on node 1
- microk8s.add-node from node 1 to get the nodes 2 and 3 in the cluster

Microk8s status does see the 3 nodes in HA :
$ microk8s.status
microk8s is running 
high-availability: yes 
  datastore master nodes: 172.31.31.122:19001 172.31.11.217:19001 172.31.40.221:19001
  datastore standby nodes: none

But kubernetes is not aware of it :
$ microk8s.kubectl get nodes -A
NAME               STATUS   ROLES    AGE   VERSION
ip-172-31-31-122   Ready    <none>   14m   v1.19.3-34+a56971609ff35a

Each node returns only one node when doing "kubectl get nodes"

Here is the microk8s inspect result: 
[inspection-report-20201117_151311.tar.gz](https://github.com/ubuntu/microk8s/files/5554378/inspection-report-20201117_151311.tar.gz)

**Comment by camille-rodriguez** [comment]
And the clustering is working, because I can see the same status on all 3 nodes with kubectl. However, this causes applications such as daemonsets to not deploy correctly, since kubernetes believes it is only deployed on one node

**Comment by balchua** [comment]
Hi
Can you resolve the hostname from each other node?  Example `ip-172-31-31-122` from the node `ip-172-31-11-217`.

**Comment by ktsakalozos** [comment]
@camille-rodriguez could you attach an inspection tarball of one of the nodes that does not register?

**Comment by camille-rodriguez** [comment]
Let me try to reproduce it and gather this info. I destroyed the cluster since it was not functional

**Comment by camille-rodriguez** [comment]
@balchua name resolution looks fine

ubuntu@ip-172-31-26-110:~$ ping ip-172-31-12-253
PING ip-172-31-12-253.ec2.internal (172.31.12.253) 56(84) bytes of data.
64 bytes from ip-172-31-12-253.ec2.internal (172.31.12.253): icmp_seq=1 ttl=64 time=0.627 ms
64 bytes from ip-172-31-12-253.ec2.internal (172.31.12.253): icmp_seq=2 ttl=64 time=0.601 ms
64 bytes from ip-172-31-12-253.ec2.internal (172.31.12.253): icmp_seq=3 ttl=64 time=0.550 ms
^C
--- ip-172-31-12-253.ec2.internal ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2019ms
rtt min/avg/max/mdev = 0.550/0.592/0.627/0.042 ms
ubuntu@ip-172-31-26-110:~$ ping ip-172-31-46-127
PING ip-172-31-46-127.ec2.internal (172.31.46.127) 56(84) bytes of data.
64 bytes from ip-172-31-46-127.ec2.internal (172.31.46.127): icmp_seq=1 ttl=64 time=0.907 ms
64 bytes from ip-172-31-46-127.ec2.internal (172.31.46.127): icmp_seq=2 ttl=64 time=0.880 ms
64 bytes from ip-172-31-46-127.ec2.internal (172.31.46.127): icmp_seq=3 ttl=64 time=0.896 ms
^C
--- ip-172-31-46-127.ec2.internal ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2025ms
rtt min/avg/max/mdev = 0.880/0.894/0.907/0.026 ms
ubuntu@ip-172-31-26-110:~$ 

I was not able to reproduce it though. Following the same steps, this time the nodes are showing up in microk8s.kubectl get nodes
ubuntu@ip-172-31-26-110:~$ microk8s kubectl get nodes
NAME               STATUS   ROLES    AGE     VERSION
ip-172-31-46-127   Ready    <none>   3m39s   v1.19.3-34+a56971609ff35a
ip-172-31-26-110   Ready    <none>   8m6s    v1.19.3-34+a56971609ff35a
ip-172-31-12-253   Ready    <none>   88s     v1.19.3-34+a56971609ff35a


Not too sure what happened the first time. I guess we can close this bug and re-open if this behavior is seen again. Thanks!
