### ISSUE TITLE
Upgrade libnvidia-container library to support Nvidia MIG (Milti-Instance-GPUs) devices

### ISSUE THREAD

**Issue by kentwelcome** [ubuntu/microk8s#1747]
As the title, Nvidia just released a new device A100 with the MIG (Milti-Instance-GPUs) feature.
The libnvidia-container library starts to support this feature since v1.1.0
https://github.com/NVIDIA/libnvidia-container/releases/tag/v1.1.0

Currently, the Microk8s use libnvidia-container@1.0.0 
https://github.com/ubuntu/microk8s/blob/8a712c465e8e8036fa4d980dc2842722cbdd284b/snap/snapcraft.yaml#L541
To support the new GPU device, we need to upgrade the version of libnvidia-container used by Microk8s

**Comment by kentwelcome** [comment]
Just notice there was already a PR to upgrade the Nvidia container runtime this July.
However, seems it didn't work and the PR had been reverted.
https://github.com/ubuntu/microk8s/pull/1381
Is there any information that can explain why the upgrade didn't work?

**Comment by ktsakalozos** [comment]
In [1] users reported the upgrade was breaking the backwards compatibility on 18.04 Ubuntu lts.

We need to revisit the PR and see if we can perform the upgrade seamlessly. 

[1] https://github.com/ubuntu/microk8s/issues/1342
