### ISSUE TITLE
dockerd-env format is not specified in readme.md

### ISSUE THREAD

**Issue by Royco1** [ubuntu/microk8s#175]
I am trying to deploy microk8s behind a proxy, and I have no idea what is the needed format of 
${SNAP_DATA}/args/dockerd-env

it is not specified in the repository.
could you add an example to how this file should ideally look like?

**Comment by ktsakalozos** [comment]
Hi @Royco1 ,

Proxy support in not yet released on the stable channel; we will release it soon.  For now you can get microk8s with proxy support from the edge channel `sudo snap install microk8s --classic --edge`. Microk8s from edge includes a template in  `${SNAP_DAT.A}/args/dockerd-env` that looks like this:

```
# To start dockerd behind a proxy you need to add an HTTPS_PROXY
# environment variable in this file. HTTPS_PROXY is of the following form:
# HTTPS_PROXY=http://username:password@proxy:port/ dockerd. 
# where username: and password@ are optional. eg:
#
# HTTPS_PROXY=https://squid.internal:3128
#
#
# Remember to restart the docker daemon after editing this file:
#
# sudo systemctl restart snap.microk8s.daemon-docker.service
```

Lines with `#` are comments.

Thank you for using microk8s.

**Comment by Royco1** [comment]
Thank you very much for the response!
In addition , is there a way to change the upstream DNS servers in the
kubedns add-on?

**Comment by ktsakalozos** [comment]
After `microk8s.enable dns` can you try a `microk8s.kubectl edit configmaps -n kube-system kube-dns` and update the `upstreamNameservers`? You may need to delete the dns pod so that a new is spawned.

**Comment by ktsakalozos** [comment]
Did this work @Royco1 ? Should I close the issue?

**Comment by Royco1** [comment]
how do I delete the dns pod?

**Comment by ktsakalozos** [comment]
Do a `microk8s.kubectl get po -n kube-system` and spot the dns pod. It should start with `kube-dns-`. Then delete that pod with something like `microk8s.kubectl delete -n kube-system pod/kube-dns-67b548dcff-2dqrk`. Kubernetes will spawn a new pod with the new configuration.

**Comment by Royco1** [comment]
Another thing. How do I configure and edit microk8s's docker daemon.json?
For example I need to add an insecure registry to pull images

On Nov 15, 2018 12:04 PM, "Konstantinos Tsakalozos" <
notifications@github.com> wrote:

Do a microk8s.kubectl get po -n kube-system and spot the dns pod. It should
start with kube-dns-. Then delete that pod with something like microk8s.kubectl
delete -n kube-system pod/kube-dns-67b548dcff-2dqrk. Kubernetes will spawn
a new pod with the new configuration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ubuntu/microk8s/issues/175#issuecomment-438985766>, or mute
the thread

**Comment by ktsakalozos** [comment]
The dockerd configuration files are normally found under /var/snap/microk8s/current/args/:
- ${SNAP_DATA}/args/docker-daemon.json: is the file you are looking for. 
- ${SNAP_DATA}/args/dockerd-env: holds environment variables set for dockerd,  and
- ${SNAP_DATA}/args/dockerd: are the cli arguments (https://docs.docker.com/engine/reference/commandline/dockerd/)

You can edit the above files and then you will need to restart dockerd with `sudo systemctl restart snap.microk8s.daemon-docker.service`. Also note that `microk8s.enable registry` will start an insecure registry on `localhost:32000`

**Comment by Royco1** [comment]
you can close the issue.
thank you for the support

**Comment by ktsakalozos** [comment]
my pleasure.
