### ISSUE TITLE
Echo text refers to dqlite in 002-switch-to-flannel-etcd upgrade-scripts

### ISSUE THREAD

**Issue by mercimat** [ubuntu/microk8s#1752]
At the beginning of the following scripts, the "echo" command mentions "dqlite upgrade" while the scripts are about switching to flannel-etcd. See:
https://github.com/ubuntu/microk8s/blob/master/upgrade-scripts/002-switch-to-flannel-etcd/commit-master.sh#L4
https://github.com/ubuntu/microk8s/blob/master/upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh#L4

This seems to be a copy/paste from similar scripts in upgrade-scripts/001-switch-to-dqlite.

I also noticed a small typo here that could be fixed at the same time:
https://github.com/ubuntu/microk8s/blob/master/upgrade-scripts/002-switch-to-flannel-etcd/rollback-master.sh#L44

I created a PR with a suggestion of fix. Please let me know in case you think there are further changes to be made.

**Comment by ktsakalozos** [comment]
Thank you for the fixes @mercimat.
