### ISSUE TITLE
Kubeflow can't be enabled after Nov. 2020 microk8s releases (always timeout)

### ISSUE THREAD

**Issue by chen98** [ubuntu/microk8s#1754]
Please run `microk8s inspect` and attach the generated tarball to this issue.

Kubeflow can't be enabled after microk8s Nov. 2020 releases.
https://ubuntu.com/tutorials/deploy-kubeflow-ubuntu-windows-mac#3-install-microk8s

Tried versions, latest/edge, 1.19/edge, 1.18/edge,
latest/stable, 1.19/stable, 1.18/stable

All timeout since the week of 11/16/2020.

Error message:
...
Waited 330s for operator pods to come up, 1 remaining.
Operator pods ready.
Waiting for service pods to become ready.
Kubeflow could not be enabled:
error: timed out waiting for the condition on pods/oidc-gatekeeper-7dbfc94964-r89cg
Command '('microk8s-kubectl.wrapper', 'wait', '--namespace=kubeflow', '--for=condition=Ready', 'pod', '--timeout=30s', '--all')' returned non-zero exit status 1
********************************* cause:
kubeflow          pod/oidc-gatekeeper-7dbfc94964-r89cg               0/1     CrashLoopBackOff   34         152m
(this service refuse to come up)
*******************************
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1821/inspection-report-20201119_172119.tar.gz
ubuntu@ip-172-31-52-231:~$ cd /var/snap/microk8s/1821/
*********************************
inspection file attached.

Need to know which microk8s still working with Kubeflow.  Thanks.
[inspection-report-20201119_172119.tar.gz](https://github.com/ubuntu/microk8s/files/5568842/inspection-report-20201119_172119.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @chen98, I see the oidc-gatekeeper pod crashlooping but I am not sure why. Maybe @knkski can spot the problem.

**Comment by GdMacmillan** [comment]
There is a known issue in the kubeflow repo about this https://github.com/kubeflow/kubeflow/issues/5407

**Comment by knkski** [comment]
@chen98: Can you run `microk8s kubectl logs -nkubeflow --tail 1000 -l juju-app=oidc-gateheeper` and copy the output to this issue?

**Comment by chen98** [comment]
Yes it is fixed now after build 1826.
sudo snap install microk8s --classic --channel=latest/edge
I just tried with build 1827 (latest) up successfully.  Also changed disk to 80G instead of 60G.

Thank you.

**Comment by knkski** [comment]
Sounds good. I'm going to close this since it's working for you, feel free to reopen if you hit the same issue again.

**Comment by chen98** [comment]
The "oidc gatekeeper crash" issue is not there anymore.  However, we can't get kubeflow dashboard (like jupyter notebook or pipeline) anymore with all the latest build.
Anyway to get aroud the issue and still get the dashboard?

Thanks.

**Comment by knkski** [comment]
@chen98: Sorry about the slow response on this. Can you try again with the latest version of microk8s (`sudo snap refresh microk8s --channel latest/edge`)?

**Comment by chen98** [comment]
@knkski Yes working no issue with your latest build, v1.20.2  2021-02-01 (1997).  All KF services coming up cleanly.  Be able to access KF dashboard and create new notebook server. Thx.
