### ISSUE TITLE
snap install microk8s : http 503 - cannot install "microk8s": cannot get nonce from store: store server

### ISSUE THREAD

**Issue by didier-durand** [ubuntu/microk8s#1755]
Hi there,

This error is probably more on the side of the Snap Store but it may be useful for Microk8s team to know

On snap install of  microk8s, I sometimes get the message below:

```
error: cannot install "microk8s": cannot get nonce from store: store server
       returned status 503
```

This is transient. If I relaunch the command, it most often goes through successfully.

Didier

**Comment by ktsakalozos** [comment]
Thank you for reporting this @didier-durand. I forwarded your query. We are in the process of upgrading the hardware substrate of the store and this may cause these transient errors. Please let me know if this problem persists.

I appreciate your patience.

**Comment by didier-durand** [comment]
@ ktsakalozos: all good. Thanks for the info! I'll close for now. And re-open if it happens again.
Didier
