### ISSUE TITLE
Cannot use deployment files on Mac

### ISSUE THREAD

**Issue by Credentive-Sec** [ubuntu/microk8s#1756]
[inspection-report-20201120_074433.tar.gz](https://github.com/ubuntu/microk8s/files/5573537/inspection-report-20201120_074433.tar.gz)

Using Mac with microk8s on Multipass.

When trying to create a pod from a deployment file, I receive the following error:

**_> microk8s kubectl create -f reader-deployment.yaml_** 
_error: the path "reader-deployment.yaml" does not exist
An error occurred when trying to execute 'sudo microk8s.kubectl create -f reader-deployment.yaml' with 'multipass': returned exit code 1._

While this error makes perfect sense (the vm can't see the deployment file on the host), the behavior is not optimal. Ideally the microk8s command would transfer the file or open it and read the contents in to the stdin of the microk8s-vm. 

I searched the documentation without success. As a workaround I copied the deployment file with "Multipass transfer" then executed "Multipass shell" to run the kubectl command.

Is there a recommended way to work with deployment files for microk8s on Mac?

**Comment by balchua** [comment]
Install kubectl in your mac.  `microk8s config` will print out the `kubeconfig` which you can then save it to your `$HOME/.kube/config`.
From there you can use the local kubectl.

**Comment by Credentive-Sec** [comment]
That works perfectly, thanks for the advice!

**Comment by Credentive-Sec** [comment]
Shoot, just kidding. I think I ran kubectl from the vm and thought it worked :(

**> microk8s config > ~/.kube/config                                  
> kubectl create -f reader-configmap-deployment.yaml**
error: the path "reader-configmap-deployment.yaml" does not exist
An error occurred when trying to execute 'sudo microk8s.kubectl create -f reader-configmap-deployment.yaml' with 'multipass': returned exit code 1.

**Comment by Credentive-Sec** [comment]
Okay, I have set kubectl as an alias of "microk8s kubectl". That might be my problem -- it may not be using native kubectl

**Comment by balchua** [comment]
Yup.  You need the real kubectl not an alias.

**Comment by Credentive-Sec** [comment]
Indeed, when I deleted the alias, it worked!

**Comment by evilnick** [comment]
I will add a note to the macOS section about this. I guess this is likely to happen with Windows also?

**Comment by Credentive-Sec** [comment]
I'm not sure. Maybe WSLv2 behaves differently? I assume multipass uses WSL under the hood..

**Comment by balchua** [comment]
@Credentive-Sec i dont think the windows version is using WSL2 yet.  Its still based off hyperv by default.
