### ISSUE TITLE
microk8s refresh-certs not creating new kubeconfig

### ISSUE THREAD

**Issue by davidberglund** [ubuntu/microk8s#1757]
I can still access cluster with old kubeconfig after running sudo microk8s refresh-certs. 

```
microk8s refresh-certs
Taking a backup of the current certificates under /var/snap/microk8s/1791/var/log/ca-backup/
Creating new certificates
Signature ok
subject=/C=GB/ST=Canonical/L=Canonical/O=Canonical/OU=Canonical/CN=127.0.0.1
Getting CA Private Key
Signature ok
subject=/CN=front-proxy-client
Getting CA Private Key
1
Creating new kubeconfig file
Stopped.
Started.

The CA certificates have been replaced. Kubernetes will restart the pods of your workloads.
Any worker nodes you may have in your cluster need to be removed and re-joined to become aware of the new CA.
```
[inspection-report-20201120_145250.tar.gz](https://github.com/ubuntu/microk8s/files/5573916/inspection-report-20201120_145250.tar.gz)

**Comment by balchua** [comment]
I noticed that the `keys` used to create the CA certificates are not modified.  The same keys are used to generate the certificates.  
When i delete the `/var/snap/microk8s/certs/*.key`, then re-run `microk8s refresh-certs`, then the old `kubeconfig` will *no* longer be usable.  Is it reasonable to delete the keys, when refreshing the certificates?
