### ISSUE TITLE
Microk8s 266 on [Multipass|VBox] 10.1-full-56 on Mac not launching pods properly

### ISSUE THREAD

**Issue by carmine** [ubuntu/microk8s#176]
I start with the following commands, after which it seems that the pods stay in PENDING. This is on a Mac - macos mojave version 10.14.1. I wonder if it is reproducible on a different host os? I even try running other pods, like nginx, and no luck. On another run, using cached snaps, I saw that several of the pods made it to RUNNING, but were then evicted and remained in PENDING. I print that out after this block:

==> multipass launch -n fred bionic
==> multipass shell fred
~$ sudo snap install microk8s --classic
~$ sudo snap install kubectl --classic
~$ export KUBECONFIG=/snap/microk8s/current/client.config
~$ microk8s.enable dns dashboard
~$ kubectl get pod -n kube-system
NAME                                              READY   STATUS    RESTARTS   AGE
heapster-v1.5.2-74f7978789-j5mnc                  0/4     Pending   0          65s
kube-dns-67b548dcff-zjqs6                         0/3     Pending   0          71s
kubernetes-dashboard-67d4c89764-dtq84             0/1     Pending   0          65s
monitoring-influxdb-grafana-v4-8467db6558-x55p4   0/2     Pending   0          65s

Here's a print out from a run where pods were evicted:
NAME                                              READY   STATUS    RESTARTS   AGE
heapster-v1.5.2-6595b788df-fbbq6                  0/4     Pending   0          11m
kube-dns-67b548dcff-8vngd                         0/3     Pending   0          11m
kube-dns-67b548dcff-mrxh9                         0/3     Evicted   0          12m
kubernetes-dashboard-67d4c89764-g779z             0/1     Evicted   0          12m
kubernetes-dashboard-67d4c89764-zs55n             0/1     Pending   0          11m
monitoring-influxdb-grafana-v4-8467db6558-8gq6l   0/2     Pending   0          12m

Version Information:
=> multipass version
multipass  2018.10.1-full-56-g9ff5e89
multipassd 2018.10.1-full-56-g9ff5e89

=> snap list
Name      Version    Rev   Tracking  Publisher   Notes
core      16-2.35.5  5742  stable    canonical✓  core
kubectl   1.12.2     585   stable    canonical✓  classic
microk8s  v1.12.2    266   stable    canonical✓  classic

=> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by carmine** [comment]
I've tried this with vagrant/virtualbox and 18.04 .. no luck .. same issue .. the pods stay in pending.

**Comment by carmine** [comment]
I've also tried 16.04 / xenial on both multipass, vagrant .. no luck.

**Comment by carmine** [comment]
Turns out the issue was an out of memory issue :(.

**Comment by ktsakalozos** [comment]
Hi @carmine ,

Here is what you can do:

- Check you have a "Ready" node:
```
kubectl get no
```

- Check that the node has no disk or memory presure:
```
kubectl describe no
```
I just tried starting a multipass machine  and got a VM with 1GB of ram:
```
> free -m 
              total        used        free      shared  buff/cache   available
Mem:            985         448          86           0         450         387
Swap:             0           0           0
```

For this reason `kubectl describe no` was reporting `MemoryPressure   True    ...   KubeletHasInsufficientMemory   kubelet has insufficient memory available`

Something else you should be aware of is that we set the eviction policy in the kubelet arguments (https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kubelet#L13).

Thanks

**Comment by carmine** [comment]
Thanks for additional info, that is really helpful, particularly regading the eviction policy. I'll reopen the issue, as I think the the hard eviction limit seems to be too high ..

--eviction-hard="memory.available<500Mi,nodefs.available<1Gi,imagefs.available<1Gi"

The default, according to https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#eviction-policy, seems to be 

memory.available<100Mi

I like that microk8s calls out the limit specifically, but any reason not to use the default of 100Mi? This is microk8s .. :-)

**Comment by ktsakalozos** [comment]
The rational was that on your working station 500MB is too few so microk8s would rather not degrade the overall UX. However I have no facts to back this so let's use the default 100MB and if we see we are taking too much heat we can reconsider.
