### ISSUE TITLE
hostPort get port but pod never leaves scheduling

### ISSUE THREAD

**Issue by johngrabner** [ubuntu/microk8s#1761]
Converting a home server with a public IP from docker-compose to microk8s and ran into 2 issues.
**1) pod with nginx never start
2) IP port not released when deployment deleted. Must stop microk8s to release.**

Note nothing else running. Microk8s installed not in a VM but directly on ubuntu 18.

How to reproduce sequence:

**the only deployment**

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: localhost:32000/nginx:mainline-alpine
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
```
**microk8s kubectl apply -f <the above file>**

```
NAME                     READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
nginx-75f9b56945-zjzd2   0/1     Pending   0          18s   <none>   <none>   <none>           <none>
```

**a long time later**

`microk8s kubectl  delete -f <the above file>`

then try to relaunch my docker-compose and it fails with 

`ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint production_hmt_nginx_1 (bd2968f015acf9d7fda0f74b2b19858663fa41eb5eefa6b8ff522c147f61a1cf): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use`

**so looks like microk8s did take the port.**

`microk8s stop`

then docker-compose can take the port **(ie: microk8s released port only when stop command issued)**.

took down docker-compose, repeated the above, same behavior.

btw, the Microk8s installation was super simple and fast. Good job.

**Comment by johngrabner** [comment]
[inspection-report-20201122_193601.tar.gz](https://github.com/ubuntu/microk8s/files/5580814/inspection-report-20201122_193601.tar.gz)

**Comment by johngrabner** [comment]
Looking at github, I see microk8s ingress also uses hostPort.

Ingress also leaks the hostPort and never gives it back (but it completes scheduling and route traffic to the service).

First the yaml file for the ingress experiment.

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: express-service
          servicePort: 3000
```

**A warning when I apply the ingress**

```
microk8s kubectl apply -f jjg_ingress.yaml 
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.networking.k8s.io/http-ingress created
john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe/k8s/production$ microk8s kubectl get services
NAME              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
kubernetes        ClusterIP   10.152.183.1   <none>        443/TCP    26h
express-service   ClusterIP   None           <none>        3000/TCP   3m18s
```

**Ingress is reported, but no indication of the port**
```
john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe/k8s/production$ microk8s kubectl get ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME           CLASS    HOSTS   ADDRESS   PORTS   AGE
http-ingress   <none>   *                 80      49s
```

**Delete the ingress**
```
john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe/k8s/production$ microk8s kubectl delete -f jjg_ingress.yaml 
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.networking.k8s.io "http-ingress" deleted
```

`confirm ingress is gone`
```
john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe/k8s/production$ microk8s kubectl get ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
No resources found in default namespace.
```


... 10 minutes later

**Now try docker-compose ... port still held by microk8s**

```
Starting production_hmt_py_transcribe_service_1 ... done
426257439daa874a27808eb92f98b87a218328dde): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint production_hmt_nginx_1 (6dbd97ef27f73f563613cba426257439daa874a27808eb92f98b87a218328dde): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Reverify ingress is off and services too**

```
microk8s kubectl get ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
No resources found in default namespace.
john@john-trx40-designare:~/Documents/GitHub/help-me-transcribe/k8s/production$ microk8s kubectl get pos
error: the server doesn't have a resource type "pos"
```

**docker still failing**

```
212a800e2980b0c16cf1f8fdff4bea74440f548d5): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint production_hmt_nginx_1 (d09fffc20318446bb46a0b7212a800e2980b0c16cf1f8fdff4bea74440f548d5): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.

```

**microk8s stop**
[sudo] password for john: 
Stopped.

Docker-compose now can run and allocate ports 80 and 443

**Comment by balchua** [comment]
The `ingress` is defined as a `DaemonSet`. Meaning it runs on all nodes in the cluster.  As you have seen it will use the ports `80` and `443`.

Ingress are meant to be used to access into your services / pods from outside the cluster.

If you use `hostPort` in your container definition make sure you dont run into conflict with any ports in the host.

**Comment by johngrabner** [comment]
I found the problem with hostPort while not using ingress.  Then while exploring for a workaround, I found a similar issue with Ingress while not using hostPort.

**Comment by johngrabner** [comment]
have not seen for a long time
