### ISSUE TITLE
Kubeflow could not be enabled:  (NotFound): mutatingwebhookconfigurations.admissionregistration.k8s.io "katib-mutating-webhook-config"

### ISSUE THREAD

**Issue by BioGeek** [ubuntu/microk8s#1762]
I have installed [microk8s][1] on Windows using the installer. I have enabled some services with `microk8s enable dashboard dns registry`. But when I try to enable  `kubeflow` I get the following error:

    C:\Users\biogeek>microk8s enable kubeflow
    Enabling dns...
    Enabling storage...
    Enabling dashboard...
    Enabling ingress...
    Enabling metallb:10.64.140.43-10.64.140.49...
    Waiting for DNS and storage plugins to finish setting up
    Deploying Kubeflow...
    Kubeflow deployed.
    Waiting for operator pods to become ready.
    Waited 0s for operator pods to come up, 34 remaining.
    Waited 15s for operator pods to come up, 34 remaining.
    [...]
    Waited 390s for operator pods to come up, 2 remaining.
    Operator pods ready.
    Waiting for service pods to become ready.
    Kubeflow could not be enabled:
    Error from server (NotFound): mutatingwebhookconfigurations.admissionregistration.k8s.io "katib-mutating-webhook-config" not found
    Error from server (NotFound): validatingwebhookconfigurations.admissionregistration.k8s.io "katib-validating-webhook-config" not found
    
    Command '('microk8s-kubectl.wrapper', 'delete', 'mutatingwebhookconfigurations/katib-mutating-webhook-config', 'validatingwebhookconfigurations/katib-validating-webhook-config')' returned non-zero exit status 1
    Failed to enable kubeflow
    An error occurred when trying to execute 'sudo microk8s.enable kubeflow' with 'multipass': returned exit code 1.

([Error is similar this Github issue from 2 weeks ago][2], but which hasn't had any response yet.)

Output of `microk8s status --wait-ready`:

    microk8s is running
    addons:
    dashboard: enabled
    dns: enabled
    ingress: enabled
    kubeflow: enabled
    metallb: enabled
    storage: enabled
    cilium: disabled
    fluentd: disabled
    gpu: disabled
    helm: disabled
    helm3: disabled
    istio: disabled
    jaeger: disabled
    knative: disabled
    linkerd: disabled
    metrics-server: disabled
    prometheus: disabled
    rbac: disabled
    registry: disabled

When I run `microk8s inspect` to [troubleshoot][3] the issue, it generates a logfile at `/var/snap/microk8s/1702/...` although I am on Windows!?

    C:\Users\biogeek>microk8s inspect
    Inspecting Certificates
    Inspecting services
      Service snap.microk8s.daemon-cluster-agent is running
      Service snap.microk8s.daemon-flanneld is running
      Service snap.microk8s.daemon-containerd is running
      Service snap.microk8s.daemon-apiserver is running
      Service snap.microk8s.daemon-apiserver-kicker is running
      Service snap.microk8s.daemon-proxy is running
      Service snap.microk8s.daemon-kubelet is running
      Service snap.microk8s.daemon-scheduler is running
      Service snap.microk8s.daemon-controller-manager is running
      Service snap.microk8s.daemon-etcd is running
      Copy service arguments to the final report tarball
    Inspecting AppArmor configuration
    Gathering system information
      Copy processes list to the final report tarball
      Copy snap list to the final report tarball
      Copy VM name (or none) to the final report tarball
      Copy disk usage information to the final report tarball
      Copy memory usage information to the final report tarball
      Copy server uptime to the final report tarball
      Copy current linux distribution to the final report tarball
      Copy openSSL information to the final report tarball
      Copy network configuration to the final report tarball
    Inspecting kubernetes cluster
      Inspect kubernetes cluster
    
    Building the report tarball
      Report tarball is at /var/snap/microk8s/1702/inspection-report-20201123_042132.tar.gz

How can I resolve this and successfully install Kubeflow on Windows using Microk8s?

  [1]: https://microk8s.io/
  [2]: https://github.com/ubuntu/microk8s/issues/1723
  [3]: https://microk8s.io/docs/troubleshooting

**Comment by kosehy** [comment]
@BioGeek I am not sure about the window's microk8s.
In ubuntu, however, I switched from 1.19/stable to 1.20/edge version of microk8s and it worked.

sudo snap install microk8s --classic --channel=1.20/edge

**Comment by tjanitsc** [comment]
I get the same issue. Tried out to reinstall Ubuntu 20, reinstall MicroK8s with a newer version 1.20 but nothing works.
