### ISSUE TITLE
HA and port 19001

### ISSUE THREAD

**Issue by just1victory** [ubuntu/microk8s#1768]
Does port 19001 need to be opened on all machines/VMs in a cluster running HA?   "microk8s status" states that 19001 is being used  (the port is not open on the machines) but nowhere in the documentation does it speak to port 19001 specifically.   Maybe I'm not looking the right place.  Thanks

**Comment by ktsakalozos** [comment]
Thank you for pointing this out @just1victory. The 19001 is used by dqlite, available on v1.19+ releases. Just updated the docs in https://discuss.kubernetes.io/t/services-and-ports/11263

Feel free to reopen the issue if you want to see this info in other places as well.
