### ISSUE TITLE
Microk8s HA setup - status shows not running, however inspect shows services being running.

### ISSUE THREAD

**Issue by PreethikaP** [ubuntu/microk8s#1771]
Have a microk8s HA setup with deployments in it, it was untouched for a week or so.
later when checked on the setups microk8s status shows not running but on inspect services shows as running.

The following is from one of the nodes in the HA setup,
```
core@core:~$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
core@core:~$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
```

But certainly apiserver logs shows the following errors,
```
Nov 20 11:25:40 core microk8s.daemon-apiserver[26939]: E1120 11:25:40.405822   26939 controller.go:223] unable to sync kubernetes service: rpc error: code = Unknown desc = query (try: 0): (
Nov 20 11:25:40 core microk8s.daemon-apiserver[26939]:                 SELECT rkv.id
Nov 20 11:25:40 core microk8s.daemon-apiserver[26939]:                 FROM kine rkv
Nov 20 11:25:40 core microk8s.daemon-apiserver[26939]:                 ORDER BY rkv.id
Nov 20 11:25:40 core microk8s.daemon-apiserver[26939]:                 DESC LIMIT 1)
Nov 20 11:25:41 core microk8s.daemon-apiserver[26939]: time="2020-11-20T11:25:41Z" level=error msg="error while range on /registry/clusterroles/ /registry/clusterroles/: count /registry/clusterroles/% (try: 0): (\n\t\tSELECT rkv.id\n\t\tFROM kine rkv\n\t\tORDER BY rkv.id\n\t\tDESC LIMIT 1)"
```

Need suggestion on this!!

**Comment by andreclaudino** [comment]
I am having exactly this same issue. The instalation was not changed for a long time, since yesterday, when I stoped, `microk8s.status` is aways saying it is not running, but `microk8s.start` says it succeeded

**Comment by ktsakalozos** [comment]
It could be the API server is not healthy but as a systemd service the API server is running. This may be the reason why the inspection scrip says the service is up but the kubernetes status says the cluster is not ready.

Could you attach the inspection tarball produced by `microk8s.inspect` so we can see the services logs?

**Comment by PreethikaP** [comment]
[inspection-report-20201130_053452.tar.gz](https://github.com/ubuntu/microk8s/files/5614038/inspection-report-20201130_053452.tar.gz)

Attaching the inspection tar.

**Comment by ECourant** [comment]
I'm also experiencing this issue. Alongside microk8s clearly running, I am unable to use microk8s.kubectl. Whenever I try I get the following message:

```
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

**Comment by balchua** [comment]
@ECourant will it be possible to upload the inspect tarball here?

**Comment by ECourant** [comment]
Unfortunately I cannot, I've since switched to a kubespray deployment instead. Sorry.

**Comment by herbsmithwv** [comment]
I have 4 raspberry pi 4s clustered.  I installed Ubuntu 20.04 servers and did the snap microk8s install.  Once I saw results from microk8s status.  All I see now on all four machines (one master, 3 nodes) is the behavior mentioned above:  microk8s status says it is stopped ; microk8s inspect says services are running; microk8s kubectl get all and similar commands refuse access to port 16443 which does not appear to be open.
I have not had this much trouble since I blew up my Vector Graphic S100 bus system trying to install a printer.

**Comment by arctiqaurora** [comment]
seeing the same issue with an HA cluster. 
[inspection-report-20210108_134230.tar.gz](https://github.com/ubuntu/microk8s/files/5787484/inspection-report-20210108_134230.tar.gz)

**Comment by balchua** [comment]
@arctiqaurora your issue is similar to this.  Unfortunately there is no resolution yet.
https://github.com/ubuntu/microk8s/issues/1864

**Comment by skytodmoon** [comment]
I met the same problem, any suggestions?
`6月 02 13:01:35 qianyan002 microk8s.daemon-apiserver[3456]:                 SELECT rkv.id
6月 02 13:01:35 qianyan002 microk8s.daemon-apiserver[3456]:                 FROM kine rkv
6月 02 13:01:35 qianyan002 microk8s.daemon-apiserver[3456]:                 ORDER BY rkv.id
6月 02 13:01:35 qianyan002 microk8s.daemon-apiserver[3456]:                 DESC LIMIT 1); reinitializing...
6月 02 13:01:35 qianyan002 microk8s.daemon-apiserver[3456]: E0602 13:01:35.152358    3456 cacher.go:419] cacher (*apps.ReplicaSet): unexpected ListAndWatch error: failed to list *apps.ReplicaSet: unexpected EOF; reinitializing...`
