### ISSUE TITLE
Pods stuck in "Terminating" state

### ISSUE THREAD

**Issue by LarsKumbier** [ubuntu/microk8s#1773]
`kubectl delete <pod>` will result in the pods to be stuck in the "Terminating" state. Same happens when I e.g. try to delete whole namespaces.

**Setup**
* Fresh, bare-metal Ubuntu 20.04.1 LTS with all updates installed
* microk8s installed via snap in 1.17/stable channel
* microk8s in v1.17.12
* kube-apiserver allowing privileged containers (/var/snap/microk8s/current/args/kube-apiserver contains `--allow-privileged=true`)

**Symptoms**
* pods (and namespaces) stay in "Terminating" state forever
* Running `ps -Af | grep <CMD>` and searching for the running command reveals, that the container command still runs in it's namespace
* Checking the `journalctl -x | grep apparmor` shows several "denied" entries for runc: 
```
Nov 25 08:23:45 k8s1 kernel: audit: type=1400 audit(1606289025.169:54559): apparmor="DENIED" operation="signal" profile="cri-containerd.apparmor.d" pid=2184447 comm="runc" requested_mask="receive" denied_mask="receive" signal=term peer="snap.microk8s.daemon-containerd"
Nov 25 08:23:45 k8s1 audit[2184457]: AVC apparmor="DENIED" operation="signal" profile="cri-containerd.apparmor.d" pid=2184457 comm="runc" requested_mask="receive" denied_mask="receive" signal=kill peer="snap.microk8s.daemon-containerd"
```
* A `kubectl describe <pod>` shows the denied message as well in the pods' events:
```
Warning  FailedKillPod  8s (x4 over 47s)  kubelet, k8s1      error killing pod: [failed to "KillContainer" for "acmesolver" with KillContainerError: "rpc error: code = Unknown desc = failed to stop container \"117c0054ed29bd806c936728785afb4f8d4556354556ccdfc2839324eae30e0f\": unknown error after kill: runc did not terminate sucessfully: container_linux.go:388: signaling init process caused \"permission denied\"\n: unknown", failed to "KillPodSandbox" for "33ab7dd7-0a07-4df4-bd8c-990b4b2c1154" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to stop container \"117c0054ed29bd806c936728785afb4f8d4556354556ccdfc2839324eae30e0f\": failed to kill container \"117c0054ed29bd806c936728785afb4f8d4556354556ccdfc2839324eae30e0f\": unknown error after kill: runc did not terminate sucessfully: container_linux.go:388: signaling init process caused \"permission denied\"\n: unknown"]
```

During analysis with @ktsakalozos, we found the problem to be the hosts' AppArmor service not running (via [this comment](https://github.com/ubuntu/microk8s/issues/249#issuecomment-525372725)). Starting the apparmor service and reloading the profile cache solved the problem.

For whatever reason, running `aa-status` did correctly show me several confinement-policies for processes, which led me to believe, that everything was working fine.

**Hypothesis**
Here's what I think happened. During installation, if apparmor is installed in the default directory, the necessary profiles are copied over and the script tries to reload apparmor ([src](https://github.com/ubuntu/microk8s/blob/74c3f47b4b67371871e83c6d68b053430fab99ea/microk8s-resources/wrappers/run-containerd-with-args#L14-L22)). But if apparmor is inactive, reloading will fail. This will leave the old AppArmor profiles stale, which can be shown via `aa-status` - but the new required ones are never loaded, even after a reboot (if AppArmor is disabled).

You can follow the timeline in the [slack microk8s channel](https://kubernetes.slack.com/archives/CAUNWQ85V/p1606232875289300)

**Reproduction**
Unfortunately, after I enabled the AppArmor service I was unable to reproduce the behavior - so this is a hypothetical reproduction for now.
(1) Install a fresh ubuntu server 20.04.1
(2) Install snapd
(3) run `snap install --classic microk8s --channel 1.17/stable`
(4) Add the line `--allow-privileged=true` to /var/snap/microk8s/current/args/kube-apiserver
(5) Start a container via `microk8s kubectl create pod test-pod --image=nginx/alpine`
(6) Ensure that the container has started via `microk8s kubectl get pod test-pod`
(7) Delete the pod via `microk8s kubectl delete pod test-pod`

If everything runs well (in terms of buggy), you will be able to see the behavior as described above in "Symptoms"

**Solution**
The installation process should not only reload the profiles, but also check, if the new profiles are *actually* present via `aa-status`. If they are not, the installation should either fail or the user should be informed at the end of the installation.

[inspection-report-20201125_080003.tar.gz](https://github.com/ubuntu/microk8s/files/5596477/inspection-report-20201125_080003.tar.gz)

**Comment by mattmeye** [comment]
+1
