### ISSUE TITLE
Scripting use of kube-apiserver doesn't work

### ISSUE THREAD

**Issue by didier-durand** [ubuntu/microk8s#1786]
Hi there,

I need to include the use of `kube-apiserver -h` in a bash script. 

I found the binary but  `/snap/microk8s/current/kube-apiserver -h` fails with 

`/snap/microk8s/current/kube-apiserver: error while loading shared libraries: libdqlite.so.0: cannot open shared object file: No such file or directory`

So, in Slack, @ktsakalozos  (thanks again!)  suggested me to use: 

```
snap run --shell microk8s
export PATH="$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH"
export ARCH="$($SNAP/bin/uname -m)"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/$ARCH-linux-gnu:$SNAP/usr/lib/$ARCH-linux-gnu"
export LD_LIBRARY_PATH=$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH
/snap/microk8s/current/kube-apiserver -h
```
This works fine interactively but it hangs on first `snap run --shell microk8s` when run in a script triggered over ssh from my laptop (script running on GCE)

What do I do wrong ?  Should I add some more options or commands to get it to work in my script?

Thanks!

Didier

**Comment by joedborg** [comment]
hey @didier-durand, I've just played with this locally to see if I could reproduce.  I think you may have to run `sudo snap run --shell microk8s` as it silently fails for me if not.

**Comment by didier-durand** [comment]
@joedborg : thanks for this info. I'll try your way then!
