### ISSUE TITLE
What is the tasteful way to edit client.config

### ISSUE THREAD

**Issue by carmine** [ubuntu/microk8s#180]
I'm running jx (jenkins-x) and it'd like to edit the $KUBECONFIG file, which is normally /snap/microk8s/current/client.config.

The error is:
error: open /snap/microk8s/current/client.config.lock: read-only file system

The command that causes that is:
kubectl config set-context microk8s --namespace jx

Which is embedded inside this command:
jx install --provider=kubernetes --on-premise

--

What is the best way get this working?  Make a copy of this file (can't be straight copy, more like cat into a new file, otherwise the same message occurs I believe).

**Comment by ktsakalozos** [comment]
`client.config` in under ${SNAP} and is on a read only filesystem. Here is what you can do:

```
microk8s.config > $HOME/.kube/config
microk8s.kubectl --kubeconfig=$HOME/.kube/config get no
```

Will this work for you? It is in our intentions to place the kubeconfig file in an editable place.

**Comment by geogeorgiev** [comment]
> `client.config` in under ${SNAP} and is on a read only filesystem. Here is what you can do:
> 
> ```
> microk8s.config > $HOME/.kube/config
> microk8s.kubectl --kubeconfig=$HOME/.kube/config get no
> ```
> 
> Will this work for you? It is in our intentions to place the kubeconfig file in an editable place.
In addition you can put `alias kubectl="microk8s.kubectl --kubeconfig=$HOME/.kube/config` in your shell profile.

**Comment by codycraven** [comment]
> It is in our intentions to place the kubeconfig file in an editable place.

That would be fantastic. It took some Googling to find this work around and complicates writing setup scripts for my team (to keep everyone's tool stack in sync) a fair amount.

**Comment by codycraven** [comment]
If anyone is running into this and isn't able to alias due to tooling, this is my workaround for now:

Install Kubectl

```bash
sudo snap install kubectl --classic
```

Run the following to configure Kubectl with MicroK8s's connection information

```bash
CLUSTER_SERVER="$(microk8s.kubectl config view -o jsonpath='{.clusters[?(@.name == "microk8s-cluster")].cluster.server}')"
CONTEXT_USER="$(microk8s.kubectl config view -o jsonpath='{.contexts[?(@.context.cluster == "microk8s-cluster")].context.user}')"
USERNAME="$(microk8s.kubectl config view -o jsonpath="{.users[?(@.name == '$CONTEXT_USER')].user.username}")"
kubectl config set-cluster microk8s-cluster --insecure-skip-tls-verify=true --server="$CLUSTER_SERVER"
kubectl config set-credentials microk8s-user --username="$USERNAME"
kubectl config set-context microk8s-context --cluster=microk8s-cluster --namespace=mwg --user=microk8s-user
kubectl config use-context microk8s-context
```

You will likely need to re-run if your IP changes. This isn't any issue for me since I have a start-up script for my team.

**Comment by sandroden** [comment]
I understand this issue is closed but the problem is still there. [Docs](https://microk8s.io/docs/working-with-kubectl) say it should work with `~/.kube/config` but it's not. I confirm `kubectl` from `snap install kubectl` works just fine (it honors the config file even w/o using the option on the command line) and using the options works with microk8s.kubectl as well. What is not working is the default w/o options and the env variable:

If you use kubectl:
```sh
$ kubectl config --kubeconfig ~/.kube/config get-contexts
CURRENT   NAME               CLUSTER            AUTHINFO                                      NAMESPACE
*         microk8s           microk8s-cluster   admin                                         
          exqlprodk8s   exqlprodk8s   clusterUser_exql_prod_exqlprodk8s   
          exqluatk8s    exqluatk8s    clusterUser_exql_uat_exqluatk8s     

$ kubectl config get-contexts
CURRENT   NAME               CLUSTER            AUTHINFO                                      NAMESPACE
*         microk8s           microk8s-cluster   admin                                         
          exqlprodk8s   exqlprodk8s   clusterUser_exql_prod_exqlprodk8s   
          exqluatk8s    exqluatk8s    clusterUser_exql_uat_exqluatk8s     
```
When using `microk8s` you get the error
```
$ microk8s.kubectl config get-contexts 
CURRENT   NAME       CLUSTER            AUTHINFO   NAMESPACE
*         microk8s   microk8s-cluster   admin   

$ microk8s.kubectl config --kubeconfig ~/.kube/config  get-contexts
CURRENT   NAME               CLUSTER            AUTHINFO                                      NAMESPACE
*         microk8s           microk8s-cluster   admin                                         
          exqlprodk8s   exqlprodk8s   clusterUser_exql_prod_exqlprodk8s   
          exqluatk8s    exqluatk8s    clusterUser_exql_uat_exqluatk8s    
```
