### ISSUE TITLE
microk8s ctr image import doesn’t work

### ISSUE THREAD

**Issue by rahamohebbi** [ubuntu/microk8s#1804]
When I run this command to import an exported image, I get the following error message:
microk8s ctr image import myimage.tar

error message:
ctr: open myimage.tar: no such file or directory
An error occurred when trying to execute 'sudo microk8s.ctr image import myimage.tar' with 'multipass': returned exit code 1.

I am using Windows Pro 10

**Comment by balchua** [comment]
@rahamohebbi you are running the `microk8s` command from windows?

If thats the case, yes that will fail because the tar file is not inside the VM for `ctr` to pickup.

You can transfer the tar image to the VM using `multipass transfer... ` then run the `microk8s.ctr` command again.
