### ISSUE TITLE
after reboot we get  Unable to authenticate the request due to an error: invalid bearer token

### ISSUE THREAD

**Issue by dougbertwashere** [ubuntu/microk8s#1805]
[inspection-report-20201211_042401.tar.gz](https://github.com/ubuntu/microk8s/files/5677062/inspection-report-20201211_042401.tar.gz)
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

We have a single node (HPGen10) system running our OnPrem application (media training).  After we shutdown/reboot we started getting this error.  This has occurred on 2 machines,  another 2 machines which have not been shutdown/rebooted, things are fine.

We are utilizing Longhorn for storage.

These single node systems deployment are a subset of 3 node deployments of the same application.

The node is NotReady and is tainted.

This is our first deployment of microk8s/kerbernetes and are learning fast on how to setup/use/debug

appreciate any hints on this cause

**Comment by ktsakalozos** [comment]
Hi @dougbertwashere 

Is it possible the hostname changed from `mssnode` to `mssnode1`? 

I see kubelet reporting `Dec 11 01:48:26 mssnode1 microk8s.daemon-kubelet[61773]: E1211 01:48:26.358792   61773 kubelet.go:2183] node "mssnode1" not found`, and the logs on the apiserver they say:
```
Dec 10 21:12:03 mssnode systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver.
-- Reboot --
Dec 10 21:14:41 mssnode1 systemd[1]: Started Service for snap application microk8s.daemon-apiserver.
```

One thing you could try, although I am not sure if it will work, is to go to  `/var/snap/microk8s/current/credentials/known_tokens.csv` and update your node's token.

Something else that is interesting is that you are not following any track so you do not get updates. How did you deploy MicroK8s?

**Comment by dougbertwashere** [comment]
thank you ktsakalozos

yes, the nodename was changed as part of our installation process - we are experimenting on how to install with our restraints.

BACKGROUND:   

we have had our application for sometime running just in docker on OnPrem hardware.  One of our customers wanted HA, and we researched kubernetes and then onto microk8s.  We are installing a 3 node cluster at that site.

We install the system/app via a system image restore, onto the hardware, setup IP Addrs, run tests on it, and etc.  We shut things down, transport whole HW/SW to the customer and then bring things back up, including setting target environment IP Addrs

Another similar customer is getting the same system but only on a single node w/o HA - which caused this issue I filed.  As mentioned in original we are using Longhorn for storage and found that we were not properly shutting down  the system which caused issues with Longhorn replicas being damaged.  We did a lot of research on how to properly shutdown the system and came up with a protocol that seems to work.  We didn't find much documention on proper OnPrem shutdown operations with both Microk8s and Longhorn (we assume since most deployments are in a cloud model that this is not so common).  So we jumped all over it and iterated over possible solutions.

We noticed the node naming issue on the single node deployment and wanted to allow for upgrading the single node customer to future HA upgrading so we changed from mssnode to mssnode1, and we see that again we failed to recognize the impact that would have.

For the question on  how we deploy, we generate a complete image of OS and perform a restore of that image onto target hardware - a manufacturing process.  In that image are snap images, application tarballs, etc and do final installations upon boot up. We have been searched for best solutions to this type of development

As for upgrades, these machines are installed in a customer data center where they CANNOT be connected to the internet. There is an air-gap network there and updates are a manual process.  Even unattended-updater package is removed from unbuntu

We appreciate your information and are re-imaging the single node system and restarting the process on these.

What is the best way to help solve our issues as we encounter them? File individual issues like this? Or something else?

thanks again

**Comment by dougbertwashere** [comment]
status update

your message on the hostname prompted our examination of our installation process in the area of hostname creation.
the bad sequence was:  1) change /etc/hostname,  2) microk8s start,  3) reboot

new process is:   1) hostnamectl set-hostname <new  name>  and 2) microk8s start.  No reboot

we have provisioned several single node systems now and no problems.

thanks again
