### ISSUE TITLE
Upgrading Cluster

### ISSUE THREAD

**Issue by sstubbs** [ubuntu/microk8s#1817]
Hi,

I've been running channel 1.19/stable for a while now and it seems to be stable. Just curious now that there is high availability which leads me to believe this can be used in production are there any plans to allow upgrading between major releases without needing a reinstall in the future.

I will skip 1.20 for the time being but it would be nice if this is something that could be easier in the future.

**Comment by arctiqaurora** [comment]
Same here. What is the best way to upgrade a major releases? Microk8s is supposed to be a lightweight k8s distribution thus there's no enough resources for a complete rebuild or green blue deployment.

**Comment by ktsakalozos** [comment]
The docs page [1] describe the process you need to follow for an upgrade.

[1] https://microk8s.io/docs/upgrade-cluster
