### ISSUE TITLE
istio/crd*yaml" does not exist when enable istio

### ISSUE THREAD

**Issue by hick** [ubuntu/microk8s#1818]
installing microk8s was done, but when istio:

![image](https://user-images.githubusercontent.com/38886/102104556-48467f80-3e69-11eb-9c3c-c65083f4d0e4.png)
[inspection-report-20201215_000524.tar.gz](https://github.com/ubuntu/microk8s/files/5690057/inspection-report-20201215_000524.tar.gz)

**Comment by balchua** [comment]
@hick can you go to this directory `/var/snap/microk8s/current/bin` and check if `istioctl` is there?
If yes can you delete that and try enabling istio again?

Thanks

**Comment by hick** [comment]
thx a lot,   it's ok now, as the following picture.

and I guess it maybe caused by the first opertion to start Istio without "sudo" by using no-root user.  and it could be done after deleting /var/snap/microk8s/current/bin/istioctl and using "sudo"

![image](https://user-images.githubusercontent.com/38886/103135395-07fdc180-46f3-11eb-8035-1d70805843e3.png)
