### ISSUE TITLE
microk8s add-node doesn't work

### ISSUE THREAD

**Issue by remeq** [ubuntu/microk8s#1819]
Hi,

adding new node to a cluster doesn't work properly. The joining command on the newly added node finishes successfully:

```
root@ip-172-31-26-187:~# microk8s join 172.31.27.5:25000/93851439e6d378146b7c765cd195ad8f
Contacting cluster at 172.31.27.5
Waiting for this node to finish joining the cluster. ..  
root@ip-172-31-26-187:~# echo $?
0
root@ip-172-31-26-187:~# 

```

But the node is not visible in the node listing: 

```
root@ip-172-31-27-5:~# microk8s kubectl get nodes
NAME               STATUS   ROLES    AGE   VERSION
ip-172-31-27-5     Ready    <none>   59m   v1.19.3-34+a56971609ff35a
ip-172-31-22-234   Ready    <none>   51m   v1.19.3-34+a56971609ff35a
root@ip-172-31-27-5:~# 
```

Notice there is no "ip-172-31-26-187" node in the listing. In the inspect log (snap.microk8s.daemon-controller-manager) there is some calico error visible: 

`Dec 14 19:06:08 ip-172-31-27-5 microk8s.daemon-controller-manager[39673]: E1214 19:06:08.860161   39673 daemon_controller.go:320] kube-system/calico-node failed with : error storing status for daemon set &v1.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"calico-node", GenerateName:"", Namespace:"kube-system",.............. Operation cannot be fulfilled on daemonsets.apps "calico-node": the object has been modified; please apply your changes to the latest version and try again`

[inspection-report-20201214_192240.tar.gz](https://github.com/ubuntu/microk8s/files/5691304/inspection-report-20201214_192240.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @remeq,

Thank you for reporting this.

In the logs you attached I see the following error:
```
Dec 14 19:12:34 ip-172-31-27-5 microk8s.daemon-apiserver[39585]: I1214 19:12:34.592311   39585 log.go:181] [ERROR] dqlite: proxy: first: remote -> local: read tcp 172.31.27.5:19001->172.31.26.187:37570: read: connection reset by peer
```

Dqlite, the datastore used, was not able to talk to the new node. Could you attach the inspection tarball of the joining node too? I would like to see the status of the joining apiserver. Is it possible that a firewall is blocking connections?

**Comment by remeq** [comment]
Hi @ktsakalozos ,

The worker nodes are fresh, plain EC2 instances on a same network. There is no security that would be filtering stuff. Also note that sometimes the join command works and sometimes it ends up with the reported problem. It doesn't seem to be a network problem. 

I've did another round of testing and generated new inspect bundles for both the node where I execute "microk8s add-node" and the node where I execute "microk8s join". 
[kubectl-add-node-inspect.tar.gz](https://github.com/ubuntu/microk8s/files/5716453/kubectl-add-node-inspect.tar.gz)
[kubectl-join-inspect.tar.gz](https://github.com/ubuntu/microk8s/files/5716454/kubectl-join-inspect.tar.gz)

**Comment by timwebster9** [comment]
I'm getting similar. Not sure if it helps but the first time I ran it I got this (on the joining node):
```
timw@io:~$ microk8s join 192.168.1.132:25000/a784cebc855be8c8e99170f93edb53df
Contacting cluster at 192.168.1.132
Waiting for this node to finish joining the cluster. ..  
Traceback (most recent call last):
  File "/snap/microk8s/1866/scripts/cluster/join.py", line 967, in <module>
    join_dqlite(connection_parts)
  File "/snap/microk8s/1866/scripts/cluster/join.py", line 900, in join_dqlite
    update_dqlite(info["cluster_cert"], info["cluster_key"], info["voters"], hostname_override)
  File "/snap/microk8s/1866/scripts/cluster/join.py", line 856, in update_dqlite
    restart_all_services()
  File "/snap/microk8s/1866/scripts/cluster/join.py", line 784, in restart_all_services
    stderr=subprocess.DEVNULL,
  File "/snap/microk8s/1866/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/1866/microk8s-stop.wrapper']' returned non-zero exit status 1

```
