### ISSUE TITLE
"Proxying" required image registries with corporate private image registry

### ISSUE THREAD

**Issue by HarveyEllis** [ubuntu/microk8s#1827]
Hi, 

I work behind a corporate proxy/firewall that limits access to certain container registries - we have our own internal mirrors. 
I've managed to get `microk8s` up and running using quite a lot of manual pulling of images from our internal docker registries (we have them for `docker.io`, `gcr.io`,`k8sgcr.io`, `quay.io` etc etc.)

However, this process of pulling images manually, tagging them with the correct namespace (for example, `k8sgcr.io` for the pause image) is very tiresome and I was wondering whether there is a way to configure this process automatically. 

I've looked at [the docs](https://microk8s.io/docs/registry-private) and followed their instruction, and come up with something like the following: 
```toml
  # 'plugins."io.containerd.grpc.v1.cri".registry' contains config related to the registry
  [plugins."io.containerd.grpc.v1.cri".registry]

    # 'plugins."io.containerd.grpc.v1.cri".registry.mirrors' are namespace to mirror mapping for all namespaces.
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      # "plugins.cri.registry" contains config related to the registry
      [plugins."io.containerd.grpc.v1".cri.registry.mirrors."docker.io"]
        endpoint = ["https://my-registry.my-company.com"]
```
(I've then done `microk8s stop && microk8s start`, as well as just restarting the `snap` containerd service too.)

I then try and pull images:
```shell
ctr images pull docker.io/calico/kube-controllers:v3.13.2
```
But still get the following error message: 
```shell
ctr: failed to resolve reference "docker.io/calico/kube-controllers:v3.13.2": unexpected status code [manifests v3.13.2]: 403 Forbidden
```
This is not a problem here because I can just pull the image I want manually from our company's internal registry, but when microk8s is starting up it needs containers like `kube-controllers` or `pause` and I can't seem to figure out how to set up this up. 

On initial startup microk8s cannot reach the required image registry, and so when I run `describe` on a pod there are just loads of io errors about pulling from `docker.io`. These are the kinds of errors I get: 

```
 Warning  Failed             56m (x3 over 59m)      kubelet            Failed to pull image "kubernetesui/dashboard:v2.0.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubernetesui/dashboard:v2.0.0": failed to resolve reference "docker.io/kubernetesui/dashboard:v2.0.0": failed to do request: Head "http://proxy:5000/v2/kubernetesui/dashboard/manifests/v2.0.0": dial tcp: lookup proxy on 10.31.66.101:53: no such host
  Warning  Failed             49m (x6 over 59m)      kubelet            Error: ErrImagePull
  Warning  Failed             42m                    kubelet            Failed to pull image "kubernetesui/dashboard:v2.0.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubernetesui/dashboard:v2.0.0": failed to resolve reference "docker.io/kubernetesui/dashboard:v2.0.0": failed to do request: Head "https://registry-1.docker.io/v2/kubernetesui/dashboard/manifests/v2.0.0": dial tcp 52.1.121.53:443: i/o timeout
  Warning  Failed             39m                    kubelet            Failed to pull image "kubernetesui/dashboard:v2.0.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubernetesui/dashboard:v2.0.0": failed to resolve reference "docker.io/kubernetesui/dashboard:v2.0.0": failed to do request: Head "https://registry-1.docker.io/v2/kubernetesui/dashboard/manifests/v2.0.0": dial tcp 52.54.232.21:443: i/o timeout
  Warning  Failed             39m (x2 over 42m)      kubelet            Error: ImagePullBackOff
  Normal   BackOff            39m (x2 over 42m)      kubelet            Back-off pulling image "kubernetesui/dashboard:v2.0.0"
  Warning  DNSConfigForming   39m (x6 over 44m)      kubelet            Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.31.66.101 10.31.68.101 10.125.66.101
  Normal   Pulling            39m (x3 over 44m)      kubelet            Pulling image "kubernetesui/dashboard:v2.0.0"
  Warning  Failed             37m                    kubelet            Failed to pull image "kubernetesui/dashboard:v2.0.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubernetesui/dashboard:v2.0.0": failed to resolve reference "docker.io/kubernetesui/dashboard:v2.0.0": failed to do request: Head "https://registry-1.docker.io/v2/kubernetesui/dashboard/manifests/v2.0.0": dial tcp 34.195.246.183:443: i/o timeout
  Warning  Failed             28m (x6 over 42m)      kubelet            Error: ErrImagePull
  Warning  MissingClusterDNS  9m18s (x104 over 44m)  kubelet            pod: "kubernetes-dashboard-7ffd448895-r5q25_kube-system(3eaa1a4e-e507-4c26-90ce-75a2ef3394aa)". kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.
  Warning  Failed             3m56s                  kubelet            (combined from similar events): Failed to pull image "kubernetesui/dashboard:v2.0.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubernetesui/dashboard:v2.0.0": failed to resolve reference "docker.io/kubernetesui/dashboard:v2.0.0": failed to do request: Head "https://registry-1.docker.io/v2/kubernetesui/dashboard/manifests/v2.0.0": dial tcp 18.232.227.119:443: i/o timeout
```
        
Is there something else that I need to set somewhere so that the registry will be proxied properly? 

I should mention that I have also looked at https://github.com/ubuntu/microk8s/issues/1035#issue-582526534 which says something to do with `microk8s.enable` manifests?

I should also say I'm very new to kubernetes so I may have got the wrong idea about what the `containerd` config does too. 

I'm using: 
- RHEL7
- microk8s 1856. 

I'm not able to put the inspection report here unfortunately (company policy), but hopefully its just something silly I'm doing in this case and someone can just correct me?

**Comment by balchua** [comment]
The `ctr` command as far as i know is not using the `containerd` configuration.  You need to have the `crictl` to test the configuration.  You need to point that to the `containerd.sock` , which is located in `/var/snap/microk8s/common/run/containerd.sock`.

The `pause` container location can be modified in the `containerd-template.conf` not the `containerd.conf`.  i have to admit that i've not tried this.

Another option i can think of, just some random thoughts, is to add in '/etc/host` `docker.io` to point to your registry's IP.  May or may not work.

Wdyt?

**Comment by HarveyEllis** [comment]
hey @balchua, 

Thanks for your suggestion. In the end I downloaded the containers locally, tagged them and used ansible to SCP them across. It seemed like the simple way to do things at the time.
