### ISSUE TITLE
Pods are restarted after notebook suspend

### ISSUE THREAD

**Issue by maxweber** [ubuntu/microk8s#1837]
Hi, first of all thanks a lot for creating this wonderful project.

We are using microk8s since a couple of months on our notebooks. We noticed that our application server always stops, whenever our notebook wakes up after it has been suspended. Same thing happens if we turn off the wifi, wait a few seconds and turn it back on.

Today I luckily found this entry: https://github.com/ubuntu/microk8s/issues/492#issuecomment-498129073 and learned about the `snap.microk8s.daemon-apiserver-kicker.service`, which seems to be responsible for the behavior described above. When I stop this service the issue is gone.

It would be great to have a better default behavior for this case. I guess many people will run into the same issue and have a hard time to figure this out.

Best regards,

Max

**Comment by ktsakalozos** [comment]
Hi @maxweber 

This behavior [1] is here to get MicroK8s adjust to IP changes of the host. Think for example the case where you are on a laptop and you connect to a different wifi that gives you a different IP.

If this is annoying you can bind the apiserver to a specific IP by adding the `--advertise-address` or `--bind-address` arguments in `/var/snap/microk8s/current/args/kube-apiserver` according to [2] and restart MicroK8s.

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/apiservice-kicker
[2] https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

**Comment by ngbrown** [comment]
I would like to say, that in my experience, adding `--advertise-address` or `--bind-address`, even with `0.0.0.0`, prevents `microk8s join` from working and the node ends up corrupted... I have to `snap remove microk8s` and re-install.
