### ISSUE TITLE
Question - RPi 4 HA tuning

### ISSUE THREAD

**Issue by rockaut** [ubuntu/microk8s#1838]
Heja, I yesterday tried to get an fresh install with 1.19 and 1.20 stable running on 4x RPi 4GB running and succeeded nicely. Great. But I also had some hangs and dug into. I saw that the cpu and io is around 30% on the master nodes. I realise why and also that RPi even with usb3 ssd are very limited.

I just wanted to see if someone maybe found a way to tune the dblite/apiserver/ha processes to don’t take so much performance. Maybe some slower votings, less monitoring of Internals or whatever.

I for now disabled ha and kept 1.19 single master running great around 17 and just 4 on workers without much io at all - without workload off course.

**Comment by tbrandstetter** [comment]
Same problem here with my 5 node cluster (3 x RPi 8GB and 2 x RPi 4GB) - I have to say that I run rook-ceps on 3 nodes exclusively with SSD only (one as boot disk and one as OSD disk). I separated the Ceph storage nodes from the worker nodes using pod affinity and node selector. Every day one node stops working with timeouts in the log:

``timeout 1s exceeded: context deadline exceeded``

There is already an issue open about the apiserver #1598 So, maybe it is a duplicate.
