### ISSUE TITLE
failed to setup network for sandbox 

### ISSUE THREAD

**Issue by he19920226he** [ubuntu/microk8s#1840]
microk8s.kubectl describe pod coredns-86f78bb79c-7s7ds -n kube-system

(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c1acf381f924a073b525f2382b6c4e5416b0abf3a84e4835086ac56e24f5e22e": error getting ClusterInformation: Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: proxyconnect tcp: dial tcp: lookup http on 100.100.2.136:53: no such host

help

**Comment by quasarchimaere** [comment]
i am experiencing a similar issue, our cluster (3 nodes, on ubuntue 18.04 lts) went completely unresponsive a week ago, microk8s wouldnt start anymore so we had to move the containerd directory and this made the cluster start again, however after another 12hours the cluster went down again, status and inspect show no signs of problems at all, what seems out of the ordinary is this:
- pod re-creation is invoked quite often, without any sign of pods being created
- api calls to 127.0.0.1:16443 either dont work or run in a timeout (timeout is set to 2s, but i think thats a default value)
- leader election happens fairly often (every 15-20seconds)
- the above mentioned issue is also happening although the rpc error is sometimes different

**Comment by ukd1** [comment]
@quasarchimaere also getting similar issues

**Comment by ktsakalozos** [comment]
Thank you for reporting this. Please attach a `microk8s inspect` tarball so we can look into what is happening in the server.

**Comment by slyons** [comment]
I just deployed a new cluster and I'm running into this problem with CoreDNS/Calico.
[inspection-report-20211104_190013.tar.gz](https://github.com/ubuntu/microk8s/files/7477543/inspection-report-20211104_190013.tar.gz)
