### ISSUE TITLE
Errors default microk8s after install

### ISSUE THREAD

**Issue by hitman249** [ubuntu/microk8s#1842]
Reinstall script 

```bash
sudo snap remove --purge microk8s
sudo snap install microk8s --classic
sudo microk8s.start
sudo microk8s.status --wait-ready
sudo microk8s.enable dns ingress
sudo microk8s.status --wait-ready
```

https://paste.laravel.io/3b340f86-7071-4be5-b679-053286b2981f#34,38,49-51,56

[inspection-report-20201222_093846.tar.gz](https://github.com/ubuntu/microk8s/files/5729039/inspection-report-20201222_093846.tar.gz)

Tested in 2 servers

**Comment by balchua** [comment]
@hitman249 thanks for using MicroK8s.
I don't see anything amiss in the inspect tarball.

Both the dns and ingress seems to be up.

Its not immediate, but after sometime it does get into stable state.

**Comment by hitman249** [comment]
I meet the same error in my containers
after which they do not work correctly
For this reason, ingress does not see my container.

**Comment by balchua** [comment]
I checked the tarball and i see this log

```
==== START logs for container mw of pod default/mw-7b5d6bf5d-qn87q ====
The [public/storage] directory has been linked.
chown: changing ownership of '/var/www/license.php': Read-only file system
==== END logs for container mw of pod default/mw-7b5d6bf5d-qn87q ====
```

There maybe something wrong with the image.

**Comment by hitman249** [comment]
```
volumeMounts:
   - name: secret
     mountPath: "/var/www/license.php"
     subPath: license.php
```

entrypoint.sh in container

```bash
... initialization logic ...

chown -R www-data:www-data /var/www/
```
the container is ok

**Comment by balchua** [comment]
I don't think the container actually started.

The startupProbe is failing.  `    "message": "Startup probe failed: HTTP probe failed with statuscode: 503",`

Does your application prints out logs after doing the `chown` statement, because i don't see anything after that.

**Comment by hitman249** [comment]
probably the wrong problem
container start successfully, error in manifest files
