### ISSUE TITLE
Helm3 upgrade command error

### ISSUE THREAD

**Issue by virtyos** [ubuntu/microk8s#1846]
I've intalled  yugabyte db (https://docs.yugabyte.com/latest/deploy/kubernetes/single-zone/oss/helm-chart/) and  now I'm trying to execute next command

`microk8s helm upgrade --set replicas.tserver=5 yb-demo ./yugabyte`

but I got an error Error: path "./yugabyte" not found

**Comment by Bessonov** [comment]
I think it's not related to microk8s and it makes more sense to open an issue @ yugabyte: https://github.com/yugabyte/yugabyte-db/issues

**Comment by balchua** [comment]
Another thing to note, there are 2 helms in microk8s addons.

* Helm 2:

`microk8s enable helm`
To use helm2
`microk8s helm ....`


* Helm 3:

`microk8s enable helm3`
To use helm 3
`microk8s helm3 ....`

**Comment by virtyos** [comment]
> Another thing to note, there are 2 helms in microk8s addons.
> 
> * Helm 2:
> 
> `microk8s enable helm`
> To use helm2
> `microk8s helm ....`
> 
> * Helm 3:
> 
> `microk8s enable helm3`
> To use helm 3
> `microk8s helm3 ....`


helm 3 is enabled, helm 2 is disbaled
and microk8s helm uses helm 3 not 2

I'd not be able to intall yugabyte db with helm 2

**Comment by balchua** [comment]
Looking at the `snapcraft` there are 2 wrappers.

https://github.com/ubuntu/microk8s/blob/b8459008fa3f6d522bcaf9e7170a16c32e94061b/snap/snapcraft.yaml#L91-L95

So `microk8s helm3` and `microk8s helm` are 2 different clients.  I usually use `microk8s helm3`

**Comment by virtyos** [comment]
microk8s helm3 upgrade --set replicas.tserver=2 yb-demo ./yugabyte
Error: path "./yugabyte" not found

same result :(

**Comment by virtyos** [comment]
yugabyte docs say that 

The default values for the Helm chart are in the helm/yugabyte/values.yaml file.

but where microk8s version of helm stores that file?

**Comment by balchua** [comment]
Oh microk8s doesn't download the chart and keep it in its folders.  That's not how it works.  Helm as a client should refer to a location where the chart is.  It can be a local file system like you showed.  Or use http to point to where the charts are located.
