### ISSUE TITLE
brew install ubuntu/microk8s/microk8s error "macos"

### ISSUE THREAD

**Issue by valentinc94** [ubuntu/microk8s#1847]
Last 15 lines from /Users/administrador/Library/Logs/Homebrew/microk8s/05.python3:
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/microk8s--homebrew-virtualenv-20201224-7573-cos5fp/target
--install-scripts=/private/tmp/microk8s--homebrew-virtualenv-20201224-7573-cos5fp/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "setup.py", line 4, in <module>
    raise RuntimeError("setuptools >= 41 required to build")
RuntimeError: setuptools >= 41 required to build

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/ubuntu/homebrew-microk8s/issues

**Comment by joedborg** [comment]
please try 

`brew reinstall Python`

and then attempt to install microk8s again
