### ISSUE TITLE
Microk8s is not pulling images from private image repository 

### ISSUE THREAD

**Issue by ppratheesh** [ubuntu/microk8s#1849]
Hi , we are using nexus image registry for our project . We are pushing our images to the registry using the tag ec2-*-*-*.ap-south-*.compute.amazonaws.com:8082/fpl-backend .We have configured `/var/snap/microk8s/current/args/containerd-template.toml` like 
```

    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."ec2-*-0-*-*.ap-south-1.compute.amazonaws.com:8082"]
          endpoint = ["http://ec2-*-0-*-*.ap-south-1.compute.amazonaws.com:8082"]
      [plugins.cri.registry.auths]
        [plugins.cri.registry.auths."ec2-*-*-*-*.ap-south-1.compute.amazonaws.com:8082"]
          username = "*******"
          password = "*******"
```

when we are deploying we are getting this error 

               
```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  2m7s                default-scheduler  Successfully assigned default/test11221-85998d7f96-k27mr to host
  Normal   Pulling    31s (x4 over 2m6s)  kubelet            Pulling image "ec2-*-0-*-*.ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4"
  Warning  Failed     31s (x4 over 2m6s)  kubelet            Failed to pull image "ec2-*-0-*-*.ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4": rpc error: code = Unknown desc = failed to resolve image "ec2-*-0-*-*.ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4": no available registry endpoint: failed to do request: Head "https://ec2-*-0-*-*.ap-south-1.compute.amazonaws.com:8082/v2/fpl-backend/manifests/93211a4": dial tcp 172.31.22.22:8082: connect: connection refused
  Warning  Failed     31s (x4 over 2m6s)  kubelet            Error: ErrImagePull
  Warning  Failed     16s (x6 over 2m5s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    2s (x7 over 2m5s)   kubelet            Back-off pulling image "ec2-*-0-*-*.ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4"





```
` /etc/docker/daemon.json ` file looks like 

```
{
  "insecure-registries": [
    "ec2-*-*-*.ap-south-1.compute.amazonaws.com:8082",
    "ec2-*-*-*.ap-south-1.compute.amazonaws.com:8083"
  ]
}
```

[inspection-report-20201226_083326.tar.gz](https://github.com/ubuntu/microk8s/files/5742856/inspection-report-20201226_083326.tar.gz)

**Comment by balchua** [comment]
@ppratheesh stupid question i have, did you restart microk8s after changing the `containerd-template.toml`?
Btw, microk8s is using containerd, so `/etc/docker/daemon.json` isn't going to affect MicroK8s.

**Comment by ppratheesh** [comment]
@balchua yes i did restart microk8s after changing the config

**Comment by balchua** [comment]
@ppratheesh i think the better way of specifying the registry config is with the kubernetes secret dockerconfig option.

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by ppratheesh** [comment]
hi @balchua  i have tried Kubernetes to manage my private registry details.But things are not working as expected.I have configured my registry with http .seems like microk8s is not accepting insecure registry 
 ```
 ----     ------     ----              ----               -------
  Normal   Scheduled  19s               default-scheduler  Successfully assigned default/fpl-backend-5bc754ddf8-n7447 to myhost
  Normal   BackOff    19s               kubelet            Back-off pulling image "ec2-*-*-*..ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4"
  Warning  Failed     19s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    5s (x2 over 19s)  kubelet            Pulling image "ec2-*-*-*.ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4"
  Warning  Failed     5s (x2 over 19s)  kubelet            Failed to pull image "ec2-*-*-*..ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4": rpc error: code = Unknown desc = failed to resolve image "ec2-ec2-*-*-*..ap-south-1.compute.amazonaws.com:8082/fpl-backend:93211a4": no available registry endpoint: failed to do request: Head "https://ec2ec2-*-*-*..ap-south-1.compute.amazonaws.com:8082/v2/fpl-backend/manifests/93211a4": http: server gave HTTP response to HTTPS client
  Warning  Failed     5s (x2 over 19s)  kubelet            Error: ErrImagePull

```

But `docker pull <my registry> `is working fine since i have configured daemon.json to accept insecure registry

**Comment by balchua** [comment]
@ppratheesh you're right, it doesn't seem to support `http`. Probably have to do like what you did previously, which is through containerd configuration.  
Is there a possibility to remove the authentication to your registry, just yo test things out?
Need to restart containerd. Or a `microk8s stop` `microk8s start`

**Comment by balchua** [comment]
Sorry may i know which version of microk8s you are using?

**Comment by balchua** [comment]
Containerd 1.2.5 which is used in 1.18 MicroK8s seems to be buggy.  Can you try using 1.19 just to see if it can access your registry?  Also note that 1.19 uses 1.3.7 containerd which has better support for insecure registries.

**Comment by ppratheesh** [comment]
hi @balchua  we have upgraded microk8s to 1.19 and edited `/var/snap/microk8s/current/args/containerd-template.toml` like

```
    # 'plugins."io.containerd.grpc.v1.cri".registry.mirrors' are namespace to mirror mapping for all namespaces.
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
        endpoint = ["https://registry-1.docker.io" ]
      [plugins.cri.registry.mirrors."ec2-*-*-*-*.ap.ap-south-1.compute.amazonaws.com"]
        endpoint = ["http://ec2-*-*-*-*.ap-south-1.compute.amazonaws.com:8082"]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:32000"]
        endpoint = ["http://localhost:32000"]
```
But after microk8s stop and microk8s start ,microk8s inspect showing` Service snap.microk8s.daemon-containerd is not running` also my node is become NotReady after this
```
NAME     STATUS     ROLES    AGE   VERSION
myhost   NotReady   <none>   21m   v1.19.5-34+8af48932a5ef06
```
Attaching the Inspection-report 
[inspection-report-20210103_065849.tar.gz](https://github.com/ubuntu/microk8s/files/5761304/inspection-report-20210103_065849.tar.gz)

**Comment by balchua** [comment]
Hi 
The plugin definition should be like this.
 ```     [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ec2-*-*-*-*.ap.ap-south-1.compute.amazonaws.com"]
```
Instead of 

```
plugins.cri.registry.mirrors
```
