### ISSUE TITLE
error: deployment "calico-kube-controllers" exceeded its progress deadline

### ISSUE THREAD

**Issue by harshit-deepsource** [ubuntu/microk8s#1850]
[inspection-report-20201226_173421.tar.gz](https://github.com/ubuntu/microk8s/files/5743055/inspection-report-20201226_173421.tar.gz)

When using 

`$  microk8s enable kubeflow --ignore-min-mem`

I'm getting this error:

```Kubeflow could not be enabled:
error: deployment "calico-kube-controllers" exceeded its progress deadline

Command '('microk8s-kubectl.wrapper', '-nkube-system', 'rollout', 'status', 'deployment.apps/calico-kube-controllers')' returned non-zero exit status 1```

I've also attached the generated tarball file for your reference.

**Comment by balchua** [comment]
Hi,

Calico couldn't find an IPv4 interface.  As shown in the logs.

```
2020-12-26 12:00:13.293 [WARNING][8] startup.go 648: Unable to auto-detect an IPv4 address: no valid IPv4 addresses found on the host interfaces
2020-12-26 12:00:13.293 [WARNING][8] startup.go 438: Couldn't autodetect an IPv4 address. If auto-detecting, choose a different autodetection method. Otherwise provide an explicit address.
```
The error you are experiencing is similar to this.
https://github.com/ubuntu/microk8s/issues/1554#issuecomment-691426908. Can you try the solution provided?
Thanks!

**Comment by harshit-deepsource** [comment]
Hey, I'm using a different approach to install kubeflow. This issue can be closed.

**Comment by Bessonov** [comment]
@harshit-deepsource can you tell a litte bit more about your approach? May be it can help others.
