### ISSUE TITLE
MicroK8s in LXD: slapadd on container startup fails with: cannot create file for "cn=config": Permission denied

### ISSUE THREAD

**Issue by gunterze** [ubuntu/microk8s#1853]
1. Installed LXD and initialized container running MicroK8s according https://microk8s.io/docs/lxd
2. `$ sudo lxc exec microk8s -- microk8s kubectl create deployment ldap --image=dcm4che/slapd-dcm4chee:2.4.50-23.0`
   ```
   deployment.apps/ldap created
   ```
3. `$ sudo lxc exec microk8s -- microk8s kubectl get pod`
   ```
   NAME                    READY   STATUS   RESTARTS   AGE
   ldap-7ddbb699cc-kmc87   0/1     Error    5          5m11s
   ```
4. `$ sudo lxc exec microk8s -- microk8s kubectl logs ldap-7ddbb699cc-kmc87`
   ```
   5feb3f7c ldif_write_entry: cannot create file for "cn=config": Permission denied
   slapadd: could not add entry dn="cn=config" (line=1): internal error (cannot create file)
   ```
**Details:**
Failure occurs on [invoke of](https://github.com/dcm4che-dockerfiles/slapd/blob/master/slapadd.sh#L3)
```
slapadd -n 0 -F /etc/openldap/slapd.d 
```
of Alpine Linux Package [openldap-2.4.50-r1](https://pkgs.alpinelinux.org/package/v3.12/main/x86_64/openldap) included in image [dcm4che/slapd-dcm4chee:2.4.50-23.0](https://hub.docker.com/r/dcm4che/slapd-dcm4chee/dockerfile) FROM [dcm4che/slapd:2.4.50](https://hub.docker.com/r/dcm4che/slapd/dockerfile) FROM [alpine:3.12.3](https://hub.docker.com/_/alpine).

It **does not** occur, on installing/running MicroK8s directly on the host (Ubuntu 20.10)!

The same error happens on `minikube` with docker driver: https://github.com/kubernetes/minikube/issues/10055

[inspection-report-20201229_144049.tar.gz](https://github.com/ubuntu/microk8s/files/5751118/inspection-report-20201229_144049.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @gunterze 

On dmesg I see this denial:
```
apparmor="DENIED" operation="mknod" profile="/usr/sbin/slapd" name="/etc/openldap/slapd.d/cn=config.FKkmaO"
```

Do you think you could change the lxd profile to allow this or the slapadd to write in another place?

**Comment by gunterze** [comment]
I am not familiar with lxd profiles. What lines I would have to add to https://raw.githubusercontent.com/ubuntu/microk8s/master/tests/lxc/microk8s-zfs.profile to allow this?

Thx
