### ISSUE TITLE
STATUS=Pending, k describe --pod-- returns "error: the server doesn't have a resource type ..."

### ISSUE THREAD

**Issue by johngrabner** [ubuntu/microk8s#1855]
`microk8s inspect`  attached 

Upgraded PC to ubuntu 20.04, and Upgraded microk8s to 1.20.

k apply -f xxx.yaml  ... these all worked in 1.19

```
k get pods
NAME                                       READY   STATUS    RESTARTS   AGE
image-deployment-b755d8ff5-7mvsj           0/1     Pending   0          6m47s
image-deployment-b755d8ff5-7pvlc           0/1     Pending   0          6m47s
transcription-deployment-d88f58c76-zg5hh   0/1     Pending   0          6m39s
transcription-deployment-d88f58c76-mjf54   0/1     Pending   0          6m39s
...
k describe image-deployment-b755d8ff5-7mvsj
error: the server doesn't have a resource type "image-deployment-b755d8ff5-7mvsj"

```

grep "error" -r .

returns lots of 

`./snap.microk8s.daemon-kubelet/journal.log:Dec 29 15:25:38 john-trx40-designare microk8s.daemon-kubelet[4866]: W1229 15:25:38.124537    4866 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/common/run/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix:///var/snap/microk8s/common/run/containerd.sock: timeout". Reconnecting...
[inspection-report-20201229_153313.tar.gz](https://github.com/ubuntu/microk8s/files/5752275/inspection-report-20201229_153313.tar.gz)
`

**Comment by ktsakalozos** [comment]
Could you share the inspection report so we can see what service is failing an how?
