### ISSUE TITLE
snapcraft microk8s through lxd issue

### ISSUE THREAD

**Issue by balasu** [ubuntu/microk8s#1859]
Hi
After cloning the repo, i was trying to run microk8s locally with below command, but it fails abruptly attached is the screenshot
snapcraft --use-lxd

![image](https://user-images.githubusercontent.com/39425180/103437527-af787800-4c4e-11eb-9911-b8fc4037b09c.png)

VM is ubuntu 20.10 5.8.0-25-generic

**Comment by ktsakalozos** [comment]
Hi @balasu. Not sure why this started happening now. Working on a fix now.
