### ISSUE TITLE
High Availability option when enabling addons?

### ISSUE THREAD

**Issue by petermetz** [ubuntu/microk8s#1861]
This is a question/feature request:

Currently a lot of the addons have single pod deployments by default (k8s dashboard, grafana, etc.) and while fail-over does work fine in multi-node setups, it takes a while when the first node goes down (e.g. where the addon enable was executed).
It would be nice if there was an option at addon-enable-time to specify replicas >1 for the addons. This way, if the first node goes down and you want to quickly investigate what is happening, you'll at least still have a dashboard that allows you to quickly visually assess what's happening. 

I'm aware that you could just run `kubectl get all` from another node and become aware of your first node being down, but if you go with that argument then you could say the dashboard addon had no point to be installed to begin with.
Thoughts?

**Comment by ktsakalozos** [comment]
I agree with you @petermetz, if an addon has an easy to configure HA setup we should opt for that since cluster HA gets enabled by default.

We should go over the core addons in [1] and review our deployment options.

[1] https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions
