### ISSUE TITLE
Microk8s Server Connection Refused on Raspberry Pi Ubuntu Server 

### ISSUE THREAD

**Issue by aliceseaborn** [ubuntu/microk8s#1862]
I followed the official [Canonical tutorial](https://ubuntu.com/tutorials/how-to-kubernetes-cluster-on-raspberry-pi#1-overview) for installing microk8s 1.19.6 on four Raspberry Pi 4Bs running fresh installs of Ubuntu 20.04.1 LTS with kernel version GNU/Linux 5.4.0-1025-raspi aarch64. Once the software was installed, I rebooted the machine and started k8s using `microk8s.start` and then checked the version of the client and verified that both the client and the server was running. However, after attempting to join the master node, suddenly my k8s server is not running or is otherwise disconnected. There is no firewall on the machine. The node is not listed as a part of the cluster by the master node despite no error message from the worker node when trying to join the cluster. 

```BASH
ubuntu@worker2:~$ microk8s.start
Started.
ubuntu@worker2:~$ microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-34+e6d0076d2a0033", GitCommit:"e6d0076d2a0033fd25db4a4abab19184d93d6ed4", GitTreeState:"clean", BuildDate:"2020-12-18T16:14:20Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-34+e6d0076d2a0033", GitCommit:"e6d0076d2a0033fd25db4a4abab19184d93d6ed4", GitTreeState:"clean", BuildDate:"2020-12-18T16:17:57Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
ubuntu@worker2:~$ microk8s join 192.168.1.7:25000/<token>
Contacting cluster at 192.168.1.7
Waiting for this node to finish joining the cluster. ..  
ubuntu@worker2:~$ microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-34+e6d0076d2a0033", GitCommit:"e6d0076d2a0033fd25db4a4abab19184d93d6ed4", GitTreeState:"clean", BuildDate:"2020-12-18T16:14:20Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

Furthermore, attempts at provisioning simple containers on the cluster fail and cause the previously responsive server on the master node to crash.

```BASH
ubuntu@master:~$ microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-34+e6d0076d2a0033", GitCommit:"e6d0076d2a0033fd25db4a4abab19184d93d6ed4", GitTreeState:"clean", BuildDate:"2020-12-18T16:14:20Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-34+e6d0076d2a0033", GitCommit:"e6d0076d2a0033fd25db4a4abab19184d93d6ed4", GitTreeState:"clean", BuildDate:"2020-12-18T16:17:57Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
ubuntu@master:~$ microk8s.kubectl run my-nginx --image nginx

^C
ubuntu@master:~$ microk8s.kubectl run my-nginx --image nginx
Unable to connect to the server: net/http: TLS handshake timeout
ubuntu@master:~$ microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-34+e6d0076d2a0033", GitCommit:"e6d0076d2a0033fd25db4a4abab19184d93d6ed4", GitTreeState:"clean", BuildDate:"2020-12-18T16:14:20Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/arm64"}
Unable to connect to the server: net/http: TLS handshake timeout
```

I have tried stopping and restarting microk8s, rebooting the machine, uninstalling microk8s then reinstalling version 1.18 and then 1.17 but none of these actions have any effect on the outcome. Is it even possible to run microk8s on Raspberry Pi 4Bs in the first place? With such a high rate of failure, I get the feeling that I am doing something wrong.

**Comment by Adial314** [comment]
I have attached the inspection report: [inspection-report-20210102_023907.tar.gz](https://github.com/ubuntu/microk8s/files/5759779/inspection-report-20210102_023907.tar.gz)

**Comment by alfusinigoj** [comment]
I am facing exact similar issue, but just on 3 VPS nodes, instead of Ras Pi. i have commented on a similar issue as well. Waiting for someone to provide a solution. 

https://github.com/ubuntu/microk8s/issues/1401#issuecomment-753562839

**Comment by alfusinigoj** [comment]
I was able to get around the issue by opening firewall for ports `1338,2380,12379,16443,19001,25000,10248-10259`

**Comment by alfusinigoj** [comment]
However, for joining the node first time, i had to remove the firewall completely.. so i guess there are additional ports other than the ones mentioned in the [documentation](https://microk8s.io/docs/ports). Needs help!

**Comment by ktsakalozos** [comment]
@Adial314 I see you are running with only 172MB of free memory (out of the 2GB of your node), could you add some swap so we get past that problem. Node that having swap is not recommended for Kubernetes deployments.

**Comment by ktsakalozos** [comment]
@alfusinigoj I think the ports you opened are mentioned in the documentation page you referenced. Do you have a recommendation on restructuring our docs to make the firewall requirements more clear?
