### ISSUE TITLE
Invalid URL used in 'microk8s enable kubeflow': https://api.jujucharms.com/identity

### ISSUE THREAD

**Issue by BionixAB** [ubuntu/microk8s#1867]
Scenario:
While running 'microk8s enable kubeflow' the installation fails with the following error message:
`cannot get discharge from "https://api.jujucharms.com/identity": cannot unmarshal wait error response: invalid character '<' looking for beginning of value
`
I do not feel the need for an inspection tarball since the above URL simply does not exist. (The 'invalid character' referred to originates from the response from the web server, which simply reports
```
<head>
<title>404 Not Found</title>
</head>
<body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at api.jujucharms.com Port 443</address>
</body>
```
I installed 'microk8s' with
`sudo snap install microk8s --classic --channel=latest/edge`
which installed version 1891.
I'm running Ubuntu 18.04.5 LTS Desktop on a Intel NUC 8i5BEC (Intel i5-8259U, 4+4 cores, 32GB RAM, 500GB .m2 SSD) wich attaches to a Nvidia GTX1080 via Thunderbolt. Nvidia Driver Version: 450.80.02.

**Comment by knkski** [comment]
@BionixAB: Can you paste the output from `microk8s enable kubeflow --debug`?
