### ISSUE TITLE
node NotReady , microk8s inspect with no errors, random node drop out of cluster

### ISSUE THREAD

**Issue by golgotow** [ubuntu/microk8s#1868]
Hello,

attaching microk8s inspect and output from working node. This appear unexpected and nothing I do make this nodes works 

root@brixone:~# microk8s.kubectl get nodes
NAME       STATUS     ROLES    AGE   VERSION
prox2      Ready      <none>   30d   v1.19.6-34+8e3147de1f0c4f
msi55      NotReady   <none>   56d   v1.19.6-34+8e3147de1f0c4f
corosync   NotReady   <none>   56d   v1.19.6-34+8e3147de1f0c4f
brixone    Ready      <none>   55d   v1.19.6-34+8e3147de1f0c4f
prox3      Ready      <none>   30d   v1.19.6-34+8e3147de1f0c4f
prox1      Ready      <none>   30d   v1.19.6-34+8e3147de1f0c4f

Best Regards,

[inspection-report-20210105_140959.tar.gz](https://github.com/ubuntu/microk8s/files/5770295/inspection-report-20210105_140959.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @golgotow 

There is this in the apiserver logs:
```
dqlite: proxy: first: remote -> local: read tcp 192.168.14.253:19001->192.168.13.180:47880: read: connection reset by peer
```
What are the IPs of the nodes you have?

Can you try to `microk8s remove-node` (maybe with `--force`) on the failing nodes and try to rejoin them?

**Comment by golgotow** [comment]
Hi @ktsakalozos 

I will tried to remove node today, but my question is why app in inspect is running, but for example api server on 16443 not listen? Any way to investigate it more ? 

Best Regards

**Comment by golgotow** [comment]
Hello,

I have no idea what happen, on node prox3 I did microk8sk stop/start and whole cluster start to work properly, before that whole cluster look like stucked.

I will close this issue later if no point how to investigate this kind of situation.

Best Regards

**Comment by golgotow** [comment]
whole cluster start to work after restarting one of nodes .
