### ISSUE TITLE
Update the microk8s Knative version

### ISSUE THREAD

**Issue by mattmoor** [ubuntu/microk8s#1869]
It looks like microk8s is shipping 0.13 (long unsupported): https://github.com/ubuntu/microk8s/blob/2088de9c95abdc59c1428e5acf127ff758c33f5a/build-scripts/set-env-variables.sh#L16

We'll be cutting 0.20 in roughly a week, and our supported version range will be 0.17-0.20 (currently 0.16 is the oldest supported version).

This recently came up in K8s slack #knative because users were trying to rationalize the docs on knative.dev (~0.19) with what they were seeing with the add-on (0.13) and things didn't make sense!

**Comment by ktsakalozos** [comment]
Thank you @mattmoor for bringing this to our attention, we will have to update the enable and disable scripts. 

I wonder if anyone from the MicroK8s/knative community would be interested in updating and even keeping those two scripts [1, 2] up-to-date. If not, we will have to make some time to so.

Thank you

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.knative.sh
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/disable.knative.sh

**Comment by ktsakalozos** [comment]
Hi @mattmoor, the 1.21 release will have the 0.21 knative version. Cheers.
