### ISSUE TITLE
how to access loadbalancer outside the vm

### ISSUE THREAD

**Issue by ffoysal** [ubuntu/microk8s#1888]
Install a ubuntu vm in mac, then did this
- install microk8s
- enable add-ons dns, storage, metallb
- deployed my kubernetes application

Now can see the loadbalancer external ip and can access the app(using loadbalancer ip) while inside the vm

How to access the app from outside(from host mac) the VM.

Help is very much appreciated.

**Comment by ktsakalozos** [comment]
Hi @ffoysal. If I understand the request correctly you need to forward the ports you want to expose from the host to the VM. This is outside the scope of MicroK8s. You may want to search on the web on how to do this, eg [1]. 

[1] https://superuser.com/questions/30917/how-to-make-a-port-forward-in-mac-os-x
