### ISSUE TITLE
Microk8s -  master node goes to NotReady state

### ISSUE THREAD

**Issue by sstoyanovqredo** [ubuntu/microk8s#1889]
Hello,
This issue occurs unexpectedly. 
Microk8s is installed over snap and all snap updates are stopped.
The cluster is created by one master(amd64) and three workers node (Raspberry Pi 4)
kubectl get nodes
NAME              STATUS   ROLES    AGE    VERSION
master        Ready    <none>   185d   v1.19.3-34+9e8b6537ec8b6f
node2         Ready    <none>   185d   v1.19.4-34+8ecc28b93f9bc0
node3         Ready    <none>   121d   v1.19.4-34+8ecc28b93f9bc0
node4         Ready    <none>   185d   v1.19.4-34+8ecc28b93f9bc0
Above are the versions  installed on each node. 
Revision number of the master node is 1786
All Pis are with 1812
 The master node goes unexpectedly to not ready status after 2-3-4 weeks  of working.
What i found is that kubelet restarts after 30s and the error that appears is "Cant create container with ID ...."
Additionally i have setup coredns , metrics-server to be deployed only on the master node.
The master node is machine with 48cores and 62G of  memory  and there is no overload  (Ubuntu 18.04 , kernel 4.15.0-129-generic)
all Pis are with Ubuntu 18.04 , kernel 5.3.0-1026-raspi2 , 4cores , 4G of memory
Any suggestions ?

**Comment by ktsakalozos** [comment]
Hi @sstoyanovqredo. It is hard to say what may have caused this. I would like to see the logs in the inspection tarball.
