### ISSUE TITLE
DNS doesn't work

### ISSUE THREAD

**Issue by 99ACA** [ubuntu/microk8s#1893]
kube-dns doesn't seem to work on a fresh installation  `snap install microk8s --classic --channel=1.13/stable`

Versions:

- snap    2.48.2
- snapd   2.48.2
- series  16
- ubuntu  20.04
- kernel  5.8.0-36-generic

Other system configuration:

- /proc/sys/net/ipv4/ip_forward **is 1**
- sudo ufw status **is  inactive** 

## troubleshooting 

- `kubectl -n kube-system describe po kube-dns-6ccd496668-64ghw`

```
Name:               kube-dns-6ccd496668-64ghw
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               buzz/10.0.0.14
Start Time:         Mon, 11 Jan 2021 00:44:14 +0200
Labels:             k8s-app=kube-dns
                    pod-template-hash=6ccd496668
Annotations:        scheduler.alpha.kubernetes.io/critical-pod: 
Status:             Running
IP:                 10.1.1.18
Controlled By:      ReplicaSet/kube-dns-6ccd496668
Containers:
  kubedns:
    Container ID:  docker://5a1e0b59338402851610deb94bd0bf849de1ed0d5168a6c5d2b0a39571ba62d5
    Image:         gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.7
    Image ID:      docker-pullable://gcr.io/google_containers/k8s-dns-kube-dns-amd64@sha256:f5bddc71efe905f4e4b96f3ca346414be6d733610c1525b98fff808f93966680
....
Events:
  Type     Reason     Age                   From           Message
  ----     ------     ----                  ----           -------
  Normal   Killing    26m (x10 over 59m)    kubelet, buzz  Killing container with id docker://dnsmasq:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy  6m43s (x71 over 60m)  kubelet, buzz  Liveness probe failed: HTTP probe failed with statuscode: 503
  Warning  BackOff    103s (x290 over 61m)  kubelet, buzz  Back-off restarting failed container

```

- `microk8s.kubectl -n kube-system logs kube-dns-6ccd496668-64ghw -c kubedns`
```
I0112 15:36:00.554045       1 dns.go:48] version: 1.14.6-3-gc36cb11
I0112 15:36:00.554520       1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
I0112 15:36:00.554544       1 server.go:112] FLAG: --alsologtostderr="false"
I0112 15:36:00.554550       1 server.go:112] FLAG: --config-dir="/kube-dns-config"
I0112 15:36:00.554555       1 server.go:112] FLAG: --config-map=""
I0112 15:36:00.554559       1 server.go:112] FLAG: --config-map-namespace="kube-system"
I0112 15:36:00.554562       1 server.go:112] FLAG: --config-period="10s"
I0112 15:36:00.554568       1 server.go:112] FLAG: --dns-bind-address="0.0.0.0"
I0112 15:36:00.554571       1 server.go:112] FLAG: --dns-port="10053"
I0112 15:36:00.554576       1 server.go:112] FLAG: --domain="cluster.local."
I0112 15:36:00.554582       1 server.go:112] FLAG: --federations=""
I0112 15:36:00.554587       1 server.go:112] FLAG: --healthz-port="8081"
I0112 15:36:00.554590       1 server.go:112] FLAG: --initial-sync-timeout="1m0s"
I0112 15:36:00.554594       1 server.go:112] FLAG: --kube-master-url=""
I0112 15:36:00.554598       1 server.go:112] FLAG: --kubecfg-file=""
I0112 15:36:00.554602       1 server.go:112] FLAG: --log-backtrace-at=":0"
I0112 15:36:00.554608       1 server.go:112] FLAG: --log-dir=""
I0112 15:36:00.554612       1 server.go:112] FLAG: --log-flush-frequency="5s"
I0112 15:36:00.554617       1 server.go:112] FLAG: --logtostderr="true"
I0112 15:36:00.554621       1 server.go:112] FLAG: --nameservers=""
I0112 15:36:00.554624       1 server.go:112] FLAG: --stderrthreshold="2"
I0112 15:36:00.554628       1 server.go:112] FLAG: --v="2"
I0112 15:36:00.554631       1 server.go:112] FLAG: --version="false"
I0112 15:36:00.554638       1 server.go:112] FLAG: --vmodule=""
I0112 15:36:00.554673       1 server.go:194] Starting SkyDNS server (0.0.0.0:10053)
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
k8s.io/dns/vendor/github.com/miekg/dns.ClientConfigFromFile(0x17178f3, 0x10, 0x0, 0x0, 0x0)
	/go/src/k8s.io/dns/vendor/github.com/miekg/dns/clientconfig.go:86 +0x948
k8s.io/dns/vendor/github.com/skynetservices/skydns/server.SetDefaults(0xc42044e6c0, 0xc42044e6c0, 0xc420605e38)
	/go/src/k8s.io/dns/vendor/github.com/skynetservices/skydns/server/config.go:122 +0x8aa
k8s.io/dns/cmd/kube-dns/app.(*KubeDNSServer).startSkyDNSServer(0xc42008b590)
	/go/src/k8s.io/dns/cmd/kube-dns/app/server.go:208 +0x3ea
k8s.io/dns/cmd/kube-dns/app.(*KubeDNSServer).Run(0xc42008b590)
	/go/src/k8s.io/dns/cmd/kube-dns/app/server.go:115 +0x55
main.main()
	/go/src/k8s.io/dns/cmd/kube-dns/dns.go:51 +0x2cd

```

- `kubectl get all --all-namespaces`

NAMESPACE       NAME                                                  READY   STATUS             RESTARTS   AGE
cert-manager    pod/cert-manager-7df5c67dfc-mbts6                     1/1     Running            13         40h
cert-manager    pod/cert-manager-cainjector-f54c57bf8-55cpp           1/1     Running            22         40h
cert-manager    pod/cert-manager-webhook-76794c6967-t57qt             1/1     Running            11         40h
convox-system   pod/atom-9b94cd6d7-2gngt                              1/1     Running            12         40h
convox-system   pod/router-f4b66cf57-qwscc                            1/1     Running            10         39h
convox          pod/api-65b7655c4-8x2sl                               1/1     Running            12         39h
convox          pod/registry-7bb479d45c-w66kt                         1/1     Running            11         39h
kube-system     pod/heapster-v1.5.2-64874f6bc6-ww7zn                  4/4     Running            22         4h48m
kube-system     pod/hostpath-provisioner-599db8d5fb-6lbjv             1/1     Running            8          40h
kube-system     pod/kube-dns-6ccd496668-64ghw                         1/3     CrashLoopBackOff   663        40h
kube-system     pod/kubernetes-dashboard-654cfb4879-j9lgs             1/1     Running            5          4h49m
kube-system     pod/metrics-server-85568bffdc-p2thm                   1/1     Running            7          39h
kube-system     pod/monitoring-influxdb-grafana-v4-6679c46745-mhrvx   2/2     Running            10         4h49m

NAMESPACE       NAME                           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
cert-manager     service/cert-manager           ClusterIP      10.152.183.244   <none>        9402/TCP                     40h
cert-manager     service/cert-manager-webhook   ClusterIP      10.152.183.143   <none>        443/TCP                      40h
convox-system   service/resolver               LoadBalancer   10.152.183.65    <pending>     53:30472/UDP                 39h
convox-system   service/resolver-internal      NodePort       10.152.183.120   <none>        53:30979/UDP                 39h
convox-system   service/router                 LoadBalancer   10.152.183.84    <pending>     80:31872/TCP,443:30095/TCP   39h
convox                service/api                    NodePort       10.152.183.78    <none>        5443:31527/TCP               39h
convox                service/registry               NodePort       10.152.183.181   <none>        80:30785/TCP                 39h
default                service/kubernetes             ClusterIP      10.152.183.1     <none>        443/TCP                      41h
kube-system      service/heapster               ClusterIP      10.152.183.43    <none>        80/TCP                       4h49m
kube-system      service/kube-dns               ClusterIP      10.152.183.10    <none>        53/UDP,53/TCP                40h
kube-system      service/kubernetes-dashboard   ClusterIP      10.152.183.194   <none>        443/TCP                      4h49m
kube-system      service/metrics-server         ClusterIP      10.152.183.209   <none>        443/TCP                      39h
kube-system      service/monitoring-grafana     ClusterIP      10.152.183.248   <none>        80/TCP                       4h49m
kube-system      service/monitoring-influxdb    ClusterIP      10.152.183.128   <none>        8083/TCP,8086/TCP            4h49m

Please run `microk8s inspect` [and attach the generated tarball to this issue.](https://drive.google.com/file/d/1oDa-8G3UiTZiCc4jU2jKytV3klUYzOSR/view?usp=sharing)

**Comment by ktsakalozos** [comment]
Hi @99ACA 

What you are describing seem like an issue on kube-dns on v1.14 kubernetes. Since kubernetes v1.14 is not supported anymore [1], do you think you could move to a newer version where kube-dns is replaced by coredns?

[1] https://kubernetes.io/docs/setup/release/version-skew-policy/

**Comment by 99ACA** [comment]
@ktsakalozos 

Thanks for replay,
I will upgrade and will verify it.

**Comment by 99ACA** [comment]
It is working with the new version.
10x
