### ISSUE TITLE
Default CoreDNS config does not work on AWS Wavelength

### ISSUE THREAD

**Issue by codefrau** [ubuntu/microk8s#1894]
The default `coredns` ConfigMap installed by microk8s points to Google's DNS (8.8.8.8). 

On AWS in general, that works fine. But on Wavelength, those DNS servers are blocked:
```
$ nslookup google.com 8.8.8.8 
;; connection timed out; no servers could be reached
```

To make it work I had to edit the ConfigMap to use
```
forward . /etc/resolv.conf
```
and add 
```
--resolv-conf=/run/systemd/resolve/resolv.conf
```
to the `kubelet` args in /var/snap/microk8s/current/args/kubelet (as suggested by https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/#known-issues)

This situation could be detected using something like my `nslookup` command above. If the installer had done this it would have saved me many hours.

**Comment by joedborg** [comment]
Thanks for the big, that’s very useful information.  Out of interest, do you know if 1.1.1.1 and 2.2.2.2 are blocked too?

**Comment by codefrau** [comment]
They are blocked, yes.

I would not be surprised if all DNS traffic to outside servers is blocked, since Wavelength is all about speed optimization. So using AWS DNS servers makes sense.

Btw, `ping 8.8.8.8` works.

**Comment by ktsakalozos** [comment]
Thank you for reporting and debugging this @codefrau. We would need to detect such cases in [1] and act accordingly. 

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.dns.sh
