### ISSUE TITLE
enable.kubeflow.sh, function(check_connectivity) donot work, how to solve it?

### ISSUE THREAD

**Issue by zhangsan09** [ubuntu/microk8s#1895]
when i run command: microk8s.enable kubeflow, 
i always get same result when microk8s version is 1.19 or 1.20 installed by snap:

--------------------------------------------

Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for DNS and storage plugins to finish setting up
DNS and storage setup complete. Checking connectivity...
Couldn't contact api.jujucharms.com
Please check your network connectivity before enabling Kubeflow.

--------------------------------------------

i‘ve tried to ’add parameter "--debug" but donot get helpful output information

in the script enable.kubeflow.sh (/snap/microk8s/xxxx/microk8s-resources/actions/enable.kubeflow.sh)
there is a funtuion:check_connectivity, it just use pytohn3 urllib.request to request a url(https://api.jujucharms.com/charmstore/v5/istio-pilot-5/icon.svg, defined by CONNECTIVITY_CHECKS )
when i request this url i can get a logo picture on the local machine(cent os)
and this function cannot be skipped, i donnot undersatand what it have done and how to resolve this problem

it troubles me for a few times.....

**Comment by Windfarer** [comment]
the same error on 
microk8s 1.20.1
archlinux

**Comment by knkski** [comment]
@ktsakalozos: Any ideas what might be causing calico issues here?
