### ISSUE TITLE
invalid capacity 0 on image filesystem

### ISSUE THREAD

**Issue by etrey** [ubuntu/microk8s#1896]
When running microk8s.kubectl describe node ubuntu I am getting the following error

Warning  InvalidDiskCapacity      2m54s  kubelet  invalid capacity 0 on image filesystem
  Normal   Starting                 2m54s  kubelet  Starting kubelet.
  Warning  InvalidDiskCapacity      2m42s  kubelet  invalid capacity 0 on image filesystem
  Normal   Starting                 2m42s  kubelet  Starting kubelet.
  Normal   Starting                 2m30s  kubelet  Starting kubelet.
  Normal   NodeHasSufficientMemory  2m30s  kubelet  Node ubuntu status is now: NodeHasSufficientMemory
  Warning  InvalidDiskCapacity      2m30s  kubelet  invalid capacity 0 on image filesystem
  Warning  InvalidDiskCapacity      2m18s  kubelet  invalid capacity 0 on image filesystem
  Normal   Starting                 2m18s  kubelet  Starting kubelet.
  Normal   Starting                 2m5s   kubelet  Starting kubelet.

When describing pod - I get the following error Warning FailedScheduling 30s (x33 over 41m) default-scheduler 0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.

From what I know I am not running ZFS on my Raspberry Pi 4 - but I have a 128gb sd card with an ext4 filesystem. I have tried this guide - but I don't have a ZFS pool....

Not sure where to go from here.

**Comment by liuxh0** [comment]
I have the same issue here. Also running on Raspberry Pi 4 (2G RAM, 128G SD card) with Ubuntu Server 20.04.
