### ISSUE TITLE
[Documentation] Can we have a link to repo/details on add-on docs

### ISSUE THREAD

**Issue by rockaut** [ubuntu/microk8s#1899]
Good Morning from Austria,

It would be nice if we could have some more informations on add-ons directly in the docs (like: https://microk8s.io/docs/addon-ambassador). Just a little, tiny box at the bottom or top with links to:
- Original Repos
- Project Homepage (currently it is sometimes only "the name" which links there)
- Link to the microk8s Repo-path
- first mk8s Version supported
- supported arches

**Comment by ktsakalozos** [comment]
That is a good suggestion @rockaut . Thank you.

**Comment by evilnick** [comment]
Yes, that is a good idea. I will try and work out some sort of information box which will work within the constraints of discourse
