### ISSUE TITLE
[Documentation] "Option to set forward DNS servers when enabling DNS"

### ISSUE THREAD

**Issue by Ramblurr** [ubuntu/microk8s#1902]
According to the 1.20 release notes there is an "Option to set forward DNS servers when enabling DNS".

Would absolutely love to use this, but it's not documented.

**Comment by balchua** [comment]
I think you can do this `microk8s enable dns:/etc/resolv.conf`

**Comment by ktsakalozos** [comment]
Just updated the doc page at https://discuss.kubernetes.io/t/add-on-dns/11287

**Comment by balchua** [comment]
Thanks @Ramblurr the documentation has been updated.
