### ISSUE TITLE
Option to disable vxlan and use BGP with calico

### ISSUE THREAD

**Issue by Ramblurr** [ubuntu/microk8s#1903]
This is a feature/documentation request.

Microk8s uses calico which is great. In some environments I do not want to use vxlan, but rather want native networking with BGP.

Is there a way to achieve this with microk8s as it stands now? If not, could this be added?

**Comment by ktsakalozos** [comment]
Hi @Ramblurr,

You can find the calico manifest in `/var/snap/microk8s/current/args/cni-network/cni.yaml`. I believe you can configure calico according to [1].

[1] https://docs.projectcalico.org/getting-started/kubernetes/installation/config-options
