### ISSUE TITLE
canonical/libco Repository not found

### ISSUE THREAD

**Issue by logici** [ubuntu/microk8s#1907]
ENV : 
- multipass ubuntu16.04
- snapcraft, version 4.4.4
- microk8s tag v.1.19
RUN:
SNAPCRAFT_BUILD_ENVIRONMENT=host KUBE_VERSION=v1.19.7 snapcraft
when Pulling libco 
```
remote: Repository not found.
fatal: repository 'https://github.com/canonical/libco/' not found
Failed to pull source, command 'git clone --recursive https://github.com/canonical/libco /home/ubuntu/microk8s/parts/libco/src' exited with code 128.
```
and run ` git clone --recursive https://github.com/canonical/libco /home/ubuntu/microk8s/parts/libco/src`
```
Cloning into 'libco'...
remote: Repository not found.
fatal: repository 'https://github.com/canonical/libco/' not found
```
and, I do not search `canonical/libco` in the github.
So, how can I build the microk8s ?

**Comment by balchua** [comment]
You can try checking out 1.19 branch.  I saw some commit removing libco.

**Comment by logici** [comment]
Thank you. I will try it.
