### ISSUE TITLE
on ha cluster pull private registry fail

### ISSUE THREAD

**Issue by codinggg** [ubuntu/microk8s#1908]
Hello, I have three microk8s node on my three virtual machine.Ip is 192.168.15.55, 192.168.15.57 and 192.168.15.63. 55 is master. I used with ha-cluster mode, I want use private registry to pull images, and I opened microk8s's registry. I rename and push with name 192.168.1.55:32000/my-server:v2 in my master node, but show me pull image failed when I deployment pod.

```
Failed to pull image "192.168.15.55:32000/test-server:v2": rpc error: code = Unknown desc = failed to pull and unpack image "192.168.15.55:32000/test-server:v2": failed to resolve reference "192.168.15.55:32000/test-server:v2": failed to do request: Head "https://192.168.15.55:32000/v2/test-server/manifests/v2": net/http: TLS handshake timeout
```

I take look pods find they running on 57 and 63 node. 
I add `"insecure-registries"` to /etc/docker/daemon.json in 55 node. How to solve this error? Thank you!

```
 [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.15.55:32000"]
        endpoint = ["http://192.168.15.55:32000"]
```
There is report:
[inspection-report-20210117_102740.tar.gz](https://github.com/ubuntu/microk8s/files/5826008/inspection-report-20210117_102740.tar.gz)

**Comment by balchua** [comment]
Just a quick question, did you add the `containerd` configuration you showed above on all you nodes?

**Comment by codinggg** [comment]
Yes, I don't add docker registry configuration to others nodes, now pull image successfully!!!
Thank you a lot!! ;)
