### ISSUE TITLE
Telepresence does not work with micro8s, nsenter/libselinux.so.1 missing

### ISSUE THREAD

**Issue by dmarkey** [ubuntu/microk8s#191]
34.8  25 | E1116 17:34:34.517444   24516 portforward.go:331] an error occurred forwarding 44657 -> 8022: error forwarding port 8022 to pod 4719bd97f6194581f6a74716d263e5a0fdfbeec9f44e457de341c1822d9727e1, uid : exit status 127: /snap/microk8s/266/usr/bin/nsenter: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
  34.8 TEL | [138] exit 255 in 0.01 secs.
 :(

**Comment by ktsakalozos** [comment]
@dmarkey thank you for the issue. Would it be possible to provide me with a minimal set of instructions/scripts I could reach to the error you report?

Thank you for using microk8s.

**Comment by johnraz** [comment]
Just for the record I didn't have any problem running telepresence.

**Comment by maciej-sawicki-codilime** [comment]
may be not related to teleconference:

kubectl port-forward dev-consul-654df67b94-7rsxb 8500
curl localhost:8500
E0320 12:31:22.823413   23830 portforward.go:331] an error occurred forwarding 8500 -> 8500: error forwarding port 8500 to pod f9f539580b2985e7eff9564b6f8ab7a1bb7cad2021efe67de0d89a1747ccdc57, uid : exit status 127: /snap/microk8s/437/usr/bin/nsenter: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory

**Comment by ktsakalozos** [comment]
@maciej-sawicki-codilime are you on some flavor of Arch Linux? There is a workaround for the same error under a similar situation in https://github.com/ubuntu/microk8s/issues/214#issuecomment-450864782 . Cloud you try to `yay -S libselinux`?
