### ISSUE TITLE
How to setup proxy for the container runtime, not only for pulling images behind the proxy

### ISSUE THREAD

**Issue by georgedriver** [ubuntu/microk8s#1913]
I followed the instruction from [this article](https://microk8s.io/docs/install-proxy) to setup the proxy to pull the images behind the proxy successfully. 

But it seems the proxy setup is `not working` inside the container runtime (I want the running pod can also use the same proxy).

I want to have the similar setup for `docker systemd proxy` which just put below entries into the file `/etc/systemd/system/docker.service.d/http-proxy.conf` and takes effect anyway include in the container runtime. (I can't use this method anymore since microk8s changed its runtime to CRI-O).

```
[Service]
Environment="HTTP_PROXY=http://<proxy-ip>:<port>/"
Environment="HTTPS_PROXY=http://<proxy-ip>:<port>/"
Environment="NO_PROXY=localhost,127.0.0.1,localaddress,.localdomain.com"
```

Share your idea if you have any, really appreciate!

**Comment by balchua** [comment]
I don't know how to do this in containerd, but i've had success using `PodPreset` where i inject a set of environment variables to the pods.
Here are useful links
* https://v1-19.docs.kubernetes.io/docs/concepts/workloads/pods/podpreset/
* https://github.com/anderseknert/podpreset-example
