### ISSUE TITLE
Try `microk8s enable kubeflow` instead.

### ISSUE THREAD

**Issue by qingfengmingyue** [ubuntu/microk8s#1934]
ubuntu :
microk8s enable kubeflow

This command can't be run as root.
Try `microk8s enable kubeflow` instead.

**Comment by qingfengmingyue** [comment]
@knkski Can you give me some advice on this problem,thanks

**Comment by ktsakalozos** [comment]
@qingfengmingyue could you try to add yous self to the microk8s group [1] and try `microk8s enable kubeflow` again?


[1] https://microk8s.io/docs
