### ISSUE TITLE
High Availability mode doesn't work

### ISSUE THREAD

**Issue by iinkov** [ubuntu/microk8s#1935]
[inspection-report-20210125_145822.tar.gz](https://github.com/ubuntu/microk8s/files/5867108/inspection-report-20210125_145822.tar.gz)

I have 3 nodes High Availability cluster. Created it from scratch for the test
I just switch off machine that is leader and everything is hanging
Just the leader is back everything works fine again

the same stuff for v1.20

As I get new leader election should takes 3 sec

**Comment by ktsakalozos** [comment]
Hi @iinkov I see the apiserver is not healthy and the 2GB of memory are not helping much. All nodes are of the same specifications? Would you be able to switch to a setup with 4GB on each node?

**Comment by iinkov** [comment]
@ktsakalozos 
New setup with 8gb for all nodes
![image](https://user-images.githubusercontent.com/18047365/106045437-9649d680-60e9-11eb-9a55-a161a210336e.png)

**Comment by iinkov** [comment]
5. Start leader machine testk8s1 (157.90.27.84)
6. `
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1856/inspection-report-20210127_203716.tar.gz`

7.Inspect one more time 
[inspection-report-20210127_204140.tar.gz](https://github.com/ubuntu/microk8s/files/5882744/inspection-report-20210127_204140.tar.gz)

**Comment by iinkov** [comment]
@ktsakalozos 
> Hi @iinkov I see the apiserver is not healthy and the 2GB of memory are not helping much. All nodes are of the same specifications? Would you be able to switch to a setup with 4GB on each node?

Yes it was 2gb and all nodes with the same specs

Which apiserver was not healthy? Leader?

**Comment by erictuvesson** [comment]
@iinkov Did it help upgrading the servers?

I am having this issue too with (CPX11) 2GB RAM.

**Comment by iinkov** [comment]
> @iinkov Did it help upgrading the servers?

@erictuvesson No, I did 8gb last time. It has the same issue

> I am having this issue too with (CPX11) 2GB RAM.

I tried different versions of microk8s and this doesn't help too

I think this is some bug and this is funny as it is the main purpose of the tool as for me

**Comment by erictuvesson** [comment]
I upgraded my servers to CPX21. It has a little bit more CPU power, which I noticed was getting bottlenecked. 

Type | VCPUS | RAM | SSD
-- | -- | -- | --
CPX21 | 3 | 4 GB | 20GB

It doesn't seem to freeze as much then, but noticed that 2 of my 4 nodes are not connected to the cluster. Which is causing other issues.

```
Name:               node-1
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=node-1
                    kubernetes.io/os=linux
                    microk8s.io/cluster=true
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.44.0.3/32
                    projectcalico.org/IPv4VXLANTunnelAddr: 10.1.84.128
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Sat, 06 Feb 2021 15:14:22 +0100
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  node-1
  AcquireTime:     <unset>
  RenewTime:       Sun, 07 Feb 2021 18:09:00 +0100
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----                 ------    -----------------                 ------------------                ------              -------
  NetworkUnavailable   False     Sat, 06 Feb 2021 15:14:58 +0100   Sat, 06 Feb 2021 15:14:58 +0100   CalicoIsUp          Calico is running on this node
  MemoryPressure       Unknown   Sun, 07 Feb 2021 18:07:33 +0100   Sun, 07 Feb 2021 18:09:45 +0100   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure         Unknown   Sun, 07 Feb 2021 18:07:33 +0100   Sun, 07 Feb 2021 18:09:45 +0100   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure          Unknown   Sun, 07 Feb 2021 18:07:33 +0100   Sun, 07 Feb 2021 18:09:45 +0100   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready                Unknown   Sun, 07 Feb 2021 18:07:33 +0100   Sun, 07 Feb 2021 18:09:45 +0100   NodeStatusUnknown   Kubelet stopped posting node status.
```

I am able to login to that server, just that I am not able to start microk8s. (same as https://github.com/ubuntu/microk8s/issues/1730) 

There are no connection issues on node-1. It can ping to all the nodes, just that it won't send any status calls to master. 

I am about to give up on microk8s, it doesn't feel very stable, don't really want that in a production environment.

**Comment by iinkov** [comment]
@erictuvesson seems your leader node is changed now and hence the cluster is not frozen. To see which node is the leader
```
> kubectl describe ep -n kube-system kube-controller-manager
Name:         kube-controller-manager
Namespace:    kube-system
Labels:       <none>
Annotations:  control-plane.alpha.kubernetes.io/leader:
                {"holderIdentity":"LEADER_IS_HERE","leaseDurationSeconds":15,"acquireTime":"201...
Subsets:
Events:  <none>
```
Sometimes It is need to be dropped the leader several times to get the issue

**Comment by ykudin** [comment]
Hi guys, we have the same problem with our cluster. Actually, absolutely the same behaviour as @iinkov explained.
We don't have any ideas on how to fix it and IMHO this is one of the most important features of K8S.
@ktsakalozos we would appreciate your support here.

Thanks,
Y

**Comment by ktsakalozos** [comment]
For such (maybe low spec) clusters we prepare a number of patches to go in the 1.21 release. For now you can give them a try if you deploy from the latest/edge channel.
```
sudo snap install microk8s --classic --channel=latest/edge
```

**Comment by erictuvesson** [comment]
I have been running a cluster for about a day now. Been turning the servers on and off in random orders and I can't replicate the issue.

Thanks @ktsakalozos!

**Comment by iinkov** [comment]
I've tried latest/edge version v1.20.2 the issue is reproduced form the first time. The steps are exactly the same as https://github.com/ubuntu/microk8s/issues/1935#issuecomment-768535392. Did `snap remove microk8s` before installing the latest version. 1.21 release is not available yet https://snapcraft.io/microk8s
![image](https://user-images.githubusercontent.com/18047365/107659632-003cb100-6c90-11eb-87a8-65368896b38e.png)

**Comment by ktsakalozos** [comment]
I am sorry @erictuvesson, @iinkov is right, I can also reproduce the issue. Here is how.

You have to have exactly three nodes. Three nodes are the minimum to have quorum and be able to reliably elect a leader. You need to kill the node acting as the leader. To locate the leader:
```
sudo -E /snap/microk8s/current/bin/dqlite -c /var/snap/microk8s/current/var/kubernetes/backend/cluster.crt -k /var/snap/microk8s/current/var/kubernetes/backend/cluster.key -s file:///var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml k8s ".leader"
```
To kill the leader you have to pull the plug of the machine or power off the VM or `kill -9` the apiserver (or kubelite) process. You should not allow the time for microk8s to shutdown or else the leader will handover leadership. As soon as the leader is unreachable a countdown of 30 seconds starts. Within these 30 seconds the remaining two nodes will elect a new leader as they are two and they should be able to have majority. The 30 seconds interval is selected to accommodate temporary disconnects and cluster partitions. From the remaining two nodes the one that becomes a leader will continue functioning with no issues. The node that was not elected will eventually use the new leader. Unfortunately the node that was not elected to be the new leader keeps some connections to the old leader so it will start using the new leader when these connections timeout. This is the bug. I am working on a fix. 

A note here, having two nodes may become problematic, you should add a third node as soon as possible so that a quorum can be formed.

**Comment by iinkov** [comment]
@ktsakalozos thx a lot for the fix (=. Is there any way to get it on my environment at the moment?

**Comment by ktsakalozos** [comment]
@iinkov, Thank you for reporting this bug and helping make MicroK8s better. Within the day the patch will land on the `latest/edge` channel (`sudo snap install microk8s --classic --channel=latest/ege`). It will reach the stable channel with the v1.21 release.
