### ISSUE TITLE
Fresh MicroK8s Cluster Not Starting

### ISSUE THREAD

**Issue by ThePieMonster** [ubuntu/microk8s#1939]
Just created a fresh microk8s cluster follow [microk8s.io](https://microk8s.io/). 
The `microk8s kubectl get all --all-namespaces` command was taking a while to return results to I cancelled it, ran microk8s stop then start and now get the below.

`microk8s status`
`microk8s is not running. Use microk8s inspect for a deeper inspection.`

`microk8s inspect`
```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/1910/inspection-report-20210126_053926.tar.gz

```

Here is the tar ball, I just starting using MicroK8S and I'm not sure what file I should be looking at first to help point in the right direction of where the issue should be.

[inspection-report-20210126_053926.tar.gz](https://github.com/ubuntu/microk8s/files/5871425/inspection-report-20210126_053926.tar.gz)

**Comment by balchua** [comment]
I can see that the calico-kube-controller isn't healthy.  And the load of the system is very high.
You may want to increase the memory of the system or start with reducing the pods.  IMHO 4GB is a good start though.
Prometheus and istio are heavy weights.

**Comment by ThePieMonster** [comment]
@balchua Thanks for the response. Updated the RAM to 4GB and rebooted. Things are running smoothly it seems.

I am having trouble accessing the dashboard however.
`microk8s.kubectl get all --all-namespaces | grep service/kubernetes-dashboard`
`kube-system          service/kubernetes-dashboard        ClusterIP      10.152.183.103   <none>        443/TCP  `

Then on another PC, navigated to https://10.152.183.103 but not getting a response. The node IP itself is 10.1.50.100. Is this expected to be accessed from the same node running the containers by chance or is it exposed publicly so other devices can access it. Typing this I realize there is no route to 10.152.183.0/24 from the 10.1.50.0/24 network so not sure how other devices can access the dashboard.

**Comment by balchua** [comment]
Are you running MicroK8s on bare metal or on a virtualized environment like mac or windows.

There is a section in (this)[https://microk8s.io/docs/addon-dashboard] link  explaining how to do so.
Thanks!

**Comment by ktsakalozos** [comment]
@ThePieMonster the `10.1.50.0/24` may be causing issues. The pods are placed in 10.1.0.0/16 network. Would you be able to select a different network for the host?

**Comment by ThePieMonster** [comment]
@balasu 
MicroK8S is running in a Ubuntu VM. The VM is on the 10.1.50.0/24 network as that is a available network that is set aside for the K8S VM's.
@ktsakalozos 
What do you mean by selecting a different network? Is there a config change that should be made when setting up the MicroK8S node. I imagine that all sorts of different base networks are used to host the nodes by different people. Is there some routing that needs to be setup to be able to access the nodes that is expected as part of the setup?

**Comment by balasu** [comment]
Hi @ThePieMonster  , instead of dashboard , portainer can be an option. if its microk8s version 1.20, microk8s enable portainer addon is available and on port 30777 its accessible. dashboard-proxy is not required for this

**Comment by balchua** [comment]
Hi @ThePieMonster the `dashboard-proxy` is doing `port-forward`ing[1].  That's why it has to stay up.  Stopping the command doesn't really stop the kubernetes dashboard, but only the port forwarding.
If i need to expose the dashboard to anywhere, which i dont really do for security sake, i use ingress to expose it. 
Some details you can get from this stackoverflow[2].  Hope this helps.


[1] https://github.com/ubuntu/microk8s/blob/8d0b9e5d6cfdb61b855b0d1ad657b43c4db73583/scripts/wrappers/dashboard-proxy.py#L62-L70

[2] https://stackoverflow.com/questions/48324760/ingress-configuration-for-dashboard

**Comment by ThePieMonster** [comment]
@balchua @balasu I would like to be able to have access to the dashboard via port forward. I'm guessing I will have to do port forwarding for accessing prometheus as well. Currently I have the below deployments. Do you know what would specifically have to be updated in order to get port forwarding working. Since it seems I don't have nginx I would be modifying istio-ingressgateway?

```
NAMESPACE            NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system          deployment.apps/metrics-server              1/1     1            1           4d19h
kube-system          deployment.apps/hostpath-provisioner        1/1     1            1           4d19h
istio-system         deployment.apps/istio-policy                1/1     1            1           4d19h
istio-system         deployment.apps/istio-sidecar-injector      1/1     1            1           4d19h
istio-system         deployment.apps/istio-galley                1/1     1            1           4d19h
kube-system          deployment.apps/dashboard-metrics-scraper   1/1     1            1           4d19h
kube-system          deployment.apps/coredns                     1/1     1            1           4d19h
container-registry   deployment.apps/registry                    1/1     1            1           4d19h
istio-system         deployment.apps/istio-citadel               1/1     1            1           4d19h
istio-system         deployment.apps/grafana                     1/1     1            1           4d19h
istio-system         deployment.apps/istio-telemetry             1/1     1            1           4d19h
istio-system         deployment.apps/istio-pilot                 1/1     1            1           4d19h
istio-system         deployment.apps/istio-tracing               1/1     1            1           4d19h
istio-system         deployment.apps/kiali                       1/1     1            1           4d19h
istio-system         deployment.apps/prometheus                  1/1     1            1           4d19h
istio-system         deployment.apps/istio-ingressgateway        1/1     1            1           4d19h
istio-system         deployment.apps/istio-egressgateway         1/1     1            1           4d19h
kube-system          deployment.apps/kubernetes-dashboard        1/1     1            1           4d19h
kube-system          deployment.apps/calico-kube-controllers     1/1     1            1           4d19h

```

**Comment by balchua** [comment]
If you want to port forward with the dashboard i will simply use the `dashboard-proxy`.
While for the others, its going to be similar to what you are doing.  But you need to know the port used by the containers.

**Comment by ThePieMonster** [comment]
> If you want to port forward with the dashboard i will simply use the `dashboard-proxy`.
> While for the others, its going to be similar to what you are doing. But you need to know the port used by the containers.
Yes but I am trying to set something up that is permanent and not relying on running that command.

**Comment by balchua** [comment]
Ingress maybe a better option imho.

**Comment by ThePieMonster** [comment]
Solution was to run `microk8s kubectl edit service -n kube-system kubernetes-dashboard`
Change type to `type: NodePort`
Run the first command again to see the nodePort that was automatically set and use that as the node-ip:port to connect too.
