### ISSUE TITLE
microk8s pods crashing with CrashLoopBackOff error

### ISSUE THREAD

**Issue by MakrandPare** [ubuntu/microk8s#1942]
Please run `microk8s inspect
[inspection-report-20210126_164036.tar.gz](https://github.com/ubuntu/microk8s/files/5876955/inspection-report-20210126_164036.tar.gz)
` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by MakrandPare** [comment]
Hi,
While creating a kubernetes deployment using microk8s, the pod is failing with the below error:
microk8s.kubectl get pods
NAME                                   READY   STATUS             RESTARTS   AGE
kubernetes-bootcamp-57978f5f5d-l6qd9   0/1     CrashLoopBackOff   23         98m

I have already attached the microk8s inspect tarball to this issue. Please let me know if anything else is needed.
Also I'm running this on  Ubutu using a Raspberry Pi.

**Comment by ktsakalozos** [comment]
Hi @MakrandPare 

In the logs of the pod I see:
```
standard_init_linux.go:219: exec user process caused: exec format error
```
This most probably means you are using an image for kubernetes-bootcamp that is not applicable for the architecture of your host, ARM64.

**Comment by MakrandPare** [comment]
Hi Konstantinos,
Thanks for your reply. I guess like you are right. Actually I was using this image as specified in the kubernetes tutorial https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive/,  which is directed for minikube. 
Seems like there is a difference between the way kubernetes images behave on minikube versus microk8s.

I may have to look for tutorials specifically written for microk8s.

Thanks again for your response,
Makrand

**Comment by balchua** [comment]
Hi @MakrandPare i will close this issue for now.
If you need help, don't hesitate to create one.

Thanks.
