### ISSUE TITLE
can not enable kubeflow with microk8s

### ISSUE THREAD

**Issue by qingfengmingyue** [ubuntu/microk8s#1948]
run：microk8s enable kubeflow

Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...

just hangs，so I stopped the process.
Then I run microk8s inspect 

![image](https://user-images.githubusercontent.com/7944239/106084833-0d1eb800-615a-11eb-9423-6fc2fb81c5d0.png)
I am attaching the full tarball file generated.
[inspection-report-20210128_110647.tar.gz](https://github.com/ubuntu/microk8s/files/5884534/inspection-report-20210128_110647.tar.gz)

**Comment by knkski** [comment]
@qingfengmingyue: can you post the output from `microk8s enable kubeflow --debug`? That will have more information about what went wrong.
