### ISSUE TITLE
Ingress address always 127.0.0.1

### ISSUE THREAD

**Issue by hokamc** [ubuntu/microk8s#1962]
With metallb and nginx ingress controller, the ingress service get external ip. whole things work.
`ingress ingress LoadBalancer   10.152.183.248   xxx.yyy.zzz.vvv   80:30229/TCP,443:32601/TCP `

However, the address of ingress is always 127.0.0.1.
`kube-system testing-ingress <none> xxx.yyyy.com 127.0.0.1 80, 443`

This affects other softwares like external-dns to work properly.

How can I assign the external ip to ingress instead of 127.0.0.1 ?

**Comment by patsevanton** [comment]
Same issue.
I search and find https://github.com/ubuntu/microk8s/issues/824

**Comment by hokamc** [comment]
Thanks

**Comment by yuswitayudi** [comment]
Hello, someone solved whit this issue?

**Comment by hokamc** [comment]
```
#!/bin/sh

SRCTMPFILE=$(mktemp /tmp/tmp_ingress_controller.src.XXXXXXXXXXX.yaml)
NEWTMPFILE=$(mktemp /tmp/tmp_ingress_controller.new.XXXXXXXXXXX.yaml)

kubectl get -ningress daemonset.apps/nginx-ingress-microk8s-controller -o yaml > $SRCTMPFILE
sed -e "s/\(\- \-\-publish-status-address=\).*/\1$(curl ifconfig.io 2>/dev/null)/g" $SRCTMPFILE > $NEWTMPFILE

if [ ! "" = "$(diff -q $NEWTMPFILE $SRCTMPFILE)" ]; then
	echo Updating publish status address
	diff $SRCTMPFILE $NEWTMPFILE
	kubectl apply -f $NEWTMPFILE
fi

rm $SRCTMPFILE
rm $NEWTMPFILE
```
https://github.com/ubuntu/microk8s/issues/824#issuecomment-751554455

**Comment by cardoe** [comment]
More appropriately for MetalLB would be to do https://github.com/ubuntu/microk8s/issues/824#issuecomment-1003284063
