### ISSUE TITLE
KUBERNETES_SERVICE_PORT set to 443, when it's 16443

### ISSUE THREAD

**Issue by djmcgreal-cc** [ubuntu/microk8s#1971]
Hi,

Trying to run `helm` from within a pod fails with:
> Error: Kubernetes cluster unreachable: Get https://10.152.183.1:443/version?timeout=32s: dial tcp 10.152.183.1:443: connect: connection refused

It gets these values from the automatically provisioned variables _KUBERNETES_SERVICE_HOST_ and _KUBERNETES_SERVICE_PORT_. The HOST seems correct, but the port seems wrong according to https://microk8s.io/docs/ports and anecdotally:
```
p2074@microk8s:~$ kubectl run -it --image alpine -- sh
If you don't see a command prompt, try pressing enter.
/ # echo $KUBERNETES_SERVICE_PORT
443
/ # echo $KUBERNETES_SERVICE_HOST
10.152.183.1
/ # nc -v 10.152.183.1 443
/ # nc -v 10.152.183.1 16443
10.152.183.1 (10.152.183.1:16443) open
```

[inspection-report-20210204_193839.tar.gz](https://github.com/ubuntu/microk8s/files/5928100/inspection-report-20210204_193839.tar.gz)

**Comment by djmcgreal-cc** [comment]
Hi, this seems fairly easy to verify. Am I alone in this experience? Can I do anything further to help?
Thanks, Dan.

**Comment by ktsakalozos** [comment]
Hi @djmcgreal-cc, if you `microk8s kubectl get svc -A` you should see a kubernetes service on port 443. So I think the port is right. If you cannot access this service from a pod it means that the pod on the 10.1.0.0/16 network cannot reach the 10.152.183.0/24 network. However, looking at the list of pods you have I see coredns is working and coredns does talk to the kubernetes service. So I suspect there might be something off with the pod itself. Could you try another pod preferably not one based on alpine? We have seen some routing problems with those images.

**Comment by djmcgreal-cc** [comment]
I do indeed have such a service. I can't explain it, but the exact process I demonstrated above is now working as expected.
I'll get back in touch if I find out why.
Thanks! Dan.
