### ISSUE TITLE
[1.20] Unable to enable Linkerd

### ISSUE THREAD

**Issue by balchua** [ubuntu/microk8s#1979]
Unable to enable linkerd on 1.19 and 1.20.

This is because linkerd 2.9.0 binaries does not exist in the releases page. Updating the version to 2.9.2, which contains some critical fixes.

**Comment by balchua** [comment]
Code merge closing

**Comment by wmorgan** [comment]
Sorry about that. We removed those binaries because there was a problem with that release.
