### ISSUE TITLE
Change default port used instead of 8080

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#198]
Where are the configurations stored after `snap install microk8s --classic`? I don't find it in /etc or my home folder. I would like to run the cluster on different port so as not to clash with various native applications using 8080. Thanks.

**Comment by ktsakalozos** [comment]
Hi @khteh ,

Have a look at this comment: https://github.com/ubuntu/microk8s/issues/43#issuecomment-434383633

Changing the API server port in an easy way is something we are considering. Any feedback on what the user experience should be is much appreciated.

**Comment by jareks** [comment]
@ktsakalozos any news on changing the default port? 

8080 is commonly used by developers and there's no simple way in microk8s to change it. I understand it's a way more work to add configuration option so I am suggesting to only change the number for now (and that will hopefully remove issue for 90%+ of users?).

I believe 7895 would be a fine port number (`random.randint(7000, 8000) # =>7895`) ;)

Last but not least, thanks for your great work on mk8s!

**Comment by jareks** [comment]
8080 is commonly used by developers and there's no simple way in microk8s to change it. I understand it's a way more work to add configuration option so I am suggesting to only change the number for now (and that will hopefully remove issue for 90%+ of users?).

I believe 7895 would be a fine port number (random.randint(7000, 8000) # =>7895) ;)

Last but not least, thanks for your great work on mk8s!

**Comment by ktsakalozos** [comment]
Hi @jareks,

We recently completely removed the insecure 8080. All communication now goes through the secure port 16443. Please review all open ports at [1]

If you need the insecure port 8080 back (or configure it) you need to edit `/var/snap/microk8s/current/args/kube-apiserver` and restart MicroK8s (`microk8s.stop; microk8s.start`)

[1] https://github.com/ktsakalozos/microk8s.io/blob/docs/ports-rework/docs/ports.md

**Comment by jareks** [comment]
@ktsakalozos thanks for that excellent news :-)
I have quickly updated my snap to v1.16.0  (2019-09-21) but I still see kube-apiserver ( /snap/microk8s/918/kube-apiserver ) listening on 127.0.0.1:8080.

Are you referring to unreleased changes? Or maybe I am missing something?

**Comment by ktsakalozos** [comment]
Could you try the edge channel?
```
sudo snap install microk8s --classic --edge
```

Should hit stable very soon.

**Comment by jareks** [comment]
I have refreshed snap to edge: (v1.16.0 - 920)
```
(ins)~$ snap info microk8s | grep 1.16
  candidate:      v1.16.0  2019-09-21 (918) 187MB classic
  beta:           v1.16.0  2019-09-21 (918) 187MB classic
  edge:           v1.16.0  2019-09-24 (920) 187MB classic
installed:        v1.16.0             (920) 187MB classic
```

But both 8000/8080 are taken:
```
(ins)~$ sudo netstat -tlnp | grep 80.0
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      2601/python3        
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      9494/kube-apiserver 
```

**Comment by ktsakalozos** [comment]
When you refresh we try to apply the service configuration you already have to the new installation. In this way we try to preserve any "special" tuning you may have done to your cluster(*). Since you are refreshing from an installation where 8080 was open that port remains open. You have to do a new installation so that the new defaults are used.

(*) Of course this comes with the risk that the old configuration may not work with the new version of MicroK8s.

**Comment by jareks** [comment]
That makes perfect sense. Indeed, with clean install everything works as intended. 
Thanks for your help and patience!
