### ISSUE TITLE
Container allow_ip_forwarding with Calico

### ISSUE THREAD

**Issue by brettmilford** [ubuntu/microk8s#1989]
Hello,
I'm trying to set:
```
"container_settings": {
    "allow_ip_forwarding": true
},
```
In the calico cni config for the purpose of being able to deploy kubevirt VMs on a newly deploy microk8s (1.20/stable).
I've tried setting this in
/var/snap/microk8s/current/args/cni-network/cni.yaml
and
/var/snap/microk8s/current/args/cni-network/10-calico.conflist
and restarting the services with microk8s stop/start.

On restart a number of the already deployed pods appear to fail for a time, eventually microk8s status returns 'running' however the above stanza is removed from 10-calico.conflist.

Additionally deploying kubevirt VMs still fails in the same manner leading me to ask has this setting worked?; is possible/compatible on microk8s?

Thanks for the assistance!

**Comment by balchua** [comment]
@brettmilford oh i think i may have an idea what is happening.  The file `/var/snap/microk8s/current/args/cni-network/cni.yaml` you are referring to is only used when installing calico.
Updating that file alone probably will not have any effect unless you apply the changes like `kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml`.
The file `10-calico.conflist` is automatically generated by calico.
I haven't done this before though.  Perhaps you want to give it a try.

**Comment by brettmilford** [comment]
Hi @balchua

So I've had a chance to test this and I believe it solves my issue.
To test that I could launch a pod with `net.ipv4.ip_forward` sysctl set I needed to add:
```
--allowed-unsafe-sysctls "net.ipv4.ip_forward"
```
to `/var/snap/microk8s/current/args/kubelet`

Then adding
```
"container_settings": {
    "allow_ip_forwarding": true
},
```
to `/var/snap/microk8s/current/args/cni-network/cni.yaml` and running
```
kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml
```
appears to set and persist the allow_ip_forwarding value.

In my use case (deploying kubevirt) I can see that containers launched by the operator have `net.ipv4.ip_forward` set to `1` which I believe indicates success in this instance, however I'm still unable to launch VMs so I think further investigation else where is required.

Thanks for you help!
