### ISSUE TITLE
microk8s.{start,stop} don't exist anymore but are referenced in the docs

### ISSUE THREAD

**Issue by trusch** [ubuntu/microk8s#199]
The current version of the README and the rest of the repo are not syncronized. The readme states to use microk8s.start and microk8s.stop to start/stop the cluster, but the actions are not defined anymore.

Please either readd the actions or clarify how to restart the cluster in the readme, thanks!

**Comment by ktsakalozos** [comment]
Hi @trusch ,

The start/stop commands (as well as `microk8s.status`) are recent additions. They exist on the edge channel (`sudo snap install microk8s --classic --edge`) and they will be released to the stable channel soon. So this is an issue of the source code on github being a bit ahead of what is released, and that's expected.

For now to stop/start the microk8s you can do:
```
sudo snap disable microk8s
sudo snap enable microk8s
```

Thank you for using microk8s.

**Comment by trusch** [comment]
@ktsakalozos Thank you for your explanation!
