### ISSUE TITLE
microk8s.helm3 not able to follow "helm.sh/hook-weight"

### ISSUE THREAD

**Issue by Pradumn-18** [ubuntu/microk8s#1990]

**Comment by balchua** [comment]
@Pradumn-18 i am not too familiar with helm, is the `hook-weight` already available on helm v3.0.2?  Since the helm3 addon is kindda old though.

But if you are keen to try the `latest/stable` or `latest/edge` just to see if it works, helm3 addon was upgraded to 3.5.0.

**Comment by balchua** [comment]
I am closing this issue for now.
