### ISSUE TITLE
Node Not Ready

### ISSUE THREAD

**Issue by falgifaisal** [ubuntu/microk8s#2001]
Hi, the status of my node become to NotReady  from Ready and when i describe node, i got this

 Ready            False   Thu, 11 Feb 2021 11:46:24 +0700   Wed, 10 Feb 2021 13:57:00 +0700   KubeletNotReady              [container runtime status check may not have completed yet, runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized, missing node capacity for resources: ephemeral-storage]

Is there any suggestion ?

**Comment by balchua** [comment]
Hi @falgifaisal are you running on multi nodes or single node?
Can you check if you have enough storage space?

**Comment by falgifaisal** [comment]
> Hi @falgifaisal are you running on multi nodes or single node?
> Can you check if you have enough storage space?

Hi @balchua 

I run on single node.
When i check the storage space, it still 78% so i think there is no problem with the storage

Filesystem      Size  Used Avail Use% Mounted on
udev             28G     0   28G   0% /dev
tmpfs           5.6G  6.0M  5.5G   1% /run
/dev/sda2       549G  406G  116G  78% /
tmpfs            28G     0   28G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            28G     0   28G   0% /sys/fs/cgroup
/dev/loop2       98M   98M     0 100% /snap/core/10583
/dev/loop4      126M  126M     0 100% /snap/docker/471
tmpfs           5.6G     0  5.6G   0% /run/user/114
overlay         549G  406G  116G  78% /var/lib/docker/overlay2/f4e0039cefccf631fc4f4b1acffcdaadd6f22a81746bff56cc9212672d4bd9c7/merged
shm              64M     0   64M   0% /var/lib/docker/containers/6ff24fcc8676caf389c630a44e495188b17ab30c14534ec652865b0dd2e90ce8/mounts/shm
overlay         549G  406G  116G  78% /var/lib/docker/overlay2/3cfee92488c6b92f3e9af5d0591f8dc93e36bfbc5c32f10bce44f376ad0a034f/merged
shm              64M  472K   64M   1% /var/lib/docker/containers/5a1f73f64047042a9660fa14448d90bfcaed6b14b7719f6ea771fb20ae9fed27/mounts/shm
overlay         549G  406G  116G  78% /var/lib/docker/overlay2/bf76dfb361fac4a563b86313c616ac04c30d4df07125bae52ce5a3870d00b4f9/merged
shm              64M     0   64M   0% /var/lib/docker/containers/48518a823b71c7188f76345ab5abbfe9b90996453738b479704d18f563353339/mounts/shm
overlay         549G  406G  116G  78% /var/lib/docker/overlay2/be6a2529718a57eb920e2d4322ce5356e87214435a23fa37c31105e1702fa96f/merged
shm              64M     0   64M   0% /var/lib/docker/containers/471fa9afabaaf67f81c44efbe0b36daa86938fd6d68f19e9d107d7958c8796fc/mounts/shm
overlay         549G  406G  116G  78% /var/lib/docker/overlay2/c6ae1d52639d9372b2e2538194d28f8c6e976c94a75f95ed8256757b66b1584e/merged
tmpfs           5.6G     0  5.6G   0% /run/user/1000
/dev/loop3       99M   99M     0 100% /snap/core/10823
/dev/loop0      208M  208M     0 100% /snap/microk8s/1910

Is there any suggestion for this case ?

Thank you

**Comment by falgifaisal** [comment]
Hi @balchua ,

Thanks for the response

I have checked the storage and there is enough space since the disk is spend 78%

![image](https://user-images.githubusercontent.com/11311949/107617694-f3fe2700-6c82-11eb-9e66-5d407b5d2f02.png)

So i think, there is no problem with the space.

Thank you

**Comment by falgifaisal** [comment]
Hi @balchua ,

Thanks for the response.
I have checked the space and there is a lot of space since the disk just spend 78%

![image](https://user-images.githubusercontent.com/11311949/107618137-a635ee80-6c83-11eb-8330-d8706e88c8e4.png)

So i think there is no problem with the space

**Comment by balchua** [comment]
Is this a new installation?

**Comment by falgifaisal** [comment]
> Is this a new installation?

Yes, this is a new installation

**Comment by balchua** [comment]
Is it possible to run `microk8s inspect` and upload the tarball?

**Comment by falgifaisal** [comment]
Hi @balchua 

Here is the tarball

[inspection-report-20210211_170913.tar.gz](https://github.com/ubuntu/microk8s/files/5964449/inspection-report-20210211_170913.tar.gz)

Thank you

**Comment by falgifaisal** [comment]
Hi @balchua 

Here is the tarball

[inspection-report-20210211_170913.tar.gz](https://github.com/ubuntu/microk8s/files/5964449/inspection-report-20210211_170913.tar.gz)

Thank you

**Comment by balchua** [comment]
So strange, it seems like snapd isn't running.
When trying to restart the services, i see these errors in the logs of the apiservice-kicker.
```
Feb 11 06:09:30 master-demo microk8s.daemon-apiserver-kicker[710]: error: cannot communicate with server: Post http://localhost/v2/snapctl: dial unix /run/snapd-snap.socket: connect: connection refused
```

Can check the output?
`journalctl -xu snapd.service`

**Comment by balchua** [comment]
You can also try restarting snapd `systemctl restart snapd.service` lets see.

**Comment by falgifaisal** [comment]
> So strange, it seems like snapd isn't running.
> When trying to restart the services, i see these errors in the logs of the apiservice-kicker.
> 
> ```
> Feb 11 06:09:30 master-demo microk8s.daemon-apiserver-kicker[710]: error: cannot communicate with server: Post http://localhost/v2/snapctl: dial unix /run/snapd-snap.socket: connect: connection refused
> ```
> 
> Can check the output?
> `journalctl -xu snapd.service`

This is output of the command

![image](https://user-images.githubusercontent.com/11311949/107627073-52320680-6c91-11eb-85af-a141d7389d5e.png)

![image](https://user-images.githubusercontent.com/11311949/107627142-6a098a80-6c91-11eb-8b3f-89c7bb1c5f99.png)

**Comment by balchua** [comment]
Ok the error i see is because snapd was down.  Can you do a microk8s stop then start?

**Comment by falgifaisal** [comment]
> You can also try restarting snapd `systemctl restart snapd.service` lets see.

I want to try this command but since this is the production server, i feel worry it will create an issue in my server
Meanwhile, when i run the command "snap logs microk8s", i found this log

![image](https://user-images.githubusercontent.com/11311949/107627412-d6848980-6c91-11eb-87ac-5730b446d4fc.png)

So i checked the directory and just found cni.yaml and cni.yaml.backup

![image](https://user-images.githubusercontent.com/11311949/107627490-f3b95800-6c91-11eb-817a-44189f33ed5c.png)

So i also check another server and found more for the files

![image](https://user-images.githubusercontent.com/11311949/107629204-57448500-6c94-11eb-9085-1fd7686713c5.png)


Does it related to the error message in my server ?

**Comment by falgifaisal** [comment]
> Ok the error i see is because snapd was down. Can you do a microk8s stop then start?

Yes, and i also reinstall microk8s but still face the issue

**Comment by falgifaisal** [comment]
> Ok the error i see is because snapd was down. Can you do a microk8s stop then start?

I've already run this command also reinstall microk8s but still face the issue

**Comment by balchua** [comment]
When u reinstalled it, can you do `snap remove microk8s --purge` then install.

**Comment by falgifaisal** [comment]
> When u reinstalled it, can you do `snap remove microk8s --purge` then install.

Well, i just use "snap remove microk8s" without --purge.

Soon, i will try this command since i just found out about this command, 

Thank you for the answer, i will update the answer

**Comment by balchua** [comment]
@falgifaisal just checking in to see if you have finally resolved your issue. Thanks

**Comment by falgifaisal** [comment]
> @falgifaisal just checking in to see if you have finally resolved your issue. Thanks

Hi, sorry for late response
I don't know why but the microk8s already fix without i run the command.
But thanks for your suggest, i run the command in another server and the process uninstall run fastly.
Thank you

**Comment by balchua** [comment]
@falgifaisal thanks for getting back at this.  I will close the issue. Feel free to file one when needed.
Thanks again!
