### ISSUE TITLE
Disabling ha-cluster addon deletes all data

### ISSUE THREAD

**Issue by knittl** [ubuntu/microk8s#2009]
Starting point: a default, single-node microk8s installation (`snap install microk8s --classic --channel=1.19`) with several deployments installed through GitLab integration, including database pods with persistent volumes (`storage` addon).

Running `microk8s disable ha-cluster` deletes all deployments, all services, all pods, and all persistent volumes _without any warning_. Everything is gone and I am left with an empty node/cluster. This was completely unexpected and you can imagine my horror. Re-enabling the addon `microk8s enable ha-cluster` does **not** bring back the data and services, the cluster remains empty :cry: 

There should be a safety question presented to the users to confirm that they are about to destroy their data on the single-node cluster irreversibly. Disabling high-availibility does not imply deleting data, this should be communicated to the users _before_ executing the action. I assume the same happens when disabling the `storage` addon, but there it is at least somewhat obvious that this could cause data-loss.

**Comment by ktsakalozos** [comment]
Hi @knittl, you are right. In the case of a single node cluster when there are deployments on the cluster (other than the CNI) we should display a warning and require a `--force` flag. The rational of cleaning the cluster when you disable-ha is that in a multi-node setup when you disable HA you essentially ask the node to leave the cluster and therefore you do not want the you do not want the workloads to be replicated.  So, on line [1] we need an extra condition to check we are on a single node servind workloads and we do not have a force flag.

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/disable.ha-cluster.sh#L11

**Comment by tripolkaandrey** [comment]
I am interested in this issue. I have followed @ktsakalozos advice and added a check for force flag(--force and -f) and being on a single node serving workloads. I am struggling with subscribing CLA, specifically with 'Please add the Canonical Project Manager or contact'. May someone explain to me who I need to mention there, please.
