### ISSUE TITLE
Update page title & description

### ISSUE THREAD

**Issue by Greggless** [ubuntu/microk8s#201]
Title: MicroK8s
Desc: Kubernetes for workstations and appliances.

![image](https://user-images.githubusercontent.com/23459065/48937390-d4458180-ef05-11e8-97f9-5865bb2ba825.png)

<hr>

`[edited]`

**Comment by ktsakalozos** [comment]
Hi @Greggless ,

That should be MicroK8s (with capital K), right?

You want me to update the README and docs, what else?

**Comment by Greggless** [comment]
Thanks @ktsakalozos. If you could update the README and docs with ~~microk8s~~ MicroK8s where applicable, that would be wonderful.

We're currently whipping the docs up into webpages in [this pull request.](https://github.com/canonical-websites/microk8s.io/pull/31)
