### ISSUE TITLE
CRD delete hangs forever if finalizers are hung

### ISSUE THREAD

**Issue by KlavsKlavsen** [ubuntu/microk8s#2010]
Running microk8s 1.20.1 - and seeing the EXACT same issue as https://github.com/kubernetes/kubernetes/issues/60538
when installing argo-cd - and then installing a "root" application..  trying to delete it hangs and then trying to remove the application CRD - which then hangs forever.

manually editing CRD and removing finalizers: made it get unstuck (exactly as specified workaround in kubernetes issue).

**Comment by KlavsKlavsen** [comment]
And when I then try to reinstall the CRD (helm install argo-cd) - the old hung "application" of this CRD - is back again.. so removing a CRD does NOT delete "instances of the CRD".. it really SHOULD :)

**Comment by KlavsKlavsen** [comment]
the CRD instance (an application) - also hung on deletion - until I removed finalizers from that as well.
It seems handling finalizers timing out properly is the central isue.

**Comment by ktsakalozos** [comment]
Indeed @KlavsKlavsen. I often find the order in which resources are deleted important.

**Comment by balchua** [comment]
I don't think there is something MicroK8s can do here.  I see this behavior too on other distro that I've used.  Im closing this unless we think there's more we can do.
