### ISSUE TITLE
Pods stuck in unknow state

### ISSUE THREAD

**Issue by jordic** [ubuntu/microk8s#2013]
I run an small cluster at my laptop, when for some reason I loose network connectivity, (I'm usually connected by wifi), some deployed pods stay at unkown state, If I try to remove them it fails. The only solution is to restart the laptop. 

```
admin-frontend-7ff9967974-j2vx2       1/1     Running       38         74d
api-7684fb8687-nqx8l                  0/1     Unknown       36         47d
apiadmin-646f6b85dc-kpzxk             0/1     Unknown       20         56d
checkout-84754d7575-5qp9l             1/1     Running       6          7d21h
django-97f86d479-c2lv2                0/1     Unknown       19         57d
elastic-master-0                      1/1     Running       11         33d
elastic-master-1                      1/1     Running       11         33d
elastic-master-2                      1/1     Running       12         33d
kibana-66c49dc47c-6q724               0/1     Unknown       70         224d
minio-844b796846-kg4t6                1/1     Running       84         221d
nfs-server-0                          1/1     Running       10         33d
postgresql-bf9967956-s7fv8            1/1     Running       9          33d
rabbitmq-0                            0/2     Unknown       154        223d
redis-869b7cc7c9-dsprf                0/1     Unknown       84         224d
redis-persistent-7985d6f49b-tjj2c     0/1     Unknown       81         224d
```
> Please run `microk8s inspect` and attach the generated tarball to this issue.

Can't attach it because it also hangs, after, copy disk usage. 

```
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
```

**Comment by ktsakalozos** [comment]
Hi @jordic. In MicroK8s we have a service that detects changes in the network and re-configures the cluster accordingly. When you get disconnected and reconnected again do you get the same IP from your wifi? I have seen cases where the node's network changes and the pods go into this unknown state for 4-5 minutes before K8s recreates them. How long do the pods stay in this unknown state? If you do not want MicroK8s to react to network changes you can edit `/var/snap/microk8s/current/args/kube-apiserver` and use either `--advertise-address` or `--bind-address` to specify the IP that node will have.

It would also be helpful next time this happens and you manage to recover the cluster to attach here a `microk8s.inspect` tarball so we see what happened. Thank you.

**Comment by jordic** [comment]
Around the ip, I don't know (I think it uses dhcp), 
Around the amount of time, infinit. My only solution is to restart the computer (then it works).
I tried to restart microk8s but had not worked, also tried to restart apiserver without luck. 

What can I do to recover the cluster (without restarting the computer)? If I manage this, I will send the tarball.

**Comment by jordic** [comment]
The problem seems lile is solved.
