### ISSUE TITLE
snap.microk8s.daemon-apiserver stop works on one node

### ISSUE THREAD

**Issue by golgotow** [ubuntu/microk8s#2026]
Hello,

Can you look at the attached inspect file if we can anyway fix this broken node ?
[inspection-report-20210217_195727.tar.gz](https://github.com/ubuntu/microk8s/files/5997973/inspection-report-20210217_195727.tar.gz)

 microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2036/inspection-report-20210217_195727.tar.gz

Best regards,

**Comment by balchua** [comment]
Hi @golgotow thanks for using MicroK8s.

Quick question, is this node part of a cluster?  Or is it a standalone node?

There are/were some fixes landed/landing on 1.19 and 1.20 like soon.

**Comment by golgotow** [comment]
Hello,

This is part of cluster on channel edge, as on other channels have much more problems like this .
This is for now 6 nodes cluster, and when operating normally those are 3 master and 3 standby due to microk8s status .

Any tip how to troubleshoot this issue ? As I did not found any message why api not starting , yet.

Best regards

**Comment by balchua** [comment]
I couldn't find any clue as to why the api server is failing to start.  
You can stop microk8s on this problematic node.

If you can remove this node like `microk8s remove-node <node name>` from a working node.

Then `snap remove microk8s --purge`, reinstall microk8s and then join it again to the cluster.

**Comment by balchua** [comment]
Or maybe try this one as commented.

https://github.com/ubuntu/microk8s/issues/1598#issuecomment-780592131

**Comment by golgotow** [comment]
Hi,

Thanks for tip.

I have to re-install whole cluster as after this one node crush, rest of cluster start to be really broken, not reacting to any scale deployment and others tools. This is our 5 crash like this in couple of months, probably this software is not yet mature

**Comment by balchua** [comment]
Previous versions have memory leak, which the recent fixes addressed.  Its in stable channel now.  Been test driving the fixes and it has been stable for me.

**Comment by golgotow** [comment]
Thank you for info, anyway we get a similar issue last week on the development cluster based on Kubernetes 1.20, 1 node drop from cluster, and rest of the functionalities was almost removed, pods did not recover... This looks very strange in microk8s, If any new ,,feature" appears in new deployment we will update it in issues.

**Comment by rockkoca** [comment]
> Previous versions have memory leak, which the recent fixes addressed. Its in stable channel now. Been test driving the fixes and it has been stable for me.

Hi,

Since which version has fixed this memory leak issue?

**Comment by balchua** [comment]
Both 1.19/stable and 1.20/stable was released on monday.
