### ISSUE TITLE
How do I use HTTP Proxy with Enable？

### ISSUE THREAD

**Issue by solirpa** [ubuntu/microk8s#2038]
I see the command to install helm3.
```
run_with_sudo "${SNAP}/usr/bin/curl" --cacert $CA_CERT -L $SOURCE_URI/helm-$HELM_VERSION-linux-$(arch).tar.gz -o "$SNAP_DATA/tmp/helm/helm.tar.gz"
```
but i try set environment https_proxy，But it didn't work.

**Comment by solirpa** [comment]
There is no proxy, I cannot complete the installation.

**Comment by solirpa** [comment]
There is no proxy, I cannot complete the installation.

**Comment by balchua** [comment]
Tried adding into `/etc/environment` file the proxies.

**Comment by solirpa** [comment]
@balchua thank，it work for me.
