### ISSUE TITLE
Error adding 3rd node, fresh install

### ISSUE THREAD

**Issue by jonshaffer** [ubuntu/microk8s#2065]
On a fresh install of a 3rd Raspberry Pi running Ubuntu 20.04.2 I got this error:

```bash
ubuntu@ubuntu:~$ microk8s join 192.168.1.33:25000/e3f8cf6fd52188d27fb2e134e4451b4f
Contacting cluster at 192.168.1.33
Waiting for this node to finish joining the cluster. ..  
Traceback (most recent call last):
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 967, in <module>
    join_dqlite(connection_parts)
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 900, in join_dqlite       
    update_dqlite(info["cluster_cert"], info["cluster_key"], info["voters"], hostname_override)
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 856, in update_dqlite     
    restart_all_services()
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 784, in restart_all_services
    stderr=subprocess.DEVNULL,
  File "/snap/microk8s/2049/usr/lib/python3.5/subprocess.py", line 581, in check_call    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/2049/microk8s-stop.wrapper']' returned non-zero exit status 1
```

I am unable to start microk8s successfully

Inspect report: [inspection-report-20210228_031910.tar.gz](https://github.com/ubuntu/microk8s/files/6056233/inspection-report-20210228_031910.tar.gz)

The master node does show that one under `datastore master nodes:` with my 2nd one.

**Comment by jonshaffer** [comment]
I've since ran the inspect, logged out of the machine, logged back and in `microk8s status` shows the cluster running correctly and in high-availability from the 3rd node. Not sure if it is helpful to figure out what happened during the cluster join or not so I grabbed another inspect (it's possible it was working during the first one and I was in some sort of race condition between checking status and the inspect command)

[inspection-report-20210228_032916.tar.gz](https://github.com/ubuntu/microk8s/files/6056235/inspection-report-20210228_032916.tar.gz)

**Comment by balchua** [comment]
Its strange, since i dont see other nodes from the inspect tarball.  It looks like it didn't join successfully.  
If you run `microk8s status` on node3, do you see all the nodes?

**Comment by jonshaffer** [comment]
Yeah, status on node3 does show all the nodes (node3 is 192.168.1.33):

```bash
ubuntu@ubuntu:~$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 192.168.1.33:19001 192.168.1.31:19001 192.168.1.32:19001   
  datastore standby nodes: none
addons:
  enabled:
    ha-cluster           # Configure high availability on the current node
  disabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics      
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory      
    traefik              # traefik Ingress controller for external access
```

**Comment by balchua** [comment]
What about `microk8s kubectl get no`?

**Comment by jonshaffer** [comment]
```bash
ubuntu@ubuntu:~$ microk8s kubectl get no
NAME     STATUS   ROLES    AGE   VERSION
ubuntu   Ready    <none>   19h   v1.20.2-34+c6851e88267786
```

kubectl shows 1 node on each of the machines. I also took these inspects from them (named):

[master-inspection-report-20210228_225700.tar.gz](https://github.com/ubuntu/microk8s/files/6058196/master-inspection-report-20210228_225700.tar.gz)
[node2-inspection-report-20210228_225710.tar.gz](https://github.com/ubuntu/microk8s/files/6058194/node2-inspection-report-20210228_225710.tar.gz)
[node3-inspection-report-20210228_225702.tar.gz](https://github.com/ubuntu/microk8s/files/6058195/node3-inspection-report-20210228_225702.tar.gz)

**Comment by balchua** [comment]
I think i know what's happening.  All you nodes hostname are `ubuntu`. Is it right?

Each node must have a unique name.  And each node's hostname must be resolvable from eacch node.

For example, you have these `hostname`s.
`node1`, `node2` and `node3`.

Add each of the node's hostname to `/etc/hosts` of each node prior to joining.

Can you try that?  I think that may have caused the issue during cluster formation.

**Comment by jonshaffer** [comment]
Making each node's hostname unique (ty!) allowed the install to get a little further and add a second node & see it in `microk8s kubectl get no`. After adding the 3rd node (k8snode2) they all dropped and won't `microk8s start` anymore. I did get the same error during the first join (of k8snode3):

```bash
ubuntu@k8snode3:~$ microk8s join 192.168.1.33:25000/0ae26ad82350bf4aba56a235dbe7c980
Contacting cluster at 192.168.1.33
Waiting for this node to finish joining the cluster. ..  
Traceback (most recent call last):
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 967, in <module>
    join_dqlite(connection_parts)
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 900, in join_dqlite       
    update_dqlite(info["cluster_cert"], info["cluster_key"], info["voters"], hostname_override)
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 856, in update_dqlite     
    restart_all_services()
  File "/snap/microk8s/2049/scripts/cluster/join.py", line 784, in restart_all_services
    stderr=subprocess.DEVNULL,
  File "/snap/microk8s/2049/usr/lib/python3.5/subprocess.py", line 581, in check_call    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/snap/microk8s/2049/microk8s-stop.wrapper']' returned non-zero exit status 1
```

[k8snode2-inspection-report-20210301_045040.tar.gz](https://github.com/ubuntu/microk8s/files/6059227/k8snode2-inspection-report-20210301_045040.tar.gz)
[k8snode3-inspection-report-20210301_045042.tar.gz](https://github.com/ubuntu/microk8s/files/6059228/k8snode3-inspection-report-20210301_045042.tar.gz)
[k8snode1-inspection-report-20210301_045325.tar.gz](https://github.com/ubuntu/microk8s/files/6059229/k8snode1-inspection-report-20210301_045325.tar.gz)

Although I did set up the `/etc/hosts` and the hostname on the machines my gateway is still displaying them all as hostname ubuntu, although I'm not sure that matters? I'm using auto DHCP name server on a Unifi UDM Pro.

**Comment by balchua** [comment]
Question, did you do redo the whole setup?  And you issued `snap remove microk8s --purge`?

**Comment by jonshaffer** [comment]
I did not use the `--purge` option, so I went ahead and reinstalled on used `sudo snap remove microk8s --purge` on 2 of the machines. There seemed to be an issue on one of the machines after a fresh install:

```bash
ubuntu@k8snode2:~$ sudo snap install microk8s --classic --channel=1.20/stable        
Run configure hook of "microk8s" snap if present                                    -microk8s (1.20/stable) v1.20.2 from Canonical✓ installed
ubuntu@k8snode2:~$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
ubuntu@k8snode2:~$ microk8s start
Started.
ubuntu@k8snode2:~$ microk8s status
^CTraceback (most recent call last):
  File "/snap/microk8s/2049/scripts/wrappers/status.py", line 231, in <module>       
    enabled, disabled = get_status(available_addons, isReady)
  File "/snap/microk8s/2049/scripts/wrappers/status.py", line 157, in get_status     
    kube_output = kubectl_get("all")
  File "/snap/microk8s/2049/scripts/wrappers/common/utils.py", line 166, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)     
  File "/snap/microk8s/2049/scripts/wrappers/common/utils.py", line 35, in run       
    args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env
  File "/snap/microk8s/2049/usr/lib/python3.5/subprocess.py", line 695, in run       
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/snap/microk8s/2049/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/snap/microk8s/2049/usr/lib/python3.5/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/snap/microk8s/2049/usr/lib/python3.5/selectors.py", line 376, in select     
    fd_event_list = self._poll.poll(timeout)
```

I'm going to flash the drives with a fresh install of ubuntu server, verify unique hostnames, and try again today at some point.

**Comment by balchua** [comment]
Let me know how it goes.  Usually fresh starting a MicroK8s node can take sometime.
I usually i do `microk8s status --wait-ready`.
The error you get above is because you cancelled the status command. `^C`

**Comment by jonshaffer** [comment]
Ok, I think I am up and running. I may have been adding new nodes too quickly before too, I waited until I could verify each new node was up before running `microk8s add-node` and adding running that on the next machine.

I think this topic can be closed unless there may be docs to update somewhere?

**Comment by balchua** [comment]
Thanks @jonshaffer for the information provided. 
I will go ahead and close this.
Feel free to log an issue should you face one.
