### ISSUE TITLE
metrics-server pod can not start up,with microk8s version 1.16 installed in ubuntu20.04LTS

### ISSUE THREAD

**Issue by gouhan** [ubuntu/microk8s#2068]
microk8s installed  in my single master node ubuntu 20.04 LTS , with the command: snap install microk8s --classic
i checked the default version is 1.16.
other pods all running normally,but the metrics-server with status "CrashLoopBackoff",the detail error shows:

> Warning  FailedMount     4m29s (x3 over 4m33s)   kubelet, node3  MountVolume.SetUp failed for volume "metrics-server-token-6xdhf" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount     4m29s (x3 over 4m33s)   kubelet, node3  MountVolume.SetUp failed for volume "metrics-server-config-volume" : failed to sync configmap cache: timed out waiting for the condition
  Normal   SandboxChanged  4m26s                   kubelet, node3  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          4m1s                    kubelet, node3  Container image "cdkbot/addon-resizer-amd64:1.8.1" already present on machine
  Normal   Created         3m54s                   kubelet, node3  Created container metrics-server-nanny
  Normal   Started         3m52s                   kubelet, node3  Started container metrics-server-nanny
  Normal   Pulled          3m10s (x3 over 4m12s)   kubelet, node3  Container image "k8s.gcr.io/metrics-server-amd64:v0.2.1" already present on machine
  Normal   Created         3m9s (x3 over 4m1s)     kubelet, node3  Created container metrics-server
  Normal   Started         3m9s (x3 over 4m1s)     kubelet, node3  Started container metrics-server
  Warning  BackOff         3m7s (x6 over 3m50s)    kubelet, node3  Back-off restarting failed container

i have some questions:
1、pod is created using yaml config file,so where is the metrics-server.yaml?
2、i have download the metrics-server-amd64:v0.3.6 image manully,then tagged,why it pulled the image everytime when it try to start up,"Container image "k8s.gcr.io/metrics-server-amd64:v0.2.1" already present on machine".

I'm new to use k8s, is there anybody can help me ,thanks very much.

**Comment by balchua** [comment]
@gouhan
Insing using `snap install microk8s --classic` is currently using 1.20 and not 1.16.

While the metrics server yaml is here.
https://github.com/ubuntu/microk8s/blob/1.20/microk8s-resources/actions/metrics-server.yaml

If you go to `/snap/microk8s/` directory thats where most of microk8s are located.  The  `/snap/microk8s` directory is a read only file system.

The default image pull policy is `IfNotPresent`. The message you see is just an indication that it didn't pull the image from the network, but will use the existing image present on the host.

I am closing the issue for now.  Feel free to open if you have an issue.
