### ISSUE TITLE
helm3 update needed

### ISSUE THREAD

**Issue by robertbovens** [ubuntu/microk8s#2070]
Ubuntu 18.04.5 LTS with all the updates

helm3 version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

The problem is that when i try to install a chart that needs helm3 version 3.1 it gives an error. For example, the latest kubeapps of bitnami needs helm3 3.1. There are more helm charts available that need a newer version of helm3 at this moment, and with all of those i get an error and the chart cant be installed. I already opend a ticket with bitnami for there kubeapps, and they say the helm version it needs is 3.1

How can i get an updated version of helm3, i use microk8s for my kubernetes but the helm3 version is outdated. The same version is also used on the latest ubuntu version.

The snap version of helm3 is more up to date then the version in microk8s but i dont know how to use that one with microk8s.

Robert

**Comment by balchua** [comment]
Helm3 updated version will be available on the next version of MicroK8s i.e. 1.21.  i think addons of previous versions are not updated unless there are bug or security fixes.

**Comment by robertbovens** [comment]
When is the next version due to come out ? Will we need to wait months ?

**Comment by balchua** [comment]
It usually comes out around the same time as kubernetes 1.21.  which is in april.  Its easy to use an external helm.
You can export the kubeconfig file like this `microk8s config > /where/you/want/to/keep/the/file`. Then do an `export KUBECONFIG=/where/you/want/to/keep/the/file`

After that you can do all the helm commands.

**Comment by robertbovens** [comment]
I tried your advise and it worked. the only thing now is, it seems i have now 2 helm3 repo databases.

**Comment by balchua** [comment]
The helm charts repo usually sits in your `$HOME` even if you use the addon.  I maybe wrong here though.

**Comment by balchua** [comment]
Will be closing this, since the issue is resolved.
Thanks!
