### ISSUE TITLE
edge version gives error: Failed to start microk8s services

### ISSUE THREAD

**Issue by robertbovens** [ubuntu/microk8s#2071]
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
[inspection-report-20210303_194517.tar.gz](https://github.com/ubuntu/microk8s/files/6078742/inspection-report-20210303_194517.tar.gz)

Installed a fresh latest/edge version, enablel helm3, rbac, dns, metrics-server and storage. After enabling storage microk8s can not start and says it has problem enabling containerd.

I installed it because i want a newer version of helm3 and this version gives helm3 version 3.5, but it seems it still has problems

After i run the inspect command, dns, rbac and metrics-server wasnt installed but i was able to start microk8s. Now i enabled it again and now it runs without errors

**Comment by robertbovens** [comment]
After reboot i get the following message:

root@test:/home/robert# microk8s.status
microk8s is not running. Use microk8s inspect for a deeper inspection.
root@test:/home/robert# microk8s.start
error: cannot perform the following tasks:
- Run service command "start" for services ["daemon-apiserver" "daemon-apiserver-kicker" "daemon-cluster-agent" "daemon-containerd" "daemon-control-plane-kicker" "daemon-controller-manager" "daemon-etcd" "daemon-flanneld" "daemon-kubelet" "daemon-kubelite" "daemon-proxy" "daemon-scheduler"] of snap "microk8s" ([start snap.microk8s.daemon-containerd.service] failed with exit status 1: Job for snap.microk8s.daemon-containerd.service failed because a timeout was exceeded.
See "systemctl status snap.microk8s.daemon-containerd.service" and "journalctl -xe" for details.
)
Failed to start microk8s services. Check snapd logs with "journalctl -u snapd.service"

Running microk8s.stop and then start gives the same error.

**Comment by robertbovens** [comment]
root@test:/home/robert# systemctl status snap.microk8s.daemon-containerd.service
● snap.microk8s.daemon-containerd.service - Service for snap application microk8s.daemon-containerd
     Loaded: loaded (/etc/systemd/system/snap.microk8s.daemon-containerd.service; disabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Wed 2021-03-03 20:08:46 UTC; 1min 23s ago
   Main PID: 7643 (code=killed, signal=KILL)

Mar 03 20:08:14 test microk8s.daemon-containerd[7643]: time="2021-03-03T20:08:14.405738936Z" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
Mar 03 20:08:14 test microk8s.daemon-containerd[7643]: time="2021-03-03T20:08:14.405768830Z" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
Mar 03 20:08:14 test microk8s.daemon-containerd[7643]: time="2021-03-03T20:08:14.405920050Z" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
Mar 03 20:08:14 test microk8s.daemon-containerd[7643]: time="2021-03-03T20:08:14.406007619Z" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
Mar 03 20:08:14 test microk8s.daemon-containerd[7643]: time="2021-03-03T20:08:14.406264983Z" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
Mar 03 20:08:46 test systemd[1]: snap.microk8s.daemon-containerd.service: State 'stop-sigterm' timed out. Killing.
Mar 03 20:08:46 test systemd[1]: snap.microk8s.daemon-containerd.service: Killing process 7643 (containerd) with signal SIGKILL.
Mar 03 20:08:46 test systemd[1]: snap.microk8s.daemon-containerd.service: Main process exited, code=killed, status=9/KILL
Mar 03 20:08:46 test systemd[1]: snap.microk8s.daemon-containerd.service: Failed with result 'timeout'.
Mar 03 20:08:46 test systemd[1]: Stopped Service for snap application microk8s.daemon-containerd.

**Comment by balchua** [comment]
Can you do `microk8s start`?

**Comment by ktsakalozos** [comment]
Thank you for reporting this @robertbovens. I also see that after a reboot containerd is flapping:
```
Mar 04 12:41:59 vm2004 microk8s.daemon-containerd[7827]: time="2021-03-04T12:41:59.885526835+02:00" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
Mar 04 12:41:59 vm2004 microk8s.daemon-containerd[7827]: time="2021-03-04T12:41:59.885672391+02:00" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
^[[5~Mar 04 12:43:29 vm2004 systemd[1]: snap.microk8s.daemon-containerd.service: start operation timed out. Terminating.
Mar 04 12:43:39 vm2004 microk8s.daemon-containerd[7827]: time="2021-03-04T12:43:39.886370239+02:00" level=warning msg="cleaning up after shim disconnected" id=59bc72f0396df2f723823e5d4924a01edc16b49c443e8361ad86a06794e43ad4 namespace=k8s.io
Mar 04 12:43:39 vm2004 microk8s.daemon-containerd[7827]: time="2021-03-04T12:43:39.886435469+02:00" level=info msg="cleaning up dead shim"
Mar 04 12:43:39 vm2004 microk8s.daemon-containerd[7827]: time="2021-03-04T12:43:39.906600846+02:00" level=warning msg="cleanup warnings time=\"2021-03-04T12:43:39+02:00\" level=info msg=\"starting signal loop\" namespace=k8s.io pid=9562\n"
Mar 04 12:44:00 vm2004 systemd[1]: snap.microk8s.daemon-containerd.service: State 'stop-sigterm' timed out. Killing.
Mar 04 12:44:00 vm2004 systemd[1]: snap.microk8s.daemon-containerd.service: Killing process 7827 (containerd) with signal SIGKILL.
Mar 04 12:44:00 vm2004 systemd[1]: snap.microk8s.daemon-containerd.service: Main process exited, code=killed, status=9/KILL
Mar 04 12:44:00 vm2004 systemd[1]: snap.microk8s.daemon-containerd.service: Failed with result 'timeout'.
Mar 04 12:44:00 vm2004 systemd[1]: Failed to start Service for snap application microk8s.daemon-containerd.
Mar 04 12:44:00 vm2004 systemd[1]: snap.microk8s.daemon-containerd.service: Scheduled restart job, restart counter is at 4.
Mar 04 12:44:00 vm2004 systemd[1]: Stopped Service for snap application microk8s.daemon-containerd.
Mar 04 12:44:00 vm2004 systemd[1]: Starting Service for snap application microk8s.daemon-containerd...
Mar 04 12:44:00 vm2004 microk8s.daemon-containerd[9933]: + '[' -d /sys/kernel/security/apparmor ']'
Mar 04 12:44:00 vm2004 microk8s.daemon-containerd[9954]: ++ cat /proc/self/attr/current
Mar 04 12:44:00 vm2004 microk8s.daemon-containerd[9933]: + '[' 'snap.microk8s.daemon-containerd (complain)' '!=' unconfined ']'
```

@joedborg could this be related to our change in the way the containerd systemd service is setup now?

**Comment by tbertenshaw** [comment]
also spotting this. Can see the Snap edge channel upgraded me to 2067 (from 2066) and this simultaneously is the result.

**Comment by tbertenshaw** [comment]
Since my snap updated overnight to v1.20.4 **(2068)** this looks to be working now.

**Comment by balchua** [comment]
I am getting this too on `master` branch.  After stopping MicroK8s gracefully (with several pods), shutting down the system and booting it backup.

Containerd failed to start with this error.

```
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316469310+08:00" level=info msg="loading plugin \"io.containerd.service.v1.containers-service\"..." type=io.containerd.service.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316491269+08:00" level=info msg="loading plugin \"io.containerd.service.v1.content-service\"..." type=io.containerd.service.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316509704+08:00" level=info msg="loading plugin \"io.containerd.service.v1.diff-service\"..." type=io.containerd.service.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316538975+08:00" level=info msg="loading plugin \"io.containerd.service.v1.images-service\"..." type=io.containerd.service.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316565952+08:00" level=info msg="loading plugin \"io.containerd.service.v1.leases-service\"..." type=io.containerd.service.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316586653+08:00" level=info msg="loading plugin \"io.containerd.service.v1.namespaces-service\"..." type=io.containerd.service.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316607044+08:00" level=info msg="loading plugin \"io.containerd.service.v1.snapshots-service\"..." type=io.containerd.service.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316625931+08:00" level=info msg="loading plugin \"io.containerd.runtime.v1.linux\"..." type=io.containerd.runtime.v1
Mar 07 09:12:26 norse microk8s.daemon-containerd[10295]: time="2021-03-07T09:12:26.316694925+08:00" level=info msg="loading plugin \"io.containerd.runtime.v2.task\"..." type=io.containerd.runtime.v2
Mar 07 09:12:58 norse systemd[1]: snap.microk8s.daemon-containerd.service: State 'stop-sigterm' timed out. Killing.
Mar 07 09:12:58 norse systemd[1]: snap.microk8s.daemon-containerd.service: Killing process 10295 (containerd) with signal SIGKILL.
Mar 07 09:12:58 norse systemd[1]: snap.microk8s.daemon-containerd.service: Main process exited, code=killed, status=9/KILL
Mar 07 09:12:58 norse systemd[1]: snap.microk8s.daemon-containerd.service: Failed with result 'timeout'.
Mar 07 09:12:58 norse systemd[1]: Stopped Service for snap application microk8s.daemon-containerd.
```

**Comment by balchua** [comment]
I added the following to the `snapcraft.yaml`.
Default timeout is around 90s, if i recall.  Changing it to 2 mins seems to prevent me from seeing this one.
This happens on cold boot.

```
  daemon-containerd:
    command: run-containerd-with-args
    daemon: notify
    stop-mode: sigterm
    start-timeout: "2m"
    restart-condition: always
    plugs: [kubernetes-support]
```

**Comment by joedborg** [comment]
Ah nice find @balchua, thank you.  I wonder if containerd only sends the "Ready" notification to systemd once the containers are back up too, or once it's reconciled all the shims it had previously dropped.  Either way, let me test that across some different use cases to see if 2m is enough.

**Comment by balchua** [comment]
I wonder if the startup of the services is included in the snap timeout of 5mins?

**Comment by joedborg** [comment]
> I wonder if the startup of the services is included in the snap timeout of 5mins?

It seems to be, yeah.  Looking at https://github.com/containerd/containerd/blob/88d97362b31fef45c410fd76b3aacba186e277e9/cmd/containerd/command/main.go#L231, it seems to be the last thing it does.  However, cold reboots seem to cause this where `systemctl restart` doesn't, so perhaps there's something not happening when the systemd kills it during host shutdown.

I've logged a big to see if we can shed any more light on it https://github.com/containerd/containerd/issues/5142

**Comment by balchua** [comment]
Oh you mean using `systemctl restart` doesn't cause this long boot?

**Comment by joedborg** [comment]
> Oh you mean using `systemctl restart` doesn't cause this long boot?

Yeah, doesn't seem to.  Only when you cold boot the host itself,so I wonder if something is happening at stop time during systemctl restart vs host reboot.

**Comment by balchua** [comment]
What i do for now is to manually issue `systemctl restart snap.microk8s.daemon-containerd` it will take sometime depending on the number of pods it has.  Check the journal logs, it will eventually come up.

**Comment by balchua** [comment]
I found an even better way to start it.  Just clean up the `/var/snap/microk8s/common/run/containerd/*`.
When you stop microk8s, you cannot delete the directories, but you can `mv` them to some other place.
Here are the steps:
* `microk8s stop`
* Move the directories somewhere like this `sudo mv /var/snap/microk8s/common/run/containerd/* /tmp`
* Reboot the node
* `microk8s start`

**Comment by balchua** [comment]
@ktsakalozos , @joedborg after installing `1.21/edge` version, `Kubelet` will panic because `containerd` is still cleaning up "dead" shims after a cold start.  
When `Kubelet` panics, `kubelite` will go into crash loop, leading up to increased load on the laptop.

Currently i only have these pods running in my laptop, it takes 41 restarts of kubelite.

```shell
NAMESPACE       NAME                                      READY   STATUS    RESTARTS   AGE
kube-system     coredns-7f9c69c78c-c89kf                  1/1     Running   1          57m
observability   jaeger-operator-85fb5c9745-lk7pn          1/1     Running   1          56m
kube-system     calico-node-fljkn                         1/1     Running   1          58m
kube-system     calico-kube-controllers-f7868dd95-cf9pf   1/1     Running   1          58m
ingress         nginx-ingress-microk8s-controller-pfb2s   1/1     Running   1          56m
observability   simplest-54b7455bf9-djg85                 1/1     Running   1          55m
```
Should we put some guard like checking for the availability of `containerd.sock` before going ahead with starting `kubelite`?

**Comment by ktsakalozos** [comment]
Re-open because we probably need to backport the fix on the rest of the tracks

**Comment by balchua** [comment]
But this happens only on container 1.4+.  1.3 and below doesn't seem to have such behavior.

**Comment by ktsakalozos** [comment]
You are right pre 1.21 tracks are not affected by this issue.

**Comment by mcfly722** [comment]
how to download file from lxc container?
