### ISSUE TITLE
Microk8s fails to start after rebooting the host.

### ISSUE THREAD

**Issue by hpannetier** [ubuntu/microk8s#2088]
I installed microk8s on Dell T440 server with Ubuntu 20.04.2 LTS.
# sudo snap install microk8s --classic --channel=1.19

Most of the time, when I restart the server , microk8s fails to be restarted properly.

# microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

A "microk8s.stop; microk8s.start" doesn't solve the problem. The only workaround I found is to uninstall/reinstall microk8s.
Please find attached the tar file produced by "microk8s inspect"

Thanks a lot for your help.
Best regards

**Comment by hpannetier** [comment]
I miss to attach  tarball of "microk8s inspect".
Here it is:
[inspection-report-20210310_133050.tar.gz](https://github.com/ubuntu/microk8s/files/6124265/inspection-report-20210310_133050.tar.gz)

**Comment by balchua** [comment]
Something changed with your system clock?
Coz i see this error.

```
Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2021-03-10T13:30:47+01:00 is before 2021-03-10T13:26:42Z
```

**Comment by ktsakalozos** [comment]
Maybe you want to check the expiration date of the CA cert with `sudo microk8s.refresh-certs -c`.

**Comment by hpannetier** [comment]
Thank you Balchua and ktsakalozos
I may have an issue with the NTP server just after the server reboot.
On the  next server reboot  I will check both timedatectl status and certificate validity.

**Comment by hpannetier** [comment]
I did a new reboot of my server and reproduced the issue:
	# microk8s status
	microk8s is not running. Use microk8s inspect for a deeper inspection

There is no issue with time synchronization. And all certificates are valid, see the attached file certs.tar. 
	# sudo microk8s.refresh-certs -c
	The CA certificate will expire in 3648 days.

	# microk8s.enable dns
	Enabling DNS
	Applying manifest
	Unable to connect to the server: x509: certificate has expired or is not yet valid: current time 2021-03-12T14:18:12+01:00 is before 2021-03-12T13:34:28Z
	Failed to enable dns
	#timedatectl
               Local time: ven. 2021-03-12 14:18:31 CET
           Universal time: ven. 2021-03-12 13:18:31 UTC
                 RTC time: ven. 2021-03-12 13:18:31
                Time zone: Europe/Paris (CET, +0100)
	System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

So, the issue is somewhere else.
I attached a new inspection-report tar file.
Thanks a lot for your help

**Comment by hpannetier** [comment]
[inspection-report-20210312_134953.tar.gz](https://github.com/ubuntu/microk8s/files/6130407/inspection-report-20210312_134953.tar.gz)
[certs.zip](https://github.com/ubuntu/microk8s/files/6130409/certs.zip)

**Comment by hpannetier** [comment]
Hello again,
Could you confirm my following analysis :

1 - The server has been rebooted at 13:34:28 CET time. (UTC+1, GMT+1)
	$ journalctl --list-boots
 	0 c3f0e50deea5409684f062653aff41d7 Fri 2021-03-12 13:34:28 CET—Fri 2021-03-12 16:27:58 CET

2 - k8s cluster-info logs reports :
	To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
	Unable to connect to the server: x509: certificate has expired or is not yet valid: 
	current time 2021-03-12T13:49:50+01:00 is before 2021-03-12T13:34:28Z

This means that the cluster uses UTC time 12:49:50 and compares it to certificate time 13:34:28


3 - What is wrong: Upon reboot , server.crt is regenerated. But the time is not correct. It appears to be GMT but actually is GMT+1 !
 
$:/var/snap/microk8s/current/certs$ openssl x509 -noout -text -in server.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            81:86:78:fd:1c:0b:75:4c
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = 10.152.183.1
        Validity
            Not Before: Mar 12 13:34:28 2021 GMT
            Not After : Mar 12 13:34:28 2022 GMT
        Subject: C = GB, ST = Canonical, L = Canonical, O = Canonical, OU = Canonical, CN = 127.0.0.1

Thank you

**Comment by balchua** [comment]
Is it possible that when MicroK8s was installed, the system time was in `GMT` all certs were generated using this. Then after the reboot the system time is finally changed to `GMT+1`?

**Comment by balchua** [comment]
Hi @hpannetier this is my setup.  The certificates validity generated are always in UTC.

```
hor@norse:/var/snap/microk8s/current/certs$ openssl x509 -noout -text -in server.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            21:d0:d3:d4:61:dc:99:bb:ef:22:a4:62:af:c9:d6:85:0e:98:67:ca
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = 10.152.183.1
        Validity
            Not Before: Mar 13 03:35:20 2021 GMT
            Not After : Mar 13 03:35:20 2022 GMT
        Subject: C = GB, ST = Canonical, L = Canonical, O = Canonical, OU = Canonical, CN = 127.0.0.1
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
```

My system time is this

```
thor@norse:/var/snap/microk8s/current/certs$ date
Sat 13 Mar 2021 11:54:09 AM +08
```
There must be some tweaking to do on your system time settings.  Since in your case, the UTC time isnt really UTC, it is still ahead by an hour when converted to UTC.(or GMT).

**Comment by hpannetier** [comment]
Hello @balchua 
Thanks for your help. 
I finally found that the issue came from the NTP configuration on the Esxi Vmware where NTP server was set but NTP client service was not started. 
It's now working fine. 
The tricky part of this issue is that I didn't imagine that the microk8s server certificate would be regenerated upon server reboot and even if the VM is properly synchronized at startup the date/time which appear in the new certificate is the date/time of the esxi rather that the date/time of the VM.
Thanks again for given me the right direction for this trouble-shooting.

**Comment by balchua** [comment]
Glad to hear that you have nailed this down @hpannetier .  Feel free to open an issue when you encounter some weirdness.
