### ISSUE TITLE
The situation when I accedentially remove all the nodes from cluster(not even a single node is left in microk8s cluster), there is no way to add them back. Completely stuck. Don't want to reinstall.

### ISSUE THREAD

**Issue by velcrine** [ubuntu/microk8s#2092]
Please run `microk8s inspect` and attach the generated tarball to this issue.
[inspection-report-20210314_000056.tar.gz](https://github.com/ubuntu/microk8s/files/6135322/inspection-report-20210314_000056.tar.gz)

After I saw that the only node attached in the cluster is not in ready state, I removed that node. Now there is no way I can add any node back. 
Tried microk8s add-node and then following the "join" command instructions multiple times but didn't worked. Tried start, stop, reset multiple times. Restarted the host machine multiple times. 

There seems to be no way, to add the node back, after removing all the nodes.

**Comment by velcrine** [comment]
```
▶ microk8s add-node
From the node you wish to join to this cluster, run the following:
microk8s join 192.168.43.203:25000/f1e3bae56a40c75701f8baf5806db4ae

If the node you are adding is not reachable through the default interface you can use one of the following:
 microk8s join 192.168.43.203:25000/f1e3bae56a40c75701f8baf5806db4ae
 microk8s join 172.16.1.1:25000/f1e3bae56a40c75701f8baf5806db4ae
 microk8s join 172.16.2.1:25000/f1e3bae56a40c75701f8baf5806db4ae
 microk8s join 172.17.0.1:25000/f1e3bae56a40c75701f8baf5806db4ae

microk8s join 192.168.43.203:25000/f1e3bae56a40c75701f8baf5806db4ae
Contacting cluster at 192.168.43.203
Error, could not locate kubelet token. Joining cluster failed.
```
Error, could not locate kubelet token. Joining cluster failed.

**Comment by eloy-salamanca** [comment]
Hi @velcrine; how did you solve this issue? I'm stuck at the same point now, I'm afraid.

**Comment by ktsakalozos** [comment]
@eloy-salamanca if you do not have nodes it probably means you also do not have workloads. In such cases it may be easier to `snap remove microk8s` and reinstall it.

**Comment by velcrine** [comment]
@eloy-salamanca i was not able to fix it. I only had to reinstall. @ktsakalozos there must be a way to force clean.
