### ISSUE TITLE
Very slow download via snap

### ISSUE THREAD

**Issue by virtyos** [ubuntu/microk8s#2106]
After crash of microk8s I removed it and now trying to download again.
I see this:

`Download snap "microk8s" (2060) from channel "1.19"                                                                                         6% 7.74kB/s 7h18m`

why is the download speed so slow? Can you do with it something?

**Comment by ktsakalozos** [comment]
Hi @virtyos, there were some issues with the snapstore. I believe these are resolved now. You can get more info on this incident by asking here https://forum.snapcraft.io/.

**Comment by balchua** [comment]
Hi @virtyos im closing this issue for now.  
Thanks for using MicroK8s.
