### ISSUE TITLE
kaniko on-cluster image build hangs on microk8s

### ISSUE THREAD

**Issue by markns** [ubuntu/microk8s#211]
I'm using kaniko for running on-cluster image builds. I've been trying to get this working on microk8s, but for some reason the kaniko executable hangs on this distribution.

The problem is easily reproduced with a fresh install of microk8s. With a brand new ubuntu 14.04 instance:
```
markns@microk8s-2:~$ sudo snap install microk8s --classic
microk8s v1.12.2 from Canonical✓ installed

markns@microk8s-2:~$ microk8s.docker run -it --entrypoint=sh gcr.io/kaniko-project/executor:debug-v0.6.0
Unable to find image 'gcr.io/kaniko-project/executor:debug-v0.6.0' locally
debug-v0.6.0: Pulling from kaniko-project/executor
042c12654203: Pull complete
e623e7f7d83e: Pull complete
4a78c04d4eaa: Pull complete
762135a12fc6: Pull complete
36461b80159c: Pull complete
06f0188b0014: Pull complete
f60827012b7f: Pull complete
Digest: sha256:8e3b6d1e7fd713c6214dca4783844d39411b7b99a5a0c460e7f977ac5264b632
Status: Downloaded newer image for gcr.io/kaniko-project/executor:debug-v0.6.0

/ # /kaniko/executor -h
... hangs forever ...
```

I also raised this issue over on the [kaniko repo](https://github.com/GoogleContainerTools/kaniko/issues/471), but I have a feeling the problem might be on the microk8s side.

In `sudo journalctl -u snap.microk8s.daemon-kubelet.service -f` I see the following log message every 10 seconds:
```
Nov 26 20:47:57 microk8s-2 microk8s.daemon-kubelet[2192]: E1126 20:47:57.613723    2192 summary_sys_containers.go:45] Failed to get system container stats for "/user.slice/user-1002.slice/session-5.scope": failed to get cgroup stats for "/user.slice/user-1002.slice/session-5.scope": failed to get container info for "/user.slice/user-1002.slice/session-5.scope": unknown container "/user.slice/user-1002.slice/session-5.scope"
```

**Comment by ktsakalozos** [comment]
Hi @markns ,

Thank you for opening this issue. I got a 14.04 vm on AWS and did not see the issue you are reporting. Here is the full run I got: https://pastebin.com/XCR4cWa9 There must be something else causing the problem you report.

Can you please check the following:
- You do not have any other dockerd installed (eg apt docker.io or snap docker should not be installed)
- Packets to/from the pod network interface can be forwarded to/from the default interface on the host:
```
sudo iptables -P FORWARD ACCEPT
```
- Allow traffic on cbr0 interface:
```
sudo ufw allow in on cbr0 && sudo ufw allow out on cbr0
```

Can you also run `microk8s.inspect` and attach the output here?

Thank you for using MicoK8s.

**Comment by markns** [comment]
hey @ktsakalozos thanks for the quick reply. Glad to hear it _should_ work. :) I'm on GCP, strange that it would be different to AWS.

Anyway, to confirm - no other docker daemon is installed.

I ran both commands (after installing ufw) - sadly, no change. 
Here's the gzipped output: [inspection-report-20181126_213137.tar.gz](https://github.com/ubuntu/microk8s/files/2617389/inspection-report-20181126_213137.tar.gz)

Am in Europe, so signing out for the day. TIA for any other ideas though!

**Comment by ktsakalozos** [comment]
We have seen some applications being sensitive to the routing approach kubernetes has. Can you try the configuration suggested in https://github.com/ubuntu/microk8s/issues/140#issuecomment-431475148 . It is a wild guess but I cannot think of anything else at the moment.

**Comment by markns** [comment]
I tried that, but no improvement unfortunately. I guess that makes sense, given the test is just using `microk8s.docker` - ie. not even using kubernetes.
Will keep experimenting today and let you know if I find anything.

**Comment by ktsakalozos** [comment]
I see this happening on 18.04 outside MicroK8s.

Start with a new ubuntu on GCE `sudo apt-get install docker.io` and try 
```
ubuntu@juju-c733bc-0:~$ sudo docker run -it --entrypoint=sh gcr.io/kaniko-project/executor:debug-v0.6.0
Unable to find image 'gcr.io/kaniko-project/executor:debug-v0.6.0' locally
debug-v0.6.0: Pulling from kaniko-project/executor
042c12654203: Pull complete 
e623e7f7d83e: Pull complete 
4a78c04d4eaa: Pull complete 
762135a12fc6: Pull complete 
36461b80159c: Pull complete 
06f0188b0014: Pull complete 
f60827012b7f: Pull complete 
Digest: sha256:8e3b6d1e7fd713c6214dca4783844d39411b7b99a5a0c460e7f977ac5264b632
Status: Downloaded newer image for gcr.io/kaniko-project/executor:debug-v0.6.0
/ # /kaniko/executor -h
```

It will hang.

**Comment by markns** [comment]
Yes indeed, I saw that this morning also. Will close this. Thanks

**Comment by markns** [comment]
One final note in case anyone sees this issue in future: with a standard (ie. non snap) install of docker, kaniko runs perfectly well.

**Comment by ktsakalozos** [comment]
> with a standard (ie. non snap) install of docker

What do you mean @markns? My (failing) installation on gce was with `apt get install docker.io`.

**Comment by markns** [comment]
Hmm, interesting. I installed docker-ce using apt-get ([guide](https://docs.docker.com/install/linux/docker-ce/ubuntu/)), and everything works fine.

**Comment by markns** [comment]
I've also posted a few updates over on the Kaniko issue, including journalctl logs (although I'm pretty sure they're wondering how it's relevant to them ;))
