### ISSUE TITLE
Can I use the built-in registry on the local network?

### ISSUE THREAD

**Issue by Servellia** [ubuntu/microk8s#2117]
I have docker installed on an Azure DevOps built agent, which is building our images.
My goal is to push those images to a machine running Microk8s on 172.116.0.119, where the registry is enabled. When I issue `docker push 172.116.0.119:32000/image` I get the following response:

The push refers to repository [172.116.0.119:32000/image]
Get https://172.116.0.119:32000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Looking up ` microk8s kubectl get all --all-namespaces` revealed, that the registry is running on the followin nodeport:
`container-registry   service/registry                    NodePort       10.152.183.119   <none>        5000:32000/TCP 18h`

So I tried the same process again, with that ip with the same result.

Is it possible to expose the built-in registry on a socket different then localhost:32000 and if so, which steps need to be taken, except adding it to the list of insecure registries? The documentation does not cover this topic explicitly, if I read it correctly.
To reiterate: docker and Microk8s are on different hosts. They are _not_ on the same machine.

Best regards

**Comment by balchua** [comment]
Oh the registry is using insecure registry. You need to configure your docker to allow connecting to an insecure registry.

**Comment by Servellia** [comment]
On the build agent machine running docker, this is the config of /etc/docker/daemon.json, so that should be covered.

```json
{
        "insecure-registries" : [
                "localhost:32000",
                "172.16.0.119:32000",
                "10.152.183.119:32000",
                "local"
        ]
}
```

**Comment by balchua** [comment]
Stupid question here, did you restart docker?  Coz based on your log above, it seems to be connecting using https.

```
Get https://172.116.0.119:32000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

```

**Comment by Servellia** [comment]
Yes I did restart and just for good measure did another `sudo systemctl restart docker` just now on the agent machine.

**Comment by balchua** [comment]
Actually i also do the same.  I have docker on one machine and push to the registry addon.  Since the port is exposed as a nodeport, it should allow one to connect to it.
You may need to check the network between the 2 machines.

**Comment by Servellia** [comment]
I got cross eyed when entering the IPs. The target IP for the registry is actually `172.16.0.116` , so the push now works. But after the push, the image does not show up in the registry using `microk8s ctr images ls -q` and a pull is also not possible, when trying to deploy:

Failed to pull image "172.16.0.116:32000/image:staging": rpc error: code = Unknown desc = failed to pull and unpack image "172.16.0.116:32000/his.web:staging": failed to resolve reference "172.16.0.116:32000/image:staging": failed to do request: Head "https://172.16.0.116:32000/v2/image/manifests/staging": http: server gave HTTP response to HTTPS client

Im thoroughly confused as why microk8s is trying to use https here, as it should be http.

I've updated the `containerd-template.toml` with an updated mirrors section and added:

```
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."172.16.0.116:32000"]
        endpoint = ["http://172.16.0.116:32000"]
```
 All in all I was still not able to successfully push an image to the cluster.

**Comment by balchua** [comment]
This time, did you restart containerd?

**Comment by Servellia** [comment]
Does `microk8s stop` / `microk8s start` count?

**Comment by balchua** [comment]
Yes.

**Comment by Servellia** [comment]
I'm a bit embarassed, but an elongated lunch break and a walk around the office did resolve the issue. 
```
Warning  Failed        137m                  kubelet            Error: ImagePullBackOff
Normal   BackOff       137m                  kubelet            Back-off pulling image "172.16.0.116:32000/image:staging"
Normal   Pulling       137m (x2 over 137m)   kubelet            Pulling image "172.16.0.116:32000/image:staging"
Normal   Pulled        136m                  kubelet            Successfully pulled image "172.16.0.116:32000/image:staging" in 10.717754053s
Normal   Created       136m                  kubelet            Created container image
Normal   Started       136m                  kubelet            Started container image
```

Thank you for your time and patience @balchua

**Comment by balchua** [comment]
Thanks @Servellia ! Happy to help. 👍
