### ISSUE TITLE
Helm3 addon doesn't recognize --create-namespace flag

### ISSUE THREAD

**Issue by benlsheets** [ubuntu/microk8s#2124]
While following the installation for democratic-csi @ https://www.truenas.com/docs/hub/solutions/kubernetes/#helm-installation using the helm3 microk8s addon it gives a fault for unrecognized flag (--create-namespace). Following the instructions using a locally installed version of helm3 works as expected.

[inspection-report-20210323_234952.tar.gz](https://github.com/ubuntu/microk8s/files/6193422/inspection-report-20210323_234952.tar.gz)

**Comment by balchua** [comment]
Helm3 update to v3.5.0 is scheduled for the 1.21 release.  See the related PR here https://github.com/ubuntu/microk8s/pull/1936

The current version packaged with MicroK8s is old and perhaps obsolete.

I am going to close this for now.  Feel free to file an issue if you are having an issue.
Thanks
