### ISSUE TITLE
Error with Cluster

### ISSUE THREAD

**Issue by VooxoPlay** [ubuntu/microk8s#2137]
Hey,

I have the problem that one server with microk8s works fine but in a cluster with three servers there is a error and it takes very long to create a deployment:

command: kubectl create deployment httpenv --image=bretfisher/httpenv

describe:
Name:         httpenv-6fdc8554fb-7vhhn
Namespace:    default
Priority:     0
Node:         node0003/159.69.33.114
Start Time:   Tue, 30 Mar 2021 16:58:41 +0200
Labels:       app=httpenv
              pod-template-hash=6fdc8554fb
Annotations:  cni.projectcalico.org/podIP: 10.1.11.193/32
              cni.projectcalico.org/podIPs: 10.1.11.193/32
Status:       Running
IP:           10.1.11.193
IPs:
  IP:           10.1.11.193
Controlled By:  ReplicaSet/httpenv-6fdc8554fb
Containers:
  httpenv:
    Container ID:   containerd://27440e5f249df8dc7fb1641e337d66e3d42102a7190a7f9060444b9232e1b29c
    Image:          bretfisher/httpenv
    Image ID:       docker.io/bretfisher/httpenv@sha256:5d26f8e2008426bf4f2bad5fa0d413e894ca7438abacb31e3a9c48987188a288
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 30 Mar 2021 17:10:56 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-sn4qq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-sn4qq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-sn4qq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               13m                  default-scheduler  Successfully assigned default/httpenv-6fdc8554fb-7vhhn to node0003
  Warning  FailedCreatePodSandBox  13m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "172675d5a47a3991d06cf291131817be0daa664ea733e8d15fc2f34585684b4b": Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/ippools: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  12m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e5e464293e3195a406583497e75fb55be0f14dc887dd00be89ff997a2b50fd73": error getting ClusterInformation: Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  11m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "42947712eaa6302c87d24d18b2ac8c745e5a2bcff49d5fda439d003bbf6e23e0": Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/ippools: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  10m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1915c516803d12f33ac38947384b07e46f9c7126ceae2558ad62de05ce8b9d71": Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/ippools: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  10m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7876579a4d7c212e7179a2616212957593943dd1ceffd8efa74bd1e784822c7c": error getting ClusterInformation: Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  9m25s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3d6f5396dd88b5f270e117c402576714b9558905cfeaa85d161191c63006d2b1": Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/ippools: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  8m44s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7a3ea59f662131e72c98b3854e71df55325914742428bc8057914c4c3852d769": error getting ClusterInformation: Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  8m2s                 kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4e398341b0a401d8af4cb0428d6d499fa5080b7255b61b0fe229ecdf6e8ead8f": error getting ClusterInformation: Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  7m21s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8f56d88902cdd323df9256003ae1b92e4664fa1bf8dbd864b3b28b6d2bb3798c": error getting ClusterInformation: Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.152.183.1:443: i/o timeout
  Warning  FailedCreatePodSandBox  97s (x8 over 6m37s)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c23dc051b2742f4fdfab8333bffd0ab7124cee20f4f6b09034ef4a5dec76f238": error getting ClusterInformation: Get https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default: dial tcp 10.152.183.1:443: i/o timeout
  Normal   Pulling                 82s                  kubelet            Pulling image "bretfisher/httpenv"
  Normal   Pulled                  79s                  kubelet            Successfully pulled image "bretfisher/httpenv" in 2.97512479s
  Normal   Created                 79s                  kubelet            Created container httpenv
  Normal   Started                 78s                  kubelet            Started container httpenv

[node0001-inspection-report-20210330_171404.tar.gz](https://github.com/ubuntu/microk8s/files/6230047/node0001-inspection-report-20210330_171404.tar.gz)
[node0002-inspection-report-20210330_171409.tar.gz](https://github.com/ubuntu/microk8s/files/6230049/node0002-inspection-report-20210330_171409.tar.gz)
[node0003-inspection-report-20210330_171410.tar.gz](https://github.com/ubuntu/microk8s/files/6230052/node0003-inspection-report-20210330_171410.tar.gz)

**Comment by balchua** [comment]
Thanks for reporting the issue.  Something isn't right with node2.  Do you mind attaching the node2 inspect tarball?

**Comment by VooxoPlay** [comment]
I reinstalled the three nodes several times and still the same thing and I attached the tarballs for each node

**Comment by balchua** [comment]
Thanks for the tarball, looking at the pods age, im wondering how come the dns pod is older than calico pods.
Based on the latest tarball you attached, it looks like a fresh cluster.

**Comment by VooxoPlay** [comment]
My problem is that the deployment is started with one node in seconds and because of this error with 3 nodes it takes minutes

**Comment by balchua** [comment]
Hi @VooxoPlay is it possible to turn off ipv6 on all nodes and reinstall MicroK8s `snap remove microk8s --purge`.
Thanks

**Comment by VooxoPlay** [comment]
same issue but I have no time to use something that does not just work. I was willing to spend 3 days for switching to self-hosted kubernetes with microk8s.

**Comment by VooxoPlay** [comment]
Ok I had an idea and some spare time so I tested it:

in my previous tests I used the network function of my provider:

description of the network function:
Networks provide private layer 3 links between Hetzner Cloud Servers using dedicated network interfaces. You can use them to conveniently construct multi-tier architectures spanning multiple locations.

now I used the public IP and it worked. Is there a reason why it does not work with the private network between the servers? The private network is a 172.16.0.0/12 subnet

**Comment by balchua** [comment]
@VooxoPlay thank you for providing more details..  just wanted to know, when u say "now you use the public ip" you use it to join the nodes?  Or just disable the private network?  Sorry i am not familiar with the cloud provider.

Fyi, i spin up a multi node MicroK8s with DigitalOcean and azure, I don't see that behavior you are seeing.

**Comment by VooxoPlay** [comment]
yeah I used the public ip to join the nodes and with it all seems fine. They still have access to the private network.
