### ISSUE TITLE
please update docker version

### ISSUE THREAD

**Issue by borkmann** [ubuntu/microk8s#214]
Current version seems to be docker 17.03 which doesn't support multi-stage builds (starting from 17.06), so for docker build I'm getting an error with `Error parsing reference: [...] is not a valid repository/tag: invalid reference format`. :-(

**Comment by markns** [comment]
+1 here, I was trying to rebuild [kaniko](https://github.com/GoogleContainerTools/kaniko) and ran into this:

```
Step 15/29 : COPY --from=0 /go/src/github.com/GoogleContainerTools/kaniko/out/executor /kaniko/executor
Unknown flag: from
```

**Comment by battlemidget** [comment]
FYI: https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1794396

Still going through proposed in xenial, shouldn't be long though

**Comment by marcoceppi** [comment]
It's a snap, why do we have to wait for Debian packaging?

**Comment by kitepad** [comment]
When is ready? I see the fix has been released at Nov. , but I still got 17.03.2 after I installed microk8s today.
Why?

**Comment by kitepad** [comment]
My ubuntu is 18.04.

**Comment by ktsakalozos** [comment]
Hi @kitepad 

The snap is build on Ubuntu Core 16 as a base, meaning it is close to xenial 16.04. I believe the new dockerd hit the xenial repositories some time this weekend (not sure exactly when) and we need to work on making sure that there is not issue with MicroK8s. Any future release from now on should come with the new dockerd.

Thanks.

**Comment by andriy-f** [comment]
@ktsakalozos Is it possible to base a snap on 18.04?

**Comment by ktsakalozos** [comment]
@andriy-f , yes It is possible to base the snap on core18. You need to edit snapcraft.yaml https://github.com/ubuntu/microk8s/blob/master/snapcraft.yaml and add a "base: core18" and rebuild. Some initial testing shows that the snap is functional but I have not tested it thoroughly. Do you want to give it a try and provide some feedback?

**Comment by dmarkey** [comment]
This would be great.. I'd like to roll this out but blocked on the docker version.

**Comment by kitepad** [comment]
@ktsakalozos, it is has been fixed :  https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/1794396

but still is 17.03 after I install microk8s today.

**Comment by battlemidget** [comment]
microk8s snap needs to be rebuilt so it'll pick up the new docker. We have a job that does this automatically and shouldn't be much longer

**Comment by ktsakalozos** [comment]
A build with the 18.06 dockerd is already on edge (`sudo snap install microk8s --classic --edge`). Please give it a try.

Thanks

**Comment by dmarkey** [comment]
Two problems: 

Invalid image name:

  Warning  InspectFailed      76s (x3 over 78s)  kubelet, dmarkey-workstation  Failed to apply default image tag "gcr.io/google_containers/defaultbackend-:1.4": couldn't parse image reference "gcr.io/google_containers/defaultbackend-:1.4": invalid reference format

➜  ~ microk8s.enable metrics-server                                       
Enabling metrics-server
/snap/microk8s/354/usr/bin/dpkg: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory

(but still seems to work)

**Comment by dmarkey** [comment]
UPDATE: Once i install the libselinux on my host it started to work. (shouldnt all dependencies be in the snap?)

**Comment by ktsakalozos** [comment]
You are right @dmarkey, all dependencies should be in the snap. The fall back should be the host system. It is not a good time for me to debug this but I need to ask, which distro are you on?

**Comment by dmarkey** [comment]
Arch \o/

**Comment by ktsakalozos** [comment]
I knew it!

**Comment by frol** [comment]
@dmarkey `yay -S libselinux` did the trick! Thank you! \o/

**Comment by joestringer** [comment]
I don't think this applies any more with microk8s 1.14, which uses containerd by default.

**Comment by ktsakalozos** [comment]
Closing this since we moved to the latest containerd (1.14+) and docker packages.
