### ISSUE TITLE
Error 404 on lot of documentation

### ISSUE THREAD

**Issue by Turiok** [ubuntu/microk8s#2152]
I want to discover kubernetes and use it on home rpi cluster. 
I hesitate between microk8s and a competitor. But a large part of your documentation shows a 404 error withi this url : 
https://microk8s.io/t/alternative-installs-macos-windows-10-multipass/11257 
But it works on this link : https://discuss.kubernetes.io/t/alternative-installs-macos-windows-10-multipass/11257

**Comment by balchua** [comment]
Hi @Turiok thank you for reporting.
@evilnick maybe able to help here.

**Comment by Turiok** [comment]
It is very strange. Since now the URL are correct.
For example My first need was to see the installation for arm architecture.
And the url was : https://microk8s.io/t/alternative-installs-macos-windows-10-multipass/11257 when I clicked to the section Raspberry Pi/ARM.
But now the URL when I'm clicking to the same section is : https://microk8s.io/docs/install-alternatives#heading--arm and it works

**Comment by ktsakalozos** [comment]
@evilnick is there anything we can do about now stray pointers to our docs?
