### ISSUE TITLE
`kubctl exec` `iptables -L` command permission denied inside the container

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#216]
```
$ k exec -it web-0 -- /bin/bash
root@web-0:/# iptables -L
iptables v1.6.1: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
root@web-0:/#
```
I have already `sudo apt install linux-image-$(uname -r)` inside the container. Google results suggests running the container in privileged mode or add NET_ADMIN capability. How to do that with microk8s, either in manifest files or when `kubectl exec` into the running pod? Thanks.

**Comment by ktsakalozos** [comment]
To allow privileged containers you need to add a `--allow-privileged true` argument to the `kubelet` and `kube-apiserver` configs under `/var/snap/microk8s/current/args/` and then restart the two servers:
```
sudo systemctl restart snap.microk8s.daemon-apiserver
sudo systemctl restart snap.microk8s.daemon-kubelet
```

On your pod you should use the proper flag as described in https://kubernetes.io/docs/concepts/workloads/pods/pod/#privileged-mode-for-pod-containers
