### ISSUE TITLE
Cinder CSI Plugin not working

### ISSUE THREAD

**Issue by lfdominguez** [ubuntu/microk8s#2166]
1 - Enabled the storage plugin of microk8s
2 - Disabled the storage plugin of microk8s
3 - Installed the CSI Cinder driver changing the path to use the path `/var/snap/microk8s/common/var/lib/kubelet` as kubelet dir.
4 - The CSI create the volumes correctly on OpenStack cloud.
5 - The CSI plugin show this error logs:
```
E0411 23:01:49.090504 1 mount_linux.go:175] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o bind /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/globalmount /var/snap/microk8s/common/var/lib/kubelet/pods/8f28ba87-a904-45bc-aa68-b1bb72b9d4a6/volumes/kubernetes.io~csi/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/mount
Output: mount: /var/snap/microk8s/common/var/lib/kubelet/pods/8f28ba87-a904-45bc-aa68-b1bb72b9d4a6/volumes/kubernetes.io~csi/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/mount: special device /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/globalmount does not exist.

E0411 23:01:49.090705 1 utils.go:84] GRPC error: rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t ext4 -o bind /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/globalmount /var/snap/microk8s/common/var/lib/kubelet/pods/8f28ba87-a904-45bc-aa68-b1bb72b9d4a6/volumes/kubernetes.io~csi/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/mount
Output: mount: /var/snap/microk8s/common/var/lib/kubelet/pods/8f28ba87-a904-45bc-aa68-b1bb72b9d4a6/volumes/kubernetes.io~csi/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/mount: special device /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-ed753933-ac97-4a67-b9b0-d4c849376ccc/globalmount does not exist
```

The `globalmount` folder is created, but the device `/dev/vdc` (in this example) is not mounted to that `globalmount` folder.

[inspection-report-20210411_230050.tar.gz](https://github.com/ubuntu/microk8s/files/6292946/inspection-report-20210411_230050.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @lfdominguez 

I see in `dmesg`:
```
[2969092.977643] EXT4-fs (vdc): mounted filesystem with ordered data mode. Opts: (null)
```
I wonder where vdc is mounted. Could you share more details on step `3. Installed the CSI Cinder driver`. Please be as descriptive as possible, what instructions did you follow, helm charts, values etc.

@joedborg, have you seen this error while working on the ceph operator?

**Comment by lfdominguez** [comment]
Nono, that's because i mounted manual the vdc to test if kubernetes format it, please here is a full reference https://github.com/kubernetes/cloud-provider-openstack/issues/1478

**Comment by lfdominguez** [comment]
I posted here too, because the CSI create the volume on the cloud and assign the virtual device to the node... then k8s format it, but not mount to the `globalmount` path... so i dont know really if that is a CSI Job or a K8s Job, because i see on `kubernetes/utils` repo, `mount_linux.go` file, that kubernetes mount the device... but in this case is not mounting anything

**Comment by balchua** [comment]
@lfdominguez just checking here.
I saw you have this defined in your yaml
```yaml
            - name: DRIVER_REG_SOCK_PATH
              value: /var/snap/microk8s/common/var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock

```
Shouldn't it be like this?
```yaml
            - name: DRIVER_REG_SOCK_PATH
              value: /registration/
```

**Comment by lfdominguez** [comment]
well the original value was `/var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock` and then i changed to add the custom path where snapd has the kubelet path.

**Comment by lfdominguez** [comment]
https://github.com/kubernetes/cloud-provider-openstack/blob/master/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml

**Comment by balchua** [comment]
But from the pod, it sees `/registration` path (since thats what you already mounted to `registration-dir`) rather than `/var/snap/microk8s/common/var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock`

**Comment by lfdominguez** [comment]
I will change to use `/registration/csi.sock` and check because is strange... /registration is the kubelet folder mounted... so why the original file dont use the /registration folder?

**Comment by lfdominguez** [comment]
`"transport: Error while dialing dial unix /registration/csi.sock: connect: no such file or directory"` on node-driver-registry container of nodeplugin

**Comment by balchua** [comment]
Another thing from the original yaml the `/registration` path is pointing only to the plugin registry directory and not the `sock` file.

```yaml
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
```

**Comment by joedborg** [comment]
@lfdominguez Did you `mkdir /registration` on your host?

**Comment by lfdominguez** [comment]
> n your host?

well that's on container....

**Comment by balchua** [comment]
Forgot to mention i haven't used cinder, but i tried with openebs which also has the same node registration.  And no i dont have to create the `regustration` path on the host.

**Comment by joedborg** [comment]
@lfdominguez ah sorry, i've just read through again.  I'd misread and thought you were changing to `/registration` on the host as a test.

You tell if the socket is okay by looking at the logs of the different ceph pods, they output the messages sent over the socket.  FWIW, we've addressed the issue of deployments like this trying to access host kubelet dir, rather than the snap's one in latest/edge.

**Comment by lfdominguez** [comment]
now i change to `/var/snap/microk8s/common/var/lib/kubelet/plugins/cinder.csi.openstack.org/csi.sock` and my question is... why is working that if `/var/snap/microk8s/common.....` doesnt exists inside the container....

**Comment by lfdominguez** [comment]
```
I0412 13:49:31.224164 1 main.go:110] Version: v1.3.0-0-g6e9fff3e
I0412 13:49:31.224393 1 connection.go:151] Connecting to unix:///csi/csi.sock
W0412 13:49:41.224801 1 connection.go:170] Still connecting to unix:///csi/csi.sock
I0412 13:49:42.988565 1 node_register.go:51] Starting Registration Server at: /registration/cinder.csi.openstack.org-reg.sock
I0412 13:49:42.989119 1 node_register.go:60] Registration Server started at: /registration/cinder.csi.openstack.org-reg.sock
I0412 13:49:44.045390 1 main.go:77] Received GetInfo call: &InfoRequest{}
I0412 13:49:47.631675 1 main.go:87] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

**Comment by lfdominguez** [comment]
humm.. now this log line is recurrent `Connecting to unix:///csi/csi.sock` sems is blocked trying to connect to sock

**Comment by lfdominguez** [comment]
> Hi @lfdominguez
> 
> I see in `dmesg`:
> 
> ```
> [2969092.977643] EXT4-fs (vdc): mounted filesystem with ordered data mode. Opts: (null)
> ```
> 
> I wonder where vdc is mounted. Could you share more details on step `3. Installed the CSI Cinder driver`. Please be as descriptive as possible, what instructions did you follow, helm charts, values etc.
> 
> @joedborg, have you seen this error while working on the ceph operator?

Now i see this kind of message on another node... but i dont see where is the device mounted.... `mount -l` dont list it, even i tested with `/proc/<csi-cinder-plugins-pid>/mounts` to check if are mounted inside a container namespace... and not listed there... so where to find it...

**Comment by lfdominguez** [comment]
https://github.com/kubernetes/cloud-provider-openstack/issues/1478#issuecomment-818435332

**Comment by lfdominguez** [comment]
https://github.com/kubernetes/cloud-provider-openstack/issues/1478#issuecomment-818479299
