### ISSUE TITLE
`microk8s status` shows microk8s is not running, but `microk8s inspect` reports no error

### ISSUE THREAD

**Issue by GalvinGao** [ubuntu/microk8s#2171]
## Environment
- OS: Ubuntu 18.04.5 LTS
- CPU: 1 Core
- RAM: 2G

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

## Steps to reproduce

```
$ sudo snap install microk8s --classic --channel=1.21

microk8s (1.21/stable) v1.21.0 from Canonical✓ installed

$ sudo usermod -a -G microk8s $USER
$ sudo chown -f -R $USER ~/.kube
$ exit

# (now I just reconnect to the server)

$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
$ microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2128/inspection-report-20210413_140233.tar.gz

```

[inspection-report-20210413_140257.tar.gz](https://github.com/ubuntu/microk8s/files/6301585/inspection-report-20210413_140257.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @GalvinGao. Do you happen to be behind a firewall of some kind? I see int he logs:
```
Apr 13 14:02:39 ggtencentshanghai microk8s.daemon-kubelite[27148]: E0413 14:02:39.492578   27148 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"calico-node-dh2pd_kube-system(73bca285-407c-45a1-94b9-b18cc7f259dc)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"calico-node-dh2pd_kube-system(73bca285-407c-45a1-94b9-b18cc7f259dc)\\\": rpc error: code = Unknown desc = failed to get sandbox image \\\"k8s.gcr.io/pause:3.1\\\": failed to pull image \\\"k8s.gcr.io/pause:3.1\\\": failed to pull and unpack image \\\"k8s.gcr.io/pause:3.1\\\": failed to resolve reference \\\"k8s.gcr.io/pause:3.1\\\": failed to do request: Head \\\"https://k8s.gcr.io/v2/pause/manifests/3.1\\\": dial tcp 64.233.189.82:443: i/o timeout\"" pod="kube-system/calico-node-dh2pd" podUID=73bca285-407c-45a1-94b9-b18cc7f259dc
``` 

You can see in [1] how to configure MicroK8ss to use aproxy. 

[1] https://microk8s.io/docs/install-proxy

**Comment by GalvinGao** [comment]
> Hi @GalvinGao. Do you happen to be behind a firewall of some kind? I see int he logs:
> 
> ```
> Apr 13 14:02:39 ggtencentshanghai microk8s.daemon-kubelite[27148]: E0413 14:02:39.492578   27148 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"calico-node-dh2pd_kube-system(73bca285-407c-45a1-94b9-b18cc7f259dc)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"calico-node-dh2pd_kube-system(73bca285-407c-45a1-94b9-b18cc7f259dc)\\\": rpc error: code = Unknown desc = failed to get sandbox image \\\"k8s.gcr.io/pause:3.1\\\": failed to pull image \\\"k8s.gcr.io/pause:3.1\\\": failed to pull and unpack image \\\"k8s.gcr.io/pause:3.1\\\": failed to resolve reference \\\"k8s.gcr.io/pause:3.1\\\": failed to do request: Head \\\"https://k8s.gcr.io/v2/pause/manifests/3.1\\\": dial tcp 64.233.189.82:443: i/o timeout\"" pod="kube-system/calico-node-dh2pd" podUID=73bca285-407c-45a1-94b9-b18cc7f259dc
> ```
> 
> You can see in [1] how to configure MicroK8ss to use aproxy.
> 
> [1] [microk8s.io/docs/install-proxy](https://microk8s.io/docs/install-proxy)

Wow that come from nowhere. Actually I don't really have a firewall, but those servers are all connecting to the network from Mainland China which from what I known the connectivity to k8s.io is a known issue. I'll try to see if there's any mirror or proxy I could use...

Thanks a lot for your help!! I was trying to going through every logs but it has been 2 days and it seems that my strategy of reading logs shall improve lol.

I'll post solutions here once I found a suitable one. :D

**Comment by GalvinGao** [comment]
Sorry for keep you waiting. At last I haven't found a way to make it running... it seems that a VPN is mandatory.

Thanks again for your help!
