### ISSUE TITLE
How to select a master nodes

### ISSUE THREAD

**Issue by hitman249** [ubuntu/microk8s#2184]
How to select a master nodes (in yaml)? 

Is empty:  
`kubectl get node --selector='node-role.kubernetes.io/master'`

```
$ microk8s.status
microk8s is running
high-availability: yes
  datastore master nodes: 192.168.1.172:19001 192.168.1.199:19001 192.168.1.38:19001
  datastore standby nodes: 192.168.1.11:19001
```

**Comment by balchua** [comment]
@hitman249 by default MicroK8s do not label nodes as master node, since all of them can act as a control plane at some point of time.  With dqlite it will automatically find and elect nodes to be voters and standbys.

**Comment by hitman249** [comment]
@balchua
In that case, how do you install `keepalived`?  
Is there a microk8s its analogs?

**Comment by balchua** [comment]
I am not familiar with keepalived, but i just have an LB pointing to all nodes' apiserver which is running on `16443`.
Btw all nodes do run an apiserver.

**Comment by hitman249** [comment]
Thank you. Checked that any node can handle a request, in which case it does not matter who the master.
