### ISSUE TITLE
Create Static Pods

### ISSUE THREAD

**Issue by hitman249** [ubuntu/microk8s#2189]
https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/#static-pod-creation

What directory is used inside the container to create static pods?

**Comment by balchua** [comment]
@hitman249 You mean from the `kubelet` argument `--staticPodPath`?

**Comment by hitman249** [comment]
@balchua yes, or [kubelet configuration file](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) `staticPodPath: <the directory>`

**Comment by balchua** [comment]
For now microk8s doesn't support the config file yet.  Why not use daemonset instead of static pods?

**Comment by hitman249** [comment]
Redesigned my code to DaemonSet.
But, support for static pods is still required to support existing third-party code.

**Comment by balchua** [comment]
@hitman249 in this case, you can create your staticpod directory inside `/var/snap/microk8s/current/var/staticpod`.  Then configure `--staticPodPath` to use the above directory.  Finally restart MicroK8s.

**Comment by hitman249** [comment]
>  Then configure --staticPodPath to use the above directory.

how to configure?

**Comment by balchua** [comment]
Oh im sorry didn't give you the filename.  
Edit the file `/var/snap/microk8s/current/args/kubelet` by adding the argument into that file.

**Comment by balchua** [comment]
@hitman249 i am going to close this one.  If you have issues feel free to create one.  Thanks for using MicroK8s.

**Comment by hitman249** [comment]
> Edit the file `/var/snap/microk8s/current/args/kubelet` by adding the argument into that file.
> Make sure that the directory you are adding exist.

This must be done on each node?

**Comment by balchua** [comment]
Yes on each node.

**Comment by hitman249** [comment]
> Then configure --staticPodPath to use the above directory.  

Result:
`unknown flag: --staticPodPath`

Correct: 
`--pod-manifest-path`

**Comment by balchua** [comment]
Oops im sorry @hitman249 and thanks for pointing it out.
