### ISSUE TITLE
add "version" argument to microk8s cli

### ISSUE THREAD

**Issue by sed-i** [ubuntu/microk8s#2192]
One hacky way to get the installed version of microk8s is (to parse the output of) `snap info microk8s | grep installed`.
An `elif` could be added to `microk8s.wrapper` along the lines of the "help" argument:
```bash
elif [ "${APP}" == "version" ] || [ "${APP}" == "--version" ] || [ "$APP" == "-v" ]; then
    # TODO how to get the version numer?
    readonly EXIT="0"
```

https://github.com/ubuntu/microk8s/blob/c8ba1b2fd72f906c74fb409d342dde3975da7650/microk8s-resources/wrappers/microk8s.wrapper#L27

**Comment by ktsakalozos** [comment]
`microk8s kubectl version` will show the kubernetes version that should match the MicroK8s one.

**Comment by sed-i** [comment]
oh nice! for some reason I see two almost identical lines that differ only in the `BuildDate`:
```console
$ microk8s kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.5-34+40f5951bd9888a", GitCommit:"40f5951bd9888a0e27960e88d1250627fb085871", GitTreeState:"clean", BuildDate:"2021-03-22T16:58:38Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.5-34+40f5951bd9888a", GitCommit:"40f5951bd9888a0e27960e88d1250627fb085871", GitTreeState:"clean", BuildDate:"2021-03-22T16:59:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

consistency- and logging convenience wise would be nice to be able to get just the version, similar to 
```console
$ echo $(juju --version) $(juju version)
2.8.10-groovy-amd64 2.8.10-groovy-amd64
```

**Comment by balchua** [comment]
@sed-i the result of `kubectl version` is normal, it shows the version of the **client** (in this case kubectl) and the **server** (i.e. kubernetes).

**Comment by balchua** [comment]
I am closing this, since there's no action to be done.  Thanks @sed-i for using MicroK8s.
