### ISSUE TITLE
Pods can't access lan ip's in data centre on centos 7/8 

### ISSUE THREAD

**Issue by harpermj66** [ubuntu/microk8s#2197]
[inspection-report-20210422_160452.tar.gz](https://github.com/ubuntu/microk8s/files/6359516/inspection-report-20210422_160452.tar.gz)

I have scoured various topics related to this but none of the fixes seem to be applicable to my situation.
I really needs some help with the following;

Microk8 install 1.20 on centos 7 and 8 in a data centre.

I can install it, and all appears to be ok on the surface but accessing lan ip's (that can be accessed directly on the kubernetes host) can't be from within pods. 

I have applied  sudo iptables -P FORWARD ACCEPT and added an entry to the kubernetes host mapping 127.0.0.1 to the host name.

Example:
This ip of the host is 10.1.3.13 and I can ping 10.1.3.15, 10.1.3.16 etc from 10.1.3.13, but from the pods I can only ping the host.

I did downgrade to 1.18 and I could then see the lan ip's but then I lost my ingress. I need both to work.

**Comment by balchua** [comment]
Hi @harpermj66 do you happen to have multiple network interface?

**Comment by harpermj66** [comment]
Is the inspection tarball not attached in my first description content?

**Comment by balchua** [comment]
Thanks.  I overlooked it.
I am going to take a wild guess here.  The flannel interface must be interfering with calico.

First stop microk8s, then delete the flannel interface like this `sudo ip link delete cni0 ip link delete flannel.1`. Then start microk8s.  Let's see if it works this time.🤞

**Comment by harpermj66** [comment]
Ill give it a try thanks

**Comment by balchua** [comment]
@harpermj66 i updated the command. See comment above https://github.com/ubuntu/microk8s/issues/2197#issuecomment-825587806

**Comment by harpermj66** [comment]
Sadly no it didn't work.

**Comment by balchua** [comment]
Went back to the logs and check.
I saw a lot of these logs emmitted by the calico-node

```
==== START logs for container calico-node of pod kube-system/calico-node-l4gh5 ====
2021-04-22 06:47:32.236 [ERROR][62] health.go 246: Health endpoint failed, trying to restart it... error=listen tcp 127.0.0.1:9099: bind: address already in use
2021-04-22 06:47:33.236 [ERROR][62] health.go 246: Health endpoint failed, trying to restart it... error=listen tcp 127.0.0.1:9099: bind: address already in use
```
Weird.  When i check the netstat log, 9099 is started by `calico-node`.

Just wondering if there are other programs using that port? Thanks

**Comment by harpermj66** [comment]
I saw that too but I don't see any other programs using that port and I've tried on two different machines

**Comment by harpermj66** [comment]
If if stop microk8s I still set that port assigned to calico

**Comment by harpermj66** [comment]
I've installed 1.21/edge and the heath endpoint failure above is gone. Behaviour is the same however so I think that was a distraction

**Comment by balchua** [comment]
I tried to replicate the setup and I can't reproduce the error you are getting. 😔
What image do you use to ping other hosts?
When you installed the 1.21/edge did you remove microk8s like this `sudo snap remove microk8s --purge`?  So its a squeeky clean setup.

**Comment by harpermj66** [comment]
No problem thanks, I can't reproduce it either on my home network although I haven't installed with minimal Centos. and I've discovered that someone in the data centre has install another kuberenetes distribution which appears to have brought down k8s and all our QA systems with it today.

I be sure post our solution (now this event has escallated it) in case anybody else encounters the same problem.

**Comment by harpermj66** [comment]
In our datacentre we have a firewall that's configured outside of the individual machines/VM's so there will be no firewall or selinux on the individual machines but there will be firewall control across them. One of our data engineers pointed out there was a half dozen or so network interfaces created by microk8s that wouldn't work if network traffic was routed through them because of the firewall. Does that sound a plausable scenario for this issue? Given this is a single node instance I didn't think that would be an issue.

Also, I had raised an ticket related to a failing Ingress 'liveness probe failed on 10254' which I closed because no one responded. - probably because no one has had the issue. This one is was able to replicate locally. 

I installed 1.20 first, then removed and installed 1.18 without rebooting. The ingress wouldn't start up. After a reboot it was fine.
I would be curious to know why reboots would fix this. I've seen a lot of tickets where people have said rebooting fixed the issue. It's not always possible to do that.

**Comment by balchua** [comment]
@harpermj66 when you removed `1.20` did you purge it? Like `sudo snap remove microk8s --purge`?

**Comment by harpermj66** [comment]
I did do a purge. I also deleted the calico network interfaces and others that weren't being used by 1.18 and I restarted all the microk8s services. I can't think of anything else I can do, there must be something though.

Useful to know it was the introduction of calico that our data centre can't cope with. That will help a lot. Thanks

**Comment by balchua** [comment]
@harpermj66 if you disable `ha`, it will then fall back to using flannel and etcd.  So you can use v1.19+ as long as you disable `ha`.  To do so simply do `microk8s disable ha-cluster`.

**Comment by harpermj66** [comment]
Thanks very much I will try that out.
