### ISSUE TITLE
Need a recipe for properly enabling RBAC on MicroK8s

### ISSUE THREAD

**Issue by msdotnetclr** [ubuntu/microk8s#220]
Default install of MicroK8s works fine with --authorization-mode=AlwaysAllow. However, simply changing the authorization mode to RBAC will break things (e.g. dashboard). We need documentation on how to properly enabling RBAC on MicroK8s.

**Comment by ktsakalozos** [comment]
While waiting for something official, I should point you to how other users have enabled RBAC https://github.com/ubuntu/microk8s/issues/84#issuecomment-423134519

**Comment by ktsakalozos** [comment]
Closing this since we just merged https://github.com/ubuntu/microk8s/pull/329 .

See: https://github.com/ubuntu/microk8s/issues/84#issuecomment-492670981
