### ISSUE TITLE
Pods don't have internet issues - only when adding nodes

### ISSUE THREAD

**Issue by simcax** [ubuntu/microk8s#2200]
I am trying to get a raspberry pi 4 microk8s cluster up and running with multiple nodes. I had everyting running, and noticed at some point, that my pods did not have internet access. 
I tried several things to solve the problem, tinkering with iptables, removing and installing the snap etc. At all times I've had the DNS add-on enabled. 
In the end I tried removing the snap on all my nodes. Then:
1. Tried out a container in docker, to see if it had internet acces, it did - on all nodes. 
2. Installing microk8s via snap on the designated master node, and running a debug pod to see if it had internet access, it did. 
3. joining 1 node, running a debug pod - no internet connection
4. removing the node. removing microk8s and adding it again
5. Then spinning up a debug pod on the node, before joining, no internet acces, until I enabled the DNS add-on, then it had internet access
6. When joining the node to the cluster, any pod running on the node has no internet access

I am at a loss, as how to solve this problem. It seems as soon as I join a node to the cluster, any pods running on those nodes, cannot access the internet. Am I missing something?

[inspection-report-20210424_203843.tar.gz](https://github.com/ubuntu/microk8s/files/6370627/inspection-report-20210424_203843.tar.gz)

**Comment by simcax** [comment]
I also tried looking if ufw was enabled, it's not. 

uname -a:
Linux simpi402 5.8.0-1021-raspi #24-Ubuntu SMP PREEMPT Tue Apr 13 11:00:57 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

**Comment by balchua** [comment]
Hi @simcax how do you access the internet? Is it via some dns?  Like `www.google.com`?  If yes, then its normal that you need to have the `dns` addon running.  Also bear in mind that the current replicas set for the `coredns` is `1`.  Which may have affected it while the apiserver is being restarted.

**Comment by simcax** [comment]
Hi @balchua - yes, in order to test it out, I tried pinging google.com. The test was done in a debug pod using busybox:

kubectl run -i --tty busybox --image=busybox --restart=Never -- sh

Check, in all cases I had the dns add-on enabled. 

Right now I am trying to reinstall my cluster, and bumping ubuntu to v. 21.04

**Comment by simcax** [comment]
That seems to have done the trick. I now have internet access from pods running on slave nodes. I must have messed something up along the way.

**Comment by balchua** [comment]
Hi @simcax thanks for giving us an update.  I will close this issue.  Feel free to log an issue when you're having trouble with MicroK8s.

Thanks for using MicroK8s.
