### ISSUE TITLE
dns documentation

### ISSUE THREAD

**Issue by cneberg** [ubuntu/microk8s#221]
You should put a note in your quick install docs that if you enable the dns component and your company blocks external dns servers by default you'll have to update the default settings dns list via

> kubectl --namespace kube-system edit configmap/kube-dns

before it will work from any pods

**Comment by ktsakalozos** [comment]
Hi @cneberg ,

What did you have to change on kube-dns? The external nameserver IPs [8.8.8.8, 8.8.4.4]?

**Comment by topher96** [comment]
yes, I just changed those 2 ip addresses to local site DNS Servers.
