### ISSUE TITLE
"Cannot load dashboard menu link" Error

### ISSUE THREAD

**Issue by chacha95** [ubuntu/microk8s#2210]
I try to set up microk8s on remote server

Other add-on run well, but kubeflow dashboard doesn't.

When I access kubeflow centural dashboard, "Cannot load dashboard menu link" error occur.

I already set SSH tunelling with SOCKS5 proxy in Chrome(Using SwitchyOmega addon)

I don't know why it is happen.

## The Error image
![1](https://user-images.githubusercontent.com/31475037/116215664-dd944180-a782-11eb-8507-31b439ecef43.png)

## When I click recent pipelines, I can go to pipeline section
![2](https://user-images.githubusercontent.com/31475037/116215943-16ccb180-a783-11eb-89c4-a6e055fbba03.png)

## So I just delete `/_/` in URL, so the error is disapperar!
![3](https://user-images.githubusercontent.com/31475037/116215970-1af8cf00-a783-11eb-8ebd-84b01c562a5f.png)

## Inspection
[inspection-report-20210427_175804.tar.gz](https://github.com/ubuntu/microk8s/files/6383285/inspection-report-20210427_175804.tar.gz)

**Comment by idlefella** [comment]
Seems to be same issue as this one: https://github.com/canonical/bundle-kubeflow/issues/344
The answer from @knkski fixed it for me:
https://github.com/canonical/bundle-kubeflow/issues/344#issuecomment-827936799

**Comment by chacha95** [comment]
> Seems to be same issue as this one: [canonical/bundle-kubeflow#344](https://github.com/canonical/bundle-kubeflow/issues/344)
> The answer from @knkski fixed it for me:
> [canonical/bundle-kubeflow#344 (comment)](https://github.com/canonical/bundle-kubeflow/issues/344#issuecomment-827936799)

Oh! Thanks to your reply!

It just work!!
