### ISSUE TITLE
port forwarding error: error upgrading connection: error dialing backend: dial tcp: lookup: Temporary failure in name resolution

### ISSUE THREAD

**Issue by mahesh-hv-appmod** [ubuntu/microk8s#2232]
**summary**: port forwarding error on 2 node microk8s cluster (2 vagrant / virtualbox VMs). 

**context**: trying to access dashboard from host 

**details**:
microk8s version: v1.20.6 (2143) 220MB classic
ubuntu: 20.04.1 LTS
VMs: Vagrant / VirtualBox

**command**:  sudo microk8s kubectl port-forward -n kube-system service/kubernetes-dashboard 14443:443

**error**: error upgrading connection: error dialing backend: dial tcp: lookup node-1: Temporary failure in name resolution

![image](https://user-images.githubusercontent.com/77741042/117011754-26388700-acbc-11eb-9a58-82aef1a54124.png)

get nodes:

![image](https://user-images.githubusercontent.com/77741042/117012611-238a6180-acbd-11eb-83c2-61de1b194f71.png)

get pods:

![image](https://user-images.githubusercontent.com/77741042/117013107-90056080-acbd-11eb-8f0c-78571afcc1ce.png)

get services:

![image](https://user-images.githubusercontent.com/77741042/117012975-7401bf00-acbd-11eb-8f2b-6e2fa7837b3c.png)

microk8s inspect: 

![image](https://user-images.githubusercontent.com/77741042/117013336-c4791c80-acbd-11eb-9518-a166b2579c77.png)

[inspection-report-20210504_131139.tar.gz](https://github.com/ubuntu/microk8s/files/6421498/inspection-report-20210504_131139.tar.gz)

**Comment by balchua** [comment]
Hi can you add on both node's `/etc/hosts` the hostnames of each one of them?

Example
```
192.168.1.1 k8s-master
192.168.1.2 node-1
```

**Comment by mahesh-hv-appmod** [comment]
Hi there,

added the nodes to the `hosts ` file and that worked! thank-you

the port forwarding command worked but it forwarded to 8443 instead of 443. is that because 443 is in use?

```
sudo microk8s kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443 --address 0.0.0.0 
Forwarding from 0.0.0.0:10443 -> 8443
```

in any event was able to access dashboard with the token credentials

thanks

**Comment by balchua** [comment]
@mahesh-hv-appmod glad that it worked.  Im closing this for now.
