### ISSUE TITLE
daemon-apiserver-kicker freaking out for no apparent reason

### ISSUE THREAD

**Issue by johngrabner** [ubuntu/microk8s#2241]
Please run `microk8s inspect` and attach the generated tarball to this issue. **Included below.**

We appreciate your feedback. Thank you for using microk8s.

Got 2 of these messages in 2095/inspection-report/snap.microk8s.daemon-apiserver-kicker over the past hour:
```
May 05 07:40:08 john-trx40-designair systemd[1]: Stopping Service for snap application microk8s.daemon-apiserver-kicker...
May 05 07:40:08 john-trx40-designair systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver-kicker.
May 05 08:00:43 john-trx40-designair systemd[1]: Started Service for snap application microk8s.daemon-apiserver-kicker.
```
and mySQL app was restarted 2 times in this period.  Note, MySQL app is rock solid so it is microk8s failing.

Also get 12 of these per hour. Does not appear healthy.

```
May 05 08:45:08 john-trx40-designair microk8s.daemon-apiserver-kicker[61683]: Signature ok
May 05 08:45:08 john-trx40-designair microk8s.daemon-apiserver-kicker[61683]: subject=/CN=front-proxy-client
May 05 08:45:08 john-trx40-designair microk8s.daemon-apiserver-kicker[61683]: Getting CA Private Key
May 05 08:45:08 john-trx40-designair microk8s.daemon-apiserver-kicker[61683]: unable to write 'random state'
May 05 08:45:08 john-trx40-designair microk8s.daemon-apiserver-kicker[61683]: CSR change detected. Reconfiguring the kube-apiserver
```

[inspection-report-20210505_145749.tar.gz](https://github.com/ubuntu/microk8s/files/6430015/inspection-report-20210505_145749.tar.gz)

In the past, when microk8s restarted my pods once per day, I was told to stop the kicker.  Not sure what changed, but now restart of all pods rate is per hour not per day and this solution fails as follows:

```
$ systemctl stop snap.microk8s.daemon-apiservice-kicker
Failed to stop snap.microk8s.daemon-apiservice-kicker.service: Unit snap.microk8s.daemon-apiservice-kicker.service not loaded.
```

**Comment by johngrabner** [comment]
microk8s-resources/wrappers/apiservice-kicker appears to handle 5 consecutive failures.  My case appears to be a failure per hour. The question is what is failing?

I do not understand this code, how does 
`"$(produce_certs)"`
get a value?

**Comment by balchua** [comment]
Hi @johngrabner did you try adding to `/var/snap/microk8s/args/kube-apiserver` this argument `--bind-address=0.0.0.0`?

**Comment by johngrabner** [comment]
Thank you,
I reinstalled ubuntu and microk8s and forgot this line. Microk8s stable for 3hr now. So will assume it was the problem.
