### ISSUE TITLE
Clustering with MicroK8s not working

### ISSUE THREAD

**Issue by ChrisEdel** [ubuntu/microk8s#2248]
Hi!

Joining two nodes does not seem to work. 

I installed `microk8s` on two different servers running Ubuntu 20.04 LTS via `sudo snap install microk8s --classic --channel=1.21/stable` (following the official installation guide: https://microk8s.io/docs). I also tried it without an explicit channel, version 1.19, ...

After installing, both installations run fine (checked via `microk8s status --wait-ready` and `microk8s kubectl get pods -A`).

According to the official docs (https://microk8s.io/docs/clustering) that should be sufficient in order to create a cluster.

So, I run `microk8s add-node` on the (master) server and the given `microk8s join <ip>:<port>/<key>` on the other server. Then it says `Contacting cluster at <ip>` (after a while it says `Connection failed. (500)`). However, as soon as I execute the `microk8s join <ip>:<port>/<key>` command on the second server, `microk8s` seems to crash on the first/master server. For example, executing `microk8s kubectl get pods -A` on the first server does not work anymore - `The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?` - even though before that it worked perfectly fine.

Is there something I'm missing? This should be easily reproducible since I just installed two fresh versions without modifying anything.

**Comment by ChrisEdel** [comment]
This might be the issue, I will look into that (might take till the beginning of next week) and let you know if that helps. Thanks a lot for pointing that out!

**Comment by ChrisEdel** [comment]
Hi @balchua!

I have opened all the ports (on the master as well as on the other server) and it is still not working. As soon as the one node is trying to connect, the master crashes with `The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?`.

Honestly, I don't know what to try anymore. Is there anything else you can suggest?

**Comment by balchua** [comment]
Can you upload the inspect tarball here? Both the main node and the node you want to join the cluster.
Thanks

**Comment by balchua** [comment]
Yes definitely thats the issue. 19001 is the port used by dqlite to talk to other dqlites.

**Comment by balchua** [comment]
Not sure what can be done but i will first check if the 19001 port is already used.

**Comment by ktsakalozos** [comment]
> Both the master and the node that wants to join are behind a NAT, but port forwarding was enabled.

Are they behind the same NAT or different NATs? (Stupid question, just making sure)

**Comment by ChrisEdel** [comment]
They are behind different NATs. But that should also be possible, right?

**Comment by ChrisEdel** [comment]
Alright, that makes sense. Thanks a lot!
