### ISSUE TITLE
Question: How to get temperature information from Raspberry Pi into MicroK8S Prometheus

### ISSUE THREAD

**Issue by KiqoCode** [ubuntu/microk8s#2258]
Hi,

I have installed prometheus and grafana into my microk8s cluster using the microk8s enable command.
By default temperature sensor data is not being monitored it seems like. 

How to enable that? 

Best Regards
Kiqo

**Comment by balchua** [comment]
I thought the metrics `node_hwmon_...` is default.

**Comment by KiqoCode** [comment]
I didn't get it atleast.. Anyway I can add it?

**Comment by balchua** [comment]
I thought its a default on rpi.

**Comment by KiqoCode** [comment]
Can I add it since it seems to be missing?

**Comment by balchua** [comment]
Looking at the node-exporter `DaemonSet` it looks like gathering `hwmon` is disabled.

If you go and do a `kubectl -n monitoring edit ds node-exporter` you will see that the args has this `--no-collector.hwmon`.  Try removing that and see if the node exporter starts to scrape these metrics.

**Comment by KiqoCode** [comment]
That worked! Thanks a lot! =)
