### ISSUE TITLE
SyntaxError when running `microk8s disable kubeflow`

### ISSUE THREAD

**Issue by mbunse** [ubuntu/microk8s#2263]
After a clean install of microk8s and kubeflow I get the following error when disabling kubeflow:
```
$ microk8s disable kubeflow  File "/snap/microk8s/2143/scripts/wrappers/common/../../../actions/disable.kubeflow.sh", line 52
    click.echo(f"Destroying Kubeflow {resource}...")
                                                  ^
SyntaxError: invalid syntax
```

Result of `microk8s inspect` :
[inspection-report-20210513_135822.tar.gz](https://github.com/ubuntu/microk8s/files/6472317/inspection-report-20210513_135822.tar.gz)

**Comment by DomFleischmann** [comment]
We have fix for this in edge and it should be released in the next days to stable

**Comment by DomFleischmann** [comment]
I'm sorry I was wrong, this fix wasn't in edge yet. If you want to disable kubeflow manually you can execute this command:
`microk8s juju kill-controller uk8s`.
