### ISSUE TITLE
Containerd stalls when starting MicroK8s on lxd

### ISSUE THREAD

**Issue by balchua** [ubuntu/microk8s#2265]
## Context

Starting MicroK8s on a newly booted lxd (the host is not rebooted), containerd fails to start on time then restart, causing kubelite to go on crashloop.

## Steps to reproduce
1. Install MicroK8s on Lxd.
2. Stop MicroK8s inside the lxd container.
3. Stop the lxd container.  `lxc stop <container name>`
3. Start the lxd container.  `lxc start <container name>`.
4. Start MicroK8s.

You will notice that microk8s isn't starting and containerd stalls while booting up.

This is similar to this issue https://github.com/ubuntu/microk8s/issues/2071

But since the lxd container shares the `/proc` with the host, it never detects that it should do the cleanup.

**Comment by ktsakalozos** [comment]
Thank you for reporting this @balchua . A fix is on its way. When in an lxc container we will be looking at the stats of /proc/1 instead of /proc/stats to see if we just booted.
