### ISSUE TITLE
FR: please add kiali in the istio instalation

### ISSUE THREAD

**Issue by c0ff3e** [ubuntu/microk8s#227]
Feature request:
There is a super nice tool included in istio that called kiali, it is visualizing the traffic in istio.
Please add it to the istio app.

**Comment by mattthym** [comment]
+1

**Comment by evgkarasev** [comment]
Please could you please at least add instructions how to add Kiali with helm! Thanks!

**Comment by antweiss** [comment]
AFAIK kiali won't work with Istio v1.0.5 as included in microk8s by default

**Comment by ktsakalozos** [comment]
Istio has a helm chart that can be configured to also install kiali https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L82 . We may want to refactor our `microk8s.enable istio` script at https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.istio.sh to make use of that installtion method.

**Comment by ktsakalozos** [comment]
We just upgraded istio to 1.2.2 and kiali is included by default. Have a look:
```
sudo snap install microk8s --channel=edge --classic
```
It should reach stable soon. 

Please reopen if you find any issues. Thanks.

**Comment by chauffer** [comment]
@ktsakalozos Thank you very much! How is it being installed now? I'd like to install it the same way microk8s is doing it without upgrading to edge, but I cannot find it [on the script you linked above](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.istio.sh).

**Comment by ktsakalozos** [comment]
@chauffer unfortunately it is not trivial to run the install script manually. If you do not want to witch to edge you should wait for the edge snap to be promoted to stable.
