### ISSUE TITLE
microk8s 1.21/stable failes to start. daemon-kubelite. Error iptables permission Denied.

### ISSUE THREAD

**Issue by frederikpietzko** [ubuntu/microk8s#2272]
When trying to start microk8s on my ubuntu 18.04 its fails.
I tried it on 2 different machines. On both machines (one a fresh install) the service snap.microk8s.daemon-kubelite fails to start. 
When inspecting those with 
`sudo journalctl -u snap.microk8s.daemon-kubelite`
and locate the error message it looks like this: 
/snap/microk8s/2210/run-kubelite-with-args: Line 168: /proc/sys/net/bridge/bridge-nf-call-iptables: No Permission

I am pretty new to microk8s and would appreciate some help since I'm kinda stuck here.

[inspection-report-20210518_150748.tar.gz](https://github.com/ubuntu/microk8s/files/6501523/inspection-report-20210518_150748.tar.gz)

**Comment by balchua** [comment]
Hi do you happen to be running in **strato**?
We have users reporting problems when running on strato such as https://github.com/ubuntu/microk8s/issues/893#issue-comment-box
As well as this https://github.com/k3s-io/k3s/issues/1236

**Comment by frederikpietzko** [comment]
Yes i am. Well shit. I guess ill have to use docker-compose for now or switch providers at some point.
