### ISSUE TITLE
Calico wireguard not working

### ISSUE THREAD

**Issue by hokamc** [ubuntu/microk8s#2275]
I followed the guide from [calico wireguard tutorial](https://www.projectcalico.org/introducing-wireguard-encryption-with-calico/). But, there is still no wireguard public key found. So, I wonder whether microk8s need special config for this case.

**Comment by balchua** [comment]
Its likely due to the version (3.13) of calico currently in MicroK8s.  There's an ongoing PR to upgrade it https://github.com/ubuntu/microk8s/pull/2081.  so far it is incomplete.
@ktsakalozos do you think its time to update calico to have better support for wireguard?

**Comment by ktsakalozos** [comment]
We have not planned for such an upgrade but the respective PR gets into a better state and is of low risk we can include it in the next release.

**Comment by hokamc** [comment]
Looking forward to include the PR in the next release. I think this is a important feature.
