### ISSUE TITLE
Group readable warning generates error.

### ISSUE THREAD

**Issue by ricknjacky** [ubuntu/microk8s#2281]
I am new to microservices & K8s in general. I have been using microk8s as my main and only distribution for over a month now. 
Whenever I used `microk8s helm` or `microk8s kubectl` command, I used to get the following warning.
`Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2210/credentials/client.config` I pretty much ignored this but recently while I was running an app, my app crashed mid-way through as the app noticed this warning and generated the following error.

`Error installing deployment OperationalError: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2210/credentials/client.config `

I searched for this issue and found a fix for the same [here](https://github.com/helm/helm/issues/8776#issuecomment-742607909) but it doesn't obviate the issue for me instead the cluster is unreachable and permission denied error is generated. 

ps:- As mentioned already, I wasn't able to run microk8s helm3 and microk8s kubectl after the solution mentioned above. but after i changed the user-permissions to group  readable using 

`chmod g+r /var/snap/microk8s/2210/credentials/client.config`
I was able to use the aforementioned commands but obviously with the warning.

TarBall:- 
[inspection-report-20210521_212754.tar.gz](https://github.com/ubuntu/microk8s/files/6523863/inspection-report-20210521_212754.tar.gz)

Any leads on where did I get it all wrong and how to obviate this would really mean a lot. Thanks

ps:- groups on my local system:-
jacky adm cdrom sudo dip plugdev lpadmin lxd sambashare microk8s

**Comment by balchua** [comment]
@ricknjacky that warning is benign.  What i normally do is to export `kubeconfig` from MicroK8s to say `~/mk8s/config`.  Like this `microk8s config > $HOME/mk8s/config` and then `export KUBECONFIG=$HOME/mk8s/config`.

Then i install a standalone kubectl, `snap install kubectl --classic` same with `helm`.

Why i do this, i find the standalone kubectl gives better bash completion.  I usually leave the `client.config` inside MicroK8s alone.

**Comment by ricknjacky** [comment]
thx i fixed it.
