### ISSUE TITLE
microk8s.status: command not found

### ISSUE THREAD

**Issue by Lawouach** [ubuntu/microk8s#229]
Hey all,

I can't figure what I'm doing wrong:

```
$ snap --version
snap    2.36.1
snapd   2.36.1
series  16
ubuntu  18.04
kernel  4.15.0-39-generic

$ snap install microk8s --classic
microk8s v1.12.2 from Canonical✓ installed

$ microk8s.status --wait-ready
microk8s.status: command not found

$ microk8s.<TAB>
microk8s.config    microk8s.docker    microk8s.inspect   microk8s.kubectl   
microk8s.disable   microk8s.enable    microk8s.istioctl  microk8s.reset 
```

Actually neither do microk8s.start and stop.

Those are front and center in the documentation so I'm puzzled. Have they disappear?

**Comment by tvansteenburgh** [comment]
Hi @Lawouach, turns out those features haven't quite made it to the stable channel yet. If you want them early you can refresh to the beta channel like this:
```
snap refresh microk8s --beta
```

**Comment by Lawouach** [comment]
I see! Thanks @tvansteenburgh. That means I'm not insane :p 

Unless I've missed it, maybe a short mention in the readme?

**Comment by tvansteenburgh** [comment]
You're right @Lawouach, it was a mistake not clarifying that in the docs. The good news is that MicroK8s 1.13 was just released, so all of those features are now in the stable branch.

Thanks for reporting this, we'll be more careful next time. :)

**Comment by Lawouach** [comment]
Awesome! Congrats :)
