### ISSUE TITLE
Additional setup when enabling gpu (avoid the crash loop)

### ISSUE THREAD

**Issue by treo** [ubuntu/microk8s#2290]
I've spent an entire day trying to debug why enabling the GPU on 1.21 on Ubuntu 20.04 resulted in a crash loop. 

I tried different versions of the gpu operator by modifying the enable.gpu.sh script, and I looked at a lot of logs. 

In the end this issue had the solution: https://github.com/NVIDIA/gpu-operator/issues/173#issuecomment-804836922

For completeness sake:
```
# Update /etc/systemd/system/multi-user.target.wants/snap.microk8s.daemon-containerd.service
- Restart=on-failure
- Type=simple
+ Restart=always
+ Type=notify
+ Delegate=yes
+ KillMode=process

sudo systemctl daemon-reload
sudo systemctl restart snap.microk8s.daemon-containerd
```

As I expect that more people may run into this particular problem, it would be nice to document this in the troubleshooting section.

**Comment by ktsakalozos** [comment]
Thank you for reporting this. There is some work we need to do before we support this form of `Type=notify` `KillMode=process` daemon.

The problem we face is that when the snap refreshes any pods mounting parts of the SNAP_DATA directory (`/var/snap/microk8s/current/...`) need to be recreated. The most important of the pods that need a restart is the calico ones. So, if in the future you see your deployment failing after a refresh make sure you try killing the calico pods.

**Comment by treo** [comment]
Just to make sure I understood this correctly:

With the necessary changes (`Type=notify` `KillMode=process`), I should stop Microk8s on the node, do the refresh, and only start it again afterwards, because some pods (esp. the calico ones) need to remount their mounts in the `/var/snap/microk8s/current` directory.

**Comment by ktsakalozos** [comment]
Let me first explain what happens during a refresh. If you list the contents of `/var/snap/microk8s/` you will see one or more directories named after MicroK8s revisions and a symlink (current) pointing to the current revision. Here is an example:
```
ls -lh /var/snap/microk8s/
total 11K
drwxr-xr-x 10 root root 10 May 28 08:01 2213
drwxr-xr-x  4 root root  4 May 28 08:01 common
lrwxrwxrwx  1 root root  4 May 28 08:01 current -> 2213
```
As soon as the next revision comes out, eg 2214 a new directory is created for that revision the current link points to this new 2214 revision and the old 2213 will get eventually removed. This is how snaps work. The CNI calico pod mounts a directories that are inside the revision it came with. The calico pod in the example above has mounted directories inside 2213. When 2214 comes out the calico pod needs to restart so it uses the directories from revision 2214. The current containerd daemon will restart all pods when it refreshes. The change you propose will not restart any pods so you will take care the calico pods restart yourself.  

I would suggest you schedule the refreshes to happen on a specific date, see [1], and have a mechanism to kubectl rollout restart the calico deployment.

[1] https://snapcraft.io/docs/keeping-snaps-up-to-date?&_ga=2.175367202.1003916964.1622042667-826334627.1586932956#heading--controlling-updates

**Comment by treo** [comment]
Thank you again for the in-depth explanation. I guess I understood half the cause of the problem (changing symlink), but I entirely forgot that snap does automatic refreshes.

**Comment by StianHanssen** [comment]
Hey, I seem to be running into the same issue and I tried to follow what was explained here, but to no avail. If possible, wold you mind giving a step by step of how to resolve this issue?

As of now, I have tried:
1. `microk8s disable gpu`
2. reboot
3.
```
# Update /etc/systemd/system/multi-user.target.wants/snap.microk8s.daemon-containerd.service
- Restart=on-failure
- Type=simple
+ Restart=always
+ Type=notify
+ Delegate=yes
+ KillMode=process

sudo systemctl daemon-reload
sudo systemctl restart snap.microk8s.daemon-containerd
```
4. `microk8s enable gpu`

Furthermore, I tried killing all the pods to including calico related pods, so that they would restart. Yet still `pod/nvidia-driver-daemonset-#####` goes into a crash loop with logs:
```

========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 460.73.01 for Linux kernel version 5.4.0-74-generic

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Could not unload NVIDIA driver kernel modules, driver is in use
Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Could not unload NVIDIA driver kernel modules, driver is in use
```

Any advice would be much appreciated

**Comment by treo** [comment]
> Could not unload NVIDIA driver kernel modules, driver is in use

This only works properly on systems where you don't have a UI running already and you may not have the drivers already installed on the system. If they are, you need to remove the installation and blacklist the nouveau driver. You absolutely want the card to be not in use already.

If you already have that situation, and it just can't unload the drivers from the container, try listing the nvidia related modules with `lsmod | grep nvidia` and unload them one by one with `rmmod`, (first it should be the two things that depend on the nvidia module, and then the nvidia module itself). If it tells you that the module is still in use, make sure X or gdm isn't running.

*If you need to have a GUI running at the same time or use the host systems drivers*, you should probably use microk8s version 1.20, as that is the default for that. 

Or if you feel adventurous, you can copy the `gpu.enable.sh` script from your microk8s installation, and modify the helm parameters for the gpu-operator (see https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/getting-started.html#chart-customization-options).  It does support using host drivers, but that way you don't get automatic driver installation when you add additional nodes, so I didn't dive into that too much. 

You'll need to define a few environment variables for the script to run directly (i.e. when it is not invoked via `microk8s enable ...`) but figuring them out is quite straight forward.

**Comment by treo** [comment]
A small update after running this for a few weeks:

As snap is auto updating AND replacing the changed config, this leads to crash loops again. It would be great if this got a proper resolution, as at the moment, GPU support in Microk8s is effectively broken.

**Comment by ktsakalozos** [comment]
The above PR should address this issue. As soon it gets merged a new snap should land on the latest/edge channel.
