### ISSUE TITLE
kube-proxy stops creating iptables rules after sometime

### ISSUE THREAD

**Issue by deejay104** [ubuntu/microk8s#2291]
I have deployed a microk8s 1.20/stable cluster with a mix of raspberry and intel-nuc.
It was working fine, but yesterday 2 nodes crashed. After restarting them, one of them was not able to resolve DNS.
Digging into it I found that iptables rules that should redirect services are missing on this node. If I do a "iptables-legacy  -t nat -L -n -v | grep SVC" nothing is return (which is not the case on the other nodes where I have the list of services).

I did not find any relevant logs or anything...

[inspection-report-20210526_234714.tar.gz](https://github.com/ubuntu/microk8s/files/6549865/inspection-report-20210526_234714.tar.gz)

**Comment by balchua** [comment]
@deejay104 just checking is the tarball from the same node where `kube-proxy` doesn't seem to work?  Do you mind uploading the inspect tarball of "working" node?
Thanks

**Comment by balchua** [comment]
I dont understand why calico is crashing.

```console
CALICO_NETWORKING_BACKEND is vxlan - no need to run a BGP daemon
Calico node started successfully
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x101b7bc]

goroutine 141 [running]:
github.com/projectcalico/felix/calc.(*VXLANResolver).OnResourceUpdate(0x400013ef60, 0x1ab7c60, 0x400035b6e0, 0x16ae640, 0x0, 0x4000904070, 0x6, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/vxlan_resolver.go:185 +0x28c
github.com/projectcalico/felix/dispatcher.updateHandlers.DispatchToAll(0x40005b4308, 0x1, 0x1, 0x1ab7c60, 0x400035b6e0, 0x16ae640, 0x0, 0x4000904070, 0x6, 0x0, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:45 +0x74
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdate(0x400000c900, 0x1ab7c60, 0x400035b6e0, 0x16ae640, 0x0, 0x4000904070, 0x6, 0x0, 0x0, 0x2, ...)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:102 +0x290
github.com/projectcalico/felix/dispatcher.(*Dispatcher).OnUpdates(0x400000c900, 0x40000e3720, 0x1, 0x1)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/dispatcher/dispatcher.go:80 +0xcc
github.com/projectcalico/felix/calc.(*AsyncCalcGraph).loop(0x400013f020)
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:150 +0x32c
created by github.com/projectcalico/felix/calc.(*AsyncCalcGraph).Start
	/go/pkg/mod/github.com/projectcalico/felix@v0.0.0-20200311115901-aa0a22d97c2d/calc/async_calc_graph.go:237 +0xb0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x101b7bc]
```

**Comment by deejay104** [comment]
Here are 2 inspect files, 1 from a working node and the other one from a non working node on which I have corrected the NodePort range settings (which did not solved the issue)

[working.tar.gz](https://github.com/ubuntu/microk8s/files/6551447/working.tar.gz)
[notworking.tar.gz](https://github.com/ubuntu/microk8s/files/6551448/notworking.tar.gz)

**Comment by deejay104** [comment]
And I just have seen that a new node in the cluster has the same issue.
On this node, no iptables redirection is working (either NodePort, services)

**Comment by balchua** [comment]
Hi @deejay104 I was looking at the 2 tarballs.  The one working is a 1.20 MicroK8s version.  While the "not working" tarball is a 1.21 MicroK8s version.

Is it intentional?  Try aligning the cluster to the same version like say `1.20/stable`.

**Comment by ktsakalozos** [comment]
@deejay104 looking at the kubeproxy arguments I see the userspace proxy mode is used. Could we try to switch to the default IPtable based mode?

To do this try to:
```
sudo modprobe br_netfilter
```
Remove the line `--proxy-mode=userspace` from `/var/snap/microk8s/current/args/kube-proxy` and restart microk8s.

I am not sure if this will address the problem, but in the past I have seen issues where the connectivity between nodes was failing due to the mode the proxy was working on.

**Comment by deejay104** [comment]
We had the issue with 1.20 and give a try to 1.21 with no luck.
I try to remove --proxy-mode=userspace and it seems to have solved the issue (no need to mobprobe br_netfilter)

I will see if that it keeps working.
Thanks for your help

**Comment by balchua** [comment]
Hi @deejay104 are you still experiencing the issue?

**Comment by deejay104** [comment]
Hi, the issue did not happened again. I have tried to re-install few nodes and it is still working.
I think we can close this case.
Thanks again for your help
