### ISSUE TITLE
microk8s is not running

### ISSUE THREAD

**Issue by bq1122** [ubuntu/microk8s#2300]
![image](https://user-images.githubusercontent.com/17918665/120074077-bf956600-c0cd-11eb-85f1-38f0e71605f5.png)

![image](https://user-images.githubusercontent.com/17918665/120074072-b6a49480-c0cd-11eb-96f2-c53e868c20ed.png)

[inspection-report-20210529_221113.tar.gz](https://github.com/ubuntu/microk8s/files/6564812/inspection-report-20210529_221113.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @bq1122 , are you behind a firewall of some kind? I see in the logs that containerd is not able to reach k8s.gcr.io:
```
5月 29 22:10:43 cdqpc microk8s.daemon-kubelite[4233]: E0529 22:10:43.070511    4233 kuberuntime_sandbox.go:68] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to get sandbox image \"k8s.gcr.io/pause:3.1\": failed to pull image \"k8s.gcr.io/pause:3.1\": failed to pull and unpack image \"k8s.gcr.io/pause:3.1\": failed to resolve reference \"k8s.gcr.io/pause:3.1\": failed to do request: Head \"https://k8s.gcr.io/v2/pause/manifests/3.1\": dial tcp 74.125.203.82:443: i/o timeout" pod="kube-system/calico-node-cqqrh"
```

**Comment by bq1122** [comment]
You're right. How can I solve this problem

**Comment by ktsakalozos** [comment]
You probably need a proxy.

**Comment by bq1122** [comment]
thanks
