### ISSUE TITLE
Error about sudo.conf while enabling gpu addon on CentOS 7

### ISSUE THREAD

**Issue by blavoie** [ubuntu/microk8s#2318]
Just installed microk8s on a fully updated CentOS 7 and get this error while activating GPU addon:

```
# microk8s enable gpu
Enabling NVIDIA GPU
sudo: error in /etc/sudo.conf, line 19 while loading plugin "sudoers_policy"
sudo: unable to load /usr/libexec/sudo/sudoers.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /snap/microk8s/2210/usr/lib/x86_64-linux-gnu/libgnutls.so.30)
sudo: fatal error, unable to load plugins
```

[inspection-report-20210603_114920.tar.gz](https://github.com/ubuntu/microk8s/files/6592871/inspection-report-20210603_114920.tar.gz)

**Comment by GuoLiuFang** [comment]
switch to root user `useradd microk8s -g microk8s`
after that executte `visudo` and append
`microk8s ALL=(ALL)   NOPASSWD: ALL`
`su - microk8s`
`microk8s enable gpu`
let me know if the advice work

**Comment by blavoie** [comment]
@GuoLiuFang 
All my tests were done by using the root user directly. 
Would you recommend to use an unprivileged/dedicated user lie microk8s?

I will test your advice as soon as I have a spare time

Thanks

**Comment by blavoie** [comment]
just retried and it worked, unable to reproduce, thanks for your help

**Comment by gilbertKorir** [comment]
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins


# here is mine help
