### ISSUE TITLE
Kubeflow is not available in mircok8s addons list

### ISSUE THREAD

**Issue by cturigioiu** [ubuntu/microk8s#2321]
I just installed microk8s 1.21 on my raspberry pi cluster. ( each node has ubuntu 20.04 )

When I tried to enable kubeflow addon, I received this error:

`Nothing to do for 'kubeflow'`

I noticed that kubeflow is not seen in addons list when I execute 'microk8s status':

>microk8s is running
>
>high-availability: yes
 > datastore master nodes: 192.168.1.211:19001 192.168.1.212:19001 192.168.1.213:19001
 > datastore standby nodes: none
>addons:
>  enabled:
 >   dashboard            # The Kubernetes dashboard
  >  dns                  # CoreDNS
  >  ha-cluster           # Configure high availability on the current node
  >  metrics-server       # K8s Metrics Server for API access to service metrics
 >   storage              # Storage class; allocates storage from host directory
 > disabled:
 >   helm                 # Helm 2 - the package manager for Kubernetes
 >   helm3                # Helm 3 - Kubernetes package manager
 >   host-access          # Allow Pods connecting to Host services smoothly
 >   ingress              # Ingress controller for external access
 >   linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
 >   metallb              # Loadbalancer for your Kubernetes cluster
 >   portainer            # Portainer UI for your Kubernetes cluster
 >   prometheus           # Prometheus operator for monitoring and logging
 >   rbac                 # Role-Based Access Control for authorisation
 >   registry             # Private image registry exposed on localhost:32000
 >   traefik              # traefik Ingress controller for external access

The output of 'microk8s inspect' seems to mention kubeflow, but I don't know if it is a problem or not.

>Inspecting Certificates
>Inspecting services
>  Service snap.microk8s.daemon-cluster-agent is running
 > Service snap.microk8s.daemon-containerd is running
 > Service snap.microk8s.daemon-apiserver-kicker is running
 > Service snap.microk8s.daemon-kubelite is running
>  Copy service arguments to the final report tarball
>Inspecting AppArmor configuration
>Gathering system information
 > Copy processes list to the final report tarball
 > Copy snap list to the final report tarball
 > Copy VM name (or none) to the final report tarball
 > Copy disk usage information to the final report tarball
 > Copy memory usage information to the final report tarball
 > Copy server uptime to the final report tarball
 > Copy current linux distribution to the final report tarball
 > Copy openSSL information to the final report tarball
 > Copy network configuration to the final report tarball
>Inspecting kubernetes cluster
 > Inspect kubernetes cluster
>Inspecting juju
>  Inspect Juju
>Inspecting kubeflow
>  Inspect Kubeflow

**Comment by balchua** [comment]
@cturigioiu thanks for using MicroK8s.

Yes the output is normal, since kubeflow is not available on `arm64` architecture.
