### ISSUE TITLE
Microk8s kubectl from Powershell

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [ubuntu/microk8s#2340]
Hey Canonical Team,

We have installed Microk8s on Windows Server 2016 with Virtualbox as vm driver and multipass is able to spin up a VM for Microk8s to run.
![image](https://user-images.githubusercontent.com/83000807/122060308-178cd600-ce0b-11eb-8783-00c4194b6cf7.png)

but we are not able to call Microk8s Kubectl from powershell directly, we had to login into the VM which multipass had created using below command and run our commands there. 
![image](https://user-images.githubusercontent.com/83000807/122060738-794d4000-ce0b-11eb-8a92-d0b88943e53b.png)

when we run microk8s kubectl directly from powershell we are getting timed out error. Is there anything which we are missing ? because in the official Microk8s docs also kubectl commands are being run directly on Powershell and results are being fetched. 

![image](https://user-images.githubusercontent.com/83000807/122061023-c0d3cc00-ce0b-11eb-8fb7-35d2c756e207.png)

Note: We are able to run just microk8s enable, start commands from powershell directly but not microk8s kubectl commands. We are running on AWS i3.metal instance and Windows 2016 base ami.
![image](https://user-images.githubusercontent.com/83000807/122061434-245df980-ce0c-11eb-9e1c-a4e58ddae1f5.png)

**Comment by Sam-Sundar-Apty** [comment]
`Update`

Hey Guys, 

So the issue was with VirtualBox, it was not letting host machine to ping the VM. 

Closing the issue.

**Comment by evilnick** [comment]
Thanks for reporting anyway @Sam-Sundar-Apty , Even though this isn't an issue with microk8s directly, I'm sure we can add something to the docs to help others avoid this problem

**Comment by Sam-Sundar-Apty** [comment]
Hey @evilnick,

Yeah. Not sure why multipass's instance was not visible directly on VirtualBox, had to run `miltipass list` to get the IP. 

Anyways a doc will help new users :)

**Comment by evilnick** [comment]
thanks, I will try to add some useful info. did you need to change any of the default settings for VirtualBox to get it working or was it just you needed the IP address?

**Comment by Sam-Sundar-Apty** [comment]
Hey @evilnick, I wanted the IP of VM which multipass created for my application.
