### ISSUE TITLE
Kibana is not available via proxy

### ISSUE THREAD

**Issue by s12v** [ubuntu/microk8s#2350]
I have followed documentation on https://microk8s.io/docs/addon-fluentd, but Kibana is not working via proxy with default configuration. The error is the following:
<img width="978" alt="Screenshot 2021-06-20 at 16 25 49" src="https://user-images.githubusercontent.com/1462574/122677896-a2dbe200-d1e4-11eb-9494-5bac2d3fc710.png">

##  Inspection Report

[inspection-report-20210620_142636.tar.gz](https://github.com/ubuntu/microk8s/files/6682506/inspection-report-20210620_142636.tar.gz)

**Comment by ktsakalozos** [comment]
@s12v as mentioned in your PR we updated the docs to reflect the change in the way to access kibana.

Setting SERVER_BASEPATH seems to allow us to access the kibana dashboard via kubectl proxy but not with port forwarding.

Thank you for reporting this and giving us the opportunity to clarify this point.
