### ISSUE TITLE
snapcraft.yaml depends on other projects' main branches

### ISSUE THREAD

**Issue by acnodal-tc** [ubuntu/microk8s#2356]
I work on a microk8s fork and twice now I've had build failures when I did a "snapcraft clean" followed by a "snapcraft snap". In both cases the problem was caused by one of microk8s' dependencies pushing a breaking change. I'm not an expert so I could be wrong but it looks to me like snapcraft.yaml depends on the main branch of these projects:
```
https://github.com/canonical/raft
https://github.com/sqlite/sqlite
https://github.com/canonical/dqlite
https://github.com/canonical/go-dqlite
https://github.com/ktsakalozos/go-migrator
```
This is annoying in development, but more importantly it means that I can build the same microk8s tomorrow and next week and they'll potentially have different dependencies built in.

Would you have any interest in a PR that pins those dependencies to specific commits? If so please LMK which branch and I'll take a look.

**Comment by acnodal-tc** [comment]
One mistake on my part - sqlite does have "source-tag: version-3.33.0".

**Comment by ktsakalozos** [comment]
Hi @acnodal-tc the projects we depend on the master are the ones we own so we are aware of what lands on master.

The go-migrator is a utility for interacting with dqlite and etcd and the go-dqlite, dqlite and raft make the dqlite datastore.

You are right that ideally we would build from a release tag but at this point the recommendation is to use the master branches so we get bug and performance fixes.

**Comment by acnodal-tc** [comment]
Got it, thanks, I'll close this issue.
