### ISSUE TITLE
microk8s status shows not running

### ISSUE THREAD

**Issue by huang12zheng** [ubuntu/microk8s#2364]
Please run `microk8s inspect` and attach the generated tarball to this issue.
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

Building the report tarball
  Report tarball is at /var/snap/microk8s/2262/inspection-report-20210625_084608.tar.gz
We appreciate your feedback. Thank you for using microk8s.

[inspection-report-20210625_084608.tar.gz](https://github.com/ubuntu/microk8s/files/6714866/inspection-report-20210625_084608.tar.gz)

**Comment by balchua** [comment]
It couldn't pull the pause container.

```
failed to pull image \\\"k8s.gcr.io/pause:3.1\\\": failed to pull and unpack image \\\"k8s.gcr.io/pause:3.1\\\": failed to resolve reference \\\"k8s.gcr.io/pause:3.1\\\": failed to do request: Head \\\"https://k8s.gcr.io/v2/pause/manifests/3.1\\\": dial tcp 108.177.97.82:443: i/o timeout\"" pod="kube-system/calico-node-vfx4c" podUID=6c33f5c4-13aa-4e86-a53f-ec037cb752f1
```
None of the pods can start without the pause container.

**Comment by huang12zheng** [comment]
thanks, I switch registry about pause. And it work.
