### ISSUE TITLE
Sporadic connection issues to kubelite-daemon on MacOS with multipass

### ISSUE THREAD

**Issue by sebastianwoinar** [ubuntu/microk8s#2365]
I want to run several services on microK8s with multipass on MacOS 11.2.3.

But the connection to microK8s seems to be pretty shaky.

When I `helm install` charts, I ran from time to time into errors like:
`Error: Get "https://192.168.64.2:16443/apis/apps/v1/namespaces/default/deployments/xyz": unexpected EOF`

After several attempts this passes usually.

When trying to connect with curl, I can see that the connection to the K8s API cannot be established there either.

Do I have to scale-up the vm more?

In the attached logs, you can see that the kubelite-daemon is crashing.

[snap.microk8s.daemon-kubelite.service.journal.zip](https://github.com/ubuntu/microk8s/files/6714947/snap.microk8s.daemon-kubelite.service.journal.zip)

**Comment by balchua** [comment]
Kubelite is crashing, but doesn't have enough information to know what's causing it to fail.

If you can upload the inspect tarball, and hopefully it can reveal something.

**Comment by sebastianwoinar** [comment]
What about the 

> Jun 25 10:08:30 microk8s-vm microk8s.daemon-kubelite[330985]: E0625 10:08:30.574441  330985 leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:16443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Isn't that the problem?

**Comment by balchua** [comment]
Aaaa its likely.
Care to try this?
https://github.com/ubuntu/microk8s/issues/2205#issuecomment-827208050

**Comment by sebastianwoinar** [comment]
@balchua thanks for the suggestions!
I tried to increase the timeout, but I still I run into errors.

Here are the details of the VM
```
Name:           microk8s-vm
State:          Running
IPv4:           192.168.64.2
Release:        Ubuntu 20.04.2 LTS
Image hash:     9dd5cb9f73c4 (Ubuntu 20.04 LTS)
Load:           3.87 1.39 0.50
Disk usage:     17.2G out of 38.6G
Memory usage:   826.2M out of 5.8G
```

**Comment by sebastianwoinar** [comment]
So, the issue with the leader-election may have been only minor.

**Comment by balchua** [comment]
Inside the microk8s-vm can you show the content of this directory?

`/var/snap/microk8s/current/var/kubernetes/backend`?

Was it always like this from the time you installed microk8s?
Thanks

**Comment by sebastianwoinar** [comment]
`/var/snap/microk8s/current/var` does not contain a directory for kubernetes

With a previous installation of microk8s it was not the case.
But since I scaled up the VM by recreating it from scratch, it started to become shaky.

Shall I re-install it again?

**Comment by balchua** [comment]
Thats so strange, that directory and the contents inside it is a must have.

At this point i have no idea why that directory doesn't exist in your setup after your reinstalled.
😭. 

@joedborg reinstalling MicroK8s on mac will remove all previous data right?

**Comment by sebastianwoinar** [comment]
I would delete the whole VM, so then all data is gone.

**Comment by balchua** [comment]
Yeah that's the easiest approach to go.

**Comment by sebastianwoinar** [comment]
It seems to be stable after reinstalling it with `microk8s install --mem 8` instead of creating the VM directly with multipass.

Thanks for your help!
