### ISSUE TITLE
CGroups 2 Warning

### ISSUE THREAD

**Issue by tlm** [ubuntu/microk8s#2384]
Hi Everyone,

I noticed after an upgrade to CGroups 2 that a fresh microk8s install fails to install the calico CNI plugin. I noticed that LXD has a warning around CGroups2 and was wondering if microk8s should have something similar to say it's not supported.

Thanks
tlm

**Comment by ktsakalozos** [comment]
Hi @tlm there is a PR under review https://github.com/ubuntu/microk8s/pull/2219 so we should have some new on this subject soon.

Would you be interested to give the patch a try and provide your feedback?

**Comment by ktsakalozos** [comment]
@tlm the cgroupV2 support just got merged. Within the day it should land on the latest/edge channel. You can give it a try with:
```
sudo snap install microk8s --classic --channel=latest/edge
```

**Comment by ktsakalozos** [comment]
Thank you
