### ISSUE TITLE
microk8s.kubectlget pods -n kube-public return empty

### ISSUE THREAD

**Issue by Yavdhesh** [ubuntu/microk8s#2387]
I have installed microk8s on a VM with centos 7

Name:               localhost.localdomain
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=localhost.localdomain
                    kubernetes.io/os=linux
                    microk8s.io/cluster=true
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 28 Jun 2021 14:53:05 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  localhost.localdomain
  AcquireTime:     <unset>
  RenewTime:       Mon, 28 Jun 2021 17:23:42 +0000
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Mon, 28 Jun 2021 17:21:05 +0000   Mon, 28 Jun 2021 14:53:05 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 28 Jun 2021 17:21:05 +0000   Mon, 28 Jun 2021 14:53:05 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Mon, 28 Jun 2021 17:21:05 +0000   Mon, 28 Jun 2021 14:53:05 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Mon, 28 Jun 2021 17:21:05 +0000   Mon, 28 Jun 2021 14:56:59 +0000   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.43.20
  Hostname:    localhost.localdomain
Capacity:
  cpu:                1
  ephemeral-storage:  30672248Ki
  hugepages-2Mi:      0
  memory:             3880392Ki
  pods:               110
Allocatable:
  cpu:                1
  ephemeral-storage:  29623672Ki
  hugepages-2Mi:      0
  memory:             3777992Ki
  pods:               110
System Info:
  Machine ID:                 524903c9ae55b046a8ab3f9dc063c9e0
  System UUID:                524903C9-AE55-B046-A8AB-3F9DC063C9E0
  Boot ID:                    dd93cda5-d820-4626-8ad6-61216e583a0b
  Kernel Version:             3.10.0-1160.31.1.el7.x86_64
  OS Image:                   CentOS Linux 7 (Core)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.2.5
  Kubelet Version:            v1.17.17

**Comment by Yavdhesh** [comment]
I followed these steps to install :
Steps:
sudo yum install epel-release
sudo yum install snapd
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap  (yaa /usr/libexec/snapd/snapd)
sudo snap install microk8s --classic --channel=1.17/stable

**Comment by balchua** [comment]
I think the namespace `kube-public` is always empty.  Maybe you can check with the `kube-system` namespace. Since you are using 1.17 you can try enabling the dns.  `microk8s enable dns` you should see coredns running.

**Comment by Yavdhesh** [comment]
Where do controller-manager, etcd, api-server, schedular run then?

**Comment by ktsakalozos** [comment]
The kusbernetes services are started as systemd services not self hosted. If you run a `microk8s inspect` you will see all the systemd services MicroK8s starts.

**Comment by Yavdhesh** [comment]
Understood. thank you :)
