### ISSUE TITLE
failed to get client config: stat /home/jenkins/.kube/config: no such file or directory

### ISSUE THREAD

**Issue by Yavdhesh** [ubuntu/microk8s#2388]
when I ran command 
  `stern -l run=pingpong`
I got err that says failed to get client config: stat /home/jenkins/.kube/config: no such file or directory
When I installed microk8s, I think such directory was not created.
Is there a way to generate such config file?

**Comment by balchua** [comment]
Yes `microk8s config > $HOME/.kube/config`

**Comment by Yavdhesh** [comment]
Got it, thank you :)
