### ISSUE TITLE
coredns and calico kube controller containers are not running

### ISSUE THREAD

**Issue by frendcarlo** [ubuntu/microk8s#2389]
after an update, i got this strange behaviour that some pods are no longer running, i've check the first what is wrong in kube-system namespace and found out that this coredns and calico kube controller containers are not running, though the pods are running.  i attached inspect report here 
[inspection-report-20210629_130720.tar.gz](https://github.com/ubuntu/microk8s/files/6732867/inspection-report-20210629_130720.tar.gz), can someone please point to me why this is not working and how to fix this?

**Comment by balchua** [comment]
Hi 
What kind of update happened?

I can see that the cluster isn't healthy.  Kube controller manager  and scheduler is timing out while trying to get a lock for leader election.  Results to kubelite panicking.

**Comment by frendcarlo** [comment]
sorry, it wasn't the update of ubuntu packages that causing the issue, because I ask our provider to rollback from last week wednesday and still we got this issue.   Any idea how i can restart or let the kube controller manager force to elect a particular node?

**Comment by frendcarlo** [comment]
i've ended up running microk8s.reset and remove microk8s, and install again. pity i can't figure out what exactly is happening and I can't point out which causes the whole cluster to be unstable.

**Comment by ktsakalozos** [comment]
@frendcarlo how many nodes you had on your cluster? I can see two, was there a third one?

In the logs I see entries such as:
```
Jun 29 13:05:32 d20 microk8s.daemon-kubelite[232941]: Trace[17491226]: [1.347179048s] [1.347179048s] END
Jun 29 13:05:32 d20 microk8s.daemon-kubelite[232941]: I0629 13:05:32.409622  232941 trace.go:205] Trace[1688598701]: "List" url:/api/v1/services,user-agent:kubectl.exe/v1.20.0 (windows/amd64) kubernetes/af46c47,client:127.0.0.1,accept:application/json,protocol:HTTP/2.0 (29-Jun-2021 13:05:31.062) (total time: 1347ms):
Jun 29 13:05:32 d20 microk8s.daemon-kubelite[232941]: Trace[1688598701]: ---"Listing from storage done" 1347ms (13:05:00.409)
```
Indicating the time it takes for an operation on the datastore to complete is rather high, maybe you should test/benchmark the performance of the disks serving `/var/snap/microk8s/current`.

Finally, I see a few:
```
Jun 29 13:05:32 d20 microk8s.daemon-kubelite[232941]: Trace[1688598701]: [1.347322423s] [1.347322423s] END
Jun 29 13:05:32 d20 microk8s.daemon-kubelite[232941]: I0629 13:05:32.465033  232941 trace.go:205] Trace[825322474]: "Get" url:/api/v1/namespaces/stacklight/services/prometheus-server,user-agent:kubectl/v1.18.15 (darwin/amd64) kubernetes/73dd5c8,client:127.0.0.1,accept:application/json,protocol:HTTP/2.0 (29-Jun-2021 13:05:30.387) (total time: 2077ms):
Jun 29 13:05:32 d20 microk8s.daemon-kubelite[232941]: Trace[825322474]: [2.077792668s] [2.077792668s] END
Jun 29 13:05:32 d20 systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=killed, status=11/SEGV
```
That may indicate data corruption, @MathieuBordere ?

**Comment by MathieuBordere** [comment]
@ktsakalozos the SEGV is not a good sign, but based on the output it's not possible to determine what's the cause. It does not mean that there is data corruption.

**Comment by MathieuBordere** [comment]
There are a lot of 
```
Jun 29 12:39:38 d20 microk8s.daemon-kubelite[193835]: goroutine 1411 [select, 1 minutes]:
Jun 29 12:39:38 d20 microk8s.daemon-kubelite[193835]: k8s.io/kubernetes/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).ttl.func1(0x69b09d0, 0xc000c781c0, 0xc000ec0d50, 0xc000f3c260, 0xc001998918)
Jun 29 12:39:38 d20 microk8s.daemon-kubelite[193835]:         /build/microk8s/parts/k8s-binaries/build/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go:301 +0xc5 
```
goroutines in the logs, is this expected?

**Comment by frendcarlo** [comment]
thanks for the response, during the time that this problem occur's I have 2 nodes running (master and joining node), yesterday I create another node and let it join to master just to enable HA so that I can terminate master and make other node as master, but after this newly created node joined to master, everything is no longer working, if I run microk8s.status, i got microk8s not running on all nodes, tried microk8s.inspect, says that all service are running.  I tried running datastore backup but everything fails, since there's nothing i can do to proceed, i end up resetting, removing and install again with latest/stable build.
