### ISSUE TITLE
Failed to reach apiserver error in crd.projectcalico.org/v1/clusterinformation/default

### ISSUE THREAD

**Issue by frendcarlo** [ubuntu/microk8s#2390]
I got this error in calico-kube-controller logs, don't know why i keep getting this, can you please help me where to fix this? 

main.go 234: Failed to reach apiserver error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded
2021-06-30 06:20:31.448 [ERROR][1] client.go 255: Error getting cluster information config ClusterInformation="default" error=Get https://10.152.183.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default: context deadline exceeded

[inspection-report-20210630_073534.tar.gz](https://github.com/ubuntu/microk8s/files/6738934/inspection-report-20210630_073534.tar.gz)

Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by ktsakalozos** [comment]
Hi @frendcarlo , I am looking at this: https://github.com/projectcalico/libcalico-go/issues/1267

If you `microk8s.kubectl delete` the  calico-kube-controller pod does the new pod display the same behavior?

**Comment by frendcarlo** [comment]
hi, yeah, i have tried deleting the pod, and still got that error. It seems like I fix the problem, it wasn't the calico causing the issue, the issue is about the mount folder which is using nfs.  Looks like the mount volume is not working, that's why all those errors are shown, after I fix the nfs volume, restart master node, errors are gone.
