### ISSUE TITLE
curl http://littletomcat.default:8080 curl: (6) Could not resolve host: littletomcat.default [Centos 7 VM]

### ISSUE THREAD

**Issue by Yavdhesh** [ubuntu/microk8s#2391]
I have followed these steps:
1) k create deployment littletomcat --image=tomcat
2) kubectl create service clusterip littletomcat --tcp 8080
3) k apply -f https://bret.run/shpod.yml
4) kubectl attach --namespace=shpod -it shpod

4th command opens up a shell, then I try to curl littletomcat service on 8080, but that does not resolve
 
[192.168.43.20] (kubernetes:default) root@shpod ~
$ curl http://littletomcat.default:8080
curl: (6) Could not resolve host: littletomcat.default
[192.168.43.20] (kubernetes:default) root@shpod ~

Also, littletomcat service has clusterIP: 10.152.183.149

[192.168.43.20] (kubernetes:default) root@shpod ~
$ curl 10.152.183.149:8080
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.48</h3></body></html>[192.168.43.20] (kubernetes:default) root@shpod ~

I am puzzledas to why DNS name is not resolved, but IP works.

[inspection-report-20210629_100032.tar.gz](https://github.com/ubuntu/microk8s/files/6740111/inspection-report-20210629_100032.tar.gz)

**Comment by balchua** [comment]
Coredns isnt ready.
Can you check if the troubleshooting guide here
https://microk8s.io/docs/troubleshooting#heading--common-issues if it resolves your issue?
There's a section there about dns.

**Comment by Yavdhesh** [comment]
okay,sure. I will check. thank you.

**Comment by Yavdhesh** [comment]
I checked, it did not work.
when I run :  `k describe pod/coredns-9b8997588-jmslx -n kube-system`
```
Events:
  Type     Reason     Age                 From                            Message
  ----     ------     ----                ----                            -------
  Normal   Scheduled  16m                 default-scheduler               Successfully assigned kube-system/coredns-9b8997588-jmslx to localhost.localdomain
  Normal   Pulled     16m                 kubelet, localhost.localdomain  Container image "coredns/coredns:1.5.0" already present on machine
  Normal   Created    16m                 kubelet, localhost.localdomain  Created container coredns
  Normal   Started    16m                 kubelet, localhost.localdomain  Started container coredns
  Warning  Unhealthy  61s (x91 over 16m)  kubelet, localhost.localdomain  Readiness probe failed: HTTP probe failed with statuscode: 503

```

**Comment by Yavdhesh** [comment]
Following steps worked for me.
```
systemctl stop firewalld
pkill -f firewalld
```
```
microk8s.disable dns
microk8s.enable dns
```
`systemctl start firewalld`

**Comment by balchua** [comment]
Any firewall enabled?

**Comment by Yavdhesh** [comment]
```
systemctl stop firewalld
 pkill -f firewalld

 microk8s.disable dns
 microk8s.enable dns

 systemctl start firewalld
```
I tried these and it worked.

**Comment by balchua** [comment]
What happens if coredns restarts? Will the firewalld block it again?  Thanks

**Comment by Yavdhesh** [comment]
@balchua okay, let me try this case.

**Comment by Yavdhesh** [comment]
@balchua , it we restart a core-dns pod, then the pod does not start.

for example, there was already a pod running and I ran the following command:

`kubectl rollout restart -n kube-system deployment/coredns`



```
-bash-4.2$ pods -n kube-system
coredns-64bb89cd49-njz9b   0/1     Running   0          5m6s
coredns-9b8997588-clnpr    1/1     Running   0          11m
```
First pod kept running, but second one was still not running. I think, I have to again stop firewalld process until the pod starts.

**Comment by balchua** [comment]
In short you need to configure firewalld, which i am not able to help there. 🙁

I am going to close this issue since we have already identified that firewalld is the one affecting coredns from starting.

**Comment by Yavdhesh** [comment]
But I think, it should be taken care off when we run microk8s enable dns because when we run such command we agree modification to our firewall settings.
How about that?

**Comment by balchua** [comment]
I don't think its the scope of MicroK8s or kubernetes to implicitly restart the firewalld.
It may cause side effect used by other parts of the system.
Imho, it should be a conscious decision by the administrator.

**Comment by Yavdhesh** [comment]
okay. Understood.
