### ISSUE TITLE
Not allowed to execute on .enable dns or istio

### ISSUE THREAD

**Issue by vromero** [ubuntu/microk8s#240]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
Can't inspect doesn't work either:
```
microk8s.inspect
Sorry, user vromerocarrasco is not allowed to execute '/snap/microk8s/340/inspect.sh' as root on vromerocarr-ltl.
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

```
microk8s.enable istio
Enabling Istio
Enabling DNS
Applying manifest
service/kube-dns unchanged
serviceaccount/kube-dns unchanged
configmap/kube-dns unchanged
deployment.extensions/kube-dns configured
Restarting kubelet
Sorry, user vromerocarrasco is not allowed to execute '/snap/microk8s/340/bin/sed -i $ a --cluster-domain=cluster.local /var/snap/microk8s/340/args/kubelet' as root on vromerocarr-ltl.
Failed to enable dns
Failed to enable istio
```

**Comment by ktsakalozos** [comment]
Hi @vromero

Thank you for opening this issue. Can you make sure you are a sudoer https://askubuntu.com/questions/7477/how-can-i-add-a-new-user-as-sudoer-using-the-command-line , https://forums.linuxmint.com/viewtopic.php?t=217505 ?

MicroK8s includes a number of systemd services. Commands such as `microk8s.enable dns` need to configure and restart those systemd services. For this you need elevated privileges. As soon as you become a sudoer the failing commands will prompt you for your password.

**Comment by vromero** [comment]
You are definitely right, I tried this in a vanilla ubuntu (as opposed to a corporate computer) at worked great. Thanks.
