### ISSUE TITLE
Hanging Status with Installation

### ISSUE THREAD

**Issue by Magnesia89** [ubuntu/microk8s#2401]
[inspection-report-20210629_125029.tar.gz](https://github.com/ubuntu/microk8s/files/6757422/inspection-report-20210629_125029.tar.gz)

Any help would be appreciated. Thanks!

**Comment by balchua** [comment]
Hi @Magnesia89 i can see that your hostname contains capital letters.

Kubernetes will normalize it to all small characters, and it will not be able to register the node into the cluster.
Can you change your hostname to contain only small letters?  
Followed by removing microk8s with `sudo snap remove microk8s --purge`. And then install it again.

**Comment by Magnesia89** [comment]
Hi @balchua, I've done this and fixed the issue with the daemon file so that the inspect command doesn't show any warnings, but the issue still remains. Here is the new inspection report if that helps any more. 

[inspection-report-20210707_101148.tar.gz](https://github.com/ubuntu/microk8s/files/6778339/inspection-report-20210707_101148.tar.gz)
