### ISSUE TITLE
feature:show details result in command inspect if pull is unsuccessful

### ISSUE THREAD

**Issue by huang12zheng** [ubuntu/microk8s#2403]
I checked inspect.sh -- suggest_fixes
I think the addition of this boundary case will be helpful to the beginner of K8s

ref to #2364

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @huang12zheng 

It make sense for the inspection script to check that the public registries we use by default are reachable and offer suggested fixes.

[1] https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh#L125

**Comment by huang12zheng** [comment]
I'm sorry it took so long,
One is fear of microk8s,
The other thing is I don't know how to deal with CLA.

although, It's all a bit silly though
