### ISSUE TITLE
MicroK8s on RHEL 8.4: No route to host. DNS and network not working.

### ISSUE THREAD

**Issue by wutkemtt** [ubuntu/microk8s#2407]
We are trying to get MicroK8s running on an RHEL 8.4, but we are not able to get a network connection to the host network to work. As far as we can see, this may be related to [Issue 2180](https://github.com/ubuntu/microk8s/issues/2180). 
Attached the inspection tarball.
We found the following log entries in CoreDNS: 
`.:53
[INFO] plugin/reload: Running configuration MD5 = 77146f3733bc5dcc5eede05600502bbb
CoreDNS-1.8.0
linux/amd64, go1.15.3, 054c9ae
[INFO] 127.0.0.1:52791 - 16160 "HINFO IN 8205547723647174745.7315565847418319427. udp 57 false 512" NOERROR - 0 0.000224503s
[ERROR] plugin/errors: 2 8205547723647174745.7315565847418319427. HINFO: read udp 10.1.90.3:41011->8.8.4.4:53: read: no route to host
[INFO] 127.0.0.1:34174 - 4174 "HINFO IN 8205547723647174745.7315565847418319427. udp 57 false 512" NOERROR - 0 6.002367794s
[ERROR] plugin/errors: 2 8205547723647174745.7315565847418319427. HINFO: read udp 10.1.90.3:47962->10.160.80.21:53: i/o timeout
[INFO] 127.0.0.1:34772 - 32018 "HINFO IN 8205547723647174745.7315565847418319427. udp 57 false 512" NOERROR - 0 4.00095142s
[ERROR] plugin/errors: 2 8205547723647174745.7315565847418319427. HINFO: read udp 10.1.90.3:41281->10.160.80.21:53: read: no route to host`

The inspection command showed something about legacy iptables rules, but RHEL 8.4 is using nft:
`Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

# Warning: iptables-legacy tables present, use iptables-legacy to see them`

[inspection-report-20210706_051320.tar.gz](https://github.com/ubuntu/microk8s/files/6767580/inspection-report-20210706_051320.tar.gz)

**Comment by polyedre** [comment]
It seems that you are using flannel. Did you switch from calico to flannel ?

**Comment by wutkemtt** [comment]
Yes, we installed a fresh Microk8s v1.21/stable and disabled the ha-cluster addon. We tried with the ha-cluster option enabled, but we were not able to get it running. 
Finally we found the reason for the dns problem: 
We needed to enable ip masquerading for the host network interface via firewall-cmd. After this configuration we were able to resolve all hosts from within the cluster.

**Comment by Sam-Sundar-Apty** [comment]
> Yes, we installed a fresh Microk8s v1.21/stable and disabled the ha-cluster addon. We tried with the ha-cluster option enabled, but we were not able to get it running. Finally we found the reason for the dns problem: We needed to enable ip masquerading for the host network interface via firewall-cmd. After this configuration we were able to resolve all hosts from within the cluster.

Hi @wutkemtt,

Can you let us know how the issue was solved ? Also the command used for masquerading ?

**Comment by natanhp** [comment]
@Sam-Sundar-Apty You can use `firewall-cmd`
```bash
firewall-cmd --add-masquerade --permanent
firewall-cmd --reload
```
Source: https://stackoverflow.com/a/68214965/11725252
