### ISSUE TITLE
Cannot push more than 3 images to Containerd

### ISSUE THREAD

**Issue by sousarmb** [ubuntu/microk8s#2412]
Cannot push more than 3 images to Containerd, they are silently deleted after that or after some time.

Cannot get the inspect tarbal because microk8s instance is in a remote server to which i only have shell access.

**Comment by joedborg** [comment]
Is there anything in the containerd logs that show images being deleted?

**Comment by sousarmb** [comment]
How can i check the containerd logs? (complete noob here)
I know the images are delete because when i run `microk8s ctr image ls` the images are no longer there after 3 pushes.

**Comment by sousarmb** [comment]
I am push to local built-in registry, and have set it up with 40Gb. The images don't take that much space.

**Comment by sousarmb** [comment]
When i run `kubectl logs pod/registry-9b57d9df8-fhdfc -n container-registry` i get lines:

time="2021-07-06T17:42:06Z" level=info msg="PurgeUploads starting: olderThan=2021-06-29 17:42:06.116293463 +0000 UTC m=+1123380.078302377, actuallyDelete=true" 

time="2021-07-06T17:42:06Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=1" 

time="2021-07-06T17:42:06Z" level=info msg="Starting upload purge in 24h0m0s" go.version=go1.10 instance.id=0ad80b9f-e820-4d3f-89c2-292e9fd2665e version="v2.6.0+unknown" 

time="2021-07-07T17:42:06Z" level=info msg="PurgeUploads starting: olderThan=2021-06-30 17:42:06.116824571 +0000 UTC m=+1209780.078833593, actuallyDelete=true" 

time="2021-07-07T17:42:06Z" level=info msg="Purge uploads finished.  Num deleted=0, num errors=1" 

time="2021-07-07T17:42:06Z" level=info msg="Starting upload purge in 24h0m0s" go.version=go1.10 instance.id=0ad80b9f-e820-4d3f-89c2-292e9fd2665e version="v2.6.0+unknown"

**Comment by sousarmb** [comment]
I keep experimenting:

Build the image with `docker build -f dockerfile-cacheone -t enterprise-cacheone:${BRANCHES[0]} --build-arg GIT_USER=${USERS[0]} --build-arg GIT_DEPLOY_TOKEN=${TOKENS[0]} --build-arg GIT_DEPLOY_BRANCH=${BRANCHES[0]} .`

Save it with `docker save enterprise-cacheone:${BRANCHES[0]} >enterprise-cacheone.${BRANCHES[0]}.tar`

Import to containerd with `microk8s ctr image import enterprise-cacheone.${BRANCHES[0]}.tar`

Remove it from docker (save space on remote host) with `docker image rm enterprise-cacheone:${BRANCHES[0]}`

Remove .tar from filesystem with `rm -f enterprise-cacheone.${BRANCHES[0]}.tar`

**Comment by sousarmb** [comment]
I observed another behaviour: i'm running a bash script to build and push 6 images into the local registry, some builds take about 3-7 minutes. If in that time span the scipt asks for my user password, all previously built images disappear from containerd. I check containerd with `microk8s ctr images list -q`
