### ISSUE TITLE
apiserver blocked when running microk8s with ufw (or any firewall?) enabled

### ISSUE THREAD

**Issue by ca-scribner** [ubuntu/microk8s#2418]
I'm trying to use microk8s with ufw enabled but hitting networking problems (pods cannot read the apiserver).  I believe #1712 saw the same issues I am encountering, but the resolution might not have gone far enough.  It appears we need additional guidance about ufw rules to allow for the network interfaces calico generates for every pod (or maybe there's a configuration to let calico manage this for us?)

## Reproduction

* `sudo ufw enable`
* `sudo snap install microk8s --classic --channel 1.21/stable`
* `microk8s start`
* monitor microk8s come up using `watch microk8s kubectl get all --all-namespaces`, paying attention to `pod/calico-kube-controllers` which will not fully start.  check `microk8s kubectl logs calico-kube-controllers-YOURID` to see that it struggles with networking

For an even more obvious failure, do `microk8s enable storage` and monitor the associated pod

## Description

As described in #1712, the calico-kube-controllers pod is unable to reach the apiserver and goes into a crash loop because ufw is blocking the connection.  This can be fixed by adding the `calico-kube-controllers-*` pod's network interface (randomly named `caliXXXXXXXXXXX`) by `sudo ufw allow in on caliXXXXXXXXXXX ; sudo ufw allow out on caliXXXXXXXXXXX`.  

This is fine for a one-off case, but calico creates a new interface device for each pod, so the user would need to repeat the process for every pod they generate if that pod needs API server access (and maybe other things?).  

## Possible solutions

* Using a wildcard in the ufw allow rule will catch all cali-generated interfaces (`sudo ufw allow in on cali+ ; sudo ufw allow out on cali+`).  This works, but is maybe too permissive (can someone take advantage by making similarly-named interfaces?)
* (my iptables knowledge is **very** limited, but...) cali auto-generates iptables rules that (I think) mark traffic on these auto-generated interfaces (ex: `-A cali-tw-cali7fba7a35b74 -m comment --comment "cali:dO9Vjxk60RO-1o0o" -j MARK --set-xmark 0x0/0x10000`).  Can we add an allow rule that allows only this marked traffic, rather than allowing all traffic in/out of `cali+`?

## Other notes:

`microk8s inspect` advises users do `sudo ufw allow in on vxlan.calico && sudo ufw allow out on vxlan.calico` if ufw is on.  afaict this doesn't do anything (at least not for my configuration).  If I allow on `vxlan.calico` the problem persists, and if I instead enable the `caliX` interfaces (or `cali+`) in ufw everything appears to work normally.  Maybe there's a misconfiguration somewhere and the intent was things go through `vxlan.calico` but they're running elsewhere?  Or maybe this is just stale advice?  Either way, if we find a better config we should update `microk8s inspect` to give that advice.

**Comment by chris-sanders** [comment]
@ca-scribner instead of keying off of the interface name, MicroK8s knows the subnets that are being used. Seems like you could just allow permissive rules for the clusterIP subnet which we can pretty safely assume is dedicated to MicroK8s.

**Comment by Cynerva** [comment]
On a single-node Microk8s cluster, it's normal for the vxlan.calico interface to not be used. It will be used for cross-node traffic if you ever set up a multi-node Microk8s cluster, and in that case I would expect the ufw allow rule on vxlan.calico to be needed.

**Comment by ca-scribner** [comment]
I've tried allowing based on MicroK8s subnets with the following:
```
sudo ufw allow in from 10.1.0.0/16 to 10.152.183.0/24
sudo ufw allow in from 10.152.183.0/24 to 10.1.0.0/16  
sudo ufw allow out from 10.1.0.0/16 to 10.152.183.0/24
sudo ufw allow out from 10.152.183.0/24 to 10.1.0.0/16  
```

but that did not work.  @Cynerva mentioned this is likely due to the kube-proxy managing rules that forward that traffic to <kube-apiserver-ip>, and that traffic is then filtered by ufw rules.  I have not been successful in getting this to work.

The best option I have at the moment is:
```
sudo ufw allow in on cali+
sudo ufw allow out on cali+
```

which could be implemented [in MicroK8s here](https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/run-kubelite-with-args#L58)

**Comment by echoface** [comment]
[UFW BLOCK] IN=flannel.1 OUT=cni0 MAC=72:b6:26:dd:65:45:8a:ad:1c:19:5b:d5:08:00 SRC=10.244.1.8 DST=10.244.0.14 LEN=93 TOS=0x00 PREC=0x00 TTL=62 ID=22646 DF PROTO=UDP SPT=52343 DPT=53 LEN=73

sudo ufw allow in on flannel.1 && sudo ufw allow out on flannel.1
sudo ufw allow in on cni0 && sudo ufw allow out on cni0
both configured, but still not work; 

any suggestion?

**Comment by Mbd06b** [comment]
> 

try turning on ufw logging with
 `sudo ufw logging on `
and  then tailing the logs to inspect what's ufw is blocking
`sudo tail -f /var/log/ufw.log`

I used this very successfully to determine what was getting blocked and what rules I could apply to control my traffic on microk8s

**Comment by hieucd04** [comment]
After several hours of struggling ... I finally found this! Thank you!
However, running `microk8s inspect` doesn't give me any warning as stated in https://github.com/canonical/microk8s/pull/2426.
I'm on Ubuntu 22.04 LTS, microk8s `1.27/stable` (not strict)

**Comment by KrappRamiro** [comment]
> > 
> 
> try turning on ufw logging with `sudo ufw logging on ` and then tailing the logs to inspect what's ufw is blocking `sudo tail -f /var/log/ufw.log`
> 
> when you're done just turn logging off `sudo ufw logging off`
> 
> I used this very successfully to determine what was getting blocked and what rules I could apply to control my traffic on microk8s

This was the way! Also, based on https://thenewstack.io/add-nodes-to-your-microk8s-kubernetes-cluster/, i did this, but for ufw.

**On the controller node:**

```bash
sudo ufw allow 25000/tcp
sudo ufw allow 16443/tcp
sudo ufw allow 12379/tcp
sudo ufw allow 10250/tcp
sudo ufw allow 10255/tcp
sudo ufw allow 10257/tcp
sudo ufw allow 10259/tcp
```

**On each worker node:**

```bash
sudo ufw allow 25000/tcp
sudo ufw allow 10250/tcp
sudo ufw allow 10255/tcp
```

**Additionally, on all machines:**

```bash
sudo ufw allow 19001/tcp
```

These commands will open the neede ports for  traffic on the respective nodes.
