### ISSUE TITLE
microk8s.reset failure

### ISSUE THREAD

**Issue by tvansteenburgh** [ubuntu/microk8s#243]
```
$ microk8s.reset
Calling clean_cluster
Cleaning resources in namespace container-registry
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
error: at least one resource must be specified to use a selector
```
[inspection-report-20181213_105332.tar.gz](https://github.com/ubuntu/microk8s/files/2677294/inspection-report-20181213_105332.tar.gz)

**Comment by khteh** [comment]
I see the same error.

**Comment by ktsakalozos** [comment]
Any ideas on how to reproduce this?

**Comment by Fryuni** [comment]
Why is it trying to call `metrics.k8s.io/v1beta1`? That subdomain doesn't even have dns records, much less an endpoint.

**Comment by tvansteenburgh** [comment]
@ktsakalozos I don't really remember, it was on a demo machine at KubeCon, which is long gone, and at the time I didn't have the luxury of time to debug. However, I'm pretty certain that I had enabled the Istio addon. No idea if that's related, but it's a good place to start. I'll try to repro.

**Comment by tvansteenburgh** [comment]
Tried to repro with a fresh install and couldn't. Thinking it might be Istio, I enabled that and then did a reset, but it worked fine.
