### ISSUE TITLE
Openebs not deleting old pods

### ISSUE THREAD

**Issue by turowicz** [ubuntu/microk8s#2434]
Deleting a dynamic PVC of `openebs-jiva-default` class does not empty the pods in `openebs` namespace.

**Comment by balchua** [comment]
Hi @turowicz 
Sorry what do you mean by not deleting the pods?  Thanks.

**Comment by turowicz** [comment]
@balchua 

When I create a pod with an OpenEbs storage requirement, except for the PVCs, microk8s also spins up pods on each node. These pods remain even after the deployment has been deleted and I need to go through them and delete them manually.

![image](https://user-images.githubusercontent.com/1055391/126129781-a554f166-6f44-441a-83ea-8256acde8ef4.png)

**Comment by balchua** [comment]
Oh that, you can ask the openebs folks about it. But may also be intentional to do so, openebs cannot assume that deleting a deployment means it doesn't need the data anymore.

I am going to close this issue for now.
