### ISSUE TITLE
How to enable PodNodeSelector?

### ISSUE THREAD

**Issue by avarf** [ubuntu/microk8s#2436]
Hi,
I need to use node-selector at the namespace level and for this I need to activate a feature called `PodNodeSelector` but I don't know how I can do it in Microk8s.

In kubeadm you can do it as below:
```bash
kubectl edit cm -n kube-system kubeadm-config

# specify extraArgs with custom values under apiServer section:
```
Link: https://stackoverflow.com/a/52487334/5553963

**Comment by balchua** [comment]
You can go to `/var/snap/microk8s/current/args/kube-apiserver` then you can add the PodNodeSelector admission controller.
Ex.
`--enable-admission-plugins=PodNodeSelector`

From there you can apply the admission controller manifest as described here.
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector

**Comment by PRNDA** [comment]
> /var/snap/microk8s/current/args/kube-apiserver

Do I need to do this on every node or just the control-plane nodes?

**Comment by neoaggelos** [comment]
Hi @PRNDA, yes, this would have to be applied across all the control plane nodes

**Comment by PRNDA** [comment]
> Hi @PRNDA, yes, this would have to be applied across all the control plane nodes

Works like a charm, and thank you.
