### ISSUE TITLE
GPU not working on Ubuntu 18.04 with RTX A6000 

### ISSUE THREAD

**Issue by j-cunanan** [ubuntu/microk8s#2442]
[inspection-report-20210716_130642.tar.gz](https://github.com/ubuntu/microk8s/files/6827742/inspection-report-20210716_130642.tar.gz)

Stuck at this:
<pre>NAMESPACE                NAME                                                          READY   STATUS     RESTARTS   AGE
gpu-operator-resources   nvidia-operator-validator-kxlb8                               0/1     Init:0/4   0          30m
gpu-operator-resources   nvidia-device-plugin-daemonset-swrkw                          0/1     Init:0/1   0          30m
gpu-operator-resources   nvidia-dcgm-exporter-q89nn                                    0/1     Init:0/1   0          30m
gpu-operator-resources   gpu-feature-discovery-lbmpl                                   0/1     Init:0/1   0          30m
default                  gpu-operator-node-feature-discovery-master-58d884d5cc-4jl27   1/1     Running    0          30m
default                  gpu-operator-node-feature-discovery-worker-79l6n              1/1     Running    0          30m
kube-system              coredns-7f9c69c78c-xwkd9                                      1/1     Running    0          30m
kube-system              calico-kube-controllers-f7868dd95-5bdv9                       1/1     Running    0          30m
default                  gpu-operator-6b5666bb8b-xfqlk                                 1/1     Running    0          30m
gpu-operator-resources   nvidia-driver-daemonset-t6wxd                                 1/1     Running    0          30m
kube-system              calico-node-7dxtw                                             1/1     Running    0          30m
gpu-operator-resources   nvidia-container-toolkit-daemonset-5v2z5                      1/1     Running    0          30m
</pre>

Installation seemed to have gone well.

<pre>========== NVIDIA Software Installer ==========

Starting installation of NVIDIA driver version 460.73.01 for Linux kernel version 5.4.0-77-generic

Stopping NVIDIA persistence daemon...
Unloading NVIDIA driver kernel modules...
Unmounting NVIDIA driver rootfs...
Checking NVIDIA driver packages...
Updating the package cache...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving &apos;archive.ubuntu.com&apos;
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving &apos;archive.ubuntu.com&apos;
W: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/InRelease  Temporary failure resolving &apos;developer.download.nvidia.com&apos;
W: Failed to fetch https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/InRelease  Temporary failure resolving &apos;developer.download.nvidia.com&apos;
W: Some index files failed to download. They have been ignored, or old ones used instead.
Resolving Linux kernel version...
Proceeding with Linux kernel version 5.4.0-77-generic
Installing Linux kernel headers...
Installing Linux kernel module files...
Generating Linux kernel version string...
Compiling NVIDIA driver kernel modules...
/usr/src/nvidia-460.73.01/kernel/nvidia-drm/nvidia-drm-modeset.c: In function &apos;__will_generate_flip_event&apos;:
/usr/src/nvidia-460.73.01/kernel/nvidia-drm/nvidia-drm-modeset.c:96:23: warning: unused variable &apos;primary_plane&apos; [-Wunused-variable]
     struct drm_plane *primary_plane = crtc-&gt;primary;
                       ^~~~~~~~~~~~~
Relinking NVIDIA driver kernel modules...
Building NVIDIA driver package nvidia-modules-5.4.0...
Cleaning up the package cache...
Installing NVIDIA driver kernel modules...

WARNING: The nvidia-drm module will not be installed. As a result, DRM-KMS will not function with this installation of the NVIDIA driver.

ERROR: Unable to open &apos;kernel/dkms.conf&apos; for copying (No such file or directory)

Welcome to the NVIDIA Software Installer for Unix/Linux

Detected 12 CPUs online; setting concurrency level to 12.
Installing NVIDIA driver version 460.73.01.
A precompiled kernel interface for kernel &apos;5.4.0-77-generic&apos; has been found here: ./kernel/precompiled/nvidia-modules-5.4.0.
Kernel module linked successfully.
Kernel module linked successfully.
Kernel module unpacked successfully.
Kernel messages:
[    8.155797] IPv6: ADDRCONF(NETDEV_CHANGE): eno1: link becomes ready
[    8.425237] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[    8.426191] Bridge firewalling registered
[    8.430163] bpfilter: Loaded bpfilter_umh pid 2376
[    8.430343] Started bpfilter
[    8.466880] Initializing XFRM netlink socket
[   24.803238] kmem.limit_in_bytes is deprecated and will be removed. Please report your usecase to linux-mm@kvack.org if you depend on this functionality.
[   25.237727] logitech-hidpp-device 0003:046D:4082.0004: HID++ 4.5 device connected.
[   26.321692] logitech-hidpp-device 0003:046D:408A.0005: HID++ 4.5 device connected.
[   32.759372] rfkill: input handler disabled
[   34.104369] cgroup: cgroup: disabling cgroup2 socket matching due to net_prio or net_cls activation
[  126.922172] IPMI message handler: version 39.2
[  126.922776] ipmi device interface
[  126.930079] nvidia: loading out-of-tree module taints kernel.
[  126.930083] nvidia: module license &apos;NVIDIA&apos; taints kernel.
[  126.930084] Disabling lock debugging due to kernel taint
[  126.936589] nvidia: module verification failed: signature and/or required key missing - tainting kernel
[  126.942832] nvidia-nvlink: Nvlink Core is being initialized, major device number 236
[  126.943185] nvidia 0000:01:00.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=none:owns=none
[  126.988509] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  460.73.01  Thu Apr  1 21:40:36 UTC 2021
[  126.991755] nvidia-uvm: Loaded the UVM driver, major device number 234.
[  126.993015] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  460.73.01  Thu Apr  1 21:32:31 UTC 2021
[  126.994032] nvidia-modeset: Unloading
[  127.107204] nvidia-uvm: Unloaded the UVM driver.
[  127.152217] nvidia-nvlink: Unregistered the Nvlink Core, major device number 236
Installing &apos;NVIDIA Accelerated Graphics Driver for Linux-x86_64&apos; (460.73.01):
  Installing: [##############################] 100%
Driver file installation is complete.
Running post-install sanity check:
  Checking: [##############################] 100%
Post-install sanity check passed.
Running runtime sanity check:
  Checking: [##############################] 100%
Runtime sanity check passed.

Installation of the kernel module for the NVIDIA Accelerated Graphics Driver for Linux-x86_64 (version 460.73.01) is now complete.

Loading ipmi and i2c_core kernel modules...
Loading NVIDIA driver kernel modules...
Starting NVIDIA persistence daemon...
Mounting NVIDIA driver rootfs...
Done, now waiting for signal
</pre>

**Comment by ktsakalozos** [comment]
Hi @j-cunanan 

Could you try the latest/beta channel with `sudo snap install microk8s --classic --channel=latest/beta` ?

There are significant fixes in the latest/beta channel including new version of nvidia operator and the installation process. The next release coming up on a few weeks (v1.22) will include those GPU related patches.

**Comment by j-cunanan** [comment]
Hello @ktsakalozos 

Thank you so much! It is WORKING for me!

`microk8s.kubectl get pods -A` now show:
<pre><font color="#8AE234"><b>user@user-desktop</b></font>:<font color="#729FCF"><b>~</b></font>$ microk8s.kubectl get pods -A
NAMESPACE                NAME                                                          READY   STATUS      RESTARTS   AGE
kube-system              calico-node-d2nvw                                             1/1     Running     0          5m15s
kube-system              calico-kube-controllers-7c496b69f9-8scf4                      1/1     Running     0          5m15s
kube-system              coredns-7f9c69c78c-9tjfd                                      1/1     Running     0          4m7s
default                  gpu-operator-node-feature-discovery-master-867c4f7bfb-hz5mq   1/1     Running     0          2m51s
default                  gpu-operator-node-feature-discovery-worker-nfrnd              1/1     Running     0          2m51s
default                  gpu-operator-7db468cfdf-qsv76                                 1/1     Running     0          2m51s
gpu-operator-resources   nvidia-driver-daemonset-r7jr6                                 1/1     Running     0          2m35s
gpu-operator-resources   nvidia-container-toolkit-daemonset-mqgs9                      1/1     Running     0          2m35s
gpu-operator-resources   nvidia-cuda-validator-7mb2x                                   0/1     Completed   0          59s
gpu-operator-resources   gpu-feature-discovery-k5p48                                   1/1     Running     0          2m35s
gpu-operator-resources   nvidia-dcgm-exporter-7pzd8                                    1/1     Running     0          2m35s
gpu-operator-resources   nvidia-device-plugin-daemonset-frrkn                          1/1     Running     0          2m35s
gpu-operator-resources   nvidia-device-plugin-validator-lc7mx                          0/1     Completed   0          28s
gpu-operator-resources   nvidia-operator-validator-9vns6                               1/1     Running     0          2m35s
</pre>

And for another sanity check using `microk8s.kubectl describe no`

<pre>Capacity:
  cpu:                12
  ephemeral-storage:  959863856Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32541832Ki
  nvidia.com/gpu:     1
  pods:               110
</pre>
