### ISSUE TITLE
microk8s will not start on Travis CI focal environment

### ISSUE THREAD

**Issue by jrtcppv** [ubuntu/microk8s#2446]
I am using Travis CI to test our Kubernetes application. It spins up a VM (currently using 8 vcpus and 32GB memory) with a preconfigured environment that I install microk8s on and then our application. I have been able to make this work with the Ubuntu 18.04 LTS (bionic) environment, but our "official" environment is Ubuntu 20.04 LTS (focal) and unfortunately `microk8s status` just hangs in this environment. I have tried several versions in both bionic and focal (1.18, 1.19, 1.21) and for all of them I have this result. To verify this behavior entered debug mode with the instances and typed these commands immediately upon entering the ssh session:
```
travis@travis-job-a0cf9506-a498-412e-b124-a1ca4b2162b3:~/build/cvisionai/tator$ sudo snap install microk8s --classic --channel=1.19/stable
microk8s (1.19/stable) v1.19.11 from Canonical✓ installed
travis@travis-job-a0cf9506-a498-412e-b124-a1ca4b2162b3:~/build/cvisionai/tator$ sleep 180
travis@travis-job-a0cf9506-a498-412e-b124-a1ca4b2162b3:~/build/cvisionai/tator$ sudo microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
travis@travis-job-a0cf9506-a498-412e-b124-a1ca4b2162b3:~/build/cvisionai/tator$ sudo microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-control-plane-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow
WARNING:  Docker is installed. 
Add the following lines to /etc/docker/daemon.json: 
{
    "insecure-registries" : ["localhost:32000"] 
}
and then restart docker with: sudo systemctl restart docker
Building the report tarball
  Report tarball is at /var/snap/microk8s/2263/inspection-report-20210717_003939.tar.gz
```
I have reviewed other issues and searched the logs for similar problems (blocked ports, proxies, firewalls, etc) and I can't find anything that matches in the logs. Microk8s has been working great for us on standalone nodes using base Ubuntu, but I suspect some configuration with the Travis VM is causing issues. Any insight is appreciated.

[inspection-report.zip](https://github.com/ubuntu/microk8s/files/6833909/inspection-report.zip)

**Comment by balchua** [comment]
I saw that the `calico-node` `DaemonSet` isnt up and running (yet?). That means the cni isn't configured yet.

This is strange.  So far i couldn't find anything suspicious in the logs.

**Comment by jrtcppv** [comment]
Would it be helpful if I try to run it longer? I could also provide a minimal `.travis.yml` that reproduces the issue.

**Comment by jrtcppv** [comment]
Here is a minimal `.travis.yml` that reproduces the issue:
```yaml
os: linux
arch: amd64
dist: focal
language: generic
vm:
  size: x-large

addons:
  snaps:
    - name: microk8s
      confinement: classic
      channel: 1.19/stable

script:
- sudo microk8s status --wait-ready
```
You can see the results of the build here:
https://travis-ci.com/github/cvisionai/tator/jobs/525139329

Note that I left the VM size at x-large (8 vcpus and 32GB memory) to rule out issues related to resource constraints, but I have seen the issue with smaller VM sizes as well. It also does not matter if I use the yaml syntax for installing the snap or if I just make `sudo snap install microk8s --classic --channel=1.19/stable` part of the script. I would be happy to enter debug mode to get any other info that might be helpful here. Thanks for taking a look!

**Comment by ktsakalozos** [comment]
I tried to get this going with no luck (you may have seen a PR I opened). Although the services seem to be running fine, kubelet does not register the node with the API server. I suspect this is due to the host having a funny hostname but I am not sure.

In the past we used to use travis as part of our CI [1] but we never saw this behavior. Travis is using VMs from AWS and GCE, right? Although I am confident microk8s deploys with no issues on AWS I am not sure about GCE as I am not testing there. Have you gone into a node to try to debug it [2]?

[1] https://github.com/ubuntu/microk8s/blob/1.19/.travis.yml
[2] https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by jrtcppv** [comment]
I have gone into the node to debug but I have only seen the same symptoms you describe, the node never gets added to the cluster. What is strange is that the bionic environment works fine, not sure if the node name changes between bionic and focal. 
Anyway, thank you for taking a look at this. Since opening this issue I have looked into other CI services and I think we are going to go with Circle CI which offers a base Ubuntu environment that works fine with microk8s. I am going to go ahead and close the issue since it is resolved on our end.

**Comment by ktsakalozos** [comment]
@michal-at-travisci would you be able to offer some insight on what might be wrong here?
