### ISSUE TITLE
How install specific (patch) microk8s version, for example 1.18.19 ?

### ISSUE THREAD

**Issue by patsevanton** [ubuntu/microk8s#2447]
Hello! Microk8s awasome project.
How install specific (patch) microk8s version, for example 1.18.19 ?
Now i can install only 1.18.20
Thanks!

**Comment by ktsakalozos** [comment]
Hi @patsevanton

As an end user you can only get the last revision published in a track. You could setup a snap store proxy [1] to gate/block revisions you do not want. 

Maybe I cann offer more assistance if you tell me more about your use case.

[1] https://docs.ubuntu.com/snap-store-proxy/en/

**Comment by patsevanton** [comment]
Ok. Thanks!
