### ISSUE TITLE
Ip address of k8s cluster is changing frequently

### ISSUE THREAD

**Issue by QuanTran91** [ubuntu/microk8s#2452]
Hi all,

I have a microk8s cluster in my Windows PC.
Every time I restart the PC, the IP address of the cluster is changed. I have to update my Kube config so that kubectl can connect to the cluster.
Is there any way to prevent this? 

Thanks

**Comment by ktsakalozos** [comment]
Hi @QuanTran91 

MicroK8s on Windows (and Mac) runs on a VM created with (Multipass)[https://multipass.run/] that in turn uses VirtualBox or HyperV. Maybe you could use ` <instance_name>.mshome.net` rather than the IP as @Saviq suggested at [1] or go to the virtualisation layer (VirtualBox or HyperV) and state that that VM will always get the same IP.

Maybe @joedborg knows of a better way to handle this.

[1] https://github.com/canonical/multipass/issues/1293#issuecomment-614075974

**Comment by QuanTran91** [comment]
Thank for your support
I tried with https://microk8s-vm.mshome.net:16443
It show error: Unable to connect to the server: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster, kubernetes.default.svc.cluster.local, not microk8s-vm.mshome.net

**Comment by ktsakalozos** [comment]
Lets add the `microk8s-vm.mshome.net` in the certificate k8s presents.

Get a shell in the microk8s-vm with:
```
multipass shell microk8s-vm
```
Edit `/var/snap/microk8s/current/certs/csr.conf.template`, eg:
```
sudo nano /var/snap/microk8s/current/certs/csr.conf.template
```
And add this line in the list of DNS entries:
```
DNS.5 = microk8s-vm.mshome.net
```
Then restart MicroK8s with:
```
sudo microk8s.stop; sudo microk8s.start
```

**Comment by QuanTran91** [comment]
Thanks to @ktsakalozos 
It worked like charm.
But I think we should document it  for Window, MacOS user because MicroK8s is installed as a VM.

**Comment by QuanTran91** [comment]
How about update on this : https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/certs/csr.conf.template ?

**Comment by Tariqpgr8** [comment]
Hi @QuanTran91 Can you guide me how to make multipass instance IP address constant? I'm using k3s inside. Environment is setup on Windows Machine with Hyper-V. I'll really appreciate, changing certs and IP all the time, makes my life miserable.
Thanks.

**Comment by Saviq** [comment]
@Tariqpgr8 here's a sample [netplan](https://netplan.io/) configuration that will _add_ an address to existing interfaces:
```yaml
# /etc/netplan/50-static.yaml
network:
    ethernets:
        ens4:
            match:
                macaddress: 52:54:00:7b:c9:da  # you need to update this
            set-name: ens4
            addresses:
            - 10.1.2.1/24
    version: 2
```

You can start by copying `/etc/netplan/50-cloud-init.yaml` and removing `dhcp4...` from the copy.

**Comment by Saviq** [comment]
There's another option, too, you can install `avahi-daemon` on the instances and refer to them that way:

https://github.com/canonical/multipass/issues/1830#issuecomment-895200100
