### ISSUE TITLE
Support for vSphere dynamic provisioning?

### ISSUE THREAD

**Issue by aldgagnon** [ubuntu/microk8s#2463]
I currently work with a bare metal Kubernetes cluster running on VMWare which supports StorageClasses for dynamic provisioning and I was curious if microk8s supports dynamic volume provisioning using StorageClass? Something along the lines of this: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/storageclass.html. 

Does anyone know if support exists already? I haven't found much online which leads me to believe support doesn't exist.

**Comment by balchua** [comment]
If the vsphere csi is installed, I don't see why MicroK8s cannot dynamically provision.
We have openebs addon which is basically using the dynamic provisioning.

**Comment by aldgagnon** [comment]
@balchua Thanks for the tip - appreciate it!

**Comment by aldgagnon** [comment]
For anyone else stumbling across this post, I was able to get this to work by following vmware's guide here: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/
