### ISSUE TITLE
Cannot remove a crashed node

### ISSUE THREAD

**Issue by jconlon** [ubuntu/microk8s#2465]
Had a three node cluster but one of my machines' hardware is marginal as its crashed more than once and I had to reinstall the OS.  Crashed so I could not do a `leave` from the cluster.  Leaving just two nodes.

So I want to remove it from the cluster for the time being.

```
$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 192.168.0.169:19001 192.168.0.186:19001 192.168.0.132:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    helm3                # Helm 3 - Kubernetes package manager
    ingress              # Ingress controller for external access
    openebs              # OpenEBS is the open-source storage solution for Kubernetes
    openfaas             # openfaas serverless framework
    prometheus           # Prometheus operator for monitoring and logging
  disabled:
  ...
```
Tried to `remove-node` but it 
20210722_132241.tar.gz)
failed with:

```
$ microk8s remove-node 192.168.0.132
Error from server (NotFound): nodes "192.168.0.132" not found
Node 192.168.0.132 does not exist in Kubernetes.
```

[inspection-report-20210722_132241.tar.gz](https://github.com/ubuntu/microk8s/files/6864114/inspection-report-

**Comment by balchua** [comment]
Try this command `microk8s.remove-node --force` see if it forces to remove it.

**Comment by jconlon** [comment]
Yes, I tried it yesterday and it did work - up to a certain point.  It removed it from my three node HA cluster turning it into:

```
$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 192.168.0.169:19001
  datastore standby nodes: none
```


but even waiting until today I still see that node show up in my kuberctl get nodes:
```
$ k get no
NAME    STATUS     ROLES    AGE   VERSION
trout   NotReady   <none>   9d    v1.21.1-3+ba118484dd39df
shamu   Ready      <none>   19d   v1.21.3-3+90fd5f3d2aea0a
tuna    Ready      <none>   19d   v1.21.3-3+90fd5f3d2aea0a
```
Should I expect that node to eventually not show up in `kubectl get nodes` ?

**Comment by balchua** [comment]
@jconlon since the node is removed from the db, you can now do a `kubectl delete node <node name>`

**Comment by jconlon** [comment]
Yes, that did it, but I also had to use the --force: `$ kuberctl delete no trout --force`
