### ISSUE TITLE
getting runtime error when trying to run on a gpu node

### ISSUE THREAD

**Issue by inohmonton99** [ubuntu/microk8s#2474]
Please run `microk8s inspect` and attach the generated tarball to this issue.
`Microk8s v.1.21`
Error:
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "nvidia" is configured

Troubleshooting:
1. followed installation process [here](https://github.com/NVIDIA/k8s-device-plugin#preparing-your-gpu-nodes)
2. tested deployment with `microk8s enable gpu`

We appreciate your feedback. Thank you for using microk8s.
![image](https://user-images.githubusercontent.com/37641302/127045623-f2590077-7d03-4592-98c1-ab7b356191b5.png)

**Comment by balchua** [comment]
@joedborg on 1.21 do we still need to manually install nvidia?  O thought the operator will do that when you do `microk8s enable gpu`?

**Comment by joedborg** [comment]
@balchua I think we need to consider backporting latest/edge GPU fixes into stable.

@inohmonton99 please refresh your cluster to `latest/edge`, disable and re-enable the GPU addon, that should work for you.

**Comment by inohmonton99** [comment]
will try that @joedborg and let you know. Thanks!

**Comment by inohmonton99** [comment]
everything's working now. thanks for the quick solution @joedborg , also with `latest/edge` I didn't need to install NVIDIA drivers only needed to enable gpu and it installed everything. Awesome!

**Comment by joedborg** [comment]
You're welcome @inohmonton99, thanks for raising the issue.   Yes, MicroK8s will detect whether or not you have drivers already installed and configure the NVIDIA operator accordingly.
