### ISSUE TITLE
gpu operator on crashback loop with fresh install

### ISSUE THREAD

**Issue by Dandevslack** [ubuntu/microk8s#2475]
When installing microk8s and enabling GPU, nvidia-driver-daemonset continually crashes.  microk8s version is 1.21.3 Steps Taken:

1. Fresh Install of Ubuntu 20.04
2. sudo snap install microk8s --classic
3. microk8s.enable dns gpu

Results from microk8s.inspect are attached 
[inspection-report-20210726_194311.tar.gz](https://github.com/ubuntu/microk8s/files/6880787/inspection-report-20210726_194311.tar.gz)

I also attempted to install the nvidia drivers and re-enable gpu.

**Comment by balchua** [comment]
The operator is failing with this error
```
W0726 19:07:54.381962       1 kernel.go:99] failed to detect the status of selinux, please check if the system supports selinux and make sure /sys on the host is mounted into the container: open /host-sys/fs/selinux/enforce: no such file or directory
I0726 19:07:54.407416       1 nfd-worker.go:480] feature discovery completed
I0726 19:07:54.407451       1 nfd-worker.go:550] sending labeling request to nfd-master
I0726 19:08:54.416382       1 nfd-worker.go:468] starting feature discovery...
W0726 19:08:54.441413       1 kernel.go:99] failed to detect the status of selinux, please check if the system supports selinux and make sure /sys on the host is mounted into the container: open /host-sys/fs/selinux/enforce: no such file or directory ```
Does it ring a bell?  It looks like it requires selinux to be present in the system.

**Comment by joedborg** [comment]
Thanks for raising this!  Could you please try with `—channel latest/edge` please?

**Comment by Dandevslack** [comment]
hi @joedborg i've reinstalled using --channel=latest/edge and the gpu operator is successfully working!  Thanks for the help.  As an aside, the reported microk8s version is ```v1.21.3-3+fa05fa7bf9459a```
