### ISSUE TITLE
Snap is a massive pain

### ISSUE THREAD

**Issue by turowicz** [ubuntu/microk8s#2491]
Guys,

Everytime there is an automated snap update, our microk8s clusters go down and never come back up.

We have tried `1.21/stable`, `latest/stable`, `latest/edge` and its all the same.

Is there at least any sort of information what to do when the cluster is down after automated update?

Disclaimer: Disabling snapd is not an option because you cant run `microk8s start` and `microk8s stop` without it running.

There has to be an option to pin the installed version to the actual revision numer.

**Comment by turowicz** [comment]
cc @balchua @ktsakalozos

**Comment by turowicz** [comment]
[inspection-report-20210804_124250.tar.gz](https://github.com/ubuntu/microk8s/files/6931338/inspection-report-20210804_124250.tar.gz)

**Comment by turowicz** [comment]
Seriously guys, forced automatic upgrades is never good for any server software, even dev & test.

**Comment by balchua** [comment]
@turowicz the comment here shows some example on how to control snap updates.
https://github.com/ubuntu/microk8s/pull/1658#issuecomment-720989345
Via snap proxy

**Comment by turowicz** [comment]
Even though is a lot of hassle, it has to do.
