### ISSUE TITLE
kubectl logs not working

### ISSUE THREAD

**Issue by amentis** [ubuntu/microk8s#250]
[inspection-report-20181217_133610.tar.gz](https://github.com/ubuntu/microk8s/files/2685831/inspection-report-20181217_133610.tar.gz)

kubectl -n kube-system logs kube-dns-6ccd496668-4zp4k kubedns 
Error from server: Get https://my-hostname:10250/containerLogs/kube-system/kube-dns-6ccd496668-4zp4k/kubedns: dial tcp: lookup my-hostname on my.dns:53: no such host

Whenever I try to use kubectl logs on any container in microk8s it tries to lookup my-hostname on my.dns. Of course, my workstation is not on the DNS server. I expect to be able to use kubectl logs nevertheless.

**Comment by ktsakalozos** [comment]
Hi @amentis 

Could you try to use the `--hostname-override` option of kubelet (https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/).
You will need to update `/var/snap/microk8s/current/args/kubelet` and to a restart of MicroK8s with `microk8s.stop` and `microk8s.start`.

How does you /etc/hosts look like?

Thanks

**Comment by amentis** [comment]
It was a matter of my hostname not existing in /etc/hosts. Everything works correct now!

**Comment by yurifrl** [comment]
Hy @amentis what did you put in your /etc/hosts? It seems I'm having the same issue

**Comment by amentis** [comment]
> Hy @amentis what did you put in your /etc/hosts? It seems I'm having the same issue

If, for example, my machine's hostname is "myhostname" I was missing the record
127.0.0.1 myhostname

**Comment by yurifrl** [comment]
Thank you, it worked.
The only thing is that for some reason my hostname seams do be "true" the word "true":
`Error from server: Get https://true:10250/...` I put `127.0.0.1 true` in to /etc/hosts and the logs worked fine, but I dunno, curious at least.

**Comment by baalaan** [comment]
> 
> 
> > Hy @amentis what did you put in your /etc/hosts? It seems I'm having the same issue
> 
> If, for example, my machine's hostname is "myhostname" I was missing the record
> 127.0.0.1 myhostname

This did the trick for me. I was trying to get the logs and got this error

Error from server: Get https://**buruntu**:10250/containerLogs/default/my-apache-5d589d69c7-ntg7w/my-apache: dial tcp: lookup buruntu on 192.168.100.1:53: no such host

I edited the /etc/hosts file and added a simple line: 127.0.0.1 **buruntu**

and now the logs cmd works!
