### ISSUE TITLE
microk8s.enable kubeflow freeze

### ISSUE THREAD

**Issue by filiphagan** [ubuntu/microk8s#2501]
After first successful run and then rebooting microk8s is not able to run kubeflow anymore. This takes forever:

```bash
billy@billy:~$ microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for other addons to finish initializing...
```

[inspection-report-20210805_221202.tar.gz](https://github.com/ubuntu/microk8s/files/6941596/inspection-report-20210805_221202.tar.gz)

microk8s version: 1.22.3 classic
OS: Ubuntu 20.04

**Comment by ktsakalozos** [comment]
Hi @filiphagan 

I see kubelet cannot register with the API server. It is complaining with errors like:
```
sie 05 22:05:48 billy microk8s.daemon-kubelite[2742]: E0805 22:05:48.507218    2742 node.go:161] Failed to retrieve node info: nodes "billy" not found
```

Did the hostname change after the kubernetes deployment? Also do not use capital letters and/or underscores in the hostnames of nodes as they are not valid for kubernetes.

**Comment by filiphagan** [comment]
@ktsakalozos In fact, yes, I changed it to the one without underscores and capital letters (saw that hint on _most common issues_). What bothers me is that it was working fine during the first run with the hostname unchanged. After reinstalling microk8s another issue came up, it's described here: https://github.com/ubuntu/microk8s/issues/2502
