### ISSUE TITLE
Service snap.microk8s.daemon-apiserver-kicker is not running in microk8s node servers

### ISSUE THREAD

**Issue by AmilaDevops** [ubuntu/microk8s#2505]
@balchua  hi  I am using microk8s version v1.21.3 installed and I have one master node and 03 node servers.  Below is the out put of the `microk8s inspect` command I get below error when I run  `microk8s inspect` only in the node servers.  Master node is fine. 

![image](https://user-images.githubusercontent.com/44959238/128621135-1e2116f2-944d-47b1-947a-8be707b53b65.png)

attached tarball is this 
[inspection-report-20210808_014910.tar.gz](https://github.com/ubuntu/microk8s/files/6950241/inspection-report-20210808_014910.tar.gz)

Please can anyone let me know why's those 02 services (snap.microk8s.daemon-apiserver-kicker, snap.microk8s.daemon-etcd) are not running in my cluster agent node machines  ?

**Comment by balchua** [comment]
This is normal when you are not using HA.  Etcd and the kicker will only run on the master node.
