### ISSUE TITLE
Add support for the service-catalog

### ISSUE THREAD

**Issue by geoand** [ubuntu/microk8s#251]
It would be awesome support for the Kubernetes [service catalog](https://kubernetes.io/docs/concepts/extend-kubernetes/service-catalog/) could be added.

Thanks!

**Comment by ktsakalozos** [comment]
That is really interesting @geoand. Could you help me make a strong case for this feature?

How would you (as a developer) use it? How would the user (service consumer) experience look like? I haven't looked into this much so excuse any naive questions. Would you expect MicroK8s to have its own default service broker and managed services would come from there? Would you expect developers to setup their own service brokers and exchange through the catalog the work they are doing with the rest of their team and/or the rest of the MicroK8s users?

**Comment by geoand** [comment]
Hi @ktsakalozos 

Those are great questions :).
I would say that I would expect the most basic support, meaning that when I enabled the addon in microk8s, all I would get is the service catalog API and it's respective controller running.
It would then be up to me to add whatever broker I like

**Comment by geoand** [comment]
Would you like me to provide any more information about this?

**Comment by geoand** [comment]
I am coming from the Openshift community and we use a couple specific brokers there, so I'm not really sure what brokers people that use Vanilla Kubernetes are used to
