### ISSUE TITLE
Access denied issue related to snapctl on Debian 9

### ISSUE THREAD

**Issue by deanyxu** [ubuntu/microk8s#2514]
Hi,

We are hitting "error: access denied" issue due to running snapctl on Debian 9 system. It affects commands like `microk8s enable metrics-server` or `microk8s enable prometheus`. We found that there was a workaround from https://bugs.launchpad.net/snapd/+bug/1933392/comments/5, wonder if this workaround could be added to microk8s package as well.

```
$ snap version
snap    2.51.3
snapd   2.51.3
series  16
debian  9
kernel  4.14.81.bm.15-amd64
```

**Comment by ktsakalozos** [comment]
I am closing this as duplicate to https://github.com/ubuntu/microk8s/issues/2513 .

@deanyxu please follow the discussion the other thread.
