### ISSUE TITLE
x509: certificate is valid for kubernetes, kubernetes.default, ..., not <my domain>

### ISSUE THREAD

**Issue by milesand** [ubuntu/microk8s#2521]
Inspection tarball: [inspection-report-20210813_015005.tar.gz](https://github.com/ubuntu/microk8s/files/6979446/inspection-report-20210813_015005.tar.gz)

I have microk8s running on multi-node raspberry pi cluster, using Ubuntu for OS. Trying to `kubectl` from external device using my domain name returns the error `x509: certificate is valid for kubernetes, kubernetes.default, ..., not <my domain>`.

I updated `/var/snap/microk8s/current/certs/csr.conf.template` to include my domain:
```
[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
DNS.6 = <my domain>
```

Per the [documentation](https://microk8s.io/docs/ports#heading--auth) I expected this to generate a new certificate which can be used to connect via my domain name, but this does not seem to change the output of `microk8s config`.

**Comment by ktsakalozos** [comment]
Hi @milesand. You will need to update the `/var/snap/microk8s/current/certs/csr.conf.template` on all nodes. Then in the kubeconfig file you get with `microk8s config` you would want to replace the IP of the API server endpoint with your domain.

**Comment by milesand** [comment]
Thank you @ktsakalozos, I had updated the template file on only one node; Updating it on all nodes resolvd my issue.
