### ISSUE TITLE
`microk8s enable kubeflow` cannot bootstrap juju controller in v1.21.3

### ISSUE THREAD

**Issue by ca-scribner** [ubuntu/microk8s#2523]
When trying to do:

```
sudo snap install microk8s --classic
microk8s enable kubeflow
```

The `enable kubeflow` gets stuck bootstrapping the juju controller.  It appears to be due to [this bug](https://bugs.launchpad.net/juju/+bug/1935075), where the controller's mongodb container is in a crash loop.  This bug was fixed in Juju 2.9.9, but microk8s 1.21.3 uses Juju 2.9.0.  Manually bootstrapping (`juju bootstrap microk8s uk8s`) using juju 2.9.10 works fine.

**Comment by ktsakalozos** [comment]
The fix will be available with the next patch release.
