### ISSUE TITLE
Can't use imported local images

### ISSUE THREAD

**Issue by milesand** [ubuntu/microk8s#2526]
Inspection tarball: [inspection-report-20210815_022232.tar.gz](https://github.com/ubuntu/microk8s/files/6987413/inspection-report-20210815_022232.tar.gz)

I followed the steps demonstrated in the [documentation](https://microk8s.io/docs/registry-images) to use locally built image, but `kubectl get pods` show `STATUS` `ErrImageNeverPull` rather than running normally.
```
NAME                                READY   STATUS              RESTARTS   AGE
nginx-deployment-748d866657-sdjkw   0/1     ErrImageNeverPull   0          7s
```

Running `microk8s ctr images ls` does show that the image has indeed been imported:
```
REF                              TYPE                                                  DIGEST                                                                   SIZE       PLATFORMS    LABELS
...
docker.io/library/mynginx:local  application/vnd.docker.distribution.manifest.v2+json  sha256:e88c832e2c8c5adec72593994550cdb186d2b7cc5770055a7a617f234a168fce  124.1 MiB  linux/arm64  io.cri-containerd.image=managed
...
```

Thank you in advance.

**Comment by balchua** [comment]
@milesand when you use locally built image and you have multiple nodes, you have to import the image to all nodes.

**Comment by milesand** [comment]
Thanks @balchua, that solved my problem.
