### ISSUE TITLE
Ingress issues (readiness/liveness failure)

### ISSUE THREAD

**Issue by nnsense** [ubuntu/microk8s#2529]
Hi, after a clean install (both latest and 1.20), I cannot use the ingress addon. If I run this
```
microk8s kubectl -n ingress describe daemonset.apps/nginx-ingress-microk8s-controller
```

`readiness` and `liveness` are failing because are both configured without any hostname:
```
 [..]
   Readiness:  http-get http://:10254/healthz delay=0s timeout=5s period=10s #success=1 #failure=3
   Liveness:   http-get http://:10254/healthz delay=10s timeout=5s period=10s #success=1 #failure=3
 [..]
```

I've tried to reinstall the whole snap a couple of times, is anyone aware of this issue? Have I missed to set anything? I must be doing something wrong, the ingress isn't exactly a rarely used addon

As soon as I remove both liveness and readiness by editing the daemonset, the ingress start working.

Thanks

**Comment by balchua** [comment]
Hi @nnsense this is the manifest we use to enable the ingress addon.

https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ingress.yaml

What you are seeing seems to be common.

What is not common is that they fail the probes.

**Comment by nnsense** [comment]
Hi, thanks for your answer. For now the best I could find has been to delete the readiness and liveness from `daemonset.apps/nginx-ingress-microk8s-controller` after the deployment, but that's not ideal of course. Are you aware of a fix/workaround or the only option if it doesn't work "out of the box" is to deploy it with helm?

**Comment by balchua** [comment]
Did u try if the ingress really work?  I don't know yet why the probe is failing.

**Comment by nnsense** [comment]
After the deployment, these are my events

```

**Comment by nnsense** [comment]
Update: OK, I am confused. I've rebooted the host.. and now it works. When it happened again I've just restarted to get it working. It seems related my host, better to stop keeping this open, until I don't make sure it's actually related microk8s.
