### ISSUE TITLE
microk8s add-node is not a valid microk8s sub command.

### ISSUE THREAD

**Issue by TheOriginalJudgie** [ubuntu/microk8s#2533]
New user here with a fresh install. After installing to a fresh install of Ubuntu 20.04 LTS Server (with no other options  other than an openssh server installed) using "sudo snap install microk8s --classic --channel=1.19/stable" from https://microk8s.io/docs/high-availability.

The very next thing I'm doing is trying to run the "microk8s add-node" command (again in accordance with the guide at https://microk8s.io/docs/high-availability), however I get the following error:

userBlablabla@microk8s1:~$ microk8s add-node 
'add-node' is not a valid MicroK8s subcommand.
Available subcommands are:
        config
        ctr
        disable
        enable
        istioctl
        kubectl
        linkerd
        reset
        start
        status
        stop
        inspect

Any idea what is going on? I'm guessing this isn't expected behaviour? I'm happy to obliterate this particular VM and start again based on your advice as it is for learning, not production :-)

**Comment by ktsakalozos** [comment]
Hi @TheOriginalJudgie, the add-node command should be there on 1.19 (I just tested it!).

Could you attach a `microk8s inspect` tarball? Something does not seem right.

**Comment by TheOriginalJudgie** [comment]
I've just got home and conducted a reinstall again from scratch, now it's functioning. Thankyou for the prompt response regardless!
