### ISSUE TITLE
k8s refuses to pull images from bundled registry

### ISSUE THREAD

**Issue by stub42** [ubuntu/microk8s#255]
Per  https://bugs.launchpad.net/juju/+bug/1809087, it seems that k8s is refusing to pull images from the microk8s bundled registry. Reported failure is 'http: server gave HTTP response to HTTPS client'. The pod gets stuck in a 'Waiting: ErrImagePull' state.

Per https://stackoverflow.com/questions/38695515/can-not-pull-push-images-after-update-docker-to-1-12 , this likely regressed with 1.12. I've reproduced this with 1.12 stable and 1.13 edge.

**Comment by stub42** [comment]
Works with 1.11/stable

**Comment by ktsakalozos** [comment]
Hi @stub42 

Thank you for reporting this issue. We do mark the docker registry as insecure in the daemon.json here: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/docker-daemon.json 

Could you share the script/commands you use to test the registry. I am asking for a way to reproduce the issue you are having, please be as detailed as possible.  Also, is the launchpad bug correct?

On every release we run this test against the registry: https://github.com/ubuntu/microk8s/blob/master/tests/validators.py#L163 I wonder if dockerd caches the images and our pulls do not really hit the registry.

Thanks

**Comment by stub42** [comment]
I've corrected the truncated Launchpad bug link.

The problem is that I was using an IP address rather than the string 'localhost' in the address of the image, so the insecure registry mark was not being applied. I had done this as I'm more used to working in environments where components have distinct localhost.

I think the issue is INVALID or maybe WONTFIX, as I don't think it is practical to list all the potential IP addresses in docker-daemon.json. It also would likely not be correct to make docker only listen on localhost.

**Comment by wallyworld** [comment]
@ktsakalozos 

The bug link in the first post has a typo. It should be https://bugs.launchpad.net/juju/+bug/1809087
The repro instructions are in that bug; I can reproduce the same problem using microk8s.kubectl and just a simple pod yaml file.

$ snap info microk8s
installed:        v1.13.1  (354) 229MB classic

The yaml:
apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: demo
    image: 10.0.0.76:32000/gcr.io/google-samples/node-hello
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080

$ microk8s.enable registry
$ microk8s.docker pull gcr.io/google-samples/node-hello
$ microk8s.kubectl create -f hello.yaml
$ microk8s.describe pod/hello
...
Events:
  Type Reason Age From Message
  ---- ------ ---- ---- -------
  Normal Scheduled 13s default-scheduler Successfully assigned default/hello to wallyworld
  Normal Pulling 12s kubelet, wallyworld pulling image "10.0.0.76:32000/gcr.io/google-samples/node-hello"
  Warning Failed 12s kubelet, wallyworld Failed to pull image "10.0.0.76:32000/gcr.io/google-samples/node-hello": rpc error: code = Unknown desc = Error response from daemon: Get https://10.0.0.76:32000/v2/: http: server gave HTTP response to HTTPS client
  Warning Failed 12s kubelet, wallyworld Error: ErrImagePull
  Normal BackOff 10s (x2 over 11s) kubelet, wallyworld Back-off pulling image "10.0.0.76:32000/gcr.io/google-samples/node-hello"
  Warning Failed 10s (x2 over 11s) kubelet, wallyworld Error: ImagePullBackOff

**Comment by wallyworld** [comment]
Ah, I didn't hit refresh before posting, sorry.
