### ISSUE TITLE
[question]multiple process exists after microk8s restart

### ISSUE THREAD

**Issue by sunhubs** [ubuntu/microk8s#2558]
Recently, I find a problem about the process after cluster restart. The procedure steps:
1, start the cluster using 'microk8s start'
2, deploy a deployment/pod which will run a go executive file, named as app_example. use 'ps axu|grep app_example' it will show only one process.
3, stop the cluster using 'microk8s stop'
4, check the process using ps command, it will show there is still one.(the process will not exit  until catch a TERM signal)
5. start the cluster again.
6. after a few minutes, check the process using ps command, it will show there are two. which is confused or not acceptable to me.

so based on the phenomena，i want to ask:
1, what is the actual behavior/effect to the container/pods when the cluster stops? such as signal emit or environment difference
2, again, what is the actual behavior/effect to the contianer/pods when the cluster starts?
3, how to make sure the process be only one in above restart situation? a bug of microk8s or make some changes in the appliance level?

BTW, i do same thing on k3s cluster, it seems to be no problem, and there is only one process.

-------Updated------
Snap Version:
snap    2.47.1-1.el7
snapd   2.47.1-1.el7
series  16
centos  7
kernel  3.10.0-1160.el7.x86_64

Microk8s Version:
Name      Version    Rev    Tracking  Publisher   Notes
core      16-2.48.2  10583  -         canonical✓  core
microk8s  v1.20.1    1910   -         canonical✓  classic

**Comment by balchua** [comment]
Hmmm I didn't actually notice this.
Does the container/pod show up in kubernetes or containerd?
For example `microk8s ctr containers`

**Comment by sunhubs** [comment]
@balchua i try to run the command "microk8s ctr containers ls", it returns error "ctr: failed to dial "/var/snap/microk8s/common/run/containerd.sock": context deadline exceeded". Seems to caused by the containered has been stopped?
Actually I do not care so much whether the container/pod has been stop when I stop the cluster, even though stop is a better choice, but the point is that it should not start/build a new container/pod when I start the cluster again.

**Comment by balchua** [comment]
It maybe that we recently changed the containerd stop mode to not kill the containers, this is to avoid disruption during snap refreshes.  I am not sure if this change would be a result of this behavior.
@ktsakalozos @joedborg thoughts on this?

**Comment by sunhubs** [comment]
> It maybe that we recently changed the containerd stop mode to not kill the containers, this is to avoid disruption during snap refreshes. I am not sure if this change would be a result of this behavior.
> @ktsakalozos @joedborg thoughts on this?

please see version above.

**Comment by balchua** [comment]
Sorry i overlooked.  hmm in this case v1.20 containerd version isn't like the one I mentioned in this [comment](https://github.com/ubuntu/microk8s/issues/2558#issuecomment-914817754)

**Comment by ktsakalozos** [comment]
@sunhubs would it be possible to share the code of the `app_example` so I can see why it does not get terminated. I assume it does not get terminated, is it possible it re-spawns before the deployment backing it up stops?

**Comment by sunhubs** [comment]
@ktsakalozos from my side, it is normal nodejs or go application with http server. And we will handle TERM or HUP signal, but actually it seemed not to catch the signal. Will any signal sent when stop the cluster?

**Comment by ktsakalozos** [comment]
@anonymouse64, do you have any ideas on why this specific application is not killed when the containerd daemon is stopped? We have the daemons as "simple", see [1], and as far as I know all other processes/pods are stopped correctly when `microk8s.stop` is called.

@sunhubs it would have helped if we had a small code sample on how the pod traps and handles signals.

[1] https://github.com/ubuntu/microk8s/blob/1.20/snap/snapcraft.yaml#L29

**Comment by sunhubs** [comment]
@ktsakalozos i have prepared a sample code including deployment manifest, this appliance will not terminated when I stop the cluster. please see attached file.
[sample-node.tar.gz](https://github.com/ubuntu/microk8s/files/7135459/sample-node.tar.gz)

Another guessing, is there any option/configuration that will control the termination behavior?

**Comment by sunhubs** [comment]
> Well looking at the snapcraft.yaml for microk8s, I don't see anything that would change the default behavior for snap daemons which is to send SIGTERM to the main PID, and then SIGKILL to all child processes in the same control group, and then finally to send SIGKILL to the main PID if it hasn't exited after stop-timeout (which is like 90 seconds I think by default?)
> 
> That being said, for the microk8s snap since it uses the `kubernetes-support` for the containerd daemon, we are adding `Delegate=true` for the systemd unit for containerd, and as such all child processes that containerd spawns are the responsibility of containerd to reap/kill. This is to avoid CVEs/bugs such as https://ubuntu.com/security/notices/USN-4728-1

As I tried, SIGKILL is not allowed to build listener in Nodejs. And SIGKILL is able to catch but also not worked in Golang.

**Comment by balchua** [comment]
@sunhubs do you think this may help?
https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals

**Comment by sunhubs** [comment]
> @sunhubs do you think this may help?
> https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals

@balchua i think it is not the issue, because i directly delete the pod using kubectl command, I will see the log of previous pod shows it catch the signal.

**Comment by anonymouse64** [comment]
Sorry if I wasn't clear, but this seems to be a bug in containerd where containerd doesn't kill the process properly when you set up some signal handling. I'm not really an expert in containerd and it's signal handling, so I will leave that to others to sort out, but there is nothing on the snapd side of things that might be affecting this AFAICT.

**Comment by sunhubs** [comment]
Good news: new microk8s version 1.22 has no such issue now
