### ISSUE TITLE
Run commands w/o sudo

### ISSUE THREAD

**Issue by virtualstaticvoid** [ubuntu/microk8s#256]
Is it possible to run the `microk8s.*` commands without needing to enter my password for `sudo`?

E.g. Running `microk8s.docker images` prompts for a password.

```
$ microk8s.docker images
[sudo] password for $USER: ***** 
```

If it isn't currently possible, then perhaps it could be achived in a similar way to how docker allows this by adding the current user to the `docker` group; as described in [Post installation steps for Linux](https://docs.docker.com/install/linux/linux-postinstall/).

**Comment by littlell** [comment]
+1

**Comment by Soullivaneuh** [comment]
It would be great for local development.

Anybody did find a workaround? Maybe with sudoers?

**Comment by Soullivaneuh** [comment]
One thing I don't understand:

```
~ at ☸️  microk8s 
➜ ls -l /var/snap/microk8s/current/docker.sock
srw-rw---- 1 root docker 0 févr. 24 17:41 /var/snap/microk8s/current/docker.sock

~ at ☸️  microk8s 
➜ groups                                      
sullivan adm cdrom sudo dip plugdev lpadmin sambashare docker
```

As I'm part of group `docker`, why am I not able to run `microk8s.docker info` command wihtout sudo password prompt?

**Comment by dralves** [comment]
this is indeed a bit annoying. reading the microk8s wrappers seems sudo is used in the docker wrapper script meaning it's not a matter of permissions to the docker unix socket.

I found unaliasing microk8's docker and using an apt installed docker client instead, in addition to setting the DOCKER_HOST env var to point to microk8s docker socket, solves this problem.
