### ISSUE TITLE
update tutorial "common issues" to include a note about DNS and hostnames

### ISSUE THREAD

**Issue by nobletrout** [ubuntu/microk8s#2562]
I don't know where this belongs, but I think this might be the spot
On the page for troubleshooting https://microk8s.io/docs/troubleshooting

can we add a note about the following issue:
```
are you getting a note about timeouts?
kubectl logs microbot-5f5499d479-lmcnm
Error from server: Get "https://racoon:10250/containerLogs/default/microbot-5f5499d479-lmcnm/microbot": dial tcp 192.0.0.2:10250: i/o timeout

make sure your hostname resolves correctly to the IP address of your host or localhost!
```

I was banging my head against this issue for a few days on and off, and didn't realize that my machine had been repurposed for a different set of activities before that required some creative name resolution and routing. The IP address 192.0.0.2 was not present on any of my interfaces, and it wasn't until I coaxed this error message that I made the connection between hostname and IP address and examined my /etc/hosts file.

**Comment by ktsakalozos** [comment]
Thank you for pointing this out @nobletrout .

I just updated the https://discuss.kubernetes.io/t/troubleshooting/11267 with an extra `common issue` entry.
