### ISSUE TITLE
microk8s.daemon-kubelet fails after a fresh microk8s installation

### ISSUE THREAD

**Issue by nemtrif** [ubuntu/microk8s#257]
Installed microk8s and the status is showing the service is not running. Relevant lines from the journal:

Dec 20 14:46:31 vagrant microk8s.daemon-kubelet[25485]: F1220 14:46:31.506934   25485 server.go:165] listen tcp 0.0.0.0:10255: bind: address already in use
Dec 20 14:46:31 vagrant systemd[1]: snap.microk8s.daemon-kubelet.service: Main process exited, code=exited, status=255/n/a
Dec 20 14:46:31 vagrant systemd[1]: snap.microk8s.daemon-kubelet.service: Unit entered failed state.
Dec 20 14:46:31 vagrant systemd[1]: snap.microk8s.daemon-kubelet.service: Failed with result 'exit-code'.
Dec 20 14:46:31 vagrant systemd[1]: snap.microk8s.daemon-kubelet.service: Service hold-off time over, scheduling restart.
Dec 20 14:46:31 vagrant systemd[1]: Stopped Service for snap application microk8s.daemon-kubelet.
Dec 20 14:46:31 vagrant systemd[1]: snap.microk8s.daemon-kubelet.service: Start request repeated too quickly.
Dec 20 14:46:31 vagrant systemd[1]: Failed to start Service for snap application microk8s.daemon-kubelet.
Dec 20 14:46:31 vagrant systemd[1]: snap.microk8s.daemon-kubelet.service: Unit entered failed state.
Dec 20 14:46:31 vagrant systemd[1]: snap.microk8s.daemon-kubelet.service: Failed with result 'start-limit-hit'.
[inspection-report-20181220_145323.tar.gz](https://github.com/ubuntu/microk8s/files/2700342/inspection-report-20181220_145323.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @nemtrif 

Apologies for the late reply... vacations.

In any case, I see you are running your own kubelet. Could you retry on a clean system?

Thanks

**Comment by nemtrif** [comment]
Hi @ktsakalozos ,

Thanks for the reply.

That was my first thought, but there is not other kubelet. The only kubelet service on my machine is the one installed by microk8s.


Maybe I should add that I am running it on a virtual machine. When I tried it at home with a Linux laptop it worked fine.

**Comment by jamesloo** [comment]
Hi

I also ran into the same issue on my virtual machine (Ubuntu 18.04.2 LTS running on Hyper-V).   Is there a workaround or fix for this?

Thanks

**Comment by miklish** [comment]
I have the exact same issue jamesloo and nemtrif. Ubuntu 16.0.4 on virtualbox Windows 10. Exact same error messages in journal immediately after a fresh install.

**Comment by gbroten-diitalk** [comment]
microk8s.stop
microk8s.start
microk8s.inspect
This cleared the failure for me ... Ubuntu 18.04.2 LTS

**Comment by paulocaldeira17** [comment]
I'm having the same issue Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1033-raspi2 aarch64).

**Comment by paulocaldeira17** [comment]
I've added `cgroup_enable=memory cgroup_memory=1` to `/boot/firmware/cmdline.txt` file and it solved the issue to me.
You `/boot/firmware/cmdline.txt` file should look to something like this:
```bash
cgroup_enable=memory cgroup_memory=1 net.ifnames=0 dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait
```
Please let me know if it helped you.

**Comment by ktsakalozos** [comment]
@paulocaldeira17 for reference there is this blog post that shows MicroK8s on rpi3 https://blog.ubuntu.com/2019/02/27/single-node-kubernetes-on-raspberry-pi-microk8s-ubuntu
