### ISSUE TITLE
GPU add-on stopped working with containerd in 1.21 - can't find nvidia runtime

### ISSUE THREAD

**Issue by robotrapta** [ubuntu/microk8s#2575]
Hi there!  I've been using microk8s with GPU on 1.20 for a while, and it was awesome.  But trying to upgrade to 1.21, everything breaks.  After resisting the upgrade for a while, I finally went through simple repro steps to confirm that the problem really is with `1.21`, and not me, because when I run these same steps on a clean instance with `1.20` it just works, which is what I expect out of clean-simple-awesome microk8s.

## Clean Repro:

On AWS, launch a g4dn.xlarge instance running Ubuntu 20.04.  Run these commands:

```
sudo snap install microk8s --channel=1.21/stable --classic
sudo usermod -a -G microk8s ubuntu
sudo chown -f -R ubuntu ~/.kube
sudo apt-get update
sudo apt install -y nvidia-driver-470
sudo reboot now
# log in again
microk8s.enable gpu
sleep 600 # oh boy this is slow
microk8s.kubectl get pods -n gpu-operator-resources
```

and it's not working:

```
NAME                                           READY   STATUS                  RESTARTS   AGE
pod/nvidia-device-plugin-daemonset-rgl9z       0/1     Init:0/1                0          3m57s
pod/nvidia-dcgm-xdgmm                          0/1     Init:0/1                0          3m57s
pod/nvidia-operator-validator-fbv4f            0/1     Init:0/4                0          3m57s
pod/nvidia-dcgm-exporter-6rd66                 0/1     Init:0/1                0          3m57s
pod/gpu-feature-discovery-6q9pb                0/1     Init:0/1                0          3m57s
pod/nvidia-container-toolkit-daemonset-c8d26   0/1     Init:0/1                0          3m57s
pod/nvidia-driver-daemonset-44xh2              0/1     Init:CrashLoopBackOff   6          11m
```

Looking at various pods' error messages, many of them say:

```
  Warning  FailedCreatePodSandBox  13s (x16 over 3m26s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "nvidia" is configured
```

where the useful part is (so you don't have to scroll):

```
no runtime for "nvidia" is configured
```

## Discussion

Much has been written about how to enable the nvidia runtime for docker, but microk8s doesn't use docker by default any more.  Nvidia announced support for nvidia-runtime support for containerd, but the instructions are a big old mess of helm files, which is what microk8s is supposed to avoid.  If additional steps are expected, they should be documented.  Currently the [doc page](https://discuss.kubernetes.io/t/add-on-gpu/11286) just says that you obviously need a GPU and the drivers installed.  If you click through to the comments there's one from a year ago noting that you'll need to switch to docker runtime for it to work, and an empty rebuttal.

I'll note again that in channel 1.20, the above steps just worked.  Well you didn't even need to look at the `gpu-operator-resources` namespace because it didn't exist - whatever it did, worked much faster and without all these pods.  Added complexity aside, this is a regression of functionality.

Maybe I could make this work by switching microk8s to use docker, and the nvidia-runtime there, but is that really what's expected?  Requiring docker seems like a regression as well.

`microk8s.inspect` tarball: 
[inspection-report-20210914_221125.tar.gz](https://github.com/ubuntu/microk8s/files/7165396/inspection-report-20210914_221125.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @robotrapta,

Would it be possible for you to try the v1.22 channel?

The v1.21 was the first release where we moved to the nvidia gpu-operator and things do not work as smoothly as we would like them to.

**Comment by robotrapta** [comment]
Oh, I didn't know 1.22 was stable.  That's great news.  And yes, 1.22 fixes the problem.  Thanks!
