### ISSUE TITLE
Certificates not re-generating after changing csr.conf.template

### ISSUE THREAD

**Issue by lukos** [ubuntu/microk8s#2576]
I have done this previously with no problems (about a year ago) on a single node cluster. I now have a 3 node cluster and am performing the same process on the master node i.e. editing /var/snap/microk8s/current/certs/csr/conf/template and then the docs say that now this should be spotted automatically and the certs re-generated but they are not.

When I try and connect externally, I still get the error "Unable to connect to the server: x509: certificate is valid for kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster, kubernetes.default.svc.cluster.local, not example.com"

I have tried stopping and starting microk8s like `microk8s.stop` and also rebooting the master node but none of these work.

The rendered csr template seems to only contain the original DNS and IP address entries and not the new DNS name and IP address I added.

I'm not sure if this is because it works different on HA clusters? Note that I have setup my LB to point the api requests only to a single node and this is the node that I have changed.

[inspection-report-20210915_112239.tar.gz](https://github.com/ubuntu/microk8s/files/7169615/inspection-report-20210915_112239.tar.gz)

**Comment by balchua** [comment]
Hi @lukos can you check if you have this file `/var/snap/microk8s/current/var/lock/no-cert-reissue`

It seems like the apiserver-kicker isn't triggering the certificate regeneration atleast I don't see it in the logs.

**Comment by lukos** [comment]
Yes, that file is there. Do you know why? Can I just delete it and it will all work?

**Comment by balchua** [comment]
The file is added during the join process.  Its added to avoid restarting the apiserver when network changes, especially on a multi node cluster.
I suggest to rename the file wait for the apiservice kicker to update the csr and certs then put back the file.  That should fix your issue.

**Comment by lukos** [comment]
Fantastic, that worked thanks. Is there a way this could be added to the docs somewhere for troubleshooting?

**Comment by balchua** [comment]
Yes we should probably update the docs in relation to this.

**Comment by evilnick** [comment]
I added this to the troubleshooting section. Not sure if it needs mentioning elsewhere also?

**Comment by balchua** [comment]
Troubleshooting page is great!
Thanks.  Im closing the issue now.

**Comment by felipegouveiae** [comment]
In my case I had to run the following commands to force the certificates re-generation:
`
sudo microk8s refresh-certs --cert ca.crt
sudo microk8s refresh-certs --cert front-proxy-client.crt
sudo microk8s refresh-certs --cert server.crt
`

**Comment by jrnp97** [comment]
> In my case I had to run the following commands to force the certificates re-generation:
> 
> sudo microk8s refresh-certs --cert ca.crt sudo microk8s refresh-certs --cert front-proxy-client.crt sudo microk8s refresh-certs --cert server.crt

I think, it's worth to include this in the troubleshooting section, how could it be possible?
