### ISSUE TITLE
microk8s installer setting up path incorrectly

### ISSUE THREAD

**Issue by A7exSchin** [ubuntu/microk8s#2578]
After a standard installation of MicroK8s on Windows 10 with the provided installer it sets the path variables to

`C:\Program ????U??`
and
`C:\Program Files\MicroK谸�^딠І땨І`

Only thing I have changed is the installation path of multipass.

**Comment by joedborg** [comment]
Fixed as part of https://github.com/ubuntu/microk8s/issues/2639
