### ISSUE TITLE
NetworkPolicy support

### ISSUE THREAD

**Issue by Philippe-Collignon** [ubuntu/microk8s#258]
Hello,
Is there any support for networkpolicies in microk8s ?
(calico CNI plugin or any other network plugin with NetworkPolicy support ?)
Thanks

**Comment by phcollignon** [comment]
Hello ! Any plan to support NetworkPolicy yet ? 
Is there an easy way to change the network plugin ?

**Comment by ktsakalozos** [comment]
Hi @phcollignon we are releasing today to stable a cilium add-on. You should be able to get it with:
```
# make sure you run the latest revision, as this addon is released today
sudo snap install microk8s --classic
sudo microk8s.enable cilium
```  
This add-on will install the [cilium](https://cilium.io/) network plugin and allow setting network policies.  
We appreciate any feedback, as this is the first time this addon is included in MicroK8s.

**Comment by phcollignon** [comment]
Hi, a small feedback as requested to tell you that networkpolicies support is working with cilium plugin.  Thanks for that new feature.

**Comment by ktsakalozos** [comment]
You have to thank @joestringer and the folks at https://cilium.io/ for their contribution.
