### ISSUE TITLE
kubelite fills syslog

### ISSUE THREAD

**Issue by kanimaru** [ubuntu/microk8s#2580]
Hi I run 4 x Raspi Pi 4b on Ubuntu 20.04.3 and I get all 30 seconds this logs. Im not sure if its problematic. But it would be cool to stop it that the SD cards dont break this fast. Does someone has a clue?
```
Sep 20 21:13:56 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:13:56.721384    1787 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///var/snap/microk8s/2347/var/kubernetes/backend//kine.sock  <nil> 0 <nil>}] <nil> <nil>}
Sep 20 21:13:56 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:13:56.721414    1787 clientconn.go:948] ClientConn switching balancer to "pick_first"
Sep 20 21:14:30 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:14:30.651939    1787 client.go:360] parsed scheme: "passthrough"
Sep 20 21:14:30 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:14:30.652097    1787 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///var/snap/microk8s/2347/var/kubernetes/backend//kine.sock  <nil> 0 <nil>}] <nil> <nil>}
Sep 20 21:14:30 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:14:30.652155    1787 clientconn.go:948] ClientConn switching balancer to "pick_first"
Sep 20 21:15:01 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:15:01.432118    1787 client.go:360] parsed scheme: "passthrough"
Sep 20 21:15:01 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:15:01.432276    1787 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///var/snap/microk8s/2347/var/kubernetes/backend//kine.sock  <nil> 0 <nil>}] <nil> <nil>}
Sep 20 21:15:01 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:15:01.432338    1787 clientconn.go:948] ClientConn switching balancer to "pick_first"
Sep 20 21:15:32 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:15:32.614834    1787 client.go:360] parsed scheme: "passthrough"
Sep 20 21:15:32 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:15:32.617552    1787 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///var/snap/microk8s/2347/var/kubernetes/backend//kine.sock  <nil> 0 <nil>}] <nil> <nil>}
Sep 20 21:15:32 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:15:32.617647    1787 clientconn.go:948] ClientConn switching balancer to "pick_first"
Sep 20 21:16:09 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:16:09.832257    1787 client.go:360] parsed scheme: "passthrough"
Sep 20 21:16:09 k8s-1 microk8
s.daemon-kubelite[1787]: I0920 21:16:09.832391    1787 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///var/snap/microk8s/2347/var/kubernetes/backend//kine.sock  <nil> 0 <nil>}] <nil> <nil>}
Sep 20 21:16:09 k8s-1 microk8s.daemon-kubelite[1787]: I0920 21:16:09.832441    1787 clientconn.go:948] ClientConn switching balancer to "pick_first"
```

[inspection-report-20210920_211945.tar.gz](https://github.com/ubuntu/microk8s/files/7198911/inspection-report-20210920_211945.tar.gz)

**Comment by taintedkernel** [comment]
I have also noticed this recently.  Attempted a few things to reduce the log level; `-l=error` to kubelite as [given of an example to containerd](https://microk8s.io/docs/configuring-services), but it does not appear to be a valid flag.  Also tried `--v=2` to kube-apiserver arguments and restarted the services but noticed no change.

I am not familiar enough with the inner workings of the various microk8s components to figure this out quickly.  Similar previous issues made me hack together a simple rsyslog filter, so I'll probably go that route again as it seems quick and easy to target specific log messages.

**Comment by balchua** [comment]
Hi these logs might not be coming from the apiserver alone.
Can you try adding `--v 2` on kube-apiserver, kubelet, kube-controller, kube-proxy and scheduler?  See if it reduces the logs

**Comment by kanimaru** [comment]
Hi I tried it but seems much more verbose then before.

**Comment by balchua** [comment]
Ok so setting it to `--v 0` will only show critical logs.  What you are seeing without setting any `--v` is the default verbosity of kubernetes control plane components.

But if you want to preserve your storage device maybe setting you journal to volatile as described here.
https://www.freedesktop.org/software/systemd/man/journald.conf.html

This is done by editing `/etc/systemd/journald.conf` setting `Storage=volatile`

**Comment by kanimaru** [comment]
--v 0 was also more logs somehow ill go with Storage=volatile that works for me thx
