### ISSUE TITLE
Very strange working with insecure registry

### ISSUE THREAD

**Issue by renatgb** [ubuntu/microk8s#2582]
Hello. I have 2 deployments named as "crm" and "elasticsearch".
I also have insecure registry on http:tools.mydomain.com:5000 and docker, microk8s known about this (all restarted after).

`containerd-template.toml`
![изображение](https://user-images.githubusercontent.com/59174096/134186893-e0d78e76-a433-4cac-8afa-c6da6863e136.png)

`docker configuration (/var/snap/docker/current/config)`
![изображение](https://user-images.githubusercontent.com/59174096/134187114-9594e659-212a-4668-8ab9-1c3c5222b0e6.png)

And my 2 deployments (you need to look at containers)
**CRM**
![изображение](https://user-images.githubusercontent.com/59174096/134187403-6f301c7a-3e5b-4ba9-ab91-6a0d0c7275eb.png)
**ELASTICREARCH**
![изображение](https://user-images.githubusercontent.com/59174096/134187500-fffe841f-73f3-446d-9f1d-a5b969c9f3a8.png)

When I apply file with crm deployment - all ok, and image pulled successfull..
![изображение](https://user-images.githubusercontent.com/59174096/134187921-f1b407e7-8119-445b-aa30-955a0a469c07.png)

But microk8s for a elasticsearch deployment says:
![изображение](https://user-images.githubusercontent.com/59174096/134188429-8b1a57a5-bdbc-49be-bf29-db356cd18139.png)

Why?
I have no idea. But each time first deployment work and image will be pulled always successful...
Secondary deployment fails each time with same error if current node has other pods or not.

Docker can pull image 
![изображение](https://user-images.githubusercontent.com/59174096/134189185-3aaceeb7-7a6b-4198-a810-1c7b32c4b06c.png)

differences between images in size:
elastic ~ 740 mb
crm ~ 200 mb

Pls, help!

 Inpection https://first_example.hb.bizmrg.com/inspection-report-20210921_170451.tar.gz

**Comment by renatgb** [comment]
![изображение](https://user-images.githubusercontent.com/59174096/134190796-f7476beb-b821-4ce7-a0ae-8dd9be8c53b2.png)

**Comment by polyedre** [comment]
Could you check if the `imagePullPolicy` could be related to the problem? It seems to me that this is the only difference between the two deployments

**Comment by renatgb** [comment]
Sorry, but imagePullPolicy not related with given error response. When microk8s pulling image he tryes https url, but why if i put into settings "http:/tools.myserver.com:5000" and it works with crm, but not work with elasricsearch.

**Comment by renatgb** [comment]
Same error. No changes :)
![изображение](https://user-images.githubusercontent.com/59174096/134197245-36d125c4-9aed-4e3e-ad9a-c54a77fa2737.png)

**Comment by renatgb** [comment]
No changes  :)
![изображение](https://user-images.githubusercontent.com/59174096/134197649-235730d1-22ca-4edc-b13e-54e269b75fd1.png)

**Comment by polyedre** [comment]
And what if you switch the two images in the deployments (replace tools.[...]:5000/dev.elasticsearch:21.09.21 with tools.[...]:5000/dev.crm:21.09.21 and also the other way)? This may help identify if the problem resides in the configuration or in the images

**Comment by renatgb** [comment]
Ok. I found some errors. I will describe it later... Maybe this is bug
