### ISSUE TITLE
A disorienting message, when a container pulling fails.

### ISSUE THREAD

**Issue by renatgb** [ubuntu/microk8s#2585]
Hello!
Is this bug or not ? Is this related to microk8s, ctr  or pure k8s? 

**Example (trivial):**
we have deployment with multiple containers (2, 3, 5 - no sence).
if name of first container is corrupted (typo), then ALL containers fails with a error message _"server gave HTTP response for HTTPS client"_.
This error message means, that we have not change settings for a insecure registry.

Ok, I will change a name for the first container - all pulling successfully without error.

I mean that the folliwing (understandable) error maybe sound like _"Container with name 'bla bla bla' not found .. Change name or tag"_

Tnx!!

**Comment by balchua** [comment]
That error message is from containerd.  I don't think microk8s can do anything with that.
