### ISSUE TITLE
Prometheus exportere cant' find  port

### ISSUE THREAD

**Issue by sandroden** [ubuntu/microk8s#2589]
Hi, I've enable prometheus plugin on a 2 node microk8s cluster and 2 pods are not running:

```
# kubectl get -n monitoring pods
NAME                                   READY   STATUS    RESTARTS   AGE
prometheus-k8s-0                       2/2     Running   0          174m
alertmanager-main-0                    2/2     Running   0          174m
node-exporter-bsk5d                    0/2     Pending   0          75m
node-exporter-vxtm7                    0/2     Pending   0          75m
prometheus-adapter-69b8496df6-xpwft    1/1     Running   1          175m
grafana-6b8df57c5b-67md6               1/1     Running   1          175m
prometheus-operator-7649c7454f-677tc   2/2     Running   2          175m
kube-state-metrics-78dc55b74b-xqpcg    3/3     Running   4          175m
```
kubectl describe shows event that complains:

```
kubectl describe -n monitoring pods node-exporter-bsk5d
...
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  62m   default-scheduler  0/2 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match Pod's node affinity/selector.
```
Why should a port not be available?
I guess the 2 pods are on different nodes, but are not yet assigned to a node.

[inspection-report-20210923_165259.tar.gz](https://github.com/ubuntu/microk8s/files/7219457/inspection-report-20210923_165259.tar.gz)

**Comment by balchua** [comment]
The node exporter uses `hostPort` and `hostNetwork` `9100`.
If your nodes already uses that port, then it will not be able to bind to that.

**Comment by sandroden** [comment]
That was it. I had Traefik's metric listening on that port (installed via helm). Sorry for the noise.
May I just suggest you add the port number in the message, that would have been easier to spot.

**Comment by balchua** [comment]
The prometheus addon is taken from the upstream kube-prometheus.  I don't think microk8s can do anything with the messages.
Plus the error is detected by kubelet before starting the pod.
