### ISSUE TITLE
nginx pod fails after microk8s update t 1.22.3+

### ISSUE THREAD

**Issue by frendcarlo** [ubuntu/microk8s#2595]
the nginx pod is no longer running after an update to 1.22.3+. any idea how to fix this?

**Comment by frendcarlo** [comment]
made a fix by updating image of nginx daemonsets to point to this version k8s.gcr.io/ingress-nginx/controller:v1.0.0@sha256:0851b34f69f69352bf168e6ccf30e1e20714a264ab1ecd1933e4d8c0fc3215c6  and the error dissappear

**Comment by ktsakalozos** [comment]
Hi @frendcarlo 

Could you provide some more info as to how/why the nginx controller stopped working on v1.22.3? I assume you are doing your own builds or 1.22.3-rc0 ?

**Comment by ktsakalozos** [comment]
I cannot confirm this issue. The ingress controller on 1.22.3-rc.0 looks fine to me.

**Comment by frendcarlo** [comment]
I made some changes on daemonsets nginx-ingress-microk8s-controller to add extra ports that i needed, but the container image is pointing to k8s.gcr.io/ingress-nginx/controller:v0.35.0, and after the update, this points to k8s.gcr.io/ingress-nginx/controller:v0.49.1 which causes the nginx pod fails to run because of this error  > Failed to list *v1beta1.Ingress: the server could not find the requested resource. 

I change this to v1.0.0 and it works fine now.

**Comment by balchua** [comment]
Oh i see,. When we upgrade microk8s, we don't upgrade addons previously enabled.  It has to be manually disabled/enabled.  For stateless services this is easy.

Moving from one version of kubernetes to another usually introduce breaking changes.  As such we recommend you use a specific `channel`
From v1.22 we upgraded nginx to the one that is compatible.  I think calico also needs some upgrade.

**Comment by frendcarlo** [comment]
i see, i will check calico, thanks for the info.

**Comment by taintedkernel** [comment]
Just chiming in here, I think I also hit this recently after an auto upgrade.  Did not have time to debug, but switched back to 1.22 and it was resolved.  I did not realize the addon disable/enable upgrade workflow was necessary but I see that in the docs now!
