### ISSUE TITLE
Openebs fails to install after Openebs 3.0 release

### ISSUE THREAD

**Issue by OhMyMndy** [ubuntu/microk8s#2600]
Openebs fails to install after Openebs 3.0 release

Temporary solution: pin the version to 2.x.x

**Comment by ktsakalozos** [comment]
Hi @OhMyMndy, thank you for reporting this. Could you tell us how the addon is failing? What should i do to reproduce the problem you are seeing? An inspection report might also help.

**Comment by OhMyMndy** [comment]
Not all the pods will start, probably because of some backwards incompatible changes in version 3.0.

Creating a new microk8s cluster and enabling openebs will fail, it doesn't say what is going wrong, but I figured it had to do with the new version of openebs being released a couple of days ago.

I copied the enable.openebs.sh file and added a fixed version (like in the pull request I created https://github.com/ubuntu/microk8s/pull/2601) and ran `SNAP_COMMON=/var/snap/microk8s/common SNAP_DATA=/var/snap/microk8s/2487 SNAP=/snap/microk8s/2487 bash enable.openebs.sh` which successfully installs and enables openebs

**Comment by ktsakalozos** [comment]
Thank you @OhMyMndy 

@niladrih from the openebs team has provided patches for all the MIcroK8s tracks. They are going through our CI now. Many thanks.

**Comment by ktsakalozos** [comment]
The openebs addon fixes have been released to the stable channels. Feel free to re open the issue if there are still problems.
