### ISSUE TITLE
Question: this repo participating in hacktoberfest?

### ISSUE THREAD

**Issue by csantanapr** [ubuntu/microk8s#2619]
Is this git repo participating in [hacktoberfest](https://hacktoberfest.digitalocean.com/resources/maintainers) this year?
If so then the topic hacktoberfest  needs to be added to the repo for the time period
If not that's cool also

Thank you

**Comment by ktsakalozos** [comment]
Hi @csantanapr, thank you for bringing this to our attention. Just added us to hacktoberfest. Looking forward for your PRs :)
