### ISSUE TITLE
Warnings when building the snap

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#2621]
When building the snap [1] we get some warnings. We should try to fix as many of those as we can.  

[1] https://github.com/ubuntu/microk8s/blob/master/docs/build.md

**Comment by MichaelCduBois** [comment]
@ktsakalozos I would like to look into these errors. When building the snap via `snapcraft` I get 21 lines containing the word `warning` before `Snapped microk8s_v1.22.2_amd64.snap` is complete. 

I have recorded a few of the errors below - would these be the errors referenced?
```
Warning: Stopping motd-news.service, but it can still be activated by:
  motd-news.timer
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Warning: couldn't identify filesystem type for fsck hook, ignoring.
libtool: install: warning: remember to run `libtool --finish /lib'
```

**Comment by ktsakalozos** [comment]
That's great news @MichaelCduBois 

The warnings I am referring to are the ones printed right before snapping:
``+ snapcraftctl prime
5465
The interpreter 'bash' for 'microk8s.wrapper' was resolved to '/bin/bash'.
5466
The command 'microk8s.wrapper' has been changed to '/bin/bash $SNAP/microk8s.wrapper' to safely account for the interpreter.
5467
A shell wrapper will be generated for command '/bin/bash $SNAP/microk8s.wrapper' as it does not conform with the command pattern expected by the runtime. Commands must be relative to the prime directory and can only consist of alphanumeric characters, spaces, and the following special characters: / . _ # : $ -
5468
The command 'wrappers/run-k8s-dqlite-with-args' for 'wrappers/run-k8s-dqlite-with-args' was resolved to 'microk8s-resources/wrappers/run-k8s-dqlite-with-args'.
5469
The command 'wrappers/run-k8s-dqlite-with-args' has been changed to 'microk8s-resources/wrappers/run-k8s-dqlite-with-args'.
5470
The interpreter 'bash' for 'microk8s-add-node.wrapper' was resolved to '/bin/bash'.
5471
The command 'microk8s-add-node.wrapper' has been changed to '/bin/bash $SNAP/microk8s-add-node.wrapper' to safely account for the interpreter.
5472
A shell wrapper will be generated for command '/bin/bash $SNAP/microk8s-add-node.wrapper' as it does not conform with the command pattern expected by the runtime. Commands must be relative to the prime directory and can only consist of alphanumeric characters, spaces, and the following special characters: / . _ # : $ -`
....
characters: / . _ # : $ -
5503
Snapping...
5504
Snapped microk8s_v1.22.2_amd64.snap
```

If you find others you can address too that would be great.

**Comment by MichaelCduBois** [comment]
@ktsakalozos Thanks for that clarification. Expect a PR later to resolve some of these warnings as I have a fix locally.
