### ISSUE TITLE
Cadvisor container_oom_events_total metric

### ISSUE THREAD

**Issue by jpuskar** [ubuntu/microk8s#2622]
Is it possible to get the container_oom_events_total metric with the integrated cadvisor that comes with microk8s?

It looks like this metric was added in March via this PR:
https://github.com/google/cadvisor/pull/2829/files

Apologies if this is already available and I just missed something.

**Comment by balchua** [comment]
Microk8s follows the upstream kubernetes components.  Looking at the kubernetes source for 1.22, it looks like it includes `github.com/google/cadvisor v0.39.2`.

That particular PR you linked is only included  from `v0.40` of cadvisor.  I guess we will have to wait for upstream to upgrade, or you deploy a newer version of cadvisor.
