### ISSUE TITLE
script/inspect.sh use of ifconfig/netstat commands

### ISSUE THREAD

**Issue by odufourc** [ubuntu/microk8s#2657]
Hello everyone,

When playing with microk8s with its command inspect, I came accross some error on ifconfig and netstat generated files :
```
ubuntu@odc-k8s:~/logs/inspection-report/network$ cat ifconfig 
/snap/microk8s/2551/inspect.sh: line 56: ifconfig: command not found
ubuntu@odc-k8s:~/logs/inspection-report/network$ cat netstat 
/snap/microk8s/2551/inspect.sh: line 55: netstat: command not found
```
[inspection-report-20211008_133310.tar.gz](https://github.com/ubuntu/microk8s/files/7345235/inspection-report-20211008_133310.tar.gz)

These errors are happening because the package net-tools wasn't installed by default on my Ubuntu image.
But there are 2 things to consider :
* these 2 commands have been deprecated for a while since they aren't maintained anymore and have been replaced by iproute2 tools, which their equivalent would be : 
  * ifconfig --> ip addr
  * netstat -lpn --> ss -lpn
* on some other Linux distributions, they aren't installed anymore by default, but iproute2 is

I did a little bit of playing with various Linux distributions (Arch, Debian, Ubuntu, Fedora, Centos, Alpine, ...) :
- ip addr works everywhere
- ss doesn't work only in Alpine by default (iproute2 package must be installed) and busybox

I can work on a short pull-request, but I wanted your opinions first.
1) Shall I just replace ifconfig and netstat with their counterparts ?
2) Shall I test replace ifconfig but test if ss is available or use netstat otherwise ?

**Comment by ktsakalozos** [comment]
Hi @odufourc, thank you for volunteering for this work, it has been in our backlog for a long time. I would prefer the first option to just replace the two utilities with their counterparts, I think it is cleaner. You could try to use those utilities from inside inside the snap (`/snap/microk8s/current`). If they are missing we could add them in the list [1].

[1] https://github.com/ubuntu/microk8s/blob/master/snap/snapcraft.yaml#L441
