### ISSUE TITLE
How about link to changelog and stable version info on frontpage?

### ISSUE THREAD

**Issue by anttilinno** [ubuntu/microk8s#268]
I was evaluating microk8s, but unfortunately there are problems with integrated docker (docker-proxy segfault). There are mentions that docker will be decoupled from microk8s, but there is no timeline.
There is no release info on homepage with changelog(or in repo). If decoupling is finished, I would like to revisit the project 😄 , but how do I know, what has changed?

**Comment by ktsakalozos** [comment]
Hi @anttilinno 

Major changes (such as the one you are waiting for) are part of the release announcement https://discuss.kubernetes.io/tags/microk8s . Another option you have is to "watch" the github project but unfortunately we do not do releases from there so there are no release change logs. 

If I understand your request correctly you would like us to have a way to notify users of new releases. Right?

Thank you for giving MicroK8s a try.

**Comment by anttilinno** [comment]
Yes, notification would be nice. If it is left to me to poll the project, I fear, I will forget the project. Old school mail subscription to announcements? 😆
