### ISSUE TITLE
KUBECONFIG environment value is not honoured!

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#270]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
Hello, I install 1.13.1 using snap. Why does it always use the config file in `/snap/microk8s/current/configs/`? I have a config in $HOME/.kube/config but it is never used at all even when the KUBECONFIG env is set!!!

**Comment by ktsakalozos** [comment]
Hi @khteh , is this a duplicate of https://github.com/ubuntu/microk8s/issues/259 ?

**Comment by ktsakalozos** [comment]
Closing in favor of  https://github.com/ubuntu/microk8s/issues/259
