### ISSUE TITLE
switch to CoreDNS as Kubernetes has done.

### ISSUE THREAD

**Issue by ljckennedy** [ubuntu/microk8s#271]
Kubernetes now uses coreDNS instead of kubeDNS.  See: https://kubernetes.io/docs/setup/release/notes/#kubernetes-1-13-release-notes

Minikube has already done this and OKD 4 will do this also.  Microk8s should do the same to maintain compatibility and improve flexibility.

Thanks.

**Comment by magne** [comment]
@ktsakalozos, should this replace the existing dns addon, or be a separate addon? If replacement, what about existing installations?

**Comment by ljckennedy** [comment]
My view, is it should be the new default.  but the old add-on should probably stay for a while but be marked as deprecated.  Just my opinion though..

**Comment by Xtigyro** [comment]
Yes - it should become the new default DNS resolution mechanism - the one from CoreOS.

**Comment by richardcase** [comment]
I agree it should be the new default

**Comment by ktsakalozos** [comment]
CoreDNS replaced KubeDNS in the commit:
https://github.com/ubuntu/microk8s/commit/4a1d2a7d17ddbebdad34418a78e981e4ee24680e

`microk8s.enable dns` will give you coredns.

**Comment by Xtigyro** [comment]
@ktsakalozos Thank you!

**Comment by ktsakalozos** [comment]
All the credit goes to @richardcase for driving this.
