### ISSUE TITLE
microk8s.docker drops passed environment variables

### ISSUE THREAD

**Issue by jgraettinger** [ubuntu/microk8s#272]
Example:
```console
johnny@boomer:~$ SOME_VAR=value microk8s.docker run --rm --env SOME_VAR alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=0f47b6dc0a69
HOME=/root
johnny@boomer:~$ SOME_VAR=value /snap/microk8s/current/usr/bin/docker -H unix:///var/snap/microk8s/current/docker.sock  run --rm --env SOME_VAR alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1c13d67e6e2f
SOME_VAR=value
HOME=/root
```

I'd expect to see `SOME_VAR` in both cases, but instead only see it by directly invoking `docker` outside of the `/usr/bin/snap` wrapper.

Thanks!

**Comment by ktsakalozos** [comment]
Thank you for reporting this issue @jgraettinger . Indeed this is not the expected behavior, we will probably need to rework the docker wrapper to pass any env variables down to the docker client https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-docker.wrapper

**Comment by lleontop** [comment]
Hi!

I have tested locally with adding the '-E' flag at sudo command of microk8s-docker.wrapper in order to pass the environmental variables to downstream process and worked successfully! @ktsakalozos If you think it's a good approach I would be happy contributing a PR for solving this!

```
SOME_VAR=value microk8s.docker run --rm --env SOME_VAR alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=c782ae1084ed
SOME_VAR=value
HOME=/root
```

**Comment by ktsakalozos** [comment]
Thank you for the fix @lleontop . `-E` sounds fine by me. Go ahead!
