### ISSUE TITLE
Pod is in the Pending state.

### ISSUE THREAD

**Issue by gastonborba** [ubuntu/microk8s#2728]
Everything was fine until the microk8s suddenly stopped.
I think I have reached the limit of cpu of the virtual machine.
I added more cpu to the virtual machine but with no luck.

❯ k get pods
NAME                        READY   STATUS        RESTARTS   AGE
microbot-5f5499d479-f2nn6   0/1     Pending       0          28m

**************************

❯ k describe pod microbot-5f5499d479-f2nn6  

Events:
  Type     Reason            Age    From               Message

  Warning  FailedScheduling  7m47s  default-scheduler  0/2 nodes are available: 1 Too many pods, 1 node(s) had taint {node.kubernetes.io/unreachable: }, that the pod didn't tolerate.
  Warning  FailedScheduling  6m28s  default-scheduler  0/2 nodes are available: 1 Too many pods, 1 node(s) had taint {node.kubernetes.io/unreachable: }, that the pod didn't tolerate.
[inspection-report-20211115_153017.tar.gz](https://github.com/ubuntu/microk8s/files/7540150/inspection-report-20211115_153017.tar.gz)

**************************

I tried:
k taint node  --all node.kubernetes.io/unreachable- 
No luck.

Any idea what I can do?
Greetings.

**Comment by ktsakalozos** [comment]
Maybe you are hitting the max limit of pods per node. Try setting the `--max-pods` argument in `/var/snap/microk8s/current/args/kubelet` to something larger than 110. And restart MicroK8s (`microk8s.stop; microk8s.start`).

[1] https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**Comment by gastonborba** [comment]
you were right! It works!
Thank you very much!
