### ISSUE TITLE
I need to add environment variables

### ISSUE THREAD

**Issue by vonvww** [ubuntu/microk8s#273]
I want to modify the environment variables

"/snap/microk8s/354/lib/systemd/system/docker.service" [readonly] 34L, 1184C

```
[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H fd://
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=1048576
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process
# restart the docker process if it exits prematurely
Restart=on-failure
StartLimitBurst=3
StartLimitInterval=60s

Environment="HTTP_PROXY=http://localhost:8118"
Environment="HTTPS_PROXY=http://localhost:8118"

[Install]
WantedBy=multi-user.target
"docker.service"                                                                                                  
"docker.service" E212: Can't open file for writing
Press ENTER or type command to continue
```

Do not modify ?

**Comment by ktsakalozos** [comment]
Hi @vonvww ,

I am afraid it is not possible to change the systemd service files. What you can do is to reconfigure the docker daemon service using command line arguments (via `/var/snap/microk8s/current/args/dockerd`) or environment variables (via `/var/snap/microk8s/current/args/dockerd-env`) or configuring dockerd via `/var/snap/microk8s/current/args/docker-daemon.json`.

What are you trying to achieve? It might be something we can help with.

Thanks

**Comment by vonvww** [comment]
Hi @ktsakalozos ，
Because there is a firewall, I can not download the image, need to configure the proxy server download, do not know where to add the proxy address，please help

pulling image "k8s.gcr.io/pause:3.1": Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

Thanks

**Comment by vonvww** [comment]
environment variables (via /var/snap/microk8s/current/args/dockerd-env) 
Add environment variables to download, thanks

**Comment by ktsakalozos** [comment]
There is a "Deploy Behind a Proxy" section in the README. Let me know if we can close this issue.

Thanks
