### ISSUE TITLE
FAIL:  Service snap.microk8s.daemon-kubelite is not running

### ISSUE THREAD

**Issue by wangqinghuan** [ubuntu/microk8s#2730]
Please run `microk8s inspect` and attach the generated tarball to this issue.

[inspection-report-20211116_153243.tar.gz](https://github.com/ubuntu/microk8s/files/7544216/inspection-report-20211116_153243.tar.gz)
We appreciate your feedback. Thank you for using microk8s.

**Comment by balchua** [comment]
@wangqinghuan care to elaborate a little bit about the cluster?
Is this a newly installed cluster or upgraded?

I see this error.  
```
Oct 22 09:01:48 ubuntu microk8s.daemon-kubelite[1085]: Error: open cluster.yaml node store: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
Oct 22 09:01:48 ubuntu microk8s.daemon-kubelite[1085]: F1022 09:01:48.534397    1085 daemon.go:67] API Server exited open cluster.yaml node store: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
O
```
Can you check the content of this file?
`/var/snap/microk8s/current/var/kubernetes/backend/cluster.yaml`. It maybe empty.

**Comment by wangqinghuan** [comment]
After reinstall, it works.
