### ISSUE TITLE
Make sudo requirement explicit

### ISSUE THREAD

**Issue by assafmendelson** [ubuntu/microk8s#274]
Currently when running micrk8s commands, sudo is implied, i.e. when doing for example microk8s.start, the internal wrapped start script runs some commands with sudo.

This means that sudo password is asked (or worse still implied from previously doing that).

A better way would be to require sudo be explicitly required (i.e. require doing sudo microk8s.start).

This could be relatively easily done by removing all cases where sudo is called and instead adding something like this:
```
if [ "$(id -u)" != "0" ]; then
	echo "This command must be run as root (or with sudo"
        exit 1
fi

```
in the beginning of the script

**Comment by assafmendelson** [comment]
@ktsakalozos I would suggest that any use of sudo should be explicit. This means that it is better to use it too much than hide it. For example it is true that microk8s.enabled ingress does not require root but microk8s.enable dns ingress would.

Logically the two are the same even if in fact enabling ingress can be done without sudo.

I would suggest that it is not unreasonable to say that any configuration of the cluster should require elevated privileges even if SOME could be done without.

**Comment by gfokkema** [comment]
Just hit this bug report while finding out why my script doesn't work.
If sudo usage was explicit I'd have known to edit sudoers before having to resort to google-fu ;)

Totally agree on this.
