### ISSUE TITLE
io.containerd.snapshotter.v1.overlaysfs/snapshots/ folder is growing

### ISSUE THREAD

**Issue by frendcarlo** [ubuntu/microk8s#2740]
Hi, after a couple of months, i notice that this folder is growing and i got notification about this file /var/snap/microk8s/common/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/3/fs/usr/lib64/libcurl.so.4.5.0: Unix.Trojan.Coinminer-9910195-0 FOUND 

Is there a way to clean this up?

**Comment by balchua** [comment]
That directory contains the containers you are running.  Check this one https://github.com/ubuntu/microk8s/issues/482
