### ISSUE TITLE
Upgrading issues (or standard way of upgrading ) of Microk8s from 1.21 to 1.22 

### ISSUE THREAD

**Issue by santhoshcameo** [ubuntu/microk8s#2749]
Hi Team,

I was trying to upgrade our single node software system which is running on top of Microk8s 1.18  to 1.22.

From 1.18 to 1.21 I was able to update the system using the below command and the system worked flawlessly.

`sudo snap refresh microk8s --channel=1.21/stable`

But I have used the same for 1.22 as well, and the system was not even loading the home page,  ( we are using keycloak and louketo for the routing and management)

The software system containers many docker containers, helm charts, Service.YAML files, deployment files, values files, etc.

So I am interested to know is there any inbuilt mechanism I can make use of to upgrade the system which updates all deprecated APIS automatically?

Of course, I can provide more logs as well, but only the search and replace is the viable option for the 1.21 to 1.22 upgrade by finding each deprecated APIS from release notes? 

Please help me to understand.

**Comment by balchua** [comment]
Unfortunately this is not something built-in in Microk8s nor the kubernetes upstream.
Kubernetes logs warning on deprecated api/versions.
In my work, cluster upgrades is not just an hour work.  Takes careful planning and of course those you mentioned incompatible resources.

**Comment by santhoshcameo** [comment]
thank you @balchua
