### ISSUE TITLE
Upgrading from 1.20 to 1.21 failed, kubelite unstable

### ISSUE THREAD

**Issue by vincentheet** [ubuntu/microk8s#2771]
Hi,

We have microk8s 1.20 running and tried upgrading to 1.21 multiple times. The last time we tried the upgrade failed due to an unstable kubelite, the process keeps exiting and restarting. Based on the logs we where unable to point a root cause on how to fix this issue. We also tried upgrading directly to 1.22 but also without success. I added the inspect tarball. I hope we can get some pointers on how to successfully upgrade to 1.21.

Thanks in advance!
[inspection-report-20211111_124059.tar.gz](https://github.com/ubuntu/microk8s/files/7632767/inspection-report-20211111_124059.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @vincentheet I see int he logs this error causing kubelet to fail to start:
```
Nov 11 11:51:12 00-avl-lb1 microk8s.daemon-kubelite[19461]: E1111 11:51:12.721175   19461 server.go:158] "Failed to parse kubelet flag" err="unknown flag: --enable-cadvisor-json-endpoints"
```

You can check the logs of the k8s services with `journalctl -fu snap.microk8s.daemon-kubelite` .

**Comment by vincentheet** [comment]
We indeed enable this flag, we will disable it and try to upgrade again soon. Thanks for your support!

**Comment by vincentheet** [comment]
Disabling the cadvisor json endpoints dit resolve the issue. Thank you.
