### ISSUE TITLE
can microk8s run docker compose config file?

### ISSUE THREAD

**Issue by littlell** [ubuntu/microk8s#278]
ERROR: for dev_zookeeper  Cannot start service zookeeper: driver failed programming external connectivity on endpoint dev_zookeeper (ffcf5bf259adf10d7327fa2a6c3652e69700df6689f7aef69d56af486293ebaa): Error starting userland proxy:

**Comment by littlell** [comment]
I encountered these errors..

**Comment by ktsakalozos** [comment]
Hi @littlell 

I had mixed success with docker compose files. After transforming the docker yaml files to kubernetes yaml manifests with kompose (https://github.com/kubernetes/kompose) I sometimes had to manually tweak some missing service references.

Could you share the docker yaml you are using?

Thank you for using MicroK8s.

**Comment by ktsakalozos** [comment]
Hey @littlell, have a look at this comment https://github.com/ubuntu/microk8s/issues/173#issuecomment-455126651 it might resolve the error you have.

**Comment by littlell** [comment]
> Hi @littlell
> 
> I had mixed success with docker compose files. After transforming the docker yaml files to kubernetes yaml manifests with kompose (https://github.com/kubernetes/kompose) I sometimes had to manually tweak some missing service references.
> 
> Could you share the docker yaml you are using?
> 
> Thank you for using MicroK8s.

Thanks for your reply, I'll try kcompose and check if problem will disappear, and then I'll share the compose file .
