### ISSUE TITLE
Upgrade dashboard to v2.3.0 to fix ingress API 404

### ISSUE THREAD

**Issue by hryyan** [ubuntu/microk8s#2791]
When using 1.22/stable, api/v1/ingress/default return 404.

From Kubernetes v1.19, Ingress resources API had moved to networking.k8s.io/v1. Kubernetes Dashboard fix that in [v2.3.0](https://github.com/kubernetes/dashboard/releases/tag/v2.3.0). 

[inspection-report-20211209_022516.tar.gz](https://github.com/ubuntu/microk8s/files/7681752/inspection-report-20211209_022516.tar.gz)

**Comment by ktsakalozos** [comment]
Thank you @hryyan  for reporting this and the time an effort you spent on debugging what the issue is and offering a fix.

**Comment by rmannibucau** [comment]
up, this is quite bothering since it prevents to use some unrelated features too.

**Comment by martindines** [comment]
> up, this is quite bothering since it prevents to use some unrelated features too.
> 
> Edit: if you get this issue you can edit the dashboard deployment in kube-system and just upgrade to v2.4.0 tag instead of v2.2.0, will respawn the dashboard and all will work back :).

Awesome, that solved it for me, thanks a lot!
