### ISSUE TITLE
Traefik 2.3 is not compatible with kubernetes 1.22+

### ISSUE THREAD

**Issue by miro-balaz** [ubuntu/microk8s#2798]
pkg/mod/k8s.io/client-go@v0.18.2/tools/cache/reflector.go:125: Failed to list *v1beta1.Ingress: the server could not find the requested resource (get ingresses.extensions)

v1beta.Ingress is deprecated and removed in kubernetes 1.22, but treafik that can hande that is 2.5+, but microk8s currently install traefik 2.3 with kubernetes 1.22.

**Comment by balchua** [comment]
Where can i find this information?  As far as i know the v1beta deprecation is at kubernetes apiserver and not at the ingress controller.

**Comment by miro-balaz** [comment]
[link](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)

> Ingress
The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress is no longer served as of v1.22

It is not even possible to create such ingress route on such version of k8s.

**Comment by balchua** [comment]
@miro-balaz i see what you mean now.  If you're keen to help, we welcome PR to address this.

**Comment by v-bulynkin** [comment]
Is there a way to change traefik's version manually? The resource traefik.yaml file is read-only.

**Comment by balchua** [comment]
You can do `kubectl edit`

**Comment by ktsakalozos** [comment]
Closing this issue as the fix has been released on 1.22. Thank you for your help in spotting and addressing this issue.
