### ISSUE TITLE
Failed to pull image from AWS ECR to my localhost

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#281]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20190117_095100.tar.gz](https://github.com/ubuntu/microk8s/files/2768033/inspection-report-20190117_095100.tar.gz)

We appreciate your feedback. Thank you for using microk8s.
After `$(aws ecr get-login --no-include-email)`
No problem: `docker pull <aws_account>.dkr.ecr.ap-southeast-1.amazonaws.com/image:latest`
However, `k apply -f <foo>.yml` and `k describe pod pod-0` shows this:
```Failed to pull image "<aws_account>.dkr.ecr.ap-southeast-1.amazonaws.com/:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://<aws_account>.dkr.ecr.ap-southeast-1.amazonaws.com/v2/<foo>/manifests/latest: no basic auth credentials```

**Comment by ktsakalozos** [comment]
Hi @khteh 

I am not familiar with this setup but here are a few things you could check. I see you are using `docker pull` I assume this is an alias to `microk8s.docker`, right? Can you also make sure the script you source with `$(aws ....)` is using `microk8s.kubectl` and `microk8s.docker`?

**Comment by khteh** [comment]
@ktsakalozos, `docker` is not `microk8s.docker`. $(aws ...) is not using any script. It's awscli tool.

**Comment by khteh** [comment]
@ktsakalozos, microk8s.docker can pull the image successsfully from AWS ECR. The problem happens during `microk8s.kubectl apply -f app..yml`:

`  Warning  Failed             60s (x3 over 100s)  kubelet, ip-172-31-10-177  Failed to pull image "<aws_account>.dkr.ecr.ap-southeast-1.amazonaws.com/my_app:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://<aws_account>.dkr.ecr.ap-southeast-1.amazonaws.com/v2/my_app/manifests/latest: no basic auth credentials
`

**Comment by khteh** [comment]
Resolved with this: https://gist.github.com/AmitDJagtap/bdd65f8831c36b512e5e1dff1eab4224#file-ecr-cred-refresh-1-yml
