### ISSUE TITLE
Can't boot to Ubuntu

### ISSUE THREAD

**Issue by omarreda14** [ubuntu/microk8s#2811]
I had just logged out from my machine which has Ubuntu 18.04 , after an hour i couldn't log in again , i forced it to restart and i get this message :
![slack_image__2021-12-22_15-54-11-212_](https://user-images.githubusercontent.com/82273399/147114201-5ebc8b70-5700-4c4f-8a12-8804b2efae42.jpg)

Even if i tried to start the recovery mode .

Note : for some reasons i can't get the usb or the CD of the source OS

**Comment by balchua** [comment]
@omarreda14 I don't think this issue is related to microk8s.
