### ISSUE TITLE
Ingress Addon Does Not Have Correct RBAC Permissions

### ISSUE THREAD

**Issue by barrelmaker97** [ubuntu/microk8s#2815]
After updating my Microk8s instance to 1.23, I have also upgraded the ingress addon by disabling and re-enabling it. I also have the RBAC addon enabled. After checking the logs of the ingress controller pod after the upgrade, I can see that it is unable to update the proper ConfigMaps after the upgrade, specifically the log
```
E0102 01:42:42.313271       6 leaderelection.go:367] Failed to update lock: configmaps "ingress-controller-leader" is forbidden: User "system:serviceaccount:ingress:nginx-ingress-microk8s-serviceaccount" cannot update resource "configmaps" in API group "" in the namespace "ingress"
```
Example Screenshot:
![Screenshot from 2022-01-02 00-15-25](https://user-images.githubusercontent.com/19742024/147867809-860d38a2-871c-4c27-abf3-b69a5a03eddd.png)
After some investigation, I can see that the associated service account only has permission to update a ConfigMap named `ingress-controller-leader-public`, but the name of the ConfigMap it wants to update is named `ingress-controller-leader`. I verified this with the following commands:
```
barrelmaker@zeus:~$ kubectl describe roles.rbac.authorization.k8s.io -n ingress nginx-ingress-microk8s-role 
Name:         nginx-ingress-microk8s-role
Labels:       <none>
Annotations:  <none>
PolicyRule:
  Resources   Non-Resource URLs  Resource Names                      Verbs
  ---------   -----------------  --------------                      -----
  configmaps  []                 [ingress-controller-leader-public]  [create update]
  configmaps  []                 []                                  [get create]
  endpoints   []                 []                                  [get]
  pods        []                 []                                  [get]
  secrets     []                 []                                  [get]
barrelmaker@zeus:~$ kubectl get configmaps -n ingress 
NAME                                DATA   AGE
kube-root-ca.crt                    1      8h
nginx-ingress-tcp-microk8s-conf     0      8h
nginx-ingress-udp-microk8s-conf     0      8h
ingress-controller-leader           0      8h
nginx-load-balancer-microk8s-conf   7      8h
barrelmaker@zeus:~$ kubectl auth can-i update configmaps --as=system:serviceaccount:ingress:nginx-ingress-microk8s-serviceaccount -n ingress
no
```
I think the fix for this would just be to update the `nginx-ingress-microk8s-role` Role to have the correct resource name, but please let me know if there's a more elegant way to approach this.

[inspection-report-20220102_001222.tar.gz](https://github.com/ubuntu/microk8s/files/7798652/inspection-report-20220102_001222.tar.gz)

**Comment by balchua** [comment]
Thanks for pointing this out.  There's a PR addressing this issue.
https://github.com/ubuntu/microk8s/pull/2813

**Comment by ktsakalozos** [comment]
@barrelmaker97 thank you for reporting this and for doing the investigation. @balchua really appreciate the work on this patch.

The fix is merged and should land with the next k8s patch release.
