### ISSUE TITLE
Upgrade of Ingress Addon to 1.1.0

### ISSUE THREAD

**Issue by barrelmaker97** [ubuntu/microk8s#2816]
Are there any plans to upgrade to Nginx Ingress Controller v1.1.0?
https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.1.0
Happy to help if so 😁

**Comment by balchua** [comment]
There's a PR https://github.com/ubuntu/microk8s/pull/2813 addressing the rbac issue and also upgrade the nginx ingress version.

**Comment by ktsakalozos** [comment]
@barrelmaker97 thank you for bringing the new ingress release to our attention. We also appreciate you volunteering for this work but unfortunately @balchua was too fast :) . In the future I am sure you will have more chances to contribute to the project. 

The update will come with the next k8s patch release on 1.23 and onward.

Thank you both.
