### ISSUE TITLE
Broken snap revision (microk8s Rev 2821 on 1.20/edge) - "symbol lookup error: /snap/microk8s/2821/bin/dqlite: undefined symbol: sqlite3_system_errno""

### ISSUE THREAD

**Issue by joes** [ubuntu/microk8s#2831]
I was setting up a new developer environment with microk8s, channel 1.20/edge on multipass VM running "Ubuntu 20.04.3 LTS".

Installed microk8s and enabled some extensions:
```
snap install microk8s --classic --channel 1.20/edge
snap refresh microk8s
microk8s start
microk8s status --wait-ready
microk8s enable rbac dns dashboard ingress storage
microk8s status --wait-ready
```

The `microk8s status` command emits the following errors:

```
/snap/microk8s/2821/bin/dqlite: symbol lookup error: /snap/microk8s/2821/bin/dqlite: undefined symbol: sqlite3_system_errno
/snap/microk8s/2821/bin/dqlite: symbol lookup error: /snap/microk8s/2821/bin/dqlite: undefined symbol: sqlite3_system_errno
^CTraceback (most recent call last):
  File "/snap/microk8s/2821/scripts/wrappers/common/utils.py", line 89, in get_dqlite_info
    timeout=4,
  File "/snap/microk8s/2821/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/snap/microk8s/2821/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/snap/microk8s/2821/bin/dqlite', '-s', 'file:///var/snap/microk8s/2821/var/kubernetes/backend/cluster.yaml', '-c', '/var/snap/microk8s/2821/var/kubernetes/backend/cluster.crt', '-k', '/var/snap/microk8s/2821/var/kubernetes/backend/cluster
.key', '-f', 'json', 'k8s', '.cluster']' returned non-zero exit status 127
KeyboardInterrupt
```

Command `snap info` shows that microk8s, version v1.20.14, rev 2821 on channel 1.20/edge was installed.

I also have a three node pre-production cluster with microk8s (tracking 1.20/edge) on "Ubuntu 20.04.3 LTS" and saw that one of these nodes have been automatically refreshed to rev 2821 (the others are on rev 2763). I checked `microk8s status` on the refreshed node too to see if I got the same error there. However, the refreshed node's `microk8s status` command does not complete nor print anything at all and needs to be interrupted (CTRL+C).

The command `kubectl get nodes` does show that the nodes are in status `Ready`.

What should I do in order to recover to a stable state?

**Comment by joes** [comment]
Tried to uncordon, `microk8s stop`, reboot server and `microk8s start` again.

I then tried to run `microk8s status` again on the refreshed node but the command does not return anything. Stack trace upon keyboard interrupt is:

```
^CTraceback (most recent call last):
  File "/snap/microk8s/2821/scripts/wrappers/status.py", line 224, in <module>
    isReady = is_cluster_ready()
  File "/snap/microk8s/2821/scripts/wrappers/common/utils.py", line 54, in is_cluster_ready
    service_output = kubectl_get("all")
  File "/snap/microk8s/2821/scripts/wrappers/common/utils.py", line 166, in kubectl_get
    return run("kubectl", kubeconfig, "get", cmd, "--all-namespaces", die=False)
  File "/snap/microk8s/2821/scripts/wrappers/common/utils.py", line 35, in run
    args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env
  File "/snap/microk8s/2821/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/snap/microk8s/2821/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/snap/microk8s/2821/usr/lib/python3.5/subprocess.py", line 1715, in _communicate
    ready = selector.select(timeout)
  File "/snap/microk8s/2821/usr/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
```

**Comment by joes** [comment]
Last time this happened (in #2784) I was asked to switch from stable to edge to resolve the error.

**Comment by ktsakalozos** [comment]
Thank you @joes for reporting this and also many thanks for using the edge channel allowing us to detect such issues early on.

We are working on a fix that should land on the edge channel.

**Comment by ktsakalozos** [comment]
@joes we reverted the offending snap revision and we made sure that track will not get anymore updates since it is out of support. You can `snap refresh microk8s` in the failing nodes to get to a working state. Apologies for the inconvenience.

**Comment by joes** [comment]
The new revision got installed and everything seems OK to me.
