### ISSUE TITLE
microk8s status --wait-ready (hanging)

### ISSUE THREAD

**Issue by adgsenpai** [ubuntu/microk8s#2836]
I installed microk8s like this 
`sudo snap install microk8s --classic`

```
adgsenpai@flybyadgsenpai:~$ sudo microk8s status --wait-ready
^CTraceback (most recent call last):
  File "/snap/microk8s/2753/scripts/wrappers/status.py", line 222, in <module>
    isReady = wait_for_ready(timeout)
  File "/snap/microk8s/2753/scripts/wrappers/common/utils.py", line 130, in wait_for_ready
    time.sleep(2)
KeyboardInterrupt
```

After running `microk8s kubectl get all --all-namespaces`

Output 
```
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
```

Could it be a port issue?
Please let me know what is the issue tested on 3 of my linux machines.

**Comment by ktsakalozos** [comment]
Hi @adgsenpai, the `microk8s status --wait-ready` waits for two things, a) that the apiserver replies and b) there is at least one node registered. in this case it seems that the API server is not coming up. Could you please attach the inspection tarball you get with `microk8s inspect` so that we see what the problem is?

**Comment by adgsenpai** [comment]
Note that Docker is installed on the system

which can be verified by command in the bottom 

```
adgsenpai@flybyadgsenpai:~$ sudo docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.2
 Built:             Mon Nov  1 00:33:59 2021
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~20.04.2
  Built:            Fri Oct 22 00:45:53 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~20.04.1
  GitCommit:
 runc:
  Version:          1.0.1-0ubuntu2~20.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

I ran the `microk8s  inspect`  as requested below.

```
adgsenpai@flybyadgsenpai:~$ microk8s inspect
[sudo] password for adgsenpai:
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running

  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-kubelite is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster
Inspecting juju
  Inspect Juju
Inspecting kubeflow
  Inspect Kubeflow

WARNING:  Docker is installed.
File "/etc/docker/daemon.json" does not exist.
You should create it and add the following lines:
{
    "insecure-registries" : ["localhost:32000"]
}
and then restart docker with: sudo systemctl restart docker
Building the report tarball
  Report tarball is at /var/snap/microk8s/2753/inspection-report-20220114_171503.tar.gz
```

You can view the `Report Tarball` here.

[inspection-report-20220114_171503.tar.gz](https://github.com/ubuntu/microk8s/files/7872123/inspection-report-20220114_171503.tar.gz)

I will add `/etc/docker/daemon.json` as prompted above

```
File "/etc/docker/daemon.json" does not exist.
You should create it and add the following lines:
{
    "insecure-registries" : ["localhost:32000"]
}
```

I will report back to you if any further problems. If my microk8s works, I will close the issue.

Thanks for your assistance

Ashlin Darius Govindasamy

**Comment by ktsakalozos** [comment]
I see this is a RPi and it does not have the cgroups enabled:
```
Jan 14 17:14:27 flybyadgsenpai microk8s.daemon-kubelite[102873]: E0114 17:14:27.278079  102873 kubelet.go:1423] "Failed to start ContainerManager" err="system validation failed - Following Cgroup subsystem not mounted: [memory]"
Jan 14 17:14:27 flybyadgsenpai systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=1/FAILURE
```

Have you seen the installation instructions we have at https://microk8s.io/docs/install-alternatives#heading--arm ?

**Comment by adgsenpai** [comment]
> I see this is a RPi and it does not have the cgroups enabled:
> 
> ```
> Jan 14 17:14:27 flybyadgsenpai microk8s.daemon-kubelite[102873]: E0114 17:14:27.278079  102873 kubelet.go:1423] "Failed to start ContainerManager" err="system validation failed - Following Cgroup subsystem not mounted: [memory]"
> Jan 14 17:14:27 flybyadgsenpai systemd[1]: snap.microk8s.daemon-kubelite.service: Main process exited, code=exited, status=1/FAILURE
> ```
> 
> Have you seen the installation instructions we have at https://microk8s.io/docs/install-alternatives#heading--arm ?

I did not follow the installation instructions for the RPi. As I did the installation by `snap installer`. I will follow the guide and let you know. I will close the issue now. If there is another issue I will open up a new issue.

**Comment by saeid93** [comment]
Were you able to solve this? I'm having the same problem.

**Comment by aNDREUET648** [comment]
> Hi @adgsenpai, the `microk8s status --wait-ready` waits for two things, a) that the apiserver replies and b) there is at least one node registered. in this case it seems that the API server is not coming up. Could you please attach the inspection tarball you get with `microk8s inspect` so that we see what the problem is?

Sorry to bother you, but I face the same situation. Here is my inspection_report in case it could help you.

Regards

Andreu

[inspection-report-20220601_174341.tar.gz](https://github.com/canonical/microk8s/files/8815884/inspection-report-20220601_174341.tar.gz)

**Comment by brokercl** [comment]
same
