### ISSUE TITLE
1.23 - HA Disabled - Syslog flood with kubelite logs

### ISSUE THREAD

**Issue by tarteens** [ubuntu/microk8s#2863]
Hello, 
I'm currently upgrading my Microk8s to the lastest 1.23 version. 
Installed with a snap command : 
```
sudo snap install microk8s --channel=1.23/stable --classic
```
by default , the HA addon is enabled , and I'm getting lots of logs in the /var/log/messages with a fresh installation
```
Jan 21 08:43:23 <host> microk8s.daemon-kubelite: {"level":"warn","ts":"2022-01-21T08:43:23.705+0100","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000aab880/#initially=[unix:///var/snap/microk8s/2848/var/kubernetes/backend/kine.sock:12379]","attempt":0,"error":"rpc error: code = Unimplemented desc = unknown service etcdserverpb.Maintenance"}

```
as I don't need HA for my projet , i'm disabling it 

```
microk8s.disable ha-cluster --force
```

And now i'm getting tons of logs in the /var/log/messages 
```
Jan 21 08:51:48 <host> microk8s.daemon-kubelite: W0121 08:51:48.681218  126720 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {unix:///var/snap/microk8s/2848/var/kubernetes/backend/kine.sock:12379 kine.sock <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/2848/var/kubernetes/backend/kine.sock:12379: connect: connection refused". Reconnecting...
```

Is there something to be done to avoid having this flooding in the logs ?

Thanks for your help.

**Comment by ktsakalozos** [comment]
Hi @tarteens thank you for reporting this. We are working on addressing the two issues causing the excessive log messages.

There is a manual fix for the `"failed to connect to {unix:///....}"` message. After you `microk8s.disable ha-cluster --force` edit `/var/snap/microk8s/current/args/kube-apiserver` and remove the line `--etcd-servers="unix://${SNAP_DATA}/var/kubernetes/backend/kine.sock:12379"`, then restart MicroK8s with `microk8s stop; microk8s start`.

Apologies for the inconvenience, fixes should be out soon.

**Comment by tarteens** [comment]
Hello @ktsakalozos  ,
thank you for you quick response. Your workaround is working as expected. 

Thanks for that.
