### ISSUE TITLE
Bad gate way in Grafana when connecting to InfluxDB

### ISSUE THREAD

**Issue by ducminhnguyen** [ubuntu/microk8s#289]
Please run `microk8s.inspect
[inspection-report-20190122_192827.tar.gz](https://github.com/ubuntu/microk8s/files/2782555/inspection-report-20190122_192827.tar.gz)
We appreciate your feedback. Thank you for using microk8s.

I cannot get the influxdb to grafana. It always return 502 bad gateway error

**Comment by ktsakalozos** [comment]
Hi @ducminhnguyen 

Can you please describe what you are deploying and how it fails? Can you share the manifests you are applying and/or instructions on how your setup is supposed to look like and how it is failing? I basically asking for a way to reproduce the issue you are seeing.

Thanks

**Comment by heckad** [comment]
Hello, everybody. I have the same error. I only eval `microk8s.enable prometheus` and add the port forward to `svc/grafana 3000`.

**Comment by ktsakalozos** [comment]
After you enable prometheus and having the pods running, can you access grafana through its ClusterIP (with something like `http://10.152.183.153:3000/login`) ?

Can you help me reproduce this? How do you do the port forwarding? Are you running MicroK8s in a VM? Can you share the tarball from `microk8s.inspect`? Thanks

**Comment by heckad** [comment]
1) Yes, I can connect to grafana and success login, but when I try to see metrics I got a red triangle in the corner of the graph. In network tab I found requests with 502 error code on url `http://localhost:3000/api/datasources/proxy/1/api/v1/query?query=1%20-%20avg(rate(node_cpu_seconds_total%7Bmode%3D%22idle%22%7D%5B1m%5D))&time=1574896347`.

2) Port forwarding command: `k port-forward -n kubectl monitoring svc/grafana 3000`
3) No, I run MicroK8s on my vps. 
4) [inspection-report-20191128_001358.tar.gz](https://github.com/ubuntu/microk8s/files/3899116/inspection-report-20191128_001358.tar.gz)

Thanks

**Comment by heckad** [comment]
In grafana logs 

```
2019/11/29 22:05:44 http: proxy error: dial tcp 10.152.183.182:9090: connect: connection refused
t=2019-11-29T22:05:44+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query status=502 remote_addr=127.0.0.1 time_ms=8913 size=0 referer="http://localhost:3000/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-compute-resources-pod?refresh=10s&orgId=1"
2019/11/29 22:05:44 http: proxy error: context canceled
2019/11/29 22:05:44 http: proxy error: context canceled
t=2019-11-29T22:05:44+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query status=502 remote_addr=127.0.0.1 time_ms=1592 size=0 referer="http://localhost:3000/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-compute-resources-pod?refresh=10s&orgId=1"
t=2019-11-29T22:05:44+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query status=502 remote_addr=127.0.0.1 time_ms=328 size=0 referer="http://localhost:3000/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-compute-resources-pod?refresh=10s&orgId=1"
t=2019-11-29T22:05:44+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query status=502 remote_addr=127.0.0.1 time_ms=6625 size=0 referer="http://localhost:3000/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-compute-resources-pod?refresh=10s&orgId=1"
2019/11/29 22:05:44 http: proxy error: context canceled
2019/11/29 22:05:44 http: proxy error: context canceled
```

Any ideas?

**Comment by ktsakalozos** [comment]
@heckad we updated the prometheus operator addon [1]. Can you give the edge snap a try: 
```
sudo snap install microk8s --classic --edge
```

[1] https://github.com/ubuntu/microk8s/pull/823

**Comment by ktsakalozos** [comment]
I assume this is addressed. Please feel free to reopen this issue if you still see problems.
