### ISSUE TITLE
Microk8s is disabled

### ISSUE THREAD

**Issue by dza89** [ubuntu/microk8s#2891]
Microk8s is suddenly disabled, I have no idea why.

```
Name      Version    Rev    Tracking       Publisher   Notes
core      16-2.54.2  12603  latest/stable  canonical✓  core
core18    20211215   2284   latest/stable  canonical✓  base
microk8s  v1.23.2    2920   1.23/stable    canonical✓  disabled,classic
```

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```
This is the second time in two days that this is happening. If I reboot it works again.
What is the next step in debugging?

**Comment by dza89** [comment]
The problem seems to be snap autorefresh.
```
sudo snap enable microk8s
error: snap "microk8s" has "auto-refresh" change in progress
```

I wish you could install microk8s without snap.

**Comment by ktsakalozos** [comment]
Hi @dza89 you may want to look at [1] where we describe your options for handling snap refreshes.

[1] https://microk8s.io/docs/snap-refreshes

**Comment by dza89** [comment]
@ktsakalozos

Thanks, I checked microk8s troubleshooting but couldn't find anything there. I opted for offline install now, since my whole cluster is borked already which is a shame.

/close
