### ISSUE TITLE
microk8s.inspect takes a very long time

### ISSUE THREAD

**Issue by joestringer** [ubuntu/microk8s#295]
I recently upgraded microk8s, and for some reason the apiserver would not run on port 8080.

In an attempt to diagnose the problem, I ran `microk8s.inspect`. Here's the output:

```
[Jan 25 10:34:43 PST] cilium $ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-docker is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster

 WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT                                                                                                                 
Building the report tarball
  Report tarball is at /var/snap/microk8s/383/inspection-report-20190125_104231.tar.gz
[Jan 25 10:42:32 PST] cilium $
```

As can be seen from my shell timestamps, it took about eight minutes to gather the data in this adverse situation.

**Comment by chngtrn** [comment]
I'm having the same issue and the only solution that I could do was below. I'm still trying to figure out how to add that rule permanently after reboots.

```
$ sudo iptables -P FORWARD ACCEPT
$ sudo microk8s.stop
$ sudo microk8s.start
```

**Comment by ktsakalozos** [comment]
@chngtrn you need to store the iptable rules and have them loaded on boot. The process might be slightly different depending on your distribution for ubuntu look at the " Saving iptables" section in https://help.ubuntu.com/community/IptablesHowTo . There might also bee firewall configuration tools that would do that automagicaly.

**Comment by chngtrn** [comment]
Thanks, @ktsakalozos. I figured out the problem. No matter if I use firewalld or iptables the rule above will always be DROP after a reboot. It was the IP forwarding setting that I had to set to make it persistent. Here it is for anyone having same issue.
```
# CentOS 7
sudo echo "net.ipv4.ip_forward = 1" >> /usr/lib/sysctl.d/50-default.conf  # Reboot

# Manjaro / Arch
sudo echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.d/30-ipforward.conf    # Reboot
```

**Comment by BigRedS** [comment]
You don't need to reboot after configuring sysctl. `sysctl -p` will reload it, or, as root, do `echo 1 > /proc/sys/net/ipv4/ip_forward` to do the same thing.
