### ISSUE TITLE
Auto-reload on configmap change

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#297]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
With reference to this https://github.com/kubevirt/kubernetes-device-plugins/issues/49 any idea when would this be made available? Thanks.

**Comment by gageorsburn** [comment]
Hey @khteh, 
I originally started to implement in this PR: https://github.com/kubevirt/kubernetes-device-plugins/pull/54

The bridge device plugin was mostly abandoned in favor of Multis over device plugins for multi-interface networking. That PR is mostly finished, needs a few minor tweaks if you want to take it over.
