### ISSUE TITLE
kubectl does not scale new pod to other available nodes after one of the nodes goes down

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#299]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
```
kubectl describe pod mypod-0:
Reason:                    NodeLost
Message:                   Node ip-10-0-1-40.ap-southeast-1.compute.internal which was running pod mypod-0 is unresponsive
```
I can't delete the pod. I tried to delete the Service and StatefulSet and `apply -f` both of them and it just stops to work. 
```
kubectl describe sts ...:
  Warning  FailedCreate  4m10s (x26 over 9m44s)  statefulset-controller  create Pod mypod-0 in StatefulSet mysts failed error: The POST operation against Pod could not be completed at this time, please try again.
```

**Comment by ktsakalozos** [comment]
@khteh this is also related to AWS EKS, right? Closing this as well.

**Comment by khteh** [comment]
I change the `podManagementPolicy: "Parallel"` thinking that it would reschedule pod in other available nodes but it doesn't. Is this a bug or my understanding of the podManagement is wrong?
