### ISSUE TITLE
NFS - CSI : mount volumes

### ISSUE THREAD

**Issue by andreatosato** [ubuntu/microk8s#2995]
Hi, I have installed NFS and CSI as described on microk8s docs.
I installed many bitnami product (mongo, redis, minio) and SQL Server with deployment.
[mongo](https://github.com/bitnami/charts/tree/master/bitnami/mongodb/)

I have this error, many times in many installation.
```txt
Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[datadir scripts kube-api-access-xs52m]: timed out waiting for the condition
```
[inspection-report-20220321_133852.tar.gz](https://github.com/canonical/microk8s/files/8315822/inspection-report-20220321_133852.tar.gz)

I attach tarball.

**Comment by balchua** [comment]
I see a lot of these errors.

```
Mar 21 13:37:14 microk8sdev microk8s.daemon-kubelite[294113]: E0321 13:37:14.026620  294113 volume_linux.go:101] "Chown failed" err="chmod /var/snap/microk8s/common/var/lib/kubelet/pods/d9b9c930-f3c8-4e0c-a3fa-c4551ce25365/volumes/kubernetes.io~csi/pvc-6a45b017-ee23-41aa-aa3d-d350ef3d2b48/mount/.minio.sys/config/iam/service-accounts: operation not permitted" path="/var/snap/microk8s/common/var/lib/kubelet/pods/d9b9c930-f3c8-4e0c-a3fa-c4551ce25365/volumes/kubernetes.io~csi/pvc-6a45b017-ee23-41aa-aa3d-d350ef3d2b48/mount/.minio.sys/config/iam/service-accounts"
```
It is looking like an nfs server permission issue here.

**Comment by andreatosato** [comment]
@balchua can you suggest me home to fix?
I follow NFS guideline on microk8s websites.
I mount NFS on /srv folder but this error Is on /car/snap/microk8s

**Comment by balchua** [comment]
The only thing i can think of is that the `nfs-csi` is started with `mount-permission` of `511`

``` json

"image": "mcr.microsoft.com/k8s/csi/nfs-csi:latest",
                                "args": [
                                    "--v=5",
                                    "--nodeid=$(NODE_ID)",
                                    "--endpoint=$(CSI_ENDPOINT)",
                                    "--drivername=nfs.csi.k8s.io",
                                    "--mount-permissions=511"
                           
```
But if i looked at the actual helm chart it is `0777`
https://github.com/kubernetes-csi/csi-driver-nfs/blob/1177e9be8a0e70648d1bcc9db6b82911317d90a0/charts/latest/csi-driver-nfs/values.yaml#L30

**Comment by andreatosato** [comment]
I add this: 
```
sudo chmod 777 -R /var/snap/microk8s/common/var/lib/kubelet
```

**Comment by balchua** [comment]
I think thats the nfs mount.  Did you change the `mountPermission` to `777` in the `nfs-csi` deployment?
You may want to recreate all the PV and pvc.  Which means redeploy the apps.

**Comment by andreatosato** [comment]
@balchua  I tried many solution, but not work fine.
