### ISSUE TITLE
Source IP is not preserved between pods

### ISSUE THREAD

**Issue by anthonydahanne** [ubuntu/microk8s#302]
Hello,
I have discovered a network discrepancy between microk8s and Minikube : with microk8s, when 2 pods connect to each other, they do not share their original IP address but the microsk8s gateway IP address.

Let me take a very simple example to explain this.
Let's start a first sleeping pod, pod-a, and let's make it run netcat on port 9999 

```
$ kubectl run pod-a  --restart=Never   --image nicolaka/netshoot -- sleep 3600
$ echo $(kubectl get pod pod-a --output=jsonpath={.status.podIP})
10.1.1.26
$ kubectl exec -it pod-a bash
# nc -l -p 9999
# "ctrl + Z"
# bg
# "ctrl + d"
```

Let's start a second sleeping pod, pod-b and let's make it connect to pod-a on port 9999 

```
$ kubectl run pod-b  --restart=Never   --image nicolaka/netshoot -- sleep 3600
$ echo $(kubectl get pod pod-b --output=jsonpath={.status.podIP})
10.1.1.27
$ kubectl exec -it pod-b bash
# telnet 10.1.1.26 9999
# "ctrl + Z"
# bg
# "ctrl + d"
# netstat -n
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 10.1.1.27:55776         10.1.1.26:9999          ESTABLISHED
```

Well, so far so good, right ? 
But let's have a look at pod-a point of view

```
$ kubectl exec -it pod-a bash
# netstat -n
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 10.1.1.26:9999          10.1.1.1:55776          ESTABLISHED
```

So what's behind 10.1.1.1 ? If I run this command from my Ubuntu machine running microsk8s :
```
anthony@host:~$ sudo ifconfig
cbr0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet 10.1.1.1  netmask 255.255.255.0  broadcast 0.0.0.0
```

My first issue with that behavior here, is that it's not consistent with most k8s setup I've come across (minikube, kops, gke, aks, on prem using kubeadm)
See, if I run the same scenario on Minikube, I'll have :

```
bash-4.4# telnet 172.17.0.10 9999
^Z
[1]+  Stopped                 telnet 172.17.0.10 9999
bash-4.4# bg
[1]+ telnet 172.17.0.10 9999 &
bash-4.4# netstat -n
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 172.17.0.11:56086       172.17.0.10:9999        ESTABLISHED 
```

and

```
bash-4.4# nc -l -p 9999
^Z
[1]+  Stopped                 nc -l -p 9999
bash-4.4# bg
[1]+ nc -l -p 9999 &
bash-4.4# netstat -n
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 172.17.0.10:9999        172.17.0.11:56086       ESTABLISHED 
```

My second issue is that I'm running a software that detects the remote address of its clients to launch a healthcheck on them; with microk8s, the healthcheck tries to connect to 10.1.1.1, and that's not working obviously.

I'm still new to microsk8s, but I think it's an issue that's breaking software making assumptions on remote IPs ; even more since other k8s distribution do not behave the same.

```
$ snap version
snap    2.37.1
snapd   2.37.1
series  16
ubuntu  18.04
kernel  4.15.0-43-generic
```

I've installed microk8s using 
```
sudo snap install microk8s --classic
````
```
installed:        v1.13.2             (383) 229MB classic
```

**Comment by ktsakalozos** [comment]
Hi @anthonydahanne ,

I do not have a good answer on this at the moment. I am not familiar with how kube-net and kube-proxy are doing the wiring to make the kubernetes deployment work. Reading   https://kubernetes.io/docs/concepts/cluster-administration/networking/#kubernetes-model I too would  expect the right IP to appear as the foreign address.

Sorry for not being able to offer more insight.

**Comment by anthonydahanne** [comment]
hello @ktsakalozos , 
thanks for your answer and the link; yes that makes it clear the remote address should be the container address.
I too am not versed into networking and microsk8s enough to send a PR to fix it; any volunteers to have a look, you're welcome :-)

**Comment by byliuyang** [comment]
I encountered the same issue. Cannot obtain client IP. Please help.
