### ISSUE TITLE
question - memory footprint

### ISSUE THREAD

**Issue by pierreozoux** [ubuntu/microk8s#303]
Hello!

I have an idea, and I have some questions, maybe you can help me.
There is a project called [YunoHost](https://yunohost.org/#/) and it is aimed at helping home users self host services like WordPress or Nextcloud on an arm computer at home.
It is nice, but based on bash let's say, and as I love k8s api, I'm wondering about k8s mem footprint on such small devices.

In a context of a one node cluster, what is the mem footprint of:

     - etcd ~ [22Mb I guess](https://coreos.com/etcd/docs/latest/benchmarks/etcd-storage-memory-benchmark.html)
    - kube-api
    - controller
    - scheduler
    - kubelet

I think our main constraint here is mem and not cpu.

Another question, do we need also a network plugin? Or as there is only one node, it is enough?

And then, what about optimization, I think there are many rooms for improvements in this context:

    - remove lot of unecessary code at compilation (like aws integration and so on)
    - remove the scheduler, or replace it with a dummy one
    - tune the controller for home user usage instead of thousands nodes, millions pods
    - tune etcd
    - reimplement some functions like cronjobs?
    - socket activation for all the services

I'm just thinking out loud here, if you have any ideas, please share them here, and do not hesitate to close the issue once you answered!

Thanks again and have a nice day :)

Relates to https://github.com/alexellis/k8s-on-raspbian/issues/10

**Comment by pierreozoux** [comment]
This is also relevant to the discussion:

https://github.com/solo-io/unik/issues/182

**Comment by ktsakalozos** [comment]
Hi @pierreozoux 

Thank you for sharing your thoughts. You bring up a very interesting topic.

Having MicroK8s extending into IoT is in our interest. MicroK8s being a snap, arm support and the move to containerd work towards this direction. Any PRs that would improve the memory footprint without compromising functionality will be gladly accepted. Would you be willing to offer any cycles?

Thank you.
