### ISSUE TITLE
microk8s-hostpath for storage feels redundant

### ISSUE THREAD

**Issue by jameinel** [ubuntu/microk8s#305]
After installing microk8s, you can list what storage options are available. Given you are talking to a microk8s already, it is reasonable for it to just list the storage as "hostpath", rather than "microk8s-hostpath".

**Comment by ktsakalozos** [comment]
Hi @jameinel 

Thank you for opening this issue. To clarify, you want the default storage class you see with `microk8s.kubectl get storageclass` to be renamed from `microk8s-hostpath` to `hostpath` https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/storage.yaml#L42 . Have you performed this rename to see if anything breaks?

**Comment by jameinel** [comment]
Hi @ktsakalozos I haven't tried directly doing the rename myself. I've asked @wallyworld to take a look.

But yes, that is the recommendation, that it would just call the storageclass that it registers by default to just "hostpath".

**Comment by wallyworld** [comment]
@ktsakalozos Juju doesn't care what the name of the storage class is. So doing the rename won't affect things for new deploys. Existing 2.5.0 models will need to be re-deployed but that's fine as using microk8s is for dev/test/demo etc. With 2.5.1 you can edit any Juju storage pools to change the name. I assume a snap update will delete the sc and create a new one as they can't be renamed once created IIANM.
