### ISSUE TITLE
node label to identify microk8s substrate

### ISSUE THREAD

**Issue by wallyworld** [ubuntu/microk8s#308]
Could we please add a label to all microk8s nodes so that a caller can inspect the node and see that microk8s is the underlying substrate?

For reference, GKE uses
- cloud.google.com/gke-os-distribution
- cloud.google.com/gke-nodepool

AKS uses
- kubernetes.azure.com/cluster

etc. So we can identify those. But we also need to identify microk8s.

**Comment by ktsakalozos** [comment]
Any label preference? What about `microk8s.io/cluster`?

To demystify this further, you want to append `--node-labels microk8s.io/cluster` in the default arguments of kubelet here: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kubelet

[Full list of available kubelet args](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)

**Comment by wallyworld** [comment]
@ktsakalozos What you propose sounds good, thank you.
