### ISSUE TITLE
Microk8s should expose the docker agent to allow for local builds 

### ISSUE THREAD

**Issue by CalvinHartwell** [ubuntu/microk8s#31]
Hi all,

Microk8s should expose the docker agent to allow for local container builds using the daemon included inside the snap, I.E:

```
microk8s.docker build .
microk8s.docker login someregistry.catloverextreme.com
```

Etc. 

Cheers,

- Calvin

**Comment by olimination** [comment]
See also minikube doc here: https://kubernetes.io/docs/getting-started-guides/minikube/#reusing-the-docker-daemon

**Comment by marcoceppi** [comment]
yes, I think a better option would be to have local docker client re-use
the docker daemon running from the snap

**Comment by bkcsfi** [comment]
I agree with @marcoceppi   I would like to use docker client and docker-compose on my laptop while microk8s is running. There should be a way to expose the microk8s docker daemon to other users on the machine.. would make image development faster and simplify tooling to not have to use special commands.

**Comment by ktsakalozos** [comment]
@bkcsfi you should already be able to do that by pointing your docker client to the socket the docker daemon is using.

`docker -H  unix://var/snap/microk8s/current/docker.sock`

**Comment by davefinster** [comment]
Can confirm this works for at least getting the Docker client talking to the internal daemon. Worth pointing out though that another slash is required

```bash
> docker -H unix:///var/snap/microk8s/current/docker.sock ps
root@other-k8s:/var/snap/microk8s/current# docker -H unix:///var/snap/microk8s/current/docker.sock ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS               NAMES
fedf8c9eb0e9        6c0dbeaa8d20                  "/pod_nanny --config…"   6 minutes ago       Up 6 minutes                            k8s_eventer-nanny_heapster-v1.5.2-577898ddbf-m868v_kube-system_0e11103f-8a47-11e8-9183-42010a800002_1
```
whereas without the additional /:
```bash
> docker -H unix://var/snap/microk8s/current/docker.sock ps
Cannot connect to the Docker daemon at unix://var/snap/microk8s/current/docker.sock. Is the docker daemon running?
```

Additionally one can use ```export DOCKER_HOST=unix:///var/snap/microk8s/current/docker.sock``` to avoid the -H argument on each command

**Comment by ktsakalozos** [comment]
In the edge and 1.11/edge channels you will now find the `microk8s.docker` command. This addition came in with the registry addon (`microk8s.enable registry`) that start an insecure registry at localhost:32000. Have a look here: https://github.com/ubuntu/microk8s/blob/master/docs/registry.md

**Comment by ktsakalozos** [comment]
Feel free to reopen this issue if you find something missing.
