### ISSUE TITLE
Consider replacing etcd with sqlite

### ISSUE THREAD

**Issue by pierreozoux** [ubuntu/microk8s#312]
In relation to #303 to save more memory, and like in [k3s](https://github.com/ibuildthecloud/k3s) project, we could think of reducing the memory footprint by using SQLite.

What do you think about the idea?

**Comment by ktsakalozos** [comment]
This is a direction we would like to explore. There are many benefits in using SQLite in the place of etcd, both interms of performance and maintenance. We could even use a distributed version of SQLite https://github.com/CanonicalLtd/dqlite . For sure a very interesting goal to pursue. Again, are you @pierreozoux or any one else willing to lead this effort?

**Comment by xanderificnl** [comment]
rancher/k3s actually provides this functionality via https://github.com/rancher/kine I believe. Perhaps this could be helpful?

**Comment by ktsakalozos** [comment]
Dqlite is coming really soon. Have a look at this: `sudo snap install microk8s --classic --channel=edge/test-dqlite`

**Comment by xanderificnl** [comment]
Nice. Is this being done via kine or another layer?

**Comment by ktsakalozos** [comment]
It is not using kine. Have a look at https://github.com/ubuntu/microk8s/tree/feature/ha-dqlite

**Comment by balchua** [comment]
This is now the default for 1.19 MicroK8s.
