### ISSUE TITLE
consider removing the scheduler

### ISSUE THREAD

**Issue by pierreozoux** [ubuntu/microk8s#313]
In relation to #303 as we are in a one node environment, we could consider removing the scheduler. We could make the kubelet directly watch the pods to be scheduled.

(I don't know much about kubernetes API but from an outside perspective it sounds like a good idea, but maybe it's not ;) )

**Comment by ktsakalozos** [comment]
I see your point here @pierreozoux. Eliminating the scheduler may yield a more compact MicroK8s and this works in favor of the IoT world.

However, I am not sure about the implications of not having a scheduler. How would this affect the rest of the users? Is this even feasible? I do not know.
