### ISSUE TITLE
I deleted all the nodes with remove-node, how do I add the localhost node back?

### ISSUE THREAD

**Issue by Freundschaft** [ubuntu/microk8s#3131]
ok maybe im just really dumb or no one ever thought of this scenario.
on a test machine I deleted all the nodes with remove-node, even the last controller node, now there are no nodes in my microk8s setup, and im wondering how i can add the machine that i am running microk8s back as a node.

when i use add-node, then try to join, microk8s tells me that its not possible because the machines share the same ip (obviously)

any ideas or is this just something that should never be done and cant be recovered from

**Comment by balchua** [comment]
I recall theres a `--force` argument in the remove-node that will remove it also from dqlite.

**Comment by lferran** [comment]
You can remove the snap and reinstall it again

**Comment by Freundschaft** [comment]
yea thats what I did, but there must be another solution surely?

**Comment by usersina** [comment]
Had a slightly different issue. My [workers weren't working](https://github.com/canonical/microk8s/issues/3101) (no pun intended) so [I applied a patch to them](https://github.com/canonical/microk8s/issues/2402#issuecomment-950884240). However that presents an [issue with reverting the patch changes](https://github.com/canonical/microk8s/issues/2402#issuecomment-951185742) when joining from another node. In conclusion, I get the following impossible to remove node now.

![2022-05-19_202815](https://user-images.githubusercontent.com/44204957/169387130-aea8d0b7-6eb1-46ff-9df7-e0fe8e6b483a.JPG)

I think I've literally run into every issue in microk8s so far 😞
