### ISSUE TITLE
My pods can't reach outside networks with UDP or TCP, but ICMP works

### ISSUE THREAD

**Issue by akaihola** [ubuntu/microk8s#316]
**Update:** Solved by figuring out the required iptables rule change on Fedora corresponding to `-P FORWARD ACCEPT` (see comment). However, probably a more specific rule should be used instead.

---

Networking used to work, but recently stopped passing UPD and TCP traffic between pods and the outside network.

I'm running
- microk8s v1.13.2 Rev 383 snap (also tried v1.13.3 Rev 406)
- Fedora 29
- kernel 4.20.6-200.fc29.x86_64 (also tried 4.19.9).

I have
- removed the Docker CE RPM (although networking used to work in microk8s with it installed)
- stopped, disabled and removed microk8s, rebooted and reinstalled microk8s
- disabled SELinux using `sudo setenforce 0`
- ensured that `ufw` is disabled
- ensured that iptables forwards all traffic with `sudo iptables -P FORWARD ACCEPT`

With a plain Docker container networking works correctly:
```bash
$ microk8s.docker run --rm -it praqma/network-multitool bash    
bash-4.4# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=9.52 ms

bash-4.4# dig google.com @8.8.8.8

; <<>> DiG 9.12.3 <<>> google.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5142
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		277	IN	A	216.58.207.206

;; Query time: 19 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Feb 12 08:10:58 UTC 2019
;; MSG SIZE  rcvd: 55
```

But in a microk8s pod only ICMP traffic gets through, and UDP and TCP are dead:
```bash
$ kubectl run -it my-shell --image=praqma/network-multitool --restart=Never -- bash
If you don't see a command prompt, try pressing enter.
bash-4.4# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=9.36 ms
^C
--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 9.369/9.369/9.369/0.000 ms
bash-4.4# dig google.com @8.8.8.8

; <<>> DiG 9.12.3 <<>> google.com @8.8.8.8
;; global options: +cmd
;; connection timed out; no servers could be reached
```

When doing the `dig`, I see this on the `cbr0` interface:
```bash
10:47:49.477515 IP 10.1.1.28.40049 > google-public-dns-a.google.com.domain: 53854+ [1au] A? google.com. (51)
10:47:49.477656 IP hiili > 10.1.1.28: ICMP host google-public-dns-a.google.com unreachable - admin prohibited, length 87
```

Here's output from `microk8s.inspect`:
```
Inspecting services
  Service snap.microk8s.daemon-docker is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/383/inspection-report-20190212_100700.tar.gz
```
[inspection-report-20190212_100700.tar.gz](https://github.com/ubuntu/microk8s/files/2854726/inspection-report-20190212_100700.tar.gz)

**Comment by akaihola** [comment]
Here's iptables tracing for the first 1 sec of network traffic generated by the `dig google.com @8.8.8.8` cmmand: [iptables-trace-dig-google.log](https://github.com/ubuntu/microk8s/files/2854961/iptables-trace-dig-google.log)

**Comment by akaihola** [comment]
In addition to `sudo iptables -P  FORWARD ACCEPT`, I needed to do this on Fedora 29:
```bash
sudo iptables -D FORWARD 20
```
since the 20th rule in the FORWARD chain was:
```
16 1264 REJECT all -- any any anywhere anywhere reject-with icmp-host-prohibited
```

I wonder what the proper way to configure iptables on Fedora for microk8s would be?

**Comment by redelman** [comment]
I solved this rather easily on Fedora 30 by running:
sudo firewall-cmd --zone=trusted --add-interface=cbr0
sudo firewall-cmd --zone=trusted --add-interface=cbr0 --permanent

This is documented in #408

**Comment by Richard87** [comment]
I also had this exact problem when a PHP pod trying to talk to a Mysql pod/service

```
sudo firewall-cmd --zone=trusted --add-masquerade --permanent
sudo firewall-cmd --zone=trusted --add-interface=cbr0 --permanent
sudo firewall-cmd --reload
```

Solved it for me :)

**Comment by Richard87** [comment]
That didn't work for me, I still get "no route to host" when connecting to mysql service (pod) from a php pod

When exec into the container and run `host mysql` it returns the FQDN and the ip-adress of the service, and _ping work_, but mysql client can't connect...
