### ISSUE TITLE
Upgrading microk8s doesn't appear to have updated calico cni files

### ISSUE THREAD

**Issue by cccscdev** [ubuntu/microk8s#3170]
I am attempting to upgrade an existing instance running microk8s from 1.14 to 1.22.

I am using the following steps to perform the upgrade (with root privileges):

- download the microk8s 1.22 snap files (as I need to perform the upgrade on an isolated instance)
- start with instance running microk8s 1.14
- microk8s.disable (all the currently enabled plugins)
- microk8s.stop
- snap ack microk8s_2947.assert (microk8s 1.22)
- snap install microk8s_2947.snap --classic
- snap switch microk8s --channel=1.22/stable
- microk8s.stop
- microk8s.start
- microk8s.enable (all the required plugins)

The above all appears to complete successfully, but I have noticed a difference in the cni configuration between this instance (upgraded from 1.14 to 1.22), when compared to a second clean instance that has had microk8s 1.22 installed directly (not upgraded from previous version).

Looking in /var/snap/microk8s/current/args/cni-network/ I see differences:

Upgraded instance from 1.14 to 1.22:

```
# ls -l /var/snap/microk8s/current/args/cni-network
total 4
-rw-rw----. 1 root microk8s 353 May 25 10:30 cni.conf
```

Clean instance with 1.22 installed directly:

```
# ls -l /var/snap/microk8s/current/args/cni-network/
total 208
-rw-rw---- 1 root microk8s    673 Apr 27 08:41 10-calico.conflist
-rw-rw---- 1 root microk8s   2821 Apr 27 08:41 calico-kubeconfig
-rw-rw---- 1 root microk8s 201439 Apr 26 13:19 cni.yaml
```

Checking both instances I see these files both state a cni version of 0.3.1:

```
"cniVersion": "0.3.1"
```

Is anyone able to explain why the upgrade has not resulted in these additional files being installed?  It looks to me like the upgraded 1.14 to 1.22 instance has just retained the previous config, and this has not been refreshed/updated to that found in 1.22.

**Comment by neoaggelos** [comment]
Hi @cccscdev 

MicroK8s upgrades will not automatically upgrade the version of the Calico CNI, and this is by design. This is to accomodate use cases where a different CNI is used, or custom Calico configuration has been applied, which could possibly break if we blindly upgrade Calico versions.

It is possible to upgrade the CNI version manually. The manifests of the current release can be found in `/snap/microk8s/current/upgrade-scripts/000-switch-to-calico/resources/calico.yaml`. This is something that would be useful to have in the documentation, but the steps are roughly like this:

```bash
# check the diff between live and latest version. this should contain the image versions (at least), and possibly a few more configs
$ diff /snap/microk8s/current/upgrade-scripts/000-switch-to-calico/resources/calico.yaml /var/snap/microk8s/current/args/cni-network/cni.yaml

# i am reluctant to suggest overwriting the file, to avoid breaking the configuration. instead, edit the cni.yaml and update accordingly. 
$ vim /var/snap/microk8s/current/args/cni-network/cni.yaml

# apply the new CNI version
$ microk8s.kubectl apply -f /var/snap/microk8s/current/args/cni-network/cni.yaml
```

**Comment by neoaggelos** [comment]
Also, keep in mind that when upgrading MicroK8s versions, it is highly recommended not to skip minor versions. For example, in your case this would be:

```bash
snap switch microk8s --channel 1.15
snap switch microk8s --channel 1.16
snap switch microk8s --channel 1.17
....
snap switch microk8s --channel 1.22
```

This is not MicroK8s specific, but rather the upstream way to upgrade a Kubernetes cluster.

**Comment by ktsakalozos** [comment]
Of note here is also that 1.14 had flannel while 1.22 comes with calico. When you upgrade from 1.14 to 1.22 flannel will continue to be in use.

**Comment by cccscdev** [comment]
Thank you for the clarification and explanations.
