### ISSUE TITLE
session stickiness between services?

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#322]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
I am using ingress nginx controller and enable sticky session according to https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/. Everything goes well when I use replicaset=1. Things break when I scale it up to 2. I suspect that session stickiness terminates at the ingress controller and therefore only works for external reqeuests. How do the k8s services maintain session stickiness? Thanks.

**Comment by ktsakalozos** [comment]
Hi @khteh 

I have never used sticky sessions. Since your question is not strictly related to MicroK8s, you may want to ask at https://discuss.kubernetes.io/ 

Thanks

**Comment by khteh** [comment]
I found out that the nginx ingress switch to a different pod after the initial request but subsequent requests go to the same pod thereafter. Is that the expected behaviour?

**Comment by khteh** [comment]
How do I upgrade the nginx ingress to 0.22.0? https://github.com/kubernetes/ingress-nginx/issues/3769

**Comment by ktsakalozos** [comment]
You could `microk8s.disable ingress` and then follow the instructions here: https://kubernetes.github.io/ingress-nginx/deploy/#prerequisite-generic-deployment-command

You could then consider providing a pull request updating the manifest in https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/ingress.yaml so you will get the latest ingress with the next MicroK8s release. Thanks.

**Comment by khteh** [comment]
https://github.com/ubuntu/microk8s/pull/325

**Comment by khteh** [comment]
When will this patched be released? v1.14.0 still uses `quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.15.0`
