### ISSUE TITLE
Using with ksync

### ISSUE THREAD

**Issue by KASOGIT** [ubuntu/microk8s#326]
Hello,

i would like to know if there is a way to use ksync with microk8s with a local setup ?

Following ksync' tutorial doesn't seems to work..

Thx !

**Comment by ktsakalozos** [comment]
Hi @KASOGIT 

Could you please point me to the tutorial you are following?

I believe I got ksync to work with MicroK8s following the steps at the "Getting Started" section here https://github.com/vapor-ware/ksync/blob/master/README.md#getting-started . Two things not included in the "Getting Started" guide needed by MicroK8s are: First copy the kubeconfig pointing to MicroK8s to a location ksync would be able to find:

```
microk8s.config > ~/kube/config
```

Second, anywhere it says `kubectl` use `microk8s.kubectl` (or create an alias).

I have never used ksync in the past so do not hesitate to point out anything I missed.

Thanks

**Comment by KASOGIT** [comment]
Thx for your replay, i'll try soon.
I think you are meaning: `microk8s.config > ~/.kube/config` instead right ?
Thanks

**Comment by KASOGIT** [comment]
Hi !
Even following @ktsakalozos  advice and succeded to connect to the cluster with ksync i got a bunch of errors when using `ksync create` command. After trying lot of things i decided to switch for minikube and everything worked well with.
Hope micro8ks will be fully compatible one day !

Thanks for the help :)
