### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by niksubramanian** [ubuntu/microk8s#327]
Hello all,

# The issue
After running the following command:
```
sudo snap install microk8s --classic
```

I get the following error:
```
error: cannot perform the following tasks:
- Run install hook of "microk8s" snap if present (run hook "install": / has 'other' write 40777)
```

The error repeats when re-running the installer.

This:
```
systemctl status snapd.service
```

Generates this snippet:
```
Feb 21 19:09:43 ub18 snapd[5066]: helpers.go:662: cannot retrieve info for snap "microk8s": cannot find installed snap "microk8s" at revision 383: missing file /snap/microk8s/383/meta/snap.yaml
```

# Attempted workarounds
* [x] ~~reinstalling snap~~
* [x] ~~building microk8s from source and installing that way~~

# System settings
* Ubuntu 18.04
* No prior microk8s installations

Thanks in advance for any insight

# Edits
* added workarounds attempted
* added more debugging info

**Comment by ktsakalozos** [comment]
Hi @niksubramanian 

Do you see this with other snaps, or is it only with MicroK8s?

I see a few threads on the snapcraft forum indicating file permissions problems:
- https://forum.snapcraft.io/t/permissions-of-snap-files-in-var-lib-snapd-snaps/1462/3
- https://forum.snapcraft.io/t/snap-d-error-cannot-communicate-with-server-connection-refused/6093

I would suggest we move this conversation over to https://forum.snapcraft.io/ we will find more expertise there.

Thanks.

**Comment by niksubramanian** [comment]
For future reference, tried this without success:
```
sudo apt autoremove --purge snapd
sudo apt install snapd
sudo snap install microk8s --classic
```
output:
```
error: cannot perform the following tasks:
- Run install hook of "microk8s" snap if present (run hook "install": / has 'other' write 40777)
```

**Comment by niksubramanian** [comment]
Some further development:

Running this
```
systemctl status snapd.service
```

Returns these interesting lines:
```
Feb 21 19:09:43 ub18 snapd[5066]: helpers.go:662: cannot retrieve info for snap "microk8s": cannot find installed snap "microk8s" at revision 383: missing file /snap/microk8s/383/meta/snap.yaml
Feb 21 19:09:43 ub18 snapd[5066]: helpers.go:662: cannot retrieve info for snap "microk8s": cannot find installed snap "microk8s" at revision 383: missing file /snap/microk8s/383/meta/snap.yaml
```

@ktsakalozos, does this ring a bell in any way?

**Comment by niksubramanian** [comment]
The quest continues - building microk8s from source and installing it generates the same issue.

**Comment by ktsakalozos** [comment]
I am sorry @niksubramanian I have never seen this. Is there anything special with your filesystem installation? Can you share the output of `mount`, `snap info  microk8s`? Can you snap install something else eg `snap install juju`?

**Comment by niksubramanian** [comment]
```snap install juju``` generates the same problem. I'm going to assume that this issue really is related to snap rather than microk8s at this point.

[I'll link the thread I started in snapcraft here](https://forum.snapcraft.io/t/issue-installing-microk8s-using-snap-run-hook-install-has-other-write-40777/10087) in case anyone else has the same problem, and close the issue!

Thanks for your help @ktsakalozos !

**Comment by niksubramanian** [comment]
Just a quick update - the issue is definitely due to permission problems! Fixing my permissions in my root directory solved this issue.

**Comment by tariq452** [comment]
> Just a quick update - the issue is definitely due to permission problems! Fixing my permissions in my root directory solved this issue.

please share with us the step

**Comment by pradhyu** [comment]
sudo chmod -R 0755 /var/lib/snapd

> > Just a quick update - the issue is definitely due to permission problems! Fixing my permissions in my root directory solved this issue.
> 
> please share with us the step

sudo chmod -R 0755 /var/lib/snapd

**Comment by yanovich** [comment]
I've had the same issue. This helped:
```
sudo apt-get purge snapd
sudo apt-get install snapd
sudo snap install --classic microk8s
```

**Comment by pascencio** [comment]
@pradhyu I tried changing the snap directory permissions but doesn't work. I tried uninstall and reinstall snap too.

This is my journalctl output:

```shell
ago 13 11:26:22 my-desktop systemd[1]: Starting Snap Daemon...
ago 13 11:26:22 my-desktop snapd[512202]: AppArmor status: apparmor is enabled but some kernel features are missing: dbus, network
ago 13 11:26:22 my-desktop snapd[512202]: daemon.go:248: started snapd/2.51.3-2 (series 16; classic; devmode) manjaro/ (amd64) linux/5.12.19-1-MANJARO.
ago 13 11:26:23 my-desktop snapd[512202]: daemon.go:341: adjusting startup timeout by 50s (pessimistic estimate of 30s plus 5s per snap)
ago 13 11:26:23 my-desktop systemd[1]: Started Snap Daemon.
ago 13 11:26:28 my-desktop snapd[512202]: api_snaps.go:299: Installing snap "microk8s" revision unset
ago 13 11:26:36 my-desktop snapd[512202]: taskrunner.go:271: [change 7 "Run install hook of \"microk8s\" snap if present" task] failed: run hook "install": / has 'other' write 40777
ago 13 11:26:43 my-desktop snapd[512202]: handlers.go:511: Reported install problem for "microk8s" as already-reported
ago 13 11:27:10 my-desktop snapd[512202]: api_snaps.go:299: Installing snap "microk8s" revision unset
ago 13 11:27:19 my-desktop snapd[512202]: taskrunner.go:271: [change 8 "Run install hook of \"microk8s\" snap if present" task] failed: run hook "install": / has 'other' write 40777
ago 13 11:27:25 my-desktop snapd[512202]: handlers.go:511: Reported install problem for "microk8s" as already-reported
```

Thanks in the advance!
