### ISSUE TITLE
Timeout on kubectl logs

### ISSUE THREAD

**Issue by lmeunier-talend** [ubuntu/microk8s#331]
Hello,

I have started to use microK8s today and ran into an issue.
I saw it first when I tried to install some helm chart.

All helm command timed out, so i tried to check the logs of tiller and the kubectl logs timed out too.

I've tried deploying on default namespace as well as on a new namespace, all the same, each time i try to get the logs i get:

`Error from server: Get https://tlnd-lmeunier:10250/containerLogs/default/hello-node-64c578bdf8-mwjrj/hello-node: dial tcp 192.168.39.230:10250: i/o timeout`

But I don't find this address in ip adresse

Started / stopped the cluster. Re-installed from scratch with no plugins nothing help

Any idea ? i really don't want to go back to minikube :(

[inspection-report-20190222_171859.tar.gz](https://github.com/ubuntu/microk8s/files/2894837/inspection-report-20190222_171859.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @lmeunier-talend 

You have a strange setup, what distribution are you on? I see the `microk8s.inspect` is not able to find  utilities like `ifconfig` and `netstat`.

The first thing I see is that etcd is not able to create a socket. This socket is used by the api server to access etcd. You can reconfigure etcd and the api server to talk over a tcp port. Update `/var/snap/microk8s/current/args/etcd` with
```
--advertise-client-urls=http://localhost:2379
--listen-client-urls=http://localhost:2379
```
Update `/var/snap/microk8s/current/args/kube-apiserver` with:
```
--etcd-servers='http://localhost:2379'
```
And restart MicroK8s with `microk8s.stop` give it a sec and `microk8s.start`.

I am not sure if this is the only issue so lets address this first and please send me a `microk8s.inspect` again.

Thanks

**Comment by lmeunier-talend** [comment]
Hello

I will try that, thanks.
I'm on ubuntu 18.10

**Comment by lmeunier-talend** [comment]
Well i have still the same issue :(
I have installed the net-tools package and ran the inspect again

[inspection-report-20190225_101728.tar.gz](https://github.com/ubuntu/microk8s/files/2899715/inspection-report-20190225_101728.tar.gz)

About docket, I installed it by following the instruction on the site, and added my user to the group so that i don't have to use sudo.
But what about snap ?

**Comment by ktsakalozos** [comment]
@lmeunier-talend MicroK8s has its own docker daemon you do not need to do anything about that. 

I would like a full detailed description and set of commands you issue so that I can reproduce the problem here locally.

Please make sure that you put the kubeconfig file in the right place so that helm can find it. To do this you do a `microk8s.config > ~/.kube/config` . After this, `helm init` should deploy the tiller. `microk8s.kubectl get all --all-namespaces` should show you something like this: ` kube-system   pod/tiller-deploy-776c5b4cc6-d7g5p          1/1     Running   0          19m` . 

The fact that you do not get the logs makes me wonder if you have a problem with the logs in general. So, I would like you to deploy the DNS pods and get the respective logs. Thry this `microk8s.enable dns` and then read the logs of the dns pod with something similar to this: `microk8s.kubectl logs -n kube-system   pod/kube-dns-6ccd496668-spzms -c kubedns` .

Let me know how the above went and please send me a script/steps I could use to reproduce the issue.

**Comment by lmeunier-talend** [comment]
Yes my problem is with the logs in general.
I'm testing with
`kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node`

then microk8s.kubectl logs <pod-name>

But I think there is something wrong in the kubelet because i have checked the log and see line like this

`pod_container_deletor.go:75] Container "af06cbe53d3e7d94d03b2e677fb6b4199d5a109b9f21d93fb51a177b31725b3c" not found in pod's containers`

But when I do a microk8s.docker ps there is no pod with that ID

I'm testing your thing your dns

**Comment by lmeunier-talend** [comment]
well just realized that asked to to get logs so of course i time out on your command :(

**Comment by ktsakalozos** [comment]
Can you please show me exactly the commands you put on the terminal?

I see for example you do a `kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node`. This implies you have `kubectl` installed and you are not using `microk8s.kubectl`. Is your `kubectl` using a config that points to the MicroK8s cluster? What is the output of `kubectl config view`? If `microk8s.kubeclt logs "yousdnspod"` times out can you run it with the -v=9 parameter to see what is timing out (`microk8s.kubeclt logs -v=9 "yousdnspod"`)? 

Thanks

**Comment by lmeunier-talend** [comment]
At first i was using the kubectl i have, but i did create the ~/.kube/config by following your documentation.

But recently i was using microk8s.kubectl, like yesterday when i tried your command

`microk8s.kubectl logs -n kube-system pod/kube-dns-6ccd496668-spzms -c kubedns`
and i timed out.

However today the problem is gone... i can use mircoK8s.kubectl or directly kubectl and i no longer time out

Yesterday in trying to make minikube work with none driver i installed socat then the KVM2 drivers as i had dns issues

Not sure if that is related

**Comment by lmeunier-talend** [comment]
anyway you can close this, thank you for your support

**Comment by ktsakalozos** [comment]
I am sorry I could not be of much help.
