### ISSUE TITLE
Multi-node support?

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#333]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
Does this support multi-node cluster? if yes, how to set it up? Thanks.

**Comment by ktsakalozos** [comment]
Please see https://github.com/ubuntu/microk8s/issues/333

**Comment by ktsakalozos** [comment]
Closing as duplicate.
