### ISSUE TITLE
Ingress uses hostNet but does not properly update its dnsPolicy

### ISSUE THREAD

**Issue by klarose** [ubuntu/microk8s#339]
I'm using microk8s on my Ubuntu 18.04 laptop. In general, it's working well. However, if the ingress needs to do any DNS lookups, for example with a `Service` of `type: ExternalName`, then it fails.

I narrowed down the cause to the nginx DaemonSet having a dnsPolicy of ClusterFirst. This does not work with hostnet.

To reproduce, set up a test httpbin deployment as follows:

```
kubectl create namespace httpbin
kubectl apply -f ~/tmp/httpbin.yaml  -n httpbin
kubectl apply -f ~/tmp/httpbin-ing.yaml
```

Next, try to get your IP:
```
curl -X GET "http://localhost/ip" -H "accept: application/json"
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.13.12</center>
</body>
</html>
```

Workaround the problem by patching the daemonset:
`kubectl patch daemonset nginx-ingress-microk8s-controller -p '{"spec": {"template": {"spec": {"dnsPolicy":"clusterFirstWithHostNet"}}}}'`

And try again:

curl -X GET "http://localhost/ip" -H "accept: application/json"
{
  "origin": "::1"
}

Logs when it's not working:

```
::1 - [::1] - - [26/Feb/2019:21:29:40 +0000] "GET /ip HTTP/1.1" 503 214 "-" "curl/7.58.0" 88 0.000 [] - - - - e01d1c233f077d2a07403124782ae5bf
I0226 21:29:47.561436       8 status.go:361] updating Ingress default/httpbin-ing status to [{127.0.0.1 }]
I0226 21:29:47.565835       8 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"httpbin-ing", UID:"39bf3a12-3a0c-11e9-a3db-f49634aec85b", APIVersion:"extensions", ResourceVersion:"39294", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/httpbin-ing
E0226 21:29:47.567381       8 endpoints.go:66] unexpected error resolving host httpbin.httpbin.svc.cluster.local: lookup httpbin.httpbin.svc.cluster.local on 127.0.0.53:53: server misbehaving
W0226 21:29:47.567450       8 controller.go:773] service default/httpbin-ext does not have any active endpoints
```

And when it's working:

```
I0226 21:26:56.447897       8 controller.go:168] backend reload required
I0226 21:26:56.527320       8 controller.go:177] ingress backend successfully reloaded...
::1 - [::1] - - [26/Feb/2019:21:27:11 +0000] "GET /ip HTTP/1.1" 200 22 "-" "curl/7.58.0" 88 0.004 [default-httpbin-ext-8000] 10.152.183.173:8000 22 0.000 200 ea1fa5c15cbc63e18f1f7f70218855a4
I0226 21:27:13.337853       8 status.go:361] updating Ingress default/httpbin-ing status to [{127.0.0.1 }]
I0226 21:27:13.340503       8 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"httpbin-ing", UID:"39bf3a12-3a0c-11e9-a3db-f49634aec85b", APIVersion:"extensions", ResourceVersion:"39067", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/httpbin-ing

```

The documents mentioned above:
[httpbin.tar.gz](https://github.com/ubuntu/microk8s/files/2907636/httpbin.tar.gz)

**Comment by klarose** [comment]
I can submit a PR if anyone wants, once I figure out how to do a test build/etc. :)

**Comment by ktsakalozos** [comment]
Hi @klarose 

Thank you for spotting this and offering a fix.

A PR would be great. We have a couple of more ingress related PRs lined up so it would be great to put them all in in a singe release.

Building MicroK8s is pretty straightforward. You clone the repository, you make sure LXC is working on you machine (let me know if you need any more info on this) and then you do a `snapcraft cleanbuild`. Unfortunately at the moment we are by this https://bugs.launchpad.net/snapcraft/+bug/1817300 . The fix should be released soon.

Thank you for your time and effort. Looking forward for the PR.

**Comment by ktsakalozos** [comment]
@klarose the build process is now unblocked. Make sure you on the latest snapcraft (v3.2) with `sudo snap refresh snapcraft --stable`. Then do a `snapcraft cleanbuild`. The build is done inside lxc so you should have that working as well.

**Comment by klarose** [comment]
I was able to get a build going. I tested it out locally, and it worked. I've submitted the PR, though it looks like Travis failed. Is there a simple way to rerun it, or should I just push a blank commit?

**Comment by ktsakalozos** [comment]
Thank you for the PR. The error is because of the `snapcore/snapcraft:stable` docker image not being updated yet. No worries, I am on it. I will ping you in case something is wrong.

Thanks again.
