### ISSUE TITLE
iptables -P FORWARD ACCEPT persistence

### ISSUE THREAD

**Issue by laurence-hudson-mindfoundry** [ubuntu/microk8s#345]
Perhaps this is more of an ubuntu question than an microk8s bug, if so feel free to close this and redirect me elsewhere.

For my microk8s use case I need traffic forwarding to be enabled. microk8s.inspect suggests `sudo iptables -P FORWARD ACCEPT` as the way to enable it. And running that command works.

However after every reboot I have to re run the command. I'm running on a clean 18.04 (desktop) install, with microk8s 1.12/stable. I've installed `iptables-persistent` & `netfilter-persistent` and run `sudo netfilter-persistent save` (after enabling forwarding). Yet after each reboot forwarding is disabled (reloading netfilter-persistent works).

Am I missing something obvious here? Is microk8s doing something funky? Any other suggestions on how I can permanently enable forwarding would be great.

**Comment by ktsakalozos** [comment]
Hi @laurence-hudson-mindfoundry 

Could you try the solution on this issue: https://github.com/ubuntu/microk8s/issues/266

**Comment by laurence-hudson-mindfoundry** [comment]
Perfect, thank you, not sure how that issue slipped by my searching. Sorry about the duplicate.
