### ISSUE TITLE
Auto-configure Magic IP 10.0.2.2 to talk to host OS

### ISSUE THREAD

**Issue by edsiper** [ubuntu/microk8s#351]
Considering Microk8s a solution to run locally, it lacks a very useful feature to allow Pods connect to Host services smoothly: Magic IP 10.0.2.2 (like minikube). 

I was presenting at Scale17x and my Pod Configmap connected to wlan0 interface to connect my local Elasticsearch service, for some reason my IP address changed and could not reach Elasticsearch anymore, this could be solved if 10.0.2.2 existed and always routed to the host OS.

**Comment by ktsakalozos** [comment]
Hi @edsiper 

I am sorry this happened during a presentation. Having a way for pods to access the host would be a nice feature, and it should be easy to implement.

From a quick search it seems `10.0.2.2` is an IP that VritualBox is adding to allow guests to reach the host. Based on https://askubuntu.com/questions/929296/how-to-define-localhost-ip-as-10-0-2-2/929414 we only need to do a `sudo ifconfig lo:1 10.0.2.2 up`. We could have a `microk8s.enable host-access` to create this interface upon user request. Your thoughts?

Thank you

**Comment by edsiper** [comment]
thanks for the quick update. Yep, I think a lo: interface would work, the 'host-access' option looks good too, likely needs to be something different than 10.0.2.2, wondering if upon start and using host-access in Kubernetes can bet set a specific environment variable like MICROK8S_HOST representing the target IP, on that way configmaps only needs to point the variable and not the IP.

**Comment by msf** [comment]
I support this. having access to hostOS services easily is productivity boon!

**Comment by ktsakalozos** [comment]
Closed via https://github.com/ubuntu/microk8s/pull/1109
