### ISSUE TITLE
curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by easybyr** [ubuntu/microk8s#353]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
[inspection-report-20190310_005245.tar.gz](https://github.com/ubuntu/microk8s/files/2948629/inspection-report-20190310_005245.tar.gz)

I created a deployment and a service to locate the pods.
But I cannot use *curl:\<NodeIP\>:\<NodePort\>* to visit the service, neither by browser nor another VM which can ping the node.

I cannot use *curl \<ClusterIP\>:\<clusterPort\>* to visit the service, either.

All of the results are: *curl: (56) Recv failure: Connection reset by peer*

i make the ufw inactive, and set *sudo iptables -P FORWARD ACCEPT*

Is there anyone can help me? I am new to use microk8s.

**Comment by ktsakalozos** [comment]
Hi @easybyr 

Would you be able to share the yaml manifests you are applying and a step by step walkthrough (or script) on what you are doing and what is failing? I am practicaly asking for a way to reproduce what you have?

Thanks, and well come to MicroK8s.
