### ISSUE TITLE
`kubectl top pod` does not show any utilization %

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#356]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
`kubectl top nodes` show utilization % but not `kubectl top pod`.

**Comment by ktsakalozos** [comment]
Hi @khteh 

You need to `microk8s.enable metrics-server` and wait a good 5-10 minutes to have metrics flowing in.

**Comment by khteh** [comment]
Does this project use https://github.com/kubernetes-incubator/metrics-server? If yes, which version? I use 1.8+ and bumps into the issue https://github.com/kubernetes-incubator/metrics-server/issues/created_by/khteh

**Comment by ktsakalozos** [comment]
Ah, now I see your point. You want to see a percentage and not a single value. Unfortunately top for pods give you a [quality value](https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/walkthrough.md#quantity-values) and not a percentage. Have a look here: https://github.com/kubernetes-incubator/metrics-server/issues/193#issuecomment-451309811

Yes, we are using the metrics server you spotted.

**Comment by khteh** [comment]
Correction: "Quantity" value.
