### ISSUE TITLE
Node not found error

### ISSUE THREAD

**Issue by lxjhk** [ubuntu/microk8s#368]
Upon installation on a fresh ubuntu system,  I could not get the daemon-kubelet to start. 

```
Mar 21 16:56:09 to_the_moon microk8s.daemon-kubelet[22979]: E0321 16:56:09.296705   22979 kubelet.go:2266] node "to_the_moon" not found
Mar 21 16:56:09 to_the_moon microk8s.daemon-kubelet[22979]: E0321 16:56:09.397054   22979 kubelet.go:2266] node "to_the_moon" not found
Mar 21 16:56:09 to_the_moon microk8s.daemon-kubelet[22979]: E0321 16:56:09.497314   22979 kubelet.go:2266] node "to_the_moon" not found
Mar 21 16:56:09 to_the_moon microk8s.daemon-kubelet[22979]: E0321 16:56:09.597602   22979 kubelet.go:2266] node "to_the_moon" not found
```

`microk8s.status` returns: `microk8s is not running. Use microk8s.inspect for a deeper inspection.`

**Comment by ktsakalozos** [comment]
Hi @lxjhk 

There are a few reasons why this might be happening, but I cannot say for sure right now. Could you run a `microk8s.inspect` and attach here the tarball produced? I wonder what is special about you setup. "to_the_moon" is your hostname, right? You can access local services through that, right? How does your `/etc/hosts/` look like?

Thanks

**Comment by masstamike** [comment]
I was experiencing this issue in combination with #375 and #198. The workaround I found was just to move the service I had already listening on port 8080 and reinstall.

**Comment by muditjuneja** [comment]
Can you help? Same issue.

**Comment by joeky888** [comment]
Change your hostname.

Your hostname `to_the_moon ` contains  invalid underscore character.

Rename your hostname to `to-the-moon` and Run `microk8s.reset` again should be fine.

**Comment by ktsakalozos** [comment]
This is something we could detect on the `microk8s.inspect` script and offer a warning (https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh).

We could detect such hostnames in the configure hook https://github.com/ubuntu/microk8s/blob/master/snap/hooks/configure and use the `--hostname-override` argument of kubelet to provide a valid node name.

**Comment by joeky888** [comment]
Maybe just add

```sh
function check_hostname {
  if [ $(hostname) =~ "_" ]; then
    printf -- '\033[31m FAIL: \033[0m Hostname %s contains invalid underscore characters \n' "$(hostname)"
  fi
}
```

**Comment by lazzarello** [comment]
> Change your hostname.

Every time I change the hostname of the base OS after microk8s is installed, it completely breaks microk8s.

**Comment by ukd1** [comment]
I'm getting this and not sure how to fix it; the node is pingable using it's hostname, from itself and other nodes...

**Comment by bc185174** [comment]
> This is something we could detect on the `microk8s.inspect` script and offer a warning (https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh).
> 
> We could detect such hostnames in the configure hook https://github.com/ubuntu/microk8s/blob/master/snap/hooks/configure and use the `--hostname-override` argument of kubelet to provide a valid node name.

I recently stumbled upon this issue too. Just doing a quick search of the repo there is a number of places that use `socket.gethostname()`.  In addition to setting `--hostname-override` in the kubelet config, I would also assigned it in the kube-proxy config.

As for the script you mentioned, maybe something like this? 

```bash
hostname_override=$(sed -nE 's/--hostname-override=(.*)/\1/p' ${SNAP}/args/kubelet)
if [[ hostname_override ]]; then
    hostname=hostname_override
else
    hostname=$(hostname)
fi
```
