### ISSUE TITLE
/snap/microk8s/442/usr/bin/gawk: error while loading shared libraries: libreadline.so.6

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#370]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20190322_115821.tar.gz](https://github.com/ubuntu/microk8s/files/2994873/inspection-report-20190322_115821.tar.gz)

We appreciate your feedback. Thank you for using microk8s.
After I have done `snap install microk8s --channel=1.14/beta --classic` and try to change default port, this is what I get:

`/snap/microk8s/442/usr/bin/gawk: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory`

**Comment by ktsakalozos** [comment]
Can you please tell me what exactly did you do to change the default port? Please be as descriptive as possible so I can reproduce the error.

**Comment by ktsakalozos** [comment]
`microk8s.config` throws this. I am able to reproduce it. Should have a fix for this soon. Thank you for reporting it here.
