### ISSUE TITLE
storage addon but no pv/pvc created on default storage class

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#377]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
I `microk8s.enable storage` and then `apply -f` a statefulset. However, no pod is created at all and no pv/pvc is created. It has been a while since I last created a local cluster. Do I need to do anything to use the "default" storage class (microk8s-hostpath) for the pvc/pv? Thanks.
```
$ microk8s.kubectl get sc
NAME                          PROVISIONER            AGE
microk8s-hostpath (default)   microk8s.io/hostpath   113m
```

**Comment by ktsakalozos** [comment]
@khteh you should have a pod hostpath-provisioner and a replicaset.apps/hostpath-provisioner deployment under the kube-system namespace.

**Comment by khteh** [comment]
Yes but they are all not ready at all:
```
$ microk8s.kubectl get all -n kube-system
NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/heapster               ClusterIP   10.152.183.248   <none>        80/TCP              147m
service/kube-dns               ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP       148m
service/kubernetes-dashboard   ClusterIP   10.152.183.102   <none>        443/TCP             147m
service/metrics-server         ClusterIP   10.152.183.242   <none>        443/TCP             146m
service/monitoring-grafana     ClusterIP   10.152.183.219   <none>        80/TCP              147m
service/monitoring-influxdb    ClusterIP   10.152.183.125   <none>        8083/TCP,8086/TCP   147m

NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/heapster-v1.5.2                  0/1     0            0           147m
deployment.apps/hostpath-provisioner             0/1     0            0           147m
deployment.apps/kube-dns                         0/1     0            0           148m
deployment.apps/kubernetes-dashboard             0/1     0            0           147m
deployment.apps/metrics-server-v0.2.1            0/1     0            0           146m
deployment.apps/monitoring-influxdb-grafana-v4   0/1     0            0           147m
```
What happen?

**Comment by khteh** [comment]
$ microk8s.kubectl describe deployment hostpath-provisioner -n kube-system
Name:                   hostpath-provisioner
Namespace:              kube-system
CreationTimestamp:      Tue, 26 Mar 2019 13:31:17 +0800
Labels:                 k8s-app=hostpath-provisioner
Annotations:            kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"hostpath-provisioner"},"name":"ho...
Selector:               k8s-app=hostpath-provisioner
Replicas:               1 desired | 0 updated | 0 total | 0 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  k8s-app=hostpath-provisioner
  Containers:
   hostpath-provisioner:
    Image:      cdkbot/hostpath-provisioner-amd64:latest
    Port:       <none>
    Host Port:  <none>
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      PV_DIR:     /var/snap/microk8s/common/default-storage
    Mounts:
      /var/snap/microk8s/common/default-storage from pv-volume (rw)
  Volumes:
   pv-volume:
    Type:          HostPath (bare host directory volume)
    Path:          /var/snap/microk8s/common/default-storage
    HostPathType:  
OldReplicaSets:    <none>
NewReplicaSet:     <none>
Events:            <none>

**Comment by khteh** [comment]
Related to https://github.com/ubuntu/microk8s/issues/376?

**Comment by khteh** [comment]
https://github.com/ubuntu/microk8s/issues/300
