### ISSUE TITLE
Instructions to migrate from kubedns to coredns in existing cluster

### ISSUE THREAD

**Issue by robinchm** [ubuntu/microk8s#378]
Just upgraded to 1.14 and everything works fine.

From what I read, the coredns is now the default whenever new microk8s is deployed. But any old deployment will stay with what they are using at the moment.

While this is a perfectly valid behaviour, is there any instruction on how to switch the existing kubedns to coredns and keep coredns as default? From the announcement this seems to be doable via a change in charm configuration but I don't understand how to do it.

I am running microk8s experimentally on my own machine. Installed it pretty much the standard way via snap on ubuntu 18.04, nothing more and nothing less.

**Comment by ktsakalozos** [comment]
Hi @robinchm 

The current `microk8s.enable dns` will still get you KubeDNS. We should work on a CoreDNS addon. For now if you want to install CoreDNS you will have to follow the official instructions: https://github.com/coredns/deployment/tree/master/kubernetes .

> the coredns is now the default whenever new microk8s is deployed
Where did you read this?

Thanks

**Comment by robinchm** [comment]
Hi @ktsakalozos

Maybe I misunderstood - kubernetes 1.14 is using but microk8s.enable is staying with kubedns at the moment. I read it here but this article talked about a number of things together and I probably got it wrong.

That article is:
https://blog.ubuntu.com/2019/03/25/kubernetes-1-14-now-available-from-canonical

I just want to stay with the default so if microk8s is using kubedns I'll stay with that. Thanks a lot!
