### ISSUE TITLE
syslog messages every second: OpenAPI AggregationController: Processing item k8s_internal_local_delegation_chain_0000000002

### ISSUE THREAD

**Issue by cruftex** [ubuntu/microk8s#379]
Fresh microk8s on Ubuntu 18.04:
`snap install microk8s --classic`
microk8s v1.14.0 from Canonical✓ installed

Results in two log entries on syslog every second:
tail -f /var/log/syslog
````
Mar 26 18:44:07 tapsy microk8s.daemon-apiserver[31821]: I0326 18:44:07.398394   31821 controller.go:102] OpenAPI AggregationController: Processing item k8s_internal_local_delegation_chain_0000000001
Mar 26 18:44:07 tapsy microk8s.daemon-apiserver[31821]: I0326 18:44:07.398649   31821 controller.go:102] OpenAPI AggregationController: Processing item k8s_internal_local_delegation_chain_0000000002
Mar 26 18:44:08 tapsy microk8s.daemon-apiserver[31821]: I0326 18:44:08.399004   31821 controller.go:102] OpenAPI AggregationController: Processing item k8s_internal_local_delegation_chain_0000000001
Mar 26 18:44:08 tapsy microk8s.daemon-apiserver[31821]: I0326 18:44:08.399299   31821 controller.go:102] OpenAPI AggregationController: Processing item k8s_internal_local_delegation_chain_0000000002
````

Maybe a separate issue:
It seems that the API server is actually doing something every second. Is it possible to reduce the load?

**Comment by ktsakalozos** [comment]
Hi @cruftex 

To tune the API server you can play with its parameters: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/ have a look at https://github.com/ubuntu/microk8s#configuring-microk8s-services to see how you can apply the desired arguments.

I see there is a PR upstream to hide this kind on annoying messages: https://github.com/kubernetes/kubernetes/pull/73121/files but I do not have a good solution for this right now.
