### ISSUE TITLE
timeout expired waiting for volumes to attach/mount for pod after snap auto refresh to v1.14.0 (rev483 / classic)

### ISSUE THREAD

**Issue by hatzlj** [ubuntu/microk8s#381]
After an automatic snap refresh today which upgraded to v1.14.0 (an introduced containerd instead of docker) we encountered the following error on some pods:

`timeout expired waiting for volumes to attach/mount for pod`

the pods affected were binding dynamic volumen claims of a custom nfs-provider (find a minimal config example attached [test.txt](https://github.com/ubuntu/microk8s/files/3008145/test.txt)).

since we were not aware of the snap auto refresh taking place it was hard to track down what caused the problems in the first place (some hours before everything was working fine and we did not change anything).
 
after some hours of research we did not really find out what caused the problem (maybe docker did not release some volume mount prior to the upgrade) but a host machine reboot fixed the problem and now everything works as expected (now with containerd instead of dockerd).

we file this issue to see if someone else encountered the same problem and had a chance to track down the initial problem during the upgrade.

Find attached the microk8s.inspect tarball (dumped after the upgrade) for reference:
[inspection-report-20190326_122820.tar.gz](https://github.com/ubuntu/microk8s/files/3008152/inspection-report-20190326_122820.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @hatzlj 

In order to not get any disruption in your workflow you could consider setting exactly the time updates will reach you. Read more at https://docs.snapcraft.io/keeping-snaps-up-to-date/7022

Especially in the case of MicroK8s, if you do not specify a channel you want to follow you should expect some disruption every time there is a Kubernetes upstream release. We are doing our best to keep everything backwards compatible but this is not always possible. To have full control over which k8s release you have running you should deploy MicroK8s with the `--channel` set, eg:
```
sudo snap install microk8s --classic --channel=1.14/stable
```

Apologies for any inconvenience we may have caused.

**Comment by hatzlj** [comment]
thanks @ktsakalozos for pointing out the snap update time feature, i've stumbled across it when researching possible solutions. We're using microk8s for internal staging systems so disruption on updates is not really a big problem. It was more a problem that we haven't been aware of the snap auto refresh thing.

Regarding the problem with the volumes during the upgrade: usually I would check release-notes or a changelog or upgrade-notes before (or after) upgrading software, especially when encountering problems. Do you have such a thing for microk8s - i didn't really find anything. Maybe I would have read there something like: "we're switching from docker to containerd, if you encounter problems with volumes try rebooting your cluster"

thanks for your efforts with microk8s

**Comment by ktsakalozos** [comment]
We have to work on automating the release notes. We try to keep humans out of the microK8s release process so as to follow the rather aggressive release schedule of upstream Kubernetes.

**Comment by hatzlj** [comment]
@ktsakalozos, of course that makes sense - automation is the key to keep on track.

with yesterdays update to v1.14.0 (Rev 492) we had again the same problem with timeout expired waiting for volumes to attach/mount for pod (described earlier) and needed to reboot our host again. 

Is there any way for me to see what commits from the microk8s repo went into v1.14.0 (Rev 492) and v.1.14.0 (Rev 483) to perhaps track down the cause for this behaviour in the changes introduced with this versions?

Thanks,
Jakob

**Comment by ktsakalozos** [comment]
By comparing the 1.13 branch to master you get everything that has changed from the latest 1.13 to 1.14 (https://github.com/ubuntu/microk8s/compare/1.13...master?expand=1) 

The way to fix this is to reproduce the issue with a minimal setup and then place it in our tests (that we run on every upgrade) so we do not break you again. Do you think you could provide a minimal manifest?

**Comment by hatzlj** [comment]
again when upgrading to 1.14.1 (522) issues when restarting the cluster after snap auto refresh. there seem to be serious issues with cluster upgrading. is there any automated testing of the actual snap auto refresh before the snap update is rolled out publicly?

see also:
https://github.com/ubuntu/microk8s/issues/432
https://github.com/ubuntu/microk8s/issues/430

**Comment by ktsakalozos** [comment]
@hatzlj, do you think you could provide a minimal manifest? I need to reproduce this issue and put it in our CI so we will not break you again.

There are a number of tests we run before pushing out a new release. We verify that the upgrade path works on each channel we release even on edge. Here is how that works. We have a bunch of validators here: https://github.com/ubuntu/microk8s/blob/master/tests/validators.py
The script at https://github.com/ubuntu/microk8s/blob/master/tests/test-upgrade.py deploys the old snap, runs the validators then upgrades the snap and reruns the validators. Obviously we are not covering your case. What I would like from you is a yaml manifest with a mini-version of your setup so I can add a validator. Perhaps the initial test.txt file you posted could serve as a starting point?

The two issues you linked are not related to what you are seeing.

I appreciate your help in spotting and fixing this hole in our tests and I apologize for the inconvenience we caused.

**Comment by ktsakalozos** [comment]
@hatzlj i have taken some time to create the a setup based on the manifest you provided at the very top. Here is what I came up with: https://gist.github.com/ktsakalozos/6ac9d2ad698019c88181e786d63fd5b5
I am setting up the environment with:
```
sudo apt install nfs-common
sudo snap install microk8s --classic
microk8s.status --wait-ready
microk8s.enable storage
# And apply the manifest
microk8s.kubectl apply -f https://gist.githubusercontent.com/ktsakalozos/6ac9d2ad698019c88181e786d63fd5b5/raw/f8b43870cde3673a30418eafb6be6c097ec4d8b3/nfs-provisioner.yaml
```

As soon as the deployment is ready I am able to reproduce timeouts by restarting the Kubernetes services (service restarts is what happens during an upgrade):
```
microk8s.stop --force
microk8s.start
```

There must be some race condition between freeing and remounting the nfs mounts. In order to mitigate this behavior I used the latest nfs-proviosner image (`quay.io/kubernetes_incubator/nfs-provisioner:latest`) and also added a `terminationGracePeriodSeconds: 10`. Both changes are in the gist above commented out.

Let me know if the setup I am testing is similar to what you have and if the changes make sense for you. Also if you have any suggestions on how we can gracefully handle mounts during restart I would me grateful.

**Comment by hatzlj** [comment]
Hi @ktsakalozos ,

thanks for your input - i'll test the `timeoutGracePeriod` tomorrow. 
In addition to the setup you described, we also use the following settings for microk8s
`microk8s.enable dns dashboard storage ingress`
and it seems that also the kubernetes dashboard is not coming up again after service restart. What we have seen, is that the kubelet fails to start in the first place, which may hinder all other kubernetes objects to start properly.
I'm trying to reproduce and attach the microk8s.daemon* logs.

**Comment by ktsakalozos** [comment]
Hi @hatzlj 

I see in your logs you are still using the v1.14.0 revision (`I0424 03:27:05.920089    3943 server.go:417] Version: v1.14.0`). On v1.14.1 we have addressed the issue https://github.com/ubuntu/microk8s/issues/423 that describes what you are seeing, kubelet not coming up. My suggestion is to move to 1.14.1 and see if the problem persists.

**Comment by hatzlj** [comment]
We've abandoned microk8s and moved to a hosted solution because maintenance of our own cluster was not feasible anymore, so I'm sorry we'll not follow up on this issue anymore.
Nevertheless, thanks for your input and effort.
