### ISSUE TITLE
auth for https services

### ISSUE THREAD

**Issue by xrpn** [ubuntu/microk8s#383]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

after installing 1.14/stable the following holds:

```
[inspection-report-20190326_111105.tar.gz](https://github.com/ubuntu/microk8s/files/3009574/inspection-report-20190326_111105.tar.gz)


~$ microk8s.kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:16443
Heapster is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Grafana is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
InfluxDB is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-influxdb:http/proxy
```
(note the https;// ).  Available documentation shows `http://` and appears not to mention what credentials to use.  In `/var/snap/microk8s/484/credentials` there are some hints, e.g. perhaps user admin, pw admin, but 

```
https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
```

trying that and other combinations from basic_auth.csv in the same directory keeps yielding
```
kind | "Status"
-- | --
apiVersion | "v1"
metadata | {}
status | "Failure"
message | "Unauthorized"
reason | "Unauthorized"
code | 401
```

**Comment by kobaltz** [comment]
The username is `admin` and the password can be found with `microk8s.config`. At the very bottom, you should see `password: XXXXX`

**Comment by ktsakalozos** [comment]
Hi @xrpn

After doing a `microk8s.kubectl proxy` you should be able to reach grafana from the URL you see with `microk8s.kubectl cluster-info`.  

> Available documentation shows `http://`

We need to do a better job with our docs. Where did you see the `http://` reference?

Thanks

**Comment by mrmowgli** [comment]
The tutorial at https://tutorials.ubuntu.com/tutorial/install-a-local-kubernetes-with-microk8s#4 needs to include this information, otherwise there is no way to access the pages.

**Comment by a-hahn** [comment]
The tutorial https://ubuntu.com/blog/monitoring-at-the-edge-with-microk8s states 
> For Grafana, the username and password will be: admin/admin.
which is just wrong and should be fixed
