### ISSUE TITLE
Ansible role to provision microk8s (single node and multi-node)

### ISSUE THREAD

**Issue by jack1902** [ubuntu/microk8s#3880]
#### Summary

Ability to form microk8s clusters using ansible officially supported by canonical would be great

#### Why is this important?

Microk8s is great at being a single-node offering and can also cater for multi-node offerings, however achieving a multi-node offering "out of the box" is not simply and repeatable without automation. Ansible is a great tool to connect to remote machines and run commands such as `microk8s join` to form a cohesive microk8s cluster.

It would be ideal to be able to cater for the following:
- single node setup (basic microk8s install)
- multi-node setup (microk8s install whereby all targets are considered worker and control-plane)
- multi-node setup (control plane and worker split)

#### Are you interested in contributing to this feature?

Currently i don't have much time to contribute to this but i do feel there would be benefits to getting a design together which can then be tested (happy to assist in testing if needed).

For a great starting point (something i have been using previously): https://github.com/istvano/ansible_role_microk8s

**Comment by berkayoz** [comment]
Hey @jack1902 ,
Thank you for the feedback! 
We've heard similar requests about Ansible roles and are discussing this topic as a team. I'll keep you updated on any related news. We are open to and appreciative of any contributions.

**Comment by ktsakalozos** [comment]
> Any updates for this?

There are no plans to have an officially supported Ansible role. You will have to use one of the community driven projects.
