### ISSUE TITLE
How to change dashboard / grafana login credentials?

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#389]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy

It prompts for username/password....

**Comment by khteh** [comment]
Got it!

**Comment by khteh** [comment]
How to change the long crypted password to a customized one?

**Comment by ktsakalozos** [comment]
Right now this username/password are random strings created at MicroK8s install time. You should be able to add more uses in `/var/snap/microk8s/current/credentials/basic_auth.csv`. You can read more here: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-password-file

**Comment by MingyiZhangQimia** [comment]
Could you please tell me where I can find the username and password? Thank you!

**Comment by keltik85** [comment]
Hi, I did the following to get microk8s running (using [this guide](https://tutorials.ubuntu.com/tutorial/install-a-local-kubernetes-with-microk8s#3)):
```
root@my-pc~# sudo snap install microk8s --classic
root@my-pc~# microk8s.enable dns dashboard

root@my-pc:/home/atekin/Downloads/microservices-demo# kubectl cluster-info
Kubernetes master is running at https://127.0.0.1:16443
Heapster is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Grafana is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy
InfluxDB is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-influxdb:http/proxy
```

Problem is I cant access the Grafana Board at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/monitoring-grafana/proxy , because i don't know where to look up the username/password that is generated by default.

**Comment by khteh** [comment]
/var/snap/microk8s/current/config

**Comment by StoyanStAtanasov** [comment]
The docs say `/var/snap/microk8s/current/credentials/basic_auth.csv` is deprecated (for prior to version 1.19). 
Where to find grafana credentials for versions 1.19 and up?

**Comment by Temikus** [comment]
@StoyanStAtanasov it's default Grafana password/login now:
- User: `admin`
- Password: `admin`

**Comment by tbscode** [comment]
I'm using microk8s (v1.25.14 rev 5975) with `observability` enabled.

First of all I do not see Grafana listed when I run `microk8s kubectl cluster-info`.
But I do see the following service:
```
NAME                                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                                                   
kube-prom-stack-grafana   ClusterIP   <...>                   <none>        80/TCP
```

If I port forward this to my local machine I can see the login screen.
I can login with credentials retrieved from the secret `kube-prom-stack-grafana` also in the `observability` namespace.

Default seem to be `admin:prom-operator`.

*How can I change them? / Set different initial defaults? *

**Comment by tbscode** [comment]
Ok got two ways:

- you can use the UI ( after login with defaults )
- or use `grafana-cli` in the container `microk8s kubectl exec --stdin --tty kube-prom-stack-grafana-*** sh -n observability`

Still wondering if there is some way to configure default for this, would be nice for automatic setups.

**Comment by codespearhead** [comment]
The credentials for the new `observability` add-on: [(user/pass: admin/prom-operator)](https://github.com/canonical/microk8s-core-addons/blob/7a64a17ddf136fc3a67ec6b13d985e05c739e2fe/addons/observability/enable#L120)
