### ISSUE TITLE
apiserver doesn't start when offline

### ISSUE THREAD

**Issue by eroglyph** [ubuntu/microk8s#392]
I believe I'm having a similar problem to #73 and #149.

I'm using microk8s on a laptop and when I'm connected to the network, it works fine. However, when I am disconnected the api server refuses to start. I'm getting `connection refused` messages to `http://127.0.0.1:8080/api` and I'm getting the `no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"` message in /var/log/syslog which makes sense since I'm offline.

I ran into this problem on both v1.13 and v1.14.

**Comment by eroglyph** [comment]
[inspection-report-20190404_082807.tar.gz](https://github.com/ubuntu/microk8s/files/3043409/inspection-report-20190404_082807.tar.gz)

Adding inspection report.

**Comment by ktsakalozos** [comment]
@eroglyph this message 
```
error: unable to find suitable network address.error='no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this
```

is not something MicroK8s can do much for. Kubernetes api server will not start under such conditions and suggests a reconfiguration. To update the configuration of the api server you will need to edit `/var/snap/microk8s/current/args/kube-apiserver` and `microk8s.stop`/`microk8s.start`.

**Comment by eroglyph** [comment]
@ktsakalozos
Modifying the api server configuration wasn't working for me. I was able to work around the issue by creating a VM using Virtualbox to create a Host-only Network.

In this case, the IP assigned to my machine is 192.168.58.1 for the vboxnet0 interface. Then I added the IP as a default route
``sudo route add default gw 192.168.58.1``
and created and started a blank VM with the vboxnet0 interface attached so that the connection would appear legit.  After that, I was able to run ``microk8s.start`` and ``microk8s.status`` shows that microk8s is running.

I'm not sure that this is exactly the best way to simulate a network while offline, but I'm open to better solutions.

**Comment by urbandroid** [comment]
i have the same problem

**Comment by magick93** [comment]
I also have the same problem.

>  To update the configuration of the api server you will need to edit /var/snap/microk8s/current/args/kube-apiserver and microk8s.stop/microk8s.start.

Can someone please describe exactly what should be edited, and changed in what way?

**Comment by kkmoslehpour** [comment]
Also getting this issue on my box.
