### ISSUE TITLE
Kibana 404 response with fluentd-elasticsearch-kibana plugin

### ISSUE THREAD

**Issue by robinchm** [ubuntu/microk8s#394]
With version 1.14
`microk8s.enable fluentd` successfully set up services of fluentd, elasticsearch and kibana.

However visiting `http://10.1.1.82:5601` returns a plain json:
```
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

I've googled similar issue [here](https://github.com/kubernetes-sigs/kubespray/issues/3322), but following the solution to remove  "SERVER_BASEPATH" from kibana deployment does not work. It actually makes the service unreachable.

Could someone confirm whether this works in 1.14, so I know whether it's something to do with my own customization (though I can't remember customizing anything that should affect this)?

**Comment by ktsakalozos** [comment]
Hi @robinchm 

After `microk8s.enable fluentd` do a `microk8s.kubectl proxy` to create a proxy at `127.0.0.1:8001`. Leave the shell with the proxy open and on a second shell do a `microk8s.kubeclt cluster-info`. You should see a line like this:
```
Kibana is running at https://127.0.0.1:16443/api/v1/namespaces/kube-system/services/kibana-logging/proxy
```

If you head to the above URL you will be asked for the username/password shown at `microk8s.config`.

**Comment by robinchm** [comment]
@ktsakalozos Thanks I should have used the endpoint specified in `kubectl cluster-info`, and that works.
By default it does not ask for passwords.

**Comment by RoSk0** [comment]
Same issue on v1.18.6. 
Instructions from @ktsakalozos doesn't help - link returns 401 and doesn't ask for auth. 
Please help
