### ISSUE TITLE
monitoring-influxdb-grafana CrashLoopBackoff

### ISSUE THREAD

**Issue by queueburt** [ubuntu/microk8s#397]
[inspection-report-20190331_191304.tar.gz]

InfluxDB container in monitoring-influxdb-grafana pod failing to bind to correct address when installed with 'microk8s.enable dashboard'.  DNS, Heapster, and Dashboard pods all deploy successfully.

The specific error inside the influx container is "run: open server: listen: listen tcp x.x.x.x:8088: bind: cannot assign requested address"

(x.x.x.x is a random public IP)

**Comment by ktsakalozos** [comment]
@queueburt could you please reattach the tarball produced by `microk8s.inspect`?

**Comment by queueburt** [comment]
I'm going to close this for now, as the issue seems to be related to the way influxdb is resolving its own DNS.  I haven't fixed the issue as it's fairly low priority, but it seems to be related to the influxdb container internals and not microk8s.
