### ISSUE TITLE
microk8s start successful, but there is no any pod

### ISSUE THREAD

**Issue by 15050050972** [ubuntu/microk8s#399]
I am in centos 7.6, I install the snap and microk8s. my microk8s version is v1.14.0
then I start microk8s, but there isn't any pod in kubectl's output:
why?
BTW, I'm try this solution in microk8s (https://github.com/AliyunContainerService/gpushare-scheduler-extender), can I do this? Or Do I have to try this solution in native k8s cluster?
```
[root@localhost gpushare]# microk8s.start
Started.
[root@localhost gpushare]# microk8s.kubectl get po --all-namespaces
No resources found.
[root@localhost gpushare]# microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster

/snap/microk8s/492/inspect.sh: line 100: ufw: command not found
Building the report tarball
  Report tarball is at /var/snap/microk8s/492/inspection-report-20190401_100339.tar.gz
```
 thanks for your time.
[inspection-report-20190401_100339.tar.gz](https://github.com/ubuntu/microk8s/files/3029776/inspection-report-20190401_100339.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @15050050972 

Right after you snap install MicroK8s you get an empty Kubernetes cluster with no pods. You have to then enable the addons you want eg `microk8s enable dns dashboard gpu`. And deploy whatever workload you wish. I am not faminiral with the solution you want to deploy but I see it wants GPU support, so I would strongly recommend you use Ubuntu and deploy there the nvidia GPU drivers before you `microk8s.enable gpu`.

**Comment by morhook** [comment]
I think we should close this issue.
