### ISSUE TITLE
I need to use Docker with microk8s

### ISSUE THREAD

**Issue by amentis** [ubuntu/microk8s#403]
I need the ability to use Docker with microk8s for use in my own scripts. Please provide an option to choose between Docker and cri-o with microk8s

**Comment by ktsakalozos** [comment]
Hi @amentis 

You can install docker or any other container building tool chain next to MicroK8s. Then you need to `microk8s.enable registry` and push the containers you create to the local registry at `localhost:32000`. Have a look at https://microk8s.io/docs/registry . 

The packaging of docker into MicroK8s has proven problematic. I do not see us going back. We could include a container building tool chain if you have any suggestions.

Thank you
