### ISSUE TITLE
microk8s.ctr --help prompts for sudo

### ISSUE THREAD

**Issue by johnsca** [ubuntu/microk8s#406]
With microk8s 1.14, `microk8s.ctr --help` prompts for the sudo password, which seems unnecessary.  I'm unclear which `microk8s.ctr` subcommands would require root, but it surely isn't all of them.

**Comment by balchua** [comment]
As far as i remember ctr uses unix socket to talk to containerd.  This normally requires sudo unless the user is added to the group owning the containerd socket.
