### ISSUE TITLE
insecure HTTP registry in CRI

### ISSUE THREAD

**Issue by hjanuschka** [ubuntu/microk8s#412]
i am having a insecure non https internal registry runing at `gitlab.krone.at:5000`

it'd need access from my microk8s setup
so i tried to find out how to add it, and tried it with all variations

`/var/snap/microk8s/current/args/containerd-template.toml`

```
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."local.insecure-registry.io"]
          endpoint = ["http://gitlab.krone.at:5000"]
        [plugins.cri.registry.mirrors."gitalb.krone.at"]
          endpoint = ["http://gitlab.krone.at:5000"]
        [plugins.cri.registry.mirrors."gitalb.krone.at:5000"]
          endpoint = ["http://gitlab.krone.at:5000"]
        [plugins.cri.registry.mirrors."heli.local"]
          endpoint = ["http://gitlab.krone.at:5000"]
        [plugins.cri.registry.mirrors."192.168.239.60"]
          endpoint = ["http://gitlab.krone.at:5000"]
```

stop && start for sure.
but it does not work inside k8s and not via

```
microk8s.ctr  images pull  gitlab.krone.at:5000/XX/YYY:master
ctr: failed to resolve reference "gitlab.krone.at:5000/krn/api:master": failed to do request: Head https://gitlab.krone.at:5000/v2/krn/api/manifests/master: http: server gave HTTP response to HTTPS client
```

so it is not using http

any ideas? i am quiet stuck now.
thx in advance, and keep up the great project ❤️

**Comment by sfriedel** [comment]
I believe the reason why this doesn't work is that you have 2 typos in your configuration:
```
[plugins.cri.registry.mirrors."gitalb.krone.at"]
[plugins.cri.registry.mirrors."gitalb.krone.at:5000"]
```
Notice the `gitalb` which should probably be `gitlab`. Keep in mind though that this is not the standard way to deal with private docker registries in kubernetes. For that you should be using `imagePullSecrets` in your Pod yaml. See [here](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/) for more information about that.

**Comment by hjanuschka** [comment]
OMG i am so sorry!
it worked, but i just went with making my registry use https
