### ISSUE TITLE
snap remove and install again error

### ISSUE THREAD

**Issue by matincvar** [ubuntu/microk8s#420]
Hi, 
I was testing microk8s 1.14 very well an decide to remove it and then install again.
I did this in 2 ubuntu 18.14 desktops:

1) `sudo snap remove microk8s`
2) `sudo snap install microk8s --classic`

and in the 2 diferents descktops I get:

error: cannot perform the following tasks:
- Ejecutar el enganche de instalación del snap "microk8s" si está presente (run hook "install": 
-----
+ export LD_LIBRARY_PATH=/snap/microk8s/492/lib:/snap/microk8s/492/usr/lib:/snap/microk8s/492/lib/x86_64-linux-gnu:/snap/microk8s/492/usr/lib/x86_64-linux-gnu
+ LD_LIBRARY_PATH=/snap/microk8s/492/lib:/snap/microk8s/492/usr/lib:/snap/microk8s/492/lib/x86_64-linux-gnu:/snap/microk8s/492/usr/lib/x86_64-linux-gnu
+ export PATH=/snap/microk8s/492/usr/sbin:/snap/microk8s/492/usr/bin:/snap/microk8s/492/sbin:/snap/microk8s/492/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/usr/local/bin
+ PATH=/snap/microk8s/492/usr/sbin:/snap/microk8s/492/usr/bin:/snap/microk8s/492/sbin:/snap/microk8s/492/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/usr/local/bin
+ source /snap/microk8s/492/actions/common/utils.sh
+ cp -r /snap/microk8s/492/default-args /var/snap/microk8s/492/args
+ mkdir /var/snap/microk8s/492/certs
+ openssl genrsa -out /var/snap/microk8s/492/certs/serviceaccount.key 2048
Generating RSA private key, 2048 bit long modulus
........................................................................+++
.................+++
unable to write 'random state'
e is 65537 (0x010001)
+ openssl genrsa -out /var/snap/microk8s/492/certs/ca.key 2048
Generating RSA private key, 2048 bit long modulus
..........+++
.+++
unable to write 'random state'
e is 65537 (0x010001)
+ openssl req -x509 -new -nodes -key /var/snap/microk8s/492/certs/ca.key -subj /CN=127.0.0.1 -days 10000 -out /var/snap/microk8s/492/certs/ca.crt
+ openssl genrsa -out /var/snap/microk8s/492/certs/server.key 2048
Generating RSA private key, 2048 bit long modulus
......................................................................................+++
.........................................+++
unable to write 'random state'
e is 65537 (0x010001)
++ get_default_ip
+++ /snap/microk8s/492/bin/netstat -rn
+++ /snap/microk8s/492/bin/grep '^0.0.0.0'
+++ /snap/microk8s/492/usr/bin/gawk '{print $NF}'
+++ head -1
++ local DEFAULT_INTERFACE=wlxf81a6729973c
+++ /snap/microk8s/492/bin/grep 'inet '
+++ /snap/microk8s/492/sbin/ifconfig wlxf81a6729973c
+++ /snap/microk8s/492/usr/bin/gawk '{print $2}'
+++ /snap/microk8s/492/bin/sed -e s/addr://
++ local IP_ADDR=
++ echo
+ IP_ADDR=
+ produce_server_cert
/snap/microk8s/492/actions/common/utils.sh: línea 108: $1: variable sin asignar
-----)

Can anybody help me? thanks!!
Mart

**Comment by balchua** [comment]
The issue seems to be similar to this.  https://github.com/ubuntu/microk8s/issues/400. It suggests to use the edge version.  Maybe you can try that.

**Comment by ktsakalozos** [comment]
Indeed this looks like https://github.com/ubuntu/microk8s/issues/400. @matincvar can you please try to get MicrK8s from edge:
```
sudo snap install microk8s --classic --edge
```

If the problem persists, can you please share the output of `netstat -rn` and `ip -o -4 addr list`?

**Comment by matincvar** [comment]
OK. I am in ubuntu 18.04

`snap version
snap    2.37.4+18.04.1
snapd   2.37.4+18.04.1
series  16
ubuntu  18.04
kernel  4.15.0-47-generic
`
`snap list
Name               Version  Rev   Tracking  Publisher   Notes
core                        6673  stable    canonical✓  roto
core18                      782   stable    canonical✓  roto
gitkraken                   138   stable    gitkraken✓  roto
gnome-3-26-1604             82    stable/…  canonical✓  roto
gnome-3-28-1804             23    stable    canonical✓  roto
gnome-calculator            352   stable/…  canonical✓  roto
gnome-characters            206   stable/…  canonical✓  roto
gnome-logs                  57    stable/…  canonical✓  roto
gtk-common-themes           1198  stable/…  canonical✓  roto
`

**Comment by matincvar** [comment]
well, I do this to fix the problem into en new and fresh ubuntu:

`sudo snap install microk8s --classic --edge`

thanks all.
