### ISSUE TITLE
Services with no backend pod available still accept TCP connections from netcat

### ISSUE THREAD

**Issue by matthiasamberg** [ubuntu/microk8s#426]
## Services with backend pods do not route TCP requests properly (at least in this case shown below)

We use the bash line below in an init container to wait until a zookeeper service becomes available (until netcat can establish a TCP connection):
This works on GKE (1.12) and OpenShift, however not in microk8s (1.12, 1.13 nor 1.14) where it sometimes continues (it is able to establish a TCP connection, even though it shouldn't be possible to do so (zero zookeeper instances available):

```bash
sh -c until printf "." && nc -z -w 2 zookeeper 2181; do sleep 2; done; echo 'zookeeper OK'
```

#### create deployment in namespace servicetest

Use this file (sorry I can't attach it as .yaml): [echotest.yaml.txt](https://github.com/ubuntu/microk8s/files/3068686/echotest.yaml.txt)

```bash
microk8s.kubectl apply -f echotest.yaml
``` 

it should create the following resources:
* namespace/servicetest 
* service/echoserver-s (this is a proper k8s service with a selector on the echoserver pods)
* service/echoserver-hs (this is a headless service)
* deployment.extensions/echoserver 
* deployment.extensions/nc-debugger 

=> the 'echoserver' simply listens on tcp port 8445 and send back whatever it receives

=> the 'nc-debugger" instance is ubuntu with the nc (netcat) tool installed (it sleeps forever)

#### get a bash console in the 'nc-debugger' instance 

```bash
microk8s.kubectl exec -n servicetest -it `microk8s.kubectl get pods -n servicetest -l app=nc-debugger --no-headers -o custom-columns=:metadata.name` -- bash
```

#### execute the following command in the above console:
```bash
echo "pong" | nc echoserver-hs 8445
```

The above works and will return the "pong" string back from the echoserver: echoserver-hs resolves to one of the pods of it's backend (in this case the single 'echoserver' pod)

#### try the same thing with the proper service:
```bash
echo "pong" | nc echoserver-s 8445
```

#### two things happen that are unexpected:
* no "pong" string is returned -> it seems as if the request does not reach the backend 'echoserver', despite the backend being registered in the 'echoservice-s' service
* nc still "connects" via TCP, otherwise it would complain (and return a non-zero exit code), it is however unclear *to what* exactly it can connect via TCP (it obviously is not the echoserver)

The above command(s) work as expected in a GKE cluster: meaning both return the "pong" string from the echo server

#### first scale your echoserver deployment to zero pods:
```bash 
microk8s.kubectl scale --replicas=0 deployment/echoserver -n servicetest
```

#### make sure the echoserver pod is gone and no resources are found with the command below:
```bash
microk8s.kubectl get pods -n servicetest -l app=echoserver
```
#### again using the 'nc-debugger' pod to use netcat try the following
```bash
nc -z -w 2 echoserver-s 8445 && echo "this shouldn't happen"
```

It will print out "this shouldn't happen" meaning the nc command exited successfully meaning it was able to create a TCP connection, *which shouldn't happen*

Again in GKE this example does not print the string, nc returns a non-zero exit code as it is not able to establish a TCP connection (as there is no backend available)

## microk8s.inspect 
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster

### tarball
[inspection-report-20190411_144237.tar.gz](https://github.com/ubuntu/microk8s/files/3068628/inspection-report-20190411_144237.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @matthiasamberg thank you for the great bug report.

The reason why you observe these differences in behavior is because we set the kube-proxy to function in `proxy-mode="userspace"` [1]. To get the expected behavior edit `/var/snap/microk8s/current/args/kube-proxy` and remove the `--proxy-mode` argument. This will switch kube proxy to iptables mode. Then restart microk8s:
```
sudo sed -i -n '/^--proxy-mode*/!p' /var/snap/microk8s/current/args/kube-proxy
microk8s.stop
microk8s.start
```

Using userspace proxy mode is a deviation from the default proxy mode (iptables). Userspace mode is the oldest mode and is also the fallback option in case iptables is failing. We decided to go with userspace for compatibility reasons as iptables mode was not working properly in some CI environments. I will take another look at this PR https://github.com/ubuntu/microk8s/pull/145 that moves us back to iptables.

[1] https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies

**Comment by matthiasamberg** [comment]
Hi @ktsakalozos ,

thank you very much for taking your time and your extensive reply. I agree that this could be responsible for *part* of my bugreport, however there is one thing I still do not understand:

When everything is set up as described in the initial bug report (so there is a service and a pod for the echoserver setup): if I then send a "string" to the echo server via its 'echoservice-s' service, it should respond, however it doesn't?

(This is the part in the bug report above described in the section:
#### two things happen that are unexpected:

* no "pong" string is returned -> it seems as if the request does not reach the backend 'echoserver', despite the backend being registered in the 'echoservice-s' service

)

**I think the above still is a problem within microk8s (and should even be handled properly with a userland proxy, no?)**

Otherwise thank you for your explanation, it helped us to formulate a workaround for our specific implementation depended situation: So we're happy no matter whether this second part is actually a bug or not

**Comment by ktsakalozos** [comment]
You are right @matthiasamberg this is a problem for MicroK8s so I opened an issue to Kubernetes upstream. I do not have high hopes for this to be fixed so our best option is to switch to the iptables proxy mode.

**Comment by matthiasamberg** [comment]
As this has been passed on to the kubernetes project by @ktsakalozos  [here](https://github.com/kubernetes/kubernetes/issues/76645). I'll close this issue.
