### ISSUE TITLE
Enabling dns (and probably anything else) cuts off network connection to the host machine

### ISSUE THREAD

**Issue by jan-hudec** [ubuntu/microk8s#429]
Installing microk8s goes OK, but when I do the next step of enabling (required for almost anything) dns, it cuts of the ssh connection into the machine, and the machine stops responding to ping.

Since the machine is headless, it is obviously almost impossible to find out what happened. The only chance is to reboot it and when it briefly starts responding between starting sshd and starting up whatever damages the routing in the kubernetes, quickly issue `microk8s.stop`.

The host is connected to (public; intranet) ethernet segment `10.1.0.0/21` (i.e. `10.1.0.0` to `10.1.7.255`) The attached inspection output (captured before everything started, because, as mentioned, it was not possible afterwards) suggests it might conflict with the internal network. Can that be changed?

[inspection-report-20190415_171604.tar.gz](https://github.com/ubuntu/microk8s/files/3080889/inspection-report-20190415_171604.tar.gz)

**Comment by jan-hudec** [comment]
I went into the `/var/snap/microk8s/current/` and replaced the IP address in the two files and it seems to work now. I am not sure it won't break on next update though.

**Comment by ktsakalozos** [comment]
Hi @jan-hudec 

MicroK8s uses `10.1.1.0/24` to place pods and this is what probably causes network conflicts in your setup. We should be more smart during our installation. We should be detect the existence of that network and randomly (?) select another one. The detection should go into the install hook https://github.com/ubuntu/microk8s/blob/master/snap/hooks/install

> replaced the IP address in the two files

Which files did you update? I can only spot the pod-cidr argument here: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kubelet#L8

**Comment by jan-hudec** [comment]
> We should be detect the existence of that network and randomly (?) select another one.

For start it would do to detect it and describe where to override it.

The selection could be done by simply iterating up and checking whether there is any conflicting route until there isn't. Just don't forget that the route might be for either bigger or smaller range—in my case it is 10.1.0.0/21, which includes the 10.1.1.0/24.

> Which files did you update?

I changed:

* In `/var/snap/microk8s/current/args/cni-network/cni.conf` the value for `"subnet"`
* In `/var/snap/microk8s/current/args/kubelet` the value for `--pod-cidr=`

There are other references to that range under `/snap/microk8s/current/build/kube_bins/v1.14.0/istio-1.0.5/`. Nothing of that gets copied under `/var/snap`, but I am not trying to use that add-on, so I don't know if it could be a problem if I did.

**Comment by jan-hudec** [comment]
> We should be detect the existence of that network and randomly (?) select another one.

For start it would do to detect it and describe where to override it.

The selection could be done by simply iterating up and checking whether there is any conflicting route until there isn't. Just don't forget that the route might be for either bigger or smaller range—in my case it is 10.1.0.0/21, which includes the 10.1.1.0/24.

> Which files did you update?

I changed:

* In `/var/snap/microk8s/current/args/cni-network/cni.conf` the value for `"subnet"`
* In `/var/snap/microk8s/current/args/kubelet` the value for `--pod-cidr=`

There are other references to that range under `/snap/microk8s/current/build/kube_bins/v1.14.0/istio-1.0.5/`. Nothing of that gets copied under `/var/snap`, but I am not trying to use that add-on, so I don't know if it could be a problem if I did.

**Comment by jan-hudec** [comment]
I didn't need it for a while, but now I have another project where microk8s would be very good candidate, except with out infrastructure sprawled all over the `10.0.0.0/8` I'd really need to configure the CNI subnet. I'm probably going to take another look at it.

**Comment by jan-hudec** [comment]
The `--pod-cidr` is apparently gone now, and the address only appears in the flannel config (`"Network": "10.1.0.0/16"` in `microk8s-resources/default-args/flannel-network-mgr-config`). But at runtime something also picks a subnet `10.1.3.1/24` and writes it to `run/flannel/subnet.env`, but I can't find what does it and how it selects `.3`. @ktsakalozos, do you have any hint?

The other network, `10.152.183.0/24`, appears in more places. It is not as immediate issue for me, because currently our infrastructure only goes to `10.52.n.m`, but it would make sense to make that configurable as well just in case. It would also allow it to be wider, because now that microk8s can join multiple nodes, it is actually viable to use it for internal infrastructure with more than ~250 services.

**Comment by jan-hudec** [comment]
With the latest build, `1443`, the changes I made are reverted, they are in more places, and the upgrade strangely started starting some pods in 10.1.98, but the rest is still running in 10.200 and the cluster is broken again.

Since flannel seems clever enough to pick subrange of 10.1.0.0/16 that does not conflict with the actual externally routed ranges, it does not render it completely useless, but it does render it unusable for production, because there will be new ranges appearing and we can't rely on those not colliding.
