### ISSUE TITLE
Check availability of port 8080 in snap install hook

### ISSUE THREAD

**Issue by tvansteenburgh** [ubuntu/microk8s#43]
If 8080 isn't available, increment and try again up to some reasonable limit. In other words, find an available port for the apiserver to use instead of just quietly failing if 8080 is already in use.

**Comment by odino** [comment]
Also, 8080 is quite of a commonly used port :) it'd be great if microk8s would have an env variable / config where users could specify on what port to bind.

**Comment by ktsakalozos** [comment]
Yes, that is true.

We cannot pass parameters during snap install. What we could do is to select an open port from a range during the installation (eg first available port in [8080, 8090]) and/or have a microk8s.init command where you would be asked this kind of questions (similar to what for example lxd is doing with lxd init).

**Comment by odino** [comment]
@ktsakalozos I also like the way kubectl manages things, where you can do a `config set / get` to update parameters -- so something like `microk8s.config set APISERVER_PORT 9876` would be nice :)

**Comment by ktsakalozos** [comment]
This is interesting. This configuration approach might extend to addons as well, for example we could do `microk8s.config set REGISTRY_SIZE 80G` to set the size of the registry in the respective addon.

**Comment by tvansteenburgh** [comment]
Here's a quick workaround for running the api-server on a different port:
```
API_PORT=8081
echo "--insecure-port=$API_PORT" | sudo tee -a /var/snap/microk8s/current/args/kube-apiserver 
sudo systemctl restart snap.microk8s.daemon-apiserver.service 
```
You can then run `microk8s.inspect` to confirm all services are running properly.

**Comment by johnraz** [comment]
The above procedure will also make `microk8s.status` to return the cluster as not running because it will use `kubectl` with the wrong kubeconfig too.

Otherwise it seems to work nicely.

**Comment by fhemberger** [comment]
Default secure port for the Kubernetes is `6443`. Assuming `6080` as insecure port for consistency, why not chose `60080` and `60443` for microk8s to avoid collision with an existing Kubernetes API endpoint?

Those ports aren't likely to be used otherwise.

**Comment by tristanlins** [comment]
This is unfortunately a blocker for me :-(
Tomcat uses port 8080 by default and I certainly will not reconfigure all my development tomcats or spring boot apps ...
The workaround of @tvansteenburgh is unfortunately only a crutch. So I'll stay with Minikube for the time being, in the hope that a reasonable solution will be found here soon ;-)

How about a microk8s.config tool that helps to reconfigure?
Something like `microk8s.config --api-insecure-port 60080`

**Comment by jmt-vanderlee** [comment]
You'll also need to update the `/snap/microk8s/current/client.config` file. Otherwise things like `microk8s.enable dashboard` will try to use the old port.

**Comment by willaaam** [comment]
This really needs fixing, choosing 8080 as the default port just doesn't make sense. I think it'd be great if you change it to _something_ else before the team starts working on a well thought-out configuration option.

**Comment by jglick** [comment]
[Workaround for Quarkus](https://stackoverflow.com/a/57464506/12916)

**Comment by jglick** [comment]
This may have been resolved recently—I did a fresh installation and the API server is now listening on `https://192.168.x.y:16443`. #323?
