### ISSUE TITLE
Containers fail to start on 1.13.5

### ISSUE THREAD

**Issue by ephill** [ubuntu/microk8s#430]
My team is using the stable 1.13 channel for microk8s and it looks like 1.13.5 was rolled out recently. Updating to this version has caused all of my team members so far to start getting errors during container startup. On 1.13.4 we had no issue. Here's an example of the events from using `kubectl describe` on the pod that `microk8s enable ingress` spins up:

```
Events:
  Type     Reason                  Age                    From                      Message
  ----     ------                  ----                   ----                      -------
  Normal   Scheduled               18m                    default-scheduler         Successfully assigned default/nginx-ingress-microk8s-controller-fq7wk to evan-hyperproof
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/494a2a36d957d9b177527a036620f1b09ba9286ddbe73326fb10a2da43ff9b71/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/a0be2d6df8a546554323910fdc35f558d8df96b011913e32d0cde5c04fa568be/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/084b52c9a69628b8e8dbff6487bed0764e0a548ad65380e71ae38989a21c0ea0/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Normal   SandboxChanged          18m (x3 over 18m)      kubelet, evan-hyperproof  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/869f8aab6b2d5f98f5c9f68783669de92466838431abc977a96265ec4713fcf3/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/fb3641f99aa71dd73944e3298796479c59fa44cb72a562d2e360b360f99de37e/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/d2dc6ef9c319c583aa8174543afc67f057c0f21bf9723319755c3cf97e83b1f7/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/27c3749b9c4f69753d862a84f72f1a8f01fe4a6a21d26fca91a8068b32148912/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/3b1e5e56c47377540a8c01bd4dcd92a9cdb129b8b219f9d02af5cdf46d64c768/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/2e0da860428945b262b6d1d2d928de510bcac7c729fd98e3365604bd15b9d54e/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/10f5d075689ed8e029adfe6129270eaea2e08edec396f25876c281ec83e71a0b/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/1ae720e984226c1576771d5dd66d93011d2bc99c78733ba317254bbef4e3868c/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/d4e66bc1eeb1e111d814a28d7177f3d65c8a42fcddf39b59de15f2f83200103e/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m                    kubelet, evan-hyperproof  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/fc8abc063632566448e522035f558098ea83d035d789fc5361bef6600a37265d/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Warning  FailedCreatePodSandBox  18m (x3 over 18m)      kubelet, evan-hyperproof  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "nginx-ingress-microk8s-controller-fq7wk": Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/d8d3395729afc1042c4383ac429db00ba028656979c1a3022c7a9f2a90ba54f4/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
  Normal   SandboxChanged          3m38s (x659 over 18m)  kubelet, evan-hyperproof  Pod sandbox changed, it will be killed and re-created.
```

This error can be seen after doing a `microk8s.reset` and `microk8s enable ingress dns dashboard storage`. All containers throw the same errors.

I've tried poking around myself but have not been able to resolve the issue. A few of the tweaks I've done started throwing different errors about Go serialization which makes me wonder if there's a versioning issue somewhere. Docker is installed on my machine but we build images using `microk8s.docker` and it has not been an issue thus far.

Here's an inspection report that I just generated:
[inspection-report-20190415_150021.tar.gz](https://github.com/ubuntu/microk8s/files/3082237/inspection-report-20190415_150021.tar.gz)

**Comment by ephill** [comment]
Confirmed that simply reverting to 1.13.4 gets things working again. Unfortunately some team members uninstalled microk8s as part of debugging this issue which leaves them with no way ('least that I know of) of getting back to 1.13.4.

**Comment by ktsakalozos** [comment]
Hi @ephill,

I can partially reproduce the issue you are seeing. If I deploy the 1.13/stable channel, copy over the configuration files you have under `/var/snap/microk8s/current/args/` to the new deployment and restart MicroK8s then dockerd is failing. Some of these arguments have been updated 11 months ago, so I assume you refreshed to 1.13 channel at some point and kept using the same deployment. 

In any case, my suggestion is to point me to a way to reproduce the issue on a new deployment. Could any of your team members that have removed and reinstalled MicroK8s attach the tarball produced by `microk8s.inspect`? Also, I am interested to know all the addons you are enabling, how you install docker, any configuration you are doing after installing MicroK8s and any workload (if any) you are using to expose the issue.

Thank you.

**Comment by neoel** [comment]
How can I run v1.13.4? 
All the channels show the same version for 1.13:
```bash
  1.13/stable:    v1.13.5  2019-04-15 (493) 237MB classic
  1.13/candidate: v1.13.5  2019-04-05 (493) 237MB classic
  1.13/beta:      v1.13.5  2019-04-05 (493) 237MB classic
  1.13/edge:      v1.13.5  2019-04-01 (493) 237MB classic
```

**Comment by ktsakalozos** [comment]
@neoel you cannot move to 1.13.4. It is not available anymore.

**Comment by ephill** [comment]
@ktsakalozos one of my team members:

1. removed `docker-ce` from their machine (was installed/uninstalled via apt-get.
2. uninstalled microk8s
3. Deleted all microk8s folders that we could find in various snap directories
4 reinstalled microk8s from the 1.13/stable channel
5. Ran `microk8s.start` and `microk8s.enable ingress`

The pods that enabling the ingress creates failed to start in the same way that I described above. I have attached his `microk8s.inspect` tarball:

[inspection-report-20190416_092904.tar.gz](https://github.com/ubuntu/microk8s/files/3085941/inspection-report-20190416_092904.tar.gz)

You mentioned that the files under `/var/snap/microk8s/current/args` are out of date which is interesting to me. We did roll back as a team from the 1.14 version to 1.13 maybe a month or so ago because we had some issues configuring filebeat properly using containerd. Anyway that doesn't quite explain why our files would be 11 months out of date. I'll look into this a bit more today.

In terms of addons we usually enable dns, dashboard, ingress, and storage but as you can see above we can repro the issue by just enabling ingress. I actually don't think that it's related to ingress at all - that's just a convenient way to get a pod spun up that has nothing to do with our code.

We do have a couple configuration steps for changing default-ulimits in docker, increasing vm.max_map_count and allowing privileged init containers but we can repro the microk8s issues without any of these changes. Quite stumped.

Let me know if you need any more information.

**Comment by ktsakalozos** [comment]
I think I understand what happens. Try this after `apt-get remove docker-ce`:
```
apt-get remove containerd.io
```

Here is what happens. Dockerd internally uses containerd. Dockerd will spawn a containerd if no containerd is already running. When you installed docker-ce you also got containerd service running. It is the containerd process under `/usr/bin/`, check it out (`ps -ef | grep containerd`)! When you `apt-get remove docker-ce` containerd daemon is left behind, and it is still running! When the microk8s dockerd start it sees a containerd available so it tries to connect to that one and this is how you get all these errors. I will try to get the microk8s docker use the local containerd. Should have news soon. For now, make sure you remove containerd.

**Comment by ephill** [comment]
@ktsakalozos Thanks for the quick turnaround. I have a lot of good news and some bad news. The good news is that when I wiped docker-ce, docker-ce-cli, and containerd.io from my machine most of my pods (including the ones that our software stands up) are running! The bad news is that the two redis pods (one master and one slave) we have (which are deployed using the standard redis helm charts) do not start. Here is the error the master pod is logging:

```
  Normal   Scheduled         7m20s                  default-scheduler         Successfully assigned default/redis-master-0 to evan-hyperproof
  Warning  FailedScheduling  7m20s (x7 over 7m20s)  default-scheduler         pod has unbound immediate PersistentVolumeClaims
  Normal   Pulled            7m15s                  kubelet, evan-hyperproof  Container image "docker.io/bitnami/minideb:latest" already present on machine
  Normal   Created           7m15s                  kubelet, evan-hyperproof  Created container
  Normal   Started           7m15s                  kubelet, evan-hyperproof  Started container
  Warning  Unhealthy         7m7s                   kubelet, evan-hyperproof  Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process235366309: no such file or directory: unknown
  Warning  Unhealthy         7m5s                   kubelet, evan-hyperproof  Readiness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process296087744: no such file or directory: unknown
  Warning  Unhealthy         7m2s                   kubelet, evan-hyperproof  Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process803270431: no such file or directory: unknown
  Warning  Unhealthy         7m                     kubelet, evan-hyperproof  Readiness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process754114034: no such file or directory: unknown
  Warning  Unhealthy         6m57s                  kubelet, evan-hyperproof  Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process498387625: no such file or directory: unknown
  Warning  Unhealthy         6m55s                  kubelet, evan-hyperproof  Readiness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process655752180: no such file or directory: unknown
  Warning  Unhealthy         6m52s                  kubelet, evan-hyperproof  Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process721182403: no such file or directory: unknown
  Warning  Unhealthy         6m50s                  kubelet, evan-hyperproof  Readiness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process182429510: no such file or directory: unknown
  Normal   Pulling           6m47s (x2 over 7m14s)  kubelet, evan-hyperproof  pulling image "docker.io/bitnami/redis:4.0.12"
  Normal   Killing           6m47s                  kubelet, evan-hyperproof  Killing container with id docker://redis:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy         6m47s                  kubelet, evan-hyperproof  Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process385276397: no such file or directory: unknown
  Normal   Created           6m45s (x2 over 7m12s)  kubelet, evan-hyperproof  Created container
  Normal   Pulled            6m45s (x2 over 7m13s)  kubelet, evan-hyperproof  Successfully pulled image "docker.io/bitnami/redis:4.0.12"
  Normal   Started           6m45s (x2 over 7m12s)  kubelet, evan-hyperproof  Started container
  Warning  Unhealthy         6m32s (x4 over 6m40s)  kubelet, evan-hyperproof  (combined from similar events): Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process679781395: no such file or directory: unknown
  Warning  BackOff           2m4s (x11 over 4m47s)  kubelet, evan-hyperproof  Back-off restarting failed container
```
The slave pod has something similar. Again this is something that worked when I had reverted to 1.13.4 but not on 1.13.5.

And here's the latest inspection report (from my machine this time but I confirmed with a coworker that their clean install of 1.13.5 has the same issue): [inspection-report-20190416_145745.tar.gz](https://github.com/ubuntu/microk8s/files/3087079/inspection-report-20190416_145745.tar.gz)

I assume this would repro if you used helm to install redis on a freshly reset microk8s cluster but I haven't tested that quite yet. Will give it a shot and see but would appreciate any suggestions you have in the meantime. We're so close!

**Comment by ephill** [comment]
Yes, I was able to repro this issue with Redis by after a `microk8s.reset` by running `helm init` and `helm install stable/redis`. At this point I am assuming that it has something to do with the specific redis chart which I'll continue to dig into. But, if you can think of any changes that might cause this chart to work in 1.13.4 and not 1.13.5 that'd be helpful.

**Comment by ktsakalozos** [comment]
Hi @ephill, this PR https://github.com/ubuntu/microk8s/pull/433 should allow you to have containerd/dockerd next to MicroK8s. I am still looking at the crashlooping issue. In the meantime, since this is a confirmed bug I reverted the stable branch to the last good revision 438.

May I ping you as soon as I have a fix on the 1.13/edge channel to give it a try? Thank you.

**Comment by ephill** [comment]
@ktsakalozos Great, thanks again for your help. I am happy to give the edge channel a try whenever it's ready.

**Comment by ktsakalozos** [comment]
@ephill the 1.13/edge has both problems reported fixed. You should be able to co-locate MicroK8s with your dockerd/containerd and executing in the containers should work. Would you be able to give it a try?
```
sudo snap install microk8s --classic --channel=1.13/edge
```

Thanks

**Comment by ephill** [comment]
@ktsakalozos I just updated to the edge channel and all my pods have started successfully! I'll monitor for issues through the day but I don't expect to find anything. Thanks for the fix.

**Comment by ktsakalozos** [comment]
The fixes are released on stable, thank you @ephill
