### ISSUE TITLE
istio failed on 1.13

### ISSUE THREAD

**Issue by shenkejie15** [ubuntu/microk8s#431]
I have been working with Knative on microk8s normally for at least a week. But today I get istio-galley and istio-sidecar-injector CrashLoopBackOff while I am pretty sure that I have done nothing unusual. microk8s.reset doesn't solve the problem, and now I can not use microk8s.enable to enable istio or ingress. 

To avoid your confusion, I have modified dockerd-env to use VPN and docker-daemon.json to solve the [#issues253](https://github.com/ubuntu/microk8s/issues/253). 

relative message: 
[inspection-report-20190416_163044.tar.gz](https://github.com/ubuntu/microk8s/files/3083878/inspection-report-20190416_163044.tar.gz)
[describe_galley.txt](https://github.com/ubuntu/microk8s/files/3083885/describe_galley.txt)
[describe_sidecar.txt](https://github.com/ubuntu/microk8s/files/3083887/describe_sidecar.txt)

microk8s version 1.13 stable
OS version Ubuntu 18.04 LTS

**Comment by shenkejie15** [comment]
I am working on [https://github.com/istio/istio/issues/7586](https://github.com/istio/istio/issues/7586) but I am not sure whether I can solve this problem.

**Comment by ktsakalozos** [comment]
I am seeing some apparmor denials as this one:
```
apparmor="DENIED" operation="signal" profile="docker-default" pid=11782 comm="docker-runc" requested_mask="receive" denied_mask="receive" signal=term peer="snap.microk8s.daemon-docker"
```

While I am investigating I can offer a workaround. `microk8s.stop` and `microk8s.start` will reload the right apparmor profile.

**Comment by shenkejie15** [comment]
I still get CrashLoopBackOff after restarting microk8s. By the way, I tried 
```
microk8s.reset
snap remove microk8s
snap install microk8s --channel 1.13
microk8s.start
microk8s.enable dns istio
```
these two pods were also CrashLoopBackOff

**Comment by ktsakalozos** [comment]
@shenkejie15 this PR https://github.com/ubuntu/microk8s/pull/433 addresses the denials from apparmor. I am still looking at the crashlooping issue. In the meantime, since this is a confirmed bug I reverted the stable branch to the last good revision 438.

May I ping you as soon as I have a fix on the 1.13/edge channel to give it a try? Thank you.

**Comment by shenkejie15** [comment]
@ktsakalozos Of course I will. Thanks for your reply.

**Comment by ktsakalozos** [comment]
@shenkejie15 the 1.13/edge has this problem fixed, would you be able to give it a try?
```
sudo snap install microk8s --classic --channel=1.13/edge
```

Thanks

**Comment by shenkejie15** [comment]
@ktsakalozos Thanks for your fix, I can run istio now.

**Comment by ktsakalozos** [comment]
The fix is on stable. Thank you for reporting this @shenkejie15
