### ISSUE TITLE
Kubelet failing to start on 1.14.x

### ISSUE THREAD

**Issue by neoel** [ubuntu/microk8s#432]
I'm not a fan of the automatic updates, is there any way to stop this? It caused my cluster to break on several occasions. 

So microk8s switched to containerd from docker, but my kubelet daemon fails to start due to trying to connect to docker:

```
failed to retrieve docker version: Cannot connect to the Docker daemon at unix:///var/snap/microk8s/492/docker.sock. Is the docker daemon running?
```

This behaviour is seen on v1.14.0 and v1.14.1

microk8s.inspect
```
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
 FAIL:  Service snap.microk8s.daemon-kubelet is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-kubelet
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster
```

**Comment by ktsakalozos** [comment]
Hi @neoel, automatic updates can be frustrating at times. Here is what you can do to handle them elegantly:

- Use the `--channel` flag when snap installing MicroK8s. This way you will only receive patch releases on the series you will be following.
- When switching channels you do a full `snap remove microk8s` and then reinstall. This ensures you are not applying outdated configurations to new Kubernetes releases. This is the issue you are reporting here.
- Time the snap updates in a convenient to you time period. You can do so as described here:  https://docs.snapcraft.io/keeping-snaps-up-to-date/7022

**Comment by neoel** [comment]
I did lock my release to v1.13, but v1.13.5 broke it, it tries to connect to runc I believe:

```
  Warning  Unhealthy         15m                  kubelet, dxhost    Liveness probe failed: OCI runtime exec failed: open /run/user/0/snap.microk8s/runc-process656130442: no such file or directory: unknown
```

I'll try removing k8s now, but i'm a bit wary of losing information.

**Comment by neoel** [comment]
@ktsakalozos Can I stop the updating of snaps? I'm reverting a backup now, since I've destroyed my cluster.

**Comment by ktsakalozos** [comment]
There is no way to completely disable snap updates. You can only push them in the future via https://docs.snapcraft.io/keeping-snaps-up-to-date/7022

**Comment by neoel** [comment]
@ktsakalozos How can I upgrade k8s to 1.14 without removing the cluster itself?

**Comment by ktsakalozos** [comment]
@neoel if you refresh to 1.14/stable channel and Kubernetes services do not start you have to reconfigure the failing ones. In your case the service failing is `snap.microk8s.daemon-kubelet`. The arguments for the kubelet service are found in `/var/snap/microk8s/current/args/kubelet`. You have to compare those arguments with the ones shipped by default: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kubelet . If i were to guess your kubelet still tries to talk to dockerd and you should update the respective `--container-runtime-*` parameters to the default values.
