### ISSUE TITLE
On Ubuntu18.04.02, some services in not running 

### ISSUE THREAD

**Issue by kongxubihai** [ubuntu/microk8s#436]
1.inspect
root@zfd-All-Series:~# microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-docker is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
 FAIL:  Service snap.microk8s.daemon-proxy is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-proxy
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster
[inspection-report-20190419_170001.tar.gz](https://github.com/ubuntu/microk8s/files/3097606/inspection-report-20190419_170001.tar.gz)

2.logs
root@zfd-All-Series:~# snap  logs microk8s.daemon-apiserver
2019-04-19T08:36:27Z microk8s.daemon-apiserver[11183]: /snap/microk8s/438/run-with-config-args: 行 49: /snap/microk8s/438/usr/bin/gawk: 没有那个文件或目录
2019-04-19T08:36:27Z microk8s.daemon-apiserver[11183]: /snap/microk8s/438/run-with-config-args: 行 49: /snap/microk8s/438/bin/sed: 没有那个文件或目录
2019-04-19T08:36:27Z systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=exited, status=127/n/a
2019-04-19T08:36:27Z systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'exit-code'.
2019-04-19T08:36:27Z systemd[1]: snap.microk8s.daemon-apiserver.service: Service hold-off time over, scheduling restart.
2019-04-19T08:36:27Z systemd[1]: snap.microk8s.daemon-apiserver.service: Scheduled restart job, restart counter is at 5.
2019-04-19T08:36:27Z systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver.
2019-04-19T08:36:27Z systemd[1]: snap.microk8s.daemon-apiserver.service: Start request repeated too quickly.
2019-04-19T08:36:27Z systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'exit-code'.
2019-04-19T08:36:27Z systemd[1]: Failed to start Service for snap application microk8s.daemon-apiserver.

**Comment by ktsakalozos** [comment]
Could you try the edge channel?

```
sudo snap install microk8s --classic --channel=1.13/edge
```

Thanks

**Comment by kongxubihai** [comment]
> Could you try the edge channel?
> 
> ```
> sudo snap install microk8s --classic --channel=1.13/edge
> ```
> Thanks

I had tried it but it does work!

There are three services not running.show as:
`root@zfd-All-Series:~# microk8s.inspect
Inspecting services
 FAIL:  Service snap.microk8s.daemon-containerd is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-containerd
 FAIL:  Service snap.microk8s.daemon-docker is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-docker
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
 FAIL:  Service snap.microk8s.daemon-proxy is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-proxy
  Service snap.microk8s.daemon-kubelet is running`

I try to log microk8s.daemon-apiserver with same questions.
`root@zfd-All-Series:~# snap logs  microk8s.daemon-apiserver
2019-04-21T23:56:06Z microk8s.daemon-apiserver[12716]: /snap/microk8s/526/run-with-config-args: 行 49: /snap/microk8s/526/usr/bin/gawk: 没有那个文件或目录
2019-04-21T23:56:06Z microk8s.daemon-apiserver[12716]: /snap/microk8s/526/run-with-config-args: 行 49: /snap/microk8s/526/bin/sed: 没有那个文件或目录
2019-04-21T23:56:06Z systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=exited, status=127/n/a
`

**Comment by kongxubihai** [comment]
> Could you try the edge channel?
> 
> ```
> sudo snap install microk8s --classic --channel=1.13/edge
> ```
> Thanks

I also try the 1.14/edge channel. Sadly I can't  installed it successfully!
`root@zfd-All-Series:~# snap install microk8s --classic --channel=1.14/edge

error: cannot perform the following tasks:
- Run install hook of "microk8s" snap if present (run hook "install":
-----
+ export LD_LIBRARY_PATH=/snap/microk8s/541/lib:/snap/microk8s/541/usr/lib:/snap/microk8s/541/lib/x86_64-linux-gnu:/snap/microk8s/541/usr/lib/x86_64-linux-gnu
+ LD_LIBRARY_PATH=/snap/microk8s/541/lib:/snap/microk8s/541/usr/lib:/snap/microk8s/541/lib/x86_64-linux-gnu:/snap/microk8s/541/usr/lib/x86_64-linux-gnu
+ export PATH=/snap/microk8s/541/usr/sbin:/snap/microk8s/541/usr/bin:/snap/microk8s/541/sbin:/snap/microk8s/541/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/usr/local/bin
+ PATH=/snap/microk8s/541/usr/sbin:/snap/microk8s/541/usr/bin:/snap/microk8s/541/sbin:/snap/microk8s/541/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/usr/local/bin
+ source /snap/microk8s/541/actions/common/utils.sh
+ cp -r /snap/microk8s/541/default-args /var/snap/microk8s/541/args
/snap/microk8s/541/meta/hooks/install: 行 10: /snap/microk8s/541/bin/cp: 没有那个文件或目录
-----)
`

**Comment by kongxubihai** [comment]
Thx,ktsakalozos ! I've worked it out by this way.

1.find  the  loader 
`root@zfd-All-Series:~# readelf -l /snap/microk8s/438/usr/bin/gawk |grep interpreter

      [Requesting program interpreter: /snap/core/current/lib64/ld-linux-x86-64.so.2]`

2.make a  soft link  core  to core18
`cd /snap  &&  ln  -s  core18  core`

3.reinstall microk8s
`sudo snap install microk8s --classic --channel=1.13/stable`

summary: I upgraded my OS  from  Ubuntu16.04 to Ubuntu18.04. Maybe this is the reason why there is no /snap/core  but /snap/core18 instead.

**Comment by ktsakalozos** [comment]
@kongxubihai using core18 in the place of core may cause problems in the future.

I believe you can `sudo snap install core` and get the right core package.

Also if you lost the core snap during 18.04 upgrade you would better report it here:  https://forum.snapcraft.io/

Thank you for spending the time to debug this.
