### ISSUE TITLE
Microk8s.reset Breaking Docker Build Command

### ISSUE THREAD

**Issue by pixelshaded** [ubuntu/microk8s#464]
Using 
- 18.10 of Ubuntu
- 18.06.1-ce Docker snap
- 1.11/edge Microk8s snap

If I build an image with docker, then run microk8s.reset, then run the build command again, I get 
```
OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/6240667963cc03f41ebb95973b882af4e99151c15f39ac0bd5ca9bbba1279495/log.json: no such file or directory): exec: "docker-runc": executable file not found in $PATH: unknown
```
If I reinstall the docker snap, I can run the build command again with no errors. I've echo'd $PATH before and after microk8s.reset and it is unchanged, so I am not sure yet why this is happening.

**Comment by ktsakalozos** [comment]
Hi @pixelshaded, I suspect some AppArmor denials. Can you check the output of `dmesg`?

**Comment by ktsakalozos** [comment]
I cannot reproduce this @pixelshaded. Can you share the Dockerfile you are using and/or any other info I may be missing?

**Comment by pixelshaded** [comment]
Thanks for trying to help. Not sure if this is related, but as I got further trying to use microk8s, I found some issues mentioning that it doesn't play nice with a local install of docker, so I've opted instead to alias the docker that comes with microk8s. I haven't experienced this issue since.
