### ISSUE TITLE
Cluster gets stuck in SchedulingDisabled state until reboot

### ISSUE THREAD

**Issue by tdickman** [ubuntu/microk8s#468]
My local node sometimes enters the `SchedulingDisabled` state - restarting my node usually fixes the issue, but it's unclear why this is occurring.

```
$ kubectl get node
NAME          STATUS                     ROLES    AGE     VERSION
tom-x1-work   Ready,SchedulingDisabled   <none>   5d22h   v1.14.1
```

The event logs from `kubectl describe node` don't reveal anything interesting:

```
  Normal   Starting                 43m                kube-proxy, tom-x1-work  Starting kube-proxy.
  Normal   Starting                 43m                kubelet, tom-x1-work     Starting kubelet.
  Warning  InvalidDiskCapacity      43m                kubelet, tom-x1-work     invalid capacity 0 on image filesystem
  Normal   NodeAllocatableEnforced  43m                kubelet, tom-x1-work     Updated Node Allocatable limit across pods
  Normal   NodeHasNoDiskPressure    43m                kubelet, tom-x1-work     Node tom-x1-work status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     43m                kubelet, tom-x1-work     Node tom-x1-work status is now: NodeHasSufficientPID
  Normal   NodeNotReady             43m                kubelet, tom-x1-work     Node tom-x1-work status is now: NodeNotReady
  Normal   NodeNotSchedulable       43m                kubelet, tom-x1-work     Node tom-x1-work status is now: NodeNotSchedulable
  Normal   NodeHasSufficientMemory  43m                kubelet, tom-x1-work     Node tom-x1-work status is now: NodeHasSufficientMemory
  Normal   NodeReady                43m                kubelet, tom-x1-work     Node tom-x1-work status is now: NodeReady
```

[inspection-report-20190513_094707.tar.gz](https://github.com/ubuntu/microk8s/files/3173179/inspection-report-20190513_094707.tar.gz)

**Comment by tdickman** [comment]
This same issue occurred today - this time I had stopped the cluster the night before, suspended my computer, and then started the cluster again this morning. I went to start an application on my computer 30 minutes later, and saw that the cluster was in `SchedulingDisabled` state.

I restarted my cluster, and it is still in the `SchedulingDisabled` state.

**Comment by ktsakalozos** [comment]
@tdickman with the merged PR the stop command will not drain the node. This means the node will never go into SchedulingDisabled and we will not see this race condition again (I hope).

A new snap should hit edge in a few hours. Let me know if you see this problem again.

**Comment by tdickman** [comment]
> A new snap should hit edge in a few hours. Let me know if you see this problem again.

@ktsakalozos Forgot to leave a comment on this a few weeks ago, so I wanted to swing by and update. I've been running this version (edge) for the last few weeks, and haven't encountered this error again. Thank you!

**Comment by smiklos** [comment]
I'm still getting this issue. Not always, but just when I needed it the most :) 
Running on v1.17.2
