### ISSUE TITLE
Is there a proper way to enable front proxy tls for extension api server

### ISSUE THREAD

**Issue by pastukhov** [ubuntu/microk8s#475]
Hi all!
I'm trying to play with kubevirt on top of microk8s and need to enable 
```
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key>
``` 
flags for kube api server. 
Have anyone advice how to generate cert and key to do it?
Related issue https://github.com/kubevirt/kubevirt/issues/1126

**Comment by ktsakalozos** [comment]
Hi @pastukhov, I am not familiar with your setup but I can offer some pointers on the certificates used in MicroK8s. As you can see in https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kube-apiserver the certificates are found in `/var/snap/microk8s/current/certs/`. We produce the server cert here: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L145 and we have a single ca `https://github.com/ubuntu/microk8s/blob/master/snap/hooks/install#L16`.

If you provide me with more info on what is failing and how I can reproduce your setup I may be able to offer more assistance. I have never used kubevirt but it sounds really interesting. It would be great to see how it can be used with MicroK8s. I can see how such integration would be part of our docs. Do you have any suggestions on how we can make your experience easier? Looking forward to hearing your thoughts.

**Comment by pastukhov** [comment]
Hi @ktsakalozos ! Here is my microk8s.inspect result
[inspection-report-20190520_133013.tar.gz](https://github.com/ubuntu/microk8s/files/3197419/inspection-report-20190520_133013.tar.gz)

I have mkcrok8s cluster installed with allow-privileged option https://gist.github.com/antonfisher/d4cb83ff204b196058d79f513fd135a6

I'm trying to run kubevirt on it. 
With:
```
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.17.0/kubevirt-operator.yaml
…
deployment.apps/virt-operator created

$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.17.0/kubevirt-cr.yaml
kubevirt.kubevirt.io/kubevirt created
``` 
from here:
https://github.com/kubevirt/demo
  Everything is fie, i can run an kubevirt with kubectl patch, but virtctl utill allways returning 401.
Relatet issue: https://github.com/kubevirt/kubevirt/issues/1126

**Comment by ktsakalozos** [comment]
Based on the comment https://github.com/kubevirt/kubevirt/issues/1126#issuecomment-396360167 we can append the following into `/var/snap/microk8s/current/args/kube-apiserver `:
```
--proxy-client-cert-file=${SNAP_DATA}/certs/server.crt
--proxy-client-key-file=${SNAP_DATA}/certs/server.key
```

Then do a MicroK8s restart:
```
microk8s.stop
microk8s.start
```
Wait for the pods to restart. Have a look at `microk8s.kubectl get all --all-namespaces`.

You will then be able to do a:
```
sudo ./virtctl  --kubeconfig /var/snap/microk8s/current/credentials/client.config start testvm
VM testvm was scheduled to start
```
Or put the kubeconfig in the default location:
```
> microk8s.kubectl config view --raw > ~/.kube/config
> ./virtctl start testvm
Error starting VirtualMachine the server rejected our request for an unknown reason
> ./virtctl stop testvm
VM testvm was scheduled to stop
```

**Comment by pastukhov** [comment]
Thanks @ktsakalozos !
It's working finaly.

**Comment by attila123** [comment]
Thanks @ktsakalozos
Actually I was only looking for how to use virtctl with microk8s, so I only did the 2nd half of your comment (e.g. using --kubeconfig with virtctl and saving the kubeconfig from microk8s, these worked fine with current microk8s, kubevirt, virtctl versions).
