### ISSUE TITLE
FailedScheduling 1 node had taints that the pod didn't tolerate

### ISSUE THREAD

**Issue by Peter7Hess** [ubuntu/microk8s#483]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
[inspection-report-20190526_231753.tar.gz](https://github.com/ubuntu/microk8s/files/3221710/inspection-report-20190526_231753.tar.gz)

raptors pod stays in pending state:
peter@socrates:~$ k describe po raptors
Name:               raptors-bfcj6
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             run=raptors
Annotations:        <none>
Status:             Pending
IP:
Controlled By:      ReplicationController/raptors
Containers:
  raptors:
    Image:        redmaple7/kubia
    Port:         8080/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-82pms (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  default-token-82pms:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-82pms
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  21s (x8 over 9m7s)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.

peter@socrates:~$ microk8s.status
microk8s is running
addons:
jaeger: disabled
prometheus: disabled
dns: disabled
fluentd: disabled
storage: disabled
gpu: disabled
registry: disabled
dashboard: disabled
ingress: disabled
metrics-server: disabled
istio: disabled
peter@socrates:~$ sudo systemctl status microk8s
[sudo] password for peter:
Unit microk8s.service could not be found.
peter@socrates:~$ netstat -an | grep "LISTEN "
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN
tcp        0      0 192.168.122.1:53        0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN
tcp        0      0 10.0.2.15:10010         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:1338          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN
tcp6       0      0 :::10255                :::*                    LISTEN
tcp6       0      0 :::10257                :::*                    LISTEN
tcp6       0      0 :::10259                :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 ::1:631                 :::*                    LISTEN
tcp6       0      0 :::16443                :::*                    LISTEN
tcp6       0      0 :::43553                :::*                    LISTEN
tcp6       0      0 :::30565                :::*                    LISTEN
tcp6       0      0 :::38503                :::*                    LISTEN
tcp6       0      0 :::10250                :::*                    LISTEN
peter@socrates:~$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster

 WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT
Building the report tarball
  Report tarball is at /var/snap/microk8s/522/inspection-report-20190526_231753.tar.gz
peter@socrates:~$ sudo iptables -P FORWARD ACCEPT
peter@socrates:~$ k get po --all-namespaces
NAMESPACE   NAME            READY   STATUS    RESTARTS   AGE
default     raptors-bfcj6   0/1     Pending   0          17m

**Comment by ktsakalozos** [comment]
Hi @Peter7Hess, I see your node is under disk pressure (running out of disk). You can check this by doing a `microk8s.kubectl describe no`. Read more on how to change the limits here:  https://github.com/ubuntu/microk8s/issues/463#issuecomment-491025765

**Comment by Peter7Hess** [comment]
Thank you ktsakalozos!  Indeed an insufficient disk space issue, thanks for tips on debugging.  I have since extended the volume.  Soon after that the pod went into a running state.

**Comment by maheshreddy32825** [comment]
@ktsakalozos Can you help with this issue. I am totally new to K8s

root@kmaster:~# kubectl describe pod kubernetes-dashboard-7c54d59f66-s7ckx -n kube-system
Name:           kubernetes-dashboard-7c54d59f66-s7ckx
Namespace:      kube-system
Priority:       0
Node:           <none>
Labels:         k8s-app=kubernetes-dashboard
                pod-template-hash=7c54d59f66
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/kubernetes-dashboard-7c54d59f66
Containers:
  kubernetes-dashboard:
    Image:      k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1
    Port:       8443/TCP
    Host Port:  0/TCP
    Args:
      --auto-generate-certificates
    Liveness:     http-get https://:8443/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /certs from kubernetes-dashboard-certs (rw)
      /tmp from tmp-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubernetes-dashboard-token-q7fxb (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kubernetes-dashboard-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-certs
    Optional:    false
  tmp-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kubernetes-dashboard-token-q7fxb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubernetes-dashboard-token-q7fxb
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  99s (x402 over 41m)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.

**Comment by ktsakalozos** [comment]
@maheshreddy32825 please attach the tarball produced by `microk8s.inspect`. Thanks.

**Comment by zhaishujie2** [comment]
Name:               localhost.localdomain
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=localhost.localdomain
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 192.168.1.67/24
                    projectcalico.org/IPv4IPIPTunnelAddr: 100.103.244.64
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 09 Dec 2019 18:30:08 +0800
Taints:             node-role.kubernetes.io/master:NoSchedule
Unschedulable:      false
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Mes
sage  ----                 ------  -----------------                 ------------------                ------                       ---
----  NetworkUnavailable   False   Mon, 09 Dec 2019 18:30:33 +0800   Mon, 09 Dec 2019 18:30:33 +0800   CalicoIsUp                   Cal
ico is running on this node  MemoryPressure       False   Wed, 11 Dec 2019 14:50:46 +0800   Mon, 09 Dec 2019 18:30:03 +0800   KubeletHasSufficientMemory   kub
elet has sufficient memory available  DiskPressure         False   Wed, 11 Dec 2019 14:50:46 +0800   Mon, 09 Dec 2019 18:30:03 +0800   KubeletHasNoDiskPressure     kub
elet has no disk pressure  PIDPressure          False   Wed, 11 Dec 2019 14:50:46 +0800   Mon, 09 Dec 2019 18:30:03 +0800   KubeletHasSufficientPID      kub
elet has sufficient PID available  Ready                True    Wed, 11 Dec 2019 14:50:46 +0800   Mon, 09 Dec 2019 18:30:38 +0800   KubeletReady                 kub
elet is posting ready statusAddresses:
  InternalIP:  192.168.1.67
  Hostname:    localhost.localdomain
Capacity:
 cpu:                4
 ephemeral-storage:  51175Mi
 hugepages-2Mi:      0
 memory:             3716164Ki
 pods:               110
Allocatable:
 cpu:                4
 ephemeral-storage:  48294789041
 hugepages-2Mi:      0
 memory:             3613764Ki
 pods:               110
System Info:
 Machine ID:                 8e75674965fd434c92b357f9d8e2217d
 System UUID:                421D27A3-83ED-DBF2-2E13-8FA9DEA7D1E0
 Boot ID:                    22102082-f3ce-4f55-9dfd-c8949ad06a70
 Kernel Version:             3.10.0-514.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://19.3.0
 Kubelet Version:            v1.16.0
 Kube-Proxy Version:         v1.16.0
PodCIDR:                     100.64.0.0/24
PodCIDRs:                    100.64.0.0/24
Non-terminated Pods:         (9 in total)
  Namespace                  Name                                             CPU Requests  CPU Limits  Memory Requests  Memory Lim
its  AGE  ---------                  ----                                             ------------  ----------  ---------------  ----------
---  ---  kube-system                calico-kube-controllers-564b6667d7-nbmcv         0 (0%)        0 (0%)      0 (0%)           0 (0%)    
     44h  kube-system                calico-node-nwfjk                                250m (6%)     0 (0%)      0 (0%)           0 (0%)    
     44h  kube-system                coredns-5644d7b6d9-6n5wj                         100m (2%)     0 (0%)      70Mi (1%)        170Mi (4%)
     44h  kube-system                coredns-5644d7b6d9-kz9mq                         100m (2%)     0 (0%)      70Mi (1%)        170Mi (4%)
     44h  kube-system                etcd-localhost.localdomain                       0 (0%)        0 (0%)      0 (0%)           0 (0%)    
     44h  kube-system                kube-apiserver-localhost.localdomain             250m (6%)     0 (0%)      0 (0%)           0 (0%)    
     44h  kube-system                kube-controller-manager-localhost.localdomain    200m (5%)     0 (0%)      0 (0%)           0 (0%)    
     44h  kube-system                kube-proxy-w9xhs                                 0 (0%)        0 (0%)      0 (0%)           0 (0%)    
     44h  kube-system                kube-scheduler-localhost.localdomain             100m (2%)     0 (0%)      0 (0%)           0 (0%)    
     44hAllocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                1 (25%)     0 (0%)
  memory             140Mi (3%)  340Mi (9%)
  ephemeral-storage  0 (0%)      0 (0%)
Events:              <none>


Name:               node4
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=node4
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 09 Dec 2019 18:30:57 +0800
Taints:             node-role.kubernetes.io/master:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 11 Dec 2019 14:51:24 +0800   Mon, 09 Dec 2019 18:30:57 +0800   KubeletHasSufficientMemory   kubelet
 has sufficient memory available  DiskPressure     False   Wed, 11 Dec 2019 14:51:24 +0800   Mon, 09 Dec 2019 18:30:57 +0800   KubeletHasNoDiskPressure     kubelet
 has no disk pressure  PIDPressure      False   Wed, 11 Dec 2019 14:51:24 +0800   Mon, 09 Dec 2019 18:30:57 +0800   KubeletHasSufficientPID      kubelet
 has sufficient PID available  Ready            True    Wed, 11 Dec 2019 14:51:24 +0800   Mon, 09 Dec 2019 18:31:18 +0800   KubeletReady                 kubelet
 is posting ready statusAddresses:
  InternalIP:  192.168.1.224
  Hostname:    node4
Capacity:
 cpu:                16
 ephemeral-storage:  1275747Mi
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             32528244Ki
 pods:               110
Allocatable:
 cpu:                16
 ephemeral-storage:  1203945915652
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             32425844Ki
 pods:               110
System Info:
 Machine ID:                 468a4bb68d99483bb941aade72e4d7e3
 System UUID:                4C4C4544-0051-3510-8044-C3C04F4A4B32
 Boot ID:                    bcb3bee1-dfb4-4303-b8ed-153cc5e05ca1
 Kernel Version:             3.10.0-862.11.6.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://19.3.5
 Kubelet Version:            v1.16.0
 Kube-Proxy Version:         v1.16.0
PodCIDR:                     100.64.1.0/24
PodCIDRs:                    100.64.1.0/24
Non-terminated Pods:         (6 in total)
  Namespace                  Name                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                             ------------  ----------  ---------------  -------------  ---
  kube-system                calico-node-x8nxf                250m (1%)     0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                etcd-node4                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-apiserver-node4             250m (1%)     0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-controller-manager-node4    200m (1%)     0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-proxy-m45vf                 0 (0%)        0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-scheduler-node4             100m (0%)     0 (0%)      0 (0%)           0 (0%)         44h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                800m (5%)  0 (0%)
  memory             0 (0%)     0 (0%)
  ephemeral-storage  0 (0%)     0 (0%)
Events:              <none>


Name:               node5
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=node5
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Mon, 09 Dec 2019 18:32:05 +0800
Taints:             node-role.kubernetes.io/master:NoSchedule
Unschedulable:      false
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Wed, 11 Dec 2019 14:51:07 +0800   Mon, 09 Dec 2019 18:32:05 +0800   KubeletHasSufficientMemory   kubelet
 has sufficient memory available  DiskPressure     False   Wed, 11 Dec 2019 14:51:07 +0800   Mon, 09 Dec 2019 18:32:05 +0800   KubeletHasNoDiskPressure     kubelet
 has no disk pressure  PIDPressure      False   Wed, 11 Dec 2019 14:51:07 +0800   Mon, 09 Dec 2019 18:32:05 +0800   KubeletHasSufficientPID      kubelet
 has sufficient PID available  Ready            True    Wed, 11 Dec 2019 14:51:07 +0800   Mon, 09 Dec 2019 18:32:19 +0800   KubeletReady                 kubelet
 is posting ready statusAddresses:
  InternalIP:  192.168.1.225
  Hostname:    node5
Capacity:
 cpu:                24
 ephemeral-storage:  1950991608Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             98819716Ki
 pods:               110
Allocatable:
 cpu:                24
 ephemeral-storage:  1798033862956
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             98717316Ki
 pods:               110
System Info:
 Machine ID:                 82016b0290cc4ff5abd7ad998ea74fb3
 System UUID:                4C4C4544-0046-4E10-8043-B1C04F343358
 Boot ID:                    650d0e37-47b8-40da-ba7e-51b05afc78a2
 Kernel Version:             3.10.0-957.21.3.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://19.3.5
 Kubelet Version:            v1.16.0
 Kube-Proxy Version:         v1.16.0
PodCIDR:                     100.64.2.0/24
PodCIDRs:                    100.64.2.0/24
Non-terminated Pods:         (6 in total)
  Namespace                  Name                             CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                             ------------  ----------  ---------------  -------------  ---
  kube-system                calico-node-28rdr                250m (1%)     0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                etcd-node5                       0 (0%)        0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-apiserver-node5             250m (1%)     0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-controller-manager-node5    200m (0%)     0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-proxy-chqqm                 0 (0%)        0 (0%)      0 (0%)           0 (0%)         44h
  kube-system                kube-scheduler-node5             100m (0%)     0 (0%)      0 (0%)           0 (0%)         44h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests   Limits
  --------           --------   ------
  cpu                800m (3%)  0 (0%)
  memory             0 (0%)     0 (0%)
  ephemeral-storage  0 (0%)     0 (0%)
Events:              <none>

**Comment by Sammy2005** [comment]
Same issue here, the logs show that everything is fine
Any help?

**Comment by L-maple** [comment]
@ktsakalozos  Hello, Could you help me to solve this similar problem?
`Name:         fortune
Namespace:    default
Priority:     0
Node:         <none>
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  html-generator:
    Image:        luksa/fortune
    Port:         <none>
    Host Port:    <none>
    Environment:  <none>
    Mounts:
      /var/htdocs from html (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gb42r (ro)
  web-server:
    Image:        nginx:alpine
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /usr/share/nginx/html from html (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-gb42r (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  html:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-gb42r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gb42r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  <unknown>            default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  54m (x58 over 139m)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
`

**Comment by ktsakalozos** [comment]
@zhaishujie2, @L-maple, @Sammy2005 although this may not be a MicroK8s issue I can take a quick look to see if there is something wrong. Please open a new issue, attach the `microk8s.inspect` tarball and provide me with all the steps and yaml manifests needed to reproduce the problem. Thanks.
