### ISSUE TITLE
can't access pod logs after some event

### ISSUE THREAD

**Issue by termie** [ubuntu/microk8s#489]
It's not clear to me what causes this, it seems to happen on the two systems that have produced the most log output but there isn't a clear event when it happens. Neither system is anywhere near capacity, though both are heavily loaded.

```
I0528 19:57:06.729518   29212 loader.go:359] Config loaded from file /snap/microk8s/526/client.config
I0528 19:57:06.730077   29212 round_trippers.go:419] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.13.5 (linux/amd64) kubernetes/2166946" 'http://127.0.0.1:8080/api/v1/namespaces/default/pods/ace-service-55b6457685-rlt49/log?container=ace-service&follow=true'
I0528 19:57:06.733367   29212 round_trippers.go:438] GET http://127.0.0.1:8080/api/v1/namespaces/default/pods/ace-service-55b6457685-rlt49/log?container=ace-service&follow=true 404 Not Found in 3 milliseconds
I0528 19:57:06.733395   29212 round_trippers.go:444] Response Headers:
I0528 19:57:06.733406   29212 round_trippers.go:447]     Content-Type: application/json
I0528 19:57:06.733413   29212 round_trippers.go:447]     Date: Tue, 28 May 2019 19:57:06 GMT
I0528 19:57:06.733423   29212 round_trippers.go:447]     Content-Length: 270
I0528 19:57:06.733480   29212 request.go:942] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource ( pods/log ace-service-55b6457685-rlt49)","reason":"NotFound","details":{"name":"ace-service-55b6457685-rlt49","kind":"pods/log"},"code":404}
I0528 19:57:06.733873   29212 helpers.go:198] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource ( pods/log ace-service-55b6457685-rlt49)",
  "reason": "NotFound",
  "details": {
    "name": "ace-service-55b6457685-rlt49",
    "kind": "pods/log"
  },
  "code": 404
}]
F0528 19:57:06.733905   29212 helpers.go:116] Error from server (NotFound): the server could not find the requested resource ( pods/log ace-service-55b6457685-rlt49)
```

Neither restarting microk8s nor rebooting the server seems to fix it, but after taking one of them out of commission over the weekend, a reboot _did_ fix it. So it seems like something to do with either load or log rotation or something.

This is microk8s 1.13/stable as the move to 1.14 broke the system in a bunch of other ways, so upgrading is less of an option to me.

Docker logs for the container still work, as do tailing the files in the file system, but any access via kubectl fails with the above NotFound.

I've not found other reports of this after googling for either kubernetes or microk8s specifically (nor run into it while administering 100 node k8s clusters), so I feel like it is more likely to be on the microk8s side.

[inspection-report.tar.gz](https://github.com/ubuntu/microk8s/files/3229482/inspection-report.tar.gz)

**Comment by jobh** [comment]
I see the same on v1.18.4. The cluster has been running under heavy-ish load for about 4 months, but today it suddenly stopped accepting logs requests:
```
I0630 09:31:09.055384   16168 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource ( pods/log postgres-postgresql-0)",
  "reason": "NotFound",
  "details": {
    "name": "postgres-postgresql-0",
    "kind": "pods/log"
  },
  "code": 404
}]
F0630 09:31:09.055516   16168 helpers.go:115] Error from server (NotFound): the server could not find the requested resource ( pods/log postgres-postgresql-0)
```

I have tried microk8s.stop/microk8s.start without success. Most other commands and communication between pods seem to work.

**Comment by jobh** [comment]
The problem might (seems to, but possibly a coincidence) have started with an automatic snapd update:
```
Jun 30 08:34:39 stfv-hpcpro02 snapd: AppArmor status: apparmor not enabled
Jun 30 08:34:39 stfv-hpcpro02 snapd: patch.go:64: Patching system state level 6 to sublevel 1...
Jun 30 08:34:39 stfv-hpcpro02 snapd: patch.go:64: Patching system state level 6 to sublevel 2...
Jun 30 08:34:39 stfv-hpcpro02 snapd: patch.go:64: Patching system state level 6 to sublevel 3...
Jun 30 08:34:39 stfv-hpcpro02 snapd: daemon.go:343: started snapd/2.45-1.el7 (series 16; classic; devmode) rhel/7.8 (amd64) linux/3.10.0-1127.10.1.el7.x86_.
Jun 30 08:34:39 stfv-hpcpro02 snapd: daemon.go:436: adjusting startup timeout by 40s (pessimistic estimate of 30s plus 5s per snap)
Jun 30 08:35:04 stfv-hpcpro02 microk8s.daemon-apiserver-kicker: /var/lib/snapd/snap/microk8s/1341/apiservice-kicker: /snap/microk8s/1341/bin/sleep: /snap/core/current/lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or direc
tory
Jun 30 08:35:05 stfv-hpcpro02 snapd: daemon.go:542: gracefully waiting for running hooks
Jun 30 08:35:05 stfv-hpcpro02 snapd: daemon.go:544: done waiting for running hooks
Jun 30 08:35:05 stfv-hpcpro02 snapd: AppArmor status: apparmor not enabled
Jun 30 08:35:05 stfv-hpcpro02 snapd: daemon.go:343: started snapd/2.45-1.el7 (series 16; classic; devmode) rhel/7.8 (amd64) linux/3.10.0-1127.10.1.el7.x86_.
Jun 30 08:35:05 stfv-hpcpro02 snapd: daemon.go:436: adjusting startup timeout by 40s (pessimistic estimate of 30s plus 5s per snap)
Jun 30 08:35:16 stfv-hpcpro02 microk8s.daemon-flanneld: I0630 08:35:16.098848    1588 main.go:437] Stopped monitoring lease
Jun 30 08:35:16 stfv-hpcpro02 microk8s.daemon-flanneld: I0630 08:35:16.101448    1588 main.go:339] Waiting for all goroutines to exit
Jun 30 08:35:16 stfv-hpcpro02 microk8s.daemon-flanneld: I0630 08:35:16.104236    1588 main.go:370] shutdownHandler sent cancel signal...
Jun 30 08:35:16 stfv-hpcpro02 microk8s.daemon-flanneld: I0630 08:35:16.113436    1588 main.go:342] Exiting cleanly...
```
Then a lot of noise in the logs for several minutes (all microk8s services, sandboxes, pods restarted). Many of which are errors, but I don't know if they mean anything or are just transient. After everything had stabilized, this error keeps getting reported in the logs:
```
Jun 30 09:56:30 stfv-hpcpro02 microk8s.daemon-etcd: WARNING: 2020/06/30 09:56:30 grpc: addrConn.createTransport failed to connect to {0.0.0.0:12379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing failed to do connect handshake, response: \"HTTP/1.1 503 Service Unavailable\\r\\nConnection: close\\r\\nContent-Length: 768\\r\\nCache-Control: no-cache\\r\\nContent-Type: text/html; charset=utf-8\\r\\nPragma: no-cache\\r\\nProxy-Connection: close\\r\\n\\r\\n<HTML><HEAD>\\r\\n<TITLE>Network Error</TITLE>\\r\\n</HEAD>\\r\\n<BODY>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big><strong></strong></big><BR>\\r\\n</FONT>\\r\\n<blockquote>\\r\\n<TABLE border=0 cellPadding=1 width=\\\"80%\\\">\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\n<big>Network Error (tcp_error)</big>\\r\\n<BR>\\r\\n<BR>\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nA communication error occurred: \\\"\\\"\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\">\\r\\nThe Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n<TR><TD>\\r\\n<FONT face=\\\"Helvetica\\\" SIZE=2>\\r\\n<BR>\\r\\nFor assistance, contact your network support team.\\r\\n</FONT>\\r\\n</TD></TR>\\r\\n</TABLE>\\r\\n</blockquote>\\r\\n</FONT>\\r\\n</BODY></HTML>\\r\\n\"". Reconnecting...
```
I can provide the full logs from after the snapd upgrade on request, but it's ~1900 lines on system I can't easily copy files out from, so only if interesting.

**Comment by jobh** [comment]
Actually I recognize that 503 message. It's from the system's $http_proxy server, which shouldn't be used here of course.

That log message is not logged in the previous 4 weeks, so whatever causes it was triggered by the snapd upgrade.

**Comment by jobh** [comment]
(Side note: I wasn't aware of the auto refresh policy of snap, and I don't like it. Although I wouldn't call it real production, the services I run under microk8s have users and is meant to be stable and up at all times - unless I decide an upgrade is warranted, and notify the users. I will try to enable the "app awareness" mode of snap to see if it helps to stop the automatic refreshes. https://forum.snapcraft.io/t/wip-refresh-app-awareness/10736)

**Comment by trulede** [comment]
I've had this same problem for some time (Feb/March 2020). At some point I presume a SNAP update broke something, the since then I've not been able to correct this. The observation is this:

```
$ microk8s kubectl -n dse logs component-5d95b44657-zwmmn -c adapter
Error from server (NotFound): the server could not find the requested resource ( pods/log component-5d95b44657-zwmmn)
```

But of course the logs are being produced (note I need sudo to read them):

```
$ sudo cat /var/log/pods/dse_component-5d95b44657-zwmmn_e40b8253-8398-4721-b77a-3d
ba12f9101b/adapter/0.log
2020-09-28T11:15:47.620748345Z stderr F INFO:dse.component.component:Component:
2020-09-28T11:15:47.62076961Z stderr F INFO:dse.component.component:    uid=1234
```

I wonder if anyone as an idea how to recover from this?

**Comment by jobh** [comment]
@trulede , @termie - do you have HTTP_PROXY/HTTPS_PROXY set? I suspect it may be relevant for my problem somehow, but if it's only me then it's probably a red herring.

**Comment by trulede** [comment]
Yes, they are set, however if I prefix the logs command with `unset ....`  to remove that, it does not help.

**Comment by jobh** [comment]
I think this may be related, https://github.com/etcd-io/etcd/issues/9763.

Unsetting the environment variables in the logs command will not help, it's some cluster-internal communication that fails.

I don't know how to fix it (possibly by setting `--advertise-client-urls` in `/var/snap/microk8s/current/args/etcd` and restarting `etcd`, in combination with a `no_proxy` environment variable, or perhaps just setting `no_proxy=localhost` in `/etc/environment`). But I can't experiment with my "problematic" system now, because it's in use.
