### ISSUE TITLE
Cluster restarts every ~1 Minute

### ISSUE THREAD

**Issue by JohnnyCrazy** [ubuntu/microk8s#492]
Hi!

Basically the cluster theoratically works fine, however, it restarts itself every ~1 Minute. I suspect a network issue because I can see some timeout issues in the logs, but sadly I could not pinpoint the bug to a specific log line error, since there are a lot of them :P It happened as soon as I try to deploy some resources (Tried it with `microk8s.enable dns` or my traefik resources, consisting of a DaemonSet, Service and Ingress)

I'm running on the edge channel because of #451 , which I could not test yet because of the restarts. However, tests also confirm it's happening on the stable channel.

```
snap    2.39.1-1
snapd   2.39.1-1
series  16
arch    -
kernel  5.1.5-arch1-2-ARCH
```

Also ran `sudo iptables -P FORWARD ACCEPT` for the correct forwarding.

[inspection-report-20190602_000748.tar.gz](https://github.com/ubuntu/microk8s/files/3244244/inspection-report-20190602_000748.tar.gz)

**Comment by ktsakalozos** [comment]
@JohnnyCrazy, MicroK8s has a service that monitors network changes and re-configures services as needed. For example if you are on a laptop and connect to a different network MicroK8s needs to be reconfigured appropriately. The apiservice-kicker daemon is here: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/apiservice-kicker#L27 . Is it possible that in your host system there is a network interface flapping? To stop the reconfiguration attempts you can: `sudo systemctl stop snap.microk8s.daemon-apiserver-kicker.service`. Note however that the apiservice-kicker will restart in the case of an upgrade or a `microk8s.stop/start` cycle.

**Comment by JohnnyCrazy** [comment]
@ktsakalozos indeed, stopping the service fixed it.

I recorded the following changes when the services is running:

1. Before I start microk8s, the following links exist:
```
➜ sudo ip link list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wlp1s0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether b4:b6:76:3f:a7:23 brd ff:ff:ff:ff:ff:ff
3: docker0: <BROADCAST,MULTICAST,DYNAMIC> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether aa:f6:8a:4d:2d:7a brd ff:ff:ff:ff:ff:ff
127: cbr0: <NO-CARRIER,BROADCAST,MULTICAST,DYNAMIC,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 82:a9:52:cf:24:0f brd ff:ff:ff:ff:ff:ff
```

No interface is flapping, AFAIK and understand.

2. Once I start it, the output changes:
```
➜ sudo ip link list
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wlp1s0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether b4:b6:76:3f:a7:23 brd ff:ff:ff:ff:ff:ff
3: docker0: <BROADCAST,MULTICAST,DYNAMIC> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether aa:f6:8a:4d:2d:7a brd ff:ff:ff:ff:ff:ff
127: cbr0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 82:a9:52:cf:24:0f brd ff:ff:ff:ff:ff:ff
182: vethae44418f@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cbr0 state UP mode DEFAULT group default
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
Error: Peer netns reference is invalid.
    link/ether 42:61:3c:6d:12:0a brd ff:ff:ff:ff:ff:ff link-netns cni-305baf71-c363-c694-4c67-8d8f2edc4488
183: veth8222acbe@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cbr0 state UP mode DEFAULT group default
    link/ether 16:7f:fb:a6:d2:ef brd ff:ff:ff:ff:ff:ff link-netns cni-6e5fe5cc-205e-1a9d-e48a-99a300cedaad
184: veth101505d2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cbr0 state UP mode DEFAULT group default
    link/ether aa:8a:5a:57:d2:e0 brd ff:ff:ff:ff:ff:ff link-netns cni-52945ffe-25ff-6ef1-97f3-365c70faabdd
185: veth466cf459@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cbr0 state UP mode DEFAULT group default
    link/ether be:66:cb:e4:ec:67 brd ff:ff:ff:ff:ff:ff link-netns cni-52fc6e86-8f54-7eeb-d710-a6d9de945766
186: vethbe110234@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master cbr0 state UP mode DEFAULT group default
    link/ether de:78:3e:28:5a:b2 brd ff:ff:ff:ff:ff:ff link-netns cni-af22adea-c7c7-5408-e3b0-a091a7d4a64e
```

and `external_ip,txt` contains:
```
192.168.178.27 10.1.1.1 fd00::XXXX:76ff:XXXX:a723 2001:XXXX:3a27:f501:b6b6:XXXX:fe3f:a723
```

after some time, it gets
```
192.168.178.27 10.1.1.1 169.254.211.165 169.254.205.113 169.254.229.235 169.254.208.136 fd00::XXXX:76ff:XXXX:a723 2001:XXXX:3a27:f501:b6b6:XXXX:fe3f:a723
```

and then back to normal state
```
192.168.178.27 10.1.1.1 169.254.151.85 fd00::XXXX:76ff:XXXX:a723 2001:XXXX:3a27:f501:b6b6:XXXX:fe3f:a723
```

and every 1 minute a 169.* pops up again

```
192.168.178.27 10.1.1.1 169.254.151.85 fd00::XXXX:76ff:XXXX:a723 2001:XXXX:3a27:f501:b6b6:XXXX:fe3f:a723
```

@ktsakalozos Do you have any idea why those interfaces get created once microk8s starts? And why so many...

**Comment by JohnnyCrazy** [comment]
Also: Once I stop microk8s, the veth* interfaces are not removed, have to remove them manually.

**Comment by ktsakalozos** [comment]
This does not seem Kubernetes related (at least I haven't seen it before). Do you happen to have a network printer configured or something similar (just guessing)?

**Comment by JohnnyCrazy** [comment]
Mh, no, sadly not.

Every of those veth interfaces contain this `cni-*` line and appear as soon as microk8s starts, maybe it could be related to this? https://github.com/ubuntu/microk8s/blob/98c38a7561da5422b641eacd4cf4adb5adaa7248/microk8s-resources/default-args/cni-network/cni.conf

I will try to analyze it furhter, maybe find out which process creates these interfaces

**Comment by JohnnyCrazy** [comment]
Sadly, I was not able to figure out why this happens...

Since it's probably related to some weird interface setup on my machine, I'm gonna close this issue. Thanks for your fast responses, appreciate it @ktsakalozos :+1:
