### ISSUE TITLE
microk8s.reset --help kills your cluster

### ISSUE THREAD

**Issue by tbaumann** [ubuntu/microk8s#497]
```
tilmanb@zuse:~$ microk8s.reset --help
[sudo] password for tilmanb: 
Calling clean_cluster
Cleaning resources in namespace default
```

I was actually fine with that. I was looking for a cleanup command.
But I called it with `--help` specifically because I wanted to find out what it does before I do something.

microk8s.reset should print usage info if called with parameters.

**Comment by ktsakalozos** [comment]
That is a good point. Our reset wrapper https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-reset.wrapper needs some refactoring.

**Comment by ktsakalozos** [comment]
The `--help` flag was added beginning of September so it was not released at the time this issue was opened.

I am closing this. Please feel free to reopen it if you need further improvements.
