### ISSUE TITLE
Service ports not working from localhost

### ISSUE THREAD

**Issue by wittlesouth** [ubuntu/microk8s#498]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

I'm unable to access services exposed via NodePorts from localhost on the machine running microk8s, but am able to access the services from off box using the NodePort. For example, I'm running microk8s on `nuc5.wittlesouth.com`. You can see that I get an empty JSON object response from the registry service running on that node via curl:

```
Erics-2018-MBP:~ eric$ curl nuc5.wittlesouth.com:32000/v2/
{}Erics-2018-MBP:~ eric$
```

And when I run the same request from on box, the request hangs with no response:

```
Erics-2018-MBP:~ eric$ ssh ericw@nuc5.wittlesouth.com
ericw@nuc5:~$ curl localhost:32000/v2/
^C
```

This is a brand-new install done earlier today.

[inspection-report-20190608_162030.tar.gz](https://github.com/ubuntu/microk8s/files/3268909/inspection-report-20190608_162030.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @wittlesouth 

I cannot reproduce the issue you are seeing here. The local curl goes through over here with no problems? Is there a firewall in the way? Can you think of anything special about the node? What else can you share so I can reproduce this issue?

**Comment by wittlesouth** [comment]
As I mentioned, it is happening on more than one node. One is a bare metal install on an Intel NUC system, the second is a VMware Fusion VM. Both running reasonably current versions of Ubuntu. I'm assuming it is a networking configuration issue of some kind, but am not sure what to suggest for reproduction. Are there other kinds of test cases you recommend? Are there IPtables configuration items I should check that are specific to localhost?

I find it odd that the service ports work on network devices with assigned IP addresses on the network, it seems to be an issue limited to localhost. I'm not an IPtables or Kubernetes networking expert by any means.

**Comment by ktsakalozos** [comment]
I see you have IPv6 in your nodes. Could you try the suggestion found here https://github.com/ubuntu/microk8s/issues/196#issuecomment-443869365 or disable IPv6?

**Comment by wittlesouth** [comment]
I can confirm for sure that solves the problem of not getting a response via `curl http://localhost:32000/v2/`. I have not re-configured the node to use the localhost URL for registry yet; do you need me to confirm that problem is solved as well? Is a reproduction still needed or useful?

**Comment by wittlesouth** [comment]
One more comment. I worded the subject more broadly than just about the registry because that wasn't the only evidence I had that there was a problem of some form with service ports and local networking. The other symptom was challenges mapping my Traefik ingress port to port 80. I have the Traefik ingress service running on service port 30400. Per multiple bits of research on the web, I attempted to use iptables to forward port 80 traffic to port 30400. Specifically, with the command:

`sudo iptables -t nat -I PREROUTING --src 0/0 --dst 192.168.119.3 -p tcp --dport 80 -j REDIRECT --to-ports 30400`

It wasn't working, any requests made externally to port 80 hung. While attempting to diagnose the problem, I ran the following command:

`sudo iptables -t nat -L -n -v | grep 30400`

That command showed the manual entry I'd created, but it also showed another redirect from port 30400 (outside the service port range) to another port (e.g. 35917, 38149, etc). Output like the following:

```
ericw@wsv-dev:/var/snap/microk8s/current/args$ sudo iptables -t nat -L -n -v | grep 30400
    3   192 REDIRECT   tcp  --  *      *       0.0.0.0/0            192.168.119.3        tcp dpt:80 redir ports 30400
    1    60 REDIRECT   tcp  --  *      *       0.0.0.0/0            192.168.119.3        tcp dpt:80 redir ports 30400
  113  7232 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/traefik-ingress-service:web */ tcp dpt:30400 redir ports 38149
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kube-system/traefik-ingress-service:web */ tcp dpt:30400 to:192.168.119.3:38149
```

If I mapped port 80 to this other port, then external traffic to port 80 on the machine correctly made it to my Traefik ingress port. This was just a workaround, because every stop/start of microk8s gave a new port number that 30400 was mapped to in this way.

Since commenting out the IPv6 entries in localhost, the original redirect from port 80 to port 30400 is now functioning, and I expect will survive restarts.

I'm not 100% certain that this symptom has the same root cause because I don't fully understand how Kubernetes networking works, but the evidence seems to suggest this might be another manifestation of the problem.

**Comment by wittlesouth** [comment]
One last comment before I focus on something else for the evening. There is another workaround besides commenting out the IPv6 localhost entries in /etc/hosts, and that is to change the address lookup configuration to default to IPv4 as described [here](http://terokarvinen.com/2016/prefer-ipv4-on-ubuntu-16-04-lts-xenial-etcgai-conf-precedence-ffff0096-100). I can confirm that uncommenting the line referenced in the link above in `/etc/gai.conf` also allows `curl http://localhost:32000/v2/` to work with the IPv6 references for localhost active in /etc/hosts. I'm not sure if that is a configuration change that can be made during microk8s install, but I would at least recommend documenting it in the installation guide the same way the ufw commands for cbr0 are documented.

**Comment by ktsakalozos** [comment]
It is good to hear that was resolved. Thank you for the deep dive into this issue. Do you have any suggestions on how to handle this IPv6 case in an elegant way? We do not want to be intrusive and configure system wide behavior (eg patching hosts and gai.conf files). We could however detect this issue in the  `microk8s.inspect` script https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh and offer an advice.

What do you think?

**Comment by wittlesouth** [comment]
Hmm, off the top of my head I would suggest that you could fail the enable command, or warn on the enable command, for any service that you expect to be accessed through localhost. If the command to enable the registry had failed saying that IPv6 is enabled on the system and therefore localhost ports would not work, I hopefully would have figured out I needed configuration changes for a local registry to work.

I also think the documentation proposal I made would probably work as well; if you add the gai.conf setting to the section that references the ufw configuration for sr0, it would probably be enough. You could also document the alternative, which would be to create an IPv4 alias in hosts and use that rather than localhost. I haven't tried that, but I think it would work.

Let me know if you want help testing a change, or I supposed I could try the doc changes myself and submit a pull request.

**Comment by ktsakalozos** [comment]
Your suggestions make sense. I am marking this as a good first issue for people like willing to contribute. 

- Documentation can be updated here: https://github.com/canonical-web-and-design/microk8s.io/blob/master/docs/index.md#troubleshooting

- To detect IPv6 and display a warning during the `microk8s.enable registry` we will need to update https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.registry.sh

- To detect IPv6 and display a warning during the `microk8s.inspect` command we will need to update https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh

**Comment by wittlesouth** [comment]
I drafted a section for troubleshooting you can see [here](https://github.com/wittlesouth/microk8s.io/blob/master/docs/index.md). As far as detecting IPv6 and issuing a warning, I'm not sure the approach you'd prefer. I was thinking of adding something like this to the end of enable.registry.sh after echoing that the registry is enabled:

```
curl -s -m 2 http://localhost:32000/v2/ > /dev/null

if [ 0 -ne $? ]; then
  echo "Registry not responding, check if IPv6 is enabled"
fi

```

At least in Ubuntu server (where I found this problem), curl is installed by default. Please let me know if this looks like a reasonable approach. As far as detecting IPv6 with inspect, I'd be curious on preferred approach there too. My temptation is to try a single ping to localhost and parse the response to see if the address looks like IPv4 or not, as opposed to trying to inspect the /etc/hosts file or deal with the actual networking configuration files.

What kinds of tests should I do before submitting a pull request?

**Comment by ktsakalozos** [comment]
Thank you for helping with this issue.

On the documentation, I would very much prefer like the troubleshooting entry to describe the problem and offer a simple fix. You might add links where this problem is explained in depth, but lets try to offer a simple fix (eg, edit the /etc/hosts).

On the inspect, I am +1 on looking at the ping result and saying something like "WARNING: IPv6 is enabled. This may cause issues in workloads using NodePort (eg the registry addon), please see the troubleshooting section at <link>". What do you think?

On the registry enable script lets use the same detection approach and print the same warning. Your approach of curling the registry endpoint is the right one, however the registry may not be ready at the time the enable script finishes. The registry enable script just submits the k8s manifests, it does not wait for the services to come up.

Thank you again for your help.
