### ISSUE TITLE
failed to access kube-dns in the cluster

### ISSUE THREAD

**Issue by zkuang** [ubuntu/microk8s#503]
There're lots of logs like:
microk8s.daemon-proxy[15543]: E0612 22:18:53.558576   15543 proxysocket.go:235] Write failed: write udp 10.1.1.1:48044->10.1.1.45:53: write: operation not permitted
And other pods can not access kube-dns with the cluster IP.

[inspection-report-20190612_220806.tar.gz](https://github.com/ubuntu/microk8s/files/3281723/inspection-report-20190612_220806.tar.gz)
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by ktsakalozos** [comment]
@zkuang could you try removing the local containerd you have `apt-get remove containerd.io` just in case there is something left running there? Can you also check the edge channel where we have introduced coredns (`sudo snap install microk8s --classic --edge`)?

**Comment by zkuang** [comment]
Sorry for replying late. I tried that, doesn't related.
But later I figure it out. I have to disconnect my vpn before initializing micrk8s (after pulling images). So I'm closing this.
