### ISSUE TITLE
Support for Windows 10

### ISSUE THREAD

**Issue by VenkateshSrini** [ubuntu/microk8s#510]
Hi Team,

Can MicroK8s be installed on Windows 10 Pro 64 bit. I would suggest that you provide the same as Chocolatey package. In case your binaries are only Linux, then can you please quickly get it running by creating a small Linux VM on hyper V and get the bits running for us. Though there many install like Minikube, they are not stable. Docker for desktop with Kubernetes, we have problem of not being able to run Istio.

**Comment by ktsakalozos** [comment]
Hi @VenkateshSrini 

MicroK8s needs a VM to run on Windows and MacOS. Please have a look at the blogs: https://itnext.io/microk8s-on-windows-the-canonical-way-ed15fd4e5476 and https://itnext.io/microk8s-on-macos-98f1de3aa63e . Any VM management solutions would work. The one recommended by Canonical is multipass. There are efforts in the community to make the VM creation and management transparent (https://github.com/Jvardas/microk8s-windows-installer).

We haven't looked into Chocolatey packages, they definitely look like a great way to deliver the end solution.

How do you intend to use MicroK8s? Any feedback you can give us on yor workflow and the user experience you are looking for are much appreciated.

**Comment by VenkateshSrini** [comment]
@ktsakalozos,

My workflow is like installing the Microk8s from chocolatey package. In that you will have a powershell script that will first elevates its previliges, then check if there is a VM by name Microk8s in Hyper-V, when not create it, deploy microk8s. Then ask an option as to whether you want to make microk8s as default. If also add that configuration kubectlconfig. This will make my kubectl directly work against microk8s.  Before doing this you also can check if system has enough memory and CPU to work

**Comment by joedborg** [comment]
Hi @VenkateshSrini, a preview of this is now available from https://github.com/ubuntu/microk8s/releases/tag/installer-v1.0.0.  Feedback is warmly welcomed!
