### ISSUE TITLE
Unable to access private Docker registry

### ISSUE THREAD

**Issue by feered** [ubuntu/microk8s#512]
I am running MicroK8s 1.14. I have used EKS and tried to deploy the same configuration to my MicroK8s without any luck.  We are using an official private Docker registry and required some configuration on EKS to allow authentication. I tried running the same command on my MicroK8s but getting authorization failed.

```bash
kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=<dockeruser> --docker-password=<dockerpass> --docker-email=<dockeremail>
```

This creates the configuration which can be verified with `kubectl get secret regcred --output=yaml`. Looks good and the base64 encoded configuration matches my EKS configuration. When trying to deploy my pods, I am getting the following error on the deployment:

```
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned default/buffet-parser-6c4fc4d5c6-flsht to kraken
  Normal   Pulling    12m (x4 over 13m)     kubelet, kraken    Pulling image "appdev/buffet-parser:latest"
  Warning  Failed     12m (x4 over 13m)     kubelet, kraken    Failed to pull image "appdev/buffet-parser:latest": rpc error: code = Unknown desc = failed to resolve image "docker.io/appdev/buffet-parser:latest": no available registry endpoint: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     12m (x4 over 13m)     kubelet, kraken    Error: ErrImagePull
  Warning  Failed     11m (x6 over 13m)     kubelet, kraken    Error: ImagePullBackOff
  Normal   BackOff    3m41s (x43 over 13m)  kubelet, kraken    Back-off pulling image "appdev/buffet-parser:latest"
```

**Comment by ktsakalozos** [comment]
Hi @feered 

I do not know what exactly might be wrong, but here are some links to resources related to the subject:
- MicroK8s accessing ECR https://discuss.kubernetes.io/t/microk8s-ec2-and-ecr/6476
- Configuring microk8s' `/var/snap/microk8s/current/args/containerd-template.toml` https://github.com/containerd/cri/blob/master/docs/registry.md
- General guidelines on how to use registries https://microk8s.io/docs/working

Hope this helps. Really interested to see what the issue might be. I would like to beef up the guidelines with concrete examples on accessing private secure registries.

**Comment by feered** [comment]
I've seen your second and third link which are related to my issue. I have attempted to create the necessary configuration based on the second link and am still unable to access the Docker repository. My images are hosted on hub.docker.com which seems to be the default registry for MicroK8s. I would assume all I would need to do is provide my own auth config as demonstrated in the second link.

So I am a bit confused. Kubernetes recommends configuring authentication via the `kubectl create secret docker-registry` command but is apparently ignored by MicroK8s. Was this intentional or a limitation of Kubernetes when building MicroK8s?

**Comment by ktsakalozos** [comment]
I just tested this and it worked. Here is what I did.

- On dockerhub you are given one private repository so I created one
- On MicroK8s (I am on 1.15 now) I created a secret like this:
```
kubectl create secret docker-registry regcred --docker-username=[myusername] --docker-password=[mypassword] --docker-email=[me]@gmail.com --docker-server=https://index.docker.io/v1/
``` 
- Build the image of the following `Dockerfile`:
```
> cat ./Dockerfile 
FROM nginx:alpine
```
- Build tag and push the image to the repository I named private:
```
docker build .
docker tag bfba26ca350c [myusername]/private:alpine
docker push [myusername]/private:alipne
```
- Use the image in the following yaml:
```
> cat ./private-repo.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: [myusername]/private:alipne
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
```
(sorry for the misleading nginx references, I was just reusing an old manifest)

What am I doing differently? Please provide all the steps i need to take to reproduce this issue.

**Comment by feered** [comment]
Thank you for taking the time to troubleshoot this with me. I am using `kompose` to orchestrate the deployment of my pods with a `docker-compose.yml` script. The `docker-compose.yml` has labels `kompose.image-pull-secret: regcred` that are translated into service labels in Kubernetes.

I have updated my version of Kompose and now it seems to be working. I apologize and thank you for taking the time to step through this with me. This is definitely a user error.

Cheers.
