### ISSUE TITLE
microk8s.daemon-kubelet unable to start on 19.04

### ISSUE THREAD

**Issue by putz612** [ubuntu/microk8s#519]
Fresh install of microk8s a Ubuntu 19.04 which admittedly has been around a long time. 

Running microk8s.inspect reports back that the "Service snap.microk8s.daemon-kubelet is not running"

Looking at journalctl -u snap.microk8s.daemon-kubelet it is reporting that the cgroup for cpu and memory are not the same.
```
Jun 21 11:48:35 itx-42l systemd[1]: Started Service for snap application microk8s.daemon-kubelet.
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --anonymous-auth has been deprecated, This parameter should be set via the config file
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file s
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --pod-cidr has been deprecated, This parameter should be set via the config file speci
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --non-masquerade-cidr has been deprecated, will be removed in a future version
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --feature-gates has been deprecated, This parameter should be set via the config file 
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --eviction-hard has been deprecated, This parameter should be set via the config file 
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file sp
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: I0621 11:48:35.984565    3272 server.go:425] Version: v1.15.0
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: I0621 11:48:35.984845    3272 plugins.go:103] No cloud provider specified.
Jun 21 11:48:35 itx-42l microk8s.daemon-kubelet[3272]: F0621 11:48:35.986778    3272 server.go:273] failed to run Kubelet: failed to get the kubel
Jun 21 11:48:35 itx-42l systemd[1]: snap.microk8s.daemon-kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
```

**Comment by timbit123** [comment]
My microk8s stopped working too with same issue on channel stable v1.15.0
service microk8s.daemon-kubelet doesn't start and i'm getting a lot of error :
Jun 05 22:14:37 kube-microk8s microk8s.daemon-kubelet[509]: E0605 22:14:37.993262     509 container_manager_linux.go:490] failed to find cgroups of kubelet - cpu and memory cgroup hierarchy not unified.  cpu: /, memory: /system.slice/snap.microk8s.daemon-kubelet.service
[inspection-report-20190621_194735.tar.gz](https://github.com/ubuntu/microk8s/files/3315838/inspection-report-20190621_194735.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @putz612 , @timbit123 is this a VM? If yes, can you please provide some info on how this VM was created?

Can you also try this:
```
echo "--runtime-cgroups=/systemd/system.slice" | sudo tee -a /var/snap/microk8s/current/args/kubelet
echo "--kubelet-cgroups=/systemd/system.slice" | sudo tee -a /var/snap/microk8s/current/args/kubelet 
sudo systemctl restart  snap.microk8s.daemon-kubelet.service
```
To append the two arguments: `--runtime-cgroups=/systemd/system.slice` and `--kubelet-cgroups=/systemd/system.slice` to /var/snap/microk8s/current/args/kubelet .

**Comment by timbit123** [comment]
Hi @ktsakalozos, I'm on Proxmox
here is my config file for qemu
```
root@pve2:/etc/pve/local/qemu-server# cat 108.conf 
agent: 1
balloon: 0
bootdisk: virtio0
cores: 8
ide2: none,media=cdrom
memory: 24576
name: kube-gke
net0: virtio=F2:6B:5C:84:B7:DF,bridge=vmbr0,firewall=1,tag=102
numa: 0
ostype: l26
scsihw: virtio-scsi-pci
smbios1: uuid=2a2e3193-6c22-484f-95c6-d29444e49376
sockets: 1
virtio0: data:vm-108-disk-0,size=128G
vmgenid: edb9532d-7aa7-4c5c-b901-1647b9705816
```
but your changes worked for me!

**Comment by putz612** [comment]
@ktsakalozos This was just on my laptop, real gear.  I did create a brand new VM just to try it out and got the same error.  Running in the two commands and rebooting the VM and it worked perfectly, have not tried my laptop yet.

**Comment by ktsakalozos** [comment]
19.04 on lxc and on aws seem to be fine. I was able to reproduce with a KVM instance.

**Comment by edison-moreland** [comment]
I had the same issue with the same setup (Ubuntu 19.04/microk8s v1.15.0) 
The commands @ktsakalozos provided worked perfectly, thank you! :)

**Comment by ktsakalozos** [comment]
Based on this https://github.com/kubernetes/kubernetes/blob/d8695d06b7191db56ebbbc0340da263833c9bb6f/pkg/kubelet/cm/container_manager_linux.go#L804 seems that the kernel of 19.04 has changed the hierarchy of cgroups and kubelet is complainig about it. There a couple of things to test before trying to automate a workaround. First there is the suggestion at https://forum.snapcraft.io/t/resources-percentage-limit-for-a-snap/985/8 for which the snap should touch its systemd. Then there is the option of figuring out if we are on a kernel where we do not have the right hierarchy (eg by looking at the /proc/1/cgroups and checking that the memory and cpu paths are the same), if needed append the two config arguments in the kubelet's args.

**Comment by ktsakalozos** [comment]
There is a quick patch for this on the edge channel:

```
sudo snap install microk8s --classic --edge
```

Any feedback is welcomed.

**Comment by ktsakalozos** [comment]
Waiting for some feedback before calling this done.

**Comment by timbit123** [comment]
I did a refresh on edge
```
Name      Version  Rev  Tracking  Publisher   Notes
microk8s  v1.15.0  671  edge      canonical✓  classic
```
everything still working fine for me.

**Comment by ktsakalozos** [comment]
The fix got released to stable yesterday. Thank you all for reporting this.
