### ISSUE TITLE
ingress controller failed while uploading large file

### ISSUE THREAD

**Issue by sureshamk** [ubuntu/microk8s#526]
I enabled ingress controller . I seen its nginx based . For testing one of my service its need more than 1gb need to uploaded. But in this setup its failed because of `413 large entity ` problem. Any workaround for this ?

**Comment by ktsakalozos** [comment]
Hi @sureshamk , have you tried the suggestion here: https://stackoverflow.com/questions/49918313/413-error-with-kubernetes-and-nginx-ingress-controller ?

**Comment by sureshamk** [comment]
Its works @ktsakalozos . thanks

**Comment by davigar15** [comment]
@sureshamk 
How did it work for you? What steps have you made?

I have tried it but it didn't work for me.
