### ISSUE TITLE
Ability to use kubectl for users who are not local

### ISSUE THREAD

**Issue by wittlesouth** [ubuntu/microk8s#532]
Symptom shown below:

```
eric@nuc4:~/snap$ kubectl get pods
cannot create user data directory: /Users/eric/snap/microk8s/671: Permission denied
eric@nuc4:~/snap$ ls -al /Users/eric/snap/microk8s
total 16
drwxrwxrwx 4 eric dialout 4096 Jul  4 14:46 .
drwxr-xr-x 3 eric dialout 4096 Jul  4 14:46 ..
drwxrwxrwx 3 eric dialout 4096 Jul  4 15:11 671
drwxrwxrwx 2 eric dialout 4096 Jul  4 14:46 common
lrwxrwxrwx 1 eric dialout    3 Jul  4 14:46 current -> 671
eric@nuc4:~/snap$ 
```

Same command works fine with the user who installed microk8s:

```
ericw@nuc4:~$ kubectl get pods
No resources found.
```

The difference between the user "eric" and the user "ericw" is that ericw is a local user whose home directory is /home/ericw. The user "eric" is an LDAP user (from Apple Server's directory service), and therefore has a home directory /Users/eric. 

Directory permissions for the root directory look the same:

```
ericw@nuc4:/$ ls -al | grep home
drwxr-xr-x   3 root root  4096 Jan 22 04:05 home
ericw@nuc4:/$ ls -al | grep Users
drwxr-xr-x   3 root root  4096 Jul  4 14:34 Users
```

Directory permissions for the user directories look similar:

```
ericw@nuc4:/$ ls -al Users | grep eric
drwxr-xr-x  6 eric users 4096 Jul  4 14:58 eric
ericw@nuc4:/$ ls -al home | grep ericw
drwxr-xr-x  8 ericw ericw 4096 Jul  4 15:03 ericw
```

I ran `sudo chmod -R 755 snap/microk8s` to see if that would help, and it didn't. I'm wondering if there is a reason microk8s can't access a /Users directory?

[inspection-report-20190704_152321.tar.gz](https://github.com/ubuntu/microk8s/files/3360335/inspection-report-20190704_152321.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @wittlesouth, I suspect this is because of the remotely mounted HOME, but I am not sure.

I asked about this in the snapcraft forum: https://github.com/ubuntu/microk8s/issues/532

**Comment by wittlesouth** [comment]
If by home you mean /Users/eric, that is not remotely mounted. I have ldap authentication configured to automatically create the home directory on local storage on first login.

**Comment by rzr** [comment]
Does your OS use apparmor ?
