### ISSUE TITLE
microk8s services restarting randomly

### ISSUE THREAD

**Issue by andrenarchy** [ubuntu/microk8s#534]
My microk8s instance seemed to go unavailable from time to time and now I saw this in the logs:
```
$ grep Stopping /var/log/syslog
Jul  7 12:03:15 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
Jul  7 12:04:15 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-apiserver...
Jul  7 12:04:16 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-proxy...
Jul  7 12:04:16 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-kubelet...
Jul  7 12:04:19 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
Jul  7 12:05:19 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-apiserver...
Jul  7 12:05:19 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-proxy...
Jul  7 12:05:19 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-kubelet...
Jul  7 12:43:11 smokey systemd[1]: Stopping User Manager for UID 1000...
Jul  7 12:43:55 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
Jul  7 12:44:56 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-apiserver...
Jul  7 12:44:56 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-proxy...
Jul  7 12:44:56 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-kubelet...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-apiserver...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-apiserver-kicker...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-controller-manager...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-etcd...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-kubelet...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-proxy...
Jul  7 12:59:25 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-scheduler...
Jul  7 14:03:16 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-containerd...
Jul  7 14:03:33 smokey systemd[1]: Stopping User Manager for UID 1000...
Jul  7 14:04:17 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-apiserver...
Jul  7 14:04:17 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-proxy...
Jul  7 14:04:17 smokey systemd[1]: Stopping Service for snap application microk8s.daemon-kubelet...
```
Systemd restarts the microk8s services randomly. Any idea what's going on here?

[inspection-report-20190707_141239.tar.gz](https://github.com/ubuntu/microk8s/files/3365715/inspection-report-20190707_141239.tar.gz)

**Comment by andrenarchy** [comment]
Some of the restarts coincide an assignment of a new ipv6 address on the host – I don't know how this could be related but I thought I should share because it's literally happening in the same second.

**Comment by balchua** [comment]
@andrenarchy microk8s comes with a systemd service `apiservice-kicker` which detects network changes and then restarts the daemons automatically.  This is the code that relates to it.

You can stop the apiservice-kicker like this. `sudo systemctl stop snap.microk8s.daemon-apiserver-kicker.service`.  but this service restarts when there is an upgrade or when you do `microk8s.stop` or `microk8s.start`.

**Comment by ktsakalozos** [comment]
Just to add here, that the `apiservice-kicker` is needed in cases where you are for example on your laptop and you switch places and getting different IPs.

**Comment by andrenarchy** [comment]
Thank you so much! I ended up adding `--bind-address=0.0.0.0` to the `kube-apiserver` config. The `apiserver-kicker` doesn't do anything if it's present. I'm not sure why the `apiserver-kicker` is actually needed because `0.0.0.0` is the default address anyway so it just listens on all interfaces and no restart should be needed.

**Comment by balchua** [comment]
@andrenarchy as far as i know the `apiservice-kicker` does a bit more.  For one you can add another fqdn and it will automatically create certificates so users can access them through that fqdn.
