### ISSUE TITLE
microk8s is not running

### ISSUE THREAD

**Issue by davix** [ubuntu/microk8s#535]
> microk8s.status
> microk8s is not running. Use microk8s.inspect for a deeper inspection.

> microk8s.kubectl get no
> No resources found.
> 
> 

> microk8s.inspect
> Inspecting services
>  Service snap.microk8s.daemon-containerd is running
>  Service snap.microk8s.daemon-apiserver is running
>  Service snap.microk8s.daemon-proxy is running
>  Service snap.microk8s.daemon-kubelet is running
>  Service snap.microk8s.daemon-scheduler is running
>  Service snap.microk8s.daemon-controller-manager is running
>  Service snap.microk8s.daemon-etcd is running
>  Copy service arguments to the final report tarball
> Inspecting AppArmor configuration
> Gathering system info
>  Copy network configuration to the final report tarball
>  Copy processes list to the final report tarball
>  Copy snap list to the final report tarball
>  Inspect kubernetes cluster
> 
> 
> Building the report tarball
>  Report tarball is at /var/snap/microk8s/671/inspection-report-20190708_083500.tar.gz
The tar file is attached.

> microk8s.kubectl get all --all-namespaces
> 
> 
> NAMESPACE     NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
> default       service/default-http-backend   ClusterIP   10.152.183.148   <none>        80/TCP              123m
> default       service/kubernetes             ClusterIP   10.152.183.1     <none>        443/TCP             2d19h
> kube-system   service/heapster               ClusterIP   10.152.183.156   <none>        80/TCP              39m
> kube-system   service/kubernetes-dashboard   ClusterIP   10.152.183.94    <none>        443/TCP             39m
> kube-system   service/monitoring-grafana     ClusterIP   10.152.183.243   <none>        80/TCP              39m
> kube-system   service/monitoring-influxdb    ClusterIP   10.152.183.88    <none>        8083/TCP,8086/TCP   39m
> 
> NAMESPACE   NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
> default     daemonset.apps/nginx-ingress-microk8s-controller   0         0         0       0            0           <none>          123m
> 
> NAMESPACE     NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
> default       deployment.apps/default-http-backend             0/1     0            0           123m
> kube-system   deployment.apps/heapster-v1.5.2                  0/1     0            0           39m
> kube-system   deployment.apps/kubernetes-dashboard             0/1     0            0           39m
> kube-system   deployment.apps/monitoring-influxdb-grafana-v4   0/1     0            0           39m

> journalctl -f -u snap.microk8s.daemon-kubelet
> -- Logs begin at Fri 2019-06-14 07:57:15 UTC. --
> Jul 08 08:48:15 bjapdp microk8s.daemon-kubelet[31079]: E0708 08:48:15.921469   31079 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: the server could not find the requested resource (ge
> t runtimeclasses.node.k8s.io)
> Jul 08 08:48:16 bjapdp microk8s.daemon-kubelet[31079]: E0708 08:48:16.002561   31079 kubelet.go:2248] node "bjapdp" not found
> Jul 08 08:48:16 bjapdp microk8s.daemon-kubelet[31079]: E0708 08:48:16.102700   31079 kubelet.go:2248] node "bjapdp" not found
> Jul 08 08:48:16 bjapdp microk8s.daemon-kubelet[31079]: E0708 08:48:16.122289   31079 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: the server could not find the requested resource (get servi
> ces)
> Jul 08 08:48:16 bjapdp microk8s.daemon-kubelet[31079]: E0708 08:48:16.202896   31079 kubelet.go:2248] node "bjapdp" not found
> Jul 08 08:48:16 bjapdp microk8s.daemon-kubelet[31079]: E0708 08:48:16.303100   31079 kubelet.go:2248] node "bjapdp" not found

Note: "bjapdp" is the hostname of my machine.
[inspection-report-20190708_083500.tar.gz](https://github.com/ubuntu/microk8s/files/3367495/inspection-report-20190708_083500.tar.gz)

**Comment by davix** [comment]
Even `sudo snap remove microk8s` and `sudo snap install microk8s --classic` won't fix this. Any workaround?

**Comment by ktsakalozos** [comment]
@davix can you please try two things?

First make sure the hostname `bjapdp` resolves to localhost or your IP. Can you share the result of `nslookup bjapdp` and the contents of your `/etc/hosts`? Can you also remove `docker.io` and `containerd.io` so we do not muddy the waters while we try to debug this?

Please attach a new `microk8s.inspect` tarball, because the one you attached above does not contain the apiserver logs.

Thanks.

**Comment by davix** [comment]
10.65.38.224 is bjapdp's IP. The docker.io is not removed yet.

> whuang@bjapdp:~$ ping bjapdp
PING bjapdp (10.65.38.224) 56(84) bytes of data.
64 bytes from bjapdp (10.65.38.224): icmp_seq=1 ttl=64 time=0.056 ms
64 bytes from bjapdp (10.65.38.224): icmp_seq=2 ttl=64 time=0.043 ms
64 bytes from bjapdp (10.65.38.224): icmp_seq=3 ttl=64 time=0.036 ms
64 bytes from bjapdp (10.65.38.224): icmp_seq=4 ttl=64 time=0.032 ms
^C
--- bjapdp ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3057ms
rtt min/avg/max/mdev = 0.032/0.041/0.056/0.012 ms

> whuang@bjapdp:~$ cat /etc/hosts
127.0.0.1       localhost.localdomain   localhost
::1             localhost6.localdomain6 localhost6
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

> whuang@bjapdp:~$ nslookup bjapdp
Server:         127.0.0.53
Address:        127.0.0.53#53
Non-authoritative answer:
Name:   bjapdp
Address: 10.65.38.224
Name:   bjapdp
Address: 172.18.0.1
Name:   bjapdp
Address: 172.17.0.1
;; Truncated, retrying in TCP mode.
Name:   bjapdp
Address: fe80::9618:82ff:fe7b:2dc4
Name:   bjapdp
Address: fe80::42:fdff:fe5b:4409
Name:   bjapdp
Address: fe80::42:20ff:fe71:43da
Name:   bjapdp
Address: fe80::48e:50ff:fe94:6d66
Name:   bjapdp
Address: fe80::8cdd:91ff:febd:2a35
Name:   bjapdp
Address: fe80::542b:edff:fe91:bdb5
Name:   bjapdp
Address: fe80::204e:ceff:fe85:b1cf
Name:   bjapdp
Address: fe80::a065:6fff:fe69:6ae4
Name:   bjapdp
Address: fe80::c09:deff:fe2f:4583
Name:   bjapdp
Address: fe80::a0eb:5fff:fec7:969a
Name:   bjapdp
Address: fe80::281a:baff:fe22:ec61
Name:   bjapdp
Address: fe80::809f:90ff:fefe:b782
Name:   bjapdp
Address: fe80::fc38:d4ff:fe35:3ee3
Name:   bjapdp
Address: fe80::9c28:6dff:fe7b:99d1
Name:   bjapdp
Address: fe80::4c6a:26ff:fea1:196f
Name:   bjapdp
Address: fe80::e8d3:b8ff:fe82:e0b5
Name:   bjapdp
Address: fe80::4cdd:c2ff:fe88:6488
Name:   bjapdp
Address: fe80::5c46:99ff:fe35:3a34
Name:   bjapdp
Address: fe80::1cbb:caff:fe3e:b3ac
Name:   bjapdp
Address: fe80::1414:a2ff:fe3c:1774
Name:   bjapdp
Address: fe80::d8c7:7fff:fef4:3101
Name:   bjapdp
Address: fe80::e0d8:a3ff:fe37:d8f1
Name:   bjapdp
Address: fe80::70a8:b3ff:fe87:81b3
Name:   bjapdp
Address: fe80::204f:35ff:fe54:52cc
Name:   bjapdp
Address: fe80::ac6c:10ff:feac:310c

> whuang@bjapdp:~$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster
Building the report tarball
  Report tarball is at /var/snap/microk8s/671/inspection-report-20190715_061756.tar.gz

[inspection-report-20190715_061756.tar.gz](https://github.com/ubuntu/microk8s/files/3391022/inspection-report-20190715_061756.tar.gz)

**Comment by davix** [comment]
[inspection-report-20190724_032652.tar.gz](https://github.com/ubuntu/microk8s/files/3424889/inspection-report-20190724_032652.tar.gz)
This is the info for this request: 
> do a remove and reinstall, leave the deployment for 5 minutes and attach a microk8s.inspect tarball to the issue

https://kubernetes.slack.com/archives/CAUNWQ85V/p1563883383012700?thread_ts=1563166913.105000&cid=CAUNWQ85V

**Comment by ktsakalozos** [comment]
For the future visitor.

The following error was int he logs showing that the node could not register with the api server.
```
Jul 24 06:34:25 bjapdp microk8s.daemon-kubelet[50302]: I0724 06:34:25.217144   50302 kubelet_node_status.go:72] Attempting to register node bjapdp
Jul 24 06:34:25 bjapdp microk8s.daemon-kubelet[50302]: E0724 06:34:25.217722   50302 kubelet_node_status.go:94] Unable to register node "bjapdp" with API server: the server could not find the requested resource (post nodes)
Jul 24 06:34:25 bjapdp microk8s.daemon-kubelet[50302]: E0724 06:34:25.217728   50302 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"bjapdp.15b4444c53b6ec14", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"bjapdp", UID:"bjapdp", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node bjapdp status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"bjapdp"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf461cdc4cf0c214, ext:20530609908, loc:(*time.Location)(0x781d740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf461cdc4cf0c214, ext:20530609908, loc:(*time.Location)(0x781d740)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'the server could not find the requested resource (post events)' (will not retry!)
```

It turns out kubelet was picking up a rather outdated version of docker. This version is not in the official repositories. If you see this error double check that the repository you get docker from is the one matching your distribution (look in `/etc/apt/sources.list`).

Thank you @davix for being available in debugging this. Feel free to reopen the issue if you need more help.

**Comment by gajen0981** [comment]
@ktsakalozos -- I have similar issue. Any pointers?

`Unable to register node "<REDACTED>" with API server: Post https://<REDACTED>:16443/api/v1/nodes: dial tcp <REDACTED>:16443: connect: connection refused`
