### ISSUE TITLE
Unable to connect to shell in running pod

### ISSUE THREAD

**Issue by jgolio** [ubuntu/microk8s#536]
[inspection-report-20190708_102035.tar.gz](https://github.com/ubuntu/microk8s/files/3368968/inspection-report-20190708_102035.tar.gz)
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

Symptom of problem: 

root@ubuntu1604:~/k8s# kubectl run -it --rm --restart=Never alpine --image=alpine sh
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: error dialing backend: dial tcp 10.141.56.42:10250: i/o timeout
pod "alpine" deleted
Error from server: Get https://ubuntu1604:10250/containerLogs/default/alpine/alpine: dial tcp 10.141.56.42:10250: i/o timeout

**Comment by jgolio** [comment]
I get the same sort of I/O timeout error attempting to get the logs from daemon sets, pods or replica sets. I'm guessing there is something very fundamentally wrong with my configuration.

**Comment by jgolio** [comment]
I don't understand why the IP address is 10.141.56.42 when the Cluster IP  for the backend looks like it is 10.152.183.91. Where is this 10.141 address coming from? I don't see it anywhere in any of my configuration.

**Comment by ktsakalozos** [comment]
Hi @jgolio, indeed the 10.141.x.y network is not used/setup by MicroK8s.

Is it possible you have another kubeconfig file under ~/.kube ? is `kubectl` an alias to `microk8s.kubectl`? Can you try to reproduce the error with `microk8s.kubectl` so we are certain we are talking to K8s setup by MicroK8s?

**Comment by jgolio** [comment]
Yes, kubectl is an alias to microk8s.kubectl. I used "snap alias microk8s.kubectl kubectl" to create the alias. I just tried it again, explicitly calling microk8s.kubectl and I get exactly the same results.

**Comment by jgolio** [comment]
I just tried upgrading to 1.15/stable and the same problem exists. Just FYI

**Comment by ktsakalozos** [comment]
Would it be possible to `apt-get remove docker.io  containerd.io` to make sure we do not have any clashes?

**Comment by jgolio** [comment]
Surely, let me give that a try. I did not install containerd.io so I should only have to remote docker.io

**Comment by jgolio** [comment]
Same problem after removing docker and containerd
Note that the same error, IP address and port number (which appears to be the port that kubelet is listening) on the i/o timeout is displayed when I try and get logs from running pods.

**Comment by jgolio** [comment]
Any update on this? This is really holding up my progress on getting a team of people to use microk8s for early development.

**Comment by ktsakalozos** [comment]
@jgolio I cannot reproduce this.

The 10.141.x.z smells like there is a VM involved. Is there a way for the hostname of the machine "ubuntu1604" to resolve to that IP? Can you share you `/etc/hosts` and the output of an `nslookup ubuntu1604`. I am thinking, that there might have been a VM with that IP and name at some point in the past.

Can you think of anything else about the host machine that may be related? Was this machine a ubuntu16.04 and got upgraded to 18.04?

**Comment by jgolio** [comment]
Yes, there is a VM involved. I'm running microk8s on an Ubuntu VM that started out as 16.04 and was upgraded to 18.04. I used "do-release-upgrade" to perform the upgrade. After the upgrade, I was having some DNS issues, so I Googled a few pages and found people were saying to do the following to fix DNS on 18.04, so I did these steps and things started working. 

"rm -f /etc/resolv.conf"
"ln -s /etc/resolvconf/resolv.conf.d/base /etc/resolv.conf"

I think you're on to something...

Here is my /etc/hosts, and ubuntu1604 is the IP which is being used incorrectly. 
root@ubuntu1604:~# cat /etc/hosts
127.0.0.1       localhost
10.141.56.42    ubuntu1604

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

Here is the output of nslookup:
root@ubuntu1604:~# nslookup ubuntu1604
Server:         10.199.227.16
Address:        10.199.227.16#53

** server can't find ubuntu1604: NXDOMAIN

**Comment by jgolio** [comment]
Also worth noting, the IP of my external Ethernet port is 10.199.197.159, which does not match what's in /etc/hosts for ubuntu1604 .

**Comment by jgolio** [comment]
Maybe all I need to do is update my /etc/hosts to have the correct IP (10.199.197.159)?

**Comment by jgolio** [comment]
So I modified my /etc/hosts to change the IP of ubuntu1604 to the correct IP, rebooted, and now the problem is gone. 

Thank you for all the help. I'm ready to close this issue, unless there is anything else you wish to have me do. Let me know.

**Comment by ktsakalozos** [comment]
Great to hear the issue is resolved. Cheers!
