### ISSUE TITLE
`kubectl delete ns -n <namespace> --all` deletes ALL namespaces

### ISSUE THREAD

**Issue by krichter722** [ubuntu/microk8s#540]
This has been reported and fixed upstream at https://github.com/kubernetes/kubernetes/issues/75706. I have nothing to add to the description:

```
What happened:
kubectl delete namespace --namespace=<namespace> --all deletes all namespaces in the cluster.

What you expected to happen:
The above command should throw an error since --namespace and --all are mutually exclusive commands.

How to reproduce it (as minimally and precisely as possible):
CAUTION: This might delete all namespaces in your cluster!
Execute the command kubectl delete namespace --namespace=<namespace> --all by replacing <namespace> to any of your namespace.

Anything else we need to know?:
None.
```

experienced with v1.15.0 (682) from snap channel 1.15/edge on Ubuntu 19.04
[inspection-report-20190710_205936.tar.gz](https://github.com/ubuntu/microk8s/files/3379029/inspection-report-20190710_205936.tar.gz)

**Comment by ktsakalozos** [comment]
Thank you for pointing this out @krichter722.

Since the fix is merged upstream we need to wait for it to be included in one of the upcoming upstream k8s releases. We do not patch the upstream binaries unless this is requested via a support contract.

**Comment by krichter722** [comment]
Not stale
