### ISSUE TITLE
services cannot communicate enabling istio inject

### ISSUE THREAD

**Issue by joergeb** [ubuntu/microk8s#541]
I'm havin issues when I enable `istio-injection`: seems the services can't communicate w/ each other any longer.

Please find attached the microk8s.inspect tarball

Any hints highly appreciated, thx
Joerg

```
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system info
  Copy network configuration to the final report tarball
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Inspect kubernetes cluster

 WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT 
```
[inspection-report-20190711_000336.tar.gz](https://github.com/ubuntu/microk8s/files/3379589/inspection-report-20190711_000336.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @joergeb, could you try to `sudo iptables -P FORWARD ACCEPT` ?

**Comment by joergeb** [comment]
And that's it? Just read the WARNING :smile: Cool, sry for inconvenience. Should I install `iptables-persistent` saving the change, or is persisting rather obstructive?

**Comment by ktsakalozos** [comment]
Yes, @joergeb you would install iptables-persistent to make this change permanent.
