### ISSUE TITLE
"unknown object type nil in kubernetesenv.spec" on istio addon

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#545]
Istio is sometimes giving me this error during `microk8s.enable istio`.
```
error: error validating "/snap/microk8s/x1/actions/istio/istio-demo-auth.yaml": error validating data: unknown object type "nil" in kubernetesenv.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

Based on https://github.com/istio/istio/issues/15130 it may need to be updated.

**Comment by ktsakalozos** [comment]
Here is an istio upgrade https://github.com/ubuntu/microk8s/tree/bug/fix-istio

**Comment by pavankumarkatakam** [comment]
Im getting this error, how to use the fix-istio branch

**Comment by ktsakalozos** [comment]
@pavankumarkatakam you can give it a try with `sudo snap install microk8s --edge` any feedback is much appreciated.
