### ISSUE TITLE
Enabling DNS from non-interactive shell in Ansible does not enable name resolution

### ISSUE THREAD

**Issue by lazzarello** [ubuntu/microk8s#549]
[inspection-report-20190715_214206.tar.gz](https://github.com/ubuntu/microk8s/files/3394324/inspection-report-20190715_214206.tar.gz)

I have an inventory that I manage through Ansible. I'm calling `microk8s.enable dns` via the Ansible `shell` module. This operation returns with success and my playbook completes without error. But after this all new pods cannot resolve any hostname, returning with the following error

```
# ping example.com
ping: example.com: Temporary failure in name resolution
# 
command terminated with exit code 2
```

If I log in via interactive SSH and manually run the same commands, all pods can resolve hostnames. The order of commands is

1. `microk8s.enable dns`
2. `microk8s.stop`
3. `microk8s.start`

My assumption is there are some environment variables that are not available when [this script is run in a non-interactive environment](https://github.com/ubuntu/microk8s/blob/4a1d2a7d17ddbebdad34418a78e981e4ee24680e/microk8s-resources/actions/enable.dns.sh).

**Comment by ktsakalozos** [comment]
@lazzarello the attached tarball is after or before the manual steps to enable dns?

We regularly use microk8s in scripts. Is it possible that there is not enough time between enabling dns and starting the additional pods? What is the state of the cluster when DNS is not working properly? Is the dns pod running ok? What is the output of `microk8s.kubectl get all --all-namespaces` at that point?

**Comment by lazzarello** [comment]
Thanks for the insights. I've narrowed this down to the Ansible `shell` module. I have migrated the same procedure I wrote about above to a small shell script and I call it with the Ansible `command` module. This seems to have fixed the DNS situation. I'll close this since it doesn't seem to relate to microk8s.
