### ISSUE TITLE
MicroK8s is not working with fluxcd 

### ISSUE THREAD

**Issue by sureshamk** [ubuntu/microk8s#556]
I did installation fluxcd (https://github.com/fluxcd/flux/blob/master/site/helm-get-started.md) with minikube it works well, But microk8s fails me . any idea why its happens 

Refer https://github.com/fluxcd/flux/issues/2262

**Comment by ktsakalozos** [comment]
Hi @sureshamk, I cannot reproduce the issue. See my reply at https://github.com/fluxcd/flux/issues/2262#issuecomment-514990791
