### ISSUE TITLE
Stability issues after running for 10+ days

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#557]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20190725_101331.tar.gz](https://github.com/ubuntu/microk8s/files/3429483/inspection-report-20190725_101331.tar.gz)

We appreciate your feedback. Thank you for using microk8s.
```
$ k get pod -n kube-system
NAME                                              READY   STATUS    RESTARTS   AGE
coredns-f7867546d-g8gwz                           1/1     Running   22         12d
heapster-v1.5.2-844b564688-q2slf                  4/4     Running   83         12d
hostpath-provisioner-58564cb894-c8kbx             1/1     Running   19         12d
kubernetes-dashboard-7d75c474bb-lxdp4             1/1     Running   69         12d
metrics-server-v0.2.1-5fd5cddd7-jrg77             2/2     Running   36         12d
monitoring-influxdb-grafana-v4-6b6954958c-2dlkg   2/2     Running   43         12d
```
And DNS doesn't work at all.

**Comment by ktsakalozos** [comment]
I am not sure if the service restarts are more than usual. I believe we need to examine each restart case by case. What is the uptime of the host machine?

**Comment by khteh** [comment]
I don't have the number now as I restarted my machine after reporting the issue. Will post here if it happens again.
