### ISSUE TITLE
Conflict between prometheos and metrics-server

### ISSUE THREAD

**Issue by avarf** [ubuntu/microk8s#562]
I wanted to monitor my cluster and pods and I decided to install the prometheos addon of the microk8s. I was able to see some of the metrics of the node but then I noticed that my auto scalers (hpa) not working and when I got `kubectl get hpa` I received ` <unknown>/75%`.

After some inspections and trial and error I found out the problem is promethous and after disabling it and later disabling and enabling metrics-server the auto-scalers started to work properly again. My question is, is there a conflict between microk8s addons? Because I have installed both promethous and metrics-server via `microk8s.enable` OR the problem is promethous and its components have a real conflict with metrics-server? My next question is how can I solve this?

**Comment by ktsakalozos** [comment]
Hi @avarf 

We have seen this issue before (https://github.com/ubuntu/microk8s/issues/509#issuecomment-502677469). There is a clash of the two add-ons (ahttps://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/metrics-server.yaml and https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions/prometheus)

**Comment by avarf** [comment]
Thanks for the answer.
Does it mean that the conflict is just limited to microk8s add-ons or even if I install promethous via helm I will face the same situation?

**Comment by ktsakalozos** [comment]
We did not write those manifests ourselves, we have taken them from upstream. It is a possible that even if you get prometheus from upstream you will run into the same issue, but you need to try this approach to find out. I would be grateful if you dropped a line here with the solution you followed so we can update the manifests we use in MicroK8s (or you can submit a PR).

**Comment by avarf** [comment]
Because I have other priorities I didn't want to spend a lot of time on a monitoring system and I wanted something that works out of the box but now I will return to it later and if I solved it I will post the result here.

**Comment by avarf** [comment]
Hi again,
Just wanted to let you know that I installed prometheos via its helm chart and everything is good and working.
I followed this link: https://medium.com/@at_ishikawa/install-prometheus-and-grafana-by-helm-9784c73a3e97 and the only change that I made was creating my own prometheus-values.yaml:
```yaml
alertmanager:
  persistentVolume:
    enabled: false

server:
  persistentVolume:
    enabled: false
```
And I installed it with this command:
```
helm install --name prometheus stable/prometheus -f prometheus-values.yaml
```
I didn't check your manifests but I noticed two changes:
- Microk8s addon installs prometheus in a separate namespace (I don't think this is important)
- If I remember correctly Microk8s prometheus addon installs its own metrics-server but prometheus helm dosn't install a metrics-server and it uses kube-state-metrics:
```
prometheus-alertmanager-65f49796f5-gfs5d
prometheus-kube-state-metrics-64f766f4cd-m7754
prometheus-node-exporter-2dtb5
prometheus-pushgateway-7bfc59b475-pq6wr
prometheus-server-6f6975d889-5vpcn
```
I hope these can help.
