### ISSUE TITLE
RBAC seems not be working

### ISSUE THREAD

**Issue by dwm66** [ubuntu/microk8s#565]
I seem not to be able to get RBAC running...

Here what i did up to now:
- microk8s.enable rbac
- fixed some rights issue with coreDNS
- added rights for tiller

Nevertheless, RBAC is simply unfunctional. 
I tried to follow instructions from https://istio.io/docs/ops/security/debugging-authorization/
which causes 
`$ kubectl get clusterrbacconfigs.rbac.istio.io --all-namespaces
error: the server doesn't have a resource type "clusterrbacconfigs"`

while looking at the logs returns
`$ kubectl logs $(kubectl -n istio-system get pods -l istio=pilot -o jsonpath='{.items[0].metadata.name}') -c discovery -n istio-system | grep rbac
2019-07-24T07:12:33.949137Z	info	registering for apiVersion rbac.istio.io/v1alpha1
2019-07-29T13:17:23.748102Z	debug	rbac	disabled, no RbacConfig
2019-07-29T13:17:23.757610Z	debug	rbac	disabled, no RbacConfig
`

Any help would be highly appreciated

[fixes.zip](https://github.com/ubuntu/microk8s/files/3442625/fixes.zip)

Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
[inspection-report-20190729_154743.tar.gz](https://github.com/ubuntu/microk8s/files/3442597/inspection-report-20190729_154743.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @dwm66 

Is it possible you give the candidate channel a try?
```
sudo snap install microk8s --classic --channel=candidate
```

We have upgraded istio there and is going to reach stable soon (this week). Thanks.

**Comment by dwm66** [comment]
Thanks, that was very helpful! With the candidate channel it now seems to be ok.
