### ISSUE TITLE
gcloud auth configure-docker is not working with microk8s

### ISSUE THREAD

**Issue by spectordotan** [ubuntu/microk8s#566]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20190729_185249.tar.gz](https://github.com/ubuntu/microk8s/files/3443106/inspection-report-20190729_185249.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

**Comment by ktsakalozos** [comment]
Hi @spectordotan be aware that MicroK8s packages its own container runtime. I do not think configuring this runtime is something other tools can do. If you tell me what you need to set I may be able to show you how to do it.
