### ISSUE TITLE
Enabling SSL passthrough with nginx ingress

### ISSUE THREAD

**Issue by ccarv** [ubuntu/microk8s#570]
I am trying to deploy a backend service that communicates over TCP and supports native TLS communication. I have installed the ingress nginx via the `microk8s.enable` command and couldn't find any authoritative documentation on enabling SSL passthrough. So I've manually edited the daemon set via the Kubernetes dashboard and modified the controller with the following args:

```json
      "spec": {
        "containers": [
          {
            "name": "nginx-ingress-microk8s",
            "image": "quay.io/kubernetes-ingress-controller/nginx-ingress-controller-amd64:0.24.1",
            "args": [
              "/nginx-ingress-controller",
              "--default-backend-service=$(POD_NAMESPACE)/default-http-backend",
              "--configmap=$(POD_NAMESPACE)/nginx-load-balancer-microk8s-conf",
              "--publish-status-address=127.0.0.1",
              "--enable-ssl-passthrough"
            ],
```

Looking at the log for the daemon set, it appears it took the `--enable-ssl-passthrough` argument.

```
I0730 19:37:09.468439       6 nginx.go:727] Starting TLS proxy for SSL Passthrough
I0730 19:37:09.468601       6 leaderelection.go:217] attempting to acquire leader lease  default/ingress-controller-leader-nginx...
I0730 19:37:09.468707       6 nginx.go:311] Starting NGINX process
I0730 19:37:09.470673       6 controller.go:170] Configuration changes detected, backend reload required.
I0730 19:37:09.482273       6 status.go:86] new leader elected: nginx-ingress-microk8s-controller-lmj6d
I0730 19:37:09.707562       6 controller.go:188] Backend successfully reloaded.
```

I know there is further configuration needed to listen on port 443 for the actual backend ingress service but I am unsure how to do this in MicroK8s.
![Capture1](https://user-images.githubusercontent.com/2898521/62169891-99e37e00-b2f7-11e9-837f-31e085dee70f.PNG)

Is there a way to modify the configuration for ingress nginx that is installed via the `microk8s.enable` feature?

I can provide more information such as my ingress rules if necessary.

**Comment by balchua** [comment]
@feered I don't the ingress yaml is modifiable.  There's an issue https://github.com/ubuntu/microk8s/issues/465 to extend configuration of addons.  

For the meantime, i think doing a `kubectl edit ds nginx-ingress-microk8s-controller` or grab that manifest and do a `kubectl apply -f modified-ingress.yaml` will be the way forward.

**Comment by feered** [comment]
@balchua This answers my question. Thank you.

**Comment by balchua** [comment]
@feered you can use your own ingress according to your needs.  In fact i use my own prometheus + grafana instead of the addon.  Coz i have a bunch of dashboards that i want to use which are not included as defaults.
