### ISSUE TITLE
Systemd reload causes some cadvisor metrics to stop being updated

### ISSUE THREAD

**Issue by taintedkernel** [ubuntu/microk8s#574]
Hello, I've been encountering a very unusual problem with my microk8s installation (and possibly cAdvisor).  It took me awhile to track down, but every few days the metric **container_cpu_usage_seconds_total** stops being updated - this happens whenever systemd is reloaded (automatically by my 18.04.2 server).  The metric is still present during Prometheus scraping, but my usual Grafana dashboards which plot a sum/rate no longer detect any change.

The only solution I found is to delete all the pods, then the metric starts updating once they are created.

Also possibly related, but I do not see any **container_network_receive_bytes_total** (or similar) metrics for any of my pods - these should be emitted, correct?

I'm not sure if this is microk8s-specific, but I did a pretty exhaustive search across anything k8s-related and have been unable to find a similar report (or solution).

Appreciate any help.

![broken-cadvisor-metrics](https://user-images.githubusercontent.com/352735/62337333-0b066b00-b489-11e9-8ab3-ed619f46fd44.jpg)

[inspection-report-20190801_182016.tar.gz](https://github.com/ubuntu/microk8s/files/3459269/inspection-report-20190801_182016.tar.gz)

**Comment by ktsakalozos** [comment]
This seems to be related to https://github.com/ubuntu/microk8s/issues/562 and https://github.com/ubuntu/microk8s/issues/509#issuecomment-502677469 . Unfortunately we did not had the chance to go through this issue yet.

**Comment by taintedkernel** [comment]
Thanks for pointing out, I would not have made the connection on my own.  FWIW, I also have Prometheus & Grafana installed via (slightly-customized) Helm charts and not the microk8s addon.  Will follow the other issues for updates.

**Comment by jtackaberry** [comment]
I can reliably reproduce this as well.  Host is Ubuntu 18.04.4 running microk8s 1.18.2 (however I've also observed this on 1.16 and 1.17).

Skipping the kubelet-integrated cAdvisor as the middle-man and looking at containerd directly with `crictl -r unix:///var/snap/microk8s/common/run/containerd.sock stats`, the problem does manifest there as well.  CPU and memory metrics stop incrementing after `systemctl daemon-reload` until the pod is restarted.

Given that, I don't believe it's related to #562.

**Comment by ktsakalozos** [comment]
@jtackaberry could you share the output of `dmesg`? Are there any apparmor denials?

**Comment by taintedkernel** [comment]
If it's any help, there are no apparmor denials that I see on my system.  I also tried the `crictl` test that @jtackaberry mentioned; see the same results: CPU is 0.00%

**Comment by taintedkernel** [comment]
@ktsakalozos is there any other information I can provide to help debug this further?

**Comment by taintedkernel** [comment]
@jtackaberry @ktsakalozos any updates?  The other linked issues claimed a resolution by reinstalling microk8s but I was able to repro this on the latest microk8s v1.20.0 with an entirely new host running Ubuntu 20.04.1, so I'm pretty sure it wasn't anything on my end.

**Comment by taintedkernel** [comment]
Just following up on this old issue, I think it's been resolved on my end for a few months now.  Can't say what changed for certain, maybe just a new microk8s version but either way I have not experienced this since March, if not earlier.  Will close this out and reopen if I see it again.
