### ISSUE TITLE
development: containerd dependency must be rebulit after microk8s changes

### ISSUE THREAD

**Issue by joestringer** [ubuntu/microk8s#586]
Every time I attempt to rebuild microk8s after making changes to the source tree, snapcraft complains that:

```
Sorry, an error occurred in Snapcraft:
Failed to reuse files from previous run: The 'pull' step of 'containerd' is out of date:
The source has changed on disk.
To continue, clean that part's 'pull' step by running `snapcraft clean containerd -s pull`.
```

Which must be resolved by removing the cached build of containerd.

I believe that this is because the source in the snapcraft.yaml lists containerd as depending on `.`, hence if any source changes locally here then it requires rebuilding containerd:

https://github.com/ubuntu/microk8s/blob/4d8a0856e66ce485631624ed0288af1076f18b98/snapcraft.yaml#L95

I think we should be able to update this or build it in a subdirectory to allow caching of this snap part to work?

**Comment by ktsakalozos** [comment]
Have you tried setting the source to something else? I see for example in https://github.com/rounak316/blazeRecon/blob/2442c19e88e19a8d1d17b35885baa5de7d272002/snapcraft.yaml#L43 the http URL is used.

I always build with `snapcraft cleanbuild`.

**Comment by joestringer** [comment]
I think that setting the http URL will work, it might just download it an extra time.

Doesn't `snapcraft cleanbuild` rebuild everything each time?

**Comment by joestringer** [comment]
For developing a plugin, @ktsakalozos pointed out this useful script that significantly reduces development cycles: ` sudo snap run --shell  microk8s.enable`. This provides the shell environment necessary to develop scripts under `microk8s-resources/actions`.
