### ISSUE TITLE
"linkerd-controller-" pod's "linkerd-proxy" container is not ready

### ISSUE THREAD

**Issue by ildella** [ubuntu/microk8s#591]
[inspection-report-20190811_153740.tar.gz](https://github.com/ubuntu/microk8s/files/3490105/inspection-report-20190811_153740.tar.gz)
A fresh install on latest Ubuntu:

```
microk8s.enable linkerd
microk8s.linkerd check
[... all good ...]
√ can query the control plane API

linkerd-api
-----------
× control plane pods are ready
    The "linkerd-controller-56b66f64df-czlg7" pod's "linkerd-proxy" container is not ready
    see https://linkerd.io/checks/#l5d-api-control-ready for hints
```

If I follow some of the tips at the hinted link, like

```
kubectl -n linkerd port-forward svc/linkerd-prometheus 9090
```

Only 1/8 linkerd-proxy is actually up. 
Only 1/8 linkerd-controller
And grafana is also down. 

If I then install the dashboard, it refuses to open, saying `Waiting for control plane to become available`

Finally if I follow the [linkerd Getting Started](https://linkerd.io/2/getting-started/), when I run

I get to

```
$ linkerd -n emojivoto stat deploy
linkerd -n emojivoto stat deploy
Error: StatSummary API error: Get http://linkerd-prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=histogram_quantile%280.95%2C+sum%28irate%28response_latency_ms_bucket%7Bdirection%3D%22inbound%22%2C+namespace%3D%22emojivoto%22%7D%5B1m%5D%29%29+by+%28le%2C+namespace%2C+deployment%29%29: dial tcp: i/o timeout
```

This is apparently "random" as in a different install on another machine with same OS version I did not get this issue.

Finally if

**Comment by balchua** [comment]
@ildella i saw some error related to mount volume setup.  Can you check if you have enough storage available for your microk8s?
