### ISSUE TITLE
Microk8s dies after installing microstack

### ISSUE THREAD

**Issue by davigar15** [ubuntu/microk8s#596]
I am experiencing an issue with microk8s and microstack. When I install microk8s after installing microstack, there are no problems. But, if I have already installed microk8s with a few pods deployed; and later I install microstack, microk8s and all the pods die.

I'm using juju to deploy the kubernetes pods. And I completely lose connection with the juju k8s controller after installing microstack. None of the pods report any error, BUT I cannot log into any one.

These are the logs I'm getting from all the pods, when doing a `kubectl describe pods`

```
Events:
  Type     Reason      Age                  From               Message
  ----     ------      ----                 ----               -------
  Warning  Unhealthy   20m                  kubelet, microosm  Readiness probe errored: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/common/run/containerd.sock: connect: no such file or directory"
  Warning  Unhealthy   20m                  kubelet, microosm  Liveness probe errored: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /var/snap/microk8s/common/run/containerd.sock: connect: no such file or directory"
  Warning  FailedSync  4m4s (x47 over 14m)  kubelet, microosm  error determining status: rpc error: code = Unknown desc = failed to get sandbox ip: check network namespace closed: remove netns: remove /var/run/netns/cni-ab4886e9-bab0-cd33-7994-f9a91fc5364c: device or resource busy
```

Also I tried restarting microk8s and rebooting the machine. It didn't work. But after rebooting, all pods went into Unknown state, and from that state to CreateContainerError.

[inspection-report-20190814_155911.tar.gz](https://github.com/ubuntu/microk8s/files/3502298/inspection-report-20190814_155911.tar.gz)

**Comment by ktsakalozos** [comment]
@petevg any ideas?

**Comment by petevg** [comment]
@ktsakalozos I'd guess that microstack is doing one of three things:

1) microstack might be grabbing a port that microk8s uses to communicate with the world. microstack grabs port :80, for example. (One of the tasks on our roadmap is to make those ports configurable.)
2) microstack might be messing with microk8s' bridge. Microstack creates and controls br-ex via Openvswitch. If microk8s is also using the name br-ex, then they probably wind up arguing over that bridge's configuration.
3) microstack creates and populates the 10.20.20.0/24. If microk8s is also using this cidr, they may be arguing over gateways and addresses.

Do any of those sound plausible?

**Comment by ktsakalozos** [comment]
Thanks @petevg. Port 80 will be an issue in setups where `microk8s.enable ingress` is used. In the issue https://github.com/ubuntu/microk8s/issues/602 we show how to change the port ingress is used.

The bridge microk8s is using is cbr0 so we are safe there.

The subnets used for pods is the 10.1.1.0/16. So that should be ok too. Something else must be wrong.

**Comment by AdamIsrael** [comment]
Adding a bit more info, as I've been testing this scenario myself.

Setup: I'm watching `juju status` and `kubectl get pods -n osm`. When microstack's configure hook is running, I first receive the error from `juju status`: `ERROR connection is shut down`.

I've seen that error before, usually when the Juju API server is down.

Output of `kubectl describe pod/controller-0 -n controller-osm-on-k8s`:
https://pastebin.ubuntu.com/p/PCWH6h3cKb/

Based on that log, it seems like the mongodb container isn't starting. I don't see anything in microstack's configure hook that seems like it would obviously conflict.

A restart of microk8s doesn't restore the controller pod to a functional state. Neither has removing microstack and both restarting microk8s and rebooting the machine.

Testing was done with the candidate channel of microstack, but I'll retry with candidate.

**Comment by ktsakalozos** [comment]
It looks as if there is a clash in the confinement but I am not sure why:
```
Aug 14 15:42:17 microosm microk8s.daemon-kubelet[5873]: E0814 15:42:17.046606    5873 kuberuntime_manager.go:903] PodSandboxStatus of sandbox "deecc12d92f67411020a2c928cc2edc847fc2f1de4de19b65d79f7c8e9a2f1d7" for pod "ui-k8s-5bb45b9b8-7bgmn_osm(c3a7bd5a-be9f-11e9-b51d-fa163ead2629)" error: rpc error: code = Unknown desc = failed to get sandbox ip: check network namespace closed: remove netns: remove /var/run/netns/cni-8b87d453-70d4-c38b-73a3-2da54ca6a77b: device or resource busy
```

**Comment by davigar15** [comment]
@ktsakalozos @petevg Hello guys!

I have tested the new microstack version with the ''sudo microstack.init --auto` function. (edge/rocky channel).

Now, this issue is not happening. I mean that when the microstack is installed, the microk8s pods are not going down.

BUT, when rebooting the machine, I'm getting the same issue. ` remove /var/run/netns/cni-8b87d453-70d4-c38b-73a3-2da54ca6a77b: device or resource busy` on all the pods.

It's important to mention that if I reboot without microstack installed, the pods inside microk8s raise up successfully.

Let me know if there's news on this

**Comment by petevg** [comment]
@davigar15 the behavior you're seeing is expected. After you run .init, microstack basically behaves in the same way that it was behaving before. It's grabbing a port, or doing something else that is interfering w/ k8s.

The next steps w/ the init script are to make it accept a config flie, which can set ports and the like.

If you have some insight into which ports need to be configurable, please drop that here, and I'll make sure that they are!

**Comment by davigar15** [comment]
That’s great, but do you think the ports are the ones responsible of this
conflict? It seems like that is happening because some networking conflict
(according to the output).

Thanks
David

**Comment by petevg** [comment]
@davigar15 Just re-reviewed the conversation. Yes, I think that you at @ktsakalozos are correct, in that it's not a port issue.

Unfortunately, I don't know what the issue is. k8s and microstack are arguing over some resource, but I'm not clear why they're respective virtualization layers aren't keeping them separate ...

**Comment by sjmudd** [comment]
Hi,

I bumped into this thread while trying to install microstack on a box with microk8s installed.
In my case this is on Ubuntu 19.10.

The problem is similar but not the same but not sure if the info below may help so posting in case it does.

I am playing with microk8s.  microk8s has been working fine and I just tried installing microstack following the link [here](https://ubuntu.com/openstack/install#workstation-deployment) and see that the install fails at this point:

```
$ sudo snap install microstack --classic --edge
...
$ sudo microstack.init
Do you want to setup clustering? (yes/no) [default=no] > 
2019-12-05 19:17:49,681 - microstack_init - INFO - Configuring networking ...
2019-12-05 19:17:50,276 - microstack_init - INFO - Setting up ipv4 forwarding...
2019-12-05 19:17:50,832 - microstack_init - INFO - Opening horizon dashboard up to *
2019-12-05 19:17:51,341 - microstack_init - INFO - Waiting for RabbitMQ to start ...
Waiting for 10.20.20.1:5672
[ gets stuck here ]
```
The box is idle (as even microk8s is not very busy) but I do notice when checking for the port 5672 the following:

```
$ netstat -an | grep 5672
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN     
tcp        0      1 A.B.C.D:55562           10.20.20.1:5672         SYN_SENT   
tcp6       0      0 :::5672                 :::*                    LISTEN     
$
```
So what looks wrong here is that the init script is trying to connect on IPv4 and the RabbitMQ listener is only listening on IPv6.

The primary IPv4 interface shows:

```
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet A.B.C.D  netmask 255.255.255.0  broadcast A.B.C.255
        inet6 fe80::c928:80e8:1b2a:d7b3  prefixlen 64  scopeid 0x20<link>
        ether 94:c6:91:a7:a1:2b  txqueuelen 1000  (Ethernet)
        RX packets 397129  bytes 534951857 (534.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 86418  bytes 8015033 (8.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0xaec00000-aec20000  
```
So IPv6 is configured but not with anything other than link local addresses.

So looks to me like a misconfiguration or expectation of networking setups etc.

Hope this helps.

Regards,

Simon
