### ISSUE TITLE
Can finish install kubeflow

### ISSUE THREAD

**Issue by ycheng** [ubuntu/microk8s#597]
OS: Ubuntu 18.04.3 LTS
GPU: Quadro P400 x 2
Procedure: https://ubuntu.com/kubeflow/install
 - microk8s 1.14.5, r744
 - gpu enable

After run install-kubeflow.sh, can't finish kubectl apply --validate=false -f default.yaml, it failed at something like

https://pastebin.ubuntu.com/p/wGg6ZMkC66/
> unable to recognize "default.yaml": no matches for kind "CompositeController" in version "metacontroller.k8s.io/v1alpha1"
> unable to recognize "default.yaml": no matches for kind "Application" in version "app.k8s.io/v1beta1"

Per my test, it can finish running once. I try to reset microk8s and wait for all kube-system pods running, but still can reproduce this.

The output of microk8s.inspect attached as follow:

[inspection-report-20190815_061551.tar.gz](https://github.com/ubuntu/microk8s/files/3503561/inspection-report-20190815_061551.tar.gz)

**Comment by ktsakalozos** [comment]
@carmine may be able to offer some insight into this issue. Two days ago I tested these scripts and they worked (but did not work for @ycheng). Today I see these scripts were updated to use v1.15 and the deployment is failing for me with:
```
+ ks show default -c metacontroller -c application
ERROR find objects: lib/ksonnet-lib/v1.15.2/k8s.libsonnet:17681:93-94 Unknown variable: x

          "withX-Kubernetes-Embedded-Resource":: self + { "x-kubernetes-embedded-resource": x-kubernetes-embedded-resource },
```

Not sure why. We should bring these scripts over at the MicroK8s repository under a `microk8s.addon` script so they go through our CI process as we release MicroK8s/updates.

**Comment by ycheng** [comment]
try again with 1.14 on another machine, and it works fine. I'll re-test on the original one (which have two gpu installed) latter when it's available.

For 1.15, also saw the same issue.

Per check, it has the same error as https://github.com/kubeflow/kubeflow/issues/3544.

**Comment by ycheng** [comment]
if use command KUBEFLOW_VERSION=0.6.1 ./install-kubeflow.sh with microk8s 1.15, it eventurally failed at

+ ks generate metacontroller metacontroller
INFO Writing component at '/home/ycheng/git/ycrepo/kubeflow-canonical/kubeflow-tools/mykubeflow/ks_app/components/metacontroller.jsonnet' 
+ ks generate profiles profiles
ERROR failed to instantiate prototype "io.ksonnet.pkg.profiles". The following required parameters are missing:
--admin=<admin> cluster admin user id [type: string]

**Comment by ycheng** [comment]
Just manage to run kubeflow 0.6 on microk8s, key points

1. enable istio, dns, storage and dashboard.
2. kustomize version: 3.1.0
   kfctl: 0.6.1 (after downloaded, it show version v0.6.1-rc.2-1-g3a37cbc6)
3. I downloaded kfctl_k8s_istio.yaml and comment out two line

   # Istio install. If not needed, comment out istio-crds and istio-install.
-  - istio-crds
-  - istio-install
+  #- istio-crds
+  #- istio-install

4. the path for config file need to be URL, so I use file:///home/...../kfctl_k8s.yaml
5. the main dashboard run in k8s service "centraldashboard".

**Comment by ycheng** [comment]
per double checking, the dashboard for kubeflow 0.6 look good, but click into detail show nothing.
Try to do it again today, some archive files chage from the server. It seems more time to converge is needed.

**Comment by carmine** [comment]
We are re-validating the install steps for kubeflow 0.6.1 now and will update this ticket / the site accordingly.

**Comment by ycheng** [comment]
steps in https://ubuntu.com/kubeflow/install works, with two minor change.

1. export VERSION='curl ...'
     is not working because the quote is not correct. Maybe change to
     export VERSION=$(curl ....)

2. as "kfctl apply all -V", it complains namespace kubeflow-anonymous does not exists.
    manually create it, then it works. Not sure why.
    command to create the namespace: "kubectl create namespace kubeflow-anonymous"

**Comment by ycheng** [comment]
for the  kubeflow-anonymous, wait longer with create it works.

However, after finish installation, can't create notebook. There is not corresponding pod created, while it works fine as using microk8s 1.14 + kubeflow 0.5.

**Comment by ycheng** [comment]
I can successfully create kubeflow_notebook if I select namespace kubeflow-anonymous.

Will check kubeflow if this is a "feature" instead of a "bug".

**Comment by ycheng** [comment]
ref: https://github.com/kubeflow/kubeflow/issues/4156

**Comment by ktsakalozos** [comment]
> steps in https://ubuntu.com/kubeflow/install works, with two minor change

/cc ammarn911

**Comment by ammarn911** [comment]
thanks @ktsakalozos , I'll update the installation.

**Comment by kschroed** [comment]
I've tried with the suggested two changes above from @ycheng but getting exit status of

Error: couldn't apply KfApp:  (kubeflow.error): Code 500 with message: kfApp Apply failed for kustomize:  (kubeflow.error): Code 500 with message: couldn't create resources from application Error: no matches for kind "Application" in version "app.k8s.io/v1beta1"

This is on microk8s 1.15.3 and kubeflow v0.6.2

**Comment by ycheng** [comment]
@kschroed I try again today and it still works. my output of snap list are
```
Name      Version  Rev   Tracking  Publisher   Notes
core      16-2.41  7713  stable    canonical✓  core
microk8s  v1.15.3  826   stable    canonical✓  classic
```
I also put all those steps into script in https://github.com/ycheng/microk8s-kubeflow-install.
It's the same with those on the web page with minor enhancement. To use it:
```
$ ./microk8s-install.bash
# logout and login to get microk8s group.
$ ./kubeflow-init.sh
$ ./kubeflow-apply.sh
```
Sorry that I don't know why it failed on your side based on the log you provided.

**Comment by kschroed** [comment]
I ran through it again and it got past stage but on to hanging with no kubflow-anonymous namespace, which after I created manually it then completed and is functional with the exception of argo runtime working with containerd.

**Comment by ycheng** [comment]
@kschroed please checkhttps://github.com/kubeflow/kubeflow/issues/40900 for kubeflow-anonmous.

Per current status, I believe we can close this bug. Feel free to open another for other issues.
