### ISSUE TITLE
unable to start kubernetes-dashboard

### ISSUE THREAD

**Issue by materia2021** [ubuntu/microk8s#601]
Ubuntu 18.4
Microk8s 15.2

tried enabling dashboard via microk8s.enable dns dashboard

kube-system   kubernetes-dashboard-7d75c474bb-wpwtb             0/1     ImagePullBackOff   0 
"Failed to pull image \"k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1\": rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1\": failed reading status of resume write: stat /var/snap/microk8s/common/var/lib/containerd/io.containerd.content.v1.content/ingest/6547e72b04ff8cae1a54f33fb7c3543c82aab966ce8258a797a58223e9d6a67d/data: no such file or directory: not found"

[inspection-report-20190817_202722.tar.gz](https://github.com/ubuntu/microk8s/files/3511996/inspection-report-20190817_202722.tar.gz)

**Comment by ktsakalozos** [comment]
This is odd. I do not have a good explanation for what you are seeing. Is this reproducible on your system? Does it happen all the time? Could it be a temporary network failure? Do you see this failure to pull images for other add-ons? Are you behind a firewall/proxy? Anything else you can think of about your setup that might be relevant?

**Comment by materia2021** [comment]
> This is odd. I do not have a good explanation for what you are seeing. Is this reproducible on your system? Does it happen all the time? Could it be a temporary network failure? Do you see this failure to pull images for other add-ons? Are you behind a firewall/proxy? Anything else you can think of about your setup that might be relevant?

not behind any firewall or proxy, it's the only image that can't be pulled. other services are working as expected

**Comment by starpit** [comment]
we are seeing this error quite routinely when running in travis:

```
Failed to pull image "gcr.io/kubernetes-helm/tiller:v2.13.0": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/kubernetes-helm/tiller:v2.13.0": failed reading status of resume write: stat /var/snap/microk8s/common/var/lib/containerd/io.containerd.content.v1.content/ingest
```

two of them recently:

https://travis-ci.org/IBM/kui/jobs/602798055
https://travis-ci.org/IBM/kui/jobs/602798727

it's hard for me to tell whether this is a travis networking error or some issues with error handling in microk8s. perhaps a networking issue that microk8s incorrectly handles? e.g. something a retry would resolve?

**Comment by biiiipy** [comment]
Having the same issue and it's driving me crazy. I'm behind non-functioning NTLM proxy, so I preloaded all images into containerd. All other services work, but for dashboard it fails to pick up the image and tries to download it:
```failed to "StartContainer" for "kubernetes-dashboard" with ImagePullBackOff: "Back-off pulling image \"kubernetesui/dashboard:v2.0.0-rc5\""```

but I have the images:

```
microk8s.ctr images ls

REF                                                                     TYPE                                       DIGEST                                                                  SIZE      PLATFORMS   LABELS                      
docker.io/cdkbot/addon-resizer-amd64:1.8.1                              application/vnd.oci.image.manifest.v1+json sha256:eac35e52e9b46fe4df1bd4c5b58f17b27dcfe2a20e6057ca0e44191254ab5262 31.7 MiB  linux/amd64 io.cri-containerd.image=managed
docker.io/coredns/coredns:1.6.6                                         application/vnd.oci.image.manifest.v1+json sha256:5dd0dbc916cbe4fe4223410e6d7c646211cb7d0a250fb65d4fda34051a0461be 39.1 MiB  linux/amd64 io.cri-containerd.image=managed
docker.io/kubernetesui/dashboard:v2.0.0                                 application/vnd.oci.image.manifest.v1+json sha256:5ed1963e8384b9bf0c784d376a6405c89d2d5bd427bdbe83387ec6603e883bc8 214.2 MiB linux/amd64 io.cri-containerd.image=managed
docker.io/kubernetesui/dashboard:v2.0.0-rc5                             application/vnd.oci.image.manifest.v1+json sha256:f3f4a72f7918feab521709d1be401e3aac60f326e73a1d32a3d04e0267ef810f 121.1 MiB linux/amd64 io.cri-containerd.image=managed
docker.io/kubernetesui/metrics-scraper:v1.0.2                           application/vnd.oci.image.manifest.v1+json sha256:7d800b187b27330b1a5af8a7898b2a562c2b51af7d1284ab27c6d31a4a1107c9 38.3 MiB  linux/amd64 io.cri-containerd.image=managed
k8s.gcr.io/heapster-amd64:v1.5.2                                        application/vnd.oci.image.manifest.v1+json sha256:5aff17313bfec94448bc8704db524cdf07f98775d57a43dafc2f02bdea2b15a4 71.8 MiB  linux/amd64 io.cri-containerd.image=managed
k8s.gcr.io/heapster-grafana-amd64:v4.4.3                                application/vnd.oci.image.manifest.v1+json sha256:bfc2809322fb5cb284e8833188ae01c271ff90ebc6ced8c271995e861330624e 147.5 MiB linux/amd64 io.cri-containerd.image=managed
k8s.gcr.io/heapster-influxdb-amd64:v1.3.3                               application/vnd.oci.image.manifest.v1+json sha256:4a21b40968e817d33aad519bffdf0c379be3f520beda6b72a94632ce094c3aa9 12.2 MiB  linux/amd64 io.cri-containerd.image=managed
k8s.gcr.io/pause:3.1                                                    application/vnd.oci.image.manifest.v1+json sha256:3efe4ff64c93123e1217b0ad6d23b4c87a1fc2109afeff55d2f27d70c55d8f73 728.9 KiB linux/amd64 io.cri-containerd.image=managed
````

**Comment by biiiipy** [comment]
OK, it seems that the problem is that dashboard yaml has:
```imagePullPolicy: Always```

While others have:
```imagePullPolicy: IfNotPresent```
