### ISSUE TITLE
ingress CrashLoopBackOff

### ISSUE THREAD

**Issue by SamChb72** [ubuntu/microk8s#602]
Hello,
May be this is duplicate of #215
I have crash problem with ingress... I've never see it Running, it's always in CrashLoopBackOff status
`
~$ microk8s.kubectl get all --all-namespaces
NAMESPACE            NAME                                                  READY   STATUS             RESTARTS   AGE
container-registry   pod/registry-6c99589dc-9dn9c                          1/1     Running            0          65m
default              pod/default-http-backend-5d5ff5d4f5-gcs22             1/1     Running            0          65m
default              pod/nginx-ingress-microk8s-controller-km4vc           0/1     CrashLoopBackOff

   17         65m
kube-system          pod/coredns-f7867546d-6d2zq                           1/1     Running            0          66m

`
[inspection-report-20190818_160837.tar.gz](https://github.com/ubuntu/microk8s/files/3513381/inspection-report-20190818_160837.tar.gz)

**Comment by SamChb72** [comment]
`
Aug 18 20:48:27 brocker systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 18 20:48:27 brocker kubelet[23398]: F0818 20:48:27.521886   23398 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 18 20:48:27 brocker systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 18 20:48:27 brocker systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 18 20:48:29 brocker microk8s.daemon-kubelet[24958]: E0818 20:48:29.455537   24958 pod_workers.go:190] Error syncing pod acc94072-59bc-4a4b-9342-3eacc92a0530 ("nginx-ingress-microk8s-controller-km4vc_default(acc94072-59bc-4a4b-9342-3eacc92a0530)"), skipping: failed to "StartContainer" for "nginx-ingress-microk8s" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=nginx-ingress-microk8s pod=nginx-ingress-microk8s-controller-km4vc_default(acc94072-59bc-4a4b-9342-3eacc92a0530)"

`

**Comment by ktsakalozos** [comment]
Hi @SamChb72,

Is it possible you have another service listening on port 80? If you get the logs of the nginx controller pod with something similar to that: `microk8s.kubectl logs -n default pod/nginx-ingress-microk8s-controller-cr6bb` you should see the error: `F0818 14:04:25.771576       6 main.go:74] Port 80 is already in use. Please check the flag --http-port`.

Lets try that suggestion, `microk8s.kubectl edit -n default     ds/nginx-ingress-microk8s-controller` and under `spec->template->spec->containers->args` add ` - --http-port=8087` so as to tell the ingress controller to use another port for http.

**Comment by SamChb72** [comment]
Hello Konstantinos,
Yes, it's better with this 'edit' option. I could change the default ports and it goes better. Thank you very much :-)
