### ISSUE TITLE
puppet firewall ignore rules

### ISSUE THREAD

**Issue by hozmaster** [ubuntu/microk8s#605]
I'm planning install the microk8s to laptop which is managed by puppet fw module. Can you give guide what I have put ignore rules for iptables like 
...
    firewallchain { 'PREROUTING:nat:IPv4':
      purge  => true,
      ignore => [ 'DOCKER' ],
    } 
.. 
(As this is example from gist file found from this service.)

**Comment by ktsakalozos** [comment]
Hi @hozmaster 

I am not familiar with what needs to be defined here. I could give you an overview of how the networking in K8s works if that helps.

**Comment by hozmaster** [comment]
I did installed microk8s on a laptop which was already maintained by puppet and the fw module. 

After that I decided to install microk8s but I noticed micork8s wants asentaa iptables settings and puppet did clear them out .

So is possbile to defina that microk8s will not set the iptables rules and is I can read/use required rules at somewhere ?

**Comment by ktsakalozos** [comment]
Kubernetes is making heavy use of iptables. Even worse some of these iptable rules are subject to the CNI plugin used. I do not have the full set of such rules but you can get an idea how Kubernetes networking works in:

- https://kubernetes.io/docs/concepts/services-networking/
- https://github.com/ubuntu/microk8s/issues/72
- https://www.altoros.com/blog/kubernetes-networking-writing-your-own-simple-cni-plug-in-with-bash/
