### ISSUE TITLE
microk8s.kubectl requires sudo

### ISSUE THREAD

**Issue by amozoss** [ubuntu/microk8s#606]
```
$ snap info microk8s
installed:        v1.15.3                    (778) 171MB classic
```

```
$ microk8s.kubectl 
You do not have enough permissions to access MicroK8s. Please try again with sudo.
```
I noticed in the beta that `microk8s.kubectl` requires sudo (possibility related to #590).
Is there a way to add a user to a group or something so that they don't need to type sudo constantly?

**Comment by ktsakalozos** [comment]
There is not specific group but in https://github.com/ubuntu/microk8s/blob/feature/dev-docs/docs/access-witout-sudo.md you can see a few methods to work around the sudo requirement including one that lets you permit your user/group to access the critical files.

**Comment by tvansteenburgh** [comment]
@ktsakalozos That link 404s.

**Comment by ktsakalozos** [comment]
> @ktsakalozos That link 404s.

Oups, fixed.

**Comment by dcharbonnier** [comment]
after a `sudo snap install microk8s --candidate --classic` the solution `Grant access to a user group` is not working

**Comment by ktsakalozos** [comment]
@dcharbonnier could you try the edge channel (`--edge` instead of `--candidate`)?

**Comment by amozoss** [comment]
After updating, I now get this message
```
$ mk get pods
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user dan to the 'microk8s' group:

    sudo usermod -a -G microk8s dan

The new group will be available on the user's next login.
```

I was able to resolve this issue by adding myself to the microk8s group. As suggested by the error message. 
```
sudo usermod -a -G microk8s ${USER}
# open a new shell for the user, with updated group membership 
su - ${USER}
```

**Comment by liguobao** [comment]
Same to me。

**Comment by aleksandaratanasov** [comment]
> There is no specific group. In https://github.com/ubuntu/microk8s/blob/feature/dev-docs/docs/access-without-sudo.md you can see a few methods to work around the sudo requirement including one that lets you permit your user/group to access critical files.

Giving access to critical files should not be an option here. If actually is, then the problem lies in most cases in the tool itself.

**Comment by movsb** [comment]
> After updating, I now get this message
> 
> ```
> $ microk8s.kubectl 
> Insufficient permissions to access MicroK8s.
> You can either try again with sudo or add the user dan to the 'microk8s' group:
> 
>     sudo usermod -a -G microk8s dan
> 
> The new group will be available on the user's next login.
> ```
> 
> I was able to resolve this issue by adding myself to the microk8s group, as suggested by the error message.
> 
> ```
> sudo usermod -a -G microk8s ${USER}
> # open a new shell for the user, with updated group membership 
> su - ${USER}
> ```

Still doesn't work for me.

```shell
nuc:~ → microk8s.start
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user tao to the 'microk8s' group:

    sudo usermod -a -G microk8s tao
    sudo chown -R tao ~/.kube

After this, reload the user groups either via a reboot or by running 'newgrp microk8s'.
nuc:~ → sudo usermod -a -G microk8s tao
[sudo] password for tao:
nuc:~ → sudo chown -R tao ~/.kube
nuc:~ → newgrp microk8s
nuc:~ → microk8s.start
Insufficient permissions to access MicroK8s.
You can either try again with sudo or add the user tao to the 'microk8s' group:

    sudo usermod -a -G microk8s tao
    sudo chown -R tao ~/.kube

After this, reload the user groups either via a reboot or by running 'newgrp microk8s'.
nuc:~ → id
uid=1000(tao) gid=997(microk8s) groups=997(microk8s),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd),121(libvirt),998(docker),1000(tao)
```
