### ISSUE TITLE
unclean host shutdown produces false positive output to describe running pods and services

### ISSUE THREAD

**Issue by lazzarello** [ubuntu/microk8s#609]
[inspection-report-20190822_131938.tar.gz](https://github.com/ubuntu/microk8s/files/3531829/inspection-report-20190822_131938.tar.gz)

I manage an inventory of appliance-like products built on small computers with an application running in microk8s. The units move around a large industrial facility. Because of this, they are frequently power cycled without cleanly shutting down the OS. microk8s has trouble failing fast when something unexpected happens after an unclean reboot. The attached inspection report should describe how both `snap.microk8s.daemon-docker.service` and `snap.microk8s.daemon-kubelet.service` have failed to start, because there is a stale PID file left behind by dockerd.

Despite this accurate information, microk8s informs me that it is running and there are pods and services ready
```
user@host:~$ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
xxx-service-58964454fd-scc24         3/3     Running   54         9d
xxxxxxx-proto-549d5686b5-cmhd6       1/1     Running   19         9d
xxxxxx-proxy-d7d8b555b-km5wh         1/1     Running   745        13d
xxxxxx-replay-69475bb6f9-t7cks       1/1     Running   748        13d
xxxxxxx-web-6778cc4587-rfd4c         1/1     Running   18         9d
xxxxxx-writer-7f5d6f99d6-jc7wr       1/1     Running   18         9d
xx-runner-775c89d56c-vcmsx           1/1     Running   18         9d
xxxx-exporter-hkmbw                  1/1     Running   8          13d
xxxxxx-socket-786ddb559c-mj6xv       1/1     Running   18         10d
xxxxxx-kubernetes-68d64c66b5-229p2   1/1     Running   749        13d
xxx-pusher-5dc7f47644-rvlsg          1/1     Running   854        13d
xxx-xproxy-7697799988-68jl8          1/1     Running   863        13d
user@host:~$ kubectl get services
NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                         AGE
xxx-service     NodePort    10.152.183.243   <none>        50666:50666/TCP,50667:50667/TCP,5666:5666/TCP   13d
xxxxxxx-proto   ClusterIP   10.152.183.126   <none>        80/TCP                                          13d
xxxxxx-proxy    NodePort    10.152.183.158   <none>        3454:3454/TCP,51000:51000/TCP                   13d
xxxxxxx-web     ClusterIP   10.152.183.22    <none>        80/TCP                                          13d
kubernetes      ClusterIP   10.152.183.1     <none>        443/TCP                                         13d
xx-runner       NodePort    10.152.183.252   <none>        3466:3466/TCP                                   13d
xxxx-exporter   ClusterIP   None             <none>        9100/TCP                                        13d
xxxxxx-socket   NodePort    10.152.183.3     <none>        3210:3210/TCP                                   13d
xxx-pusher      NodePort    10.152.183.115   <none>        5005:5005/TCP,3453:3453/TCP                     13d
xxx-xproxy      NodePort    10.152.183.160   <none>        3455:3455/TCP,3456:3456/TCP                     13d
```

A simple `microk8s.stop && microk8s.start` magically fixes everything.

**Comment by lazzarello** [comment]
I've confirmed I can't reproduce this bug with the same manifests for my application using the latest/edge channel of the microk8s snap.

**Comment by ktsakalozos** [comment]
I am glad the latest MicroK8s works for you. The obvious recommendation is to move to a newer kubernetes especially since v1.13 will go out of support in a about a month.

I am very interested in your usecase. Where can I find more about it?

**Comment by lazzarello** [comment]
I tested this on 1.15/stable channel and everything works as expected. Regarding my use case, I'm restricted a bit in what I can disclose. Basically I support scientists and engineers using precision measurement instruments. An application running in microk8s is powering the first hop of our streaming data pipeline.

**if you really want to know you can check out my LinkedIn  :)**
