### ISSUE TITLE
/snap/microk8s/743/usr/bin/curl: error while loading shared libraries

### ISSUE THREAD

**Issue by affanse** [ubuntu/microk8s#612]
[inspection-report-20190824_205239.tar.gz](https://github.com/ubuntu/microk8s/files/3537259/inspection-report-20190824_205239.tar.gz)

Using current stable version 1.15.2

`~> sudo microk8s.enable istio`
`Enabling Istio`
`Fetching istioctl version v1.2.2.`
`/snap/microk8s/743/usr/bin/curl: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory`
`Failed to enable istio`

**Comment by ktsakalozos** [comment]
@affanse sorry for the late response we pushed an update on edge but it seems the fix is not complete yet (at least not for centos).
