### ISSUE TITLE
 FAIL:  Service snap.microk8s.daemon-kubelet is not running

### ISSUE THREAD

**Issue by nlitterat** [ubuntu/microk8s#618]
Hi
I am using Dell G5 15
Have 32 GB memory
Ubuntu 18.04
kernel 4.15.0-1050-oem
Used snap to install MicroK8S classic with Edge or without 
remove reinstaling or stop start did not helped
upgrading to kernel 5 seems to help for a short time and then it stoped again

Please help

[inspection-report-20190830_103453.tar.gz](https://github.com/ubuntu/microk8s/files/3558802/inspection-report-20190830_103453.tar.gz)
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by ktsakalozos** [comment]
Hi @nlitterat 

In the kubelet logs I see `listen tcp 0.0.0.0:10255: bind: address already in use`. Could you share the output of `netstat -lnp`? Could there be some other services on that port? You can check the kubelet logs with `sudo journalctls -u snap.microk8s.daemon-kubelet`

**Comment by nlitterat** [comment]
Hi thanks for your reply
I straggle with this error for along time.
It might be an issue with my working station.
I checked also if there is something listening on this port and there is no
process.

I decided to move to minikube. Thanks again.
