### ISSUE TITLE
Saving snap fails when saving docker socket

### ISSUE THREAD

**Issue by lazzarello** [ubuntu/microk8s#629]
Not sure if this is the right place for this report but I'm preparing for a big upgrade of a lot of infrastructure from 1.13 to 1.15 and I tried the `snap save microk8s` feature so I could quickly rollback if needed. The operation failed with this output. Notably, this process ran for ~ 3 hours before outputting this message.

```
$ sudo snap save microk8s
error: cannot perform the following tasks:
- Save data of snap "microk8s" in snapshot set #1 (cannot create archive: tar: 581/docker.sock: socket ignored (and 4023 more))
```

**Comment by mihairadulescu** [comment]
#3 (cannot create archive: tar: 384/run/docker/metrics.sock: socket ignored (and 2 more))

**Comment by Gryphn** [comment]
it seems to be working if you do `sudo microk8s stop` before doing `sudo snap save`

**Comment by lazzarello** [comment]
Oh my yes. this works and is quite fast. closing.

**Comment by gerrywastaken** [comment]
Hmmm... I'm not sure I'd say "quite fast", the stop normally takes a very long time by itself and then save took a further 58 seconds.
