### ISSUE TITLE
"ufw: command not found" in inspect.sh

### ISSUE THREAD

**Issue by popey** [ubuntu/microk8s#631]
When filing #630 I ran `microk8s.inspect` it produces an error at the end.

```
/snap/microk8s/743/inspect.sh: line 101: ufw: command not found
Building the report tarball
```

I'd expect the snap to bundle everything necessary to produce this report.

**Comment by ktsakalozos** [comment]
You are right we should not be showing this kind of errors: https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh#L122

We try to be smart and suggest a fix to a common problem (firewall).
