### ISSUE TITLE
hostpath-provisioner deployment pulls image every pod restart

### ISSUE THREAD

**Issue by alsasian** [ubuntu/microk8s#632]
Based on information at official working [docs](https://microk8s.io/docs/working), containerd will not cache image if its requested with version *latest*. In the case of microk8s storage add-ons, this cause hostpath-provisioner deployment to pull image every time the pod is restarted.

Every time I restart my laptop or microk8s, I need to make sure to connect to the internet to pull the image. This doesn't seems to be efficient.

Is there any reason for this 'latest' behavior? Perhaps we could set fix version for this like the other add-ons?

**Comment by ktsakalozos** [comment]
Thank you for spotting and reporting this @alsasian. Should be an easy fix.

**Comment by alsasian** [comment]
@ktsakalozos When checking available versions for hostpath-provisioner, I noticed that it has only one version **latest** in [dockerhub](https://hub.docker.com/r/cdkbot/hostpath-provisioner-amd64/tags). Do you know if we or someone else could add a fixed version for this docker image?

**Comment by ktsakalozos** [comment]
@alsasian just added the 1.0.0 tag. Give it a try.
