### ISSUE TITLE
Error: failed to generate container XX spec: invalid environment variable "ENV_VAR"

### ISSUE THREAD

**Issue by Kylex87** [ubuntu/microk8s#635]
Hi,

I'm trying to run a deployment with some environment variables that are set through a configMap. But the container cannot be run, because i get the error message

> Error: failed to generate container XX spec: invalid environment variable "ABAS_GUI_PORT"

It's an environment variable that is used inside the container to define which port should be used for a specific service.

I tried using different methods to set the environment variable. Directly in the deployment, through envFrom in the deployment (direct and configMapRef). None of them work. Starting the container outside of microk8s with `docker run ...` or docker-compose works fine. With or without setting the ABAS_GUI_PORT environment variable.

Google does not turn up much for that error and the only thing I can see as similar is using a docker-compose file where the environment is set as such:
```
...
 environment:
 - ""
...
```
The error then is also
> invalid environment variable

I already tried microk8s.reset, completely removing microk8s and installing again... I'm out of ideas at this point.

You guys have any pointers, things I can try out?

Thanks,
Kylex

Inspect Report:
[inspection-report-20190906_175849.tar.gz](https://github.com/ubuntu/microk8s/files/3584702/inspection-report-20190906_175849.tar.gz)

**Comment by Kylex87** [comment]
Seems like there was a problem with the docker-compose build script so it resulted in a bad layer. Docker runtime seems to ignore that, microk8s doesn't.
Fixing the build script removed the error.

**Comment by BatiGencho** [comment]
@Kylex87 I am having the same problem, but there is no build script for docker compose. I am entirely within the context o microk8s. The service that is failing with the err message "spec: invalid environment variable "xec" has a configmap.yaml, a deployment.yaml and a service.yaml files. The image itself is being pulled from a container registry so I have no control over it. ANy ideas what I could do in my case ?
