### ISSUE TITLE
can we remove sudo for microk8s.config?

### ISSUE THREAD

**Issue by wallyworld** [ubuntu/microk8s#640]
When microk8s.config started requiring sudo, Juju bootstrap breaks.
Since config is a read only command, I think that should not require sudo.

In general, even for other commands, perhaps the use of sudo can be restricted to those cases that really require it. eg if kubectl is not operating as admin, then is sudo really required? Or perhaps microk8s can look at what LXD did to remove the need for sudo? That would be the ideal solution IMO.

**Comment by ktsakalozos** [comment]
The options available for accessing MicroK8s currently is either sudo or add users to the microk8s group. Adding users to a group is done with: `sudo usermod -a -G microk8s ubuntu` and a logout-login so you get an updated shell. If logout-login is not an option you need to `newgrp microk8s` to get a shell with the group included. I believe this is what LXD is doing, there is a group users can be added to.

The reason we have taken this approach is because we do not want to allow unauthorized users to have access to the admin kubeconfig. Therefore `microk8s.config` should be guarded.

**Comment by wallyworld** [comment]
We need to do whatever needs to be done automatically when the snap is installed or refreshed, so that things Just Work. We are already running under sudo at that point so can (should?) perform the necessary operations for the current user, including the newgrp. Users expect to be able to snap install microk8s and juju and have things work out of the box. With the change to microk8s, we've started getting bug reports and questions about how to make things work again. All IMHO :-)

**Comment by tvansteenburgh** [comment]
> With the change to microk8s, we've started getting bug reports and questions about how to make things work again.

Can you link to some of these so we can see what issues people are hitting?

While perhaps not convenient, the change to require sudo was done for good reason and under the guidance of the Security team. CC'ing them for guidance on your suggestion to set up the group membership at snap install time.

/cc @jdstrand @alexmurray

**Comment by jdstrand** [comment]
> > With the change to microk8s, we've started getting bug reports and questions about how to make things work again.
> 
> Can you link to some of these so we can see what issues people are hitting?
> 
> While perhaps not convenient, the change to require sudo was done for good reason and under the guidance of the Security team. CC'ing them for guidance on your suggestion to set up the group membership at snap install time.
> 
> /cc @jdstrand @alexmurray

The classic microk8s can do this at install time. A strict mode microk8s cannot without coordination with snapd (we have a mechanism for this now, but the username would almost certainly need to be 'snap_microk8s' instead of 'microk8s'). Cc @pedronis for awareness)

**Comment by wallyworld** [comment]
@tvansteenburgh here's one such bug report
https://bugs.launchpad.net/bugs/1843281

Juju calls microk8s.config to get the cluster info and now that's not possible without sudo
