### ISSUE TITLE
"GLIBC_PRIVATE not defined in file libc.so.6 with link time reference" error when try to install microk8s in centos7

### ISSUE THREAD

**Issue by yangshenhuai** [ubuntu/microk8s#648]
when I try to install microk8s in centos7(CentOS Linux release 7.2.1511 (Core))  I got below error. any idea how to solve this error?

> $ sudo snap install microk8s --classic
error: cannot perform the following tasks:
\- Run install hook of "microk8s" snap if present (run hook "install": 
\-----
\+ export LD_LIBRARY_PATH=/snap/microk8s/826/lib:/snap/microk8s/826/usr/lib:/snap/microk8s/826/lib/x86_64-linux-gnu:/snap/microk8s/826/usr/lib/x86_64-linux-gnu
\+ LD_LIBRARY_PATH=/snap/microk8s/826/lib:/snap/microk8s/826/usr/lib:/snap/microk8s/826/lib/x86_64-linux-gnu:/snap/microk8s/826/usr/lib/x86_64-linux-gnu
\+ export PATH=/snap/microk8s/826/usr/sbin:/snap/microk8s/826/usr/bin:/snap/microk8s/826/sbin:/snap/microk8s/826/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/bin:/usr/local/bin
\+ PATH=/snap/microk8s/826/usr/sbin:/snap/microk8s/826/usr/bin:/snap/microk8s/826/sbin:/snap/microk8s/826/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/bin:/usr/local/bin
\+ source /snap/microk8s/826/actions/common/utils.sh
\+ cp -r /snap/microk8s/826/default-args /var/snap/microk8s/826/args
\+ mkdir /var/snap/microk8s/826/certs
\+ cp /snap/microk8s/826/certs/csr.conf.template /var/snap/microk8s/826/certs/csr.conf.template
\+ produce_certs
\+ for key in serviceaccount.key ca.key server.key front-proxy-client.key
\+ '[' -f /var/snap/microk8s/826/certs/serviceaccount.key ']'
\+ openssl genrsa -out /var/snap/microk8s/826/certs/serviceaccount.key 2048
openssl: relocation error: /snap/core/current/lib/x86_64-linux-gnu/libresolv.so.2: symbol __h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
\-----)

**Comment by ktsakalozos** [comment]
We intend to address this kind of problems by moving to a strictly confined setup.
