### ISSUE TITLE
How to enable use-forwarded-headers?

### ISSUE THREAD

**Issue by heckad** [ubuntu/microk8s#661]
I want to get real IP in my app but X-Forwarded-For is empty. Why? I run ingress by `microk8s.enable ingress`. In google I found that in config need add `use-forwarded-headers: true`. How to do it?

**Comment by balchua** [comment]
You may want to edit the configmap `nginx-load-balancer-microk8s-conf` and add the option to it.  example:
`kubectl edit cm nginx-load-balancer-microk8s-conf`
then add the `use-forwarded-headers: true` in the `data section.

```
data:
  use-forwarded-headers: true
```

**Comment by heckad** [comment]
It's return `Error from server (BadRequest): error when replacing "/tmp/kubectl-edit-76l5q.yaml": ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found t, error found in #10 byte of ...|headers":true},"kind|..., bigger context ...|apiVersion":"v1","data":{"use-forwarded-headers":true},"kind":"ConfigMap","metadata":{"annotations":|...
` if I do it. Maybe there is another way?

**Comment by balchua** [comment]
That's strange, perhaps you have tabs in your yaml.  The `ConfigMap` should look like this.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-microk8s-conf
  namespace: ingress
data:
  use-forwarded-headers: true
``|

**Comment by heckad** [comment]
My configmap is
```
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-load-balancer-microk8s-conf","namespace":"default"}}
  creationTimestamp: "2019-09-19T08:12:29Z"
  name: nginx-load-balancer-microk8s-conf
  namespace: default
  resourceVersion: "92854"
  selfLink: /api/v1/namespaces/default/configmaps/nginx-load-balancer-microk8s-conf
  uid: fd969aa7-6024-429e-bf02-2ad7916c4bc2
```
I am added
```
data:
  use-forwarded-headers: true
```
And did `kubectl replace -f /tmp/kubectl-edit-ua11p.yaml` because 
```
error: configmaps "nginx-load-balancer-microk8s-conf" could not be patched: unrecognized type: string
You can run `kubectl replace -f /tmp/kubectl-edit-ua11p.yaml` to try this update again.
```
And got that erro.

**Comment by balchua** [comment]
@heckad can you enclose true with quotes? Ex. 
```
data:
  use-forwarded-headers: "true"
```

**Comment by heckad** [comment]
Yes, it accepts but  `X-Forwarded-For` still empty.

**Comment by balchua** [comment]
Do you have a load balancer in front of your ingress?

If no, the easiest way to test if you can do a curl and pass the header `X-Forwarded-For`.
