### ISSUE TITLE
Issue Installing Microk8s

### ISSUE THREAD

**Issue by thomaskwok91** [ubuntu/microk8s#663]
Hi when I tried to install microk8s using snap install microk8s --classic I get this error

`+ export LD_LIBRARY_PATH=/snap/microk8s/826/lib:/snap/microk8s/826/usr/lib:/snap/microk8s/826/lib/x86_64-linux-gnu:/snap/microk8s/826/usr/lib/x86_64-linux-gnu
+ LD_LIBRARY_PATH=/snap/microk8s/826/lib:/snap/microk8s/826/usr/lib:/snap/microk8s/826/lib/x86_64-linux-gnu:/snap/microk8s/826/usr/lib/x86_64-linux-gnu
+ export PATH=/snap/microk8s/826/usr/sbin:/snap/microk8s/826/usr/bin:/snap/microk8s/826/sbin:/snap/microk8s/826/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/usr/local/bin
+ PATH=/snap/microk8s/826/usr/sbin:/snap/microk8s/826/usr/bin:/snap/microk8s/826/sbin:/snap/microk8s/826/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin:/usr/local/bin
+ source /snap/microk8s/826/actions/common/utils.sh
+ cp -r /snap/microk8s/826/default-args /var/snap/microk8s/826/args
/snap/microk8s/826/meta/hooks/install: line 10: /snap/microk8s/826/bin/cp: No such file or directory`

Anyone know how to fix it? I tried to create that directory by typing in mkdir -p /snap/microk8s/826/bin/cp but then there are other issues.

I have looked at the other solutions like sudo snap install core but it seems core is already installed in my machine.

**Comment by ktsakalozos** [comment]
Hi @thomaskwok91 what distribution are you on? I suspect this might be an issue with snapd not placing the snaps in the right location.

**Comment by thomaskwok91** [comment]
I am using Ubuntu 18.04 @ktsakalozos

**Comment by ktsakalozos** [comment]
What is the out put of `snap changes microk8s`. Are you able to `sudo snap remove microk8s`? When removing the snap, can you make sure there is no `microk8s` directory under `/snap/`?

**Comment by ktsakalozos** [comment]
When microk8s is removed, can you make sure you do not have a directory named `microk8s` under `/var/snap` (notice the `/var/` this time)?

The error says that the cp command in  https://github.com/ubuntu/microk8s/blob/master/snap/hooks/install#L10 cannot find the directory with the default configuration. This directory however is part of the snap. It does not make sense, it seems part of the snap gets installed in your machine? You may want to ask https://forum.snapcraft.io, the snapd people might have seen this before.

**Comment by thomaskwok91** [comment]
I just checked and I do not have /var/snap/microk8s either. And I'll send the message to the snapcraft forum to see if they know. Is there any dependencies or anything that I may have needed to install before doing sudo snap install microk8s --classic that may have been the reason?

**Comment by ktsakalozos** [comment]
I guess you have already checked for missing packages, `apt-get install --fix-missing`.

**Comment by thomaskwok91** [comment]
Yes I have run that and there is no packages that need to be fixed. This is the oddest error

**Comment by thomaskwok91** [comment]
So the reason we wanted microk8s is because I heard that kubeflow is the best job scheduler at the moment and we need a job scheduler for our deep learning server. Is it possible to install kubeflow job scheduler without microk8s? And are there any alternatives for job scheduling at the mean time while I try to figure this issue out with snap community and github?

Thanks

**Comment by thomaskwok91** [comment]
Wow actually it seemed my issue was more with snapd than with microk8s. I uninstalled and reinstalled snapd and it fixed everything. Seemed something was broken with my core and snap

**Comment by ktsakalozos** [comment]
@thomaskwok91 let me introduce @knkski who can point you to some easy to use scripts to install kubeflow.

**Comment by knkski** [comment]
@thomaskwok91: There's a README here that covers installing kubeflow on microk8s:

https://github.com/juju-solutions/bundle-kubeflow/

**Comment by thomaskwok91** [comment]
Hi @knkski I am currently running

`python3 scripts/cli.py deploy-to uk8s`

and I get these error messages
`Running microk8s.enable storage
+ microk8s.enable storage
Enabling default storage class
deployment.extensions/hostpath-provisioner unchanged
storageclass.storage.k8s.io/microk8s-hostpath unchanged
serviceaccount/microk8s-hostpath unchanged
clusterrole.rbac.authorization.k8s.io/microk8s-hostpath unchanged
clusterrolebinding.rbac.authorization.k8s.io/microk8s-hostpath unchanged
Storage will be available soon
`

`Running microk8s.enable dashboard
+ microk8s.enable dashboard
Applying manifest
secret/kubernetes-dashboard-certs unchanged
serviceaccount/kubernetes-dashboard unchanged
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal unchanged
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal unchanged
deployment.apps/kubernetes-dashboard unchanged
service/kubernetes-dashboard unchanged
service/monitoring-grafana unchanged
service/monitoring-influxdb unchanged
service/heapster unchanged
deployment.extensions/monitoring-influxdb-grafana-v4 unchanged
serviceaccount/heapster unchanged
clusterrolebinding.rbac.authorization.k8s.io/heapster unchanged
configmap/heapster-config unchanged
configmap/eventer-config unchanged
deployment.extensions/heapster-v1.5.2 unchanged

If RBAC is not enabled access the dashboard using the default token retrieved with:

token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token

In an RBAC enabled setup (microk8s.enable RBAC) you need to create a user with restricted
permissions as shown in https://github.com/kubernetes/dashboard/wiki/Creating-sample-user`

Do you know how I could fix the storage and dashboard, or can I technically move on without them?

**Comment by knkski** [comment]
@thomaskwok91: Those messages are expected output, actually (I'm assuming you mean the `... unchanged` lines). That's just the output that `microk8s.enable storage` has, which that script echoes.

**Comment by thomaskwok91** [comment]
I ran into some hiccups today so I will try again tomorrow when I'm back in the office and state the problems. I ended up uninstalling microk8s and reinstalling it as I ran one of the scripts and it kept giving me an error that's output seemed to be a misplaced directory.

Anyways wanted to ask first, possibly stupid question, but I saw that the juju-solutions requires an AWS account for authorization. Is the service free? I read somewhere in AWS about a $5 per month fee for portfolios and does this technically count as a portfolio or no? Just wondering to see if I should put my personal AWS account or get the school to put it for me.

**Comment by ktsakalozos** [comment]
> I saw that the juju-solutions requires an AWS account for authorization

Where did you saw this? Juju works on many substrates (aws included) public and private clouds, local hardware.

[1] https://jaas.ai/docs/clouds 
[2] https://jaas.ai/

**Comment by thomaskwok91** [comment]
I actually was able to install microk8s so I moved the topic to juju-solutions bundle-kubeflow as that is the next part where I am having the issue.
