### ISSUE TITLE
cgroup permission error attempting to run pod as non-root user

### ISSUE THREAD

**Issue by HowellBP** [ubuntu/microk8s#665]
Relvant log line from `microk8s.kubectl describe pod`:
```
  Warning  Failed          8s (x2 over 21s)       kubelet, ubuntu    Error: failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"failed to write 100000 to cpu.cfs_period_us: open /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/podd3732880-bc19-46f6-877a-671add179658/kiosk-manager/cpu.cfs_period_us: permission denied\\\"\"": unknown
```

microk8s.inspect tarball:
[inspection-report-20190923_152339.tar.gz](https://github.com/ubuntu/microk8s/files/3643992/inspection-report-20190923_152339.tar.gz)

I'm attempting to run microk8s on a Raspberry Pi 4B with 4GB RAM on Ubuntu 18.04 using a [custom arm64 kernel](https://github.com/TheRemote/Ubuntu-Server-raspi4-unofficial/releases/tag/v8). I've made a few modifications to the image since installation to get microk8s to run; however attempting to run a pod as a non-root user results in the permission error above.

Is there a workaround for this, or is this a kernel issue? If it's a kernel issue, what flag should be set to allow non-root users permission to write to cgroupfs?

**Comment by ktsakalozos** [comment]
Hi @HowellBP I am not exactly sure what you are doing. Could you provide more information?

I know that snapd will start all daemons as root and that includes containerd. Containerd is the one creating the containers and kubelet is talking to containerd through a socket. So a user talks to kubernetes and kubernetes asks containerd to spawn the containers (with runc). Do you want containerd to run as a normal user? How do you start a pod as non-root? Do you have a special configuration somewhere?

**Comment by HowellBP** [comment]
On a standard AMD64 PC running Ubuntu 18.04, I have a non-privileged user as a member of a group, `microk8s`, and I use `microk8s.kubectl apply -f` to create a deployment. I don't know how the underlying framework of microk8s or containerd work, so I can't tell you exactly what's different, aside from the fact it's running in an ARM64 environment instead of AMD64, on a custom kernel. I have the same setup (to the best of my knowledge), with a non-privileged user as a member of the `microk8s` group, and I attempted a `microk8s.kubectl apply -f`, yet the pods refuse to start due to the cgroup permission issue.

I've also attempted to run `microk8s.kubectl apply -f` as root, and ran into the same error, so there must be something missing from my cgroup or kernel configuration.

If this isn't a microk8s issue then I'll talk to the person who built the custom kernel, but as I said, I'm not 100% familiar with exactly how microk8s and snapd work, so I'm not sure I'd be able to guide them to a fix without better knowledge of the components.

**Comment by benton** [comment]
I am having the same issue, but even as `root`, also on a Raspberry Pi4. I'm using a fresh installation of `microk8s` on Ubuntu 18.04 via snap, and I cannot install the example add-ons, as described in the [Getting Started][3].

    sudo microk8s enable dns dashboard registry

...or create a simple one-liner deployment:
 
    microk8s kubectl create deployment test-deployment --image=registry.hub.docker.com/arm64v8/redis:latest

In fact, `microk8s` does not seem able to create _any_ containers at all!  I get the following from `journalctl`...

    Mar 30 11:35:08 k8m1 microk8s.daemon-containerd[1713]: 
    time="2020-03-30T11:35:08.439727371-07:00" 
    level=error 
    msg="StartContainer for "cdb48b65bd41d0e0cd63a1f9c3ab3cf1f902068ca40266d061b002f7ea46d555" failed" 
    error="failed to create containerd task: OCI runtime create failed: 
    container_linux.go:345: 
    starting container process caused "process_linux.go:424: 
    container init caused \"process_linux.go:390: 
    setting cgroup config for procHooks process caused 
    \\\"failed to write 100000 to cpu.cfs_period_us: 
    open /sys/fs/cgroup/cpu,cpuacct/kubepods/besteffort/pod5affe721-d742-496e-b4be-b68b6bca8fa3/cdb48b65bd41d0e0cd63a1f9c3ab3cf1f902068ca40266d061b002f7ea46d555/cpu.cfs_period_us: 
    permission denied\\\"\"": unknown"

_(this is actually a single log line - I broke it up for readability)_

This error is occurring on a Raspberry Pi 4 device – hence the `arm64v8` image – using a v4.19 kernel only [slightly tweaked][1] by the [BerryBoot][2] project. (Though I believe that BerryBoot in turn tracks the [Raspbian kernel][4], which tracks Debian itself)

Searching around for the error text points to a possible bug with systemd's `cgroup` driver, but it looks like that was fixed. I can't tell whether I need to rebuild the kernel with some currently-missing cgroup-related `CONFIG` value or just change some config somewhere.  :-/

Attached is the [inspection-report-20200331_104342.tar.gz](https://github.com/ubuntu/microk8s/files/4410652/inspection-report-20200331_104342.tar.gz)

Any insights are appreciated.

[1]:https://github.com/maxnet/berryboot/blob/berryboot2018/configs/kernel_config_fragment_pi64
[2]:https://www.berryterminal.com/doku.php/berryboot
[3]:https://microk8s.io/#get-started
[4]:https://github.com/raspberrypi/linux

**Comment by benton** [comment]
I resolved this issue by recompiling the Berryboot kernel with 

    CONFIG_CFS_BANDWIDTH=y

**Comment by benton** [comment]
I resolved this issue by recompiling Berryboot with the following extra kernel parameter:

    CONFIG_CFS_BANDWIDTH=y
