### ISSUE TITLE
requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

### ISSUE THREAD

**Issue by davidthewatson** [ubuntu/microk8s#669]
I'm following this guide:

https://discuss.kubernetes.io/t/microk8s-clustering-preview/7472

They are all running Ubuntu 19.04 with passwordless ssh enabled.

I have a master and 2 nodes. I've done:

    sudo snap install microk8s --classic --channel=1.15/edge/clustering

on all nodes. 

I tried to add node with:

    sudo microk8s.add-node

and copied/pasted the join command. When I run that, I get:

```
watson@k8s-node1:~$ sudo  microk8s.join 10.1.90.0:25000/LZbwbrVEqKTkdKcquwyfpiCCpcDWPvcu
Traceback (most recent call last):
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 549, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 251, in _get_conn
    return conn or self._new_conn()
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 764, in _new_conn
    raise SSLError("Can't connect to HTTPS URL because the SSL "
requests.packages.urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/microk8s/874/scripts/cluster/join.py", line 369, in <module>
    info = get_connection_info(master_ip, master_port, token, callback_token)
  File "/snap/microk8s/874/scripts/cluster/join.py", line 56, in get_connection_info
    verify=False)
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/requests/api.py",
line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/requests/api.py",
line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/requests/sessions.py", line 480, in request
    resp = self.send(prep, **send_kwargs)
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/requests/sessions.py", line 588, in send
    r = adapter.send(request, **kwargs)
  File "/snap/microk8s/874/usr/lib/python3/dist-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.
```

[inspection-report-20190924_194237.tar.gz](https://github.com/ubuntu/microk8s/files/3649898/inspection-report-20190924_194237.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @davidthewatson, thank you for reporting this.

I was able to reproduce this on 19.04. I do not have a workaround or fix for now.

**Comment by davidthewatson** [comment]
Thanks @ktsakalozos

Wouldn't the workaround be to apt install openssl and run the join again?

**Comment by ktsakalozos** [comment]
Did this work for you?

**Comment by ktsakalozos** [comment]
@davidthewatson a version with a fix should be available on the latest edge channel (`snap install microk8s --classic --edge`) by tomorrow. Let me know if it works for you.

**Comment by davidthewatson** [comment]
Awesome. Thanks. I'll watch for the update.

**Comment by davidthewatson** [comment]
I grabbed the update to 1.16 after it came out today and attempted the same steps above. Unfortunately, the bug still occurs with the merged PR #672 above. Are you sure that python3 can find the openssl module? This was a common problem with the request module which I think this code depends on.

**Comment by ktsakalozos** [comment]
Could you try the edge channel?
```
sudo snap install microk8s --classic --edge 
```

**Comment by davidthewatson** [comment]
@ktsakalozos 

I just installed edge channel. Same version: 1.16. Fails the same way. Again, I ask: Are you sure python3 can find the openssl module? It's not clear to me what the point of trying the edge channel was when it's the same version as tested previously. Do you actually have any evidence that the bug is fixed or are we just flying blind?

**Comment by ktsakalozos** [comment]
The edge and stable do have the same version but they do not have the same revision. In `sudo snap info microk8s` you see stable at 920 and edge at 922. Revision 922 includes this PR  https://github.com/ubuntu/microk8s/pull/672/files that pulls openssl into the snap. Openssl is part of your system as it is a dependency of snapd. In 19.04 there is a misalignment between the openssl version on the system and what the in-snap python wants to find and this causes the error. By placing openssl in the snap my intention is to have the in-snap python use the in-snap openssl. Two days ago when working on this bug I managed to get it working but now that I test the snap again the fix is not complete. There must have been something else (perhaps in the local building process?) that tweaked the lib versions.   

I am sorry for this. I thought I had this fixed but I do not yet.

**Comment by davidthewatson** [comment]
Thanks for the additional detail.

I'm aware of the openssl history on ubuntu having run into this years ago with requests in python. I'd like to help but I don't understand the microk8s virtual environment. Are you using docker or lxd to build the snaps?

I could pursue this, but I don't find any developer documentation when searching the microk8s git repo. Can you point me in the right direction? TIA

**Comment by ktsakalozos** [comment]
Thank you @davidthewatson for offering your help.

@DomFleischmann has been working on this issue for a couple of days now and he might have some fix ready soon. We would appreciate your feedback on the PR as soon it is ready.

For building MicroK8s have a look at [1]. `snapcraft cleanbuild` creates an lxc container and does all the building there. The files you may want to look at is the `microk8s.join` command wrapper [2].

Thank you again.

[1] https://github.com/ubuntu/microk8s/blob/master/docs/build.md
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-join.wrapper

**Comment by ktsakalozos** [comment]
@davidthewatson the fix should be available on edge within a day. Hope, it gets fixed this time.
