### ISSUE TITLE
Tutorial broken link to Charmed Kubernetes

### ISSUE THREAD

**Issue by NumesSanguis** [ubuntu/microk8s#670]
Just a small heads-up. On the last tutorial page (https://tutorials.ubuntu.com/tutorial/install-a-local-kubernetes-with-microk8s#6), the `Try Charmed Kubernetes` link is broken.
It refers to: https://tutorials.ubuntu.com/tutorial/get-started-canonical-kubernetes#0

**Comment by ktsakalozos** [comment]
Thank you for reporting this. A fix is under way.

**Comment by ktsakalozos** [comment]
The PR with the fix is merged. The tutorial should be updated soon.
