### ISSUE TITLE
microk8s.status not running and microk8s inspect gives error

### ISSUE THREAD

**Issue by thomaskwok91** [ubuntu/microk8s#673]
Hi all, I just ran microk8s.status and see that it is not running, it suggested to use microk8s.inspect and when I use it, I receive this error

```
 FAIL:  Service snap.microk8s.daemon-scheduler is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-scheduler
 FAIL:  Service snap.microk8s.daemon-controller-manager is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-controller-manager
```
I have attached the gz file for reference. [https://drive.google.com/open?id=1bUMY25GrT8QH1fsZvHfGf-1arpwrn9G-](url)

**Comment by ktsakalozos** [comment]
It seems you have another kubernetes running localy in your system. Many of the default kubernetes ports are already used so MicroK8s will not start. I am not sure how you installed the second kubernetes so I am not sure what is the right process to remove it.

**Comment by thomaskwok91** [comment]
I think one of the grad students was trying to install kubernetes and kubeflow and ran into error so they told me and I took over for it. Do you know how I would check which kubernetes is running on my system, so I can ask them if it is needed and then remove it?

**Comment by thomaskwok91** [comment]
Hi @ktsakalozos so I had the student uninstall kubernetes and then I reinstalled microk8s and followed the steps on [https://microk8s.io/docs/](url) to get kubeflow installed. I am running into the issue with the dashboard is not able to get enabled as I get this error

`Applying manifest
secret/kubernetes-dashboard-certs unchanged
serviceaccount/kubernetes-dashboard unchanged
role.rbac.authorization.k8s.io/kubernetes-dashboard-minimal unchanged
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard-minimal unchanged
deployment.apps/kubernetes-dashboard unchanged
service/kubernetes-dashboard unchanged
service/monitoring-grafana unchanged
service/monitoring-influxdb unchanged
service/heapster unchanged
deployment.extensions/monitoring-influxdb-grafana-v4 unchanged
serviceaccount/heapster unchanged
clusterrolebinding.rbac.authorization.k8s.io/heapster unchanged
configmap/heapster-config unchanged
configmap/eventer-config unchanged
deployment.extensions/heapster-v1.5.2 unchanged

If RBAC is not enabled access the dashboard using the default token retrieved with:

token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token

In an RBAC enabled setup (microk8s.enable RBAC) you need to create a user with restricted
permissions as shown in https://github.com/kubernetes/dashboard/wiki/Creating-sample-user`

And then when I run microk8s.inspect I get this message

`FAIL:  Service snap.microk8s.daemon-controller-manager is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-controller-manager`

with this error
`Sep 25 19:07:09 dls1 microk8s.daemon-controller-manager[39609]: Flag --address has been deprecated, see --bind-address instead.
Sep 25 19:07:09 dls1 microk8s.daemon-controller-manager[39609]: I0925 19:07:09.803436   39609 serving.go:319] Generated self-signed cert in-memory
Sep 25 19:07:09 dls1 microk8s.daemon-controller-manager[39609]: failed to create listener: failed to listen on 127.0.0.1:10252: listen tcp 127.0.0.1:10252: bind: address already in use
`
Here is the inspection report [https://drive.google.com/file/d/1DUC8kFrfCPRsQ8RKY4mYfMwdGZEVFbob/view?usp=sharing](url)

Thank you so much for all your help.

**Comment by balchua** [comment]
@thomaskwok91 another process is using the port 10252.

Try running `netstat tulpn | grep 10252` might help you find the pid of the process using that port.  Note, if the process is executed by root or another user you might not see it if you execute the command with an unprivileged user.

**Comment by thomaskwok91** [comment]
I forgot about that command, but it also fixed itself the minute I ran microk8s.reset and then started it again.
