### ISSUE TITLE
enabling coredns: error validating data

### ISSUE THREAD

**Issue by kartoch** [ubuntu/microk8s#675]
When enabling coredns:

```
$ microk8s.enable coredns
Enabling coredns
serviceaccount/coredns created
configmap/coredns created
error: error validating "/home/kartoch/snap/microk8s/920/tmp/temp.coredns.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext.allowPrivilegeEscalation): invalid type for io.k8s.api.core.v1.SecurityContext.allowPrivilegeEscalation: got "string", expected "boolean"; if you choose to ignore these errors, turn validation off with --validate=false
Failed to enable coredns
```

The reason seems to be in the way the coredns enable script handle string for `$ALLOWESCALATION` in `/microk8s-resources/actions/enable.dns.sh`:

https://github.com/ubuntu/microk8s/blob/e0dbaab51273b8cac36eaee8e80b0c56f00d484d/microk8s-resources/actions/enable.dns.sh#L10-L17

Which is injected as a string with double quote in `microk8s-resources/actions/coredns.yaml` instead of a boolean.

https://github.com/ubuntu/microk8s/blob/50e8f2488d0bb20332b6894328913e4ab691d856/microk8s-resources/actions/coredns.yaml#L104-L105

**Comment by kartoch** [comment]
enable dns works fine, and uses `coredns`:

```
 microk8s.enable dns             
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns unchanged
clusterrolebinding.rbac.authorization.k8s.io/coredns unchanged
Restarting kubelet
DNS is enabled
```

**Comment by ktsakalozos** [comment]
Indeed you are expected to `microk8s.enbale dns` and not coredns. The `coredns.yaml` file served as a template to the enable script.

**Comment by ktsakalozos** [comment]
What made you try to `enable coredns`?

**Comment by kartoch** [comment]
> What made you try to enable coredns?

Just testing enabling all plugins for fun. 

> Indeed you are expected to microk8s.enbale dns and not coredns. The coredns.yaml file served as a template to the enable script.

Maybe removing the coredns script makes sense ?
