### ISSUE TITLE
Document rules needed if ufw enabled

### ISSUE THREAD

**Issue by tvansteenburgh** [ubuntu/microk8s#68]
As shown by #66 and #67, if user has ufw enabled, some rules will need to be added to allow traffic for the apiserver and dns (maybe others?).

Let's add the necessary rules to the readme.

**Comment by tvansteenburgh** [comment]
I wonder if this problem would go away if we used the loopback interface by default (which I think we should do, see https://github.com/juju-solutions/microk8s/issues/63#issuecomment-402865403). Then maybe ufw modifications would only be required if you wanted to expose your microk8s on a different interface.

**Comment by tvansteenburgh** [comment]
Ignore previous comment, loopback is irrelevant. Actual fix described in https://github.com/juju-solutions/microk8s/issues/67#issuecomment-404921973

**Comment by davefinster** [comment]
I suspect we also need to run ```sudo ufw default allow routed``` in order to enable IP forwarding. I have ufw enabled on a host and while I could ping and DNS resolve between containers, many things couldn't reach the outside world and had spotty connectivity to each other that was tricky to diagnose. Adding the above resolved it.

**Comment by tvansteenburgh** [comment]
@davefinster FWIW, I think we came to the same conclusion here: https://github.com/ubuntu/microk8s/issues/75#issuecomment-407357469

**Comment by tvansteenburgh** [comment]
readme was updated by #77

**Comment by sgasse** [comment]
Hi! I have issues with `microk8s` and `ufw` - maybe you can nudge me in the right direction?
Basically, I added all the rules to `ufw` described here/in the troubleshooting section, but even then, I run into the error:
```
$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```
I even made sure that IP4/IP6 forwarding is enabled in general in `/etc/ufw/sysctl.conf`, but it does not help.

## Not-working example with (slightly redacted) ufw rules:
```
$ sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), allow (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW IN    Anywhere                          
Anywhere on vxlan.calico   ALLOW IN    Anywhere                  
22/tcp (v6)                ALLOW IN    Anywhere (v6)                  
Anywhere (v6) on vxlan.calico ALLOW IN    Anywhere (v6)             

Anywhere                   ALLOW OUT   Anywhere on vxlan.calico  
Anywhere (v6)              ALLOW OUT   Anywhere (v6) on vxlan.calico

$ microk8s stop
Stopped.
$ microk8s start
Started.
$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.

$ cat /etc/ufw/sysctl.conf | grep forward
net/ipv4/ip_forward=1
net/ipv6/conf/default/forwarding=1
net/ipv6/conf/all/forwarding=1
```

## Working after disabling ufw
```
$ sudo ufw disable
Firewall stopped and disabled on system startup
$ microk8s stop
Stopped.
$ microk8s start
Started.
$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    ha-cluster           # Configure high availability on the current node
  disabled:
    dashboard            # The Kubernetes dashboard
    dns                  # CoreDNS
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
    traefik              # traefik Ingress controller for external access
```

Since I plan to install `microk8s` on a device in an untrusted environment, having `ufw` permanently disabled is not an option. Any hints on what could be the issue?

Also on a side-note: Would there be a less permissive option for routing? `sudo ufw default allow routed` seems very broad, maybe some `sudo ufw route allow in on vxlan.calico && sudo ufw route allow out on vxlan.calico` would be enough?

**Comment by sgasse** [comment]
I also added `sudo ufw allow in on cali+ && sudo ufw allow out on cali+` as in the troubleshooting session and `sudo ufw allow in on cali993d141e13d && sudo ufw allow out on cali993d141e13d` (created specifically on our machine) but it did not help :thinking:
