### ISSUE TITLE
When upgrading to 1.16/stable 2019-09-25 (920) unable to use cluster until change of configs

### ISSUE THREAD

**Issue by myers** [ubuntu/microk8s#682]
It looks like the default port the kube-apiserver was changed from 16443 to 6443.  The problem is some autogenerated files in `/var/snap/microk8s/current/credentials`: `controller.config`, `kubelet.config`, `proxy.config`, and `scheduler.config` all had the line

```
    server: https://127.0.0.1:16443
```

which needed to be corrected before the cluster would come up all the way (e.g. nginx-ingress worked).

I post this as both to help those that might be upgrading (no thanks to the design flaw of snap for forcing this upgrade) and to let the microk8s team know that this upgrade is not as smooth as I think they would like.

**Comment by balchua** [comment]
Looking at the source, I think it moved from 6443 to 16443 instead.

**Comment by ktsakalozos** [comment]
Indeed every MicroK8s update that pushes a new upstream release (in this case v1.16) may introduce breaking changes. If you are interested in having a long lasting MicroK8s cluster it is safer to select the channel you want to follow (eg `sudo snap install microk8s --classic --channel=1.16/stable`). Ephemeral clusters you want to keep for a few hours or days can use the latest stable version by skipping the `--channel` during installation.

**Comment by myers** [comment]
@ktsakalozos Thank you for that info.  That's super helpful.  Would it make sense to put that in the README.md some where?
