### ISSUE TITLE
Publicly exposed ports don't match documentation in v1.16

### ISSUE THREAD

**Issue by jareks** [ubuntu/microk8s#684]
I have noticed two occasions where https://microk8s.io/docs/ports is incorrect for v1.16.

1. According to docs it is possible stop exposing ports by "remove --proxy-mode from /var/snap/microk8s/current/args/kube-proxy". But there is no `--proxy-mode` in that file anymore (or elsewhere).
What's the v1.16 way to stop exposing ports?

2. Documentation seems to miss one tcp and three tcp6 ports:
```
tcp        0      0 0.0.0.0:25000           0.0.0.0:*               LISTEN      8661/python3 # /snap/microk8s/920/usr/bin/gunicorn3 cluster.agent:app
tcp6       0      0 :::10257                :::*                    LISTEN      2093/kube-controlle 
tcp6       0      0 :::10259                :::*                    LISTEN      2069/kube-scheduler 
tcp6       0      0 :::12379                :::*                    LISTEN      5911/etcd           
```
I looks to me that those ports are also publicly exposed?

One general remark:
I think it would be better to not expose any ports publicly by default. I did not expect that behavior and I think k8s could work using only private interfaces.

**Comment by ktsakalozos** [comment]
There was a PR against our docs sitting there for some time now. That doc is now updated: https://github.com/ubuntu/microk8s/issues/684

Yes, K8s could work with only private interfaces. Do you think we should run with everything closed until the user says something like `microk8s.expose`, or `microk8s.expose apiserver`?

**Comment by jareks** [comment]
Yes, I think everything should be closed by default.
My rationale is as follow:
- I am installing isolated k8s via snap on my host
- I am going to use my host's shell (microk8s.* commands) to manage it
- that's the default way of using microk8s and it doesn't require exposing ports to outside

Now regarding how to implement that - if k8s should bind to different interfaces or if it should have separated interface I am not sure.

BTW, @ktsakalozos the link you provided seems incorrect - it is to this PR itself. I was wondering where are docs PRs?

**Comment by ktsakalozos** [comment]
Sorry about that, here is the link https://microk8s.io/docs/ports

**Comment by jareks** [comment]
Awesome, I confirm update is publicly visible now. Thanks!
