### ISSUE TITLE
microk8s.helm returns Eror: could not find tiller

### ISSUE THREAD

**Issue by davidthewatson** [ubuntu/microk8s#695]
I've installed microk8s on ubuntu 19.04 with:

    snap install microk8s --classic --edge

I then enable helm:

    microk8s.enable helm

which produces:

    Enabling Helm
    Helm is enabled

I then issue:

    microk8s.helm version

which produces:

    Client: &version.Version{SemVer:"v2.14.3",     GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085",  GitTreeState:"clean"}
    Error: could not find tiller

For some reason, tiller does not install properly on v2.14.3.

[inspection-report-20191001_135328.tar.gz](https://github.com/ubuntu/microk8s/files/3677969/inspection-report-20191001_135328.tar.gz)

**Comment by balchua** [comment]
Enabling helm in microk8s does not explicitly install tiller.

Also Kubernetes 1.16 disabled the deprecated apis.  Helm/tiller 2.14.3 still uses them.  2.15.0 will fix that.  You can also use their canary release.

https://github.com/helm/helm/issues/6374

**Comment by davidthewatson** [comment]
Sorry about that. Here's the additional detail that I forgot:
```
$ microk8s.helm init
$HELM_HOME has been configured at /home/watson/.helm.
Error: error installing: the server could not find the requested resource
```
Of course, this is after the helm enable.

**Comment by balchua** [comment]
@davidthewatson yeah that's due to the disabled api in kubernetes 1.16.
Thanks

**Comment by ktsakalozos** [comment]
While we wait for a helm release [1] we can:
-  use MicroK8s v1.15 with sudo snap install microk8s --classic --channel=1.15/stable
-  go through the issue [2] and try any workarounds described there.

Apologies for any inconvenience.

[1] https://github.com/helm/helm/releases
[2] helm/helm#6374


Related to:
https://github.com/ubuntu/microk8s/issues/70#issuecomment-537832749

**Comment by andrewfinnell** [comment]
The following command worked quite well for me

```
microk8s.helm init --override spec.selector.matchLabels.'name'='tiller',spec.selector.matchLabels.'app'='helm' --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | microk8s.kubectl apply -f -
```

**Comment by jon-dearaujo** [comment]
> The following command worked quite well for me
> 
> ```
> microk8s.helm init --override spec.selector.matchLabels.'name'='tiller',spec.selector.matchLabels.'app'='helm' --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | microk8s.kubectl apply -f -
> ```

This allows the creation of Tiller's deployment and service but when I tried `microk8s.helm version` again I got the same `Error: cannot connect to Tiller`.

**Comment by balchua** [comment]
This can be closed now.  Helm 2.15.1 is now merged.
@ktsakalozos

**Comment by ktsakalozos** [comment]
Indeed, the latest helm is on edge and should reach stable with the next patch release (1.16.3)

**Comment by zbyte64** [comment]
Having this issue, fresh install today:

```
~$ microk8s.helm version
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Error: could not find tiller
```

**Comment by balchua** [comment]
@zbyte64 can you check tiller pod?  Also after enabling helm, did you run `microk8s.helm init`?

**Comment by pmm-sumo** [comment]
Seems that helm is still on v0.16.0 and needs to be updated: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.helm.sh#L13
