### ISSUE TITLE
Helm does not show up in microk8s.status

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#699]
The helm addon does not have a corresponding pod so the `microk8s.status` script [1] need to be updated to check for the existence of the helm binary before reporting the addon enabled or disabled.

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-status.wrapper

**Comment by balchua** [comment]
@ktsakalozos i think we can close this issue now.

**Comment by ktsakalozos** [comment]
Thanks @balchua
