### ISSUE TITLE
Migrate this to either ubuntu/ or CanonicalLtd/ org?

### ISSUE THREAD

**Issue by marcoceppi** [ubuntu/microk8s#7]
Seems it'd be a better fit under either of those orgs, or even kubernetes-incubator 🤔

**Comment by ktsakalozos** [comment]
We will need to be added to those GH orgs first.

**Comment by ktsakalozos** [comment]
kubernetes-incubator is interesting also, there must be some requirements to get there.

**Comment by marcoceppi** [comment]
I'm inquiring now. I am a member of the other two orgs and can start the
process, but let's see if we can add this as an incubator project

**Comment by BenHall** [comment]
The incubator has been deprecated (https://github.com/kubernetes/community/pull/1979).

Instead, it's now up to the related SIG (https://github.com/kubernetes/community/blob/master/sig-list.md) to sponsor a new subproject.

**Comment by CalvinHartwell** [comment]
> We will need to be added to those GH orgs first.

You will need to raise a ticket for this internally, it can take a while unless you speak to the right people. If you need help with this let me know.

**Comment by tvansteenburgh** [comment]
https://github.com/ubuntu/microk8s
