### ISSUE TITLE
enable.fluentd creates OLD elastic (6.5.1) & kibana (6.3.2)

### ISSUE THREAD

**Issue by DF-ui** [ubuntu/microk8s#701]
`sudo microk8s.enable fluentd`

works fine and links are available with  "kubectl cluster-info".

Its very conveniently, but microk8s install old elasticsearch 6.5.1 and old kibana 6.3.2. Metrics in old versions dont work correctly for now.

How can I update them for modern versions (7.3.2 or 7.4.0)? 
Or maybe you can update them in newer version of microk8s?

Thx.

**Comment by ktsakalozos** [comment]
Hi @DF-ui to update the fluentd addon we need to update (if needed) the script at https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.fluentd.sh and probably the yaml manifests in https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions/fluentd based on the instructions found in You will need to follow the instructions at https://docs.fluentd.org/container-deployment/kubernetes. To rebuild the snap have a look at https://github.com/ubuntu/microk8s/blob/feature/dev-docs/docs/build-the-snap-from-source.md .

Thank you for your help.

**Comment by benton** [comment]
Is the `fluentd` addon even available now? I'm running microk8s on a set of Raspberry Pi 4 systems, and want to try it out, but it does not seem to be there:

    root@k8m1:~# snap list microk8s
    Name      Version  Rev   Tracking     Publisher   Notes
    microk8s  v1.18.0  1296  1.18/stable  canonical✓  classic

    root@k8m1:~# microk8s enable fluentd
    Nothing to do for fluentd

    root@k8m1:~# microk8s status
    microk8s is running
    addons:
    dns: enabled
    ingress: enabled
    storage: enabled
    dashboard: disabled
    helm: disabled
    helm3: disabled
    kubeflow: disabled
    metallb: disabled
    metrics-server: disabled
    rbac: disabled
    registry: disabled

**Comment by ktsakalozos** [comment]
Hi @benton , the fluentd addon is not available for arm64. I believe the fluentd integration with k8s is not available [1].

[1] https://github.com/fluent/fluentd-kubernetes-daemonset/issues/407#issuecomment-589968497
