### ISSUE TITLE
Update containerd to 1.3.0

### ISSUE THREAD

**Issue by amouat** [ubuntu/microk8s#702]
The latest release of containerd - 1.3.0 - is a major step forward in functionality https://github.com/containerd/containerd/releases/tag/v1.3.0 and it would be great to move to it as standard asap.

In particular, it includes support for pulling from registries that have their own TLS cert. In some cases this is essential for securely pulling from private registries. The microk8s docs currently indicate that this is possible (see the "Secure registry" section here https://microk8s.io/docs/working and the link to https://github.com/containerd/cri/blob/master/docs/registry.md), but it's not, as the functionality isn't present in the 1.2.5 version of containerd that is currently shipped.

**Comment by ktsakalozos** [comment]
Containerd 1.3.0 came out 10 days ago https://github.com/containerd/containerd/releases

Updating MicroK8s should be as easy are updating the commit hash we use to build containerd and the respective runc https://github.com/ubuntu/microk8s/blob/master/build-scripts/set-env-variables.sh#L20 .

**Comment by amouat** [comment]
FWIW I tried to update myself and failed despite several attempts - you can read the details on the Kubernetes slack: https://kubernetes.slack.com/archives/CAUNWQ85V/p1570188839178700

Thanks for the suggestion though.

**Comment by balchua** [comment]
@ktsakalozos i think we can close this one now that we have merged the pr. Thanks

**Comment by ktsakalozos** [comment]
Thank @balchua.

@amouat containerd 1.3.0 is on edge (`snap install microk8s --classic --channel=edge`) and should reach stable soon (with v1.16.3).

**Comment by amouat** [comment]
Can we reopen this? I went to try the new version and found the change had been rolled back because of #813  :cry:

**Comment by balchua** [comment]
Hi @amouat there is a pr to bring back containerd 1.3.1 https://github.com/ubuntu/microk8s/pull/838
This one will be using the config v2 which can work with gpu.  But it may land in 1.18 microk8s.

**Comment by amouat** [comment]
Thanks. I see there are even more breaking configuration changes in containerd :sob:
