### ISSUE TITLE
Add to documentation about imagePullPolicy for locally built images without a registry

### ISSUE THREAD

**Issue by gostaj** [ubuntu/microk8s#707]
@balchua helped me fix an issue https://github.com/ubuntu/microk8s/issues/704 when my deployment failed for an image built locally without a registry. 

The solution was to add
`imagePullPolicy: Never`
to the deployment.

I think it would be great to include this information under 
**"Working with locally built images without a registry"**
at https://microk8s.io/docs/working

**Comment by ktsakalozos** [comment]
Thank you @gostaj and @balchua for working on this. The PR with the fix in our docs is under review.
