### ISSUE TITLE
Creating a sample user link in microk8s output no longer valid

### ISSUE THREAD

**Issue by knkski** [ubuntu/microk8s#708]
As of Sep 16th according to the kubernetes dashboard wiki git log, the "Creating sample user" page no longer exists that's linked in the microk8s dashboard enable script:

https://github.com/ubuntu/microk8s/blob/5b349a4a1a6492a9a2357db37053835e13ba98ff/microk8s-resources/actions/enable.dashboard.sh#L17

I don't see any indication of where the information may have gone to

**Comment by balchua** [comment]
The docs were moved to https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

**Comment by ktsakalozos** [comment]
Thank you @knkski, @balchua for reporting this.
