### ISSUE TITLE
Can't enable Knative

### ISSUE THREAD

**Issue by zy445566** [ubuntu/microk8s#714]
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

 WARNING:  IPtables FORWARD policy is DROP. Consider enabling traffic forwarding with: sudo iptables -P FORWARD ACCEPT 
The change can be made persistent with: sudo apt-get install iptables-persistent
WARNING:  Docker is installed. 
File "/etc/docker/daemon.json" does not exist. 
You should create it and add the following lines: 
{
    "insecure-registries" : ["localhost:32000"] 
}
and then restart docker with: sudo systemctl restart docker
Building the report tarball
  Report tarball is at /var/snap/microk8s/920/inspection-report-20191011_145050.tar.gz
I use：
```
sudo snap install --classic microk8s
```
# Problem
```sh
echo 'N;' | microk8s.enable knative
output:
# ...
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
.Unable to connect to the server: net/http: TLS handshake timeout
.....................................................................
```
I kown microk8s.config get password,but in terminal,how to input password.

**Comment by ceefour** [comment]
Note to those having same problem: I also got this issue and what I did was just wait, I think it took about 15-20 minutes to get pas this point:

```
instance.config.istio.io/attributes created
destinationrule.networking.istio.io/istio-policy created
destinationrule.networking.istio.io/istio-telemetry created
Istio is starting
Waiting for Istio to be ready
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?
........................................................................................................................

*********VERY LONG TIME HERE********

............................................................
.............
Installing Knative CRDs
customresourcedefinition.apiextensions.k8s.io/apiserversources.sources.knative.dev created
customresourcedefinition.apiextensions.k8s.io/brokers.eventing.knative.dev created
```

but resolved just by waiting and don't interrupt the command prompt..
