### ISSUE TITLE
Error enabling helm

### ISSUE THREAD

**Issue by containerwriter** [ubuntu/microk8s#717]
Here's my inspection report (if dragging and dropping is working):

[inspection-report-20191012_133256.tar.gz](https://github.com/ubuntu/microk8s/files/3721150/inspection-report-20191012_133256.tar.gz)

I was ready to install some pods, so I wanted to install helm, but this happened:

$ microk8s.enable helm
Enabling Helm
Fetching helm version v2.14.3.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) Problem with the SSL CA cert (path? access rights?)
Failed to enable helm

**Comment by ktsakalozos** [comment]
Can you please use the edge channel? `sudo snap install microk8s --classic --edge`

This has been addressed in a past issue and should reach stable really soon.

**Comment by containerwriter** [comment]
This worked as advertised. Thanks for the response. Closing.

**Comment by vadimkhm** [comment]
Hi guys! Can anyone help me with this, it was downloadable in the morning... Thanks.
I am on the latest stable version. The Internet is ok, other things are being downloaded normally.

microk8s enable helm
Enabling Helm
Fetching helm version v2.16.7.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 24.1M    0 16384    0     0    257      0 27:19:06  0:01:03 27:18:03     0
curl: (56) GnuTLS recv error (-54): Error in the pull function.
Failed to enable helm

**Comment by ktsakalozos** [comment]
@vadimkhm does the problem persist? I was just able to get the addon running.

**Comment by vadimkhm** [comment]
@ktsakalozos thank you for checking, I figure out that the internet provider was blocking specific URLs, now all is good and all components are connected and working!
