### ISSUE TITLE
networking in microk8s

### ISSUE THREAD

**Issue by dustinkirkland** [ubuntu/microk8s#72]
This issue probably stems from my own confusion about the network that's created and being used by microk8s...

"kubectl get all" shows my services running on a 10.152.183.* network.  But on my laptop, I don't see any bridge or interface associated with this subnet.  What/where is this network?

On a related note, I've killed my wifi and put my laptop in airplane mode.  I'd expect to continue to be able to hit my locally running kubernetes services without wired/wireless uplink.  But I can't.  What's going on here?

**Comment by gbrayut** [comment]
I was curious my self too how that works. Looks like it creates a docker0 interface:
```
root@k8s:~# ip -o -4 a s
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
2: docker0    inet 172.17.0.1/16 scope global docker0\       valid_lft forever preferred_lft forever
21: eth0    inet 192.168.4.81/24 brd 192.168.4.255 scope global eth0\       valid_lft forever preferred_lft forever
```
And while checking the status of the various services using `systemctl status snap\*` I see snap.microk8s.daemon-apiserver.service has a --service-cluster-ip-range=10.152.183.0/24 parameter

I'm attempting to run this in a privileged LXD container, but it looks like there are still some errors in the logs:

```
journalctl -u snap.microk8s.daemon-kubelet
journalctl -u snap.microk8s.daemon-apiserver
journalctl -u snap.microk8s.daemon-docker
journalctl -u snap.microk8s.daemon-proxy 
```
I also saw reference to a cr0 bridge, but I dont see that. So maybe I'm having some issues due to it being in LXD.

**Comment by ktsakalozos** [comment]
Hi @dustinkirkland ,

K8s does some fancy networking configurations that I honesty do not fully understand either! The 10.158.183.X are virtual IPs used in DNAT rules. You can start unraveling the routing paths with `sudo iptables -t nat -L -n -v`. Here is what I have over here:
```
sudo iptables -t nat -L -n -v
[sudo] password for jackal: 
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
 1794  545K KUBE-PORTALS-CONTAINER  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
    0     0 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
    0     0 KUBE-NODEPORT-CONTAINER  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
19013 1258K KUBE-PORTALS-HOST  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* handle ClusterIPs; NOTE: this must be before the NodePort rules */
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL
17089 1040K KUBE-NODEPORT-HOST  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL /* handle service NodePorts; NOTE: this must be the last rule in the chain */

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   16  1573 RETURN     all  --  *      *       10.17.17.0/24        224.0.0.0/24        
    0     0 RETURN     all  --  *      *       10.17.17.0/24        255.255.255.255     
    0     0 MASQUERADE  tcp  --  *      *       10.17.17.0/24       !10.17.17.0/24        masq ports: 1024-65535
    0     0 MASQUERADE  udp  --  *      *       10.17.17.0/24       !10.17.17.0/24        masq ports: 1024-65535
    0     0 MASQUERADE  all  --  *      *       10.17.17.0/24       !10.17.17.0/24       
   16  1627 RETURN     all  --  *      *       10.18.18.0/24        224.0.0.0/24        
    0     0 RETURN     all  --  *      *       10.18.18.0/24        255.255.255.255     
    0     0 MASQUERADE  tcp  --  *      *       10.18.18.0/24       !10.18.18.0/24        masq ports: 1024-65535
    0     0 MASQUERADE  udp  --  *      *       10.18.18.0/24       !10.18.18.0/24        masq ports: 1024-65535
    0     0 MASQUERADE  all  --  *      *       10.18.18.0/24       !10.18.18.0/24       
   94 17149 MASQUERADE  all  --  *      *       10.26.36.0/24       !10.26.36.0/24        /* generated for LXD network lxdbr0 */
   16  1573 RETURN     all  --  *      *       192.168.122.0/24     224.0.0.0/24        
    0     0 RETURN     all  --  *      *       192.168.122.0/24     255.255.255.255     
    0     0 MASQUERADE  tcp  --  *      *       192.168.122.0/24    !192.168.122.0/24     masq ports: 1024-65535
    0     0 MASQUERADE  udp  --  *      *       192.168.122.0/24    !192.168.122.0/24     masq ports: 1024-65535
    0     0 MASQUERADE  all  --  *      *       192.168.122.0/24    !192.168.122.0/24    
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
   15  1533 MASQUERADE  all  --  *      *       10.0.3.0/24         !10.0.3.0/24         

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           

Chain KUBE-NODEPORT-CONTAINER (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain KUBE-NODEPORT-HOST (1 references)
 pkts bytes target     prot opt in     out     source               destination         

Chain KUBE-PORTALS-CONTAINER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            10.152.183.1         /* default/kubernetes:https */ tcp dpt:443 redir ports 41421
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            10.152.183.87        /* kube-system/heapster: */ tcp dpt:80 redir ports 42711
    0     0 REDIRECT   udp  --  *      *       0.0.0.0/0            10.152.183.10        /* kube-system/kube-dns:dns */ udp dpt:53 redir ports 40349
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            10.152.183.10        /* kube-system/kube-dns:dns-tcp */ tcp dpt:53 redir ports 44303
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            10.152.183.8         /* kube-system/kubernetes-dashboard: */ tcp dpt:443 redir ports 39637
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            10.152.183.81        /* kube-system/monitoring-grafana: */ tcp dpt:80 redir ports 41243
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            10.152.183.64        /* kube-system/monitoring-influxdb:http */ tcp dpt:8083 redir ports 35037
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            10.152.183.64        /* kube-system/monitoring-influxdb:api */ tcp dpt:8086 redir ports 38495

Chain KUBE-PORTALS-HOST (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.152.183.1         /* default/kubernetes:https */ tcp dpt:443 to:192.168.1.23:41421
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.152.183.87        /* kube-system/heapster: */ tcp dpt:80 to:192.168.1.23:42711
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            10.152.183.10        /* kube-system/kube-dns:dns */ udp dpt:53 to:192.168.1.23:40349
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.152.183.10        /* kube-system/kube-dns:dns-tcp */ tcp dpt:53 to:192.168.1.23:44303
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.152.183.8         /* kube-system/kubernetes-dashboard: */ tcp dpt:443 to:192.168.1.23:39637
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.152.183.81        /* kube-system/monitoring-grafana: */ tcp dpt:80 to:192.168.1.23:41243
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.152.183.64        /* kube-system/monitoring-influxdb:http */ tcp dpt:8083 to:192.168.1.23:35037
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            10.152.183.64        /* kube-system/monitoring-influxdb:api */ tcp dpt:8086 to:192.168.1.23:38495
```

You can see here the docker0 interface rule @gbrayut mentioned.

Also note that kube-proxy is configured with in userspace mode (https://stackoverflow.com/questions/36088224/what-does-userspace-mode-means-in-kube-proxys-proxy-mode).

I do not know yet anything about the airplane mode. We will look into this.

**Comment by ktsakalozos** [comment]
@dustinkirkland could you try:
`sudo snap disable microk8s` followed by `sudo snap enable microk8s`?

**Comment by safderali5** [comment]
When I do microk8s.enable dns,  the kubedns installed is crash looping. i tried adding rule to ufw, no ufw installed on system. don't know to go farward from here?
 
k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.152.183.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.152.183.1:443: getsockopt: no route to host

**Comment by ktsakalozos** [comment]
Hi @safderali5,

Do you see anything interesting on the `microk8s.kubectl logs pod/kube-dns-<something> -n kube-system` and the `microk8s.kubectl describe` of the Pod? Are you on `--beta` or on `--edge`? Did you try to `sudo snap disable microk8s` and then `sudo snap enable microk8s`?

There is not much in your error report I can work with. Is this reproducible (at least in you machine)? How?

Thank you

**Comment by safderali5** [comment]
@ktsakalozos  Here are the logs for kubedns. It looks like for reason the kubedns pod liveness and readiness probes are failing.
I have already tried your suggestions they did not work for me.

$ microk8s.kubectl logs -n kube-system pod/kube-dns-864b8bdc77-4q6dx kubedns

I0823 07:16:41.942559       1 dns.go:48] version: 1.14.6-3-gc36cb11
I0823 07:16:41.943457       1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
I0823 07:16:41.943498       1 server.go:112] FLAG: --alsologtostderr="false"
I0823 07:16:41.943506       1 server.go:112] FLAG: --config-dir="/kube-dns-config"
I0823 07:16:41.943512       1 server.go:112] FLAG: --config-map=""
I0823 07:16:41.943517       1 server.go:112] FLAG: --config-map-namespace="kube-system"
I0823 07:16:41.943520       1 server.go:112] FLAG: --config-period="10s"
I0823 07:16:41.943526       1 server.go:112] FLAG: --dns-bind-address="0.0.0.0"
I0823 07:16:41.943529       1 server.go:112] FLAG: --dns-port="10053"
I0823 07:16:41.943536       1 server.go:112] FLAG: --domain="cluster.local."
I0823 07:16:41.943544       1 server.go:112] FLAG: --federations=""
I0823 07:16:41.943551       1 server.go:112] FLAG: --healthz-port="8081"
I0823 07:16:41.943555       1 server.go:112] FLAG: --initial-sync-timeout="1m0s"
I0823 07:16:41.943558       1 server.go:112] FLAG: --kube-master-url=""
I0823 07:16:41.943571       1 server.go:112] FLAG: --kubecfg-file=""
I0823 07:16:41.943574       1 server.go:112] FLAG: --log-backtrace-at=":0"
I0823 07:16:41.943581       1 server.go:112] FLAG: --log-dir=""
I0823 07:16:41.943585       1 server.go:112] FLAG: --log-flush-frequency="5s"
I0823 07:16:41.943588       1 server.go:112] FLAG: --logtostderr="true"
I0823 07:16:41.943591       1 server.go:112] FLAG: --nameservers=""
I0823 07:16:41.943596       1 server.go:112] FLAG: --stderrthreshold="2"
I0823 07:16:41.943600       1 server.go:112] FLAG: --v="2"
I0823 07:16:41.943603       1 server.go:112] FLAG: --version="false"
I0823 07:16:41.943609       1 server.go:112] FLAG: --vmodule=""
I0823 07:16:41.943656       1 server.go:194] Starting SkyDNS server (0.0.0.0:10053)
I0823 07:16:41.943917       1 server.go:213] Skydns metrics enabled (/metrics:10055)
I0823 07:16:41.943929       1 dns.go:146] Starting endpointsController
I0823 07:16:41.943934       1 dns.go:149] Starting serviceController
I0823 07:16:41.944043       1 sync.go:177] Updated upstreamNameservers to [8.8.8.8 8.8.4.4]
I0823 07:16:41.944127       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0823 07:16:41.944150       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
E0823 07:16:41.944737       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.152.183.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.152.183.1:443: connect: network is unreachable
E0823 07:16:41.945143       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?resourceVersion=0: dial tcp 10.152.183.1:443: connect: network is unreachable
I0823 07:16:42.444395       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0823 07:16:42.944394       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
E0823 07:16:42.945768       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Get https://10.152.183.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.152.183.1:443: connect: network is unreachable
E0823 07:16:42.947065       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?resourceVersion=0: dial tcp 10.152.183.1:443: connect: network is unreachable
I0823 07:16:43.444385       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
I0823 07:16:43.944703       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...


$ microk8s.kubectl describe -n kube-system pod/kube-dns-864b8bdc77-4q6dx
Events:
  Type     Reason     Age              From                  Message
  ----     ------     ----             ----                  -------
  Warning  Unhealthy  1m               kubelet, <hostname>  Liveness probe failed: Get http://10.1.1.56:10054/healthcheck/dnsmasq: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  1m               kubelet, <hostname>  Liveness probe failed: Get http://10.1.1.56:10054/metrics: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  1m (x8 over 2m)  kubelet, <hostname>  Readiness probe failed: Get http://10.1.1.56:8081/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by ktsakalozos** [comment]
Could you also share the output of `sudo iptables -t nat -L -n -v` , `sudo journalctl -u snap.microk8s.daemon-kubelet.service`,  `sudo journalctl -u snap.microk8s.daemon-apiserver.service` , `sudo journalctl -u snap.microk8s.daemon-proxy.service`. Did you also enable traffic forwarding? `sudo iptables -P FORWARD ACCEPT`.

I see that the dns pod cannot reach the API server to query for pods and services. There must be something in the network configuration in your system blocking the traffic from the pods to the services. Pods and services are on separate subnets. I hope to find a hint on the logs of the kubelet, apiserver and kube-proxy.

**Comment by safderali5** [comment]
@ktsakalozos  Thanks for explanation, Now I understand what real problem is. The iptables rules are missing, somehow they are not created upon installation e.g KUBE-SERVICES, KUBE-FORWARD and other rules. I cannot mess with iptables rules on system, so I have decided to move back to minikube. Thanks a lot for help.

**Comment by TeNNoX** [comment]
I think I am experiencing the same problem. I cannot access any of the Cluster-IPs.
Using microk8s (snap 149) on `Ubuntu 16.04.5 LTS`.

`sudo iptables -t nat -L -n -v`: http://termbin.com/wj99
`sudo journalctl -u snap.microk8s.daemon-kubelet.service`: http://termbin.com/qj8y
`sudo journalctl -u snap.microk8s.daemon-apiserver.service`: http://termbin.com/an8v
`sudo journalctl -u snap.microk8s.daemon-proxy.service`: http://termbin.com/duh8
`sudo iptables -P FORWARD ACCEPT` - no output

But I just read that there is a channel called `--edge`, and I tried installing that instead - and this seems to work now.

I will still post this comment as it might still help in some way.

**Comment by akaihola** [comment]
In addition to `sudo iptables -P  FORWARD ACCEPT`, I needed to do this on Fedora 29:
```bash
sudo iptables -D FORWARD 20
```
since the 20th rule in the FORWARD chain was:
```
16 1264 REJECT all -- any any anywhere anywhere reject-with icmp-host-prohibited
```

See also #316.

**Comment by urbandroid** [comment]
I have a problem that is something similar if anyone find the root cause if they share with me that will be great. 

My problem is that whenever i disconnect wifi service that is reachable when connected becomes unreachable. 

Both of them:

default     service/kubernetes         ClusterIP   10.152.183.1     <none>        443/TCP   7d5h
default     service/nginx-deployment   ClusterIP   10.152.183.203   <none>        80/TCP    6d20h

 But kubectl get all --all-namespaces seems to work when in start if wifi connected but without connecting once per boot kubectl can't connect to api server either.
