### ISSUE TITLE
Separete CA for the aggregation layer

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#721]
Currently we use the same CA to authorize users and the aggregation apiserver requests [2]. As described in [1] this is not a good practice.

This issue seems to be related with https://github.com/ubuntu/microk8s/pull/664 

[1] https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#ca-reusage-and-conflicts
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kube-apiserver

**Comment by giner** [comment]
Best practices:
- https://kubernetes.io/docs/setup/best-practices/certificates/#single-root-ca
- https://kubernetes.io/docs/setup/best-practices/certificates/#all-certificates
- https://kubernetes.io/docs/setup/best-practices/certificates/#certificate-paths

**Comment by balchua** [comment]
@ktsakalozos this is resolved.  We can close this one now.

**Comment by ktsakalozos** [comment]
Yes, thank you
