### ISSUE TITLE
Containerd-env not working

### ISSUE THREAD

**Issue by davigar15** [ubuntu/microk8s#724]
Hello,

I am facing issues with containerd in microk8s.

Environment: I have set up an environment with two VMs, one with a squid http proxy, and another one with microk8s.

1. SETUP SQUID
**Squid proxy VM**: 10.28.55.187
```bash
multipass@squid:~$ sudo apt update
multipass@squid:~$ sudo apt -y install squid
multipass@squid:~$ sudo systemctl start squid
multipass@squid:~$ sudo systemctl enable squid
```

By default, it denies everything. Test it:
```bash
multipass@squid:~$ export https_proxy=http://10.28.55.187:3128
multipass@squid:~$ curl https://rocks.canonical.com:443
curl: (56) Received HTTP code 403 from proxy after CONNECT
multipass@squid:~$ export https_proxy=
multipass@squid:~$ curl https://rocks.canonical.com:443
multipass@squid:~$ 
```

2. SETUP MICROK8S
**Microk8s VM**: 10.28.55.202
```bash
multipass@microk8s:~$ export PATH=$PATH:/snap/bin
multipass@microk8s:~$ sudo snap install microk8s --classic --channel 1.14/stable
multipass@microk8s:~$ sudo route del default
multipass@microk8s:~$ sudo ip route add default via 10.28.55.187
multipass@microk8s:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.28.55.187    0.0.0.0         UG    0      0        0 ens3
10.28.55.0      0.0.0.0         255.255.255.0   U     0      0        0 ens3
10.28.55.1      0.0.0.0         255.255.255.255 UH    100    0        0 ens3
```

Now I'm going to configure the proxy in containerd.
```bash
multipass@microk8s:~$ sudo vim /var/snap/microk8s/current/args/containerd-env
multipass@microk8s:~$ sudo cat /var/snap/microk8s/current/args/containerd-env | grep -vE ^#
HTTPS_PROXY=http://10.28.55.187:3128

ulimit -n 65536 || true
multipass@microk8s:~$ sudo systemctl restart snap.microk8s.daemon-containerd.service
```

In this state, the proxy should deny everything. We can check that executing the following in microk8:

```bash
multipass@microk8s:~$ curl https://rocks.canonical.com:443
curl: (56) Received HTTP code 403 from proxy after CONNECT
```

3. CONFIGURE SQUID TO ENABLE ACCESS TO ROCKS
Edit the squid.conf file adding these two lines:
```
acl microk8s dstdomain rocks.canonical.com # around line 995
http_access allow microk8s # around line 1200, above "http_access deny all"
```

```bash
multipass@squid:~$ sudo vim /etc/squid/squid.conf
multipass@squid:~$ sudo systemctl restart squid
```

4. TEST THAT PROXY WORKS IN MICROK8S

```bash
multipass@microk8s:~$ export https_proxy=http://10.28.55.187:3128
multipass@microk8s:~$ curl https://rocks.canonical.com:443 # WORKED!
multipass@microk8s:~$ 
```

It's working.

5. TEST THAT PROXY IN CONTAINERD WORKS

```bash
multipass@microk8s:~$ sudo microk8s.ctr image pull rocks.canonical.com:443/canonicalosm/light-ui:release6
rocks.canonical.com:443/canonicalosm/light-ui:release6: resolving      |--------------------------------------| 
elapsed: 30.0s                                          total:   0.0 B (0.0 B/s)                                         
ctr: failed to resolve reference "rocks.canonical.com:443/canonicalosm/light-ui:release6": failed to do request: Head https://rocks.canonical.com:443/v2/canonicalosm/light-ui/manifests/release6: dial tcp 162.213.33.224:443: i/o timeout
```

Observation: As we can see, the proxy is not successfully set up in containerd. It is important to mention that if we do `sudo tail -f /var/log/squid/access.log` in the squid VM, we'll see the request for the curl commands, but we won't see anything when we try to pull images with containerd.

**Comment by ktsakalozos** [comment]
@davigar15 I was able to pull the image behind a proxy with `sudo microk8s.ctr image pull rocks.canonical.com:443/canonicalosm/light-ui:release6` by adding the `HTTPS_PROXY` variable in  `/etc/environment`.

To see the effect of  `HTTPS_PROXY` in ` /var/snap/microk8s/current/args/containerd-env` tell containerd to pull the image with something like `sudo microk8s.kubectl run nginx --image=rocks.canonical.com:443/canonicalosm/light-ui:release6 --replicas=1`.

**Comment by davigar15** [comment]
@ktsakalozos Thank you very much for your time. Effectively, I was testing the `microk8s.ctr` command without putting the HTTPS_PROXY in /etc/environment. That was causing me a bit of a confusion.

May be, if you consider, it would be nice to add some more information about this in the microk8s docs.

Thanks again!
