### ISSUE TITLE
Microk8s cluster nodes staying registered after cluster upgrade

### ISSUE THREAD

**Issue by CalvinHartwell** [ubuntu/microk8s#727]
Hi all, 

After hitting an issue with the SSL Library (https://github.com/ubuntu/microk8s/issues/720), I upgraded microk8s on each machine to the edge snap. I had previously tried to create a microk8s cluster before the upgrade which didn't work. 

After rolling out the new snap on each of the machines in my cluster, I noticed that the node was appearing twice when I ran microk8s.kubectl get nodes: 

```
ubuntu@battleship:/etc/systemd/system$ microk8s.kubectl get nodes 
NAME                     STATUS     ROLES    AGE    VERSION
battlecruiser.microk8s   NotReady   <none>   172m   v1.16.1
battleship.microk8s      NotReady   <none>   40h    v1.16.1
submarine.microk8s       NotReady   <none>   3h4m   v1.16.1
ubuntu                   NotReady   <none>   40h    v1.16.0
```

In this case, "192.168.0.21" is the same IP used for the "ubuntu" host and "battleship" host. 

I assume the nodes are preserved in order for upgrades to correctly work, but perhaps we should have a way to clear a cluster config? microk8s.clear-nodes or similar?

I guess another approach would be to make sure the add-node/join node functionality ensures that nodes cannot be added twice and to detect/remove k8s nodes which have the same IP address. 

Node dumps attached:
[submarine-inspection-report-20191015_144633.tar.gz](https://github.com/ubuntu/microk8s/files/3729960/submarine-inspection-report-20191015_144633.tar.gz)
[battlecruiser-inspection-report-20191015_144639.tar.gz](https://github.com/ubuntu/microk8s/files/3729961/battlecruiser-inspection-report-20191015_144639.tar.gz)
[battleship-inspection-report-20191015_144755.tar.gz](https://github.com/ubuntu/microk8s/files/3729962/battleship-inspection-report-20191015_144755.tar.gz)

Cheers,

- Calvin

**Comment by usersina** [comment]
I also have a scenario where I might execute the `join` command in an ansible script more than once. It would save the work needed to get the standard output of `microk8s kubectl get nodes -o wide` then comparing the IPs before adding again.
