### ISSUE TITLE
kubectl connection error

### ISSUE THREAD

**Issue by wallyworld** [ubuntu/microk8s#73]
$ microk8s.kubectl get all
The connection to the server 127.0.0.1:8080 was refused - did you specify the right host or port?

$ snap list
Name                 Version                    Rev   Tracking  Developer      Notes
microk8s             v1.11.0                    104   beta      canonical      classic

**Comment by ktsakalozos** [comment]
Hi @wallyworld ,

Can you make sure you do not have any other service running on port 8080. Could you also share the output of `journalctl -u snap.microk8s.daemon-apiserver.service`?

Thank you for reporting this.

**Comment by wallyworld** [comment]
Idon't seem to have anything running on port 8080.
The service log does seems to show an issue starting up due to no default routes. 

https://pastebin.ubuntu.com/p/RCwhf5wbvp/

(pods, nodes, etc.), comma separated. The individual override format: resource[.group]#size, where resource is lowercase plural (no version), group is optional, and size is a number. It takes effect when watch-cache is enabled. Some resources (replicationcontrollers, endpoints, nodes, pods, services, apiservices.apiregistration.k8s.io) have system defaults set by heuristics, others default to default-watch-cache-size
Jul 20 22:08:56 wallyworld microk8s.daemon-apiserver[2978]: error: Unable to find suitable network address.error='No default routes.'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this.
Jul 20 22:08:56 wallyworld systemd[1]: snap.microk8s.daemon-apiserver.service: Service hold-off time over, scheduling restart.
Jul 20 22:08:56 wallyworld systemd[1]: snap.microk8s.daemon-apiserver.service: Scheduled restart job, restart counter is at 5.
Jul 20 22:08:56 wallyworld systemd[1]: Stopped Service for snap application microk8s.daemon-apiserver.
Jul 20 22:08:56 wallyworld systemd[1]: snap.microk8s.daemon-apiserver.service: Start request repeated too quickly.
Jul 20 22:08:56 wallyworld systemd[1]: snap.microk8s.daemon-apiserver.service: Failed with result 'exit-code'.
Jul 20 22:08:56 wallyworld systemd[1]: Failed to start Service for snap application microk8s.daemon-apiserver.

**Comment by hyperbolic2346** [comment]
@ktsakalozos 
@tvansteenburgh was seeing this yesterday as well. He saw it on multipass with xenial and bionic.
