### ISSUE TITLE
Feature request: shared storage with OS X

### ISSUE THREAD

**Issue by jareks** [ubuntu/microk8s#731]
In my team we are using mk8s for local development. It works great because we can use host storage to mount source code directly into containers and edit code with all the benefits of hot reloading.
Unfortunately, that only works for Linux users and we can't run same setup on OS X. It would be truly great if we could use microk8s + multipass to achieve same result. Perhaps it is possible to configure some sort of nfs or sync to share from host to VM and mount into k8s?

There have been other approaches to address similar issues:
http://docker-sync.io/
https://github.com/vapor-ware/ksync
https://github.com/GoogleContainerTools/skaffold
https://devspace.cloud/docs/cli/development/configuration/file-synchronization
https://github.com/okteto/okteto

https://stackoverflow.com/questions/47894378/is-it-possible-to-mount-a-local-computer-folder-to-kubernetes-for-development-l

I think this would be a great addition to microk8s and would help to adopt it outside core Linux users.

**Comment by ktsakalozos** [comment]
@tvansteenburgh @ammarn911 here are some interesting suggestions we could consider for the future.
