### ISSUE TITLE
Storage and initial user experience

### ISSUE THREAD

**Issue by slimjim777** [ubuntu/microk8s#733]
As a new user to microk8s, I've tried installing an application workload, following the "getting started" user instructions. In that process I deployed the application, which needed storage, without storage enabled. The deployment failed, and it took some investigation to realise the error that I made. I then enabled storage, but that did not fix the deployment. Even restarting microk8s did not resolve the issue. To fix the issue, I found that I need to make sure that storage was enabled first before deploying the application.

I ended up having to remove the workload (I actually uninstalled microk8s and reinstalled it), enabled dns and storage and then deployed the workload and everything worked fine.

Since microk8s may be the first experience of k8s for many people, I'm wondering whether it may be better to make some clearer recommendations in the docs around some of the items that need to be
enabled before doing anything. Even, possibly, having DNS and storage on by default and allowing more advanced users to turn them off if needed.

[inspection-report-20191017_135548.tar.gz](https://github.com/ubuntu/microk8s/files/3739664/inspection-report-20191017_135548.tar.gz)

**Comment by evilnick** [comment]
Sorry you had this problem. As MicroK8s is minimal by default it is a deliberate design choice not to enable anything not strictly necessary.

However, we can do much better in docs and I hope you will see we are - there is a big overhaul of docs happening right now (you will see updates, new pages and sections being added pretty much daily). I will leave this issue open until we have updated the getting started section, but please let us know if you find the changes useful.

**Comment by slimjim777** [comment]
The docs have certainly improved and been helpful.

I'm not sure that the docs is the right place to fix the issue. Whilst I understand that you may not want to turn on unnecessary services, it may be helpful if you could catch and log situations where the user is deploying something that needs an extra service enabled. In the case of storage, it's jarring that you can deploy a workload that needs storage when it is not enabled. Also, enabling storage after the fact does not fix the issue.

If the deployment raised an error instead of carrying on, then it would alert the user that they are doing something wrong. As it is, it leads to head scratching for new users.
