### ISSUE TITLE
"Clustering" snap seems to have vanished

### ISSUE THREAD

**Issue by strigona-worksight** [ubuntu/microk8s#734]
`sudo snap install microk8s --classic --channel=1.15/edge/clustering`

Still succeeds, however the cluster specific commands no longer exist. On top of that, my cluster seems to have been downgraded to the non-clustering version of the snap automatically and is essentially dead.

**Comment by strigona-worksight** [comment]
Thanks - will give that a shot.

**Comment by tvansteenburgh** [comment]
@ktsakalozos Might be good to post a comment about that on https://discuss.kubernetes.io/t/microk8s-clustering-preview/7472
