### ISSUE TITLE
Scheduling the first pod on fresh installation triggers restart of microk8s services

### ISSUE THREAD

**Issue by giner** [ubuntu/microk8s#741]
Scheduling the first pod on a fresh installation of microk8s triggers restart of its services which somewhat complicates automated provisioning using tools such as Vagrant.

Here is how to reproduce:
1. Install microk8s
2. Schedule a pod (or enable any plugin which schedules a pod, e.g. enable dns, storage, etc)
3. api server is still available (i.e. microk8s.status --wait-ready will pass successfully)
4. A few seconds later all microk8s services will be restarted and api will not be available for ~10 seconds

What happens is that scheduling a pod triggers creation of `cbr0` interface which adds one more ip to the output of `hostname -I`. `hostname -I` is used in [apiservice-kicker](https://github.com/ubuntu/microk8s/blob/1.15/microk8s-resources/wrappers/apiservice-kicker) to detect changes in host IPs in order to regenerate certificates and restart services.

Thoughts on possible solutions:
- make apiserver reload configuration instead of restart (I have doubts it is possible though)
- ignore IP address added by cbr0 when detecting the changes
- ensure cbr0 is initialized before doing anything else
- kind of dirty one: sleep 5 seconds on the step 3 and wait with `microk8s.status --wait-ready` after scheduling the first pod

**Comment by ktsakalozos** [comment]
@giner, there is a PR up that takes the approach suggested in the second bullet point. Let me know what you think.
