### ISSUE TITLE
High disk usage, is this normal?

### ISSUE THREAD

**Issue by PhilAndrew** [ubuntu/microk8s#742]
Is this normal? I haven't really done anything much with microk8s except let it run for about two weeks.

philip@philipserver:~$ df
Filesystem     1K-blocks      Used Available Use% Mounted on
udev            32916732         0  32916732   0% /dev
tmpfs            6596184      2884   6593300   1% /run
/dev/nvme0n1p2 238797468 186241464  40356020  83% /
tmpfs           32980912         0  32980912   0% /dev/shm
tmpfs               5120         0      5120   0% /run/lock
tmpfs           32980912         0  32980912   0% /sys/fs/cgroup
/dev/nvme0n1p1    523248      6152    517096   2% /boot/efi
/dev/loop0        167680    167680         0 100% /snap/microk8s/826
/dev/loop1         91264     91264         0 100% /snap/core/7713
/dev/loop4         91264     91264         0 100% /snap/core/7917
/dev/loop3        182912    182912         0 100% /snap/microk8s/920
tmpfs            6596180         0   6596180   0% /run/user/1000
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/83c2222836bed82990b618875c52ba6d0b47a6d170605b7b158cc73e934c8bfa/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/83c2222836bed82990b618875c52ba6d0b47a6d170605b7b158cc73e934c8bfa/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/837c68e8429db9da5bea14770f8661dc4876617efdd7e65d05b63e90f051182a/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/71ebb8e01066c2163ea7928de5a84ffb1983167ce4a22cf7da4163d347707188/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/71ebb8e01066c2163ea7928de5a84ffb1983167ce4a22cf7da4163d347707188/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/197b33d7801fb82086cf4f2a7df9a8dbffd045334bfad41c294976ad5315d785/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/f74debdb0c16668873ba0d4fbab496ef3d826e87aec378a16c1edf798446fdec/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/f74debdb0c16668873ba0d4fbab496ef3d826e87aec378a16c1edf798446fdec/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/212358da9feb11399996cac940052a87c03be75593a1eb8b1a4a3db3083bc836/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/7e0150f34ec984e603a11d4397b1ab4997b7dd9e06a50b689c8731ab1eb1e116/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/1352587f35bf04059e8dcd2a55d3da6ed66beb5f77bbcca8df948d416f622c89/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/1352587f35bf04059e8dcd2a55d3da6ed66beb5f77bbcca8df948d416f622c89/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/7d588a26e81bdb152d24f3bd4ec3abf359e1d608fcc353c720a7ede72f8aca88/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/7d588a26e81bdb152d24f3bd4ec3abf359e1d608fcc353c720a7ede72f8aca88/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/d849d516e08ca667761b96e33686d507b1ad391b8865d8aa50c9109822559d59/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/b3952db6318c58bc2fcc89e989ccdc55f2ed1a130747ecade3710847bc3974e4/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/4c5ba52dfe2863d1ddeb11869b5f6517f0c491ff3d0419e784e82078c5e37786/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/4c5ba52dfe2863d1ddeb11869b5f6517f0c491ff3d0419e784e82078c5e37786/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/a195400d37ba49afe379430522d977c66a3d433b69a9d95f4d8157358da2e456/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/c3e902ed14a13da3e5ef30747098140c309f18e4cf7a1d0a7430f29d92e41042/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/d07f6137a4ac79773b136763c9d632cddaf7ea3b773e832de0f9336ce26a5f99/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/3dbd358331f5faa190fa8e9d6a0e8ba281f23f4e32755e0d88fa6d81c91f66cc/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/3dbd358331f5faa190fa8e9d6a0e8ba281f23f4e32755e0d88fa6d81c91f66cc/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/051bfbb4a5a49cb420b31f634662f5b080883557340678f4788efe78c97408e4/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/2b284ea16bca0c27ee18a14747f2e7f9bcd0e285261c046ee8cea41c1a47d69f/rootfs
shm                65536         4     65532   1% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/580ff20812ca8a7d732ff31067e125747970046b3a1d0faccf5a46e6053642ba/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/580ff20812ca8a7d732ff31067e125747970046b3a1d0faccf5a46e6053642ba/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/f9e8fe4c535929cffa81f63c76a1d7afb75c0bd75057a3fc6d03fd201561e7cd/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/f9e8fe4c535929cffa81f63c76a1d7afb75c0bd75057a3fc6d03fd201561e7cd/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/b532269ae4625e3d61a332d546ec2ad1fcc1ff773737194fccfb3fbcaa135880/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/d73303e0196067da03c9d9ee907bc70b7cfb7adf06070877e9b5afac917d5297/rootfs
shm                65536         4     65532   1% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/1c52653e02f3d881d52c105b0b5bd67a9675ef0ee08f602fba41c1dd6fd2e10e/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/1c52653e02f3d881d52c105b0b5bd67a9675ef0ee08f602fba41c1dd6fd2e10e/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/ab8f3d5174aa535913de6b5f76a74efda91f222b0619681b0517dc5078c18abe/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/1196a98d2bb9743ee142a1f0cd8d5bbe55e1479bca0a175b205e954e5c2b1547/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/a3d7119101da041dde3993190d53c193f243c0e14f6d2655d0e625b398b0b5e3/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/a3d7119101da041dde3993190d53c193f243c0e14f6d2655d0e625b398b0b5e3/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/63a3834b5cf8330e05227eb1c56dac95015e70a105b0348f2f4c7ee2f6294b59/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/63a3834b5cf8330e05227eb1c56dac95015e70a105b0348f2f4c7ee2f6294b59/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/fb1474f6ae5d2a32325ab8b1ca46818fd7fd5b1f3540c96ec6fe8665d043df5a/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/61e814b5123704bd4a6e470f798c6b83ee7047111c0133d0f9c3414c0a3ed4a8/rootfs
shm                65536         4     65532   1% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/d17b9956d7c2af7239a51bf8bd1098136e281a145f82e34cea41a40d96ec1e1a/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/d17b9956d7c2af7239a51bf8bd1098136e281a145f82e34cea41a40d96ec1e1a/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/e5d5344cb2c3cedf0f941a40d8e4b13470cf53986f75d34115fb4295942965cc/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/d32bdae17dbb6af7e133be289fb22f1b726f4fdd46d3cf35bc5d55b7033aad10/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/d32bdae17dbb6af7e133be289fb22f1b726f4fdd46d3cf35bc5d55b7033aad10/rootfs
shm                65536         4     65532   1% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/1c310f3166a7e19f86ff9db0d2503b44c2376df996d702a3e24de81cbe48c5e5/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/1c310f3166a7e19f86ff9db0d2503b44c2376df996d702a3e24de81cbe48c5e5/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/be15371cc94c41f1dee98a23153597bcdf48a7fb19ce504b9fd70fbd58390932/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/827afc73a8e11d6034fa7a87c3434e790bccade667c1285e3abe029b06654993/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/883d533f39ccd30830f5c7088fd95d2ed75cd6e6d533866fb6630724cdd6ab90/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/375c8075e802459f858005e725be022f987535a5f92e7857abeb3ee9fd47199f/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/375c8075e802459f858005e725be022f987535a5f92e7857abeb3ee9fd47199f/rootfs
shm                65536         4     65532   1% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/b3ee4a97bf55d09f3412ae5cf12fd0585b9bcfb9ea055eb0f9cbeff46bfb50df/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/b3ee4a97bf55d09f3412ae5cf12fd0585b9bcfb9ea055eb0f9cbeff46bfb50df/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/988f77ae7ef1ef4ff8b48b01f13adb57edf6dba55d9eb4918fb974247fe43197/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/988f77ae7ef1ef4ff8b48b01f13adb57edf6dba55d9eb4918fb974247fe43197/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/6e8037611e49e2d913c433c221e1f5a5c3607429d772f4251a5d68c29b55f030/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/a58835f9b672cae8eb71cb23ad3595695000d1d8869a10fee54ca7323f6e6305/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/d4746b3a343b4a28d048fd56184a4d9f6724c10497f281b73112e54aa6fdb2dd/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/3f23f9a3bd914f66f2d5e7520c8f1d0c38f3e1f077a81c3fd50c07460db72074/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/26ff8f849dd0fdf106c12b155fc62f45c63ac95ef8daa65f3bf5af756b3d8378/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/26ff8f849dd0fdf106c12b155fc62f45c63ac95ef8daa65f3bf5af756b3d8378/rootfs
shm                65536         0     65536   0% /var/snap/microk8s/common/run/containerd/io.containerd.grpc.v1.cri/sandboxes/576ba56e4d4b2872c440cbc966d0e0be077ec56648102a49691c677b9f04da45/shm
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/576ba56e4d4b2872c440cbc966d0e0be077ec56648102a49691c677b9f04da45/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/706ce006ff1c3c457354bdc3b8fc7efe89cbac521f74cbeef4f4326788934efc/rootfs
overlay        238797468 186241464  40356020  83% /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v1.linux/k8s.io/9f50330586375bf2fc467ad6bb83d092a816af62587bc04ebeb0028f175cf65a/rootfs

**Comment by balchua** [comment]
@PhilAndrew, have you ran any pods there?

**Comment by PhilAndrew** [comment]
Sorry, its not microk8s's fault, its my other program.

**Comment by viictorvzla** [comment]
> Sorry, its not microk8s's fault, its my other program.

Hi! 
I have the same doubt. It consumes a lot of snap/microk8s disk space. Can you help me with a solution please?

**Comment by alessiodam** [comment]
> Sorry, its not microk8s's fault, its my other program.

Could you please tell us which one? I have a similar issue.
