### ISSUE TITLE
Update Istio

### ISSUE THREAD

**Issue by AndrewX192** [ubuntu/microk8s#743]
The version of Istio installed with MicroK8s (via istioctl) is version 1.2.2 which is a few months old and doesn't address several recent (though probably not too significant) vulnerabilities:

With 1.3.3 out, the 1.3 branch is probably stable enough to include https://istio.io/news/2019/announcing-1.3.3/

**Comment by ktsakalozos** [comment]
Thank you for the suggestion @AndrewX192 . Updating MicroK8s should be as easy as patching the desited release version at https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.istio.sh#L12 and rebuilding the snap as described in https://github.com/ubuntu/microk8s/blob/master/docs/build.md

**Comment by cvgaviao** [comment]
@ktsakalozos, would be possible to us, once microk8s is installed and working, to upgrade the installed addons?
