### ISSUE TITLE
I want to install microk8s by snap, but met this problem.

### ISSUE THREAD

**Issue by andyzheung** [ubuntu/microk8s#747]
root@ubuntu:/etc/systemd/system# snap install microk8s --classic
error: cannot install "microk8s": Post https://api.snapcraft.io/v2/snaps/refresh: x509: certificate
       signed by unknown authority

How can set the right certificate?

**Comment by ktsakalozos** [comment]
Hi @andyzheung 

This like a snapd installation problem. I suspect you cannot install any snap. Could you ask at https://forum.snapcraft.io ? Here is a similar issue: https://forum.snapcraft.io/t/solved-cant-install-snaps-ubuntucore16-x509-certificate-has-expired/13470

**Comment by andyzheung** [comment]
thank you, I have solve the problem, by put our ca.crt  to /usr/local/share/ca-certificates/ 
and 
#update-ca-certificates..
@ktsakalozos
