### ISSUE TITLE
Getting error while installing elasticsearch with helm 

### ISSUE THREAD

**Issue by ghost** [ubuntu/microk8s#749]
helm install incubator/elasticsearch --namespace logging --name elasticsearch --set data.terminationGracePeriodSeconds=0

Error: release elasticsearch failed: Deployment.apps "elasticsearch-client" is invalid: spec.template.spec.initContainers[0].securityContext.privileged: Forbidden: disallowed by cluster policy

**Comment by ktsakalozos** [comment]
Could you try to add `--allow-privileged` into `/var/snap/microk8s/current/args/kube-apiserver` and do a restart with `microk8s.stop; microk8s.start` ?

**Comment by lordcf** [comment]
Into var/snap 2 directories amazon-ssm-agent and core 
I am not getting where exactly i need to add --allow-privileged

**Comment by ktsakalozos** [comment]
Could you attach the tarball produced by `microk8s.inspect`? Thank you.

**Comment by morganchristiansson** [comment]
Hello. I had the same issue when trying to run elasticsearch on microk8s.

Adding `--allow-privileged` into /var/snap/microk8s/current/args/kube-apiserver and `microk8s.stop; microk8s.start` resolves it. Thank you @ktsakalozos

**Comment by eli-halych** [comment]
For me this was also relevant with other operators like Rook in a rook-ceph cluster
