### ISSUE TITLE
I meet to problem thant enable dns, didn't know why?

### ISSUE THREAD

**Issue by andyzheung** [ubuntu/microk8s#752]
I have install microk8s by 
$snap install microk8s --classic
and I want to install corens.
$microk8s.enable dns

but I meet to the problem:
![image](https://user-images.githubusercontent.com/22912347/67389232-c5ab9280-f5cc-11e9-912f-ab8d755c2bef.png)
![image](https://user-images.githubusercontent.com/22912347/67389288-e4aa2480-f5cc-11e9-8b54-3ec39da50d77.png)

I have change the container-template.toml:
![image](https://user-images.githubusercontent.com/22912347/67389326-fab7e500-f5cc-11e9-84dd-0d5aa7840434.png)

And I try to use microk8s.ctr images pull docker.io/mirrorgooglecontainers/pause:3.1
that is OK.
![image](https://user-images.githubusercontent.com/22912347/67389398-233fdf00-f5cd-11e9-80a2-dfa44e8e40a8.png)

**Comment by ktsakalozos** [comment]
Are you behind a proxy?

**Comment by andyzheung** [comment]
> Are you behind a proxy?

Yes I am behind the proxy.
But why I use microk8s.ctr CLI can pull the images from docker.io?
@ktsakalozos

**Comment by ktsakalozos** [comment]
You will need to setup the proxy in the containerd-env file as described in https://microk8s.io/docs/

ctr is using the overall `/etc/environment` settings, have a look at this issue https://github.com/ubuntu/microk8s/issues/724#issuecomment-541872651

**Comment by andyzheung** [comment]
Thank you so much, I read it and solve the problem.@ktsakalozos
