### ISSUE TITLE
Some question about microk8s

### ISSUE THREAD

**Issue by andyzheung** [ubuntu/microk8s#754]
I have install the microk8s use one command:
$snap install microk8s --classic

Is the k8s Master component is containerized? example:
kube-controller-manager, kube-apiserver, kube-scheduler etc...

How can I search the containers that I deploy in the k8s?
I use the k8s 1.16 and containerd as container-engine.

I deploy 50s nginx app demo which is containerized:
![image](https://user-images.githubusercontent.com/22912347/67472151-40cf8000-f683-11e9-8ef6-b9bb05a4b944.png)

But I use microk8s.ctr container list 
![image](https://user-images.githubusercontent.com/22912347/67472258-6ceb0100-f683-11e9-8906-577b52f52902.png)

I can't see the container in the system. How can I search how many container in my system? I have some doubt about the microk8s snap manage the software way is different? What is the advantage about snap?

**Comment by andyzheung** [comment]
Thank you.
But the second question I try like this:
![image](https://user-images.githubusercontent.com/22912347/67484667-273a3280-f69b-11e9-93af-0d7e9bbe2ad5.png)
@ktsakalozos

**Comment by ktsakalozos** [comment]
Try `--namespace k8s.io` ?

**Comment by ktsakalozos** [comment]
Like so: `microk8s.ctr --namespace k8s.io containers list`

**Comment by andyzheung** [comment]
thx, ctr is some different from kubectl.
