### ISSUE TITLE
Ahout how to visit the k8s dashboard?

### ISSUE THREAD

**Issue by andyzheung** [ubuntu/microk8s#755]
I have enable the dashboard.
$ microk8s.enable dns dashboard

1、I try to visit by the cluster IP like this:
![image](https://user-images.githubusercontent.com/22912347/67480261-29e45a00-f692-11e9-958b-6cadcbd18546.png)
![image](https://user-images.githubusercontent.com/22912347/67480307-46809200-f692-11e9-9a59-2d54b0dc7b75.png)

2、I try to change the service traffic mode to NodePort:
![image](https://user-images.githubusercontent.com/22912347/67479724-416f1300-f691-11e9-80c1-07612dbfd2ad.png)
![image](https://user-images.githubusercontent.com/22912347/67479778-5f3c7800-f691-11e9-99c6-13bb166932d7.png)

But can't visit the web by webbrowser in the Ubuntu which I install microk8s:
![image](https://user-images.githubusercontent.com/22912347/67479864-93179d80-f691-11e9-87e1-7dd44496aa0e.png)

use IP: 216.10.10.100

**Comment by balchua** [comment]
@andyzheung you cannot access the dashboard using `http://localhost:32000/`?

**Comment by andyzheung** [comment]
Yes, I use web browser in the node (Ubunt), also can't access.
@balchua

**Comment by balchua** [comment]
It seems to be connecting, except your browser doesn't like self signed certs.

**Comment by andyzheung** [comment]
> It seems to be connecting, except your browser doesn't like self signed certs.

But how to solve it?

**Comment by balchua** [comment]
Can you try this https://timleland.com/firefox-allow-self-signed-certificate/

**Comment by andyzheung** [comment]
Thank you that I have solve the problem by your answer.
@balchua
