### ISSUE TITLE
Unable to pull images from private registry

### ISSUE THREAD

**Issue by marian-margeta** [ubuntu/microk8s#756]
I have installed microk8s on Ubuntu 18.04.3 server that is behind the firewall and access to internet is limited. Thus I downloaded snap from another computer
```sh
snap download microk8s
```
and then installed it on that server (with root privileges) and imported sandbox_image (k8s.gcr.io/pause:3.1) that was needed and couldn't be downloaded because of firewall
```sh
snap ack microk8s_989.assert
snap install microk8s_989.snap --classic

microk8s.ctr -n k8s.io image import pause3.1
```

Then, I have updated file /var/snap/microk8s/current/args/containerd-template.toml according to the tutorial at https://microk8s.io/docs/working#working-with-a-private-registry

```
    [plugins.cri.registry.configs."registry01*".auth]
      username = "name"
      password = "pwd"
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["http://registry01:80"]
        [plugins.cri.registry.mirrors."local.insecure-registry.io"]
          endpoint = ["http://registry01:80"]
        [plugins.cri.registry.mirrors."registry01:80"]
          endpoint = ["http://registry01:80"]
```

Howewer, It seems like it is ignored. When I run command
```sh
microk8s.kubectl run name --image=registry01:80/image:tag
microk8s.kubectl describe pod [podname]
```
the output from describe is as follows
```
Failed to pull image "registry01:80/image:tag": rpc error: code = Unknown desc = failed to resolve image "registry01:80/image:tag": no available registry endpoint: failed to do request: Head https://registry01:80/v2/image/manifests/tag: http: server gave HTTP response to HTTPS client
```
Regardless the **endpoint** property of **[plugins.cri.registry.mirrors."registry01:80"]**. When I change it to something else, the result is the same.

**Comment by ktsakalozos** [comment]
@marian-margeta I see you are importing the image to containerd cache as described in "Working with locally built images without a registry" but then you mention a private registry. Can you please explain with more detail what steps are you following?

**Comment by marian-margeta** [comment]
@ktsakalozos I had to import just one image manually - k8s.gcr.io/pause:3.1, because it is defined as **sandbox_image** by default in file /var/snap/microk8s/current/args/containerd-template.toml at **[plugins]->[plugins.cri]->sandbox_image**. My private registry doesn't contain that file and each my pod (with docker image from my private registry) ends with en error as microk8s tries to pull this sandbox image for some reason.

**Comment by balchua** [comment]
I think containerd 1.3.0, seems to be much better in handling this registries, there a lot of fixes related to registry in this release. I cooked a PR https://github.com/ubuntu/microk8s/pull/761 to upgrade containerd to 1.3.0

**Comment by ktsakalozos** [comment]
@marian-margeta have you tried removing the invalid entries from `/var/snap/microk8s/current/args/containerd-template.toml` and leaving only your registry? Could you also attach the tarball created from `microk8s.inspect`?

**Comment by marian-margeta** [comment]
@ktsakalozos I have tried that and the result is the same. Even when I provide invalid url:
```sh
[plugins.cri.registry.mirrors."registry01:80"]
   endpoint = ["http://xxxxxxx:80"]
```
it tries to pull image from https://registry01:80/, while http://xxxxxxx:80 is expected. 

Here is the tarball [inspection-report-20191029_100729.tar.gz](https://github.com/ubuntu/microk8s/files/3782626/inspection-report-20191029_100729.tar.gz)

**Comment by balchua** [comment]
I find that containerd 1.2.5 cri plugin is giving different results when it comes to insecure registry.  I also faced the same thing sometime back when doing builds with kaniko.  Using my machine's ip instead of localhost.
But so far with containerd 1.3.0 this flakiness is not there.
Just my 2 cents.

**Comment by balchua** [comment]
@marian-margeta would you be able to try the edge version?  the edge comes with containerd 1.3, perhaps this will solve your registry issue.
thanks.

**Comment by marian-margeta** [comment]
@balchua I wouldn't now, maybe after one or two week. I have bypassed the problem for now so I will try it later. Thank you anyway.

**Comment by balchua** [comment]
@marian-margeta its all good. When u get the chance. Thanks.

**Comment by berttejeda** [comment]
My scenario:

- Private Registry DNS: my-registry.mydomain
- Private Registry IP:  192.168.1.57

What worked for me was adding both the IP and DNS values to the containerd template.

Here's the relevant section in my /var/snap/microk8s/current/args/containerd-template.toml:
```
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
        [plugins.cri.registry.mirrors."localhost:32000"]
          endpoint = ["http://localhost:32000"]
        [plugins.cri.registry.mirrors."192.168.1.57"]
          endpoint = ["http://192.168.1.57"]
        [plugins.cri.registry.mirrors."my-registry.mydomain"]
          endpoint = ["http://my-registry.mydomain"] 
```

Once I did that, I rebooted the VM for good measure, but I bet this would work as well:

`systemctl restart snap.microk8s.daemon-containerd.service && microk8s.stop && microk8s.start`	

Here's my /etc/docker/daemon.json for posterity:
```
{
    "insecure-registries" : ["localhost:32000", "my-registry.mydomain"]
}
```

Once I did this, the image pull errors went away.
