### ISSUE TITLE
I use the demo--nginx in dockerhub deploy on microk8s, but can't access from browser

### ISSUE THREAD

**Issue by andyzheung** [ubuntu/microk8s#758]
I just use microk8s to deploy a demo, and meet some problem:
1、microk8s use k8s 1.16:

2、nginx:
![image](https://user-images.githubusercontent.com/22912347/67561134-ddab1f80-f74e-11e9-82ed-b8bdb745f327.png)

3、deploy like this:
![image](https://user-images.githubusercontent.com/22912347/67561153-e3a10080-f74e-11e9-880c-b6a331788a83.png)
![image](https://user-images.githubusercontent.com/22912347/67561167-e996e180-f74e-11e9-8a17-4a0e1a53b391.png)
![image](https://user-images.githubusercontent.com/22912347/67561178-ed2a6880-f74e-11e9-83cb-d624c349503c.png)

4、pod is ok:
![image](https://user-images.githubusercontent.com/22912347/67561186-f1ef1c80-f74e-11e9-88b8-0be6a10d5348.png)
![image](https://user-images.githubusercontent.com/22912347/67561194-f6b3d080-f74e-11e9-848c-d1f3b8c6e99b.png)

5、but can't access:
I am in the node use browser:
https://localhost:30080

https://216.10.10.100:30080

**Comment by balchua** [comment]
@andyzheung, you are accessing it as `https`.  I think you mean `http`, i.e. unsecure.

**Comment by andyzheung** [comment]
I use http, still not ok.@balchua

**Comment by balchua** [comment]
I think it has something to do with ipv6 in your system.  There is an existing issue https://github.com/ubuntu/microk8s/issues/498#issuecomment-501088380 cud be related to ur case.

**Comment by andyzheung** [comment]
I try , may be I did't use ipv6.
![image](https://user-images.githubusercontent.com/22912347/68177566-ad237b00-ffc3-11e9-89d5-c85d06081b10.png)

**Comment by balchua** [comment]
You can use `kubectl exec` to get into the pod.  Could it be that the nginx container is uaing 8080 port instead of 80?

**Comment by andyzheung** [comment]
> ould it be that the nginx container is uaing 8080
I enter into the container:
![image](https://user-images.githubusercontent.com/22912347/68179370-8f0d4900-ffca-11e9-9fcb-627b80d54b9c.png)
![image](https://user-images.githubusercontent.com/22912347/68179382-9af90b00-ffca-11e9-8771-a4f8268c070f.png)
![image](https://user-images.githubusercontent.com/22912347/68179401-aa785400-ffca-11e9-9319-1ec7ad2fe67b.png)

I change my yaml port to 8080, that is ok.Thank you so much.
@balchua 

![image](https://user-images.githubusercontent.com/22912347/68179448-e1e70080-ffca-11e9-9d55-0583e9985047.png)
