### ISSUE TITLE
Pods with `exec` in the readiness failing in Disco

### ISSUE THREAD

**Issue by davigar15** [ubuntu/microk8s#760]
Hello,

I have noticed that when I deploy k8s charms on microk8s, using Disco instead of Bionic, there are issues when the readiness of the pod uses `exec`.

Here are some logs:
(Deployed charm: cs:~charmed-osm/mariadb-k8s)

http://paste.ubuntu.com/p/WFtyQTKqpJ/
http://paste.ubuntu.com/p/sHSq8W3knf/

Thanks,
David Garcia

**Comment by ktsakalozos** [comment]
Hi @davigar15 

Could you please attach the tarball produced by `microk8s.inspect` and a minimal manifest/script with which I can reproduce the issue?

Many thanks.

**Comment by davigar15** [comment]
Hello,

Well, apparently is not a Disco issue, because I was able to successfully deploy this on Disco:

```bash
multipass launch -c 2 -d 50G -m 8G disco
multipass exec soothing-squirrelfish bash 

export PATH=$PATH:/snap/bin

sudo snap install juju --classic

sudo snap install microk8s --channel 1.14/stable --classic
sudo usermod -a -G microk8s $USER
newgrp microk8s
microk8s.status --wait-ready
microk8s.enable storage dns

sudo snap alias microk8s.kubectl kubectl

sleep 20
juju bootstrap microk8s
juju add-model test
juju deploy cs:~charmed-osm/mariadb-k8s
```

@AdamIsrael, as you could reproduce the error repetitively, could you please attach the `microstack.inspect` generated tar.gz?
