### ISSUE TITLE
MicroK8s Token Dashboard

### ISSUE THREAD

**Issue by lukitch59** [ubuntu/microk8s#771]
Hello,

I've installed MicroK8s and all is working except the dashboard authentification

I can acces to the dashboard but the token is not working

I've generate the token using this command 👍 
token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token

I get this : 

Data
====
token:      eyJhbGciOiJSUzI1NiIsImtpZCI6ImllYU9IMndUcHVHOFNaQmlpUEFhcEEtN2tDQkhYdDE0U1ZGQzUtVXYwNnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWdoOW5jIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmZDAzZjRlNS1kYzIzLTQzY2QtOTM2MC1kNWRhOTY2N2ZmMWUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.uBnMWP3ElL-RUugDc61570ISBX8NmOzma2oU-aFCSn2jBrsaztAXglBBPl_x5gF0pO0wrmDwaJy4HS-JhI9-CZ-kjawLxXn9VP9WpNj8SH1ucEhfUL5UzWIyPRSErwbOj_k6AMwZ1GdcUs_a4xSQtCbGoOzW4XjCvwcg0N0i990Ral__vmldzxFFEJ2QycalaNRaU5Oj4vP-80Rfe2BFqo9FuAqw8O7214xfGVmIh6o1lyBht8rDWYj1UtNVrbjsNN-v8A4fFtZ2Ci7h7EujjhxbIS1l7Z1OiryjPnrciIaXDl5QfLnIEYcKNzn8AaoeTUgylkofez1EPUb5LZQYzw

When i've tried this token and it's not working , i get no message error but nothing happen.

I don't know what i've missed and why this token is not working

**Comment by mprostko** [comment]
I experienced this issue today too. Tried the --classic option while installing and --classic --edge. Both produced same results - very long token that does not work with dashboard.

**Comment by ktsakalozos** [comment]
@lukitch59  @lukitch59 could you help me reproduce this? I just tested it and got it working. Could you attach the tarball from `microk8s.inspect`?

**Comment by lukitch59** [comment]
due to a network lack , I will provide u tomrrow the tar from the microK8s.inspect

**Comment by lukitch59** [comment]
Here is tar from the microK8s.inspect

[inspection-report-20191108_075737.tar.gz](https://github.com/ubuntu/microk8s/files/3823304/inspection-report-20191108_075737.tar.gz)

**Comment by ktsakalozos** [comment]
The problem seems to be that your cluster is not healthy. For example, `microk8s.kubectl get all --all-namespaces` shows a lot of pods in an unknown state. This machine seems to be a CentOS (?) which version? Looks old, but could you try the latest edge build? `sudo snap install microk8s --classic --edge`

**Comment by lukitch59** [comment]
When i use mcrok8s.kubectl get all --all-namespaces all seems to be in a proper state :

![Capture](https://user-images.githubusercontent.com/57354941/68741560-3f440880-05ee-11ea-9bba-aa565ddf82d5.PNG)

My actual CentOS version is :  CentOS  Linux release 7.7.1908 (Core) --> I can upgrade it to 8x versin or maybe change the linux distribution from Centos to Debian or other.... Which distro is the best ?

**Comment by lukitch59** [comment]
How to avoid this kind of trouble ?
Maybe upgrade my centos Version ? or change it ?

A workaround solution exist ?

**Comment by ktsakalozos** [comment]
I was wrong Centos 7.7 is not old, I saw the 3.10 kernel and thought the entire distribution is old.

If you want best compatibility and you have the option to switch to another distribution you would better go to an Ubuntu LTS; bionic for not.

**Comment by lukitch59** [comment]
I ve just installed an Ubuntu 19.10 server with snaps and microk8s from ubuntu's package during the server installation.

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan

The cluster has no errors  :

root@devops:~# microk8s.kubectl get all --all-namespaces
NAMESPACE     NAME                                                  READY   STATUS              RESTARTS   AGE
kube-system   pod/coredns-9b8997588-2jkh4                           0/1     ContainerCreating   0          24s
kube-system   pod/dashboard-metrics-scraper-566cddb686-9cvcw        0/1     ContainerCreating   0          24s
kube-system   pod/heapster-v1.5.2-5c58f64f8b-mnvcl                  0/4     ContainerCreating   0          24s
kube-system   pod/kubernetes-dashboard-678b7d865c-f4jq8             0/1     ContainerCreating   0          24s
kube-system   pod/monitoring-influxdb-grafana-v4-6d599df6bf-7pcz4   0/2     ContainerCreating   0          24s

NAMESPACE     NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes                  ClusterIP   10.152.183.1     <none>        443/TCP                  5m44s
kube-system   service/dashboard-metrics-scraper   ClusterIP   10.152.183.127   <none>        8000/TCP                 24s
kube-system   service/heapster                    ClusterIP   10.152.183.95    <none>        80/TCP                   24s
kube-system   service/kube-dns                    ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   24s
kube-system   service/kubernetes-dashboard        ClusterIP   10.152.183.71    <none>        443/TCP                  24s
kube-system   service/monitoring-grafana          ClusterIP   10.152.183.128   <none>        80/TCP                   24s
kube-system   service/monitoring-influxdb         ClusterIP   10.152.183.59    <none>        8083/TCP,8086/TCP        24s

NAMESPACE     NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                          0/1     1            0           24s
kube-system   deployment.apps/dashboard-metrics-scraper        0/1     1            0           24s
kube-system   deployment.apps/heapster-v1.5.2                  0/1     1            0           24s
kube-system   deployment.apps/kubernetes-dashboard             0/1     1            0           24s
kube-system   deployment.apps/monitoring-influxdb-grafana-v4   0/1     1            0           24s

NAMESPACE     NAME                                                        DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-9b8997588                           1         1         0       24s
kube-system   replicaset.apps/dashboard-metrics-scraper-566cddb686        1         1         0       24s
kube-system   replicaset.apps/heapster-v1.5.2-5c58f64f8b                  1         1         0       24s
kube-system   replicaset.apps/kubernetes-dashboard-678b7d865c             1         1         0       24s
kube-system   replicaset.apps/monitoring-influxdb-grafana-v4-6d599df6bf   1         1         0       24s

but when i'm getting the secret token for the dashboard I get the same error like on my Centos Server.

token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token

Name:         default-token-5g4p4
Namespace:    kube-system
Labels:       <none>
Annotations:  kubernetes.io/service-account.name: default
              kubernetes.io/service-account.uid: ff57e787-8e91-40c2-aa21-ad2807312ff0

Type:  kubernetes.io/service-account-token

Data
====
ca.crt:     1103 bytes
namespace:  11 bytes
token:      eyJhbGciOiJSUzI1NiIsImtpZCI6IlYzeXFrQUVldWt1UTFLd3hxU3BkSFFOUE4wTkx6R2t3b0dNUkF4OUtrWXMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTVnNHA0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmZjU3ZTc4Ny04ZTkxLTQwYzItYWEyMS1hZDI4MDczMTJmZjAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.ikMbEC9dsp1e-xhGjtEQgUI_tdvjMKHg0VwWSHewsd_ixBsIl87AsRdBSSxmofngMXIijCHNGGQkpOuyYTXq8rYkYAwkkXai5I7Nl0txHjUz4a4n0KtHkAkZqt8KIy0OLTa2kedqpSlJL2r0h_RKsI9dsPcTa0Xyci37PRVwopCd-3cFFQyklbW-AzIFrF-khxTKL8OciRVuIklRBJhP53r38yji6lNJGKCHd0mSMV61fhqIDM5p5aLVdlup0WPqddkaCZWJ4dKP2plTJEWaUEirJi-WxCtzCnLiOiRngLKaFmNEbh66kwnqTFwxQT0O7wYP76TXvl0KjSF39a7_XA

But this token is not working on the Kubernetes Dashboard.

Is am missing something during the installation ?

**Comment by lukitch59** [comment]
i get the same trouble with snap install microk8s --classic --edge

**Comment by jmichalek132** [comment]
Same here with `--classic` on Debian buster. as a workaround I edited the dashboard deployment and added arg to skip login
```
microk8s.kubectl edit deployment/kubernetes-dashboard --namespace=kube-system
```
```
- args:
  - --enable-skip-login
```

**Comment by lukitch59** [comment]
it's working with this arguments but it's not very secure

**Comment by ktsakalozos** [comment]
I am sorry I cannot reproduce this. Could you make sure you do not copy any new lines along with the token? I cannot think of anything else.

**Comment by ktsakalozos** [comment]
@lukitch59 @jmichalek132 are you running MicroK8s in a VM? As you can read in the upstream docs [1], there are limitations in exposing the dashboard to other hosts.

In the PR above we have revised the docs page to use an alternative approach that can work around the dashboard exposing limitations.

[1] https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/1.7.x-and-above.md

**Comment by jmichalek132** [comment]
> @lukitch59 @jmichalek132 are you running MicroK8s in a VM? As you can read in the upstream docs [1], there are limitations in exposing the dashboard to other hosts.
> 
> In the PR above we have revised the docs page to use an alternative approach that can work around the dashboard exposing limitations.
> 
> [1] https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/1.7.x-and-above.md

Yes. thanks for the update.

**Comment by lukitch59** [comment]
Hello,

I'm running MicoK8s on a server not a VM... I've tried 3 linux distribution Centos , Debian & Unbuntu... both 3 the same result.

In order to grab the token I ve used this command : 

token=$(microk8s.kubectl -n kube-system get secret | grep default-token | cut -d " " -f1)
microk8s.kubectl -n kube-system describe secret $token

And the result is : ca.crt: 1103 bytes
namespace: 11 bytes
token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlYzeXFrQUVldWt1UTFLd3hxU3BkSFFOUE4wTkx6R2t3b0dNUkF4OUtrWXMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTVnNHA0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmZjU3ZTc4Ny04ZTkxLTQwYzItYWEyMS1hZDI4MDczMTJmZjAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.ikMbEC9dsp1e-xhGjtEQgUI_tdvjMKHg0VwWSHewsd_ixBsIl87AsRdBSSxmofngMXIijCHNGGQkpOuyYTXq8rYkYAwkkXai5I7Nl0txHjUz4a4n0KtHkAkZqt8KIy0OLTa2kedqpSlJL2r0h_RKsI9dsPcTa0Xyci37PRVwopCd-3cFFQyklbW-AzIFrF-khxTKL8OciRVuIklRBJhP53r38yji6lNJGKCHd0mSMV61fhqIDM5p5aLVdlup0WPqddkaCZWJ4dKP2plTJEWaUEirJi-WxCtzCnLiOiRngLKaFmNEbh66kwnqTFwxQT0O7wYP76TXvl0KjSF39a7_XA

maybe the arguments are not the correct... but If i check all token all are in this format

**Comment by matthiasbeyer** [comment]
I'm experiencing the same issue, the token just won't work. No error or other notification, just nothing happening.

**Comment by javaChip56** [comment]
Got the same issue just now. Unable to authorize using the token. Running on Ubuntu 18.04 LTS.

**Comment by maximillianus** [comment]
i am trying this and I cant access the dashboard too despite already generating token as told the tutorial here: https://ubuntu.com/tutorials/install-a-local-kubernetes-with-microk8s#4-accessing-the-kubernetes-and-grafana-dashboards

**Comment by ktsakalozos** [comment]
Please attach the tarball produced by `microk8s.inspect` and any instructions we could use to reproduce the issue. Thank you.

**Comment by cytown** [comment]
exact the same problem...

[inspection-report-20200909_185136.tar.gz](https://github.com/ubuntu/microk8s/files/5194599/inspection-report-20200909_185136.tar.gz)

**Comment by cytown** [comment]
the skip works but....

**Comment by cytown** [comment]
for your reference, I use `microk8s.kubectl proxy --accept-hosts=.* --address=0.0.0.0 --port 8043` to access the dashboard with `http://{Ubuntu_IP_address}:8043/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/`

should be this issue???

**Comment by derekneves** [comment]
Same issue as others have described

Ubuntu 20.04.1
sudo snap install microk8s --classic
microk8s.enable dns dashboard registry ingress

`derek@node2:~$ microk8s.kubectl get all --all-namespaces
NAMESPACE            NAME                                             READY   STATUS    RESTARTS   AGE
kube-system          pod/metrics-server-8bbfb4bdb-f8xd5               1/1     Running   0          25m
kube-system          pod/dashboard-metrics-scraper-6c4568dc68-7g9dg   1/1     Running   0          25m
kube-system          pod/calico-node-c4jbg                            1/1     Running   1          29m
kube-system          pod/calico-kube-controllers-847c8c99d-ggs7n      1/1     Running   0          29m
kube-system          pod/coredns-86f78bb79c-w9g6b                     1/1     Running   0          25m
kube-system          pod/kubernetes-dashboard-7ffd448895-9jr9p        1/1     Running   0          25m
kube-system          pod/hostpath-provisioner-5c65fbdb4f-mtwc7        1/1     Running   0          25m
ingress              pod/nginx-ingress-microk8s-controller-xhghq      1/1     Running   0          25m
container-registry   pod/registry-9b57d9df8-rq8gk                     1/1     Running   0          25m

NAMESPACE            NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default              service/kubernetes                  ClusterIP   10.152.183.1     <none>        443/TCP                  29m
kube-system          service/kube-dns                    ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   25m
kube-system          service/metrics-server              ClusterIP   10.152.183.217   <none>        443/TCP                  25m
kube-system          service/kubernetes-dashboard        ClusterIP   10.152.183.20    <none>        443/TCP                  25m
kube-system          service/dashboard-metrics-scraper   ClusterIP   10.152.183.15    <none>        8000/TCP                 25m
container-registry   service/registry                    NodePort    10.152.183.189   <none>        5000:32000/TCP           25m

NAMESPACE     NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/calico-node                         1         1         1       1            1           kubernetes.io/os=linux   29m
ingress       daemonset.apps/nginx-ingress-microk8s-controller   1         1         1       1            1           <none>                   25m

NAMESPACE            NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
kube-system          deployment.apps/metrics-server              1/1     1            1           25m
kube-system          deployment.apps/dashboard-metrics-scraper   1/1     1            1           25m
kube-system          deployment.apps/calico-kube-controllers     1/1     1            1           29m
kube-system          deployment.apps/coredns                     1/1     1            1           25m
kube-system          deployment.apps/kubernetes-dashboard        1/1     1            1           25m
kube-system          deployment.apps/hostpath-provisioner        1/1     1            1           25m
container-registry   deployment.apps/registry                    1/1     1            1           25m

NAMESPACE            NAME                                                   DESIRED   CURRENT   READY   AGE
kube-system          replicaset.apps/metrics-server-8bbfb4bdb               1         1         1       25m
kube-system          replicaset.apps/dashboard-metrics-scraper-6c4568dc68   1         1         1       25m
kube-system          replicaset.apps/calico-kube-controllers-847c8c99d      1         1         1       29m
kube-system          replicaset.apps/coredns-86f78bb79c                     1         1         1       25m
kube-system          replicaset.apps/kubernetes-dashboard-7ffd448895        1         1         1       25m
kube-system          replicaset.apps/hostpath-provisioner-5c65fbdb4f        1         1         1       25m
container-registry   replicaset.apps/registry-9b57d9df8                     1         1         1       25m
`

 microk8s.kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' 
 or 
 microk8s.kubectl proxy --accept-hosts=.* --address=0.0.0.0 --port 8043

Dashboard getting hit on 8001 and 8043 respectively above, still same issue, no error or response

Replicated issue on two baremetal nodes, no other conflicting ports

**Comment by IainColledge** [comment]
This happened to me when I was using

kubectl proxy --accept-hosts=.* --address=0.0.0.0 & 

Instead I tried this 

kubectl port-forward -n kube-system service/kubernetes-dashboard 10443:443 --address 0.0.0.0

And connected to https://x.x.x.x:10443/ where x.x.x.x is my server IP

**Comment by wimdecorte** [comment]
same issue, brand new microk8s 1.21 on RPI4 running Ubuntu 18.04
Got around it by enabling the skip option but would prefer for this this to be fixed.

When I enter the token nothing happens, no error, no other feedback.

Inspection report attached.
[inspection-report-20210906_205310.tar.gz](https://github.com/ubuntu/microk8s/files/7117782/inspection-report-20210906_205310.tar.gz)
