### ISSUE TITLE
Increase systemd unit timeout for microk8s.stop

### ISSUE THREAD

**Issue by krichter722** [ubuntu/microk8s#774]
`microk8s.stop` regularly (~20% of times) fails to stop due to

```
Fehler: cannot perform the following tasks:
- stop of [microk8s.daemon-apiserver microk8s.daemon-apiserver-kicker microk8s.daemon-cluster-agent microk8s.daemon-containerd microk8s.daemon-controller-manager microk8s.daemon-etcd microk8s.daemon-flanneld microk8s.daemon-kubelet microk8s.daemon-proxy microk8s.daemon-scheduler] (# systemctl stop snap.microk8s.daemon-apiserver.service snap.microk8s.daemon-apiserver-kicker.service snap.microk8s.daemon-cluster-agent.service snap.microk8s.daemon-containerd.service snap.microk8s.daemon-controller-manager.service snap.microk8s.daemon-etcd.service snap.microk8s.daemon-flanneld.service snap.microk8s.daemon-kubelet.service snap.microk8s.daemon-proxy.service snap.microk8s.daemon-scheduler.service

<exceeded maximum runtime of 1m1s>)
- stop of [microk8s.daemon-apiserver microk8s.daemon-apiserver-kicker microk8s.daemon-cluster-agent microk8s.daemon-containerd microk8s.daemon-controller-manager microk8s.daemon-etcd microk8s.daemon-flanneld microk8s.daemon-kubelet microk8s.daemon-proxy microk8s.daemon-scheduler] (exceeded maximum runtime of 1m1s)
Failed to stop microk8s services. Check snapd logs with "journalctl -u snapd.service"
```

In this case `microk8s.stop` needs to be repeated and then usually succeeds. Since aborting the stop routine  which already takes more than 60s is a source of trouble (resources left in undefined state or else) increasing the timeout to 120s to even 300s doesn't hurt afaik.

experienced with v1.16.2 (989) on Ubuntu 19.10
[inspection-report-20191107_115904.tar.gz](https://github.com/ubuntu/microk8s/files/3819235/inspection-report-20191107_115904.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @krichter722 I do not see an obvious way to set the service stop timeout. I asked the snappy people at https://forum.snapcraft.io/t/snap-disable-timeout/14060. Let's see.

**Comment by DomFleischmann** [comment]
According to this [reply](https://forum.snapcraft.io/t/snap-disable-timeout/14060/4?u=dominik.f) there seems to be a non trivial bug that doesn't allow us to up the timeout time currently.

**Comment by eferreira2** [comment]
I've also encountered this issue with issuing snap commands to install the digital signage "xibo" platform on a Linux Centos 8 device.

- Run configure hook of "xibo-player" snap if present (run hook "configure": 
-----
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
/usr/share/fonts: caching, new cache contents: 0 fonts, 29 dirs
/usr/share/fonts/abattis-cantarell: caching, new cache contents: 4 fonts, 0 dirs
/usr/share/fonts/dejavu: caching, new cache contents: 21 fonts, 0 dirs
/usr/share/fonts/gnu-free: caching, new cache contents: 12 fonts, 0 dirs
/usr/share/fonts/google-droid: caching, new cache contents: 15 fonts, 0 dirs
/usr/share/fonts/google-noto: caching, new cache contents: 8 fonts, 0 dirs
/usr/share/fonts/google-noto-cjk: caching, new cache contents: 73 fonts, 0 dirs
/usr/share/fonts/jomolhari: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/julietaula-montserrat: caching, new cache contents: 72 fonts, 0 dirs
/usr/share/fonts/khmeros: caching, new cache contents: 3 fonts, 0 dirs
/usr/share/fonts/liberation-mono: caching, new cache contents: 4 fonts, 0 dirs
/usr/share/fonts/liberation-sans: caching, new cache contents: 4 fonts, 0 dirs
/usr/share/fonts/lohit-assamese: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-bengali: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-devanagari: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-gujarati: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-gurmukhi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-kannada: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-odia: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-tamil: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/lohit-telugu: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/paktype-naskh-basic: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/paratype-pt-sans: caching, new cache contents: 6 fonts, 0 dirs
/usr/share/fonts/sil-abyssinica: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/sil-nuosu: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/sil-padauk: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/smc: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/stix: caching, new cache contents: 4 fonts, 0 dirs
/usr/share/fonts/thai-scalable: caching, new cache contents: 4 fonts, 0 dirs
/usr/share/fonts/urw-base35: caching, new cache contents: 69 fonts, 0 dirs
/usr/share/X11/fonts/Type1: skipping, no such directory
/usr/share/X11/fonts/TTF: skipping, no such directory
/usr/local/share/fonts: 
<exceeded maximum runtime of 5m0s>
