### ISSUE TITLE
microk8s.status doesn't list kubeflow

### ISSUE THREAD

**Issue by iatrou** [ubuntu/microk8s#777]
The latest beta has support for kubeflow but it's not listed in status:

```
$ snap list | grep microk8s
microk8s          v1.17.0-beta.1  1037  1.17/beta  canonical*  classic
$ microk8s.status | grep kubeflow | wc -l
0
$ microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling rbac...
Enabling juju...
Deploying Kubeflow...
...
```

Thanks for the great work with microk8s!

**Comment by ktsakalozos** [comment]
Thank you for reporting this @iatrou , a fix should be available on the edge channel within the day (`sudo snap install microk8s --classic --edge`).
