### ISSUE TITLE
KubeletNotReady Ubuntu 19.10 raspberry pi 3 B+

### ISSUE THREAD

**Issue by wpoosanguansit** [ubuntu/microk8s#778]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
 
Hi, I have followed the instruction to install the image ubuntu 19.10 on raspberry pi 3 B+ and I managed to install microk8s.  However, when I do describe node ubuntu I have got the Ready is False:

container runtime status check may not have completed yet, missing node capacity for resources: ephemeral-storage.

How do I resolve the issue?  Thanks for your help.

[inspection-report-20191107_184157.tar.gz](https://github.com/ubuntu/microk8s/files/3821242/inspection-report-20191107_184157.tar.gz)

**Comment by ktsakalozos** [comment]
@wpoosanguansit have a look at this issue: https://github.com/ubuntu/microk8s/issues/728#issuecomment-548722833

How does your `/proc/cgroups` look like? It is possible you need to update `/boot/firmware/nobtcmd.txt` by appending `cgroup_enable=memory cgroup_memory=1` and rebooting.

**Comment by wpoosanguansit** [comment]
Thank you.  I will recheck that.

**Comment by wpoosanguansit** [comment]
Hi @ktsakalozos I did add the cgroup as recommended and rebooted.  However, now I am seeing 

microk8s.status
microk8s is not running. Use microk8s.inspect for a deeper inspection.

ubuntu@ubuntu:~$ microk8s.kubectl get no
Unable to connect to the server: net/http: TLS handshake timeout

ubuntu@ubuntu:~$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Thanks for your help.


[inspection-report-20191107_205226.tar.gz](https://github.com/ubuntu/microk8s/files/3821638/inspection-report-20191107_205226.tar.gz)

**Comment by wpoosanguansit** [comment]
I needed to change the localhost from 127.0.0.1 to 127.0.1.1 to have the kubectl get no to work.  Now the node is ready.  Thanks.
