### ISSUE TITLE
Dashboard-metrics-scraper image support for ARM64

### ISSUE THREAD

**Issue by camille-rodriguez** [ubuntu/microk8s#779]
Hi! 
I am running microk8s on a ARM64 server and the dashboard-metrics-scraper pod kept crashing. 

I found that it was already reported upstream here https://github.com/kubernetes/dashboard/issues/4029 and it has been fixed in this https://github.com/kubernetes-sigs/dashboard-metrics-scraper/releases/tag/v1.0.2 . 

So I updated the image name with 
`microk8s.kubectl edit pod/dashboard-metrics-scraper-566cddb686-f7qhg -n kube-system`
and changed the image version from `kubernetesui/metrics-scraper:v1.0.1` to `kubernetesui/metrics-scraper:v1.0.2` , and now the pod is working. It would be great to implement this fix in the next update. Thanks!

**Comment by ktsakalozos** [comment]
Hi @camille-rodriguez, thank you for reporting this.

The change you propose is already merged (https://github.com/ubuntu/microk8s/issues/779) and should reach the stable channel soon. You can either change the image version as you did, or you can deploy microk8s from the edge channel with `sudo snap install microk8s --classic --channel=latest/edge`

**Comment by camille-rodriguez** [comment]
Oh perfect then, thanks!
