### ISSUE TITLE
microk8s.status errors but inspect indicate that everything is running.

### ISSUE THREAD

**Issue by wpoosanguansit** [ubuntu/microk8s#781]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

I just install microk8s on ubuntu 19.10 raspberry pi 3 B+.  

Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

But 

ubuntu@ubuntu:~$ microk8s.status
microk8s is not running. Use microk8s.inspect for a deeper inspection.

I managed to get things working once when I changed the localhost from 127.0.0.1 to 127.0.1.1.  But it came back to the same error when I restarted the box.

Appreciate your help.

[inspection-report-20191108_025935.tar.gz](https://github.com/ubuntu/microk8s/files/3822941/inspection-report-20191108_025935.tar.gz)

**Comment by ktsakalozos** [comment]
@wpoosanguansit I see that trying to access the API server result in a ` Unable to connect to the server: net/http: TLS handshake timeout`. I need to understand what this thange of localhost to 127.0.1.1 is for, how did you end up to this change? Any documentation I could look into?

I wonder if you also need to change the `/var/snap/microk8s/current/certs/csr.conf.template` to use 127.0.1.1 instead of 127.0.0.1.

**Comment by wpoosanguansit** [comment]
Hi, I have gone through old tickets that I was given in my earlier case.  And I saw that that step might help.  So I just tested that out.  And I was surprised that it worked before I rebooted.  And now, it doesn’t.  Even when I tried changing it back and forth between 127.0.0.1 and 127.0.1.1.  Any suggestion what I need to set to get things to work?  Thanks for your help.

**Comment by wpoosanguansit** [comment]
I have made the change in the hosts file to point to 127.0.0.1 as localhost and reinstalled microk8s.  But it still gives me the same errors.

ubuntu@ubuntu:~$ sudo snap install microk8s --classic
microk8s v1.16.2 from Canonical✓ installed
ubuntu@ubuntu:~$ microk8s.kubectl get no
The connection to the server 127.0.0.1:16443 was refused - did you specify the right host or port?

Appreciate your help.

[inspection-report-20191109_081528.tar.gz](https://github.com/ubuntu/microk8s/files/3827060/inspection-report-20191109_081528.tar.gz)

**Comment by wpoosanguansit** [comment]
I have 4 instances installed and one of them turned up working.  So I attached the inspect for the one working here.  Any direction as how to debug this would be great.  Thanks for your help.

[inspection-report-20191109_081528.tar.gz](https://github.com/ubuntu/microk8s/files/3828157/inspection-report-20191109_081528.tar.gz)

**Comment by wpoosanguansit** [comment]
Here is another inspect log that I did after commented out all of the IPv6 in the /etc/hosts.  Thanks.

[inspection-report-20191112_222717.tar.gz](https://github.com/ubuntu/microk8s/files/3838513/inspection-report-20191112_222717.tar.gz)

**Comment by ktsakalozos** [comment]
@wpoosanguansit just noticed you are running on 1GB machine with no swap. Is it possible the kernel is killing some of the running processes and systemd needs to restart them? Do you run any workloads on the cluster?

**Comment by wpoosanguansit** [comment]
At the moment no workload yet, as I have not been able to make it work yet.  Thanks for your suggestion on swap.  I will look to see how I can enable that.

**Comment by wpoosanguansit** [comment]
I did follow the suggestion given by Balchu on slack to disable ipv6 as in:

https://itsfoss.com/disable-ipv6-ubuntu-linux/

Now everything seems to work and I am able get the status correctly.
