### ISSUE TITLE
Microk8s stopped listening at 127.0.0.1

### ISSUE THREAD

**Issue by nottrobin** [ubuntu/microk8s#782]
I'm running the microk8s snap v1.15.5 on Ubuntu 18.04.3:

``` bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
$ snap list microk8s
Name      Version  Rev  Tracking  Publisher   Notes
microk8s  v1.15.5  984  1.15      canonical✓  classic
```

My microk8s configuration is pretty default, and I'm deploying services and ingresses from our [deployment-configs repository](https://github.com/canonical-web-and-design/deployment-configs). I don't think the details of exactly what I'm deploying matter to this issue, but I can walk you through that if it's important.

I frequently find that microk8s stops being accessible on localhost (127.0.0.1), and I'm experiencing that same issue right now. I think basically this happens after microk8s has been running for a while, and the only reliable fix I've found is to reset microk8s completely with `microk8s.reset && snap disable microk8s && snap enable microk8s`.

Here's the state of my microk8s cluster:

``` bash
$ microk8s.kubectl get all,ingress
NAME                                          READY   STATUS    RESTARTS   AGE
pod/default-http-backend-5d5ff5d4f5-l462n     1/1     Running   10         2d2h
pod/nginx-ingress-microk8s-controller-j4hfn   1/1     Running   1          87s
pod/ubuntu-com-79997c7db9-55587               1/1     Running   8          2d2h
pod/ubuntu-com-blog-76467ff4cc-7wn28          1/1     Running   8          2d2h


NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/default-http-backend   ClusterIP   10.152.183.186   <none>        80/TCP    2d2h
service/kubernetes             ClusterIP   10.152.183.1     <none>        443/TCP   2d2h
service/ubuntu-com             ClusterIP   10.152.183.39    <none>        80/TCP    2d2h
service/ubuntu-com-blog        ClusterIP   10.152.183.123   <none>        80/TCP    2d2h

NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/nginx-ingress-microk8s-controller   1         1         1       1            1           <none>          2d2h

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/default-http-backend   1/1     1            1           2d2h
deployment.apps/ubuntu-com             1/1     1            1           2d2h
deployment.apps/ubuntu-com-blog        1/1     1            1           2d2h

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/default-http-backend-5d5ff5d4f5   1         1         1       2d2h
replicaset.apps/ubuntu-com-79997c7db9             1         1         1       2d2h
replicaset.apps/ubuntu-com-blog-76467ff4cc        1         1         1       2d2h

NAME                                    HOSTS                                              ADDRESS     PORTS     AGE
ingress.extensions/staging-ubuntu-com   staging.ubuntu.com,www.staging.ubuntu.com          127.0.0.1   80, 443   2d2h
ingress.extensions/ubuntu-com           ubuntu.com,www.ubuntu.com,ubuntu.net + 7 more...   127.0.0.1   80, 443   2d2h
```

I've noticed that the pod/nginx-ingress-microk8s-controller-j4hfn pod keeps restarting about every minute, and when it does, the `127.0.0.1` IP address assigned next to the ingresses disappears for a while and then comes back.

But regardless, whether `127.0.0.1` is appearing next to the ingresses or not, the host never seems to be able to access the cluster on that address:

``` bash
$ curl 127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused
 ```

I'm sure there's more I could do to debug this, but I don't know what the next step is. Could you give me pointers as to where to look next?

**Comment by ktsakalozos** [comment]
Could you attach the tarball produced by `microk8s.inspect`?

**Comment by nottrobin** [comment]
``` bash
$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

WARNING:  Docker is installed. 
File "/etc/docker/daemon.json" does not exist. 
You should create it and add the following lines: 
{
    "insecure-registries" : ["localhost:32000"] 
}
and then restart docker with: sudo systemctl restart docker
Building the report tarball
  Report tarball is at /var/snap/microk8s/984/inspection-report-20191108_091134.tar.gz
```

[inspection-report-20191108_091134.tar.gz](https://github.com/ubuntu/microk8s/files/3823778/inspection-report-20191108_091134.tar.gz)

**Comment by nottrobin** [comment]
Is that Docker warning relevant? Is that what I need to do?

**Comment by ktsakalozos** [comment]
> Is that Docker warning relevant? Is that what I need to do?

The docker warning is relevant only if you are using the registry addon (`microk8s.enable registry`) in which case the docker client needs to trust the addon registry in order to push images there.

**Comment by nottrobin** [comment]
Ah, not relevant then.

Let me know if there's anything obvious in that tarball, or if there's a way I can help look into it?

**Comment by ktsakalozos** [comment]
In the logs of the API server I see a lot of error messages like this one:
```
Error: unable to find suitable network address.error='no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this
```

The default route is needed to identify the interface where kubernetes should listen to. While the APIserver starts we wait for 2 minutes for the default interface to be set (https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/run-with-config-args#L80). Could you verify that when you see this abnormal behavior the apiserver is complaining about the default route? To see the logs do `sudo journalctl -u snap.microk8s.daemon-apiserver.service`.
