### ISSUE TITLE
microk8s.kubectl get all --all-namespaces returns errors.

### ISSUE THREAD

**Issue by wpoosanguansit** [ubuntu/microk8s#800]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

Hi,

I have now 9 nodes connected to a master node.  They all show up Ready when I do:

microk8s.kubectl get no                                                                                            master: Thu Nov 

NAME           STATUS   ROLES    AGE     VERSION
192.168.1.32   Ready    <none>   39h     v1.16.2
192.168.1.33   Ready    <none>   39h     v1.16.2
192.168.1.34   Ready    <none>   39h     v1.16.2
192.168.1.35   Ready    <none>   103m    v1.16.2
192.168.1.36   Ready    <none>   25h     v1.16.2
192.168.1.37   Ready    <none>   25h     v1.16.2
192.168.1.38   Ready    <none>   25h     v1.16.2
192.168.1.39   Ready    <none>   25h     v1.16.2
192.168.1.40   Ready    <none>   25h     v1.16.2
master         Ready    <none>   2d14h   v1.16.2

However I do get errors when I do:

microk8s.kubectl get all --all-namespaces                                                                          master: Thu Nov 14 20:04:32 2019

NAMESPACE            NAME                                        READY   STATUS             RESTARTS   AGE
container-registry   pod/registry-9dffc8bcf-5b2p5                0/1     Pending            0          24h
kube-system          pod/coredns-9b8997588-qs5jm                 0/1     Running            1          24h
kube-system          pod/hostpath-provisioner-7c48f5d96d-cd868   0/1     CrashLoopBackOff   105        24h

NAMESPACE            NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
container-registry   service/registry     NodePort    10.152.183.247   <none>        5000:32000/TCP           24h
default              service/kubernetes   ClusterIP   10.152.183.1     <none>        443/TCP                  46h
kube-system          service/kube-dns     ClusterIP   10.152.183.10    <none>        53/UDP,53/TCP,9153/TCP   24h

NAMESPACE            NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
container-registry   deployment.apps/registry               0/1     1            0           24h
kube-system          deployment.apps/coredns                0/1     1            0           24h
kube-system          deployment.apps/hostpath-provisioner   0/1     1            0           24h

NAMESPACE            NAME                                              DESIRED   CURRENT   READY   AGE
container-registry   replicaset.apps/registry-9dffc8bcf                1         1         0       24h
kube-system          replicaset.apps/coredns-9b8997588                 1         1         0       24h
kube-system          replicaset.apps/hostpath-provisioner-7c48f5d96d   1         1         0       24h

At the moment, there is no firewall being setup on any node at all.  So I am not quite sure why there are issues with networking at this point.  Appreciate any suggestion and help.

Thanks.

[inspection-report-20191114_191622.tar.gz](https://github.com/ubuntu/microk8s/files/3848446/inspection-report-20191114_191622.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @wpoosanguansit 

Here is a reason why you may be seeing this behavior. On each node you have a service called kube-proxy that takes care of the network configuration of the node at hand. Kube-proxy contacts the API server and asks for any information on pods and services that run on the node. By default kube-proxy assumes the node has registered on the API server with its hostname. However in your case I assume the node hosts names are not resolvable on the master. I mean that if you go on the master node and try an `nslookup "any_node_hostname"` it will tell you that this hostname is unknown. To verify that this is the problem go on a node and do a `journalctl -n 3000 -u snap.microk8s.daemon-proxy` you should see an error similar to:
```
 Nov 15 00:33:10 microk8s-node microk8s.daemon-proxy[25539]: E1115 00:33:10.000349   25539 node.go:124] Failed to retrieve node info: nodes "microk8s-node" not found
```
Please, attach the `microk8s.inspect` of a node.

There are a few ways to fix that. 
- You can have a dns service
- You can edit the `/etc/hosts` on each node to add entries for each machine you have and then join each node.
- You can edit  `/var/snap/microk8s/current/args/kube-proxy` of each node and add a `--hostname-override="IP_of_the_node_you_are_in"`, then restart the kubeproxy: `systemctl restart snap.microk8s.daemon-proxy` on that node.

I can see this being a frequent issue, we should find a way to fix it while we setup the cluster.
