### ISSUE TITLE
Shim TCP Load-balancer

### ISSUE THREAD

**Issue by DazWilkin** [ubuntu/microk8s#802]
microk8s is excellent. Thank you!

I've begun using microk8s as my exemplar Kubernetes deployment and then test additionally elswhere e.g. on Kubernetes Engine and DO.

It's reasonable to assume that each platform provides TCP Load-balancing and thus enables services with `--type=LoadBalancer` but this is untrue for microk8s.

Instead, it's possible (recommended) to `localhost:${NODEPORT}` services.

This means that microk8s is unlike (most) others.

Is there utility in providing a TCP LB shim for microk8s that defaults to the host's IP and the service's NodePort? IIUC this is a chunk of what's done by a Kubernetes Load-balancer implementation anyway.

The downside is the requirement to use unique (host) ports but this is satisfied by the uniqueness of NodePorts.

This would enable the equivalent of `kubectl expose --type=LoadBalancer` and -- I think -- would permit most deployments to continue working when querying a service's LoadBalancer.

This would bring microk8s' functionality further in line with other platforms.

Apologies if this is a naive request.

**Comment by ktsakalozos** [comment]
> microk8s is excellent. Thank you!

Thank you for using MicroK8s.

Probably the easiest option to get a loadbalancer in MicroK8s is through MetalLB. We already have a pending PR for this (https://github.com/ubuntu/microk8s/pull/759) but we haven't merge it yet.

Do you have another loadbalancer implementation in mind? We would gladly review and merge it. This is a very interesting topic.

**Comment by DazWilkin** [comment]
Thanks for the prompt and helpful reply, @ktsakalozos 

MetalLB is a good option.

I think -- and I'm perhaps I'm being overly simplistic here (!?) -- there's an even simpler option.

Classic (!) TCP Load-balancing in Kubernetes is somewhat redundant. The LB exposes an endpoint and proxies traffic to the cluster's nodes via the Nodes' (service's) NodePort. Kubernetes then proxies traffic to one of the Pods backing the service. A two-fer with the challenge that the LB is disintermediated from the backend (Pods), but...

Because microk8s is only a single Node (the host), this functionality of the Load-balancer is redundant; it must always route traffic to the same Node (the host). Because Kubernetes uniquely assigns NodePorts, it also make sense (though this could be advanced functionality) to use the NodePort as the LB's port. As a result, the TCP Load-balancer is effectively just a pass-through.

BUT it provides a benefit that a client need not ask "Are you microk8s? Do you support TCP Load-balancing?", it can simply do the equivalent of `kubectl expose service --type=LoadBalancer` (as it would only many other Kubernetes services) and get a object back that behaves like a Load-balancer, provides an endpoint (`localhost:${NodePort}`) and works as expected.

Another advantage is that, if it's a simple as I suspect, microk8s could include this as a default, trivial implementation that avoids taking additional dependencies on 3rd-party offerings.

**Comment by ktsakalozos** [comment]
Let me think about this a bit. However, I would like to point out that MicroK8s is not a single node cluster, have a look at https://microk8s.io/docs/clustering

**Comment by DazWilkin** [comment]
IDNKT :-)

Yes, this changes things.

Sorry to have wasted your time.
