### ISSUE TITLE
microk8s.enable dns doesn't work

### ISSUE THREAD

**Issue by roxax19** [ubuntu/microk8s#806]
I use `microk8s.enable dns` and it deploys the dns but the service isn't available.
The results of `microk8s.kubectl get all --all-namespaces` is:
<details>
NAMESPACE     NAME                          READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-9b8997588-7tl7s   0/1     Pending   0          2m38s

NAMESPACE     NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP                  4m54s
kube-system   service/kube-dns     ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   2m38s

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/1     1            0           2m38s

NAMESPACE     NAME                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-9b8997588   1         1         0       2m38s

</details>
So it shows AVAILABLE : 0 and the pod is Pending.

And the results of `microk8s.inspect`:
<details>
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/993/inspection-report-20191115_163840.tar.gz
</details>

My question: **What can I do too make it available?**. 

At first it went everything okey. Then I removed the snap to install another version. Then I returned to the current version with `sudo snap install microk8s --classic` and now it doesn't work.

**Comment by ktsakalozos** [comment]
@roxax19 start by describing the pod to see why it stays in the pending state: `microk8s.kubectl decribe  -n kube-system pod/coredns-9b8997588-7tl7s`. Then based on the outcome you should be able to see why it is not scheduled. With `microk8s.inspect` you get a list of all the services running, you can see the logs of each service with `journalctl -u "service_name_reported_in_inspect"`. Please attach the tarball produced by `microk8s.inspect` so I can help you more.

**Comment by roxax19** [comment]
I have reinstalled microk8s so the name have changed.
I used `microk8s.kubectl describe -n kube-system pod/coredns-9b8997588-7s5xt` and it sais:
<details>
Name:                 coredns-9b8997588-7s5xt

Namespace:            kube-system

Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 <none>
Labels:               k8s-app=kube-dns
                      pod-template-hash=9b8997588
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        ReplicaSet/coredns-9b8997588
Containers:
  coredns:
    Image:       coredns/coredns:1.5.0
    Ports:       53/UDP, 53/TCP, 9153/TCP
    Host Ports:  0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-vr2h4 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-vr2h4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-vr2h4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  no nodes available to schedule pods
  Warning  FailedScheduling  <unknown>  default-scheduler  no nodes available to schedule pods
</details>

Also for `journalctl -u service/kube-dns` (I'm not sure if that's the right way to usse it):
-- Logs begin at Sun 2018-12-16 16:17:02 CET, end at Fri 2019-11-15 17:04:10 CET. --
-- No entries --

I'm attaching the tarball.
[inspection-report-20191115_170533.tar.gz](https://github.com/ubuntu/microk8s/files/3852267/inspection-report-20191115_170533.tar.gz)

**Comment by ktsakalozos** [comment]
`microk8s.kubectl get no` shows that you have no nodes running. If you look at the kubelet logs with `journalct -u snap.microk8s.daemon-kubelet` you should see it cannot bind to 10250 port because it is in use by another application. The other application is actually a separate kubelet snap. You do not need the kubelet snap because MicroK8s packages its own. You need to `sudo snap remove kubelet` and (probably) `microk8s.stop; microk8s.start`.

**Comment by roxax19** [comment]
Thanks!! That worked perfectly. But now I'm getting an `Error: ErrImagePull`. Could you give me another hand?

The output for `microk8s.kubectl describe -n kube-system pod/coredns-9b8997588-597ls` is:
<details>
Name:                 coredns-9b8997588-597ls

Namespace:            kube-system

Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 lenovo-y50-70/172.16.158.16
Start Time:           Fri, 15 Nov 2019 18:46:05 +0100
Labels:               k8s-app=kube-dns
                      pod-template-hash=9b8997588
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Pending
IP:                   10.1.19.4
IPs:
  IP:           10.1.19.4
Controlled By:  ReplicaSet/coredns-9b8997588
Containers:
  coredns:
    Container ID:  
    Image:         coredns/coredns:1.5.0
    Image ID:      
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-7xtrf (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-7xtrf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-7xtrf
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason          Age                 From                    Message
  ----     ------          ----                ----                    -------
  Normal   Scheduled       <unknown>           default-scheduler       Successfully assigned kube-system/coredns-9b8997588-597ls to lenovo-y50-70
  Normal   SandboxChanged  3m22s               kubelet, lenovo-y50-70  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulling         88s (x4 over 3m7s)  kubelet, lenovo-y50-70  Pulling image "coredns/coredns:1.5.0"
  Warning  Failed          87s (x4 over 3m4s)  kubelet, lenovo-y50-70  Failed to pull image "coredns/coredns:1.5.0": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/coredns/coredns:1.5.0": failed reading status of resume write: stat /var/snap/microk8s/common/var/lib/containerd/io.containerd.content.v1.content/ingest/50dcd12384bf0c0801bb93cd7dcd19d7df7ed567be7b8b130bfe5a348ac7fed7/data: no such file or directory: not found
  Warning  Failed          87s (x4 over 3m4s)  kubelet, lenovo-y50-70  Error: ErrImagePull
  Normal   BackOff         71s (x6 over 3m3s)  kubelet, lenovo-y50-70  Back-off pulling image "coredns/coredns:1.5.0"
  Warning  Failed          71s (x6 over 3m3s)  kubelet, lenovo-y50-70  Error: ImagePullBackOff

</details>

I'm attaching the tarball again.
[inspection-report-20191115_185631.tar.gz](https://github.com/ubuntu/microk8s/files/3852629/inspection-report-20191115_185631.tar.gz)
I'm sorry for the inconvenience, but I'm still learning :)

**Comment by ktsakalozos** [comment]
Do you happen to be behind a firewall and/or need a proxy to reach the internet?

**Comment by roxax19** [comment]
Yes! I'm using a proxy. I have been looking how to configure microk8s when working with a proxy but I haven't found it. How can I add the configuration?

**Comment by ktsakalozos** [comment]
To let MicroK8s use a proxy enter the proxy details in `/var/snap/microk8s/current/args/containerd-env` and restart the containerd daemon service with:
```
microk8s.stop; microk8s.start
```

**Comment by Gemstone123** [comment]
@ktsakalozos 
kindly visit this:
https://github.com/ubuntu/microk8s/issues/845
