### ISSUE TITLE
Pods get 'Unauthorized' when talking to master

### ISSUE THREAD

**Issue by adrianchifor** [ubuntu/microk8s#81]
Just upgraded from `1.11.0` to `1.11.1` and getting the following in kube-dns pods:
```
E0730 20:47:05.692976       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:150: Failed to list *v1.Service: Unauthorized
E0730 20:47:05.695262       1 reflector.go:201] k8s.io/dns/pkg/dns/dns.go:147: Failed to list *v1.Endpoints: Unauthorized
I0730 20:47:05.929969       1 dns.go:173] Waiting for services and endpoints to be initialized from apiserver...
F0730 20:47:06.429965       1 dns.go:167] Timeout waiting for initialization
```
Other pods such as `nginx-ingress-controller` are failing as well.

It's a bit weird as I have `--authorization-mode=AlwaysAllow` on the `kube-apiserver`.

**Comment by ktsakalozos** [comment]
Hi @adrianchifor ,

Not sure why this would happen. Could you share some more info on your setup? What it the output of `snap list`?

As part of the release process, we deploy all addons, upgrade the snap, ensure the addons are still functional and only then we release the snap. Especially for the 1.11.0 to 1.11.1 release there was no major changes in the code. 

As soon as the new snap reaches your system the daemons restart. Could it be that there was some special configuration you did on the services that was picked up after the restart? Could you share the contents of `/var/snap/microk8s/current/args`? 

Something else we should double check is the connection between the api server and the pods. Do you see any DENY messages in the api-server logs for requests comming from the dns pod (`sudo journalctl -u snap.microk8s.daemon-apiserver.service`)? Could you share the full logs of the failing pods and the api server?

Last thought, the api server listens on port 8080 of the host. Cloud we make sure there is no other service on that port? And that the api-server is really running (`sudo systemctl status snap.microk8s.daemon-apiserver.service`).

Thank you for reporting this.
