### ISSUE TITLE
Update Istio to 1.4.0

### ISSUE THREAD

**Issue by drwatsno** [ubuntu/microk8s#819]
The version of Istio installed with MicroK8s is 1.3.4.
1.4.0 was released a couple of days ago and includes many new features.
Could the version be updated to 1.4.0? Or maybe there is a way to tell microk8s which version to install?

**Comment by ktsakalozos** [comment]
Thank you for bringing up this point @drwatsno. The task could be as easy as updating the version number in https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.istio.sh#L12

**Comment by karlmutch** [comment]
Would it be possible to bump this to Istio 1.5.1 now that things have moved on since this issue was first generated. Thanks
