### ISSUE TITLE
Allow custom hooks to be invoked pre/post upgrades

### ISSUE THREAD

**Issue by ramukima** [ubuntu/microk8s#820]
k8s cluster upgrade is not as simple as updating kubernetes control plane software packages. It involves performing tasks like backing up volumes, draining, upgrading, restoring etc. It would be great to allow custom pre and post upgrade hooks to be invoked.

**Comment by ktsakalozos** [comment]
Hi @ramukima, it was great meeting you at kubecon.

The feature you are suggesting makes sense. A user may want to time an upgrade with ops we cannot predict. While we try to make some time to work on this let me provide some pointers in case anyone wants to contribute.

MicroK8s is a snap. Snaps are made of hooks that are triggered during their lifecycle. The available hooks are described in [1]. To create pre-refresh and post-refresh user provided hooks you have to create two scripts in [2] named pre-refresh and post-refresh and inside them do something like:
```
if [ -e $SNAP_DATA/pre-refresh ]
then
  $SNAP_DATA/pre-refresh
fi
```  

So if the user creates the `pre-refresh` file under `/var/snap/microk8s/current` it will be called.


[1] https://snapcraft.io/docs/supported-snap-hooks
[2] https://github.com/ubuntu/microk8s/tree/master/snap/hooks
