### ISSUE TITLE
Microk8s on Fedora 31

### ISSUE THREAD

**Issue by soumplis** [ubuntu/microk8s#822]
It seems that Fedora 31 drops support (by default) for Cgroups v1 [1] and microk8s.status returns always bad status. After enabling v1 all seems fine.

[1] https://www.redhat.com/sysadmin/fedora-31-control-group-v2

**Comment by balchua** [comment]
Related to this https://github.com/ubuntu/microk8s/issues/651
Im not sure if containerd supports cgroups v2.  I know its being worked on perhaps in containerd 1.4.

**Comment by ktsakalozos** [comment]
@soumplis how did you enable v1 cgroups? It would be great if we could detect this setup and suggest a fix in the `microk8s.inspect` [1] command.

[1] https://github.com/ubuntu/microk8s/blob/master/scripts/inspect.sh#L104

**Comment by omkensey** [comment]
Here are more details on Fedora 31, containers, and cgroups, including how to switch back to CGroups V1 (requires a reboot though): https://docs.fedoraproject.org/en-US/fedora/f31/release-notes/developers/Containers/
