### ISSUE TITLE
Add Crossplane addon

### ISSUE THREAD

**Issue by displague** [ubuntu/microk8s#825]
This issue is to gauge interest, obstacles, and traction towards including [Crossplane](https://crossplane.io/docs/v0.5/) in MicroK8s.

Crossplane provides a controller and CRDs for managing Cloud infrastructure  (such as `RDSInstance`, `CloudSQLInstance`, `GKECluster`, `AKSCluster`) from within Kubernetes.  Crossplane adds abstractions such as `MySQLInstance` and `KubernetesCluster` which, similar to how PV Claims rely on StorageClasses, are resolved using configuration resources.

A workload resource type, `KubernetesApplication` provides a way to create a set of resources on a provisioned cluster.  This is similar to how a `Deployment` templates `Pods`.

MicroK8s could then be used to provision and manage new clusters, other types of cloud resources, and applications using the Crossplane semantics.

Supported stacks currently include GCP, AWS, Azure, and others.  A Rook stack is also available for provisioning "infrastructure" resources within the cluster.  The resource types that have portable claim types (abstractions) are `MySQLInstance`, `PostgreSQLInstance`, `RedisCluster`, `MachineInstance` (VMs), `KubernetesCluster`, and `BucketStorage` (S3-like services).

**Comment by ktsakalozos** [comment]
This is very interesting! Do you see this as a `microk8s.enable crossplane` option coupled with a MicroK8s specific provider?

**Comment by displague** [comment]
`microk8s.enable crossplane` would install crossplane and would allow you to start provisioning managed cloud clusters and other managed cloud services from your MicroK8s cluster.

Stack-Rook is an example of a non-Cloud service that Crossplane can provision.

I think a MicroK8s provider (`stack-microk8s`) would be interesting, but I don't know how Crossplane would go about provisioning more MicroK8s clusters from within MicroK8s.

Are there examples of running MicroK8s from a bare docker environment, or better yet, through ClusterAPI or a microk8s-operator?  Kind and K3s might be similar fits for a local cluster option (managed through the crossplane control cluster).
