### ISSUE TITLE
Unable to enable dns and storage after remove and reinstall.

### ISSUE THREAD

**Issue by wpoosanguansit** [ubuntu/microk8s#831]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

Hi,

I am on Raspberry Pi 3 b+ boards.  I do have 5 instances installed and joined successfully.  But I ran into deployment issues so I decided to start everything fresh.  However, when i did that, snap remove and snap install, I could not get the cluster up and running like I did the first time anymore.  I do get errors when I tried to enable dns storage like in the quick start guide.

```
ubuntu@node23:~$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1076/inspection-report-20191127_233932.tar.gz
```

```
ubuntu@node23:~$ microk8s.enable dns storage
Enabling DNS
Applying manifest
E1127 21:51:31.489682    7091 request.go:879] Unexpected error when reading response body: context deadline exceeded (Client.Timeout exceeded while reading body)
serviceaccount/coredns unchanged
configmap/coredns unchanged
clusterrole.rbac.authorization.k8s.io/coredns unchanged
clusterrolebinding.rbac.authorization.k8s.io/coredns unchanged
Error from server (InternalError): error when creating "/home/ubuntu/snap/microk8s/1076/tmp/temp.coredns.yaml": Internal error occurred: resource quota evaluates timeout
error when creating "/home/ubuntu/snap/microk8s/1076/tmp/temp.coredns.yaml": Post https://127.0.0.1:16443/api/v1/namespaces/kube-system/services: stream error: stream ID 17; INTERNAL_ERROR
Failed to enable dns
```
[inspection-report-20191127_233932.tar.gz](https://github.com/ubuntu/microk8s/files/3899167/inspection-report-20191127_233932.tar.gz)

Appreciate your help.

**Comment by ktsakalozos** [comment]
I see that the API server is not healthy. Can you describe in as much detail as possible the steps you have taken after snap installing the master node? I am looking for a way to reproduce the setup you have. How do you setup the cluster? Do you have a script for this purpose?

**Comment by wpoosanguansit** [comment]
At first, I have the master node with 8 client nodes connected and setup correctly to the point where I could deploy my app.  I tried to have 5 in the replica set but that didn't work so I reduced that down to 3.  That seems to be stable enough so I went on to the next step which is to have ingress pointing to the app.  I created services along with the deployment and followed this article https://kndrck.co/posts/microk8s_ingress_example/.  I also did try to stop pods being deposed on master by editing the files /var/snap/microk8s/current/args/kube-apiserver and add this --feature-gates=ScheduleDaemonSetPods=false and did the same for kube-controller-manager and kube-scheduler. but things didn't work at all.  So I decided to reset.  That is the back story for the state of the machines.

The things I did after having the deployment but not the ingress working, I just did:

microk8s.reset on the master.

From that, I tried add-node afterwards but things do not work at all.  Of the five nodes I tried to add, two were able to join.  So I decided to do a clean install.  I did:

sudo apt remove microk8s && sudo snap install microk8s --classic --channel=1.16/edge

From that I tried the normal steps in Quickstart to try to get back to where I was.  But I could not even enable dns as reported.

So the question I have is does remove and reinstall do clean install?  Or is there something lingering around even when I do remove and reinstall?  How do I totally remove everything for microk8s and really start from scratch?  Thanks.

**Comment by ktsakalozos** [comment]
The removal does not leave anything behind. I see you wrote above `sudo apt remove microk8s`, the right command is `sudo snap remove microk8s`. Could that be the problem?

**Comment by wpoosanguansit** [comment]
Oh, it is actually sudo snap remove microk8s.  Without snap it wouldn’t work.

**Comment by wpoosanguansit** [comment]
So any suggestion what I should try or do to debug the issue?

**Comment by ktsakalozos** [comment]
I do not think the removal was clean. I see for example the `--feature-gates=ScheduleDaemonSetPods=false` argument in the arguments list. Could you try a clean removal and installation cycle?

**Comment by wpoosanguansit** [comment]
So I just need to do sudo snap remove microk8s?  After I do that, how do I check it was a clean removal?

**Comment by ktsakalozos** [comment]
There should not be any `microk8s.*` in your path. There should not be anything under `/var/snap/` or `/snap/`.

**Comment by wpoosanguansit** [comment]
This is what I have after remove:

ubuntu@node23:~$ sudo snap remove microk8s
microk8s removed
ubuntu@node23:~$ ls /var/snap/
core  lxd
ubuntu@node23:~$ ls /var/snap/core
7920  8042  common  current
ubuntu@node23:~$ ls /snap
README  bin  core  lxd

I will try reinstalling and following Quickstart guide again.

**Comment by wpoosanguansit** [comment]
After I did a clean install, reinstalling ubuntu and microk8s for master.  But I am still getting these errors:

microk8s.enable dns storage
Enabling DNS
Applying manifest
E1129 23:15:32.725515    1232 request.go:879] Unexpected error when reading response body: net/http: request canceled (Client.Timeout exceeded while reading body)
configmap/coredns created
clusterrole.rbac.authorization.k8s.io/coredns created
Error from server (Timeout): error when creating "/home/ubuntu/snap/microk8s/1094/tmp/temp.coredns.yaml": the server was unable to return a response in the time allotted, but may still be processing the request (post serviceaccounts)
Error from server (Timeout): error when creating "/home/ubuntu/snap/microk8s/1094/tmp/temp.coredns.yaml": the server was unable to return a response in the time allotted, but may still be processing the request (post deployments.apps)
Error from server (Timeout): error when creating "/home/ubuntu/snap/microk8s/1094/tmp/temp.coredns.yaml": the server was unable to return a response in the time allotted, but may still be processing the request (post services)
error when creating "/home/ubuntu/snap/microk8s/1094/tmp/temp.coredns.yaml": Post https://127.0.0.1:16443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings: stream error: stream ID 33; INTERNAL_ERROR
Failed to enable dns

```
microk8s.kubectl get no --all-namespaces                                                                   master: Fri Nov 29 23:29:03 2019

NAME           STATUS   ROLES    AGE   VERSION
192.168.1.10   Ready    <none>   89m   v1.16.3
192.168.1.12   Ready    <none>   53m   v1.16.3
192.168.1.13   Ready    <none>   47m   v1.16.3
192.168.1.14   Ready    <none>   23m   v1.16.3
master         Ready    <none>   19h   v1.16.3
```

microk8s.kubectl get all --all-namespaces                                                                  master: Fri Nov 29 23:26:49 2019

NAMESPACE   NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
default     service/kubernetes   ClusterIP   10.152.183.1   <none>        443/TCP   19h

**Comment by ktsakalozos** [comment]
Can I have the `microk8s.inspect` tarball.

**Comment by wpoosanguansit** [comment]
I attached above.

https://github.com/ubuntu/microk8s/files/3906545/inspection-report-20191129_234159.tar.gz
