### ISSUE TITLE
Is microk8s supporting kubectl plugins?

### ISSUE THREAD

**Issue by yuxx0248** [ubuntu/microk8s#841]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
```
@working-computer:~$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
 FAIL:  Service snap.microk8s.daemon-flanneld is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-flanneld
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1073/inspection-report-20191130_233811.tar.gz

```

Is microk8s currently supporting plugins? Or I just mess up some setups...
I installed some popular plugins and kubectl was able to find them with plugin list
```
working-computer:~$ sudo microk8s.kubectl plugin list
The following compatible plugins are available:

/usr/local/bin/kubectl-ctx
/usr/local/bin/kubectl-krew
/usr/local/bin/kubectl-ns

```

But the ctl cannot find it when I try to use them
```
working-computer:~$ sudo microk8s.kubectl krew
Error: unknown command "krew" for "kubectl"
Run 'kubectl --help' for usage.
```

At this moment, I am not sure whether this is a microk8s issue or kubectl issue, but since I am able to use these plugins on my mac with minikube, I am opening the issue here first. 

Thank you for your help!

**Comment by balchua** [comment]
@yuxx0248 can you try running `microk8s.kubectl` without sudo?

Before that you have to add your user to the `microk8s` group.  Like this `sudo usermod -a -G microk8s <username>`

**Comment by yuxx0248** [comment]
Behave the same after doing that
```
working-computer:~$ microk8s.kubectl plugin list
The following compatible plugins are available:

/usr/local/bin/kubectl-ctx
/usr/local/bin/kubectl-krew
/usr/local/bin/kubectl-ns
```
```
working-computer:~$ microk8s.kubectl krew
Error: unknown command "krew" for "kubectl"
Run 'kubectl --help' for usage.

```

**Comment by yuxx0248** [comment]
[inspection-report-20191130_233811.tar.gz](https://github.com/ubuntu/microk8s/files/3908094/inspection-report-20191130_233811.tar.gz)

**Comment by yuxx0248** [comment]
quick question, is this working for any of you? Just want to sure if it's something I didn't do right or it's a feature request

**Comment by balchua** [comment]
@yuxx0248 i haven't tried it myself.
And what i usually do is that i get the kubeconfig from microk8s and use an external `kubectl`.

To get kubeconfig, you can do `microk8s.kubectl config view --raw > $HOME/.kube/config` from there you can start using your own `kubectl`.

**Comment by balchua** [comment]
@yuxx0248 it could be apparmor is denying the execution of binaries outside the snap confines.

**Comment by balchua** [comment]
I think i know the issue here.  `microk8s.kubectl` adds the option `--kubeconfig=` when invoked.  This breaks `kubectl` when invoking a plugin.  
In short it runs like this:
`kubectl --kubeconfig='wherethekubeconfigis` krew --help`

If running this on a standalone `kubectl` (i.e. not part of microk8s), it also spits out the same error.

Have you tried adding options in kubectl and pair it with a plugin execution?

**Comment by ktsakalozos** [comment]
Thank you for reporting and debugging this. Here is what you can do:
- edit `/var/snap/microk8s/current/args/kubectl` and comment out the line that adds the `--kubeconfig` argument. 
- place the kubeconfig file in the default location so `microk8s.kubectl` can find it `microk8s.config > ~/.kube/config`

After that the plugin should work:
```
$ microk8s.kubectl krew
krew is the kubectl plugin manager.
You can invoke krew through kubectl: "kubectl krew [command]..."

Usage:
  krew [command]

Available Commands:
  help        Help about any command
  info        Show information about a kubectl plugin
  install     Install kubectl plugins
  list        List installed kubectl plugins
  search      Discover kubectl plugins
  uninstall   Uninstall plugins
  update      Update the local copy of the plugin index
  upgrade     Upgrade installed plugins to newer versions
  version     Show krew version and diagnostics
```

Right now I am not sure how to permanently fix this. It is strange that the plugin funstionality gets affected by the `--kubeconfig` argument.

**Comment by balchua** [comment]
One way that i think we can fix this is to remove the kubectl config and add `KUBECONFIG=${SNAP_DATA}/credentials/client.config` 
But i do have a question when strict confinement is applied will the `kubectl` inside the snap be able to execute external executables?

**Comment by yuxx0248** [comment]
So I started to use a regular kubectl as my solution as for now. Where do we want to go for this ticket here tho

**Comment by ktsakalozos** [comment]
We would at least document this process and place it in https://microk8s.io/docs/ this is what the Q&A label is for. If we see this being a frequent ask we should consider looking into a less involving process.

**Comment by yuxx0248** [comment]
You mean documenting how to use the native kubectl instead? Or why microk8s.kubectl isn't working as expected? I am willing to put something in if I can lol
