### ISSUE TITLE
Support parameters like "--image-mirror-country" and "--image-repository"

### ISSUE THREAD

**Issue by davix** [ubuntu/microk8s#842]
The default k8s.gcr.io is not always available to all areas. In this case, commands like `microk8s.enable dns` will not succeed.

Setting up a HTTPS proxy and configuraing it in `/var/snap/microk8s/current/args/containerd-env` can be an option, but it's not an easy task to find such a proxy.

Another option is to specify the image-repository to use.
Minikube supports parameters as below:

```
      --image-mirror-country='': Country code of the image mirror to be used. Leave empty to use the global one. For
Chinese mainland users, set it to cn.
      --image-repository='': Alternative image repository to pull docker images from. This can be used when you have
limited access to gcr.io. Set it to "auto" to let minikube decide one for you. For Chinese mainland users, you may use
local gcr.io mirrors such as registry.cn-hangzhou.aliyuncs.com/google_containers
```

Suggest microk8s add this support as well.

**Comment by ktsakalozos** [comment]
This is a great suggestion @davix.

I suspect we will need a directory in [1] with mappings of registries to mirrors per country. Then in use_manifest [2]  we would patch the manifests before applying them based on the active mapping. A simple sed should be enough for most of the cases. We would also need to review all the addon scripts at [3] for any curl calls.

It seems a straight forward task but it is not a small one-liner either. Let me know if anyone wants to work on this. Thank you.

[1] https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/default-args
[2] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/common/utils.sh#L174
[3] https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions
