### ISSUE TITLE
Upgrade to helm 3

### ISSUE THREAD

**Issue by davix** [ubuntu/microk8s#843]
Helm 3 has already been released and it will replace helm 2.

microk8s.helm is still using v2.16.0.

**Comment by ktsakalozos** [comment]
We will probably need a transition strategy here. We could have a `microk8s.enable helm3` command similar to [1] that would link the helm3 client binary to the `microk8s.helm` command. This way the user would need to explicitly state that he want helm3. 

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.helm.sh#L23

**Comment by qs** [comment]
As a quick alternative solution you can also just install helm with snap by yourself and create a link to it for microk8s:
```
sudo snap install helm --classic
sudo mkdir /var/snap/microk8s/current/bin
sudo ln -s /snap/bin/helm /var/snap/microk8s/current/bin/helm
```

**Comment by krichter722** [comment]
What's the purpose of a custom helm command for microk8s? I'd consider myself an advanced highly regular user of microk8s exploring all sorts of k8s features. And I never had any issues using the version shipped with snap or release tarballs from gethelm.sh. Maybe the function can be deprecated or removed in order to prevent maintenance efforts.

**Comment by r8code** [comment]
> As a quick alternative solution you can also just install helm with snap by yourself and create a link to it for microk8s:
> 
> ```
> sudo snap install helm --classic
> sudo mkdir /var/snap/microk8s/current/bin
> sudo ln -s /snap/bin/helm /var/snap/microk8s/current/bin/helm
> ```

Thank you , been waiting for current solution on how using helm 3 with microk8s

**Comment by ktsakalozos** [comment]
@krichter722 the helm addon and all addons are here to save you time. The functionality offered by the addons is often trivial. For example, setting up DNS, getting the dashboard up setting up a storage class, a registry and helm are steps users usually have to take to come to a working environment. By themselves each step is trivial but all of them together introduce some complexity. For advance users like you ignoring the helm addon and installing it manually is fine. For me that I do not use helm so often it is good that I do not need to lookup the documentation on how to install it.

**Comment by balchua** [comment]
PR Already merged to master.

**Comment by Rzpeg** [comment]
Is there any ETA for the stable channel ?

**Comment by ktsakalozos** [comment]
> What's the correct way of upgrading and migrate existing helm deployments from v2 to v3 in microk8s?

I think you should ask this question over at https://github.com/helm/helm

**Comment by renefritze** [comment]
I'm using the `1.19/stable` snap and it seems I cannot enable the `helm3` addon:
```
root@MACHINE:~# microk8s.enable helm3
Nothing to do for helm3
root@MACHINE:~# microk8s helm3
'helm3' is not a valid MicroK8s subcommand.
```
What am I doing wrong?

**Comment by balchua** [comment]
@renefritze may i know what arch you are using? Helm3 is only available for arm64 and amd64.

**Comment by renefritze** [comment]
> @renefritze may i know what arch you are using? Helm3 is only available for arm64 and amd64.

amd64 (running debian 10)

**Comment by ktsakalozos** [comment]
Hi @renefritze, the "Nothing to do for helm3" is shown when there is not enable script or yaml manifest for the respective addon (helm3 in this case) under `/snap/microk8s/current/actions` [1]. Could you attach the `microk8s.inspect` report tarball?

Also (unrelated to this issue) the capital letters in the hostname  will probably get you into trouble if you try to enable RBAC.

[1] https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-enable.wrapper#L60

**Comment by renefritze** [comment]
Sorry, but that's a whole lot of logs I'd need to check for sensitive info. If there's no more specific info I can help with I'll live with posted workaround.
