### ISSUE TITLE
Prometheus Operator (via add-on) broken on microk8s v1.16

### ISSUE THREAD

**Issue by cscheib** [ubuntu/microk8s#844]
There appears to be an issue with the version of the prometheus-operator that is installed via `microk8s.enable prometheus`.  This seems to be related to some deprecated APIs in k8s v1.16, specifically apps/v1beta2 for the StatefulSets that the operator generates.

Behaviors observed: after I enable prometheus on v1.16, the prometheus-k8s-0 pod is not created, and I see errors similar to the following in the logs:
```
prometheus-operator-84c6fd4988-7mndc prometheus-operator E1202 03:27:05.196218       1 reflector.go:134] github.com/coreos/prometheus-operator/pkg/prometheus/operator.go:399: Failed to list *v1beta2.StatefulSet: the server could not find the requested resource
prometheus-operator-84c6fd4988-7mndc prometheus-operator E1202 03:27:06.247019       1 reflector.go:134] github.com/coreos/prometheus-operator/pkg/alertmanager/operator.go:233: Failed to list *v1beta2.StatefulSet: the server could not find the requested resource
```
The operator itself seems to be trying to query and/or create resources of a deprecated API version.

This is not directly a microk8s issue, but there will be action needed to ensure that the prometheus addon installed in v1.16 uses an updated version of the operator.  I manually updated the deployment to use `image: quay.io/coreos/prometheus-operator:v0.34.0` rather than `image: quay.io/coreos/prometheus-operator:v0.25.0`, which seemed to get me further along.  The `prometheus-k8s-0` pod was created, and 2/3 containers went into Running status.  That didn't get me to a fully running state, as other adjustments to the deployments were likely required.

It looks like some work has already been done to get v0.34.0 integrated, as some of the manifests for prometheus in the microk8s repo seem to have it there.  If there's a way to pull an updated microk8s add-on I'm not aware of it.

microk8s snap version: v1.16.3, Rev 1079
Ubuntu installation method: via multipass on OSX

Note: i have created and destroyed this cluster a few times to verify the behavior.  I have also run lower versions (1.14, 1.15), which I can get prometheus working on.

Attached is a `microk8s.inspect` report, which was run after I updated the deployment with v0.34.0 of the operator.  I imagine it has before and after logs in its contents, though.

[inspection-report-20191201_223336.tar.gz](https://github.com/ubuntu/microk8s/files/3909368/inspection-report-20191201_223336.tar.gz)

**Comment by cscheib** [comment]
Appears to have been resolved by the following issue and pull request in upstream prometheus-operator:
https://github.com/coreos/prometheus-operator/issues/2649
https://github.com/coreos/prometheus-operator/pull/2652

**Comment by ktsakalozos** [comment]
@cscheib thank you for reporting this. We recently updated the prometheus operator in the 1.16 and latest tracks (PR https://github.com/ubuntu/microk8s/pull/834). While waiting for the update to get propagated to stable can you try the edge channel?
```
sudo snap install microk8s --classic --channel=1.16/edge
```

**Comment by cscheib** [comment]
@ktsakalozos that does appear to work, thank you.

Sorry for the noob question, but is there a way to tell which version of the add-on manifests actually get applied in any given scenario?  I don't know how 1.16/edge vs 1.16/stable relate to the commit history in this microk8s repo.  Knowledge of that may have helped me figure this out on my own.  The tag/branch structure doesn't seem to directly map to the channels.

**Comment by ktsakalozos** [comment]
@cscheib the MicroK8s tracks you see with `snap info microk8s` are build from corresponding github branches. For example 1.16/stable, 1.16/candidate, 1.16/beta, 1.16/edge are all build from the 1.16 branch. A build starts from the edge channel and slowly gets tested and makes its way through the rest of the channels until it reaches stable. The edge channel gets updated 4 times a day with builds using the code in the respective github branch. When an upstream release comes out (eg when on 1.16.3 and 1.16.4 comes out) we push to beta and candidate what we currently have on edge. After a week and given no major problems found whatever is on candidate is pushed to stable. We describe the intended use of channels in https://microk8s.io/docs/setting-snap-channel .

You point is valid, we would like to improve clarity on what is on every channel at any point in time. The challenge is to do this in an automated way without the need of a human assembling a list of component versions. Any suggestions would be much appreciated. Thank you.
