### ISSUE TITLE
microk8s dns show running status but remains in 0/1 state 

### ISSUE THREAD

**Issue by Gemstone123** [ubuntu/microk8s#845]
i'm trying to customize nginx-ingress controller in microk8s. when i enable dns its status is shown below:

microk8s.kubectl get all --all-namespaces

NAMESPACE     NAME                                          READY   STATUS             RESTARTS   AGE
ingress       pod/nginx-ingress-microk8s-controller-gwm9n   0/1     CrashLoopBackOff   7          12m
kube-system   pod/coredns-9b8997588-k77dd                   0/1     Running            0          15m

NAMESPACE     NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP                  18m
kube-system   service/kube-dns     ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   15m

NAMESPACE   NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
ingress     daemonset.apps/nginx-ingress-microk8s-controller   1         1         0       1            0           <none>          12m

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/1     1            0           15m

NAMESPACE     NAME                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-9b8997588   1         1         0       15m
------------------------------------------------------------------------------------------------------------------------

due to this dns problem ingress controller keeps restarting repeatedly. 

microk8s.kubectl -n kube-system describe pod coredns-9b8997588-k77dd

Name:                 coredns-9b8997588-k77dd
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 k8s-master/192.168.0.198
Start Time:           Mon, 02 Dec 2019 07:20:50 +0000
Labels:               k8s-app=kube-dns
                      pod-template-hash=9b8997588
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Running
IP:                   10.1.51.14
IPs:
  IP:           10.1.51.14
Controlled By:  ReplicaSet/coredns-9b8997588
Containers:
  coredns:
    Container ID:  containerd://515e1755dc498716863895b98a97b90733886786d4d8a7cb050c5e351e64c091
    Image:         coredns/coredns:1.5.0
    Image ID:      docker.io/coredns/coredns@sha256:e83beb5e43f8513fa735e77ffc5859640baea30a882a11cc75c4c3244a737d3c
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Running
      Started:      Mon, 02 Dec 2019 07:20:51 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-pwf5w (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-pwf5w:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-pwf5w
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                 Message
  ----    ------     ----  ----                 -------
  Normal  Scheduled  10m   default-scheduler    Successfully assigned kube-system/coredns-9b8997588-k77dd to k8s-master
  Normal  Pulled     10m   kubelet, k8s-master  Container image "coredns/coredns:1.5.0" already present on machine
  Normal  Created    10m   kubelet, k8s-master  Created container coredns
  Normal  Started    10m   kubelet, k8s-master  Started container coredns

-----------------------------------------------------------------------------------------------------------------
in my /var/log/containers directory the coredns-container log file contains following output:

sudo cat coredns-9b8997588-k77dd_kube-system_coredns-515e1755dc498716863895b98a97b90733886786d4d8a7cb050c5e351e64c091.log 
2019-12-02T07:20:51.573981332Z stdout F E1202 07:20:51.573622       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Get https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: connect: connection refused
2019-12-02T07:20:51.574031438Z stdout F E1202 07:20:51.573682       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: connect: connection refused

**Comment by ktsakalozos** [comment]
Firewall is often the reason for such errors. You go over the common issues in https://microk8s.io/docs/troubleshooting#common-issues. Also can you share the output and tarball produced by `microk8s.inspect`. Thank you.

**Comment by ktsakalozos** [comment]
@Gemstone123 did you find what the issue was?

**Comment by Gemstone123** [comment]
nope couldn't find it

**Comment by ktsakalozos** [comment]
A similar issue is this one: https://github.com/ubuntu/microk8s/issues/854#issuecomment-564547247

Can you make sure your iptable rules allow traffic between the pods and the services in the clusterip subnet?

**Comment by Moeletji17** [comment]
I'm having the same issue and we're using iptables as the firewall. Microk8s adds the rules required but do the following ports (https://microk8s.io/docs/ports) need to be added to the iptables?
