### ISSUE TITLE
Disabled --insecure-port in kube-apiserver breaks service and ingress resources

### ISSUE THREAD

**Issue by lazzarello** [ubuntu/microk8s#847]
I can't include the microk8s.inspect output due to some of my nation's regulations. Apologies in advance. My goal is to reconfigure microk8s for only TLS access using port 8080.

I would like to disable the insecure-port in the kube-apiserver. I couldn't find a way to do this, but setting `--insecure-port=0` seems to disable something. I have updated the config to  `--secure-port=8080`. With this configuration, microk8s.status reports it is running and kubectl shows all resources as operating correctly. 

But no services or ingress resources are listening on a port, so all my application's UI screens return with a connection refused.

**Comment by balchua** [comment]
Curious to know, u are using 1.13?

**Comment by lazzarello** [comment]
1.15.6

**Comment by balchua** [comment]
The 1.15.6 secure port is bound to `16443` and you want it to be in `8080`?

**Comment by lazzarello** [comment]
correct. I also want to disable the insecure port.

**Comment by balchua** [comment]
@lazzarello i am guessing you have changed all the configuration related to `controller-manager`, `scheduler`, `proxy` and `kubelet` to point to the new port 8080?
They mostly reside in `/var/snap/microk8s/current/credentials/`

Strangely enough `--insecure-port` is not listed in the kube-apiserver reference doc.

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

When you say no ports in

**Comment by lazzarello** [comment]
I did not change the other configuration, which makes sense why it wouldn't work. Sorry for the noise.

I'm also concerned about how the microk8s kube-apiserver has parameters that are absent from upstream documentation. In addition to `--insecure-port` the reference doc doesn't list `--basic-auth-file` as a valid option.

**Comment by balchua** [comment]
The `--basic-auth-file` option is described here.  https://kubernetes.io/docs/reference/access-authn-authz/authentication/#static-password-file
But not in the api servers reference doc.

**Comment by ktsakalozos** [comment]
The `--basic-auth-file` and `--insecure-port` are being deprecated and this is why they are not present in the upstream docs. The work on disabling the insecure port is in this commit [1]. It is a rather involving process. @lazzarello you could consider moving to v1.16 where this has already landed.

[1] https://github.com/ubuntu/microk8s/commit/8173dce3189d376bd0267b9f2d62ef11193d5ada
