### ISSUE TITLE
Update the CNI to the latest version

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#85]
This request came from the slack channel where people reported problems with the CNI 0.6.0 + our docker + IPv6.

Probably related issue: https://github.com/containernetworking/cni/issues/531

**Comment by nirvdrum** [comment]
Thanks for opening the issue. I'm the guy that asked about whether CNI could be upgraded on Slack. I had difficulties building microk8s myself, so I can't confirm that upgrading CNI will fix my problem, but that issue you linked is what got me on this train of thought.

I'm running Docker 18.06.0-ce on Ubuntu 18.04 and microk8s failed to run the job started via `kubectl create -f https://k8s.io/examples/controllers/job.yaml`.

Unfortunately, I don't have a log readily available. I uninstalled microk8s in favor of minikube. I can try microk8s again if you think the log would be helpful. The reason I went for a full uninstall is something in that interaction was causing my network connection to be dropped and reestablished. So, it wasn't just a matter of the job failing to create -- there was a negative impact to the host as well. The only way I found to halt the network restart loop was to stop the Docker daemon.
