### ISSUE TITLE
etcd causes high io writes on btrfs

### ISSUE THREAD

**Issue by neilbags** [ubuntu/microk8s#852]
Installed microk8s on Debian 10, Linux 4.19. Rootfs is btrfs

I'm seeing etcd writes at ~10MB/s even with no pods running, and no plugins enabled. As soon as I moved /var/snap to ext4 writes dropped to ~10kB/s. 

Assuming this is to do with CoW. Not sure if its microk8s specific

While on btrfs:
[inspection-report-20191125_124950.tar.gz](https://github.com/ubuntu/microk8s/files/3936013/inspection-report-20191125_124950.tar.gz)

While on ext4:
[inspection-report-20191208_195555.tar.gz](https://github.com/ubuntu/microk8s/files/3936014/inspection-report-20191208_195555.tar.gz)

**Comment by neilbags** [comment]
While on btrfs:
[inspection-report-20191125_124950.tar.gz](https://github.com/ubuntu/microk8s/files/3936009/inspection-report-20191125_124950.tar.gz)

**Comment by iczero** [comment]
Same problem here. On my laptop, etcd constantly writes around 30 MB/s while idle. Disabling copy-on-write on `/var/snap/microk8s/common/var/run/etcd` using `chattr +C` and then rewriting all the files didn't reduce i/o.

**Comment by iczero** [comment]
Apparently the same happens even without microk8s. Running etcd with a data dir inside btrfs and running
```bash
etcdctl mk date < /dev/null
while sleep 0.25; do
    date | etcdctl set date
done
```
causes about 50 MB/s write to the disk. 

Interestingly, loop-mounting an ext4 image (from btrfs) and putting the data dir in there reduces the io to only about 500 KB/s:
```bash
touch ext4.img
chattr +C ext4.img
truncate -s 512M ext4.img
sudo losetup /dev/loop21 ./ext4.img
sudo mkfs.ext4 /dev/loop21
mkdir mount
sudo mount /dev/loop21 mount
```

**Comment by mar-kolya** [comment]
It looks like the only way to avoid high write IO is to put etcd data onto ext4 fs. That ext4 fs may potentially be a non-cow-enabled file on btrfs...
