### ISSUE TITLE
how to set http_proxy when microk8s.enable

### ISSUE THREAD

**Issue by Hokwang** [ubuntu/microk8s#856]
Hello.

After install microk8s in my ubuntu 16.04,
I want to enable istio and helm

$ sudo microk8s.enable istio
Enabling Istio
Fetching istioctl version v1.3.4.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:08 --:--:--     0

In my corporate http_proxy, I need to set proxy config.

But I can't find how to do.

**Comment by balchua** [comment]
Try this.
https://github.com/ubuntu/microk8s/issues/396#issuecomment-478253659

**Comment by Hokwang** [comment]
@balchua

I already done, but it didn't work.

$ sudo cat /var/snap/microk8s/current/args/containerd-env
# To start containerd behind a proxy you need to add an HTTPS_PROXY
# environment variable in this file. HTTPS_PROXY is of the following form:
# HTTPS_PROXY=http://username:password@proxy:port/
# where username: and password@ are optional. eg:
#
# HTTPS_PROXY=https://squid.internal:3128
#
#
# Remember to restart the containerd daemon after editing this file:
#
# sudo systemctl restart snap.microk8s.daemon-containerd.service
#
#

# Attempt to change the maximum number of open file descriptors
# this get inherited to the running containers
#
ulimit -n 65536 || true

HTTP_PROXY=http://proxyip:port
HTTPS_PROXY=http://proxyip:port

and I 'v done also
`sudo systemctl restart snap.microk8s.daemon-containerd.service`

**Comment by Hokwang** [comment]
and I mean it is the download time not related with container.

**Comment by balchua** [comment]
Oh i get it now. Its not the containerd. Its the script.  Exporting the `HTTP_PROXY` and HTTPS_PROXY` before running the script also doesn't work?

**Comment by Hokwang** [comment]
@balchua 
I can install microk8s using snap with proxy setting as you mentioned.
But this is not related with snap's proxy setting.

I found problem point is 

/snap/microk8s/1079/actions/enable.istio.sh

there's 
```
CA_CERT=/snap/core/current/etc/ssl/certs/ca-certificates.crt
run_with_sudo "${SNAP}/usr/bin/curl" --cacert $CA_CERT -L https://github.com/istio/istio/releases/download/${ISTIO_ERSION}/istio-${ISTIO_ERSION}-linux.tar.gz -o "$SNAP_DATA/tmp/istio/istio.tar.gz"
```
your ca_cert does not have mine, my company's and curl command does not use -k option.

this is problem.
and I can't edit this file and /snap/core/current/etc/ssl/certs/ca-certificates.crt because of readonly permission.

**Comment by balchua** [comment]
Your proxy is using https with self signed cert?

**Comment by Hokwang** [comment]
```
$ env | grep pro
http_proxy=http://proxyip:port
https_proxy=http://proxyip:port
$ curl -L https://github.com/istio/istio/releases/download/1.3.4/istio-1.3.4-linux.tar.gz -o out
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   614    0   614    0     0   1099      0 --:--:-- --:--:-- --:--:--  1100
100 36.3M  100 36.3M    0     0  1382k      0  0:00:26  0:00:26 --:--:-- 2342k
```
this works and also curl -Lk is works.
and in my linux install company cert file already

how to test for you?

**Comment by balchua** [comment]
That is strange. As far as i know github.com is verified by standard CAs thats why it uses the certs part of the snap core.

**Comment by chensima1001** [comment]
I also encountered the same problem, my proxy has a self-signed certificate,  do you have a solution？
@Hokwang @balchua

**Comment by balchua** [comment]
not a snap expert here, but maybe you can try bind mounting the system certs to snap certificates.  like this.  `sudo mount --bind -o nodev,ro /etc/ssl/certs /snap/core/current/etc/ssl/certs/`
i got the answer from here. https://askubuntu.com/questions/919091/why-can-snap-files-not-be-modified-in-any-way
There is a note there though that it might not survive a reboot.

**Comment by chensima1001** [comment]
it seems not a problem with snap certificates,  It worked when i set the proxy in the `/etc/environment`. But not useful by 
```
$ sudo snap set system proxy.http="http://<proxy_addr>:<proxy_port>"
$ sudo snap set system proxy.https="http://<proxy_addr>:<proxy_port>"
```

**Comment by balchua** [comment]
@chensima1001 thank you for confirming that it works by adding the proxy in `/etc/environment` and not those using snap settings.

**Comment by happyxhw** [comment]
I solved this:
Read enable.istio.sh,
do the downloading action manually
mkdir the dir, and copy the files just do by the enable.istio.sh

```bash
if [ ! -f "${SNAP_DATA}/bin/istioctl" ]
then
  ISTIO_VERSION="v1.3.4"
  echo "Fetching istioctl version $ISTIO_VERSION."
  ISTIO_ERSION=$(echo $ISTIO_VERSION | sed 's/v//g')
  run_with_sudo mkdir -p "${SNAP_DATA}/tmp/istio"
  (cd "${SNAP_DATA}/tmp/istio"
  run_with_sudo "${SNAP}/usr/bin/curl" --cacert $CA_CERT -L https://github.com/istio/istio/releases/download/${ISTIO_ERSION}/istio-${ISTIO_ERSION}-linux.tar.gz -o "$SNAP_DATA/tmp/istio/istio.tar.gz"
  run_with_sudo gzip -d "$SNAP_DATA/tmp/istio/istio.tar.gz"
  run_with_sudo tar -xvf "$SNAP_DATA/tmp/istio/istio.tar")
  run_with_sudo mkdir -p "$SNAP_DATA/bin/"
  run_with_sudo mv "$SNAP_DATA/tmp/istio/istio-${ISTIO_ERSION}/bin/istioctl" "$SNAP_DATA/bin/"
  run_with_sudo chmod +x "$SNAP_DATA/bin/"

  run_with_sudo mkdir -p "$SNAP_DATA/actions/istio/"

  run_with_sudo cp "$SNAP_DATA/tmp/istio/istio-${ISTIO_ERSION}"/install/kubernetes/helm/istio-init/files/crd*.yaml "$SNAP_DATA/actions/istio/"
  run_with_sudo mv "$SNAP_DATA/tmp/istio/istio-${ISTIO_ERSION}/install/kubernetes/istio-demo-auth.yaml" "$SNAP_DATA/actions/istio/"
  run_with_sudo mv "$SNAP_DATA/tmp/istio/istio-${ISTIO_ERSION}/install/kubernetes/istio-demo.yaml" "$SNAP_DATA/actions/istio/"

  run_with_sudo rm -rf "$SNAP_DATA/tmp/istio"
fi
```

**Comment by gunofmoon** [comment]
On my os, curl not use “http_proxy” environment variable。touch /root/.curlrc, add line:
```
proxy=[PROXY_IP]:[PROXY_PORT]
```
