### ISSUE TITLE
Pod unable to reach itself through a service

### ISSUE THREAD

**Issue by sbrunk** [ubuntu/microk8s#858]
It seems that the networking configuration in microk8s doesn't allow a pod to reach itself through a service.

How to reproduce:

```bash
kubectl run my-nginx --image=nginx 
kubectl expose deploy my-nginx --port=80
kubectl exec -it deploy/my-nginx -- bash

root@my-nginx-948577f65-c9t5c:/#
apt update
apt install curl dnsutils
curl my-nginx # <-- hangs

nslookup my-nginx # DNS works
curl my-nginx-948577f65-c9t5c ## Using the pod name directly works
```

This causes issues i.e. when trying to run [presto](https://github.com/helm/charts/tree/master/stable/presto).

Seen on v1.15.6 on Ubuntu 19.10

Seems to be similar to https://github.com/kubernetes/minikube/issues/1568.

**Comment by ktsakalozos** [comment]
On 1.16 onwards we switch the flannel CNI would such an upgrade be an option for you? 

A temporary workaround for 1.15 is to do a:
```
sudo ip link set cbr0 promisc on
```

**Comment by sbrunk** [comment]
Your workaround did help for 1.15. I also did a test on 1.16 and it seems to work out of the box on top of flannel.

Thanks a lot for your help @ktsakalozos!
