### ISSUE TITLE
Windows and MacOS installer

### ISSUE THREAD

**Issue by ktsakalozos** [ubuntu/microk8s#861]
To improve the UX in non-Linux platforms we would like to provide an installer that would take care of the Multipass+MicroK8s installation and will also setup any platform native microk8s.& command hooks.

Further discussion should be don over this doc: https://docs.google.com/document/d/1A-Ujybw3kWysGjDFXRowImOHHyAM_0QIToZZCZWat-U/edit?usp=sharing

**Comment by balchua** [comment]
Is this planned to be running in wsl2?

**Comment by ktsakalozos** [comment]
> Is this planned to be running in wsl2?

Not at this stage. Have a look here  https://wsl.dev/wsl2-ermine-docker/  to see how to get MicroK8s running in wsl2.

**Comment by balchua** [comment]
Addressing this issue https://github.com/ubuntu/microk8s/issues/132

**Comment by joedborg** [comment]
A preview of this is now available https://github.com/ubuntu/homebrew-microk8s.  Feedback is warmly welcome, please open new issues in this issue tracker.

Many thanks.
