### ISSUE TITLE
How can I get k8s docker images details of microk8s for specified version?

### ISSUE THREAD

**Issue by BlueSky5300** [ubuntu/microk8s#866]
I want to install microk8s locally. But I can not download necessary k8s images for microk8s to use.

So I want to know version numbers of those images to inject into microk8s.

Could anyone give me a link or some information? Thanks.

**Comment by balchua** [comment]
Most if not all kubernetes control plane components are part of the snap package.  This means it is included when you do a `snap install microk8s --classic` command.  The only docker image that is required to have internet connection is the `pause` container `k8s.gcr.io/pause:3.1`.

If you are referring to the addons, they are located here. 
https://github.com/ubuntu/microk8s/tree/master/microk8s-resources/actions

If you want to download the snap and install it somewhere, maybe you can follow how this thread, where it explains how to get the snap manually. 
 https://forum.snapcraft.io/t/offline-snap-installers-and-possibility-to-update/275

**Comment by BlueSky5300** [comment]
Thanks for your help. I have installed microk8s 1.17.0 and I will try those addons.
