### ISSUE TITLE
How to change cni? I want to use macvlan or multus

### ISSUE THREAD

**Issue by markus7811** [ubuntu/microk8s#867]
Hi,

i am new to microk8s but think it is really good for running some iot workload or homeautomation and things like this. Therefor i need to use macvlan.

At the moment it is really hard to get an idea what i have to do to change the default cni (flannel) to something other, like multus (would be my favorit) or macvlan. Please consider to add some information what needs to be done to change the cni.

Thank you a lot.

**Comment by balchua** [comment]
Hi @markus7811 thank you for pointing out the lack of documentation on this front.  Apologies.

To get you started, cni binaries are usually stored in `$SNAP_DATA/bin`, in the case of cilium cni, it is actually in `$SNAP_DATA/opt/cni/bin`

On the cni configuration aspect, again it is stored in `$SNAP_DATA/args/cni-network/`

If you need to change kubelet's configuration, it is located in `$SNAP_DATA/args/kubelet`

If you need to change containerd configuration, you will need to change in `$SNAP_DATA/args/containerd-template.toml`.  please take note that you are modifying the template file and not the actual `containerd.toml`

`$SNAP_DATA` is often located in `/var/snap/microk8s/current` directory.

**Comment by balchua** [comment]
Since multus is now an addon on edge channel, closing the issue.
