### ISSUE TITLE
Zombie heapster process/artifact results in unresponsive cluster

### ISSUE THREAD

**Issue by respatialized** [ubuntu/microk8s#868]
*Overall problem*: microk8s is slow and unresponsive.

*Factors*: the system logs (viewed via `journalctl`) repeatedly give an error message about a volume associated with a pod that doesn't exist anymore when commands against the cluster are run.

`microk8s.daemon-kubelet[31097]: W1217 19:20:59.014411   31097 kubelet_getters.go:293] Path "/var/snap/microk8s/common/var/lib/kubelet/pods/196b096a-231d-46a2-8bcc-3484ba66597b/volumes" does not exist`

This error message persists when I try to reset the cluster using `microk8s.reset --destroy-storage`  and even when I use `snap remove microk8s` to reinstall microk8s - `journalctl` still shows this message cropping up.

Grepping for the the pod uuid system-wide reveals that it was a heapster pod, which `microk8s` shouldn't be looking for because I don't have the dashboard addon enabled. Looking for `heapster` in the cluster report at `/var/snap/microk8s/current/inspection-report/sys/ps` reveals the following:

`nobody   10309     1  0 Dec17 ?        00:00:00 /heapster --source=kubernetes.summary_api:'' --sink=influxdb:http://monitoring-influxdb:8086`

I assume that this is why the `microk8s` cluster is expecting a heapster pod, but I can't say for certain. Is this expected behavior? No other process in the `ps` logs is started by `nobody`. I've tried to manually `SIGKILL` the process via `pkill`, but it doesn't terminate the process.

I don't know how to create a reproducible example of this, because I have no idea where this mystery heapster process is coming from. Any assistance is much appreciated. More than happy to dig through other system logs, but I'd appreciate some direction as to where else I might look. Thanks!

The full inspection report is attached. 
[inspection-report-20191218_082151.tar.gz](https://github.com/ubuntu/microk8s/files/3979227/inspection-report-20191218_082151.tar.gz)

**Comment by balchua** [comment]
After you do a `snap remove microk8s` do you still have this directory?
`/var/snap/microk8s`?

**Comment by respatialized** [comment]
I forgot to mention that I manually cleared out the microk8s path after uninstalling it. It didn't seem to make a difference.

**Comment by balchua** [comment]
@respatialized when doing `snap remove microk8s` you dont have to manually delete the file system under `/var/snap/microk8s` it will automatically be removed.
Do you still see this phantom heapster?

**Comment by respatialized** [comment]
I'm not seeing this anymore, but I also have since moved what I was doing off of local microk8s and on to a dev cluster. Feel free to close this.

**Comment by balchua** [comment]
Thank you for the information.
