### ISSUE TITLE
Can't enable Prometheus via add-on

### ISSUE THREAD

**Issue by timwebster9** [ubuntu/microk8s#869]
When I try to enable the prometheus add-on I get this:
```
timw@io:~$ microk8s.enable prometheus
Nothing to do for prometheus
```
This is with k8s 1.17.0 and Ubuntu 19.10

[inspection-report-20191218_212432.tar.gz](https://github.com/ubuntu/microk8s/files/3980610/inspection-report-20191218_212432.tar.gz)

**Comment by balchua** [comment]
I can see that you are running on arm64 architecture.
Pometheus operator isnt included on arm.

To see what addons are available, do a `microk8s.status`.

**Comment by timwebster9** [comment]
OK, I believe you but there is nothing in that command output to indicate that it's not included:
```
timw@io:~$ microk8s.status
microk8s is running
addons:
cilium: disabled
dashboard: disabled
dns: enabled
fluentd: disabled
gpu: disabled
helm: disabled
ingress: disabled
istio: disabled
jaeger: disabled
juju: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: enabled
metrics-server: disabled
prometheus: disabled
rbac: disabled
registry: disabled
storage: enabled
```

**Comment by balchua** [comment]
Ooops. Spoke too soon. Sorry bout that.  I will create an issue regarding the usage of `microk8s.status` to identify what addons are available.

**Comment by balchua** [comment]
Related issue https://github.com/ubuntu/microk8s/issues/870

**Comment by balchua** [comment]
I am sorry @timwebster9 the command to see available addon is `microk8s.enable --help`
Will look like this
```
microk8s.enable --help
Usage: microk8s.enable ADDON...
Enable one or more ADDON included with microk8s
Example: microk8s.enable dns storage

Available addons:

  cilium
  dashboard
  dns
  fluentd
  gpu
  helm
  ingress
  istio
  jaeger
  juju
  knative
  kubeflow
  linkerd
  metallb
  metrics-server
  prometheus
  rbac
  registry
  storage
```
