### ISSUE TITLE
Microk8s v17 and 16 stable versions coredns pod running but not ready

### ISSUE THREAD

**Issue by Moeletji17** [ubuntu/microk8s#871]
Hi I'm a newbie to Microk8s and I have an issue with the starting up my cluster. When enabling the dns addon after starting the cluster, the coredns pod is running but is not ready, it cannot connect to the master nodes apiserver :

2019-12-19T12:57:46.287Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2019-12-19T12:57:56.287Z [INFO] plugin/ready: Still waiting on: "kubernetes"
2019-12-19T12:58:06.287Z [INFO] plugin/ready: Still waiting on: "kubernetes"
E1219 12:58:13.111802       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Get https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: i/o timeout
E1219 12:58:13.112827       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: i/o timeout
E1219 12:58:13.113912       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Get https://10.152.183.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: i/o timeout 

We're using iptables as the firewall on the Ubuntu 18.04.3 LTS.

Currently I cannot provide the inspection-report for my issue to be replicated. I've looked at all the recent issues and I've tried them to no success. If more information is requested I will try my best to provide it.

NB! Can I suggest that the documentation on the MicroK8s website provide more detail regarding troubleshooting issues such as these.

**Comment by balchua** [comment]
I guess you tried these...

` sudo iptables -P FORWARD ACCEPT` or this `sudo ufw allow in on cni0 && sudo ufw allow out on cni0`

**Comment by Moeletji17** [comment]
Yes, I added the rule to the iptables as given as a warning when running [microk8s.inspect].

I referred to it looking for some assistance and I removed the rules in the iptables. Then I restarted Microk8s but it didin't work. I'm not running on the Oracle Cloud.

I have attached a copy of the iptables.

[iptables.txt](https://github.com/ubuntu/microk8s/files/3987115/iptables.txt)

**Comment by wreed4** [comment]
I'm having this same issue.  I cannot use microk8s at all because I cannot seem to figure out how to get the dns pod running.
