### ISSUE TITLE
using docker local registry instead of local installation creates problems if the registry used is not docker.com

### ISSUE THREAD

**Issue by urubatan** [ubuntu/microk8s#873]
If I'm using ECR for example to store the docker images, the image names in my yaml deployments have the ECR namespace, so using the local private registry means I'll have to change the yaml files for local testing and for deployment.

this is a really bad approach.

if microk8s uses the local docker installation, it will just get the same images that are already tagged with the ECR namespace, or any other private server namespace that is already there.

**Comment by balchua** [comment]
Hi @urubatan 
Back in 1.13 microk8s was using docker.  But it led to multiple problems when another docker daemon is installed.

Microk8s went on to using containerd to avoid those issues.  The consequence is that the usual development usage of locally cached docker images is no longer available in microk8s when you build using docker.

Though there is still a way to get that image into microk8s' containerd.  But it will invole some few steps mainly.
You need to do `docker save` then `microk8s.ctr import`

Something like this.
```
docker save mynginx > myimage.tar
microk8s.ctr image import myimage.tar
```
More information here.
https://microk8s.io/docs/registry-images

**Comment by urubatan** [comment]
That didn't solve the problem with images tagged with AWS URI for example

The best solution I found up to now was to configure kubelet to use the
already installed docker daemon.

The provided dockerd coul also be a solution if someone decided to use that
implementation as the default machine docker...


Em qui, 19 de dez de 2019 20:25, balchua <notifications@github.com>
escreveu:

**Comment by balchua** [comment]
What version are you in? 
That's strange.  I've tried using the `microk8s.ctr import` successfully even if the image repo doesn't exist at all as long as i use `imagePullPolicy` to `IfNotPresent`.

You can try adding namespace to `microk8s.ctr` like this.  `microk8s.ctr -n k8s.io image import myimage.tar`

**Comment by urubatan** [comment]
Ctr import works, but the image name will not have the correct repository
URI, what makes you need to change the test and production yaml image name

Because in many situations you need to put the full image name/URI in the
deployment yaml

Em sex, 20 de dez de 2019 01:59, balchua <notifications@github.com>
escreveu:

**Comment by balchua** [comment]
Hmm. Image repository and tag is part of the manifest file inside the tar.  
Doing `microk8s.ctr import` doesn't change the repo name, as far as my experience goes.

**Comment by amouat** [comment]
I was just reading this issue as we have some similar issues. 

As @balchua says, you should be able to use `docker tag` to rename the image to the ECR remote name/URI, then do `docker save` and `ctr import`. It is a bit of a hack though.

**Comment by urubatan** [comment]
I made my life easier changing the configuration of microk8s to use my
local docker install 😅

Em qua, 8 de jan de 2020 07:29, Adrian Mouat <notifications@github.com>
escreveu:
