### ISSUE TITLE
microk8s.reset hangs when addons are enabled

### ISSUE THREAD

**Issue by balchua** [ubuntu/microk8s#877]
Sometimes when addons using CRDs or api-services, resetting the cluster hangs during namespace deletion.
Reset also does not properly cleanup addon other resources such as service accounts, clusterroles, etc..

**Comment by mayankshah1607** [comment]
Hi, I am not really sure if its the addons that's causing this problem. I tried disabling the addons and running `microk8s.reset` then. The command hangs after the namespace deletion. Any suggestions?

**Comment by balchua** [comment]
This usually happens when crds are still being used.  If somewhere you have crds used in a namespace, you must delete it first prior to deleting the namespace.

**Comment by balchua** [comment]
@mayankshah1607 thanks for the info.  I was thinking about this further, perhaps should move the `crd` deletion earlier.

https://github.com/ubuntu/microk8s/blob/dbc90b6332ee0d96d94ebeaab044b2815adfe01f/microk8s-resources/wrappers/microk8s-reset.wrapper#L54

Will try this one out. Thanks 👍

**Comment by ukd1** [comment]
I'm still seeing this as well, even after trying @balchua's suggestion.

**Comment by balchua** [comment]
@ukd1 `apiservices` also needs to be deleted before the namespace.  Otherwise it will be stuck in `Terminating` state.

`kubectl delete apiservices --all`. IIRC.
