### ISSUE TITLE
Raspberry Pi install instructions not working

### ISSUE THREAD

**Issue by jfmatth** [ubuntu/microk8s#880]
There are a few of us having issues getting MicroK8s to run on a Pi.

The instructions say to modify /boot/firmware/cmdline.txt when in fact, for myself and others, modifying /boot/firmware/nobtcmd.txt instead. Per ubuntu/microk8s#778

Hope this helps.

**Comment by ktsakalozos** [comment]
@jfmatth thank you for pointing this out. AFAIK the `nobtcmd.txt` is a new addition so some versions have `cmdline.txt`.

Just submitted a PR to update the docs https://github.com/canonical-web-and-design/microk8s.io/pull/198

**Comment by jfmatth** [comment]
> @jfmatth thank you for pointing this out. AFAIK the `nobtcmd.txt` is a new addition so some versions have `cmdline.txt`.
> 
> Just submitted a PR to update the docs [canonical-web-and-design/microk8s.io#198](https://github.com/canonical-web-and-design/microk8s.io/pull/198)

Also, there seems to be quite a difference between 18.04 and 19.03 versions of Ubuntu.  Right now, i've had no luck getting MicroK8ss to run successfully on 19.03
