### ISSUE TITLE
Cloud we set vpn proxy in microk8s to retrieve necessary images?

### ISSUE THREAD

**Issue by BlueSky5300** [ubuntu/microk8s#881]
Sometimes we want to retrieve docker images from internet, but the process may timeout.
Cloud we config vpn proxy in microk8s like docker desktop? Thanks.

**Comment by balchua** [comment]
How do you do it with docker desktop? Microk8s is using containerd which is also what docker is using underneath.  Perhaps docker desktop is doing something special.
Are you planning to run microk8s with windows or mac?  Sorry many questions.

**Comment by BlueSky5300** [comment]
I use windows. For docker desktop, I can set proxy to make sure pull docker images successfully like below screenshot. While I don't know how to do the same thing in microk8s.
![docker-desktop-proxy](https://user-images.githubusercontent.com/11501826/71541478-8ca8e900-2994-11ea-90b5-79cbd80e77e0.png)

**Comment by balchua** [comment]
You can try this one https://github.com/ubuntu/microk8s/issues/396#issuecomment-478253659

**Comment by BlueSky5300** [comment]
Thanks for your help. I will try to add proxy.
Here is another solution just for pulling images from k8s.gcr.io, hope it will help others.

Add below into hosts file.
```
172.217.197.82 k8s.gcr.io
```
