### ISSUE TITLE
DNS/Storage possible RBAC issue

### ISSUE THREAD

**Issue by andrei-dascalu** [ubuntu/microk8s#883]
I have a fresh Ubuntu Bionic install (Hetzner VM) and installed microk8s via snap
`snap install microk8s --classic --channel=1.16/stable`

Once it was ready I ran
`microk8s.enable rbac storage dns`

However, later when I run
`microk8s.kubectl get pods --all-namespaces`

All I see is this:
```
NAMESPACE     NAME                                    READY   STATUS             RESTARTS   AGE
kube-system   coredns-9b8997588-4jfxz                 0/1     Running            6          11m
kube-system   hostpath-provisioner-7b9cb5cdb4-546jz   0/1     CrashLoopBackOff   5          4m46s
```

As per coredns logs:
```
E1229 22:51:30.871661       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Endpoints: Get https://10.152.183.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: connect: no route to host
E1229 22:51:30.871661       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: Get https://10.152.183.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: connect: no route to host
E1229 22:51:30.871860       1 reflector.go:134] pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Service: Get https://10.152.183.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.152.183.1:443: connect: no route to host
[INFO] SIGTERM: Shutting down servers then terminating
```

At the same time, logs from storage pod:

```
F1229 22:51:55.127914       1 hostpath-provisioner.go:162] Error getting server version: Get https://10.152.183.1:443/version: dial tcp 10.152.183.1:443: connect: no route to host
```

I am not quite sure what to make of it, except that perhaps the rbac setup for dns isn't quite what it should be?

Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.
[inspection-report-20191229_234718.tar.gz](https://github.com/ubuntu/microk8s/files/4008654/inspection-report-20191229_234718.tar.gz)

**Comment by balchua** [comment]
Hi thanks for reporting this.  Did you get the chance to the recommendation in https://microk8s.io/docs/troubleshooting#common-issues regarding coredns and iptables settings?
Thanks
