### ISSUE TITLE
Another DNS issue!

### ISSUE THREAD

**Issue by lukos** [ubuntu/microk8s#890]
I have been running a microk8s cluster and it is up and running, and the services working, except that the containers cannot resolve DNS so any outgoing functionality doesn't work.

The host (Ubuntu 18.04) can resolve OK and the firewall has always been inactive on the host. Unfortunately, the image I am using for the containers does not have net-tools installed so the best I can try is `apt update` which shows the resolution error (no access to ping, nslookup etc).

When I `get pods`, I notice that the kubernetes-dashboard and hostpath-provisioner have been crashing forever (7000 restarts) and the coredns pod shows running but not ready, which would probably explain why the containers can't resolve DNS!

All the other problems I have seen are related to firewall problems and mine isn't running so is there anything else I can test? Thanks.

[inspection-report-20200103_154256.tar.gz](https://github.com/ubuntu/microk8s/files/4019760/inspection-report-20200103_154256.tar.gz)

**Comment by balchua** [comment]
Can you post the file `/var/snap/microk8s/current/certs/csr.conf`?  The kube-api-server is complaining about bad certificate.

**Comment by lukos** [comment]
I have changed the Common Name to example from the real one I am using.

```
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = "US"
ST = "Isles of Blessed"
L = "Arkadia"
O = acme
OU = dev
CN = office.example.co.uk

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
IP.1 = 127.0.0.1
IP.2 = 31.24.220.141
IP.3 = 192.168.0.87
IP.4 = 10.1.52.0

[ v3_ext ]
authorityKeyIdentifier=keyid,issuer:always
basicConstraints=CA:FALSE
keyUsage=keyEncipherment,dataEncipherment,digitalSignature
extendedKeyUsage=serverAuth,clientAuth
subjectAltName=@alt_names
```

**Comment by balchua** [comment]
My guess is that you don't have the service ip of the apiserver.
In the original `csr.conf.template` there is the definition of it as `IP.2 = 10.152.183.1`.
Want to give that a try?

**Comment by lukos** [comment]
Thanks. I added that but it doesn't seem to have fixed it after reboot. After modifying csr.conf.template, the contents of csr.conf are:

```
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = "US"
ST = "Isles of Blessed"
L = "Arkadia"
O = acme
OU = dev
CN = office.example.co.uk

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = kubernetes
DNS.2 = kubernetes.default
DNS.3 = kubernetes.default.svc
DNS.4 = kubernetes.default.svc.cluster
DNS.5 = kubernetes.default.svc.cluster.local
IP.1 = 127.0.0.1
IP.2 = 31.24.220.141
IP.3 = 10.152.183.1
IP.3 = 192.168.0.87
IP.4 = 10.1.52.0

[ v3_ext ]
authorityKeyIdentifier=keyid,issuer:always
basicConstraints=CA:FALSE
keyUsage=keyEncipherment,dataEncipherment,digitalSignature
extendedKeyUsage=serverAuth,clientAuth
subjectAltName=@alt_names
```

**Comment by balchua** [comment]
Hmm. You have a duplicate `IP.3` attribute.

**Comment by lukos** [comment]
Can I delete everything from csr.conf and let it get generated again?

**Comment by balchua** [comment]
The `csr.conf.template` is the basis of `csr.conf`.  maybe you can try grabbing the original `csr.conf.template` from here. https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/certs/csr.conf.template

**Comment by lukos** [comment]
I tried deleting the additional entries from csr.conf and then modified csr.conf.template by adding a blank line. This got pulled through to csr.conf, which implies that the template IPs are added and then the generator assumes that the next entry is IP 3 instead of counting the ones in conf.template. Is this a fault in the generator or is there somewhere else that I should be setting the number of IPs so it counts correctly?

I note that some code in utils.sh uses hostname to get the IPs and presumably checks if they are already added but I don't know bash well enough to work out where it is generating the IP number and therefore why it starts at 3.

`csr.conf.template`:
```
IP.1 = 127.0.0.1
IP.2 = 31.24.220.141
IP.3 = 10.152.183.1

#MOREIPS
```

`csr.conf`:
```
IP.1 = 127.0.0.1
IP.2 = 31.24.220.141
IP.3 = 10.152.183.1

IP.3 = 192.168.0.87
IP.4 = 10.1.52.0
```

**Comment by balchua** [comment]
Change `csr.conf.template` like this
```
IP.1 = 127.0.0.1
IP.2 = 10.152.183.1
#MOREIPS
31.24.220.141
192.168.0.87
10.1.52.0
```
Give it a try.

**Comment by lukos** [comment]
csr.conf is now:
```
IP.1 = 127.0.0.1
IP.2 = 10.152.183.1
IP.3 = 192.168.0.87
IP.4 = 10.1.52.0
31.24.220.141
192.168.0.87
10.1.52.0
```

But the error remains. I have added another tarball.

[inspection-report-20200107_125807.tar.gz](https://github.com/ubuntu/microk8s/files/4030744/inspection-report-20200107_125807.tar.gz)

**Comment by balchua** [comment]
Im so sorry, the only custom IP you want to add is `31.24.220.141` those others are auto discovered.
Try this.
```
IP.1 = 127.0.0.1
IP.2 = 10.152.183.1
#MOREIPS
IP.5 = 31.24.220.141
```

**Comment by lukos** [comment]
That's amazing, it works now. Thank you! Is there a document that you need me to edit or create on github regarding editing these files? I believe you couldn't originally edit the CSR but now you can so presumably the IP.3 etc. is a bug and we need to document a workaround (consisting of trying the above code and adjusting the numbers if it doesn't quote line up)?

**Comment by balchua** [comment]
That's great news!  
Regarding documentation, there is an ongoing discussion about where to add such information.
Would like to hear your thoughts around it.

https://github.com/ubuntu/microk8s/issues/421#issuecomment-571539943

**Comment by balchua** [comment]
The shell works like this:
1.  It is always assumed that `IP.1` and `IP.2` is fixed, i.e. `127.0.0.1` and `10.152.183.1`
2.  Then it will start to auto discover all the network interfaces and their IP addresses and add it starting from `IP.3`
3.  Then followed by your custom IP address that you want to add.  For example an external Virtual IP provided by some load balancer.
