### ISSUE TITLE
InvalidDiskCapacity, invalid capacity 0 on image filesystem

### ISSUE THREAD

**Issue by DanikRaikhlin** [ubuntu/microk8s#893]
[inspection-report-20200104_130923.tar.gz](https://github.com/ubuntu/microk8s/files/4021880/inspection-report-20200104_130923.tar.gz)

Node hanging in a NotReady state with constant InvalidDiskCapacity on a fresh instalation of Ubuntu 18.04. There is ~380gb of space available.

Tried installing snapd both as root and different user. Same counts for microk8s. 

Everytime installation goes fine, services looks to be running.

`
root@h2863847:~# microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
2020/01/04 13:09:21.341859 main.go:150: description of sign's "k" is lowercase: "naam van de te gebruiken sleutel, gebruik anders de standaardsleutel"
2020/01/04 13:09:21.415713 main.go:150: description of sign's "k" is lowercase: "naam van de te gebruiken sleutel, gebruik anders de standaardsleutel"
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1067/inspection-report-20200104_130923.tar.gz
`

**Comment by balchua** [comment]
I see that `InvalidDiskCapacity` too.  Im guessing it is because of the snap filesystem which is readonly.
I do find one thing though, the file `/var/snap/microk8s/current/args/flannel-template.conflist` doesn't have the `cniVersion`.
Can try to add it like this?
```
{
    "name": "microk8s-flannel-network",
    "cniVersion": "0.3.1",
    "plugins": [
```
I believe this attribute is a required attribute from 1.16.
After that restart microk8s.

**Comment by DanikRaikhlin** [comment]
@balchua Thanks for your reply.

I've tried your suggestions but with not effect. New report;

[inspection-report-20200104_143706.tar.gz](https://github.com/ubuntu/microk8s/files/4021956/inspection-report-20200104_143706.tar.gz)

**Comment by balchua** [comment]
Strange, it seems like it didn't create the cni network.
What is the output of `ip addr`?

**Comment by DanikRaikhlin** [comment]
root@h2863847:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/void
    inet 127.0.0.1/32 scope host venet0
       valid_lft forever preferred_lft forever
    inet 85.214.28.137/32 brd 85.214.28.137 scope global venet0:0
       valid_lft forever preferred_lft forever
    inet6 ::2/128 scope global
       valid_lft forever preferred_lft forever
3: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether 26:91:90:34:d0:94 brd ff:ff:ff:ff:ff:ff
    inet 10.1.53.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::2491:90ff:fe34:d094/64 scope link
       valid_lft forever preferred_lft forever

**Comment by balchua** [comment]
No `eth0` or those wifi interfaces?

**Comment by DanikRaikhlin** [comment]
Not sure, its running on a hosted vps.

**Comment by balchua** [comment]
Which cloud provider are you using?

**Comment by DanikRaikhlin** [comment]
Its hosted from Strato

**Comment by DanikRaikhlin** [comment]
Guess its a Strato issue on how they setup their VPS's. See this thread: https://github.com/rancher/k3s/issues/1236

I guess the system missing some parts that microk8s needs acces to, from deamon-kubelet journal.log:

jan 04 19:58:37 h2863847.stratoserver.net microk8s.daemon-kubelet[13295]: W0104 19:58:37.679087   13295 fs.go:438] Not collecting filesystem statistics because file "/proc/diskstats" was not found

jan 04 19:58:37 h2863847.stratoserver.net microk8s.daemon-kubelet[13295]: E0104 19:58:37.680361   13295 machine.go:288] failed to get cache information for node 0: open /sys/devices/system/cpu/cpu0/cache: no such file or directory

I've tried sudo apt-get install linux-image-$(uname -r) but with no effect.

**Comment by balchua** [comment]
Strato seems to be using openvz for virtualization and I don't think it is a real VM.  But im not familiar at all with openvz. 😁

**Comment by balchua** [comment]
@DanikRaikhlin i am going to close this one, as it seems to be a strato issue.

**Comment by muhanov** [comment]
I have the same issue on time4vps having a regular KVM, not OVZ

**Comment by balchua** [comment]
@muhanov if the vps is missing some directories as pointed out above, im not sure what can be done.
Feel free to create an issue.
