### ISSUE TITLE
Add kube-router addon

### ISSUE THREAD

**Issue by abh23** [ubuntu/microk8s#898]
The Kube-router is a turnkey solution for Kubernetes networking with aim to provide operational simplicity. Kube-router provides a cohesive yet lean and powerful alternative to several network components. It simplifies routing between pods in a distributed cluster. 

It can be used to set IPVS/LVS mode for service proxy or the use of direct routing across the nodes for pod networking etc. 

Although, flannel is provided as CNI for microk8s but having flexibility to choose kube-router will add more use-cases to developer's kubernetes environment. 

It will be great to enable it with a simple command: `microk8s.enable kube-router`

**Comment by shaun-forgie** [comment]
Would love to see kube-router supported in Microk8
