### ISSUE TITLE
RBAC fails if hostname has capital letters

### ISSUE THREAD

**Issue by jobh** [ubuntu/microk8s#902]
If microk8s is installed on a computer which has capital letters in the hostname, pods cannot be created after enabling rbac.

The reason seems to be that the hostname is normalized to lowercase by kubernetes, which fails rbac authorization checks when it is compared to the non-normalized hostname.

Symptoms include failure registering the node, failing to mount secrets, etc. I didn't keep a record of the different failures, but this is an example (note that the capitalization differs between the lease and the user):
```
Jan  9 09:46:05 my-Precision-5540 microk8s.daemon-kubelet[6158]: E0109 09:46:05.170054    6158 controller.go:177] failed to update node lease, error: leases.coordination.k8s.io "my-precision-5540" is forbidden: User "system:node:my-Precision-5540" cannot update resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease": can only access node lease with the same name as the requesting node
```

After changing the computer's hostname to be all-lowercase, everything worked perfectly.

**Comment by jobh** [comment]
Here's the error message with wrapping/indentation, to make it easier to read:

```
Jan  9 09:46:05 my-Precision-5540 microk8s.daemon-kubelet[6158]:
  E0109 09:46:05.170054 6158 controller.go:177]
    failed to update node lease, error:
      leases.coordination.k8s.io "my-precision-5540" is forbidden:
          User "system:node:my-Precision-5540" cannot update resource "leases" in API group  "coordination.k8s.io" in the namespace "kube-node-lease":
              can only access node lease with the same name as the requesting node
```

**Comment by balchua** [comment]
Can you check the content of `/var/snap/microk8s/credentials/known_tokens.csv` and see if the hostname there has the capital letter?

**Comment by jobh** [comment]
I'm afraid I don't have that file anymore, after the hostname change/reinstall. And it is not part of the inspection report tarball I believe?

**Comment by balchua** [comment]
Unfortunately no.

**Comment by jobh** [comment]
I suspect that #729 might be a duplicate of this issue, if so the reporter there might have a live failing system.

**Comment by balchua** [comment]
@jobh thank you very much for providing this valuable info.
