### ISSUE TITLE
[coredns] upstream dns should be configurable

### ISSUE THREAD

**Issue by grebennikov** [ubuntu/microk8s#905]
I run microk8s in the restricted environment and google dns is unreachable.
Due to this reason I can't resolve any remote addresses as the default resolvers currently and by default point to 8.8.4.4/8.8.8.8
https://microk8s.io/docs/addon-dns describes how to change the value temporary, but the settings revert if I enable/disable plugins.
There should be an option to set up upstream dns permanently.

**Comment by ktsakalozos** [comment]
@balchua this is also a good example showing we need a way to say "add on X is already enabled and not try to reenable it". https://github.com/ubuntu/microk8s/issues/900#issuecomment-573232015

**Comment by balchua** [comment]
@ktsakalozos yes exactly what i meant.  We should make them idempotent.
