### ISSUE TITLE
multipass launch failed: Downloaded image hash does not match on Mac

### ISSUE THREAD

**Issue by tae9yu** [ubuntu/microk8s#909]
VM launch failed with "launch failed: Downloaded image hash does not match"

```
% multipass -v launch --name microk8s-vm --mem 4G --disk 40G
launch failed: Downloaded image hash does not match

% uname -a
Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

% multipass version
multipass  1.0.0+mac
multipassd 1.0.0+mac
```

**Comment by ktsakalozos** [comment]
This seems like multipass specific issue. Perhaps @Saviq or @townsend2010 can help. @tae9yu, you may also want to open an issue at https://discourse.ubuntu.com/c/multipass or https://github.com/canonical/multipass/issues .

**Comment by tae9yu** [comment]
I opened this issue at https://github.com/canonical/multipass/issues/1299.

**Comment by balchua** [comment]
Will be closing this issue, being tracked in multipass https://github.com/canonical/multipass/issues/1299
