### ISSUE TITLE
Change ports where scheduler and manager are listening

### ISSUE THREAD

**Issue by jeusdi** [ubuntu/microk8s#911]
[inspection-report-20200113_203422.tar.gz](https://github.com/ubuntu/microk8s/files/4055418/inspection-report-20200113_203422.tar.gz)

Is there any way to change port where scheduler and controller-manager components are listening?

I mean, currently thuey are listening to 10252 and 10251.

Is there any way to change that?

**Comment by strigona-worksight** [comment]
You should be able to adjust the parameters in
`/var/snap/microk8s/current/args/kube-scheduler`

According to the docs here: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
