### ISSUE TITLE
Question: how to disable microk8s startup at boot time?

### ISSUE THREAD

**Issue by spencergibb** [ubuntu/microk8s#913]
I want to start it only when I need it.

Thanks for a great tool!

**Comment by balchua** [comment]
When you do a `microk8s.stop` it is actually disabling the services.  Although there is a bug when the snap refreshes it starts the services.  Checkout the comment here. https://github.com/ubuntu/microk8s/issues/474#issuecomment-493898948

**Comment by spencergibb** [comment]
Ah, so `microk8s.stop` disables the services thus persisting across a reboot. Thanks!

**Comment by wapmorgan** [comment]
So, you need may be to do `snap stop --disable microk8s`
