### ISSUE TITLE
Jenkins init container cannot resolve dns

### ISSUE THREAD

**Issue by saad352** [ubuntu/microk8s#915]
- OS: CentOS
- microk8s plugin dns, dashboard, ingress are enabled
- If I ping google.com from inside of dnsutils pod, dns gets resolved
- Init container logs:
```
Creating initial locks...
Analyzing war /usr/share/jenkins/jenkins.war...
Registering preinstalled plugins...
Downloading plugins...
Downloading plugin: git from https://updates.jenkins.io/download/plugins/git/4.0.0/git.hpi
Downloading plugin: kubernetes from https://updates.jenkins.io/download/plugins/kubernetes/1.21.2/kubernetes.hpi
Downloading plugin: workflow-aggregator from https://updates.jenkins.io/download/plugins/workflow-aggregator/2.6/workflow-aggregator.hpi
Downloading plugin: workflow-job from https://updates.jenkins.io/download/plugins/workflow-job/2.36/workflow-job.hpi
Downloading plugin: credentials-binding from https://updates.jenkins.io/download/plugins/credentials-binding/1.20/credentials-binding.hpi
cp: overwrite '/var/jenkins_home/config.xml'? cp: overwrite '/var/jenkins_home/jenkins.CLI.xml'? cp: overwrite '/var/jenkins_home/jenkins.model.JenkinsLocationConfiguration.xml'? curl: (28) Resolving timed out after 20708 milliseconds
curl: (28) Resolving timed out after 20710 milliseconds
curl: (28) Resolving timed out after 20713 milliseconds
curl: (28) Resolving timed out after 20717 milliseconds
curl: (28) Resolving timed out after 20719 milliseco01:11:20 Failure (28) Retrying in 1 seconds...
nds
01:11:20 Failure (28) Retrying in 1 seconds...
01:11:20 Failure (28) Retrying in 1 seconds...
01:11:20 Failure (28) Retrying in 1 seconds...
01:11:20 Failure (28) Retrying in 1 seconds...
```

```
[centos@master ~]$ microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

```

 `microk8s.inspect` generated tarball
[inspection-report-20200117_200012.tar.gz](https://github.com/ubuntu/microk8s/files/4081113/inspection-report-20200117_200012.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

**Comment by balchua** [comment]
Are you behind a proxy?  
Can u also ping the jenkins update site? `updates.jenkins.io`?

**Comment by saad352** [comment]
No I am not behind any proxy.
And No I can not ping ```updates.jenkins.io``` becuase It is blocking ping requests but it does get resolved showing it's IP.

```/ # ping updates.jenkins.io
PING updates.jenkins.io (52.202.51.185): 56 data bytes
^C
```

**Comment by balchua** [comment]
So it seems to be resolving jenkins' url.  Could it be just jenkins site unable to serve the request?

**Comment by saad352** [comment]
I am not sure about that. Additionally after installing Jenkins with helm if I check endpoints they are also not being created for Jenkins. If this helps in some way.

**Comment by balchua** [comment]
Hi @saad352 is it possible to paste the log of the `initContainer`?
I can't seem to find what could be wrong.
Thanks.

**Comment by saad352** [comment]
The ```initContatiner``` logs are mentioned above. If you mean to say log of Jenkins pod it just says ```Pod Initializing```

**Comment by balchua** [comment]
Thanks.  I saw the logs above, i thought it could have mentioned which plugin can't be installed.

**Comment by saad352** [comment]
No it just gets in loop of restarting Pod and then these logs and then again restarting Pod.
