### ISSUE TITLE
microk8s storage explained and migration

### ISSUE THREAD

**Issue by philthynz** [ubuntu/microk8s#918]
I want to move from LXD to microk8s. In the past I would simply migrate the whole LXC container when moving or playing around with it.

Does microk8s only support "hostpath"? Can we use "local" to make it more portable? I haven't seen much documentation around the micok8s storage functionality.

Also, can the local storage be outside of snap so we can migrate it to another server? Not sure how the storage migration would work.

**Comment by strigona-worksight** [comment]
Out of the box it only supports "hostpath" but it can be configured to use other storage platforms. I believe someone has got it hooked up with rook/ceph, but I don't have any details on that.

**Comment by philthynz** [comment]
And how would we migrate the hostpath storage?

**Comment by ktsakalozos** [comment]
Hi @philthynz 

If you `microk8s.enable storage` the data are stored under `/var/snap/microk8s/common/default-storage`.

As MicroK8s is a distribution of upstream Kubernetes so you can configure it with any storage solution described in the Kubernetes docs [1].

As you can see storage is something Kubernetes itself does not deal with. It offers ways to hook your storage solution to a kubernetes cluster but storage management is out of the scope of the Kubernetes project.

I do not think storage migration across Kubernetes clusters is possible but I haven't really looked into this. Is this kind of migration what you are asking for?

[1] https://kubernetes.io/docs/concepts/storage/

**Comment by philthynz** [comment]
Thanks @ktsakalozos that really helps.
