### ISSUE TITLE
Enable GPU on multi-node cluster

### ISSUE THREAD

**Issue by vakker** [ubuntu/microk8s#920]
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20200121_142427.tar.gz](https://github.com/ubuntu/microk8s/files/4091519/inspection-report-20200121_142427.tar.gz)

I set up microk8s according to the [quick start](https://microk8s.io/docs/) guide and added another node according to [this](https://microk8s.io/docs/clustering).
I'm trying to enable GPU support as the node that I added has GPUs.
When I run `microk8s.enable gpu` on the master I get: 
```
Enabling NVIDIA GPU
Aborting: NVIDIA kernel module not loaded.
Please ensure you have CUDA capable hardware and the NVIDIA drivers installed.
Failed to enable gpu
```

But then when I run `microk8s.enable gpu` on the node I get: 
```
This MicroK8s deployment is acting as a node in a cluster. Please use the microk8s.enable on the master.
```

So what's the correct way to do this?
Thanks

**Comment by ktsakalozos** [comment]
I am afraid the current version of the gpu addon assumes a uniform cluster. You are right this might not always be the case. 

You will need to perform the steps of the gpu addon manually. Have a look at https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.gpu.sh

On the node where the GPUs are tell containerd to be reconfigured so that it uses the nvidia runtime:
```
sudo mkdir -p /var/snap/microk8s/var/lock
sudo touch /var/snap/microk8s/var/lock/gpu
sudo systemctl restart snap.microk8s.daemon-containerd
```

From the master setup the daemonset with:
```
microk8s.kubectl apply -f https://raw.githubusercontent.com/ubuntu/microk8s/master/microk8s-resources/actions/gpu.yaml
```

I haven't tried such configuration. This is how I believe it should work.

**Comment by vakker** [comment]
Thanks, I might test this in the future, but atm I'll just fall back to my previous kubeadm based setup.

**Comment by croesuslab** [comment]
@ktsakalozos, I tried your suggestion, but it doesn't appear to work. It doesn't fail with any error message, but the cluster does not appear to see the gpus
```
kubectl describe nodes  |  tr -d '\000' | sed -n -e '/^Name/,/Roles/p' -e '/^Capacity/,/Allocatable/p' -e '/^Allocated resources/,/Events/p'  | grep -e Name  -e  nvidia.com  | perl -pe 's/\n//'  |  perl -pe 's/Name:/\n/g' | sed 's/nvidia.com\/gpu:\?//g'  | sed '1s/^/Node Available(GPUs)  Used(GPUs)/' | sed 's/$/ 0 0 0/'  | awk '{print $1, $2, $3}'  | column -t
```

Output:
```
Node         Available(GPUs)  Used(GPUs)
node1                   0                0
node1                   0                0
```

**Comment by croesuslab** [comment]
I figure out the solution: you need to use the enable command on the nodes, but **before** joining them to the master.
```
microk8s enable gpu
```
Then, you run this command on the master:
```
microk8s.kubectl apply -f https://raw.githubusercontent.com/ubuntu/microk8s/master/microk8s-resources/actions/gpu.yaml
```
The gpus will be visible in the nodes description.

**Comment by foxel** [comment]
@croesuslab how do you see gpu is available?

**Comment by croesuslab** [comment]
They appear in the nodes description as "nvidia.com gpu"

You can use this command to get a better formatted view:

```
kubectl describe nodes  |  tr -d '\000' | sed -n -e '/^Name/,/Roles/p' -e '/^Capacity/,/Allocatable/p' -e '/^Allocated resources/,/Events/p'  | grep -e Name  -e  nvidia.com  | perl -pe 's/\n//'  |  perl -pe 's/Name:/\n/g' | sed 's/nvidia.com\/gpu:\?//g'  | sed '1s/^/Node Available(GPUs)  Used(GPUs)/' | sed 's/$/ 0 0 0/'  | awk '{print $1, $2, $3}'  | column -t
```

**Comment by jli113** [comment]
> https://raw.githubusercontent.com/ubuntu/microk8s/master/microk8s-resources/actions/gpu.yaml

This file is 404 now.
