### ISSUE TITLE
Unable to install stable microk8s on raspberry pi 4

### ISSUE THREAD

**Issue by smetal1** [ubuntu/microk8s#921]
I am unable to install mircok8s on raspberry pi 4.

ERR:
 snap "microk8s" is not available on 1.16/stable for this architecture
       (armhf)

**Comment by ktsakalozos** [comment]
MicroK8s is available for arm64, I am sure rpi4 are arm64. Is it possible this is not a rpi4 or perhaps the distribution you installed marks the processor architecture as armhf?

**Comment by trulede** [comment]
I tried this with Ubuntu and it worked. There is a process to follow : https://ubuntu.com/blog/single-node-kubernetes-on-raspberry-pi-microk8s-ubuntu
