### ISSUE TITLE
Registry addon config

### ISSUE THREAD

**Issue by nevyan** [ubuntu/microk8s#926]
Hello, since dealing with microk8s for some time now, I would like to ask if the registry can be configured to use less than the default 20GB space. 
In other words, is it known the location of the predefined .yaml manifest files that start the addons?

**Comment by ktsakalozos** [comment]
Hi @nevyan 

The 20GB comes from here: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/registry.yaml#L18

It would have been great if the 20GB was configurable during the enable command (eg `microk8s.enable registry:storage=100GB`). Adding arguments is relatively simple. Have a look at https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.metallb.sh where the IP range of metallb addresses is provided as an argument and makes its way to the yaml manifest.

**Comment by cyril-corbon** [comment]
Hello,
I would like to do this issue and add this feature as my first open source PR
Hope it will help everyone
