### ISSUE TITLE
microk8s.etcd do not start - 8.8.4.4:53: no such host

### ISSUE THREAD

**Issue by LuffyyyffuL** [ubuntu/microk8s#930]
Hello,

My server : 

OS : Ubuntu 19.10 x64
I have "Pi-hole" installed
I have "ufw" enable

I have installed microk8s, and when i start and i run microk8s status, microk8s.etcd is not start.

Log "journalctl -u snap.microk8s.daemon-etcd" : 

`janv. 23 20:59:58 monkeydryzen etcd[6266]: etcd Version: 3.3.4
janv. 23 20:59:58 monkeydryzen etcd[6266]: Git SHA: fdde8705f
janv. 23 20:59:58 monkeydryzen etcd[6266]: Go Version: go1.9.5
janv. 23 20:59:58 monkeydryzen etcd[6266]: Go OS/Arch: linux/amd64
janv. 23 20:59:58 monkeydryzen etcd[6266]: setting maximum number of CPUs to 12, total number of available CPUs is 12
janv. 23 20:59:58 monkeydryzen etcd[6266]: listen tcp: lookup localhost on 8.8.4.4:53: no such host`

I have run : 

`sudo ufw allow in on cni0 && sudo ufw allow out on cni0`

But the problem is always here.

Question : Pi-hole use FTL, can this be a problem ?

Thank you very munch

**Comment by balchua** [comment]
Can you check your `/etc/hosts` file?  Its looking up `localhost` through the upstream dns.

**Comment by LuffyyyffuL** [comment]
Thank you for your reply, i have that in my "hosts" file : 

`127.0.0.1       serveur_name
127.0.1.1       serveur_name
192.168.0.11    serveur_name`

**Comment by balchua** [comment]
@LuffyyyffuL is it working now? Thanks.

**Comment by LuffyyyffuL** [comment]
Yes
