### ISSUE TITLE
ClusterIP service reachable from HOST?!

### ISSUE THREAD

**Issue by felipecruz91** [ubuntu/microk8s#936]
Host: Ubuntu 18.04 LTS

`microk8s.kubectl version --short`
Client Version: v1.14.10
Server Version: v1.14.10

Reproduce steps:

1. Run an nginx pod and expose it with a `ClusterIP` service.
`kubectl run nginx --image=nginx --restart=Never --port=80 --expose`

2. List services with `kubectl get svc`.

|NAME         |TYPE        |CLUSTER-IP       |EXTERNAL-IP   |PORT(S)   |AGE|
--------------|-----------|--------------|------------|-------------|------------|
|kubernetes   |ClusterIP   |10.152.183.1     |<none>        |443/TCP   |2m15s|
|nginx        |ClusterIP   |10.152.183.221   |<none>        |80/TCP    |8s|

3. Do a curl to the nginx service:
`curl 10.152.183.221`

**Expected** behaviour: 
The nginx pod should not be able to be accessed from the host through the service as the service is of type `ClusterIP`. This means that only pods running within the Cluster could reach the nginx pod through the ClusterIP service.

`curl: (7) Failed to connect to 10.98.57.229 port 80: Connection refused`

**Actual** behaviour:

The nginx pod serves the index.html file

```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
.....
</body>
</html>
```

--- 
How is then possible that from my host I am able to reach the nginx pod through the `ClusterIP` service?

> Note: I have tried replicating the same steps in Windows with Docker for Desktop and in this case the nginx pod is not reachable from the host machine which is the expected and correct behavior.

**Comment by balchua** [comment]
IIRC docker for desktop launches a vm.
Perhaps if you get into docker for desktop vm, you might also access the clusterip.
Just guessing.

**Comment by felipecruz91** [comment]
`ClusterIP`: Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from **within** the cluster.

@balchua Does it mean that when using Microk8s the host machine belongs to the same network as the K8s cluster, in contrast with Docker for Desktop where the host machine lives outside the K8s cluster network?

**Comment by balchua** [comment]
As far as i know, the host will have a network interface which it can access to. Similar to a docker overlay ip.
While on a docker for desktop the host (i.e. your windows machine) does not have the network interface, while the vm (hyperv) has it.
i think i also tried this on a non microk8s host sometime back.  Will probably have to try this again. 😁

**Comment by felipecruz91** [comment]
@balchua  I would like to find some documentation in the Microk8s website that explains this unexpected behaviour to be honest...

**Comment by balchua** [comment]
@ktsakalozos can surely explain it better than me.

**Comment by ktsakalozos** [comment]
> `ClusterIP`: Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from **within** the cluster.

MicroK8s turns your host into a Kubernetes node. Your host *is* the node. If you look at the interfaces available (`ifconfig`) you should see the interface with the ClusterIPs.

On windows and mac a Linux VM is used to host Kubernetes so your node is a VM whose network is not normally exposed to the host.

**Comment by felipecruz91** [comment]
Thank you @ktsakalozos for the clarification!
