### ISSUE TITLE
Can't use localhost:25000 for the cluster agent.py API

### ISSUE THREAD

**Issue by giorgos-apo** [ubuntu/microk8s#937]
Hello, 
I 've been trying to user the `agent.py` API in order to get the status of the cluster.
However `localhost:25000/cluster/api/v1.0/status` doesn't work. In fact, `localhost:25000` doesn't work at all. I have attached the inspection tarball.
Thanks.
[inspection-report-20200126_213715.zip](https://github.com/ubuntu/microk8s/files/4114243/inspection-report-20200126_213715.zip)

**Comment by balchua** [comment]
@giorgos-apo is there by any chance that this cluster was upgraded from previous version like 1.15?  Its seems strange that i dont see the `cluster-agent` file.

**Comment by giorgos-apo** [comment]
@balchua hello! Actually, I have reinstalled microk8s using snap. Then, I ran `microk8s.start` and tried to make a POST request using Postman. However, `localhost:25000/cluster/api/v1.0/status` doesn't work. The  problem is that I can't "see" the port 25000 in localhost, so whatever request I make to the agent, it fails.

**Comment by balchua** [comment]
Can you check if you have this file
`/var/snap/microk8s/current/args/cluster-agent?
When you "reinstall" microk8s im guessing you did a `snap remove microk8s`

**Comment by ktsakalozos** [comment]
In the logs of the cluster agent I see it is running on port 8080. Any idea why that may be?

**Comment by giorgos-apo** [comment]
@ktsakalozos hi! no I don't have any idea actually.

@balchua hi! no I did `sudo snap refresh microk8s`

**Comment by balchua** [comment]
@giorgos-apo i see, i think there is a bug in the `configure` script.  It didn't consider copying the `cluster-agent` configuration to `$SNAP_DATA/args`, hence the agent started using the default port which is `8080`.

Would it be possible for you to create a file in `/var/snap/microk8s/current/cluster-agent` with this content?
```
--bind 0.0.0.0:25000
--keyfile "${SNAP_DATA}/certs/server.key"
--certfile "${SNAP_DATA}/certs/server.crt"
```
And then do a `microk8s.stop` and `microk8s.start`.

This should pickup the config and start the agent using port `25000`.

**Comment by ktsakalozos** [comment]
> Would it be possible for you to create a file in `/var/snap/microk8s/current/cluster-agent` with this content?

That should be `/var/snap/microk8s/current/args/cluster-agent`. Better yet, do a `sudo snap remove microk8s` and reinstall.

**Comment by giorgos-apo** [comment]
Hello @ktsakalozos and @balchua  I did what you suggested and now I am able to see the cluster-agent file. However, I am still not able to run anything on `localhost:25000`. For example `localhost:25000/cluster/api/v1.0/status` doesn't work. I attatch the tarball again.
[inspection-report.zip](https://github.com/ubuntu/microk8s/files/4140724/inspection-report.zip)

**Comment by ktsakalozos** [comment]
There is no status endpoint in https://github.com/ubuntu/microk8s/blob/master/scripts/cluster/agent.py . You will have to implement that yourself.

**Comment by giorgos-apo** [comment]
@ktsakalozos it doesn't really matter actually because calling `localhost:25000/cluster/api/v1.0/configure` doesn't work either, even when I send a json as body for the post request.

**Comment by balchua** [comment]
@giorgos-apo what error do you get when you call the configure endpoint?

**Comment by giorgos-apo** [comment]
@balchua I get a **Couldn't get any response** error. I am wondering though, in case I have microk8s running, is there any request I can do in order to know if cluster agent is running properly?

**Comment by balchua** [comment]
@giorgos-apo no status code is returned too? Thats strange.

**Comment by giorgos-apo** [comment]
@balchua I am actually making the call using postman and the response I get looks like that:

> Could not get any response

There was an error connecting to `localhost:25000/cluster/api/v1.0/configure`

Why this might have happened:

The server couldn't send a response:Ensure that the backend is working properly

Self-signed SSL certificates are being blocked:Fix this by turning off 'SSL certificate verification' in Settings > General

Proxy configured incorrectly Ensure that proxy is configured correctly in Settings > Proxy

Request timeout:Change request timeout in Settings > General

**Comment by balchua** [comment]
Thanks, so its not hitting the agent.  Postman is not allowing the handshake because its self signed cert.
You need to turn off ssl cert verification in postman.

**Comment by giorgos-apo** [comment]
@balchua thanks but unfortunately I get the same error. 
I am providing a screenshot:
![Screenshot from 2020-02-04 20-17-00](https://user-images.githubusercontent.com/8779638/73773813-896efd00-478b-11ea-862d-43264d05d107.png)
Below you can see my general settings:
![Screenshot from 2020-02-04 20-21-04](https://user-images.githubusercontent.com/8779638/73774124-2336aa00-478c-11ea-8029-09013f63e269.png)
And below you can see my proxy settings:
![Screenshot from 2020-02-04 20-21-08](https://user-images.githubusercontent.com/8779638/73774203-3ea1b500-478c-11ea-9571-2c20da87595a.png)

**Comment by balchua** [comment]
@giorgos-apo what if you add a json body? 

Lets try restarting `kube-proxy`.  And make sure we point to the master node `https://masterip:25000`

With the content-type as `application/json`
 ```
    {
      "callback": "xyztoken"
      "service":
      [
        {
          "name": "kube-proxy",
          "restart": True
        }
      ]
    }
```

**Comment by giorgos-apo** [comment]
@balchua hello again! so here is the outcome:
![Screenshot from 2020-02-05 20-14-01](https://user-images.githubusercontent.com/8779638/73870226-5e041500-4854-11ea-8305-509963f5c861.png)
If I don't use `https://` then it responds with the previous error (Could not get any response)

**Comment by balchua** [comment]
@giorgos-apo so this is looking good, i mean it is now hitting the cluster agent `configure` endpoint.
If you follow through the code, i guess it threw that error due to the wrong callback token.
Try creating a file under `/var/snap/microk8s/current/credentials/callback-token.txt` and add a row `xyztoken`.
Then hit the `configure` endpoint again with the same json body.

**Comment by giorgos-apo** [comment]
@balchua Unfortunately after creating the file and changed its ownership and permission to `root:microk8s` and `644`, I still get the same error. If I change the callback on the json request (for example if I put `"callback": "sjsjxy"`) then I receive a `invalid token`. So I feel like I am close...

**Comment by giorgos-apo** [comment]
@ktsakalozos @balchua hello both! I have been trying to run this:
![Screenshot from 2020-02-12 21-44-30](https://user-images.githubusercontent.com/8779638/74371137-f82e0500-4de0-11ea-830c-891e4b06977c.png)
As you can see I get an error 500 in the request.
So after viewing the logs I got that back:
``` microk8s.daemon-cluster-agent[1089]: Traceback (most recent call last):
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
 microk8s.daemon-cluster-agent[1089]:     response = self.full_dispatch_request()
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
 microk8s.daemon-cluster-agent[1089]:     rv = self.handle_user_exception(e)
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
 microk8s.daemon-cluster-agent[1089]:     reraise(exc_type, exc_value, tb)
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
 microk8s.daemon-cluster-agent[1089]:     raise value
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
 microk8s.daemon-cluster-agent[1089]:     rv = self.dispatch_request()
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
 microk8s.daemon-cluster-agent[1089]:     return self.view_functions[rule.endpoint](**req.view_args)
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/scripts/cluster/agent.py", line 412, in configure
 microk8s.daemon-cluster-agent[1089]:     subprocess.check_call("{}/microk8s-disable.wrapper {}".format(snap_path, addon["name"]).split())
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/usr/lib/python3.5/subprocess.py", line 576, in check_call
microk8s.daemon-cluster-agent[1089]:     retcode = call(*popenargs, **kwargs)
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/usr/lib/python3.5/subprocess.py", line 557, in call
 microk8s.daemon-cluster-agent[1089]:     with Popen(*popenargs, **kwargs) as p:
 microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/usr/lib/python3.5/subprocess.py", line 947, in __init__
microk8s.daemon-cluster-agent[1089]:     restore_signals, start_new_session)
microk8s.daemon-cluster-agent[1089]:   File "/snap/microk8s/1173/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
 microk8s.daemon-cluster-agent[1089]:     raise child_exception_type(errno_num, err_msg)
 microk8s.daemon-cluster-agent[1089]: FileNotFoundError: [Errno 2] No such file or directory: '/var/snap/microk8s/1173/microk8s-disable.wrapper'
```
I believe the last line says everything... But could anyone explain me what that is? Why doesn't it exist? and what does it do if it exists?

**Comment by ktsakalozos** [comment]
@giorgos-apo you found a bug in our code.

In https://github.com/ubuntu/microk8s/blob/master/scripts/cluster/agent.py#L19 `snap_path` should be `os.environ.get('SNAP')`. If you follow the code of the configure you will see it tries to find the `microk8s-enable.wrapper` under  `snap_path` and that should be where the `$SNAP` variable point.

Would you be interested in a PR to fix this? Thank you.

**Comment by giorgos-apo** [comment]
@ktsakalozos sure I will do that the sooner possible! Thanks for the help anyway!

**Comment by giorgos-apo** [comment]
@ktsakalozos @balchua Hello both!  I am still struggling with this issue unfortunately. 
I have been executing the following, having gpu enabled:
![image](https://user-images.githubusercontent.com/8779638/75181150-4f6b9800-5746-11ea-9a07-34a3d0f45009.png)
However, when I see the logs using `journalctl -fu snap.microk8s.daemon-cluster-agent` command, I face the following issue:
```
[2020-02-24 20:39:41 +0200] [1720] [CRITICAL] WORKER TIMEOUT (pid:4016)
[2020-02-24 20:39:41 +0200] [4016] [INFO] Worker exiting (pid: 4016)
[1172]: gpu
[1172]: Disabling gpu
[1172]: [2020-02-24 20:39:41 +0200] [15920] [INFO] Booting worker with pid: 15920
```
I am monitoring all namespaces using `watch -n 1 microk8s.kubectl get all --all-namespaces` and unfortunately nothing changes.

Any idea please?

**Comment by balchua** [comment]
@giorgos-apo if you run `microk8s.enable gpu` from command line is it going through?  Or you are seeing the same error?

**Comment by giorgos-apo** [comment]
@balchua I can run and execute anything from the command line. BUT, when I run `microk8s.enable gpu` it asks for sudo password. So, I was thinking that maybe this is the issue with the agent.

**Comment by balchua** [comment]
Oh you may want to add the user into the microk8s group.  If you run `microk8s.status` it should suggest you to add your user to microk8s group.

**Comment by giorgos-apo** [comment]
@balchua Unfortunately nothing changed. And the command `microk8s.status` doesn't suggest anything.

**Comment by balchua** [comment]
Can try something simpler like enabling dns?

**Comment by giorgos-apo** [comment]
@balchua same issue unfortunately. It says gpu enabled and then request
timeout

**Comment by balchua** [comment]
@giorgos-apo there are some addons that require sudo because it downloads binaries and keeps into directories that are owned by root.
What if you install and start microk8s as root?

**Comment by giorgos-apo** [comment]
@balchua Hello,
1. I  have reinstalled microk8s using `sudo snap install microk8s --classic --edge`.
2. I have created a file in the credentials directory called `callback-token.txt` with the content `mytoken`.
3. I have `sudo chown root:microk8s callback-token.txt`
4. I have `sudo chmod 660 callback-token.txt`
5. I have `sudo microk8s.start`
6. I have sent the following request:
![Screenshot from 2020-03-01 12-05-45](https://user-images.githubusercontent.com/8779638/75623679-1c495e80-5bb5-11ea-80a6-f9182d4d069f.png)
7. I have received the following (`microk8s.kubectl get all --all-namespaces` on top and `journalctl -fu snap.microk8s.daemon-cluster-agent` on bottom):
![Screenshot from 2020-03-01 12-07-57](https://user-images.githubusercontent.com/8779638/75623705-7ba76e80-5bb5-11ea-9335-5edea8094db0.png)

**Comment by balchua** [comment]
Thats great!!

**Comment by giorgos-apo** [comment]
@balchua in what way? I mean it didn't work.

**Comment by balchua** [comment]
I didn't try gpu so i thought that it did enable gpu because it showed something in the log.
Again, when u execute enable gpu from command line, do you get enter password?

**Comment by giorgos-apo** [comment]
@balchua no I don't. I can enable it easily without password.
