### ISSUE TITLE
hostpath-provisioner unable to connect to the api server 

### ISSUE THREAD

**Issue by JackDallas** [ubuntu/microk8s#939]
Hi all,
I'm having an issue with connectivity to the api-server service 
when getting the logs from the hostpath-provisioner I get  
`F0129 13:31:20.298460       1 hostpath-provisioner.go:162] Error getting server version: Get https://10.152.183.1:443/version: dial tcp 10.152.183.1:443: connect: connection refused`
and on `kubectl get all` I get 
```
NAMESPACE     NAME                                                  READY   STATUS             RESTARTS   AGE
default       pod/default-http-backend-5d5ff5d4f5-46t42             1/1     Running            2          25h
default       pod/nginx-ingress-microk8s-controller-sz8tj           1/1     Running            460        25h
kube-system   pod/coredns-f7867546d-txnxc                           0/1     Running            2          25h
kube-system   pod/heapster-v1.5.2-6b794f77c8-jtf2n                  4/4     Running            8          25h
kube-system   pod/hostpath-provisioner-65cfd8595b-w86c6             0/1     CrashLoopBackOff   313        25h
kube-system   pod/kubernetes-dashboard-7d75c474bb-9x8d2             0/1     CrashLoopBackOff   315        25h
kube-system   pod/metrics-server-v0.2.1-7f6776db7-lgg8p             1/2     CrashLoopBackOff   316        25h
```

`microk8s.inspect` says everything is running, the tarball is attached
[inspection-report-20200129_133100.tar.gz](https://github.com/ubuntu/microk8s/files/4128261/inspection-report-20200129_133100.tar.gz)

Thanks in advanced for any help :)

**Comment by JackDallas** [comment]
[inspection-report-20200129_135541.tar.gz](https://github.com/ubuntu/microk8s/files/4128380/inspection-report-20200129_135541.tar.gz)
Second inspection report after upgrading to 1.17

**Comment by balchua** [comment]
@JackDallas i can see that your machine name has capital letters.  There is a reported issue https://github.com/ubuntu/microk8s/issues/902 that depicts it.
For the meantime, will it be possible to change the machine name to all small letters? And then try to reinstall microk8s?
Like `sudo snap remove microk8s` and then install it back?

**Comment by ktsakalozos** [comment]
Where did you spot the machine name @balchua? I missed that. Do you think the `--hostname-override` argument in kubelet would be of any help?

**Comment by JackDallas** [comment]
Hey @balchua, yesterday I decided just to wipe the machine and re-install ubuntu 18.04 on it, after doing so it worked perfectly, however the machine name is the same as it was before with capitals ...

**Comment by balchua** [comment]
@ktsakalozos in the controller logs it starts with GPU... But as @JackDallas mentioned, he reinstalled it clean slate and it seems to be working even with big case.

**Comment by JackDallas** [comment]
```
cluster@GPU-Cluster:~$ hostname
GPU-Cluster
```
Yeah the new hostname is the same, I'd be happy to upload another inspect log if it could help towards working out this if more people hit the same problem

**Comment by balchua** [comment]
Thanks @JackDallas do you have rbac enabled?

**Comment by ktsakalozos** [comment]
@JackDallas would it me possible to attach the current output of `iptables -L` ? thanks

**Comment by JackDallas** [comment]
Sure thing, here's both 
[iptables.txt](https://github.com/ubuntu/microk8s/files/4133699/iptables.txt)
[inspection-report-20200130_111339.tar.gz](https://github.com/ubuntu/microk8s/files/4133700/inspection-report-20200130_111339.tar.gz)

**Comment by JackDallas** [comment]
> Thanks @JackDallas do you have rbac enabled?
No, rbac is disabled

**Comment by JackDallas** [comment]
I'm gonna close this, it's all still here for history's sake but after a complete re-install of the machine it was working perfectly and I haven't re-produced it since
