### ISSUE TITLE
1.17/stable enable kubeflow failed at juju

### ISSUE THREAD

**Issue by andrewcheny** [ubuntu/microk8s#943]
[inspection-report-20200131_153204.tar.gz](https://github.com/ubuntu/microk8s/files/4141322/inspection-report-20200131_153204.tar.gz)

Command '('microk8s-juju.wrapper', 'bootstrap', 'microk8s', 'uk8s')' returned non-zero exit status 2
Failed to enable kubeflow

**Comment by pgronau** [comment]
I have experienced the same bug.
```
microk8s.disable kubeflow
microk8s.enable kubeflow
```
solved it for me if I remember correctly.

**Comment by andrewcheny** [comment]
Got this error message. Any idea what it means?

Command '('microk8s-juju.wrapper', 'bootstrap', 'microk8s', 'uk8s')' returned non-zero exit status 2
Failed to enable kubeflow

**Comment by andrewcheny** [comment]
Tried:

microk8s.juju status --debug
Juju is not available for arm64

So I would assume Kubeflow is not going to work on arm64. Am I correct?

**Comment by ktsakalozos** [comment]
> So I would assume Kubeflow is not going to work on arm64. Am I correct?

Yes @andrewcheny you are right. Sorry about that we have to add a check for this at the very beginning and print the right message.
