### ISSUE TITLE
microk8s containerd does not support registry options "ca_file" or "insecure_skip_verify"

### ISSUE THREAD

**Issue by candlerb** [ubuntu/microk8s#947]
microk8s current snap (1109, Ubuntu 18.04) contains an old version of containerd released on 12 March 2019.

```
ubuntu@ar1:~$ /snap/microk8s/1109/bin/containerd --version
containerd github.com/containerd/containerd v1.2.5 bb71b10fd8f58240ca47fbb579b9d1028eea7c84
```

This means it does not have recent features needed to communicate with a private registry using a custom CA:

* `ca_file` added on [3 May 2019](https://github.com/containerd/cri/commit/60a58af376f35a05f6ac50ab24c8775c5ea64566); or
* `insecure_skip_verify` added on [26 November 2019](https://github.com/containerd/cri/commit/ab6701bd1139cc3cb8d0ca35ba2bfb92e8ad7f74)

e.g. the following has no effect:

```
[plugins.cri.registry.configs."foo.example.net:5000".tls]
  ca_file   = "/etc/foo.example.net.pem"
```

**Comment by candlerb** [comment]
I found #702 had updated containerd to 1.3.0 (in snap edge) - however that was rolled back in #813

**Comment by balchua** [comment]
@candlerb there's already a PR to upgrade containerd to 1.3+.  https://github.com/ubuntu/microk8s/pull/838
This will also involve significant change on the configuration (version 2) format.

The target as of now is to land this along with 1.18 release.

**Comment by candlerb** [comment]
Thanks.  Closing this in favour of #838.
