### ISSUE TITLE
Windows installer can't install Multipass

### ISSUE THREAD

**Issue by joedborg** [ubuntu/microk8s#952]
```
Support for 'multipass' needs to be set up. Would you like to do that it now? [y/N]: y
Failed to download Multipass: 'an updated version is available that snapcraft does not yet know about'
Please install manually. You can find the latest release at:
https://multipass.run
```

**Comment by ktsakalozos** [comment]
This comes from here: https://github.com/ubuntu/microk8s/blob/feature/jdb/installer/installer/vm_providers/_multipass/_windows.py#L162

We will have to keep up with the multipass releases :( (and clean up the error messages we got from snapcraft)

**Comment by joedborg** [comment]
@ktsakalozos This might be an issue as the latest are not, seemingly, Windows compatible:

https://github.com/canonical/multipass/releases/tag/v1.0.2

**Comment by ktsakalozos** [comment]
Closing this since I see in your work Multipass installation is working now. Thanks.
