### ISSUE TITLE
Readiness probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by felipecruz91** [ubuntu/microk8s#954]
Hi,

When enabling Linkerd2 with `microk8s.enable linkerd` I see that some Pods take lot of time to be up and running due to the following message:

`Warning  Unhealthy  35s (x10 over 2m5s)  kubelet, microk8s  Readiness probe failed: HTTP probe failed with statuscode: 503 `

When doing `microk8s.linkerd check` it results in:

```
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
× [prometheus] control plane can talk to Prometheus
    Error calling Prometheus from the control plane: server_error: server error: 503
    see https://linkerd.io/checks/#l5d-api-control-api for hints
```

**Comment by balchua** [comment]
Is it possible to do a `microk8s.inspect` and upload the tarball?
And what is the output of `kubectl get pods --all-namespaces -o wide` looks like?
Thanks.
