### ISSUE TITLE
ClusterIP appears to do source NAT, contradicting official Kubernetes docs

### ISSUE THREAD

**Issue by rjw245** [ubuntu/microk8s#956]
I am trying to preserve the source IP of incoming requests to a clusterIP service, but I find that the requests appear to be source NAT'd. That is, they carry the IP address of the node as the source IP rather than the IP of the pod who made the request. I am following the example for cluster IPs here: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-clusterip
but I find that the behavior of Kubernetes is totally different for me.

The above example has me deploy an echo server which reports the source IP. This is deployed behind a clusterIP service which I request from a separate pod running busybox. The response from the echo server is below:

```
CLIENT VALUES:
client_address=10.1.36.1
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://10.152.183.99:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
connection=close
host=10.152.183.99
user-agent=Wget
BODY
```

The source IP 10.1.36.1 belongs to the node. I expected to see the address of busybox which is 10.1.36.168.

Does anyone know why SNAT would be enabled for a clusterIP? It's really strange to me that this directly contradicts the official documentation.

all of this is running on the same node
the node is running in iptables mode
I am using microk8s
microk8s.ctr version:
```
Client:
  Version:  v1.2.5
  Revision: bb71b10fd8f58240ca47fbb579b9d1028eea7c84

Server:
  Version:  v1.2.5
  Revision: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
```

microk8s.kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

Inspection report:
[inspection-report-20200210_114831.tar.gz](https://github.com/ubuntu/microk8s/files/4182533/inspection-report-20200210_114831.tar.gz)

**Comment by rjw245** [comment]
@ktsakalozos

**Comment by peix2** [comment]
I'm joining to this one. I'm facing issue with multi node Microk8s with flannel SNATing packets between pods running on different nodes.
Issue described here: https://discuss.kubernetes.io/t/microk8s-and-flannel-different-source-address/10618

**Comment by adamyi** [comment]
I'm running into the same issue on v1.18.2

**Comment by adamyi** [comment]
This seems to be the same issue as https://github.com/ubuntu/microk8s/issues/1139 and is fixed in the latest HEAD.
