### ISSUE TITLE
Pod metrics are not available

### ISSUE THREAD

**Issue by ghys** [ubuntu/microk8s#96]
After installing heapster with `microk8s.enable dashboard` only the metrics from the node are available in Grafana and as an output of `microk8s.kubectl top` like:
```
$ microk8s.kubectl top node
NAME       CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%
microk8s   89m          8%        1237Mi          42%
```
However the pod metrics are not available:
```
$ microk8s.kubectl top pod -n kube-system
W0825 05:49:24.131657   10654 top_pod.go:263] Metrics not available for pod kube-system/heapster-v1.5.2-577898ddbf-wzq4w, age: 4m8.131641237s
error: Metrics not available for pod kube-system/heapster-v1.5.2-577898ddbf-wzq4w, age: 4m8.131641237s
```
You also don't get the per-pod CPU and memory graphs in the dashboard.

I think I've tracked it down to the summary API having an empty `"pods"` array:
```
$ curl http://localhost:10255/stats/summary
{
  "node": {
...
   }
  },
  "pods": []
 }
```
I haven't been able to figure out why - can't find anything of relevance on the kubelet service logs. This is reproducible on a fresh microk8s install. Any help would be appreciated, thanks!

**Comment by ktsakalozos** [comment]
We know we have a gap in respect to metrics. We do not ship the [metrics server](  https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/). Could this be related?

**Comment by ghys** [comment]
I actually found the problem: the cadvisor included in kubelet listens to the Docker socket at the default location (`/var/run/docker.sock`) to get container metrics.
The standalone instance has a option to change it (https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#docker) but I haven't found a way to change it in the kubelet options.
I managed to get the metrics with a (very) dirty hack:
`ln -s /var/snap/microk8s/current/docker.sock /var/run/docker.sock` 😕 
Of course this supposes you don't have a standalone docker installed.

**Comment by ktsakalozos** [comment]
Thank you so much for debugging this!

There is a configuration argument for kubelet that goes by the name `--docker`. Here is what you have to do to add it.

Edit `/var/snap/microk8s/current/args/kubelet` and append this line
```
--docker unix://${SNAP_DATA}/docker.sock
```
Save the file and restart kubelet with:
```
sudo systemctl restart snap.microk8s.daemon-kubelet
```
I see the metrics for pods flowing in now.

It was my fault I missed the `--docker` option because there is also the `--docker-endpoint`. Right now my kubelet args file looks like this:
```
> sudo cat /var/snap/microk8s/current/args/kubelet 
--kubeconfig=${SNAP}/configs/kubelet.config
--cert-dir=${SNAP_DATA}
--network-plugin=kubenet
--root-dir=${SNAP_COMMON}
--docker-root=${SNAP_COMMON}/var/lib/docker
--fail-swap-on=false
--pod-cidr=10.1.1.0/24
--non-masquerade-cidr=10.152.183.0/24
--cni-bin-dir=${SNAP}/opt/cni/bin/
--docker unix://${SNAP_DATA}/docker.sock
--docker-endpoint unix://${SNAP_DATA}/docker.sock
--feature-gates=DevicePlugins=true
--eviction-hard="memory.available<500Mi,nodefs.available<1Gi,imagefs.available<1Gi"
--cluster-domain=cluster.local
--cluster-dns=10.152.183.10
--allow-privileged=true
```

The fix is appending this single line in this file: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kubelet . @ghys  do you want to submit a PR? You deserve it.

Thank you again

**Comment by ghys** [comment]
Oh so it was simply `--docker` 😄 

> @ghys do you want to submit a PR?

Sure - thanks!
