### ISSUE TITLE
Unable to delete  Pod, hang in Terminating state

### ISSUE THREAD

**Issue by dapeng09** [ubuntu/microk8s#967]
Please run `microk8s.inspect` and attach the generated tarball to this issue.

[inspection-report-20200215_230654.tar.gz](https://github.com/ubuntu/microk8s/files/4208628/inspection-report-20200215_230654.tar.gz)

We appreciate your feedback. Thank you for using microk8s.

I just run below command to test if I install microk8s successfully
`kc run nginx --image nginx`

then I run
`kc delete deploy nginx`

after this, I can see the Pod hung in 'Terminating' state.

```
kc get all
NAME                         READY   STATUS        RESTARTS   AGE
pod/nginx-6db489d4b7-lp5fz   1/1     Terminating   0          83m
```
And even microk8s.reset hangs due to this

![Snipaste_2020-02-16_13-53-04](https://user-images.githubusercontent.com/4626700/74599862-cc05d300-50c3-11ea-9aac-a89667483d07.png)

Can anyone help me delete this?
Thanks in advance

**Comment by balchua** [comment]
Hi @dapeng09 the inspect tarball shows that the nginx pod is in ready state.  

Can you still describe the pod? `kubectl describe po nginx-6db489d4b7-lp5fz`

**Comment by dapeng09** [comment]
Hi balchua, please see below

`kc describe pod nginx-6db489d4b7-lp5fz`

kc describe pod nginx-6db489d4b7-lp5fz
Name:                      nginx-6db489d4b7-lp5fz
Namespace:                 default
Priority:                  0
Node:                      microk8s-1d5872730/10.41.137.39
Start Time:                Sat, 15 Feb 2020 21:51:59 +0800
Labels:                    pod-template-hash=6db489d4b7
                           run=nginx
Annotations:               <none>
Status:                    Terminating (lasts 15h)
Termination Grace Period:  1s
IP:                        10.1.65.3
IPs:
  IP:           10.1.65.3
Controlled By:  ReplicaSet/nginx-6db489d4b7
Containers:
  nginx:
    Container ID:   containerd://3a1fe911de72ca20a5ec331a1587f5731d6b252777f9feffb2db594fe34dfabf
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:ad5552c786f128e389a0263104ae39f3d3c7895579d45ae716f528185b36bc6f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sat, 15 Feb 2020 21:53:42 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-flgt7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-flgt7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-flgt7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by balchua** [comment]
@dapeng09 i checked the list of processes running, and i dont see nginx.  
If you try with `kubectl delete pod <pod name> --grace-period 0 --force` does it remove the pod?
If yes, after that, can you easily reproduce it?
Thanks

**Comment by dapeng09** [comment]
@balchua It worked! And it's currently not reproducing it. Many thanks, I am closing this issue.
