### ISSUE TITLE
How to keep from automatically starting?

### ISSUE THREAD

**Issue by pentatronix** [ubuntu/microk8s#972]
Hi, I am not heavily using Microk8s, and so I don't need it running by default.  Is there a way start the OS (Ubuntu 18.04lts) with Microk8s stopped, then start it when I need it?
Otherwise it resource hogs my machine and causes crashes.

**Comment by ktsakalozos** [comment]
If you do a `microk8s.stop` MicroK8s should stay stopped throughout reboots. you can start it again with `microk8s.start`. If this is not the case please attach the `microk8s.inspect` tarball as this would be a bug. Thank you.
