### ISSUE TITLE
raspberry pi 4 - ubuntu 19.10 - microk8s.start DOES NOT RUN

### ISSUE THREAD

**Issue by uberknot** [ubuntu/microk8s#973]
ubuntu@ubuntu:~$ microk8s.status
microk8s is not running. Use microk8s.inspect for a deeper inspection.

ubuntu@ubuntu:~$ microk8s.inspect
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-flanneld is running
  Service snap.microk8s.daemon-containerd is running
  Service snap.microk8s.daemon-apiserver is running
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1174/inspection-report-20200223_163946.tar.gz

Although all services seem to report running, status indicates otherwise. 

Thanks in advance

**Comment by uberknot** [comment]
Inspection report uploaded.

[inspection-report-20200223_163946.tar.gz](https://github.com/ubuntu/microk8s/files/4242497/inspection-report-20200223_163946.tar.gz)

**Comment by ktsakalozos** [comment]
Hi @uberknot 

Could you go over the instructions at https://microk8s.io/docs/install-alternatives#arm to make sure cgroups are properly enabled? I see in your `journalctl -u snap.microk8s.daemon-kubelet` this error:
` failed to get the kubelet's cgroup: mountpoint for memory not found.  Kubelet system container metrics may be missing.`

**Comment by uberknot** [comment]
@ktsakalozos I did try with and without the modification to the nobtcmd.txt. In either case, it didn't report running. Attached is a new inspection report with the nobtcmd.txt having been modified per install alternatives instructions. 
[inspection-report-20200225_014913.tar.gz](https://github.com/ubuntu/microk8s/files/4247811/inspection-report-20200225_014913.tar.gz)

Thanks

**Comment by ktsakalozos** [comment]
Could you share the contents of `/proc/cgroups`?

Also how does your `/boot/firmware/nobtcmd.txt` look like?
￼

**Comment by uberknot** [comment]
@ktsakalozos Will do as you ask tomorrow evening. Thank you.

**Comment by uberknot** [comment]
@ktsakalozos Contents of /boot/firmware/nobtcmd.txt
net.ifnames=0 dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=memory cgroup_memory=1

**Comment by uberknot** [comment]
@ktsakalozos Contents of /proc/cgroups

#subsys_name    hierarchy       num_cgroups     enabled
cpuset  6       14      1
cpu     8       14      1
cpuacct 8       14      1
blkio   7       14      1
memory  9       146     1
devices 11      75      1
freezer 5       15      1
net_cls 4       14      1
perf_event      2       14      1
net_prio        4       14      1
pids    3       82      1
rdma    10      1       1

**Comment by ktsakalozos** [comment]
Looks ok. I do not understand why kubelet reports this: `Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]`.

Could you attach a fresh `microk8s.inspect` tarball?

**Comment by uberknot** [comment]
@ktsakalozos Although the example app in the docs keeps restarting, it looks like microk8s has started. Don't understand why it would at this point. I followed the instructions with a fresh install of ubuntu twice and had the same results. Restarted the OS several times, stop and started microk8s many times. I'm puzzled. Only other thing I can metion is over the last couple of days I did updates and installed the kubuntu GUI. 

I suppose there's no point in sending another tarball. Please let me know if you still want it. Otherwise, I'm moving onto figuring out why the example app fails to start.

**Comment by ktsakalozos** [comment]
I do not need another tarball.

> I'll walk thru another OS and microk8s install to see if the issue arises again and report my findings here.

That would be great, note that the most well tested OSes are Ubuntu Xenial (16.04) and Bionic (18.04).

Thank you

**Comment by uberknot** [comment]
@ktsakalozos Installed new ubuntu image and microk8s, restarted and waited a little while before checking status and it was running! I suppose we can chalk this up to user error and is not an issue. Thank you so much for the fast responses and assistance.
