### ISSUE TITLE
microk8s.enable juju fails on curl step on Centos7

### ISSUE THREAD

**Issue by dliebsterwb** [ubuntu/microk8s#975]
Hello, 

'microk8s.enable juju' fails to pull juju-2.7.0-centos7.tar.gz from typepad.net with curl error 77. Centos 7's native curl pulls the file ok, there seems to be an issue using the snap's version of curl:

`#  /var/lib/snapd/snap/microk8s/1176/usr/bin/curl -L https://launchpad.net/juju/2.7/2.7.0/+download/juju-2.7.0-centos7.tar.gz -o /root/1176/tmp/juju.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) Problem with the SSL CA cert (path? access rights?)

[root@centos7 ~]# /bin/curl -L https://launchpad.net/juju/2.7/2.7.0/+download/juju-2.7.0-centos7.tar.gz -o /root/1176/tmp/juju.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  116M  100  116M    0     0  1239k      0  0:01:36  0:01:36 --:--:--  943k
[root@centos7 ~]# uname -a
Linux centos7.localdomain 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@centos7 ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
`

So far I've yum installed ca-certificates based on another post, microk8s.enable juju still still with the came curl error.   Would there be any unexpected microk8s management issues if the enable.juju.sh script is run manually outside of microk8s.enable? 

Thanks!
-Dan
[inspection-report-20200224_171509.tar.gz](https://github.com/ubuntu/microk8s/files/4245845/inspection-report-20200224_171509.tar.gz)
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by knkski** [comment]
@dliebsterwb: There won't be any issues if you manually download the Juju binary and place it at `/var/snap/microk8s/current/bin/juju`. The step that downloads Juju just checks for the existence of that binary, and skips downloading it if it's already there.

**Comment by sphinks** [comment]
@knkski I have the same issue, and I have downloaded juju.tar.gz, unpack it and moved juju file into folder that you have mentioned - get new issue:

```microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling rbac...
Enabling juju...
Deploying Kubeflow...
Kubeflow could not be enabled:
ERROR cannot load ssh client keys: mkdir /var/snap/microk8s/1222/juju: permission denied```

**Comment by knkski** [comment]
@sphinks: Can you paste the output from `ls -lah /var/snap/microk8s/current/juju`?

**Comment by sphinks** [comment]
Nothing, there is no such folder. I just picked up juju file from tar and put it into `current/bin`. Should I put whole unpacked folder in `current/`?

**Comment by knkski** [comment]
@sphinks: You'll need to run the commands found here:

https://github.com/ubuntu/microk8s/blob/050e98b/snap/hooks/configure#L380-L382
https://github.com/ubuntu/microk8s/blob/050e98b/snap/hooks/configure#L386

Where `$SNAP_DATA` is `/var/snap/microk8s/current`

Additionally, #989 will fix this issue generally, as it just includes the juju binary in the snap, instead of downloading it after snap install.

**Comment by sphinks** [comment]
@knkski looks like we do not need manual download. It can be done with 
`snap install juju --classic`. But next that will be new issue:
```microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling rbac...
Enabling juju...
Deploying Kubeflow...
Kubeflow could not be enabled:
ERROR connection is shut down

Command '('microk8s-juju.wrapper', 'add-model', 'kubeflow', 'microk8s')' returned non-zero exit status 1
Failed to enable kubeflow
```

**Comment by sphinks** [comment]
I manage to resolve issue with manual executing commands, but get some new strange thing:
```
microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling rbac...
Enabling juju...
Kubeflow has already been enabled.
Failed to enable kubeflow
```

I try to stop/start microk8s, disable/enable kubeflow... Microk8s hurts me.

**Comment by knkski** [comment]
@sphinks: When it hangs, does it eventually complete and print any output, or does it never complete? Are you able to run `microk8s.juju --debug show-controller uk8s` manually?

**Comment by sphinks** [comment]
@knkski output that I have posted above shows all input I get. Process hangs at `Running microk8s-juju.wrapper --debug show-controller uk8s` but then finished with:
```
KUBEFLOW_DEBUG=true microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling rbac...
Enabling juju...
Running `microk8s-juju.wrapper --debug show-controller uk8s`
Kubeflow has already been enabled.
Failed to enable kubeflow
```
Yes, manual run of `microk8s.juju --debug show-controller uk8s` looks ok.
```
microk8s.juju --debug show-controller uk8s
15:11:41 INFO  juju.cmd supercommand.go:83 running juju [2.7.3 9da5b593fa1d096220230143f1e1fea5c4eb56ad gc go1.12.17]
15:11:41 DEBUG juju.cmd supercommand.go:84   args: []string{"/snap/microk8s/1245/bin/juju", "--debug", "show-controller", "uk8s"}
15:11:41 INFO  juju.juju api.go:67 connecting to API addresses: [10.152.183.126:17070]
```

**Comment by knkski** [comment]
@sphinks: You'll need to disable kubeflow before enabling it again. The main way would be `microk8s.disable kubeflow`, though you might have to do `sudo snap remove microk8s && sudo snap install microk8s --classic` if you've done any manual twiddling to get around the main issue.

**Comment by knkski** [comment]
Closing this issue, since microk8s now comes packaged with the juju binary, and doesn't need to download it.
