### ISSUE TITLE
Enabling RBAC addon: storage/dns addon doesn't work

### ISSUE THREAD

**Issue by davigar15** [ubuntu/microk8s#977]
Steps to reproduce it:
microk8s.enable rbac
microk8s.enable storage dns
Logs I see in CoreDNS and storage pods: https://pastebin.canonical.com/p/x8Cptr79ZT/
[inspection-report-20200225_095832.zip](https://github.com/ubuntu/microk8s/files/4249469/inspection-report-20200225_095832.zip)
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

**Comment by davigar15** [comment]
I had "Canonical" as my hostname machine.

I changed it to "canonical", and it works

**Comment by balchua** [comment]
@davigar15 thanks for providing the fix.  We've seen this a couple of times.  Let's see what we can do with such setup.
