### ISSUE TITLE
Install Microk8s without Snap

### ISSUE THREAD

**Issue by RAbraham** [ubuntu/microk8s#988]
Hi,

We love microk8s but we have to use it in an offline setting. We have tried the offline snap install but it still reaches out to the network for microk8s and hence does not get installed.

We tried just copying the binaries installed by snap but that didn't work either as they depend on snap.

Are there any directions on how to create the microk8s binaries and start and stop them without any snap dependency?

**Comment by balchua** [comment]
I've never installed snaps on air gapped settings.  I guess you tried this one
https://forum.snapcraft.io/t/offline-snap-installers-and-possibility-to-update/275/2

**Comment by RAbraham** [comment]
@balchua thanks for your reply. Yes, I tried that and it will still try to access the internet :(

**Comment by balchua** [comment]
Which os are you using? Centos? Perhaps you also need to download and install `core` or `core18` before installing microk8s snap.

**Comment by RAbraham** [comment]
I'm using ubuntu 18.04. I tried that too :( (core or core18).

**Comment by balchua** [comment]
Can you paste the logs here?

**Comment by ktsakalozos** [comment]
@RAbraham you will probably need to download the core snap.

```
snap download core --channel=stable
snap download microk8s --channel=stable
rm *.assert
```

For charmed kubernetes we have the script at [1] that handles among others the snap installation in air gaped installations.

[1]  https://github.com/charmed-kubernetes/cdk-shrinkwrap/blob/master/shrinkwrap.py

**Comment by RAbraham** [comment]
I'm very sorry @balchua . I think I did something different. https://askubuntu.com/questions/1209847/18-04-cant-install-docker-in-offline-mode-using-snap

Let me try out @ktsakalozos's solution and come back. Thank you so much both of you :).

**Comment by RAbraham** [comment]
@ktsakalozos I tried this.
```
ubuntu@microk8s:~$ mkdir snap_download
ubuntu@microk8s:~$ cd snap_download/
ubuntu@microk8s:~/snap_download$ snap download core --channel=stable
Fetching snap "core"
Fetching assertions for "core"
Install the snap with:
   snap ack core_8689.assert
   snap install core_8689.snap
ubuntu@microk8s:~/snap_download$ ls
core_8689.assert  core_8689.snap
ubuntu@microk8s:~/snap_download$ snap download microk8s --channel=stable
Fetching snap "microk8s"
Fetching assertions for "microk8s"
Install the snap with:
   snap ack microk8s_1214.assert
   snap install microk8s_1214.snap
ubuntu@microk8s:~/snap_download$ ls
core_8689.assert  core_8689.snap  microk8s_1214.assert  microk8s_1214.snap
ubuntu@microk8s:~/snap_download$ rm ./*.assert
ubuntu@microk8s:~/snap_download$ ls
core_8689.snap  microk8s_1214.snap

# Turn of Wifi
ubuntu@microk8s:~/snap_download$ sudo snap install core_8689.snap
error: cannot find signatures with metadata for snap "core_8689.snap"
```

**Comment by RAbraham** [comment]
This worked.
```
ubuntu@microk8s:~/snap_download$ sudo snap ack core_8689.assert
ubuntu@microk8s:~/snap_download$ sudo snap install core_8689.snap

2020-03-03T12:21:59-05:00 INFO Waiting for restart...
core 16-2.43.3 from Canonical✓ installed
ubuntu@microk8s:~/snap_download$ sudo snap ack microk8s_1214.assert
ubuntu@microk8s:~/snap_download$ sudo snap install microk8s_1214.snap --classic
microk8s v1.17.3 from Canonical✓ installed 
```

Thank you @balchua and @ktsakalozos  for your guidance!

**Comment by RawSanj** [comment]
Is there a way to install microk8s without using snap at all?
I wanted to install microk8s in WSL2, there's a lengthy blog that explains how to do that but after several tries and errors I gave up. So I was wondering if there is some easier way to this on WSL2.

**Comment by ktsakalozos** [comment]
> Is there a way to install microk8s without using snap at all?

I am sorry there is no way to install MicroK8s without snapd.

**Comment by Ruakij** [comment]
I would love to install mikroK8s without snap aswell..
Guess i wont use mikroK8s then at all.

How can a publisher only publish on his own platform one might not like to use? Guess to force everyone to use it..

**Comment by PAStheLoD** [comment]
@Ruakij ... or to simplify maintenance, development, deployment, etc. I'm not saying snap is the best thing since hot water, but for microk8s it kind of just works, so who cares? 🤷 For local development on k8s there are a ton of other platfroms. (Minikube being the default, or kind, or skaffold, or k0s, k3s, k1s .. no that's a dashboard. Anyway.)

That said, it'd be great to be able to understand how microk8s is derived from upstream k8s, where the snap-ification starts and where it ends :D

**Comment by javad87** [comment]
the problem is snap daemon is running on Centos7 (systemctl status snapd -l) but it gives the error: "trying to compare the snap system key: system-key missing on disk"

and when checking snap version it says it is unavailable:

snap    2.53.4-1.el7
snapd   unavailable
series  -

**Comment by spectrapulse** [comment]
It's kind of sad that this is the way Canonical would like to force people to use snaps. What if I just dont want to have unnessesary loop devices or yet another pointless package manager with its own way of dealing with dependencies. It's just additional annoyances which I find sad that people would have to deal with just to use mk8s.

Guess I'll be looking for another single-node production solution using k8s. Recommendations are welcome.

**Comment by jkinred** [comment]
Another disappointed team that will avoid tools only provided via snap.

My team are professional, long term and significant users of LXD and therefore snap. It is universally disliked and we are actively seeking alternatives.

The obsession with snap is disturbing.

**Comment by bithavoc** [comment]
What a waste of a MOTD message:

- Installation instructions: `snap ...`
- "No thanks..."

**Comment by nlhnt** [comment]
This thread is like youtube comments. I got nothing against snap, but it is hard to install on anything other than Ubuntu, especially if you're working on an "air gapped" machine.  
I understand this is not a snap repository, but installing snap in air gapped environments is difficult, there's no good documentation on how to do that.  
I started working on a solution for my employer using microk8s, but now I'll have to switch to k3s because they at least explicitly state that I'll need to mirror the docker images adn set up some configuration files to do an offline install. Even helm/helm3 can be modified like that.  
Snap is an unknown land in such a scenario and I am not willing to put in the hours that should be spent on getting results to debug "open source" product like snap.  
I think snap is great for userland applications, but seriously forcing it on professionals who try to provide architecture for really big companies is a shady move.

**Comment by neoaggelos** [comment]
Hi @nlhnt, sad to see that MicroK8s does not fit your use case, and thanks for sharing some constructive feedback.

> Windows and macOS installs don't use snap, they use multipass and homebrew, so this is just politics.

Given that WSL now supports systemd natively, keep in mind we are working to improve this on the Windows side.

> I understand this is not a snap repository, but installing snap in air gapped environments is difficult, there's no good documentation on how to do that.

Thanks, airgap installations are a use case that we target with MicroK8s, and it is good to know that this is a friction point.

All in all, thanks for this feedback. Know that this will reach the right people, and action will be taken to improve on it :pray:

**Comment by bhlevca** [comment]
> microk8s looks like a good tool, but as long as it requires snap, I'm not touching it or recommending it to anyone; stick to minikube, kind or any other alternative.

Good idea, I am also using minikube.  I will never touch anything that requires snap. Snap is a resource hog and a poorly implemented technology.  I prefer appimage or even flatpak, which is ligher on your resources.  Snapd - NEVER!

**Comment by kaimast** [comment]
I'm trying to install microk8s on multiple machines using a script that invokes SSH.

snap will rewrite the console output on the same line which garbles the output on the invoking machine. For apt there is apt-get that provides are more script-friendly output.
Is there something similar for snap? Currently, I just forward all of snap's output to /dev/null, which is the only way to fix this it seems.

**Comment by neoaggelos** [comment]
@kaimast though not particularly related to the original issue, indeed `> /dev/null` is the easiest way to go for this.

**Comment by OnceUponALoop** [comment]
To chime in on this. We were recently evaluating tooling for local k8 and the instant feedback from seeing "install with snap" was to dump microk8s as an option. It's a shame to tie a good product to a "dead horse technology".

**Comment by notbasetwo** [comment]
I'm chiming in on this whilst I'm admittedly in a bit of a foul mood - but I literally don't know a single soul who wants to install stuff like this with Snap, particularly on a server (which is pushed by Ubuntu installer).

Worst part is, you have to use classic mode - basically defeating most of the point anyway. 

Just immediately makes microk8s a non starter for me.

**Comment by misaya98** [comment]
now is 2025, any way to Install Microk8s without Snap ?
